package.json, packages/loopback/lib/router/SwaggerRouter.ts
Hey All, "npm test" was failing, I got it working after some fixes. Had to make a change in SwaggerRouter.ts and added some test related dependencies in package.json.
Please take a look, and merge, if everything looks ok to you.
=> Fixing issue #153 (failing tests)

packages/loopback/lib/router/SwaggerRouter.ts, packages/loopback/package.json, packages/loopback/test/integration/router/SwaggerRouter.integration.ts
Connect to #99
The code is not as pretty and clean as I would like it to be. My plan is to land this enhancement now, and then refactor the router to take other requirements into account too (like the DI/IoC approach we are discussing).
=> Add more parameter sources: header, formData, body

.travis.yml
=> Enable Travis CI builds

.travis.yml
=> Run lerna via npm on Travis

README.md
Fixes https://github.com/strongloop/loopback-next/issues/168 PTAL
=> Fix installation steps in README

packages/loopback/test/acceptance/module-exporting/feature.md
=> Add acceptance test for @loopback/loopback export

packages/testlab/.npmignore, packages/testlab/package.json
=> Use whitelist for publishing in testlab

packages/testlab/.gitignore, packages/testlab/package.json, packages/testlab/test/testlab.smoke.js
=> Add ES2015 compilation for testlab

packages/testlab/package.json
=> Update testlab to 4.0.0-alpha.2

packages/authentication/package.json, packages/context/package.json, packages/example-codehub/package.json, packages/loopback/package.json
=> Use testlab 4.0.0-alpha.2 in all packages

packages/example-codehub/package.json
=> Mark CodeHub as private

packages/context/package.json, packages/core/package.json, packages/core/test/integration/router/SwaggerRouter.integration.ts, packages/core/test/unit/application/application.controller.test.ts, packages/example-codehub/package.json, packages/openapi-spec-builder/package.json, packages/openapi-spec/package.json
=> Fix broken tests from prepublishing

package.json
cc @bajtos @raymondfeng @ritch @superkhau Following discussions on https://github.com/strongloop/loopback-next/pull/251#issuecomment-299046532. This fixes https://github.com/strongloop/loopback-next/issues/164 and added a lint:fix task to automatically try and fix lint issues
=> Fixing tests for windows and added lint:fix task

packages/context/package.json, packages/context/tsconfig.json, packages/core/package.json, packages/core/tsconfig.json, packages/openapi-spec-builder/package.json, packages/openapi-spec-builder/tsconfig.json, packages/openapi-spec/package.json, packages/openapi-spec/tsconfig.json, packages/testlab/package.json, packages/testlab/tsconfig.json
Fixups for:
- https://github.com/strongloop/loopback-next/pull/253#discussion_r114733111
- https://github.com/strongloop/loopback-next/pull/253#discussion_r114733177
cc @bajtos
=> Prep for publishing fixups

appveyor.yml
This pull request depends on https://github.com/strongloop/loopback-next/issues/164 to fix `npm test` on Windows.
=> Enable AppVeyor CI

packages/context/package.json, packages/core/package.json, packages/openapi-spec-builder/package.json, packages/openapi-spec/package.json, packages/testlab/package.json
Connect to https://github.com/strongloop/loopback-next/pull/253#discussion_r115000494
* Use tree again
* Make each script clean up after itself after running tree
cc @bajtos
=> Refactor verify scripts

lerna.json
Connect to https://github.com/strongloop/loopback-next/issues/262
=> Use independent mode for Lerna publishing

lerna.json, package.json
=> Use Lerna 2.0.0-rc.4

packages/core/src/Sequence.ts, packages/core/src/invoke.ts, packages/core/src/router/SwaggerRouter.ts, packages/core/src/server.ts
* Decompose invoke from SwaggerRouter
* Clean up Server handler/request entrypoint to use Sequence
=> Use sequence in request/response lifecycle

packages/core/package.json, packages/core/test/unit/parser.test.ts, packages/testlab/package.json, packages/testlab/src/client.ts, packages/testlab/src/shot.ts, packages/testlab/src/testlab.ts
=> Add HTTP Request/Response mocks to testlab

packages/authentication/index.ts, packages/authentication/package.json, packages/authentication/src/index.ts, packages/authentication/src/strategy-adapter.ts, packages/authentication/test/unit/fixtures/mock-strategy.ts, packages/authentication/test/unit/strategy-adapter.test.ts, packages/core/index.ts, packages/core/package.json, packages/core/src/index.ts, packages/example-codehub/package.json, packages/example-codehub/src/controllers/UserController.ts
* create adapter for passport strategies
* create unit test for adapter
https://github.com/strongloop/loopback-next/issues/138
cc @raymondfeng
=> Implement passport strategies

packages/core/src/index.ts, packages/core/src/router/SwaggerRouter.ts, packages/core/src/router/routing-table.ts, packages/core/test/unit/routing-table.test.ts
=> Refactor route lookup into a standalone class

packages/authentication/package.json, packages/context/package.json, packages/core/package.json, packages/openapi-spec-builder/package.json, packages/openapi-spec/package.json, packages/testlab/package.json
=> Refactor clean NPM scripts

.travis.yml, package.json
* coverage:ci NPM script for CI output (with coveralls)
* coverage NPM script for local viewing
=> Split coverage NPM script

packages/core/test/integration/http-handler.integration.ts
=> Remove async from sync test

packages/core/src/http-handler.ts, packages/core/src/sequence.ts
=> Refactor decomposed router bindings

packages/core/src/application.ts, packages/core/src/http-handler.ts, packages/core/src/internal-types.ts, packages/core/src/sequence.ts, packages/core/test/acceptance/sequence/sequence.acceptance.ts, packages/core/test/integration/http-handler.integration.ts
=> WIP: instantiate Sequence via Context

packages/context/src/index.ts, packages/context/src/reflect.ts, packages/context/test/unit/reflect.ts
* Scope reflect context to a namespace
* Provide wrapper methods for reflect api
cc @raymondfeng
=> Namespaced Reflect wrapper class

packages/context/src/reflect.ts, packages/context/test/unit/reflect.ts
=> Only filter metadata key with namepspace prefix

packages/context/src/binding.ts, packages/context/src/index.ts, packages/context/src/provider.ts, packages/context/src/resolver.ts, packages/context/test/unit/binding.ts, packages/context/test/unit/provider.ts, packages/context/test/unit/resolver.test.ts
=> Provider interface

packages/repository/src/common-types.ts, packages/repository/src/crud-connector.ts, packages/repository/src/datasource.ts, packages/repository/src/decorators/model.ts, packages/repository/src/decorators/relation.ts, packages/repository/src/decorators/repository.ts, packages/repository/src/legacy-juggler-bridge.ts, packages/repository/src/loopback-datasource-juggler.ts, packages/repository/src/mixin.ts, packages/repository/src/model.ts, packages/repository/src/query.ts, packages/repository/src/types/any.ts, packages/repository/src/types/array.ts, packages/repository/src/types/boolean.ts, packages/repository/src/types/buffer.ts, packages/repository/src/types/date.ts, packages/repository/src/types/number.ts, packages/repository/src/types/string.ts, packages/repository/src/types/type.ts, packages/repository/src/types/union.ts, packages/repository/test/unit/decorator/repository.ts, packages/repository/test/unit/mixin/mixin.ts
A follow-up for #346 which requires #350 to be landed first.
=> Get rid of "type Any = any"

package.json
=> Add pretest script to ensure build is run before test

packages/core/src/application.ts, packages/core/test/acceptance/bootstrapping/application.acceptance.ts
* Rename AppConfig to ApplicationOptions
* Make components and sequence keys optional in ApplicationOptions
=> Use user defined sequence when provided

.vscode/tasks.json
1. Use relative scripts for commands
2. Rename juggler to repository
3. Add isShellCommmand
4. Fix mocha options
=> Fix/enhance tasks.json for vscode

packages/repository/src/decorators/repository.ts, packages/repository/test/unit/decorator/repository.ts
=> Add repo property injection

packages/context/src/index.ts, packages/context/src/inject.ts, packages/context/src/resolver.ts, packages/context/test/unit/inject.test.ts, packages/context/test/unit/resolver.test.ts
=> Add support for custom resolver with @inject

packages/context/src/inject.ts, packages/context/test/unit/inject.test.ts
=> Support DI with inheritance

.vscode/settings.json
* VS Code: 80 char ruler
* VS Code: Tab completion
=> Add useful VS Code workspace settings

packages/authentication/src/index.ts, packages/authentication/src/provider.ts, packages/authentication/src/strategy-adapter.ts, packages/authentication/test/unit/provider.test.ts, packages/authentication/test/unit/strategy-adapter.test.ts
=> AuthenticationProvider to inject authenticate() function into context

package.json, packages/context/src/is-promise.ts
=> Fix is promise

packages/authentication/docs.json, packages/context/docs.json, packages/core/docs.json, packages/openapi-spec-builder/docs.json, packages/openapi-spec/docs.json, packages/repository/docs.json
=> Added docs.json

packages/core/src/router/routing-table.ts, packages/openapi-spec-builder/src/openapi-spec-builder.ts, packages/openapi-spec/src/openapi-spec-v2.ts
=> Add API docs for openapi packages

packages/authentication/package.json, packages/authentication/test/acceptance/basic-auth.ts, packages/context/src/index.ts, packages/core/src/http-handler.ts, packages/core/src/index.ts, packages/core/src/internal-types.ts, packages/core/src/keys.ts, packages/core/test/unit/http-handler.ts
* Given app with a sequence
* Given app with a controller
* Given controller has basic authentication
* Add Test for basic authentication
=> Acceptance test for Basic Authentication

README.md
=> Add AppVeyor and Coveralls badges to README

package.json, packages/authentication/package.json, packages/context/package.json, packages/context/src/reflect.ts, packages/core/package.json, packages/example-codehub/package.json, packages/openapi-spec-builder/package.json, packages/openapi-spec/package.json, packages/repository/package.json, packages/repository/src/legacy-juggler-bridge.ts, packages/repository/src/repository.ts, packages/repository/test/unit/repository/legacy-juggler-bridge.ts, packages/testlab/package.json
Remove dev deps of typescirpt and mocha from packages
Fix type checks by ts 2.4.x
=> Upgrade to typescript 2.4.1

packages/context/src/is-promise.ts, packages/context/src/resolver.ts, packages/core/src/internal-types.ts, packages/core/src/router/routing-table.ts
- `isPromise<T>`
- `Constructor<T>`
- `OperationRetval`
- `parseRequestUrl`
=> Add more apidocs

packages/core/src/application.ts, packages/core/src/http-handler.ts, packages/core/src/index.ts, packages/core/src/sequence.ts, packages/core/test/acceptance/bootstrapping/application.acceptance.ts, packages/core/test/acceptance/sequence/sequence.acceptance.ts, packages/core/test/integration/http-handler.integration.ts
Additonally, rename `Sequence` to `DefaultSequence`.
Connect to #399
=> Add app.sequence() and app.handle() API

packages/core/src/application.ts, packages/core/test/acceptance/routing/routing.acceptance.ts, packages/openapi-spec-builder/src/openapi-spec-builder.ts
=> Add "app.api()" method for registering routes

README.md
I was approached by a person asking whether LoopBack Next is suitable for use in real-world applications. Apparently we are not advertising the alpha status anywhere in the project. This pull request is fixing that.
=> Describe the current status of the project

packages/core/src/application.ts, packages/core/src/parser.ts, packages/core/src/router/routing-table.ts, packages/core/src/writer.ts
I have reviewed TODO comments in loopback-next codebase and created issues for the important one. This pull requests enhances TODO comments with links to these GitHub issues.
Connect to strongloop-internal/scrum-asteroid#251
=> Link TODOs to GitHub issues

packages/openapi-spec-builder/README.md, packages/openapi-spec/README.md
=> Update docs for openapi

packages/context/README.md
=> Update Context Readme

packages/core/README.md
=> Update core docs

packages/authentication/README.md
=> Update authentication docs

packages/testlab/README.md
=> Update testlab docs

packages/repository/README.md
=> Update repository docs

packages/core/src/application.ts, packages/core/test/acceptance/routing/routing.acceptance.ts
Connect to #470 
Wiki will be updated once this PR is good to merge.
=> Update x-controller to x-controller-name

packages/core/src/application.ts, packages/core/src/http-handler.ts, packages/core/src/sequence.ts, packages/core/test/acceptance/sequence/sequence.acceptance.ts
=> Expose this.ctx in DefaultSequence

packages/authentication/src/providers/authenticate.ts
=> authentication: use new Setter<T> and Getter<T>

packages/core/src/router/metadata.ts, packages/core/test/unit/router/metadata/param.test.ts
=> Allow @param to be applied to method args

packages/authentication/test/acceptance/basic-auth.ts
=> Remove unsed dependency

packages/authentication/.npmrc, packages/context/.npmrc, packages/core/.npmrc, packages/example-codehub/.npmrc, packages/openapi-spec-builder/.npmrc, packages/openapi-spec/.npmrc, packages/repository/.npmrc, packages/testlab/.npmrc
=> chore: disable package-lock in all packages

packages/authentication/test/acceptance/basic-auth.ts, packages/core/src/router/metadata.ts, packages/core/test/acceptance/sequence/sequence.acceptance.ts, packages/core/test/integration/application.integration.ts, packages/core/test/integration/http-handler.integration.ts, packages/core/test/unit/router/metadata/param.test.ts, packages/openapi-spec/src/openapi-spec-v2.ts
The PR completes openapi v2 (swagger) spec.
=> Tidy up openapi v2 spec

packages/core/package.json, packages/core/src/application.ts, packages/core/test/integration/application.integration.ts
- /swagger.json 2.0 json
- /swagger.yaml 2.0 yaml
- /openapi.json 3.0.0 json
- /openapi.yaml 3.0.0 yaml
Close #489
=> Expose openapi spec 2 & 3 in json & yaml

packages/core/README.md, packages/core/src/application.ts
=> doc(core): fix typos in code examples

package.json
=> chore: upgrade global devDependencies

lerna.json
This will automatically generate a CHANGELOG for each package when lerna publish is used
closes #263
=> build: add conventional commit flag for automatic changelog generation

package.json
In case users forget to install dependencies before running `npm run boostrap`, add it to the build step.
None
=> install deps as part of bootstrap

packages/core/src/http-handler.ts
=> Remove unused function

packages/rest/index.d.ts, packages/rest/index.js
Add the index.d.ts and index.js files required to load the rest package.
=> fix(rest): Add index boilerplate

packages/context/src/binding.ts, packages/context/src/context.ts, packages/context/src/index.ts, packages/context/test/unit/binding.ts, packages/context/test/unit/context.ts
Provide customization to serialize Context and Binding objects to JSON
=> feat(context): Add toJSON() for Context and Binding

packages/core/README.md, packages/rest/README.md
The examples in the README don't even compile; this fixes that.
Tested both by myself and with third-party help!
=> docs(core): Correct usage examples in READMEs

packages/authentication/README.md
~**DO NOT REVIEW**: It seems like there are discussions on how the servers should be created in another PR.  Will wait till that's resolved and make the corresponding changes.~
Fix the README in authentication package due to the refactoring of `@loopback/rest`
Connect to: https://github.com/strongloop/loopback-next/issues/613
=> docs: Fix auth README from rest refactor change

README.md
=> swapped back contributors' images

README.md
- add the Getting Started link
- fix the broken link for `LoopBack 3 vs LoopBack 4`
connect to: https://github.com/strongloop/loopback-next/issues/625
=> docs: add getting started link

package.json
=> build: Upgrade dev dependencies

packages/context/src/provider.ts
A minor fix of example, feel free to make it in you PR and close this one if check in it causes your rebase effort.
=> example fix

packages/rest/package.json, packages/rest/src/router/routing-table.ts, packages/rest/test/integration/rest-server.integration.ts
=> Upgrade rest deps

packages/context/src/context.ts, packages/context/test/unit/context.ts
=> feat(contex) Add isBound() and more apidocs to Context

README.md
=> chore: Fix team lineup in README

packages/rest/src/rest-server.ts, packages/rest/src/sequence.ts
General additions and fixup for typedocs on the rest module
=> docs(rest): Typedoc fixup

packages/build/README.md
=> docs: Improve README for @loopback/build

packages/example-codehub/test/acceptance/health.test.ts, packages/example-codehub/test/acceptance/user.test.ts, packages/repository/src/legacy-juggler-bridge.ts
=> style: fix linting errors

README.md, packages/authentication/LICENSE, packages/build/LICENSE, packages/context/LICENSE, packages/core/LICENSE, packages/example-codehub/LICENSE, packages/repository/LICENSE, packages/rest/LICENSE, packages/testlab/LICENSE
=> chore: Update README and LICENSE files

packages/authentication/package.json, packages/context/package.json, packages/core/package.json, packages/openapi-spec-builder/package.json, packages/openapi-spec/package.json, packages/repository/package.json, packages/rest/package.json, packages/testlab/package.json
Include src folder for npm publish for debugging
Use prepare to replace deprecated prepublish
=> build: Tidy up package.json

packages/cli/generators/project/templates/package.json, packages/cli/generators/project/templates/package.plain.json, packages/cli/generators/project/templates/tsconfig.json, packages/cli/generators/project/templates/tslint.json, packages/cli/lib/project-generator.js, packages/cli/test/app.js, packages/cli/test/extension.js, packages/cli/test/project.js
=> fix: Fix cli templates

commitlint.config.js, package.json
See https://github.com/marionebl/commitlint/issues/54
=> fix: Remove deprecated rules for commitlint

packages/rest/src/router/metadata.ts, packages/rest/src/router/routing-table.ts, packages/rest/test/acceptance/routing/routing.acceptance.ts, packages/rest/test/unit/router/routing-table.test.ts
Simplify method level metadata processing
Add support for basePath
=> fix(rest): Tidy up rest decorator metadata

packages/core/src/application.ts, packages/core/src/component.ts, packages/core/src/keys.ts, packages/core/src/promisify.ts, packages/core/src/server.ts
=> docs(core): Add more ts docs for the core module

.github/stale.yml
We've got a lot of cruft in the backlog that needs pruning.
This will bring us in line with the rest of the loopback repositories, though I've made the rules here _more lenient_.
=> chore: Add Stalebot config

packages/rest/test/unit/parser.test.ts, packages/rest/test/unit/router/reject.test.ts, packages/rest/test/unit/router/routing-table.test.ts
=> fix(rest): Remove unused imports

packages/authentication/README.md, packages/build/README.md, packages/cli/README.md, packages/context/README.md, packages/core/README.md, packages/example-codehub/README.md, packages/openapi-spec-builder/README.md, packages/repository/README.md, packages/rest/README.md, packages/testlab/README.md
Fixes https://github.com/strongloop/loopback-next/issues/562
=> chore: clean up readmes

packages/context/src/context.ts, packages/context/test/unit/context.ts, packages/core/src/application.ts, packages/core/test/acceptance/application.acceptance.ts, packages/core/test/unit/application.test.ts
- Allow find bindings by RegExp
- Add tags for controller/server/component
=> Improve context bindings

README.md, packages/rest/README.md
Update release status from `ALPHA` to `Developer Preview #1`
=> Update release status

CODEOWNERS
Add entries for recently added packages:
- cli
- rest
Add Kevin as a co-owner of project infrastructure.
=> docs: update CODEOWNERS file

packages/metadata/test/unit/inspector.test.ts
=> test(metadata): Add a test for design-time array types

packages/rest/src/router/metadata.ts, packages/rest/test/unit/router/metadata/param-body.test.ts, packages/rest/test/unit/router/metadata/param.test.ts
=> feat(rest): Improve decorators to infer param types

packages/context/src/resolver.ts, packages/context/test/acceptance/method-level-bindings.ts
=> docs: resolve injected arguments

packages/context/src/resolver.ts, packages/context/test/acceptance/method-level-bindings.ts
=> revert: revert error message

packages/build/package.json
Fix https://github.com/strongloop/loopback-next/issues/837
- connect to https://github.com/strongloop/loopback-next/issues/837
=> fix: update git repo url

packages/authentication/package.json, packages/authentication/src/providers/authenticate.ts, packages/authentication/src/strategy-adapter.ts, packages/authentication/test/unit/fixtures/mock-strategy.ts, packages/authentication/test/unit/strategy-adapter.test.ts, packages/openapi-v2/src/controller-spec.ts
Recent changes in some of our dependencies caused `tsc` to fail. This patch is fixing the problem.
There are two commits, the first one for the recently added `openapi-v2` package. The second one is more involved and fixes `authentication` package.
=> Fix broken build

packages/cli/test/clone-example.test.js, packages/testlab/package.json, packages/testlab/src/test-sandbox.ts, packages/testlab/src/testlab.ts, packages/testlab/test/fixtures/copy-me.txt, packages/testlab/test/integration/test-sandbox.integration.ts, packages/testlab/test/unit/test-sandbox.unit.ts
A Class utility to create a temporary test sandbox to stand up testing environments.
Blocks #858 
- [ n/a ] Affected artifact templates in `packages/cli` were updated
- [ n/a ] Affected example projects in `packages/example-*` were updated
=> feat(testlab): create a test sandbox utility

packages/rest/test/acceptance/routing/routing.acceptance.ts
A follow-up to https://github.com/strongloop/loopback-next/pull/903.
=> test(rest): add a test to cover params not resolved or injected

packages/context/README.md
=> docs(context): improve README for @loopback/context

packages/example-getting-started/README.md
- missed as a part of PR #955 
- updates the README according to the refactor
=> fix(example-getting-started): update readme to use RestApplication

.nycrc, .prettierignore, .vscode/launch.json, .vscode/settings.json, CHANGELOG.md, appveyor.yml
Just a cleanup of some top level files:
- Remove `dist6` from config files
- Fix `mocha` path for debugger in launch.json
- Update `CHANGELOG.md`
- `appveyor.yml` remove `npm install` since it's done as part of `npm run bootstrap`.
=> chore: cleanup of top level files

packages/cli/test/clone-example.test.js
=> ci(cli): increase timeout for a slow acceptance test

lerna.json
See https://github.com/lerna/lerna#--message--m-msg
=> fix(build): configure commit message for lerna publish

packages/boot/src/booters/base-artifact.booter.ts, packages/boot/src/booters/booter-utils.ts, packages/boot/test/unit/booters/booter-utils.unit.ts
=> fix(boot): fix loadClassesFromFiles to be a sync function

packages/openapi-v2/docs.json
=> fix: openapi-v2 docs

lerna.json
The current message breaks commit lint as `release` is not a valid scope
=> fix: update the generated commit message for lerna

packages/rest/package.json, packages/rest/src/rest-server.ts, packages/rest/test/integration/rest-server.integration.ts
Fixes https://github.com/strongloop/loopback-next/issues/1055
=> fix(rest): enable cors preflight

packages/repository-json-schema/README.md
- connected to https://github.com/strongloop/loopback-next/issues/988
=> fix(repository-json-schema): change model to be a class

packages/cli/generators/controller/templates/src/controllers/controller-rest-template.ts.template, packages/cli/test/controller.js
=> fix: template

packages/example-log-extension/README.md, packages/example-log-extension/src/component.ts, packages/example-log-extension/src/index.ts, packages/example-log-extension/src/mixins/log.mixin.ts, packages/example-log-extension/test/acceptance/log.extension.acceptance.ts, packages/example-log-extension/test/unit/mixins/log.mixin.unit.ts
- renamed LogLevelMixin to LogMixin
- made LogMixin automatically mount LogComponent for better UX
- added tests and refactored some as well.
- Reviewed and updated code in README
connected to #988
=> example-log-extension: refactor code + update README

packages/core/README.md
=> docs(core): update readme with latest code changes and links

docs/CONTRIBUTING.md
=> chore: fix broken link to monorepo.md in contributing

packages/example-rpc-server/README.md, packages/example-rpc-server/tsconfig.json
Added index.ts at root level to files that need to be compiled in tsconfig.json
Also changed the powered by loopback logo
=> fix(example-rpc-server): include index.ts in tsconfig

packages/authentication/README.md
- connected to https://github.com/strongloop/loopback-next/issues/988
=> fix(authentication): update broken code in README

CHANGELOG.md, CODEOWNERS, README.md, docs/site/Repositories.md
The PR cleans up the repo setup for code review responsibilities. Contributions are welcome regardless of this file.
=> chore: update CODEOWNERS and fix typo in CHANGELOG

docs/site/LoopBack-3.x.md
First commit adds line breaks, so please review from second commit and onward please :)
=> chore: update loopback-3.x.md

packages/metadata/README.md
=> docs(metadata): fix typo

README.md
=> docs: update installation, examples and production disclaimer

packages/example-getting-started/data/db.json
Remove non-existent model from sample data in example-getting-started and add some more data for our `Todo` model.
=> fix(example-getting-started): remove old model from sample data

.github/PULL_REQUEST_TEMPLATE.md
Add "docs update" entry to the check-list used for new pull requests.
=> chore: add "docs update" to pull-request checklist

packages/example-getting-started/docs/controller.md, packages/example-getting-started/docs/datasource.md, packages/example-getting-started/docs/juggler.md, packages/example-getting-started/docs/model.md, packages/example-getting-started/docs/putting-it-together.md, packages/example-getting-started/docs/repository.md, packages/example-getting-started/docs/scaffolding.md, packages/example-getting-started/src/application.ts, packages/example-getting-started/src/controllers/todo.controller.ts, packages/example-getting-started/src/index.ts, packages/example-getting-started/src/sequence.ts, packages/example-getting-started/test/acceptance/application.test.ts
connected to #729 
Updates the tutorial and the code so they are in sync with each other and the code reflects what is generated as someone follows along the tutorial using `@loopback/cli`.
=> refactor(example-getting-started): sync code and docs

docs/site/Concepts.md
=> fix: make small changes to Concepts.md

docs/site/Routes.md
Please review the 2nd commit :)
=>  docs: update route.md to use openapi-v3 

packages/build/bin/run-clean.js
It's follow-up to https://github.com/strongloop/loopback-next/pull/1150.
=> fix(build): use variable names to reflect the accepted args

docs/site/Server.md
Fix the code snippet in the Server page (http://loopback.io/doc/en/lb4/Server.html#usage).
Related to #988
=> docs:Update code snippet in Server page

docs/site/Controllers.md
- First commit is from running prettier
- Second commit is where the stuff that needs to be reviewed is
=> docs: fix code snippets in controllers.md

packages/repository/examples/juggler-bridge/note-with-repo-class.ts, packages/repository/examples/juggler-bridge/note-with-repo-instance.ts, packages/repository/tsconfig.build.json
The PR fixes compilation errors in the `examples` directory.
=> fix(repository): make sure examples are compiled

docs/site/Creating-components.md, docs/site/Creating-servers.md, docs/site/Extending-LoopBack-4.md, docs/site/Testing-Your-Extensions.md, docs/site/sidebars/lb4_sidebar.yml
=> docs: review and update of code snippets

packages/context/README.md
=> docs(context): update code in readme

docs/site/Application.md
- consistency with links
- better example names
- spacing
- connected to #988
=> docs: update Application page

docs/site/Context.md
=> docs: update code snippets in Context.md

docs/site/Controller-generator.md
=> docs: upgrade controller-generator.md to v3

docs/site/Decorators.md
=> docs: update code in Decorators.md

docs/site/sidebars/lb4_sidebar.yml
follow up to #1214 -- updating sidebar links
=> fix: update sidebar links

docs/site/Application.md, docs/site/Context.md, docs/site/Creating-components.md
=> docs: fix miscellaneous errors/typos

docs/site/includes/CLI-std-options.md
=> docs: add includes folder + files

packages/openapi-v3-types/docs.json
=> fix: include openapi-v3-spec-types.ts in docs.json

README.md
Update the @hacksparrow to the maintainer list. 
Welcome back @hacksparrow!
=> chore: add Yaapa to maintainer list

examples/hello-world/package.json, examples/log-extension/package.json, examples/rpc-server/package.json, examples/todo/package.json, package.json, packages/authentication/package.json, packages/boot/package.json, packages/build/package.json, packages/cli/package.json, packages/context/package.json, packages/core/package.json, packages/metadata/package.json, packages/openapi-spec-builder/package.json, packages/openapi-v3-types/package.json, packages/openapi-v3/package.json, packages/repository-json-schema/package.json, packages/repository/package.json, packages/rest/package.json, packages/testlab/package.json
Based on the discussion found here: https://github.com/strongloop/loopback-next/pull/1241#issuecomment-379963942
=> refactor: add @types/node as a devDependency

packages/openapi-v3-types/package.json, packages/openapi-v3-types/test/unit/openapi-v3-spec-types.unit.ts, packages/openapi-v3-types/test/unit/type-guards.unit.ts, packages/testlab/package.json, packages/testlab/src/validate-api-spec.ts
connected to #181 
set up the test infrastructure for this package as well as write tests for coverage.
NOTE: Interfaces are meant to be tested by just having the files compile as the typing information is otherwise lost afterwards.
=> test(openapi-v3-types): improve test coverage

docs/site/Context.md
This is causing a failure on loopback.io
=> style(docs): fix syntax for include block

docs/.npmrc
Disable `package-lock.json` file for `@loopback/docs` package.
=> chore(docs): disable package-lock

README.md
- change gitter logo; the previous logo does not load quickly enough. There are often times when the logo does not appear at all
=> fix: change gitter logo

.travis.yml, appveyor.yml
=> ci: enable node 10

.prettierignore, commitlint.config.js, package.json, packages/build/bin/compile-package.js, packages/build/bin/run-clean.js, packages/build/bin/run-mocha.js, packages/build/bin/run-prettier.js, packages/build/bin/utils.js, packages/build/src/fail-on-console-logs.js, packages/build/test/integration/scripts.integration.js, packages/cli/bin/cli.js, packages/cli/generators/app/index.js, packages/cli/generators/controller/index.js, packages/cli/generators/example/downloader.js, packages/cli/generators/example/index.js, packages/cli/lib/artifact-generator.js, packages/cli/lib/project-generator.js, packages/cli/lib/utils.js, packages/cli/test/integration/cli/cli.integration.js, packages/cli/test/integration/generators/app.integration.js, packages/cli/test/integration/generators/controller.integration.js, packages/cli/test/integration/generators/example.integration.js, packages/cli/test/integration/generators/extension.integration.js, packages/cli/test/integration/lib/artifact-generator.js, packages/cli/test/integration/lib/project-generator.js, packages/cli/test/test-utils.js, packages/cli/test/unit/utils.unit.js, packages/dist-util/index.js, packages/repository/examples/models/customer.definition.js
=> chore: enable prettier for JavaScript sources

docs/apidocs.html, docs/site/Reserved-binding-keys.md, packages/openapi-v3/src/keys.ts, packages/repository-json-schema/src/keys.ts
=> chore: rework binding key docs to point to apidocs

packages/build/package.json
Upgrade to strong-docs@3.0.1, which is a rewrite in TypeScript.
=> chore: upgrade to strong-docs@3.0.1

packages/openapi-v3/test/unit/decorators/param/param-header.decorator.unit.ts, packages/openapi-v3/test/unit/decorators/param/param-path.decorator.unit.ts, packages/openapi-v3/test/unit/decorators/param/param-query.decorator.unit.ts
connect to https://github.com/strongloop/loopback-next/issues/1052
=> test: add shortcut tests

examples/hello-world/package.json, examples/log-extension/package.json, examples/rpc-server/package.json, examples/todo/package.json, packages/authentication/package.json, packages/boot/package.json, packages/build/package.json, packages/cli/package.json, packages/context/package.json, packages/core/package.json, packages/metadata/package.json, packages/openapi-spec-builder/package.json, packages/openapi-v3-types/package.json, packages/openapi-v3/package.json, packages/repository-json-schema/package.json, packages/repository/package.json, packages/rest/package.json, packages/rest/src/rest.server.ts, packages/testlab/package.json
=> chore: upgrade to @types/node@10.x

packages/repository/src/mixins/repository.mixin.ts
=> fix: move apidocs outside of the function

docs/site/tables/lb4-artifact-commands.html, docs/site/tables/lb4-project-commands.html
=> fix: add tealium scripts to page

.travis.yml
=> ci: run coveralls after test

docs/site/Controller-generator.md
Something I forgot to fix when #887 landed
=> fix: correct docs for rest controller cli prompt

packages/testlab/README.md
Small syntax correction from #1393
=> fix: fill out missing brackets in testlab readme

docs/site/Controller-generator.md, docs/site/Defining-the-API-using-code-first-approach.md
The PR fixes headers extending across the rest of the pages
=> docs: fix header renderings

docs/site/Application-generator.md, packages/cli/generators/app/index.js, packages/cli/generators/controller/templates/src/controllers/controller-rest-template.ts.ejs, packages/cli/generators/controller/templates/src/controllers/controller-template.ts.ejs, packages/cli/lib/artifact-generator.js, packages/cli/lib/base-generator.js, packages/cli/lib/update-index.js, packages/cli/test/integration/generators/app.integration.js
1. Make sure `--applicationName` is honored
2. Fix templates
3. Move some utils to base-generator
=> Fix cli issues

packages/context/src/resolver.ts, packages/context/test/acceptance/method-level-bindings.acceptance.ts
Fixes https://github.com/strongloop/loopback-next/issues/1408
=> fix(context): calculate # of method params with default

.github/stale.yml
=> fix: increase stalebot ttl

docs/site/Best-practices.md, docs/site/sidebars/lb4_sidebar.yml
=> docs: rename Best Practices page & sidebar section

packages/rest/src/rest.server.ts, packages/rest/test/integration/rest.server.integration.ts
=> fix(rest): error when stopping an app that hasn't been started

examples/todo/test/acceptance/application.acceptance.ts, packages/http-caching-proxy/test/integration/http-caching-proxy.integration.ts
See https://github.com/strongloop/loopback-next/issues/1407
=> test: increase timeouts to accomodate slow networks

docs/site/OpenAPI-generator.md, docs/site/sidebars/lb4_sidebar.yml, docs/site/tables/lb4-artifact-commands.html
=> docs(cli): add docs for lb4 openapi command

packages/cli/generators/openapi/index.js, packages/cli/generators/openapi/schema-helper.js, packages/cli/generators/openapi/spec-helper.js, packages/cli/generators/openapi/templates/src/controllers/controller-template.ts.ejs, packages/cli/generators/openapi/utils.js, packages/cli/smoke-test/openapi/code-gen-utils.js, packages/cli/smoke-test/openapi/real-world-apis.smoke.js, packages/cli/test/fixtures/openapi/3.0/customer.yaml, packages/cli/test/unit/openapi/controller-spec.unit.js, packages/cli/test/unit/openapi/schema-model.unit.js, packages/openapi-v3/src/decorators/request-body.decorator.ts
=> [WIP] Improve generated code from openapi specs

docs/site/todo-tutorial-putting-it-together.md
I change todo-tutorial-putting-it-together.md tutorial with advice!
https://github.com/strongloop/loopback-next/pull/1496
=> docs: update todo-tutorial-putting-it-together.md

docs/site/DataSource-generator.md, docs/site/Model-generator.md, docs/site/sidebars/lb4_sidebar.yml, docs/site/tables/lb4-artifact-commands.html, docs/site/todo-tutorial-geocoding-service.md, docs/site/todo-tutorial-model.md, docs/site/todo-tutorial-repository.md, packages/cli/README.md, packages/cli/generators/model/index.js
=> docs: add/update lb4 model related docs

docs/site/HasMany-relation.md
=> docs: add missing imports to code examples

.nycrc
This is a follow-up for #1526.
=> build: start measuring code coverage of `cli` package

README.md
My name is ordered and spelt "Hage Yaapa" :D
=> docs: fix Yaapa's name

docs/site/HasMany-relation.md, packages/repository/src/repositories/legacy-juggler-bridge.ts, packages/repository/src/repositories/relation.factory.ts, packages/repository/test/acceptance/has-many-without-di.relation.acceptance.ts, packages/repository/test/acceptance/has-many.relation.acceptance.ts, packages/repository/test/integration/repositories/relation.factory.integration.ts
=> fix(repository): change parameter order in HasManyRepositoryFactory

README.md
Merge when Developer Preview #3 is ready.
This PR is part of the [DP3 release checklist](https://github.com/strongloop/loopback-next/issues/1377).
=> docs: update release name in README

packages/cli/generators/app/templates/src/controllers/ping.controller.ts.ejs, packages/cli/test/integration/generators/app.integration.js
connect to https://groups.google.com/forum/#!topic/loopbackjs/g1_SI9_wkis
=> fix: import package in template

docs/site/Parsing-requests.md
fix https://loopback.io/doc/en/lb4/Parsing-requests.html
=> docs: fix the note

docs/site/Getting-started.md
Minor changes in the [Getting Started doc](https://loopback.io/doc/en/lb4/Getting-started.html) to reflect the current output of `lb4 controller`.
=> docs: update Getting Started doc

packages/rest/src/rest.server.ts, packages/rest/test/integration/rest.server.integration.ts
=> fix(rest): set openapi url based on x-forwarded-* headers

bin/build-docs-site.sh, bin/travis.sh, lerna.json, package.json
https://github.com/lerna/lerna/issues/1449#issuecomment-414706160
Move the `ci` flag into `lerna.json` for consistency.
=> chore: set ci flag in lerna.json

.gitignore, sandbox/.gitignore, sandbox/README.md, sandbox/example/index.js, sandbox/example/package.json
See https://github.com/lerna/lerna/issues/1602
=> chore: add a package to sandbox to avoid publish failure

docs/site/Decorators.md, docs/site/todo-list-tutorial-model.md, docs/site/todo-list-tutorial-repository.md
=> docs: edits to decorators topic

docs/site/DataSource-generator.md
Small error in documentation link.
=> docs(DataSource-generator): Update DataSource-generator.md

docs/site/todo-tutorial-geocoding-service.md
=> docs: fix file path in tutorial

CODEOWNERS
Kyu is no longer actively maintaining LoopBack.
=> chore: remove @shimks from CODEOWNERS

packages/rest/src/rest.server.ts, packages/rest/test/integration/rest.server.integration.ts
This PR improves host/port parsing from http headers. If the `host` is set and `port` is default, we honor it now.
@virkt25 I think it will fix the issue you have with bluemix where `8080` is added.
=> fix(rest): tidy up host/port parsing and client url building

packages/cli/generators/model/index.js
Fixes https://github.com/strongloop/loopback-next/issues/1665
=> fix: make `lb model` prompts clearer

packages/repository/src/model.ts, packages/repository/test/unit/model/model.unit.ts
This PR adds the ability to recursively convert model instances to plain json object
=> fix(repository): handle conversion of property values to plain json

packages/repository/src/model.ts, packages/repository/test/unit/model/model.unit.ts
A follow-up to #1711. This PR fixes the array conversion.
=> fix(repository): convert array items to json

packages/cli/generators/app/templates/index.js.ejs, packages/cli/generators/extension/templates/index.d.ts.ejs, packages/cli/generators/extension/templates/index.js.ejs, packages/cli/generators/project/templates/package.plain.json.ejs, packages/cli/test/integration/lib/project-generator.js
Fixes https://github.com/strongloop/loopback-next/issues/1714
=> fix(cli): generate correct index.js without loopback build

docs/site/todo-list-tutorial-controller.md
=> Fix repository name typo

packages/boot/src/booters/datasource.booter.ts
=> fix(boot): fix incorrect comment

packages/rest/src/validation/request-body.validator.ts
Improve schema validation performance. Fixes https://github.com/strongloop/loopback-next/issues/1590.
Was:
```
find all todos: { requestsPerSecond: 1737.57, latency: 5.23 }
create a new todo: { requestsPerSecond: 249.67, latency: 39.6 }
```
Is:
```
find all todos: { requestsPerSecond: 2244.7, latency: 3.89 }
create a new todo: { requestsPerSecond: 1209.37, latency: 7.74 }
```
=> perf: improve schema validation peformance

CODEOWNERS
Replace Taranveer with Yaapa in CODEOWNERS
=> chore: replace Taranveer with Yaapa in CODEOWNERS

docs/site/BelongsTo-relation.md, docs/site/HasMany-relation.md, docs/site/Relations.md, docs/site/sidebars/lb4_sidebar.yml, docs/site/todo-list-tutorial-repository.md, examples/todo-list/src/controllers/todo.controller.ts, examples/todo-list/src/repositories/todo-list.repository.ts, examples/todo-list/src/repositories/todo.repository.ts, examples/todo-list/test/acceptance/todo.acceptance.ts, examples/todo-list/test/unit/controllers/todo-list-todo.controller.unit.ts, packages/repository/examples/models/order.model.ts, packages/repository/src/repositories/legacy-juggler-bridge.ts, packages/repository/test/acceptance/has-many-without-di.relation.acceptance.ts, packages/repository/test/fixtures/repositories/customer.repository.ts, packages/repository/test/fixtures/repositories/order.repository.ts
=> docs: describe BelongsTo relation

packages/repository/src/repositories/legacy-juggler-bridge.ts, packages/repository/test/unit/repositories/legacy-juggler-bridge.unit.ts
Fixes https://github.com/strongloop/loopback-next/issues/1813
=> fix(repository): resolve types for juggler

README.md
- Remove @superkhau, @loay, @virkt25 and @shimks
- Add @nabdelgadir and @marioestradarosa 
Screenshot of the new content:
=> docs: update list of maintainers in README

benchmark/README.md, packages/rest/src/validation/request-body.validator.ts
MacBookPro Early 2015 Processor: 2.5 GHz Intel Core i5 Memory: 8 GB 1867 MHz
DDR3.
Was:
```
find all todos: { requestsPerSecond: 2853.17, latency: 3.01 }
create a new todo: { requestsPerSecond: 231.34, latency: 42.78 }
```
Is:
```
find all todos: { requestsPerSecond: 2620.84, latency: 3.31 }
create a new todo: { requestsPerSecond: 2603.77, latency: 3.35 }
```
=> perf: update AJV validation cache

packages/repository/examples/repositories/customer.repository.ts, packages/repository/src/common-types.ts, packages/repository/src/connectors/crud.connector.ts, packages/repository/src/query.ts, packages/repository/src/repositories/constraint-utils.ts, packages/repository/src/repositories/legacy-juggler-bridge.ts, packages/repository/src/repositories/relation.repository.ts, packages/repository/src/repositories/repository.ts, packages/repository/test/unit/query/query-builder.unit.ts, packages/repository/test/unit/repositories/constraint-utils.unit.ts
Supersedes https://github.com/strongloop/loopback-next/pull/1782
@gms1 Please review.
=> feat(repository): add type safety for query filter/where

packages/cli/generators/project/templates/tsconfig.json.ejs, packages/cli/test/integration/lib/project-generator.js
=> fix(cli): enable --resolveJsonModule for plain tsconfig

docs/site/Service-generator.md, packages/cli/generators/service/index.js
- to be consistent with lb4 repository
- to fail fast if no service datasource is defined
=> chore(cli): prompt datasources first before service name

docs/site/todo-tutorial-controller.md, docs/site/todo-tutorial-model.md, docs/site/todo-tutorial-putting-it-together.md, docs/site/todo-tutorial-repository.md, examples/todo/README.md
There are a few areas in the todo tutorial that I've modified in this PR to keep it up-to-date:
- Add model section: include the Entity/Model prompt, update the interactive output.
- Add repository section: use `lb4 repository` instead
- Add controller section: create REST controller instead of empty controller.  
- Putting it all together section: there is no longer extra steps to modify the Application class.
Fixes https://github.com/strongloop/loopback-next/issues/1827
=> docs: clean up todo tutorial

.vscode/settings.json, examples/hello-world/.vscode/settings.json, examples/log-extension/.vscode/settings.json, examples/rpc-server/.vscode/settings.json, examples/soap-calculator/.vscode/settings.json, examples/todo-list/.vscode/settings.json, examples/todo/.vscode/settings.json, packages/cli/generators/project/templates/.vscode/settings.json
=> chore: vscode config for v 1.28

docs/site/Controllers.md
Fix awkward wording in Controllers.md
=> docs: Fix wording

docs/site/Decorators_openapi.md, packages/openapi-v3/src/controller-spec.ts, packages/openapi-v3/test/integration/controller-spec.integration.ts
https://github.com/strongloop/loopback-next/issues/1892
=> fix(openapi-v3): generate schemas for x-ts-type

packages/rest/package.json
Cleans up / re-fixes #1917
Other items are N/A for this PR.
Verified this in my local environment that originally experienced #1917
=> fix: remove unnecessary dependency from #1918

packages/rest/test/integration/rest.application.integration.ts
Additional tests for RestApplocation.
=> chore: additional tests for RestApplication

docs/site/Controller-generator.md, docs/site/todo-list-tutorial-controller.md, examples/todo-list/src/controllers/todo-list-todo.controller.ts, examples/todo-list/src/controllers/todo-list.controller.ts, examples/todo-list/src/controllers/todo.controller.ts, examples/todo/src/controllers/todo.controller.ts, packages/cli/generators/controller/templates/src/controllers/controller-rest-template.ts.ejs, packages/cli/test/integration/generators/controller.integration.js
Fixes https://github.com/strongloop/loopback-next/issues/1933
This is a follow-up of #1907
=> fix: update usage of `x-ts-type` for schemas

docs/CONTRIBUTING.md, docs/site/WEBSTORM.md
This PR adds documentation for Webstorm IDE.
=> docs: add webstorm

.travis.yml
=> ci: enable Node.js 11.x on Travis CI

docs/site/Decorators_inject.md
Update link error to **Dependency Injection** page on `Decorators_inject.md`.
=> docs: update Decorators_inject.md

packages/openapi-v3/test/unit/filter-schema.unit.ts, packages/repository/src/decorators/model.decorator.ts
Fixes https://github.com/strongloop/loopback-next/issues/2002
=> fix(repository): make sure model definition is built correctly

docs/site/Testing-your-application.md
Update doc "Testing Your Application" unit test
update section of "unit test controllers" to show how to use `createStubInstance` from `@loopback/testlab` instead of `SinonStub` directly
Implements #1935
=> docs: update unit test example with StubbedInstanceWithSinonAccessor

docs/CONTRIBUTING.md
Connect to https://github.com/strongloop/loopback-next/issues/1853.
=> docs: contribution docs repo update

docs/site/Booting-an-Application.md, docs/site/Creating-components.md, docs/site/Server.md
=> docs: minors edits to docs

.vscode/tasks.json
=> build: update VSCode "lint" task to use tslint5 problem matcher

docs/site/Deploying-with-pm2-and-nginx.md
This fixes the comments mentioned in PR #2093
=> docs: fixed spelling mistakes and indentation issue

packages/repository/src/query.ts, packages/repository/test/unit/query/query-builder.unit.ts
Fixes #2215
I believe the unchecked items above are not applicable to the changes in this PR.
=> fix: add nin operator to query typing and builder (#2215)

docs/site/FAQ.md
Closes: strongloop/loopback.io#790
=> Fix typo in docs

packages/testlab/docs.json, packages/testlab/package.json
Fixes https://github.com/strongloop/loopback-next/issues/2234
=> fix(testlab): add api docs during build

docs/site/Getting-started.md, docs/site/soap-calculator-tutorial-scaffolding.md, docs/site/todo-tutorial-scaffolding.md, packages/cli/generators/app/index.js, packages/cli/lib/project-generator.js
Connect to https://github.com/strongloop/loopback-next/issues/1298.
Add descriptions from https://github.com/strongloop/loopback-next/issues/1298#issuecomment-449027445 to features in the CLI when creating an app so users can understand what the features do.
=> fix(cli): add descriptions to features

docs/site/Parsing-requests.md
=> docs: fix controllers url in parsing-requests

examples/hello-world/package.json, examples/log-extension/package.json, examples/rpc-server/package.json, examples/soap-calculator/package.json, examples/todo-list/package.json, examples/todo/package.json, package.json, packages/build/package.json
Upgrade to TypeScript 3.3.x and other dev deps for root package.json
=> chore: upgrade dependencies for build

README.md
=> chore: add dominique to maintainers

.github/stale.yml
Let's keep "good first issues" open forever. They are providing an important entry point for new contributors .
=> chore: exclude "good first issue" from stalebot

benchmark/package.json, examples/rpc-server/package.json, packages/http-caching-proxy/package.json, packages/http-server/package.json
=> [greenkeeper] upgrade to p-event@2.3.1

docs/site/Controllers.md, docs/site/Repositories.md
Related to https://github.com/strongloop/loopback-next/issues/2099
Move the "Review questions" to the github issue for the Controller page: https://loopback.io/doc/en/lb4/Controllers.html.
=> fix(docs): remove review questions section for Controller page

examples/todo-list/src/repositories/todo-list.repository.ts, packages/repository/src/__tests__/fixtures/repositories/customer.repository.ts, packages/repository/src/repositories/legacy-juggler-bridge.ts
Removed underscore from hasOne protected method
Fixes #2370
See also #2112, #2091
=> refactor(repository): remove underscore from hasOne protected method

packages/build/package.json
=> chore(build): upgrade to strong-docs@4.1.0

docs/site/todo-tutorial-datasource.md
Just a grammar fix in the tutorial.
- [ x] Agree to the CLA (Contributor License Agreement) by [clicking and signing](https://cla.strongloop.com/agreements/strongloop/loopback-next)
=> fix(docs): grammar fix on todo-tutorial-datasource.md

docs/site/Server.md, packages/rest/src/__tests__/integration/rest.server.integration.ts, packages/rest/src/rest.server.ts
Implements https://github.com/strongloop/loopback-next/issues/2410
=> feat(rest): add `disabled` option for OpenAPI spec endpoints

packages/cli/generators/repository/index.js
=> fix(cli): fix prompt for base repository class

packages/cli/generators/app/templates/Dockerfile, packages/cli/test/integration/generators/app.integration.js
Update Dockerfile to a better version that is slimmer and has no vulnerabilities detected by IBM
Cloud
=> perf: update dockerfile to better version

packages/rest/src/__tests__/integration/request-context.integration.ts
This is a follow-up for https://github.com/strongloop/loopback-next/pull/2547#discussion_r265152486.
=> test(testlab): verify how RequestContext combines urlBase and basePath

packages/repository/src/__tests__/acceptance/has-many.relation.acceptance.ts
See https://github.com/strongloop/loopback-next/pull/2595#discussion_r266420445
=> test: add context to hasMany to self test

package.json
See https://github.com/strongloop/loopback-next/issues/2578#issuecomment-473809374
=> chore: customize commit message for greenkeeper lockfileUpdate

packages/repository/src/__tests__/acceptance/repository.acceptance.ts, packages/repository/src/__tests__/unit/repositories/legacy-juggler-bridge.unit.ts, packages/repository/src/repositories/legacy-juggler-bridge.ts
=> fix(repository): support embedded models for nested properties 

packages/core/src/__tests__/unit/application.unit.ts, packages/core/src/application.ts, packages/core/src/component.ts, packages/core/src/keys.ts
Extracted code to improve application bindings from https://github.com/strongloop/loopback-next/pull/1928
=> feat(core): improve app bindings

docs/site/todo-list-tutorial-controller.md
Include code of TodoListTodoController instead of TodoListController
Closes https://github.com/strongloop/loopback-next/issues/2465.
=> docs: change code examples

packages/cli/package-lock.json, packages/cli/package.json
=> [greenkeeper] Greenkeeper/default/semver 6.0.0

packages/cli/package-lock.json, packages/cli/package.json, packages/testlab/package-lock.json, packages/testlab/package.json
=> chore: update sinon to version 7.3.1

examples/express-composition/package-lock.json, examples/express-composition/package.json, examples/greeter-extension/package-lock.json, examples/greeter-extension/package.json, examples/hello-world/package-lock.json, examples/hello-world/package.json, examples/log-extension/package-lock.json, examples/log-extension/package.json, examples/rpc-server/package-lock.json, examples/rpc-server/package.json, examples/soap-calculator/package-lock.json, examples/soap-calculator/package.json, examples/todo-list/package-lock.json, examples/todo-list/package.json, examples/todo/package-lock.json, examples/todo/package.json, package-lock.json, package.json, packages/build/package-lock.json, packages/build/package.json
Upgrade to TypeScript 3.4.x and tslint 5.14.0.
=> chore: upgrade to typescript 3.4

benchmark/package-lock.json, docs/site/DEVELOPING.md, examples/express-composition/package-lock.json, examples/soap-calculator/package-lock.json, examples/todo-list/package-lock.json, examples/todo/package-lock.json, package.json, packages/boot/package-lock.json, packages/build/package-lock.json, packages/cli/package-lock.json, packages/repository/package-lock.json, packages/rest-explorer/package-lock.json, packages/rest/package-lock.json, packages/service-proxy/package-lock.json, packages/testlab/package-lock.json, packages/tslint-config/package-lock.json
The first commit introduces a new package script:
```sh
$ npm run update-all-deps
```
The second commit contains the changes (dependency updates) produced by running that script.
_Resolve #2667_
=> Update all dependencies to latest versions + document the process

examples/express-composition/package-lock.json, examples/express-composition/package.json, examples/rpc-server/package-lock.json, examples/rpc-server/package.json, packages/context/package-lock.json, packages/context/package.json, packages/http-caching-proxy/package-lock.json, packages/http-caching-proxy/package.json, packages/http-server/package-lock.json, packages/http-server/package.json, packages/rest/package-lock.json, packages/rest/package.json
- update bluebird to version 3.5.4 - resolve #2680
- update p-event to version 4.1.0 - resolve #2679
- update @types/js-yaml to version 3.12.1 - resolve #2678
=> chore: update dependencies

packages/rest/src/validation/request-body.validator.ts
A replacement for #2683 where I am not able to rewrite git history.
/cc @pktippa-bn @pktippa 
=> fix(rest): a small typo fix in code comments

docs/site/BelongsTo-relation.md
Add documentation for the self relation. The code snippet is updated according to the test fixtures [here](https://github.com/strongloop/loopback-next/tree/2657c9e99edd93ccdec3d4ba79f14524c5678792/packages/repository/src/__tests__/fixtures)
=> docs: add self relation examples

docs/site/Sequence.md
Update the levels of:
And small change from `.html` -> `.md`.
=> fix(docs): fix sequence levels

packages/context/src/inject.ts
=> chore(context): adjust resolvers to accept a non-optional session

packages/context/src/__tests__/acceptance/class-level-bindings.acceptance.ts, packages/context/src/inject.ts, packages/context/src/resolution-session.ts
Refactor target type checking for injections to a utility function.
=> refactor(context): refactor target type checking for injections into a function

docs/site/Model.md, docs/site/Parsing-requests.md
Add document according to PR https://github.com/strongloop/loopback-next/commit/d0014c607eb130bf0d2adaf3249e67c3755771ae
=> docs: add jsonSchema field

packages/rest/README.md
=> Fix unused variable issue in sample code

packages/rest/src/__tests__/acceptance/file-upload/file-upload-with-parser.acceptance.ts
=> test: fixed get request fields with multer

.travis.yml
=> chore: add node v12 to the travis build

docs/site/HasMany-relation.md
Add details about foreign key property in hasMany relation
=> docs: document foreign key property in hasMany relation

docs/site/Serving-static-files.md
Fix a typo.
- [x ] Documentation in [/docs/site](../tree/master/docs/site) was updated
=> Fix typo in Service-static-files.md

packages/testlab/package-lock.json, packages/testlab/package.json, packages/testlab/src/shot.ts
This should eventually fix most of the deprecation warnings reported by `npm install` executed from our CLI tests (see e.g. https://github.com/strongloop/loopback-next/pull/2827) ~~Please note that we need to publish a new version of `@loopback/testlab` to bring this change into effect.~~
```
npm WARN deprecated shot@4.0.7: This module has moved and is now available at @hapi/shot. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated joi@14.3.1: This module has moved and is now available at @hapi/joi. Please …
```
=> chore(testlab): move from deprecated `shot` to `@hapi/shot`

packages/rest-explorer/src/__tests__/acceptance/rest-explorer.express.acceptance.ts
As pointed out by @emonddr, see https://github.com/strongloop/loopback-next/pull/2856.
=> refactor(rest-explorer): improve test names

README.md
=> chore: add agnes'info into README

packages/context/src/__tests__/acceptance/interception-proxy.acceptance.ts
=> chore(context): improve test coverage for interception proxy

docs/site/exposing-graphql-apis.md
=> docs: fix lb4 graphQL tutorial steps

packages/authentication/docs/authentication-system.md, packages/authentication/src/__tests__/fixtures/strategies/basic-strategy.ts, packages/authentication/src/__tests__/fixtures/strategies/jwt-strategy.ts
Change extractCredentals to extractCredentials
=> refactor: fix typo in authentication package

packages/context/src/interception-proxy.ts, packages/context/src/interceptor.ts
=> chore(context): use `@example` for ts code in comments

packages/boot/src/booters/booter-utils.ts, packages/boot/src/bootstrapper.ts, packages/cli/generators/discover/index.js, packages/cli/lib/model-discoverer.js, packages/core/src/application.ts, packages/core/src/component.ts, packages/core/src/lifecycle-registry.ts, packages/openapi-v3/src/decorators/api.decorator.ts, packages/openapi-v3/src/decorators/parameter.decorator.ts, packages/openapi-v3/src/decorators/request-body.decorator.ts, packages/repository/src/decorators/model.decorator.ts, packages/repository/src/relations/belongs-to/belongs-to.decorator.ts, packages/repository/src/relations/has-many/has-many.decorator.ts, packages/repository/src/relations/has-one/has-one.decorator.ts, packages/repository/src/relations/relation.decorator.ts, packages/repository/src/types/type.ts, packages/rest/src/providers/parse-params.provider.ts, packages/rest/src/providers/send.provider.ts, packages/rest/src/rest.application.ts, packages/rest/src/rest.server.ts
=> chore: fix more tsdoc tags in comments

packages/authentication/docs/authentication-system.md, packages/authentication/src/__tests__/acceptance/basic-auth-extension.acceptance.ts, packages/authentication/src/__tests__/acceptance/jwt-auth-extension.acceptance.ts, packages/authentication/src/__tests__/fixtures/helper.ts, packages/authentication/src/__tests__/fixtures/sequences/authentication.sequence.ts, packages/authentication/src/__tests__/fixtures/users/user.ts
While working on the shopping cart example refactor, some suggested changes were mentioned.
Bringing `some` of these suggested changes into the @loopback/authentication package.
`improved error handling in sequence`:
https://github.com/strongloop/loopback4-example-shopping/pull/130
`expired token function instead of constant`:
https://github.com/strongloop/loopback4-example-shopping/pull/120#discussion_r284343896 
`firstName and lastName instead of firstname and surname` :
https://github.com/strongloop/loopback4-example-shopping/pull/120#discussion_r284890105 
`userProfile.name should be more flexible with regards to availability of firstName and lastName`  :
https://github.com/strongloop/loopback4-example-shopping/pull/120#discussion_r284864793 
👉 [Read and sign the CLA (Contributor …
=> refactor: change firstname and surname to firstName and lastName

docs/site/Testing-your-application.md
- resolves https://github.com/strongloop/loopback-next/issues/2568
fixed the code sample of `givenEmptyDatabase` for two repositories that have circular dependency
=> docs: update circular dependency of repositories tests

packages/context/src/__tests__/unit/inject.unit.ts, packages/context/src/inject.ts
See https://github.com/strongloop/loopback-next/issues/2946
=> fix(context): allow injection when a class decorator returns a mixin

bin/update-greenkeeper-json.js, greenkeeper.json
=> chore: improve greenkeeper script to skip sandbox and keep other settings

packages/tsdocs/README.md
fix a typo in @loopback/tsdocs/README.MD
=> docs: fix a typo in @loopback/tsdocs/README.MD

docs/site/Examples.md, docs/site/Tutorials.md, docs/site/deployment/Deploying-to-IBM-Cloud.md, docs/site/express-with-lb4-rest-tutorial.md, examples/express-composition/README.md, examples/soap-calculator/README.md, examples/todo-list/README.md, examples/todo/README.md, packages/cli/generators/example/index.js
=> chore: add greeting-app to examples

packages/context/README.md
Add `Examples` section in README.
=> chore(context): add a link to example-context

examples/express-composition/package.json
Updated to correct file location.
=> fix(example-express-composition): update migrate script file location

docs/site/Controller-generator.md, docs/site/Repositories.md, docs/site/tutorials/todo-list/todo-list-tutorial-controller.md, packages/cli/generators/controller/templates/src/controllers/controller-rest-template.ts.ejs, packages/cli/generators/relation/templates/controller-relation-template-has-many.ts.ejs, packages/cli/test/integration/generators/controller.integration.js, packages/cli/test/integration/generators/hasmany.relation.integration.js
=> fix(cli): add type param to Filter and Where

examples/context/README.md, examples/context/fixtures/examples-output.txt, examples/context/src/binding-types.ts, examples/context/src/configuration-injection.ts, examples/context/src/context-chain.ts, examples/context/src/context-observation.ts, examples/context/src/custom-configuration-resolver.ts, examples/context/src/custom-inject-decorator.ts, examples/context/src/custom-inject-resolve.ts, examples/context/src/dependency-injection.ts, examples/context/src/find-bindings.ts, examples/context/src/index.ts, examples/context/src/injection-without-binding.ts, examples/context/src/interceptor-proxy.ts, examples/context/src/parameterized-decoration.ts, examples/context/src/sync-async.ts, examples/context/src/value-promise.ts, packages/context/src/__tests__/unit/value-promise.unit.ts
=> feat(example-context): add sync-async example to resolve bindings

benchmark/src/__tests__/benchmark.integration.ts, benchmark/src/autocannon.ts
-  Ensure the benchmarks pass their own tests. Note that we ARE NOT running the actual benchmarks.
-  ~~upgrade autocannon to 4.0.0 and~~ leverage their new support for promises (see https://github.com/mcollina/autocannon/pull/205).
=> Leverage built-in async support in autocannon + include bechmark tests in the test suite 

examples/context/src/__tests__/acceptance/examples.acceptance.ts
=> chore(example-context): increase timeout for tests

examples/context/package.json, examples/context/src/binding-types.ts, examples/context/src/configuration-injection.ts, examples/context/src/context-chain.ts, examples/context/src/context-observation.ts, examples/context/src/custom-configuration-resolver.ts, examples/context/src/custom-inject-decorator.ts, examples/context/src/custom-inject-resolve.ts, examples/context/src/dependency-injection.ts, examples/context/src/find-bindings.ts, examples/context/src/index.ts, examples/context/src/injection-without-binding.ts, examples/context/src/interceptor-proxy.ts, examples/context/src/parameterized-decoration.ts, examples/context/src/sync-async.ts, examples/context/src/value-promise.ts, examples/context/tslint.build.json, examples/context/tslint.json
=> chore(example-context): clean up eslint comments and tslint files

docs/site/tutorials/soap-calculator/soap-calculator-tutorial-add-controller.md, docs/site/tutorials/soap-calculator/soap-calculator-tutorial-add-datasource.md, docs/site/tutorials/soap-calculator/soap-calculator-tutorial-add-service.md, examples/soap-calculator/README.md
=> docs: fix soap-calculator tutorial

examples/lb3-application/package-lock.json, examples/lb3-application/package.json
Update `loopback` to the latest version.
=> chore(example-lb3-application): update loopback dependency

docs/site/Extending-request-body-parsing.md, packages/rest/src/__tests__/acceptance/validation/validation.acceptance.ts, packages/rest/src/__tests__/unit/parser.unit.ts, packages/rest/src/__tests__/unit/request-body.validator.test.ts, packages/rest/src/index.ts, packages/rest/src/parser.ts, packages/rest/src/providers/parse-params.provider.ts, packages/rest/src/types.ts, packages/rest/src/validation/request-body.validator.ts
=> feat(rest): allows validation (AJV) options to be configured via RequestBodyParserOptions

packages/cli/generators/relation/utils.generator.js, packages/cli/package-lock.json, packages/cli/package.json
=> chore(cli): upgrade to ts-morph 2.3.x

package-lock.json, package.json, packages/build/package-lock.json
Start using https://github.com/lerna/lerna/pull/2104 and get rid of the following warning in our test suite: _ Installing local packages that do not match filters from registry_ 💪 
=> Update lerna to 3.15.0

docs/site/tutorials/soap-calculator/soap-calculator-tutorial-add-controller.md
Update the docs to match the example.
=> fix(docs): update soap calculator controller

docs/site/Command-line-interface.md, docs/site/express-with-lb4-rest-tutorial.md, docs/site/tables/lb4-class-file-naming-convention.html, docs/site/tutorials/soap-calculator/soap-calculator-tutorial-add-controller.md, docs/site/tutorials/soap-calculator/soap-calculator-tutorial-add-datasource.md, docs/site/tutorials/todo-list/todo-list-tutorial-controller.md, docs/site/tutorials/todo-list/todo-list-tutorial-model.md, docs/site/tutorials/todo-list/todo-list-tutorial-repository.md, docs/site/tutorials/todo/todo-tutorial-controller.md, docs/site/tutorials/todo/todo-tutorial-datasource.md, docs/site/tutorials/todo/todo-tutorial-geocoding-service.md, docs/site/tutorials/todo/todo-tutorial-model.md, docs/site/tutorials/todo/todo-tutorial-repository.md
- update docs for the new naming convention
- Add naming convention section in CLI main page
resolves https://github.com/strongloop/loopback-next/issues/2644
=> docs: update docs for the new naming convention

docs/site/Command-line-interface.md, docs/site/tutorials/soap-calculator/soap-calculator-tutorial-add-controller.md
fix typos in https://github.com/strongloop/loopback-next/pull/3084
=> docs: fix typos

docs/site/DEVELOPING.md
=> docs: describe RenovateBot process

docs/site/tutorials/soap-calculator/soap-calculator-tutorial-add-controller.md
See https://github.com/strongloop/loopback.io/pull/845 and resolves https://github.com/strongloop/loopback-next/issues/3060.
=> fix(docs): fix soap calculator controller parameters

packages/build/test/integration/scripts.integration.js
=> test(build): remove generated tsconfig.tsbuildinfo to force build

docs/site/DEVELOPING.md
Remove the paragraph about editing commit authors to pass CLA checks, RenovateBot has signed our CLA :)
=> docs: simplify RenovateBot docs

examples/context/package.json, examples/greeting-app/package.json, packages/eslint-config/package.json
Mark the new repos to be private to avoid publishing them.
=> chore: mark new repos private to avoid publish

docs/site/decorators/Decorators_authenticate.md
Change options type from Object to object
Related to : https://github.com/strongloop/loopback-next/issues/2940 
=> docs: fix options type

packages/cli/package.json
Fixes https://github.com/strongloop/loopback-next/issues/3187
=> Lock inquirer to 6.3.1

labs/authentication-passport/README.md, labs/authentication-passport/src/__tests__/acceptance/authentication-with-passport-strategy-adapter.acceptance.ts
- I setup a sample app on local to test the released lab package, found some missing part, so create a PR to add them
- Update the sequence to be consistent with others in our docs/tests. cc @emonddr 
=> Labs dev/passport adapter

docs/site/Loopback-component-authentication.md, packages/authentication/README.md
connect to https://github.com/strongloop/loopback-next/issues/3183
Add  "creating and registering passport based strategies" in our doc.
=> docs: add passport adapter

docs/site/tutorials/authentication/Authentication-Tutorial.md
change the link to fix git@github.com: Permission denied (publickey).
fix #3314
=> docs: change loopback4-example-shopping clone link

examples/greeter-extension/README.md
Updating README to reflect the code.
=> fix(example-greeter-extension): use `@config` for configuration injection in README

docs/site/decorators/Decorators_repository.md, docs/site/tutorials/todo-list/todo-list-tutorial-model.md, examples/todo-list/src/models/todo-list-image.model.ts, examples/todo-list/src/models/todo-list.model.ts
Make foreign key property required and other relational properties optional
=> Make foreign key property required and other relational properties optional

docs/site/Relations.md, docs/site/sidebars/lb4_sidebar.yml, docs/site/tables/lb4-artifact-commands.html
Add references to the `Relation-generator.md` file. 
=> docs: add references to relation generator doc

README.md
Update the status of different versions of LB in README. 
=> chore: update README to reflect LTS status

packages/authorization/README.md, packages/authorization/src/__tests__/acceptance/authorization.options.acceptance.ts, packages/authorization/src/authorization-component.ts, packages/authorization/src/authorize-interceptor.ts, packages/authorization/src/keys.ts, packages/authorization/src/types.ts
See https://github.com/strongloop/loopback-next/issues/3555
=> feat(authorization): add options to improve decision making

packages/context/src/__tests__/unit/interceptor.unit.ts
=> chore(context): only test interceptor order if sort is stable

packages/repository/src/__tests__/unit/repositories/legacy-juggler-bridge.unit.ts, packages/repository/src/repositories/legacy-juggler-bridge.ts
- Added `registerInclusionResolver` method to `DefaultCrudRepository`
- Added `includeRelatedModels` method to `DefaultCrudRepository`
- modify `find*` methods to use` includeRelatedModels` helper
resolves https://github.com/strongloop/loopback-next/issues/3446
=> feat(repository): add inclusionResolvers to DefaultCrudRepository

packages/http-server/src/__tests__/integration/http-server.integration.ts, packages/http-server/src/http-server.ts, packages/repository/src/common-types.ts, packages/rest/src/__tests__/integration/rest.server.integration.ts, packages/testlab/src/http-server-config.ts
The commits are extracted from (an older version of) https://github.com/strongloop/loopback-next/pull/3614.
=> Fix compilation errors reported by TypeScript 3.6

packages/authentication/src/index.ts, packages/authentication/src/providers/auth-strategy.provider.ts
=> feat(authentication): allow to extend AuthenticationStrategyProvider

README.md
See https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps
=> chore: switch to travis-ci.com

docs/site/Loopback-component-authentication.md
Fixes https://github.com/strongloop/loopback-next/issues/3655
=> docs(breaking-change): Update user profile related docs after adding @loopback/security

packages/authorization/src/__tests__/acceptance/authorization.options.acceptance.ts, packages/authorization/src/authorize-interceptor.ts, packages/authorization/src/types.ts
Implements https://github.com/strongloop/loopback-next/issues/3681
=> feat(authorization): add support for default authorization metadata

packages/cli/generators/datasource/templates/datasource.ts.ejs, packages/cli/test/integration/generators/datasource.integration.js
Implements https://github.com/strongloop/loopback-next/issues/3675
=> feat(cli): add lifecycle support for datasources

docs/site/Interceptors.md
Fixes https://github.com/strongloop/loopback-next/issues/3697
=> docs: fix asGlobalInterceptor refs

CODEOWNERS, MAINTAINERS.md, README.md
=> docs: update loopback core maintainers

docs/site/Importing-LB3-models.md
A follow-up for https://github.com/strongloop/loopback-next/pull/3688, see also  #2480
=> docs(cli): describe LB3 model settings ignored during import

packages/cli/generators/model/index.js
Fixes https://github.com/strongloop/loopback-next/issues/3831
=> fix(cli): make sure properties are correctly generated

docs/ROADMAP.md
Roadmap for 2019Q4
@raymondfeng @bajtos, this is based on the box note that we were working together.  Please feel free to update this PR. Thanks. 
=> feat(docs): add 2019Q4 roadmap

docs/site/Command-line-interface.md
See https://github.com/strongloop/loopback-next/issues/3608
=> docs: add a section to cover project dependency upgrade after scaffolding

packages/cli/snapshots/integration/generators/relation.belongs-to.integration.snapshots.js, packages/cli/snapshots/integration/generators/relation.has-many.integration.snapshots.js, packages/cli/test/integration/generators/relation.belongs-to.integration.js, packages/cli/test/integration/generators/relation.has-many.integration.js
Update hasMany and belongsTo generator tests with snapshots.
=> refactor(cli): update cli-relation tests with snapshots

packages/cli/snapshots/integration/generators/relation.belongs-to.integration.snapshots.js, packages/cli/snapshots/integration/generators/relation.has-many.integration.snapshots.js, packages/cli/test/integration/generators/relation.belongs-to.integration.js, packages/cli/test/integration/generators/relation.has-many.integration.js
Remove some redundant tests in belongsTo and hasMany cli generator tests
=> test(cli): remove redundant tests and fix typos/titles

packages/cli/snapshots/integration/generators/relation.belongs-to.integration.snapshots.js, packages/cli/snapshots/integration/generators/relation.has-many.integration.snapshots.js, packages/cli/test/integration/generators/relation.belongs-to.integration.js, packages/cli/test/integration/generators/relation.has-many.integration.js
=> fix(cli): fix typo in cli relation tests

docs/site/tutorials/core/1-introduction.md, docs/site/tutorials/core/11-summary.md, docs/site/tutorials/core/2-architecture.md, docs/site/tutorials/core/3-context-in-action.md, docs/site/tutorials/core/index.md
Update the core tutorial in `core-tutorial`.
=> fix(docs): update core-tutorial

packages/cli/generators/service/templates/local-service-class-template.ts.ejs, packages/cli/test/integration/generators/local-service.integration.js
=> fix(cli): append "Service" in service generator

docs/site/tutorials/core/4-dependency-injection.md, docs/site/tutorials/core/5-extension-point-extension.md
This PR is created against the `core-tutorial` which is coming from PR https://github.com/strongloop/loopback-next/pull/2939. 
=> fix(docs): core tutorial part 4 and 5

docs/site/tutorials/core/10-advanced-recipes.md, docs/site/tutorials/core/6-interception.md, docs/site/tutorials/core/7-observation.md, docs/site/tutorials/core/8-configuration.md, docs/site/tutorials/core/9-boot-by-convention.md
This PR is created against the core-tutorial which is coming from PR #2939.
=> Clean up core-tutorial - part 6 - 10

docs/site/HasMany-relation.md, docs/site/hasOne-relation.md
- Enhance the  explanations for relation metadata
- Add 2-3 cases of customizing id/foreign key names via the metadata for `hasMany` and `hasOne` relations.
=> docs: update keyFrom, keyTo for hasMany and hasOne relations

packages/http-caching-proxy/src/__tests__/integration/http-caching-proxy.integration.ts
Fixes https://ci.appveyor.com/project/strongloop/loopback-next/builds/28304852
=> chore(http-caching-proxy): fix getaddrinfo error assertion

docs/site/Testing-your-application.md, examples/rpc-server/tsconfig.build.json, packages/repository/src/__tests__/unit/mixins/repository.mixin.unit.ts, packages/repository/src/mixins/repository.mixin.ts, packages/rest/src/__tests__/unit/rest.server/rest.server.unit.ts, packages/rest/src/rest.server.ts, packages/service-proxy/src/mixins/service.mixin.ts
Cherry-pick typing fixes from #3858 
=> Fix typings for ts 3.7

packages/repository/src/__tests__/unit/repositories/relations-helpers/resolve-belongs-to-metadata.unit.ts, packages/repository/src/__tests__/unit/repositories/relations-helpers/resolve-has-many-metadata.unit.ts, packages/repository/src/__tests__/unit/repositories/relations-helpers/resolve-has-one-metadata.unit.ts
See https://github.com/strongloop/loopback-next/pull/4046#pullrequestreview-314029460.
=> test(repository): move integration `resolve{Relation}Metadata` tests to unit tests

acceptance/repository-mongodb/package.json, acceptance/repository-mysql/package.json, acceptance/repository-postgresql/package.json
=> chore: update dev dependencies for acceptance test packages

docs/site/Binding.md
=> feat(docs): explain justification of binding scopes and add examples

packages/cli/generators/example/index.js, packages/eslint-config/eslintrc.js
Cross-posting from https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-extra-non-null-assertion.md:
Examples of **incorrect** code for this rule:
```ts
const foo: { bar: number } | null = null;
const bar = foo!!!.bar;
```
```ts
function foo(bar: number | undefined) {
const bar: number = bar!!!;
}
```
Examples of **correct** code for this rule:
```ts
const foo: { bar: number } | null = null;
const bar = foo!.bar;
```
```ts
function foo(bar: number | undefined) {
const bar: number = bar!;
}
```
- Code conforms with the [style …
=> feat(eslint-config): enable no-extra-non-null-assertion

docs/site/Tutorials.md
=> chore(docs): add core series to the home page of tutorials

docs/site/exposing-graphql-apis.md
- update the mutation query that works
- fix the formatting 
=> fix(docs): update graphql mutation command

docs/site/migration/express-middleware.md, examples/lb3-application/README.md, examples/lb3-application/index.js, examples/lb3-application/lb3app/server/boot/routes.js, examples/lb3-application/lb3app/server/config.json, examples/lb3-application/lb3app/server/middleware.json, examples/lb3-application/package-lock.json, examples/lb3-application/package.json, examples/lb3-application/public/index.html, examples/lb3-application/src/__tests__/acceptance/home-page.acceptance.ts, examples/lb3-application/src/__tests__/acceptance/lb3app.acceptance.ts, examples/lb3-application/src/__tests__/acceptance/test-helper.ts, examples/lb3-application/src/application.ts, examples/lb3-application/src/index.ts, examples/lb3-application/src/migrate.ts, examples/lb3-application/src/server.ts
Document how to migrate middleware from LB3 to LB4. Addresses https://github.com/strongloop/loopback-next/issues/3947.
=> docs:  migrate Express middleware from LB3 to LB4

examples/lb3-application/README.md
Addresses:
- https://github.com/strongloop/loopback-next/pull/4056#discussion_r356241938
- https://github.com/strongloop/loopback-next/pull/4056#discussion_r356242691
=> fix: fixed formatting issues

benchmark/package-lock.json, benchmark/package.json, benchmark/src/__tests__/benchmark.integration.ts, benchmark/src/autocannon.ts, benchmark/src/benchmark.ts, benchmark/src/worker.ts, package.json
- add `benchmark` package to `npm test` 
- add autocannon typings 
- improve the code handling worker startup to detect & reporterrors 
- make "create todo" scenario pass
=> Fix benchmark + add it to `npm test`

docs/site/Update-generator.md, docs/site/sidebars/lb4_sidebar.yml
=> chore(docs): add `lb4 update` to sidebar

examples/todo-list/README.md
The previous command was generating the final result instead of where the previous project left off.
=> docs: fix todo-list tutorial command

extensions/authentication-passport/README.md, extensions/authentication-passport/src/__tests__/acceptance/authentication-with-passport-strategy-adapter.acceptance.ts, extensions/authentication-passport/src/__tests__/unit/passport-strategy-adapter.unit.ts, extensions/authentication-passport/src/strategy-adapter.ts, packages/authentication/package-lock.json, packages/authentication/package.json, packages/authentication/src/__tests__/acceptance/basic-auth-extension.acceptance.ts, packages/authentication/src/__tests__/acceptance/jwt-auth-extension.acceptance.ts, packages/authentication/src/__tests__/fixtures/helper.ts, packages/authentication/src/__tests__/fixtures/services/basic-auth-user-service.ts, packages/authentication/src/__tests__/fixtures/services/jwt-service.ts, packages/authentication/src/__tests__/unit/types/user-profile-factory.unit.ts, packages/authentication/src/keys.ts, packages/authentication/src/types.ts
Provide a user profile factory function that takes in
a user and outputs a user profile.
Connect to: https://github.com/strongloop/loopback-next/issues/3846
=> feat: add user profile factory code

docs/site/HasMany-relation.md, docs/site/hasOne-relation.md
fix comment and add warnings in hasMany and HasOne
=> docs: fix comment and add warnings

docs/site/Loopback-component-authorization.md
issue https://github.com/strongloop/loopback-next/issues/4291
=> docs: fix authorization doc and improve readability

packages/model-api-builder/index.d.ts, packages/model-api-builder/package.json
=> fix(model-api-builder): fix project setup so that tsdocs can be generated

README.md
correct apidocs broken link
Fixes #4422
=> fix(docs): apidocs link in /README.md

docs/site/deployment/Deploy-for-GDPR-readiness.md
=> docs(docs): remove dev preview disclaimer

packages/tsdocs/src/index.ts
=> docs(tsdocs): fixed package docs typos

docs/site/Binding.md, packages/context/src/__tests__/unit/binding.unit.ts, packages/context/src/binding.ts
=> feat(context): make bindings as event emitters to report changes

docs/ROADMAP.md
Add 2020 goals and focus to the roadmap.
cc @bajtos @raymondfeng , per our conversation. 
=> fix(docs): add 2020 goals to roadmap

packages/tsdocs/src/update-api-md-docs.ts
=> fix(tsdocs): use unscoped package name as the key to locate the url

packages/repository/src/common-types.ts
alter CountSchema title to be consistent with repository-json-schema titles
See also #4240
=> refactor(repository): alter CountSchema title case

docs/site/Loopback-component-authorization.md
=> fix(docs): correct errors in sample code

.travis.yml
=> fix: remove cloudant-repo-tests temporary from travis due to unavailable docker img

packages/core/src/lifecycle.ts
- This can leverage tag index for bindings to match life cycle observers
=> chore(core): use tag filter for life cycle observers

docs/site/BelongsTo-relation.md, docs/site/Relations.md, docs/site/migration/models/relations.md, docs/site/sidebars/lb4_sidebar.yml, docs/site/tutorials/todo-list/todo-list-tutorial-has-one-relation.md, docs/site/tutorials/todo-list/todo-list-tutorial-relations.md
Update TodoList tutorial hasOne relation with the new added CLI
=> docs: update todoList tutorial with hasOne CLI

CODEOWNERS
This year, I set a goal for myself to find a way how to spend less time on reviewing code and have more time for implementing new features and other activities pushing the framework further. After discussing the idea with @dhmlau, we decided that the first step is to enable other core maintainers (especially in @strongloop/sq-lb-apex) to take on more responsibility & ownership of various parts of the codebase (the functional areas).
We have discussed the functional areas and new owners internally within the IBM team first. Now in this pull request, I am reworking the content of CODEOWNERS file to keep track of the Functional Areas and their Owners we identified in our discussion. I expect the list of owners to evolve over time, it's not necessary to get it perfect on the first try. …
=> docs: rework CODEOWNERS into a list of Functional Areas & Owners

docs/site/Loopback-component-authorization.md
Some relative links were not formatted properly; clicking
them didn't work. They are working now.
=> docs: fix links in authorization doc

README.md
Welcome on board, @frbuceta! 🎉 
=> chore: add frbuceta to the list of maintainers

packages/cli/generators/project/templates/DEVELOPING.md
This PR corrects a typo in the documentation in `packages/cli/generators/project/templates/DEVELOPING.md`. It does not affect actual operation.
`packages/cli/generators/project/templates/DEVELOPING.md`
L28: `continous` -> `continuous`
I tried to accept the CLA but got a 504 error. I will try again at a different time.
=> chore: fix typo 'continous' -> 'continuous'

packages/cli/generators/app/index.js, packages/cli/generators/controller/index.js, packages/cli/intl/en/messages.json, packages/cli/lib/globalize.js, packages/cli/package-lock.json, packages/cli/package.json
Originated from #4493.
This PR extract messages from the app generator and controller generator.
Once this PR lands, I'll extract messages from the other generators in one PR.
- I didn't add more tests. I assume we need to get the messages translated and then add tests?
=> fix(cli): extract messages for generators

packages/rest/src/__tests__/acceptance/file-upload/file-upload.acceptance.ts
=> test(rest): improve the file upload test with more than one files

packages/cli/lib/artifact-generator.js, packages/cli/lib/base-generator.js
While working on https://github.com/strongloop/loopback-next/issues/4425, I needed to add more logging to better understand what's going on inside our code. In this pull request, I am adding those new log statements as permanent debug logs and also improving error messages reported when no interactive prompts are allowed. …
=> feat(cli):  improve logging from processing of config & options

MAINTAINERS.md, README.md
=> chore: add mschnee to the list of maintainers

packages/repository/src/define-model-class.ts, packages/rest-crud/src/crud-rest.controller.ts, packages/rest-crud/src/repository-builder.ts
Fixes https://github.com/strongloop/loopback-next/issues/4631
=> chore: fix tsdoc comments so that apidocs can be rendered correctly

docs/site/Model.md, packages/repository-json-schema/src/__tests__/integration/build-schema.integration.ts
See https://github.com/strongloop/loopback-next/issues/4645
=> test(repository-json-schema): add a test case for @property.array

packages/context/src/__tests__/unit/context.unit.ts, packages/context/src/context.ts
Classes with the same name can be declared and bound from different scopes
or modules. For inspection, we need to have unique names to treat them
differently.
=> feat(context): improve ctx.inspect() to allow classes with colliding names

docs/site/DEVELOPING.md
=> chore: update minimum node.js version

docs/site/Discovering-models.md
=> chore: update pre-discover warning

docs/site/DEVELOPING.md, sandbox/README.md
=> chore(docs): clarify on usage of packages via monorepo

packages/build/README.md
=> chore(build): remove references to 'lb-tslint'

packages/context/src/binding-filter.ts
The generic parameter was not used, it was preserved for backwards compatibility only.
The type `BindingFilter` is no longer generic. Please update your code and remove any generic arguments provided for the type.
```diff
- BindingFilter<SomeType>
+ BindingFilter
```
=> feat(context): remove generic parameters from `BindingFilter` type

docs/site/Controllers.md
Updated Controllers.md to enhance readability of error message
=> fix(docs): enhanced readability of error message in controllers

README.md, SECURITY.md
Add clarity on the security policies for the LoopBack framework.
See:
- https://github.com/nodejs/package-maintenance/blob/master/docs/drafts/security-guidelines.md#publishing-the-policy
- https://help.github.com/en/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository
=> chore: add security policy

packages/rest/src/__tests__/integration/rest.server.integration.ts, packages/rest/src/__tests__/unit/rest.server/rest.server.open-api-spec.unit.ts, packages/rest/src/keys.ts, packages/rest/src/rest.server.ts
=> feat(rest): allow controllers to be added or removed after server start

docs/site/tutorials/authentication/Authentication-Tutorial.md
=> Update Authentication-Tutorial.md with JWT specific info

package.json, packages/build/bin/run-mocha.js, packages/build/test/integration/scripts.integration.js, packages/cli/package.json
Fixes https://github.com/strongloop/loopback-next/issues/4487
=> feat: set LANG for mocha tests

packages/cli/snapshots/integration/generators/relation.belongs-to.integration.snapshots.js, packages/cli/snapshots/integration/generators/relation.has-many.integration.snapshots.js, packages/cli/snapshots/integration/generators/relation.has-one.integration.snapshots.js, packages/cli/test/integration/generators/relation.belongs-to.integration.js
The format difference didn't fail the test. But it's better to make it
consistent with what's produced by `UPDATE_SNAPSHOTS=1 npm t`.
=> chore(cli): update snapshots for relation related tests

docs/site/BelongsTo-relation.md, docs/site/HasMany-relation.md, docs/site/HasOne-relation.md, docs/site/Relations.md
Refactors the relation limitation section. 
=> docs: refactors the relation limitation section

docs/site/HasOne-relation.md, packages/repository/src/relations/belongs-to/belongs-to.repository.ts, packages/repository/src/relations/has-one/has-one.repository.ts
Updates  API docs to match with currently design.
=> docs: update relations' api docs

docs/site/deployment/Deploying_to_ibm_cloud_kubernetes.md, examples/access-control-migration/public/index.html, examples/express-composition/public/express.html, examples/express-composition/public/index.html, examples/lb3-application/public/index.html, examples/soap-calculator/public/index.html, examples/todo-list/public/index.html, examples/todo/public/index.html, packages/cli/generators/app/templates/public/index.html.ejs
Remove any references for `v4.loopback.io`.  It includes:
- docs
- examples
- cli template
=> fix: remove ref for v4.loopback.io

packages/repository/src/__tests__/fixtures/mixins/find-by-title-repo-mixin.ts, packages/rest/package-lock.json, packages/rest/src/__tests__/fixtures/mixins/find-by-title-controller-mixin.ts
See https://github.com/strongloop/loopback-next/pull/4723
This PR contains suggested changes to #4723 to simplify the review process.
@emonddr If you agree with the suggestions, please simply merge this PR into your feature branch.
=> chore: suggest changes to improve #4723

README.md
See https://github.com/strongloop/loopback/issues/4306
=> docs: update LTS info in root README

docs/site/migration/models/mixins.md, packages/repository/src/__tests__/fixtures/mixins/base-entity.ts, packages/repository/src/__tests__/fixtures/mixins/category-property-mixin.ts, packages/repository/src/__tests__/fixtures/mixins/find-by-title-repo-mixin.ts, packages/repository/src/__tests__/fixtures/models/note.model.ts, packages/repository/src/__tests__/fixtures/repositories/note.repository.ts, packages/repository/src/__tests__/unit/mixins/add-method-to-repository.mixin.unit.ts, packages/repository/src/__tests__/unit/mixins/model.mixin.unit.ts, packages/repository/src/__tests__/unit/mixins/repository.mixin.unit.ts, packages/rest/src/__tests__/fixtures/controllers/note.controller.ts, packages/rest/src/__tests__/fixtures/mixins/find-by-title-controller-mixin.ts, packages/rest/src/__tests__/fixtures/models/note.model.ts, packages/rest/src/__tests__/fixtures/repositories/note.repository.ts, packages/rest/src/__tests__/integration/controller.mixin.unit.ts
Related to : https://github.com/strongloop/loopback-next/issues/3951
=> docs: migrating lb3 model property mixins, and custom model method/remote method mixins to lb4

docs/site/Mixin.md
=> chore: update Mixin.md

CODEOWNERS
`booter-lb3-app` -> `booter-lb3app`
=> fix: fix booter-lb3app entry in CODEOWNERS

docs/ROADMAP.md
Q2 roadmap. 
@raymondfeng @bajtos, per our discussion yesterday.
cc @strongloop/loopback-maintainers 
=> feat(docs): add 20202Q2 roadmap

docs/site/Relations.md
Remove the closed issue from the limitation section.
=> docs: update the limitation section of relations

docs/site/Binding.md
See https://github.com/strongloop/loopback-next/pull/4822
@King-Success Thank you for catching the error.
=> fix(docs): fix typo for Binding.md

docs/site/Creating-CRUD-REST-apis.md, docs/site/sidebars/lb4_sidebar.yml
=> feat(docs): add readme reference for @loopback/rest-crud under `Using Components`

acceptance/extension-logging-fluentd/package-lock.json, acceptance/repository-cloudant/package-lock.json, acceptance/repository-mongodb/package-lock.json, acceptance/repository-mysql/package-lock.json, acceptance/repository-postgresql/package-lock.json, benchmark/package-lock.json, docs/site/Examples.md, examples/access-control-migration/README.md, examples/access-control-migration/package-lock.json, examples/lb3-application/package-lock.json, examples/rest-crud/package-lock.json, examples/soap-calculator/package-lock.json, examples/todo-list/package-lock.json, examples/todo/package-lock.json, extensions/cron/package-lock.json, package-lock.json, packages/authentication/package-lock.json, packages/boot/package-lock.json, packages/booter-lb3app/package-lock.json, packages/cli/package-lock.json, packages/repository/package-lock.json, packages/rest/package-lock.json, packages/service-proxy/package-lock.json, packages/testlab/package-lock.json
Add missing examples to Example page: https://loopback.io/doc/en/lb4/Examples.html.
Since there are quite a lot of examples, so I did some categorization as well.
cc @raymondfeng @nabdelgadir 
=> fix(docs): update examples page

packages/context/src/__tests__/unit/context-view.unit.ts, packages/context/src/context-view.ts
This further improves #4916 
- Change cached values to a map with binding/value pairs
- Return a shallow copy of cached values so that the cache won't be mutated
- Include `cachedValue` for `unbind` event. This is useful for fine-grained
invalidation of cache
I'm adding this feature to support a use case in `extension point/extension` pattern to allow fine-grained
handling of an extension being removed. For example, if a cron job is removed after the app starts, we can stop the resolved instance if it exists.
=> feat(context): improve context view for bind/unbind events and cached values

packages/repository-json-schema/src/__tests__/unit/build-schema.unit.ts, packages/repository/src/decorators/metadata.ts
Fixes https://github.com/strongloop/loopback-next/issues/4721
=> fix(repository-json-schema): fix schema generation for model inheritance

extensions/logging/src/decorators/logging.decorator.ts, packages/cli/generators/relation/utils.generator.js, packages/http-server/src/http-server.ts, packages/metadata/src/decorator-factory.ts, packages/repository/src/relations/relation.helpers.ts
tsdoc is slightly different from jsdoc. See a list of valid tsdoc tags at:
https://github.com/microsoft/tsdoc/blob/master/tsdoc/src/details/StandardTags.ts
=> chore: fix invalid tags in tsdocs

docs/.npmignore, docs/package.json, docs/site/Running-cron-jobs.md, docs/site/Using-components.md, docs/site/sidebars/lb4_sidebar.yml
=> Improve docs module and fix component docs

packages/cli/generators/project/templates/package.json.ejs, packages/cli/generators/project/templates/package.plain.json.ejs, packages/cli/test/integration/generators/app.integration.js, packages/cli/test/integration/lib/project-generator.js
Fix indentation for generated `package.json`. 
=> fix(cli): make sure generated package.json is well formatted

packages/repository-json-schema/src/__tests__/integration/build-schema.integration.ts, packages/repository-json-schema/src/build-schema.ts
Fixes https://github.com/strongloop/loopback-next/issues/4938
=> fix(repository-json-schema): honor options for referenced types

README.md
=> fix(docs): use new apidocs link in readme

docs/site/sidebars/lb4_sidebar.yml
Update the sidebar to include the OpenAPI connector under the [Connector Reference](https://loopback.io/doc/en/lb4/Connectors-reference.html).  
Related to: https://github.com/strongloop/loopback.io/pull/960
=> fix(docs): update sidebar for OpenAPI connector

docs/site/Request-response-cycle.md, docs/site/sidebars/lb4_sidebar.yml
Added link to LB4 req-res doc along with some typo fixes. Forgot to add side bar link in https://github.com/strongloop/loopback-next/pull/4914.
=> docs: side bar link to LB4 req-res doc

README.md
Replaces community chat link from Gitter to Slack workspace
see #5048
=> chore: replaces community chat

docs/site/Copyright-generator.md, packages/cli/generators/copyright/index.js
=> feat(cli): print options for `lb4 copyright --help` and update docs

packages/cli/bin/cli-main.js
=> fix(cli): allow `-h` for help

docs/site/FAQ.md, docs/site/sidebars/lb4_sidebar.yml
=> chore(docs): updates FAQ

docs/site/sidebars/lb4_sidebar.yml
Adds Mixins page to lb4 sidebar to increase accessibility.
Loosely-related: #4759
=> chore(docs): add Mixins to sidebar

docs/site/Calling-other-APIs-and-Web-Services.md
Related to: https://github.com/strongloop/loopback-next/issues/4488
Add the instructions to call REST service with OpenAPI connector in the [Calling Other APIs and web service page](https://loopback.io/doc/en/lb4/Calling-other-APIs-and-web-services.html).
**Question to reviewers**
I have an example repo working: https://github.com/dhmlau/openapi-test2. Not sure if it's a good idea to put in our `examples` directory. I think it would be helpful to include a full application, but also concerned about too many examples added to this repo. 
The alternative is that we can eventually have an example on how to call REST and SOAP services mentioned in https://loopback.io/doc/en/lb4/Calling-other-APIs-and-web-services.html. I do have another working repo: …
=> fix(docs): add OpenAPI DataSource instructions

examples/access-control-migration/package-lock.json, examples/context/package-lock.json, examples/express-composition/package-lock.json, examples/file-transfer/package-lock.json, examples/greeter-extension/package-lock.json, examples/greeting-app/package-lock.json, examples/hello-world/package-lock.json, examples/lb3-application/package-lock.json, examples/log-extension/package-lock.json, examples/metrics-prometheus/package-lock.json, examples/rest-crud/package-lock.json, examples/rpc-server/package-lock.json, examples/soap-calculator/package-lock.json, examples/todo-list/package-lock.json, examples/todo/package-lock.json, examples/validation-app/package-lock.json, package-lock.json, packages/booter-lb3app/package-lock.json, packages/build/package-lock.json, packages/cli/package-lock.json, packages/testlab/package-lock.json
=> chore: update package-lock.json files to prepare for a new release

lerna.json
See https://github.com/lerna/lerna#legacy-fields
=> chore: remove deprecated lerna field

extensions/authentication-passport/package-lock.json, extensions/authentication-passport/package.json, extensions/authentication-passport/src/__tests__/acceptance/fixtures/mock-oauth2-social-app.ts
Fix tsc compilation errors with latest dependencies.
=> fix(authentication-passport): fix typing issues for oAuth2 mock app

docs/site/migration/models/remoting-hooks.md
Updating lb3 remote hooks code in modifying request parameters section.
- [ x] `npm test` passes on your machine
- [x ] Documentation in [/docs/site](../tree/master/docs/site) was updated
=> docs: updating modifying request parameters

packages/cli/lib/connectors.json
=> chore: upgrade to loopback-connector-openapi@5.x

packages/rest/src/__tests__/acceptance/request-parsing/request-parsing.acceptance.ts, packages/rest/src/body-parsers/index.ts
=> test(rest): add a test to show how to validate a hash for incoming requests

.github/ISSUE_TEMPLATE/Bug_report.md, .github/ISSUE_TEMPLATE/Migration_docs.md, .github/ISSUE_TEMPLATE/Question.md, examples/access-control-migration/README.md, examples/lb3-application/README.md, examples/todo/README.md
=> chore: removes gitter, adds slack

packages/rest/src/rest.server.ts
=> chore(rest): import deepClone from lodash

packages/context/src/binding-inspector.ts, packages/context/src/interception-proxy.ts, packages/core/src/application.ts
=> feat: improve generic typing for context/core

docs/site/Calling-other-APIs-and-Web-Services.md, docs/site/Querying-data.md, docs/site/sidebars/lb4_sidebar.yml, docs/site/tutorials/authentication/Authentication-Tutorial.md, docs/site/tutorials/soap-calculator/soap-calculator-tutorial-scaffolding.md, docs/site/tutorials/todo-list/todo-list-tutorial-relations.md, docs/site/tutorials/todo-list/todo-list-tutorial-sqldb.md
Fix broken links and formatting
=> fix(docs): fix broken links and formatting

packages/cli/generators/openapi/spec-loader.js, packages/cli/test/fixtures/openapi/3.0/customer.yaml
=> fix(cli): check if the object is `null` for OpenAPI spec cloning

docs/site/Repositories.md, docs/site/decorators/Decorators_inject.md, docs/site/decorators/Decorators_openapi.md, docs/site/decorators/Decorators_repository.md
Using https://www.npmjs.com/package/broken-link-checker to detect broken links. 
Fix broken links in the LB4 docs. 
=> fix(docs): fix broken links

docs/site/decorators/Decorators_openapi.md
Update the hardcoded openapi decorator links
=> docs: update decorator links

examples/passport-login/.gitignore, examples/passport-login/data/db.json, examples/passport-login/src/index.ts
=> fix: remove memory backup file from example-passport-login tests

packages/cli/lib/base-generator.js
The menu options are undefined:
After fixing ( translatable):
=> fix: fixes help menu undefined options

bin/update-ts-project-refs.js
Do not rewrite tsconfig files that are up to date.
=> feat: improve update-ts-project-refs.js to skip updating identical files

docs/site/Working-with-data.md, docs/site/sidebars/lb4_sidebar.yml
=> refactor: reposition working with data pages

CODEOWNERS
Assign this part of our monorepo to "Internal Tooling" functional area.
=> chore: add CODEOWNERS entry for `/bin`

docs/site/migration/cli.md, docs/site/migration/tables/lb3-lb4-command-mappings.html, docs/site/migration/tables/lb3-only-commands.html, docs/site/migration/tables/lb4-only-commands.html
Describe the similarities and differences between
the LB3 and LB4 command line interfaces
Related to : https://github.com/strongloop/loopback-next/issues/3953 
The best way to view this document is to:
- clone this repository 
- switch to the `dremond_cli_migration_doc` branch
- npm install
- npm run build
- npm run docs:prepare
- npm run docs:start
This will start a document server on your machine.
Navigate to `Navigation > CLI` section of LoopBack 4 documentation.
=> docs: differences between lb3 and lb4 cli

docs/site/Fields-filter.md, docs/site/Include-filter.md, docs/site/Limit-filter.md, docs/site/Order-filter.md, docs/site/Querying-data.md, docs/site/Skip-filter.md, docs/site/Where-filter.md, docs/site/Working-with-data.md
=> fix(docs): fix querying data layout

examples/access-control-migration/package-lock.json, examples/context/package-lock.json, examples/express-composition/package-lock.json, examples/file-transfer/package-lock.json, examples/greeter-extension/package-lock.json, examples/greeting-app/package-lock.json, examples/hello-world/package-lock.json, examples/lb3-application/package-lock.json, examples/log-extension/package-lock.json, examples/metrics-prometheus/package-lock.json, examples/multi-tenancy/package-lock.json, examples/passport-login/package-lock.json, examples/rest-crud/package-lock.json, examples/rpc-server/package-lock.json, examples/soap-calculator/package-lock.json, examples/todo-list/package-lock.json, examples/todo/package-lock.json, examples/validation-app/package-lock.json, extensions/authentication-jwt/package-lock.json, package-lock.json, packages/build/package-lock.json, packages/cli/package-lock.json
To pick up a fix from `is-promise`.
=> chore: update package-lock.json files

packages/cli/package-lock.json
=> chore(cli): update package-lock.json to remove inquirer@7.0.x

extensions/apiconnect/src/__tests__/acceptance/apiconnect.acceptance.ts, extensions/apiconnect/src/apiconnect.spec-enhancer.ts, packages/openapi-v3/src/__tests__/unit/enhancers/fixtures/info.spec.extension.ts
Fixes https://github.com/strongloop/loopback-next/issues/5259
=> Fix https://github.com/strongloop/loopback-next/issues/5259

packages/cli/generators/openapi/schema-helper.js, packages/cli/generators/openapi/utils.js, packages/cli/test/unit/openapi/openapi-utils.unit.js
Fixes https://github.com/strongloop/loopback-next/issues/5247
=> fix(cli): mitigate json schema to be draft 7 compatible

docs/site/Model.md, packages/repository-json-schema/src/__tests__/integration/build-schema.integration.ts
Related to https://github.com/strongloop/loopback-next/issues/3033. Taken from https://github.com/strongloop/loopback-next/issues/3033#issuecomment-619103450 (thank you to @zzhenryquezz).
=> docs: add docs for enum type

extensions/context-explorer/src/__tests__/acceptance/context-explorer.acceptance.ts
=> chore(context-explorer): increase timeout for tests for CI builds

packages/repository-json-schema/src/index.ts
=> chore(repository-json-schema): fix typedoc comments

packages/cli/generators/repository/index.js, packages/cli/intl/en/messages.json
"Select the model(s) you want to generate a repository" should be "Select the model(s) you want to generate a repository for".
=> chore: add "for"

docs/site/sidebars/lb4_sidebar.yml
Closes https://github.com/strongloop/loopback-next/issues/5268
=> fix(docs): remove push and storage connectors from lb4 list

packages/repository-json-schema/src/__tests__/integration/build-schema.integration.ts, packages/repository-json-schema/src/__tests__/unit/build-schema.unit.ts, packages/repository-json-schema/src/build-schema.ts, packages/repository/src/__tests__/unit/type/type.unit.ts, packages/repository/src/type-resolver.ts, packages/repository/src/types/index.ts, packages/repository/src/types/null.ts
=> test(repository-json-schema): add a test for nesting models

docs/site/migration/auth/passport.md, examples/passport-login/README.md, examples/passport-login/src/controllers/oauth2.controller.ts, extensions/authentication-passport/src/__tests__/acceptance/README.md, extensions/authentication-passport/src/__tests__/acceptance/authentication-with-passport-strategy-oauth2-adapter.acceptance.ts
issue: https://github.com/strongloop/loopback-next/issues/3958
=> docs: migrate apps using loopback-component-passport

packages/cli/test/acceptance/app-run.acceptance.js
See also https://github.com/strongloop/loopback-next/pull/5230#issuecomment-621934842
=> Add yarn acceptance test

docs/site/Examples.md, packages/cli/generators/example/index.js
The PR adds the `passport-login` to the `lb4 example` command, and update the Examples.md to include this new example.
cc @deepakrkris 
=> fix(cli): add passport-login to example cli

packages/context/src/__tests__/unit/binding-inspector.unit.ts
=> test(context): add tests for isProviderClass() check

docs/site/Working-with-data.md
Fix broken links in https://loopback.io/doc/en/lb4/Working-with-data.html. 
=> fix(docs): fix broken link

docs/site/Binding.md, docs/site/Crafting-LoopBack-4.md, docs/site/decorators/Decorators_inject.md, docs/site/sidebars/lb4_sidebar.yml
Add section to the binding documentation that explains
when it is necessary to use createBindingFromClass
method.
=> docs: improve binding doc with regards to createBindingFromClass method

docs/site/Components.md
=> docs: fix link to Binding.html

docs/site/Sequence.md, packages/express/src/types.ts, packages/rest/src/__tests__/acceptance/sequence/sequence.acceptance.ts, packages/rest/src/sequence.ts
=> fix: update default sequence and docs

CODEOWNERS
=> chore: add code owners for apiconnect extension

docs/site/OpenAPI-generator.md
=> docs: fix OpenAPI md docs listing

extensions/authentication-passport/README.md
Deleted an extra curly brackets in UserProfileFactory example
=> docs: update README.md

extensions/context-explorer/package-lock.json, extensions/context-explorer/package.json, extensions/context-explorer/src/context-graph.ts
This is a fix for the API change of the ts-graphviz library, and some refactoring.
See also #5466 
=> chore(context-explorer): upgrade ts-graphviz, and refactor

docs/site/Components.md
See https://github.com/strongloop/loopback-next/pull/5379
Credit to https://github.com/decooliveira
=> fix(docs): fix typo in Components.md

packages/context/src/__tests__/unit/binding.unit.ts, packages/context/src/binding.ts
We track the source for a binding using multiple properties such as `valueConstructor`, `providerConstructor`, `_alias`. This PR converges it to a `_source` property and have getters to keep backward compatibility. 
This is loosely related to https://github.com/strongloop/loopback-next/issues/5426. To inspect bindings for certain artifacts, being able to access the `source` is useful for extensions to enhance the inspection results.
=> feat(binding): use `_source` to track the original value source for a binding

docs/site/Binding.md, packages/context/src/__tests__/unit/binding-inspector.unit.ts, packages/context/src/binding-inspector.ts, packages/context/src/binding.ts, packages/context/src/keys.ts
=> feat(context): allow bindings to be created from dynamic value provider classes

docs/site/Setting-debug-strings.md, docs/site/Using-strong-error-handler.md, docs/site/sidebars/lb4_sidebar.yml
Implements https://github.com/strongloop/loopback-next/issues/4846
=> docs: add using strong-error-handler page

extensions/authentication-jwt/src/services/security.spec.enhancer.ts
Fix the scheme name
https://github.com/strongloop/loopback-next/pull/5493#discussion_r427659273
=> fix(authentication-jwt): correct the scheme name

packages/cli/generators/relation/templates/controller-relation-template-belongs-to.ts.ejs, packages/cli/snapshots/integration/generators/relation.belongs-to.integration.snapshots.js
=> @loopback/cli: Generate proper relation belongsTo fix #5430

docs/site/Discovering-models.md, docs/site/Relation-generator.md
=> docs: fix inconsistent docs

packages/cli/lib/connectors.json
=> chore: update version of connectors in @loopback/cli package

extensions/authentication-jwt/src/__tests__/acceptance/jwt.component.test.ts, extensions/authentication-jwt/src/models/user-credentials.model.ts, extensions/authentication-jwt/src/models/user.model.ts
unique email for each user. Avoiding multiple user account from single email.
Implements first feature #5536
=> feat(authentication-jwt): unique index email for user.model.ts

docs/site/tutorials/connectors/Postgresql-tutorial.md
=> fix(docs): fix listing error in PostgreSQL tutorial

packages/repository/src/__tests__/unit/query/query-builder.unit.ts, packages/repository/src/query.ts
=> feat(repository): adds fuzzy where filters to WhereBuilder

docs/site/decorators/Decorators_openapi.md
=> feat(docs): adds requestBody.array() docs

packages/boot/src/mixins/boot.mixin.ts, packages/core/src/mixin-target.ts, packages/repository/src/mixins/repository.mixin.ts, packages/service-proxy/src/mixins/service.mixin.ts
See https://loopback.io/doc/en/lb4/apidocs.service-proxy.servicemixin.html
=> chore: fix tsdoc comments for mixin functions

docs/site/tutorials/todo/todo-tutorial-geocoding-service.md
Fixes https://github.com/strongloop/loopback-next/issues/5518
- add imports for todo controller in code snippet
- add links to the file reference
=> fix(example-todo): add imports

docs/site/Authentication-overview.md, docs/site/JWT-authentication-extension.md, extensions/authentication-jwt/README.md
Sub PR for #5598
Add the jwt-extension page with new layout
=> docs: add jwt extension

docs/site/Authentication-overview.md, docs/site/Create-custom-authentication-strategy.md, extensions/authentication-jwt/README.md
connects to https://github.com/strongloop/loopback-next/pull/5598
- Add customizing strategy. 
- I wrote a beginning part, and the rest are copied from [this section](https://loopback.io/doc/en/lb4/Loopback-component-authentication.html#creating-a-custom-authentication-strategy) and [this section](https://loopback.io/doc/en/lb4/Loopback-component-authentication.html#registering-a-custom-authentication-strategy)
=> auth doc refactor - customizing strategy

docs/site/Mixin.md
=> feat(docs): improve clarity of Mixins docs

.gitattributes
As requested in [comment](https://github.com/strongloop/loopback-next/pull/5616#discussion_r435281611
)
=> chore: prevent prettier from overwriting line endings on Windows

packages/boot/src/__tests__/acceptance/application-metadata.booter.acceptance.ts, packages/boot/src/__tests__/acceptance/component-application.booter.acceptance.ts, packages/boot/src/__tests__/acceptance/controller.booter.acceptance.ts, packages/boot/src/__tests__/acceptance/crud-rest.api-builder.acceptance.ts, packages/boot/src/__tests__/acceptance/model-api.booter.acceptance.ts, packages/boot/src/__tests__/fixtures/application.ts, packages/boot/src/__tests__/integration/controller.booter.integration.ts, packages/boot/src/__tests__/integration/datasource.booter.integration.ts, packages/boot/src/__tests__/integration/interceptor.booter.integration.ts, packages/boot/src/__tests__/integration/lifecycle-observer.booter.integration.ts
This reverts #5720 which was landed before a consensus was reached. 
=> Revert: make sure sandbox directories are removed after test

.vscode/launch.json, packages/build/bin/run-mocha.js, packages/build/bin/utils.js, packages/build/config/.mocharc.json
This is a follow-up for #5710 which did not take into account that upgrade to Mocha is a breaking change 😞 
=> feat(build): upgrade to mocha 8.x

packages/tsdocs/package.json
Add a `postinstall` script to re-build the test fixtures using the currently-installed version of TypeScript compiler.
This is a follow-up for #5714 to address the following concern:
>  I'm worried that we forget to rebuild the fixtures during TypeScript upgrade.
Output of `npm install` from monorepo root
```
❯ npm i
> loopback-next@0.1.0 postinstall /Users/bajtos/src/loopback/next
> npm run -s bootstrap && npm run -s update-ts-project-refs
lerna notice cli v3.22.1
lerna info versioning independent
lerna info Bootstrapping 62 packages
lerna info Installing external dependencies
lerna info Symlinking packages and binaries
lerna info lifecycle @loopback/tsdocs@2.2.2~postinstall: @loopback/tsdocs@2.2.2
> @loopback/tsdocs@2.2.2 postinstall /Users/bajtos/src/loopback/next/packages/tsdocs
> npm …
```
=> build(tsdocs): rebuild fixtures after npm install

examples/access-control-migration/src/sequence.ts, examples/express-composition/src/sequence.ts, examples/file-transfer/src/sequence.ts, examples/lb3-application/src/sequence.ts, examples/multi-tenancy/src/sequence.ts, examples/passport-login/src/sequence.ts, examples/rest-crud/src/sequence.ts, examples/soap-calculator/src/sequence.ts, examples/todo-jwt/src/sequence.ts, examples/todo-list/src/sequence.ts, examples/todo/src/sequence.ts, examples/validation-app/src/sequence.ts
Update `src/sequence.ts` to be consistent with cli code generation to avoid subtle bugs where the CORS/OpenAPI spec endpoints are not exposed.
=> feat: update sequence to invoke middleware

docs/site/Booting-an-Application.md, docs/site/Creating-components.md
=> [Docs] adds component supported artifacts table, booter model artifact

packages/repository/src/repositories/legacy-juggler-bridge.ts
=> feat: add HasManyThroughFactory to Juggler bridge

docs/site/Authentication-component-action.md, extensions/authentication-jwt/README.md, extensions/authentication-passport/README.md, extensions/metrics/README.md
Fixes #5739 
1. Fix broken link on the image
2. Fix the layout issue for using `<details>` as collapsible section. I'm fixing other occurrences in this repo.
3. Fix numbering 
=> fix(docs): fix collapsible section

examples/passport-login/README.md
Fixes https://github.com/strongloop/loopback-next/issues/5876
=> fix(example-passport-login): improve README to mention OAUTH_PROVIDERS_LOCATION

packages/cli/generators/model/index.js, packages/cli/intl/en/messages.json
=> fix(cli): globalize strings for model generator

packages/cli/generators/controller/index.js, packages/cli/generators/datasource/index.js, packages/cli/generators/interceptor/index.js, packages/cli/generators/model/index.js, packages/cli/generators/relation/index.js, packages/cli/generators/repository/index.js
=> docs: add no translation terms to generators

packages/authentication/README.md
Update after we restructured the auth docs
connect to https://github.com/strongloop/loopback-next/issues/5294
=> docs(authentication): update readme

examples/access-control-migration/README.md
=> fix: tutorial link

docs/site/Querying-data.md
A update for the proper usage of import of FilterBuilder
=> fix(docs): update Querying-data.md on proper usage of import for FilterBuilder

docs/site/HasManyThrough-relation.md, packages/cli/intl/en/messages.json, packages/cli/lib/base-generator.js
fixes #5955 
Package manager is already being translated.
=> fix: globalize help options

README.md
Welcome @nabdelgadir back to the maintainers' team! 🎉 
=> chore: add Nora as maintainer

docs/site/guides/data-access/transactions.md
Based on our discussion in Maintainers Call, I verified that multiple models can be changed from inside a single transaction. In this pull request, I am updating our docs with instructions.
=> docs: explain how to access multiple models in a single transaction

docs/site/Community-extensions.md
Fixes the soft-delete extension description according to https://github.com/strongloop/loopback-next/pull/5707#discussion_r439019653.
cc @samarpanB 
=> fix(docs): fix extension desc

packages/repository-tests/src/crud/relations/acceptance/has-many-through.relation.acceptance.ts, packages/repository-tests/src/crud/relations/acceptance/has-many.relation.acceptance.ts, packages/repository-tests/src/crud/relations/fixtures/models/address.model.ts, packages/repository-tests/src/crud/relations/fixtures/models/customer.model.ts, packages/repository-tests/src/crud/relations/fixtures/models/index.ts, packages/repository-tests/src/crud/relations/fixtures/models/shipment.model.ts, packages/repository-tests/src/crud/relations/fixtures/models/user-link.model.ts, packages/repository-tests/src/crud/relations/fixtures/models/user.model.ts, packages/repository-tests/src/crud/relations/fixtures/repositories/index.ts, packages/repository-tests/src/crud/relations/fixtures/repositories/user-link.repository.ts, packages/repository-tests/src/crud/relations/fixtures/repositories/user.repository.ts, packages/repository-tests/src/crud/relations/helpers.ts
connects to #5835 
Add tests to prove hasManyThrough supports self through (same source mode and target model).
=> test(repository-tests): add tests for self through

packages/repository/src/__tests__/unit/model/model.unit.ts, packages/repository/src/model.ts
Fixes https://github.com/strongloop/loopback-next/issues/5951
=> fix(repository): convert relation property in toobject

README.md
=> chore: add Madaky as maintainer

docs/site/Authentication-overview.md, docs/site/Examples.md
Add example for https://github.com/strongloop/loopback-next/issues/5573
=> docs: add auth tutorial example

CODEOWNERS
Since @nabdelgadir is one of the community maintainers, I'd like to update the CODEOWNERS file to include some of the areas that she's more heavily involved. 
@nabdelgadir, I don't want to overwhelm you, so only taking some of areas in this commit: https://github.com/strongloop/loopback-next/commit/7c34ac0788f8d03eededb9c566d5c1689cd1c013#diff-5daf978e60e03b3975b485d5f1b449dc. If there are other areas you'd like to get more involved, please let me know. Thanks! 
=> chore: update CODEOWNERS to add Nora

docs/site/Testing-your-application.md, packages/build/README.md
=> fix(docs): fix minor typo

docs/site/Application.md, docs/site/Crafting-LoopBack-4.md, docs/site/Extending-LoopBack-4.md, docs/site/Glossary.md, docs/site/migration/components/project-layout.md, docs/site/migration/not-planned.md, examples/log-extension/README.md, packages/cli/generators/extension/templates/src/providers/README.md
Fixing the broken [using component](https://loopback.io/doc/en/lb4/Application.html#components) links.
=> docs: fix broken using component links

docs/site/migration/models/relations.md
=> docs: update migration guide - relations

docs/site/migration/overview.md
=> docs: fix typo in migration overview

docs/site/LoopBack-types.md, docs/site/sidebars/lb4_sidebar.yml
connects to https://github.com/strongloop/loopback-next/issues/5063
=> docs: add loopback types page

docs/site/Create-other-forms-of-apis.md, docs/site/sidebars/lb4_sidebar.yml
Implements https://github.com/strongloop/loopback-next/issues/5777
Clicked every page to make sure they display properly.
Fold subsections:
Unfold subsections - part 1:
Unfold subsections - part 2:
=> docs: restructuring how to guide

examples/todo/src/controllers/todo.controller.ts
I'm proposing we ignore coverage for this section, because for unrelated PRs, this section will cause the coverage to decrease if the geocoder service is not up and running.
=> chore(example-todo): ignore coverage for geocode

packages/cli/generators/project/templates/package.json.ejs, packages/cli/generators/project/templates/package.plain.json.ejs, packages/cli/lib/project-generator.js, packages/cli/test/integration/lib/project-generator.js
=> feat(cli): improve project templates to be compatible with `yarn`

commitlint.config.js
The PR enables `Signed-off-by` check for commits.
=> feat: check signed-off-by for commits

docs/site/DEVELOPING.md, docs/site/Developing-with-vscode.md, docs/site/Developing-with-webstorm.md, docs/site/REST-action-sequence.md
=> fix: rest action sequence permalink, dev. IDE docs

packages/rest/src/body-parsers/body-parser.ts, packages/rest/src/providers/find-route.provider.ts, packages/rest/src/providers/invoke-method.provider.ts, packages/rest/src/providers/parse-params.provider.ts
=> feat(rest): add more debugging statements for middleware

packages/http-server/package-lock.json, packages/http-server/package.json, packages/http-server/src/http-server.ts
=> feat(http-server): add debugging statements for http-server package

packages/http-server/src/http-server.ts, packages/rest/src/__tests__/unit/rest.server/rest.server.unit.ts, packages/rest/src/rest.server.ts
Fixes https://github.com/strongloop/loopback-next/issues/6170
=> feat(rest): make sure rest options are passed to http-server

docs/site/migration/components/project-layout.md
Fixes a broken link in https://loopback.io/doc/en/lb4/migration-extensions-project-layout.html#loopback-4-layout
=> docs: fix incorrect file name

examples/todo/src/__tests__/acceptance/todo.acceptance.ts, packages/openapi-v3/src/__tests__/unit/decorators/query.decorator.unit.ts, packages/openapi-v3/src/__tests__/unit/filter-schema.unit.ts, packages/repository-json-schema/src/__tests__/unit/filter-json-schema.unit.ts, packages/repository-json-schema/src/filter-json-schema.ts
=> fix(repository-json-schema): allows string-based order filter

extensions/health/src/__tests__/acceptance/health.acceptance.ts, extensions/health/src/observers/health.observer.ts
This is to fix warnings emitted during mocha tests.
(node:93642) MaxListenersExceededWarning: Possible EventEmitter memory
leak detected. 11 SIGTERM listeners added to [process]. Use emitter.setMaxListeners()
to increase limit
=> fix(extension-health): unregister signal listener to avoid potential memory leak

packages/rest/src/__tests__/unit/ajv-factory.provider.unit.ts, packages/rest/src/validation/ajv-factory.provider.ts, packages/rest/src/validation/openapi-formats.ts
=> feat(rest): add AJV formats for OpenAPI spec data type formats

extensions/graphql/tsconfig.json, packages/filter/tsconfig.json
After pulling the latest `master` and running `npm install`, I noticed that a couple of tsconfig files were updated.
This pull request commits those auto-generated changes.
=> chore: fix project references

docs/site/Server.md
Add the instructions to disable CORS according to [this thread](https://loopbackio.slack.com/archives/C01177XQN8N/p1598966073244300) in Slack.
=> fix(docs): add instructions to disable CORS

docs/site/Authentication-overview.md
=> docs: fixes typo in 'Authentication-overview.md'

packages/rest/src/providers/find-route.provider.ts, packages/rest/src/providers/invoke-method.provider.ts, packages/rest/src/providers/log-error.provider.ts, packages/rest/src/providers/parse-params.provider.ts, packages/rest/src/providers/reject.provider.ts, packages/rest/src/providers/send.provider.ts, packages/rest/src/rest.application.ts
=> feat(rest): use singleton binding scope to cache REST middleware

docs/site/Order-filter.md, docs/site/Querying-data.md, docs/site/Where-filter.md
=> docs: fix broken links in filters

docs/site/Inside-Loopback-Application.md
Update auth links to point to latest examples
=> docs: update auth links

package.json
In this PR the properties of the package.json have been ordered for a better reading and put the important things first and the description has been added
=> Sort keys + add description in package

docs/site/Booting-an-Application.md, docs/site/Interceptor.md
=> docs: improve docs for interceptors

docs/site/Booting-an-Application.md
=> docs: fix note.html

docs/site/Memory-connector.md
=> feat(docs): update memory connector docs for lb4

docs/site/Accepting-MessagePack-over-HTTP.md
I've verified it by running the preview on loopback-next.
cc @raymondfeng 
=> fix(docs): fix file link

bodyparsers/rest-msgpack/LICENSE, bodyparsers/rest-msgpack/src/__tests__/acceptance/bodyparser.acceptance.ts, bodyparsers/rest-msgpack/src/__tests__/acceptance/component.acceptance.ts, bodyparsers/rest-msgpack/src/__tests__/unit/bodyparser.unit.ts, bodyparsers/rest-msgpack/src/bodyparser.ts, bodyparsers/rest-msgpack/src/component.ts, bodyparsers/rest-msgpack/src/index.ts, bodyparsers/rest-msgpack/src/keys.ts
=> chore(rest-msgpack): update copyright header node module

docs/site/Application.md
=> chore(docs): fix broken context apidocs links

docs/ROADMAP.md
=> feat(docs): add Q4 roadmap

docs/site/sidebars/lb4_sidebar.yml, docs/site/tutorials/core/1-introduction.md, docs/site/tutorials/core/10-advanced-recipes.md, docs/site/tutorials/core/11-summary.md, docs/site/tutorials/core/3-context-in-action.md, docs/site/tutorials/core/9-boot-by-convention.md
This PR is to fix an assortment of minor issues throughout the docs.
=> chore(docs): fix assortment of issues

docs/site/Using-openapi-to-graphql.md, docs/site/sidebars/lb4_sidebar.yml, extensions/graphql/README.md
=> chore: add graphql module differentiator note

docs/site/Authorization-overview.md
=> fix: authorization links

extensions/authentication-jwt/README.md
=> chore(authentication-jwt): add action-based sequence-only note

.github/workflows/codeql-analysis.yml
See https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/enabling-code-scanning-for-a-repository
=> chore: enable github code scanning

docs/site/decorators/Decorators_authorize.md, docs/site/sidebars/lb4_sidebar.yml
connect to https://github.com/strongloop/loopback-next/issues/5142
=> docs: add authorize decorator

packages/cli/generators/app/templates/README.md.ejs, packages/cli/snapshots/integration/generators/app.integration.snapshots.js
Improve the README.md for generated applications using CLI
Signed-off-by: Kerollos Magdy <kerolloz@yahoo.com>
=> fix(cli): add missing language to code blocks

docs/site/DEVELOPING.md
Signed-off-by: Kerollos Magdy <kerolloz@yahoo.com>
=> docs: fix minor grammar mistakes

docs/site/reference/reserved-binding-keys.md
=> fix(docs): fix Dependency-injection link

docs/site/guides/data-access/transactions.md
Signed-off-by: Pradeep Kumar Tippa <pktippa@gmail.com>
=> docs: fixed transactions doc

docs/site/Middleware.md
Hi, I was using the new Middleware feature on a loopback project by following the documentation and I was confused when I implemented my middleware function and all my endpoints returned an empty 204 response.
Am I correct that the Middleware example should be corrected in this way? If not, we should find a better way to document the Middleware example.
=> feat(docs): update middleware example

extensions/graphql/package-lock.json, extensions/graphql/package.json
=> chore(graphql): remove unused @types/graphql stub dependency

docs/site/Community-examples.md, docs/site/Examples.md, docs/site/sidebars/lb4_sidebar.yml
Add a community example page. Also move the examples sidebar item to be more visible. 
Here is the preview:
cc @raymondfeng 
=> feat(docs): add community example page

packages/context/src/__tests__/acceptance/class-level-bindings.acceptance.ts
=> test(context): add a test case to verify inject.getters for circular dependencies

docs/site/Authorization-component-authorizer.md
connect to https://github.com/strongloop/loopback-next/issues/6580
=> docs: update authorizer

docs/site/Controller.md, docs/site/Extending-Model-API-builder.md, docs/site/Extending-OpenAPI-specification.md, examples/passport-login/src/authentication-strategies/twitter.ts, examples/passport-login/src/authentication-strategy-providers/twitter.express-mw.ts, examples/passport-login/src/authentication-strategy-providers/twitter.ts, packages/express/src/__tests__/acceptance/middleware-registeration.acceptance.ts
=> fix: use @injectable over @bind

packages/openapi-v3/src/decorators/index.ts, packages/openapi-v3/src/decorators/response.decorator.ts, packages/openapi-v3/src/decorators/tags.decorator.ts
connect to https://github.com/strongloop/loopback-next/issues/5170
Add apidocs for `oas.response()` and `oas.tags()`
=> fix(openapi-v3): add apidocs for oas.response and oas.tags

docs/site/Community-examples.md
Fixes https://github.com/strongloop/loopback-next/issues/5595
=> https://github.com/strongloop/loopback-next/issues/5595

examples/webpack/README.md, examples/webpack/package-lock.json, examples/webpack/package.json, examples/webpack/webpack.config.js
Reduce webpack tests from `17s` to `12s`.
=> feat(example-webpack): speed up webpack by using js only

docs/site/tutorials/todo/todo-tutorial-putting-it-together.md, examples/todo/LICENSE, examples/todo/src/__tests__/acceptance/home-page.acceptance.ts, examples/todo/src/__tests__/acceptance/test-helper.ts, examples/todo/src/__tests__/unit/controllers/todo.controller.unit.ts, examples/todo/src/application.ts, examples/todo/src/controllers/todo.controller.ts, examples/todo/src/datasources/db.datasource.ts, examples/todo/src/datasources/geocoder.datasource.ts, examples/todo/src/index.ts, examples/todo/src/repositories/todo.repository.ts
=> update artifacts of the todo example to the latest style generated by the LoopBack CLI

docs/site/tutorials/authentication/Authentication-Tutorial.md, examples/todo-jwt/src/application.ts, examples/todo-jwt/src/controllers/todo.controller.ts, examples/todo-jwt/src/datasources/db.datasource.ts, examples/todo-jwt/src/index.ts, examples/todo-jwt/src/models/todo.model.ts, examples/todo-jwt/src/repositories/todo.repository.ts
Update the artifacts of this example
to the latest style generated by the
LoopBack CLI.
=> update artifacts of the todo-jwt example to the latest style generated by the LoopBack CLI

README.md
=> chore: sync LoopBack 4 EOL with Node.js 14 EOL

CODEOWNERS, MAINTAINERS.md, README.md
Welcome @nflaig to the maintainer team! 🎉 
@nflaig, I've also proposed some areas for you to be CODEOWNERS based on your previous PRs. Please review. Thanks.
=> chore: add nflaig to maintainer

extensions/socketio/package.json, extensions/socketio/src/socketio-controller-factory.ts
Signed-off-by: mayank <mayank.nauriyal@sourcefuse.com>
Update the import for @loopback/context in @loopback/socketio
Fixes #6756 
=> fix(socketio): remove related path for socketio

docs/site/Life-cycle.md, packages/core/src/__tests__/unit/application-lifecycle.unit.ts, packages/core/src/__tests__/unit/lifecycle-registry.unit.ts, packages/core/src/lifecycle-registry.ts, packages/core/src/lifecycle.ts
Improved version for #6700 
CC @mdbetancourt
=> feat(core): allow parameter injection for lifecycle methods

packages/context/src/index.ts, packages/core/src/application.ts
=> fix: re-export generateUniqueId in index.ts

docs/site/Express-middleware.md, packages/express/src/__tests__/fixtures/spy.middleware.ts, packages/express/src/express.server.ts, packages/express/src/middleware.ts, packages/express/src/types.ts, packages/rest/src/http-handler.ts
=> feat(express): set up MIDDLEWARE_CONTEXT for request object in constructor of `MiddlewareContext`

docs/site/submitting_a_pr.md
=> docs: add note about unrelated commits

docs/site/tutorials/todo-list/todo-list-tutorial-relations.md, examples/todo-list/data/db.json
Fix for #6733. In summary, model uses "color" but db.json used "dateModified".
=> Todolist example 6733

.github/codeql/codeql-config.yml, .github/workflows/codeql-analysis.yml
=> ci: ignore tests for codeql analysis

docs/site/index.md
Update the overview page to remove the LB4 monorepo box and the note about gaps between LB3 and LB4. 
- The monorepo description may not fit well in this overview page, as it might be more relevant to contributors
- We have a separate sidebar item about migration guide, so having a note to show the gap may not fit so well in the overview page as well.
With the change, the overview is much cleaner.
=> chore(docs): update overview page

packages/cli/generators/app/templates/README.md.ejs, packages/cli/generators/extension/templates/README.md.ejs, packages/cli/generators/project/templates/package.json.ejs, packages/cli/lib/project-generator.js, packages/cli/snapshots/integration/generators/app.integration.snapshots.js
=> Show README with yarn when selected and make it dynamic

docs/CONTRIBUTING.md
=> chore: update CLA link to DCO

docs/site/Binding.md
=> fix(docs): binding event listener sample code

README.md, SECURITY.md
=> chore: update LB3 LTS status to EOL

packages/repository/src/__tests__/unit/repositories/legacy-juggler-bridge.unit.ts, packages/repository/src/__tests__/unit/repositories/relations-helpers/find-by-foreign-keys.unit.ts, packages/repository/src/__tests__/unit/repositories/relations-helpers/include-related-models.unit.ts, packages/repository/src/relations/relation.helpers.ts
=> fix(repository): unwanted object param manipulation

.github/workflows/continous-integration.yaml, packages/cli/generators/copyright/git.js
- `continous-integration.yaml` is the main file.
- ~`test-workflow.yaml` is the default workflow by GitHub for sanity check as malformed YAML is silently disregarded. Will be removed before landing the PR.~
Related: https://github.com/strongloop/loopback-next/issues/1752
=> ci: switch to GitHub actions

docs/site/Include-filter.md
=> fix(docs): encoded inclusion filter code example

extensions/health/README.md, extensions/logging/README.md, extensions/metrics/README.md
=> chore: add note to configure before component registration

packages/cli/generators/copyright/git.js
=> fix(cli): copyright year git integration 

docs/site/migration/models/operation-hooks.md
=> feat(docs): add warning on LB3 hooks 'this' behaviour

extensions/socketio/src/booters/socketio.booter.ts, extensions/socketio/src/decorators/socketio.decorator.ts
=> docs: improve tsdoc

bodyparsers/rest-msgpack/README.md
=> chore: update docs for new msgpack parser library

.github/workflows/codeql-analysis.yml, .github/workflows/continous-integration.yaml
Did a casual regression test on the commit lint using a deliberately bad commit - Looks like it still works fine with the new code and is able to catch bad commit bodies. (see [reference run](https://github.com/strongloop/loopback-next/pull/6997/checks?check_run_id=1672437843)):
```
⧗   input: Merge b0e774226ad14a0183411d21f442d459797dbdce into f91a7eed1219650e1bedffe8b9445f3c943bfb6d
✔   found 0 problems, 0 warnings
⧗   input: This is a deliberately bad commit
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]
✖   found 2 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
⧗   input: ci: remove unecessary steps from ci
✔   found 0 problems, 0 warnings
⧗   input: ci: remove unecessary steps from …
```
=> Cleanup GitHub Actions workflows

packages/cli/generators/app/templates/src/controllers/ping.controller.ts.ejs, packages/cli/generators/controller/templates/src/controllers/controller-rest-template.ts.ejs, packages/cli/generators/repository/templates/src/repositories/repository-crud-default-template.ts.ejs, packages/cli/generators/repository/templates/src/repositories/repository-kv-template.ts.ejs, packages/cli/generators/service/templates/remote-service-proxy-template.ts.ejs, packages/cli/snapshots/integration/generators/app.integration.snapshots.js, packages/cli/snapshots/integration/generators/controller.integration.snapshots.js, packages/cli/snapshots/integration/generators/remote-service.integration.snapshots.js, packages/cli/test/integration/generators/controller.integration.js
=> Use response decorator instead of operation decorator

docs/site/Creating-datasource-runtime.md
Fixed a broken link to DataSource documentation
fix #7021
Signed-off-by: Andrii_Myronenko <andrewms2013@icloud.com>
=> docs: fixed a broken link

docs/site/Setting-debug-strings.md, packages/repository/src/__tests__/unit/repositories/has-many-through-repository-factory.unit.ts, packages/repository/src/relations/belongs-to/belongs-to.accessor.ts, packages/repository/src/relations/belongs-to/belongs-to.decorator.ts, packages/repository/src/relations/belongs-to/belongs-to.helpers.ts, packages/repository/src/relations/belongs-to/belongs-to.inclusion-resolver.ts, packages/repository/src/relations/belongs-to/belongs-to.repository.ts, packages/repository/src/relations/belongs-to/index.ts, packages/repository/src/relations/has-many/has-many-through.helpers.ts, packages/repository/src/relations/has-many/has-many-through.inclusion-resolver.ts, packages/repository/src/relations/has-many/has-many-through.repository-factory.ts, packages/repository/src/relations/has-many/has-many.helpers.ts, packages/repository/src/relations/has-many/has-many.inclusion-resolver.ts, packages/repository/src/relations/has-many/has-many.repository-factory.ts, packages/repository/src/relations/has-many/has-many.repository.ts, packages/repository/src/relations/has-many/index.ts, packages/repository/src/relations/has-one/has-one.helpers.ts, packages/repository/src/relations/has-one/has-one.inclusion-resolver.ts, packages/repository/src/relations/has-one/has-one.repository-factory.ts, packages/repository/src/relations/has-one/index.ts
=> Normalize debug scopes in relations

docs/site/migration/auth/overview.md
Signed-off-by: Pradeep Kumar Tippa <pktippa@gmail.com>
resolves #7023
=> fix(docs): migration doc built in auth broken link

examples/log-extension/README.md
*Suggestion*
**Rationale**: the document is more about building an **extension** (with Component, Decorator and Mixen) than using *the CLI*
Signed-off-by: ddsultan <2477698+ddsultan@users.noreply.github.com>
=> docs(examples): re-phrase overview introduction in 'log-extension' README

docs/site/migration/models/mixins.md
Signed-off-by: Pradeep Kumar Tippa <pktippa@gmail.com>
Fixes #3581 
=> fix(docs): documentation code snippet missing imports

packages/repository-tests/src/crud/relations/acceptance/has-many-through-inclusion-resolver.acceptance.ts, packages/repository-tests/src/crud/relations/fixtures/models/cart-item.model.ts, packages/repository-tests/src/crud/relations/fixtures/repositories/cart-item.repository.ts, packages/repository-tests/src/crud/relations/helpers.ts
Simply add an inclusion test for hasManyThrough
=> test(repository-tests): add a nested inclusion test for hasManyThrough

packages/cli/generators/copyright/license.js, packages/cli/package-lock.json, packages/cli/package.json, packages/cli/test/integration/generators/copyright.integration.js
Reverts strongloop/loopback-next#7099
@frbuceta, sorry that when I merged the PR #7099, I thought it's only the changes from the bot, but didn't see there're changes around the license text as well.
=> Revert "chore: update dependency spdx-license-list to ^6.4.0"

.github/workflows/continous-integration.yaml, .github/workflows/continuous-integration.yaml
They see that the tests are failing (#7096, also #7082), I have thought about adding a weekly test.
I have also fixed a typo.
=> Cron schedule for CI action

docs/site/Community-extensions.md
Signed-off-by: Samarpan Bhattacharya <this.is.samy@gmail.com>
Added new community extensions 
See also #6528 
=> fix(docs): add new extensions to community extensions page

.github/ISSUE_TEMPLATE/Bug_report.md, .github/ISSUE_TEMPLATE/config.yml, SECURITY.md
- update bug report template title for consistency 
- add more details to SECURITY.md 
- remove custom issue template for sec vulns 
=> Improve issue templates & SECURITY.md

docs/site/tutorials/todo-list/todo-list-tutorial-has-one-relation.md
Signed-off-by: Javier Zapata <javierzapata82@gmail.com>
=> fix(docs): fix typo in todo list tutorial

.github/renovate.json5
=> chore: do not update engines (renovate)

fixtures/tsdocs-monorepo/package.json, package.json
Reverts strongloop/loopback-next#7315
We have to disable the engine update in renovate
=> Revert "chore: update npm to >=7.7.5"

.github/renovate.json5
Fixes https://github.com/strongloop/loopback-next/pull/7229#issuecomment-808839069
=> chore: use npm v7 (renovate)

.github/renovate.json5
=> chore: force to use npm v7 (renovate)

package.json
Install husky in postinstall npm hook
=> chore: fix husky

CODEOWNERS, MAINTAINERS.md, README.md
With a bit of sadness I'd like to share with you my personal news. Today is my last day at IBM and that's also the end of my journey with LoopBack. 😢
It was great to build the framework from the initial 1.0 version back in 2013 to the new TypeScript-based version 4.0, I learned a lot along the way. It was even better to build the community surrounding this project, you are awesome! 🤗 
All good things have to come to an end, and so the time came for me to close this chapter of my life. I'll miss you all. ❤️ 
On the bright side, I hope you - the members of the LoopBack community - will use this change as an opportunity to grow your involvement with the project, bring fresh ideas and new perspectives unencumbered by the limitations of the past, and make the project fly even higher! 🚀
=> Farewell 👋

docs/site/index.md
=> Updated link to Diátaxis documentation authoring framework

package-lock.json, package.json
=> Remove husky remnants v4

.github/renovate.json5
=> chore: add socket.io group (renovate)

examples/graphql/src/__tests__/acceptance/graphql-middleware-options.acceptance.ts, extensions/graphql/src/graphql.server.ts, extensions/graphql/src/types.ts
fixes https://github.com/strongloop/loopback-next/issues/7412
=> feat: add ability to configure graphql path

extensions/logging/README.md
=> chore: update README to use `WinstonLogger`

packages/cli/test/acceptance/app-run.acceptance.js
@datpp has observed that the pretests are not running in the acceptance tests for NPM and I propose this temporary solution to the problem
=> `pretest` script is not executed in the NPM acceptance tests in v7

packages/cli/generators/app/index.js, packages/cli/generators/project/templates/package.json.ejs, packages/cli/generators/project/templates/package.plain.json.ejs, packages/cli/test/integration/generators/app.integration.js
Signed-off-by: Pradeep Kumar Tippa <pktippa@gmail.com>
Fixes #7080
Original PR was #7083
=> fix(cli): do not create migration script if repositories not selected

docs/site/Community-extensions.md
add new extension to community extensions page
Signed-off-by: Alex Pereira <alex.3.dj@gmail.com>
=> docs: update doc extensions

packages/tsdocs/src/__tests__/acceptance/tsdocs.acceptance.ts
A test case in `tsdocs` failed which is caused by the repo move:
```
1) tsdocs
updates apidocs for site:
AssertionError: expected '---\nlang: en\ntitle: \'API docs: pkg1.pet._constructor_\'\nkeywords: LoopBack 4.0, LoopBack 4, Node.js, TypeScript, OpenAPI\nsidebar: lb4_sidebar\nediturl: https://github.com/loopbackio/loopback-next/tree/master/packages/pkg1\npermalink: /doc/en/lb4/apidocs.pkg1.pet._constructor_.html\n---\n\n\r\n\r\n[Home](./index.md) &gt; [pkg1](./pkg1.md) &gt; [Pet](./pkg1.pet.md) &gt; [(constructor)](./pkg1.pet._constructor_.md)\r\n\r\n## Pet.(constructor)\r\n\r\nCreate a pet\r\n\r\n<b>Signature:</b>\r\n\r\n```typescript\r\nconstructor(name: string, kind: string);\r\n```\r\n\r\n## Parameters\r\n\r\n|  Parameter | Type | …
```
=> fix(tsdocs): fix tests after repo move

.github/renovate.json5
=> Increase prConcurrentLimit (renovate)

docs/site/Examples.md, packages/cli/generators/example/index.js
=> feat(cli): add socketio example

docs/site/LoopBack-types.md
=> fix(docs): fix example for array of number

examples/socketio/package-lock.json, examples/socketio/package.json
=> chore: remove unused socket.io direct deps

.github/workflows/codeql-analysis.yml, .github/workflows/continuous-integration.yml
see: https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/
see: https://github.com/github/codeql-action/blob/008b2cc71c4cf3401f45919d8eede44a65b4a322/README.md#usage
see: https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token
=> ci: add explicit GITHUB_TOKEN permissions

appveyor.yml
Synchronise AppVeyor config with the other CI workflows:
- Update `max-old-space-size` Node.js option
- Only build on `master` branch
=> ci: sync appveyor config

packages/tsdocs/package-lock.json, packages/tsdocs/package.json
@lerna/project is required when the package is installed from npm.
=> fix: add missing dependency for tsdocs

appveyor.yml
see: https://github.com/loopbackio/cicd/issues/4
Continuation of: https://github.com/loopbackio/loopback-next/pull/8088
=> ci: enable Windows testing on Node.js v16

packages/repository/src/__tests__/unit/repositories/relations-helpers/find-by-foreign-keys.unit.ts, packages/repository/src/relations/relation.helpers.ts
fixes: https://github.com/loopbackio/loopback-next/issues/8074
=> fix: relation query count regression

.github/renovate.json5, .github/workflows/codeql-analysis.yml, .github/workflows/continuous-integration.yml, .github/workflows/renovate-config-validator.yml, .lintstagedrc, package-lock.json, package.json
=> chore: update renovate config

.github/workflows/continuous-integration.yml, .github/workflows/renovate-config-validator.yml
=> chore: remove duplicate job

packages/cli/test/integration/generators/copyright.integration.js
=> fix tests for MIT license

extensions/logging/src/fluent.ts, package.json, packages/boot/src/booters/application-metadata.booter.ts, packages/core/src/lifecycle-registry.ts, packages/express/src/__tests__/fixtures/spy.middleware.ts, packages/rest-crud/src/crud-rest.controller.ts, packages/rest/src/__tests__/fixtures/middleware/spy.middleware.ts, packages/testlab/src/client.ts
=> Correct import syntax

packages/boot/src/__tests__/unit/booters/base-artifact.booter.unit.ts, packages/boot/src/booters/base-artifact.booter.ts
fixes https://github.com/loopbackio/loopback-next/issues/8201
=> fix: invalid glob for nested dirs

README.md
=> fix appveyor badge in README

packages/core/src/__tests__/acceptance/service.acceptance.ts, packages/core/src/service.ts
Fixes https://github.com/loopbackio/loopback-next/issues/8357
=> fix: honor service injection options

packages/eslint-config/eslintrc.js
see: https://github.com/loopbackio/loopback-next/issues/8383#issuecomment-1066777759
see: https://github.com/loopbackio/loopback-next/commit/f282dcab18addf63a2fad45fb7b1f0da97c27390#commitcomment-68685619
=> fix: ignore HTTP code-like object members

docs/site/migration/overview.md
Signed-off-by: ddsultan <2477698+ddsultan@users.noreply.github.com>
=> docs(migration-overview): fix link to 'Migrating datasources'

docs/CODE_OF_CONDUCT.md, package.json
=> chore: fix lint

README.md, SECURITY.md
Related to https://github.com/loopbackio/loopback-governance/issues/16
=> docs: update security reporting

packages/openapi-v3/src/controller-spec.ts
Signed-off-by: Rohit Vishwakarma <rohit.vishwakarma@sourcefuse.com>
Fixes #8353 
=> fix: controller spec response building from metadata

.github/workflows/renovate-config-validator.yml
=> ci: configuration file has been moved [skip ci]

package.json
Revert this commit when fixed.
=> test(example-soap-calculator): disable tests temporarily

packages/cli/generators/datasource/index.js, packages/cli/generators/model/index.js, packages/cli/generators/openapi/index.js, packages/cli/generators/repository/index.js, packages/cli/lib/project-generator.js, packages/cli/package-lock.json, packages/cli/package.json, packages/cli/snapshots/integration/generators/datasource.integration.snapshots.js, packages/cli/snapshots/integration/generators/interceptor.integration.snapshots.js, packages/cli/test/fixtures/interceptor/index.js, packages/cli/test/integration/generators/interceptor.integration.js, packages/cli/test/integration/generators/model.integration.js, packages/cli/test/integration/generators/openapi-client.integration.js, packages/cli/test/integration/generators/repository.integration.js, packages/cli/test/integration/generators/rest-crud.integration.js, packages/cli/test/test-utils.js
=> chore: update dependency yeoman-test to v4

docs/site/Interceptor-generator.md
Documentation update for non-global Interceptor
=> fix(docs): documentation update for non-global interceptor

docs/site/Context.md
Context documentation update to fix text
=> fix(docs): documentation update for context

docs/site/REST-middleware-sequence.md
middleware sequence document update for typo from middlware to middleware
=> fix(docs): middleware sequence document update

docs/site/Model.md
fix in docs for models for typo from "specifcation" to "specification"
=> fix(docs): model documentation fix for typo

docs/site/Repository.md
fix in repository docs for datasource typo
=> fix(docs): documentation fix in repository

docs/site/Model-generator.md
model generator documentation fix from additonal to additional
=> fix(docs): model generator documentation typo fix

docs/site/BelongsTo-relation.md
fix in documentation of belongsTo relation
=> fix(docs): fix in documentation of belongs to relation

packages/cli/generators/extension/templates/src/providers/README.md
documentation update  from seuqence to sequence
=> fix(docs): documentation update from seuqence to sequence

examples/log-extension/README.md
documentation update from dependecy to dependency
=> fix(docs): documentation update from dependecy to dependency

packages/cli/generators/extension/templates/src/providers/README.md
documentation update from availble to available
=> fix(docs): documentation update for typo availble

docs/site/tutorials/soap-calculator/soap-calculator-tutorial-scaffolding.md, packages/cli/lib/utils.js
documentation updates for datasoure to datasource
=> fix(docs): documentation updates for datasoure to datasource

examples/todo-jwt/README.md
documentation update from screeshot to screenshot
=> fix(docs): todo jwt documentation update for fix

examples/lb3-application/README.md
documentation update from neccessary to necessary
=> fix(docs): documentation update for typo

packages/core/src/__tests__/acceptance/application.feature.md
documentation update from initalizing to initializing
=> fix(docs): documentation update from initalizing to initializing

examples/rest-crud/README.md
documentation update from folowing to following
=> fix(docs): documentation update for rest crud document

packages/build/README.md
documentation update from availalbe to available
=> fix(docs): documentation update from availalbe to available

docs/site/tutorials/soap-calculator/soap-calculator-tutorial-add-controller.md
fix typo in documentation from begining to beginning
=> fix(docs): fix typo in documentation from begining to beginning

examples/multi-tenancy/CHANGELOG.md, examples/multi-tenancy/public/index.html
documentation update from demostrate to demonstrate
=> fix(docs): documentation update from demostrate to demonstrate

docs/site/Model.md
=> fix(docs) : updated link for docs/site/Model.md

packages/cli/generators/openapi/spec-loader.js
For the lb4 openapi command, the problem occurred when the ref URLs for openapi spec file contained links to secure routes. When the openapi loader tried to fetch those URLs, it returned 403 unauthorized errors, and because there was no exception handling it resulted in a crash. 
The library used to load openapi spec provides an option to skip resolving external refs. To resolve this issue, we modified the code to first try fetching URL with refs, if it returns 403 error then load it again without resolving refs. This way we can ensure that for accessible APIs we can always fetch refs and for authorized APIs, we can just ignore them.
=> fix(openapi-spec-builder): fix resolution of openapi urls returning http unauthorized error

.github/workflows/codeql-analysis.yml, .github/workflows/continuous-integration.yml, .github/workflows/renovate-config-validator.yml
see: https://github.com/loopbackio/security/issues/27
=> ci: pin GitHub Actions to Git hash

packages/repository/src/repositories/legacy-juggler-bridge.ts
fix #9071
Signed-off-by: Samarpan Bhattacharya <this.is.samy@gmail.com>
=> fix(repository): remove async from entityToData method in legacy-juggler-bridge

README.md
Welcome @samarpanB joining the LoopBack maintainer team! 🎉 
Signed-off-by: dhmlau <dhmlau@ca.ibm.com>
=> docs: add samarpanb to maintainer list

packages/cli/generators/datasource/index.js, packages/cli/generators/discover/index.js, packages/cli/lib/base-generator.js
This PR fixes the issues lb4 discover & lb4 datasource ran with the --config option.
"fix #8963", "fix #8966".
=> fix(cli): fix lb4 discover --config missing provided options

docs/site/express-with-lb4-rest-tutorial.md
In https://loopback.io/doc/en/lb4/express-with-lb4-rest-tutorial.html
Signed-off-by: Shubham Prajapat <shubham.prajapat@sourcefuse.com>
Fixes [#1242](https://github.com/loopbackio/loopback.io/issues/1242)
=> fix(docs): replace pEvent with once

packages/repository/src/repositories/legacy-juggler-bridge.ts
Signed-off-by: Samarpan Bhattacharya <this.is.samy@gmail.com>
Update DefaultCrudRepository to use new createAll method of juggler
Implements #3357
=> feat(repository): add capability for insert multiple rows in single query

packages/cli/generators/repository/index.js
Signed-off-by: Deepak Singh Solanki <deepaksinghsolanki1989@gmail.com>
#8637
=> fix(cli): fixed cli not detecting custom base repositories

docs/package-lock.json, docs/package.json
When trying to publish, I got the following error: 
```
> node ./bin/copy-readmes.js && node ./bin/copy-changelogs.js && cd .. && npm run tsdocs
node:internal/modules/cjs/loader:1050
throw err;
^
Error: Cannot find module '@lerna/project'
Require stack:
- /Users/dianalau/code/loopback/loopback-next/docs/bin/copy-readmes.js
at Module._resolveFilename (node:internal/modules/cjs/loader:1047:15)
at Module._load (node:internal/modules/cjs/loader:893:27)
at Module.require (node:internal/modules/cjs/loader:1113:19)
at require (node:internal/modules/cjs/helpers:103:18)
at Object.<anonymous> (/Users/dianalau/code/loopback/loopback-next/docs/bin/copy-readmes.js:15:23)
at Module._compile (node:internal/modules/cjs/loader:1226:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1280:10) …
```
=> fix: publish release issue in docs module 

docs/site/Application-generator.md
=> docs: switch --outDir of application generator have to be --outdir

packages/repository/src/relations/relation.helpers.ts
For huge data responses was able to see a lot of spikes in flame chart which pointed at clone deep fn in repository package, after further inspection was able to handle it through an if check 
=> perf(repository): handle cloneDeep while manipulating data 

docs/site/Calling-rest-apis.md
Adding post endpoint to calling-rest-api documentation
Issue : https://github.com/loopbackio/loopback-next/issues/7947
=> docs: adding post endpoint

README.md
Welcome @aaqilniz to the maintainers' team! 🎉 👏 
We really appreciate his contributions to LoopBack 4 especially CLI!   👏
Updated section looks like below in the preview:
=> chore: add @aaqilniz as maintainer 🎉 

packages/repository/src/repositories/legacy-juggler-bridge.ts
Restore async behaviour for entityToData method as it caused a regression
Fixes #9374
See also #9071 
=> fix(repository): restore async for entityToData method in legacy-juggler-bridge

extensions/sequelize/src/__tests__/fixtures/controllers/todo-list.controller.ts, extensions/sequelize/src/__tests__/integration/repository.integration.ts, extensions/sequelize/src/sequelize/sequelize.datasource.base.ts, extensions/sequelize/src/sequelize/sequelize.repository.base.ts
Implemented execute method on repository with similar interface as juggler, supports named and positional parameters.
=> feat(sequelize): custom query support

packages/repository-json-schema/src/__tests__/integration/build-schema.integration.ts, packages/repository-json-schema/src/build-schema.ts
This PR provides support for the `blob` type.
=> fix: support blob type

packages/cli/generators/datasource/index.js
=> fix: fix the usage of the option "connector"

package-lock.json, packages/tsdocs/package.json
This fixes up API docs generation for those running `npm run tsdocs` locally.
=> fix: apidocs generation

docs/site/migration/auth/passport.md
The anchor links appear to render lower cased
=> fix(docs): Fix migration/auth/passport section links

packages/cli/generators/discover/index.js
This makes it much easier to find a model in the list.
=> Display model choices alphabetically for "lb4 discover" CLI command

docs/site/Application-generator.md, examples/access-control-migration/Dockerfile, examples/multi-tenancy/Dockerfile, examples/references-many/Dockerfile, examples/rest-crud/Dockerfile, examples/socketio/Dockerfile, examples/todo-jwt/Dockerfile, examples/todo-list/Dockerfile, examples/todo/Dockerfile, packages/cli/generators/app/templates/Dockerfile
see: https://github.com/loopbackio/loopback-next/issues/9841
=> chore: use FQIN in Dockerfile

.gitignore, packages/cli/generators/project/templates/_.gitignore
see: https://www.gnu.org/software/emacs/manual/html_node/emacs/Auto-Save-Files.html
see: https://www.emacswiki.org/emacs/AutoSave
=> chore: `gitignore` emacs auto-save files

bin/build-docs-site.sh
=> fix: removing lerna bootstrap from bin/build-docs-site.sh

examples/todo/src/__tests__/helpers.ts
Updated the geopoint in the test case of `example/todo` application as per the census bureau update. Refer [this census bureau link](https://geocoding.geo.census.gov/geocoder/locations/onelineaddress?address=1%20New%20Orchard%20Road%2C%20Armonk%2C%2010504&benchmark=4) and [the impacted test case](https://github.com/loopbackio/loopback-next/blob/master/examples/todo/src/__tests__/acceptance/todo.acceptance.ts#L95) for more information.
=> fix: updating the geopoint as per census bureau update

packages/cli/lib/connectors.json
Update loopback-connector-mysql to latest version
=> fix: update loopback-connector-mysql to 7.0.5 (latest)

packages/cli/lib/connectors.json
Update connector versions to latest available.
=> fix: update connector versions to latest

extensions/sequelize/src/__tests__/integration/repository.integration.ts, extensions/sequelize/src/sequelize/sequelize.repository.base.ts
Support ordering by associations using this Sequelize API: https://sequelize.org/docs/v6/advanced-association-concepts/eager-loading
Fixes: #10374
Example:
```
{
include: [
{
"relation": user
}
],
order: "user email ASC"
}
```
<details><summary>SQL generated by the test cases</summary>
```sh
sequelize:sql:sqlite Executing (default): SELECT `TodoList`.`id`, `TodoList`.`title`, `TodoList`.`user`, `todos`.`id` AS `todos.id`, `todos`.`title` AS `todos.title`, `todos`.`is_complete` AS `todos.isComplete`, `todos`.`todo_list_id` AS `todos.todoListId` FROM `TodoList` AS `TodoList` LEFT OUTER JOIN `Todo` AS `todos` ON `TodoList`.`id` = `todos`.`todo_list_id` ORDER BY `TodoList`.`title` DESC;
sequelize:sql:sqlite Executed (default): SELECT `TodoList`.`id`, `TodoList`.`title`, `TodoList`.`user`, …
```
=> fix(sequelize): support ordering by associations

README.md
Welcome @samarpanB joining the Technical Steering Committee! 🎉 
Samarpan (@samarpanB) has been a LoopBack maintainer since Nov 2022. Since then, he continues to maintain and contribute to LoopBack. Some of his many contributions including upgrading MySQL connector to the latest MySQL version and adding relational query support in LoopBack 4.
=> Welcome Samarpan (@samarpanb) joins TSC

packages/core/src/__tests__/acceptance/application.acceptance.ts, packages/core/src/application.ts, packages/core/src/component.ts
In a large project, a component can have dependencies on other components. This feature makes it easier to mount required components to the application.
=> feat(core): allow a component to register nesting components

docs/site/migration/overview.md
Issue #6957 - add notice to migration page about LB3's EOL
found on https://loopback.io/doc/en/lb4/migration-overview.html
Signed-off-by: Susan Tan <suetan93@gmail.com>
=> docs: update migration overview page for LB3 EOL

packages/cli/generators/app/templates/src/index.ts.ejs
`process.env.HOST` may be `undefined` so we need to add a check on it !
=> add check on process.env.HOST in index.ts.ejs file

docs/site/Parsing-requests.md, docs/site/decorators/Decorators_openapi.md, docs/site/migration/auth/authentication.md
=> fix(docs): fix docs linting issue

docs/site/Community-extensions.md
updated extension page with the kafka client component which is built using KafkaJs.
=> docs(tsdocs): add extensions to community extensions list

packages/repository-json-schema/src/__tests__/unit/build-schema.unit.ts, packages/repository-json-schema/src/build-schema.ts
Reverts loopbackio/loopback-next#10635
=> Revert "fix: show readonly in openapi spec of model property if it is generated"

.github/workflows/continuous-integration.yml, .github/workflows/renovate-config-validator.yml
-  New tests added or existing tests modified to cover all changes
=> ci: update base Node.js version to v22

.github/workflows/continuous-integration.yml
=> chore: add Node.js 23 to CI

package-lock.json, packages/cli/package.json
=> fix: revert latest-version to use v5

examples/socketio/README.md, examples/webpack/README.md, extensions/cron/README.md, extensions/logging/README.md, packages/boot/README.md, packages/metadata/README.md, packages/rest/README.md
=> fix(docs): fix typos in documentation

README.md
=> docs: correct Node versions in README.md

extensions/sequelize/src/sequelize/connector-mapping.ts
Fix sequelize mssql support error
https://github.com/loopbackio/loopback-next/issues/11110
=> Fix sequelize mssql support error
