packages/loopback/index.ts, packages/loopback/lib/router/SwaggerRouter.ts, packages/loopback/lib/router/metadata.ts, packages/loopback/package.json, packages/loopback/test/integration/router/SwaggerRouter.integration.ts, packages/loopback/test/support/OpenApiSpecBuilder.ts, packages/openapi-spec/LICENSE, packages/openapi-spec/README.md, packages/openapi-spec/index.ts, packages/openapi-spec/package.json, packages/openapi-spec/src/OpenApiSpec-v2.ts
Connect to #135
Next steps (I'll create a follow-up issues): 
- add basic tests to verify that example Swagger documents can be compiled against this type definition
- support the upcoming 3.0 flavour of OpenAPI Spec
=> Move OpenApiSpec to a standalone npm package

packages/context/src/binding.ts
Alias "any" as "BoundValue" so that we can keep the tslint exception allowing "any" type in a single place.
This commit was extracted from #176 to get it landed sooner.
Connect to #142
=> Clean up types in binding.ts

packages/context/index.ts, packages/context/src/binding.ts, packages/context/src/context.ts, packages/context/src/inject.ts, packages/context/test/acceptance/class-level-bindings.feature.md, packages/context/test/acceptance/class-level-bindings.ts, packages/context/test/unit/binding.ts, packages/context/test/unit/inject.test.ts, packages/example-codehub/src/CodeHubApplication.ts, packages/loopback/index.ts, packages/loopback/lib/application.ts, packages/loopback/test/acceptance/routing/routing.acceptance.ts
- Add a new Binding method `toClass(ctor)` to define a value that should be resolved by calling the constructor with arguments resolved using `@inject` annotation
- Integrate this new API with Application and Controller concept
Connect to #142 
Requires #175 to be resolved first.
=> Inject constructor args

package.json, tsconfig.json
- modify engines field in the top-level package.json (we will have to edit engines in all sub-packages eventually too)
- change `tsc` transpilation target to `es6`
- (unrelated): upgrade `lib` from `es6` to `es2017`
My reasoning why it's ok to stop supporting Node.js 4: the release line is in maintenance mode and will go out of support in April 2018. Since LB.next will be used on new projects, I think it's reasonable to ask LB.next users to use a recent supported Node.js version for their new work.
=> Drop support for Node.js 4

package.json, packages/loopback/index.ts, packages/testlab/src/testlab.ts, tslint.json
- Upgrade tslint to ^5.1
- Enable `no-unnecessary-callback-wrapper`: reject `foo(x => fn(x))`, prefer `foo(fn)` instead.
- Disable `no-use-before-declare`, it was meant for `var` (which is not allowed by our config) and reports false positives in our code base (e.g. `UserController` is using `UserResponse` before it was declared).
=> Upgrade tslint to ^5.1 + enable no-unnecessary-callback-wrapper

packages/example-codehub/src/controllers/HealthController.ts, packages/loopback/lib/router/SwaggerRouter.ts, packages/openapi-spec/src/OpenApiSpec-v2.ts, packages/testlab/tsconfig.json, tsconfig.common.json, tsconfig.json
- Extract shared `tsc` settings to tsconfig.common.json
- Enable repository-wide export of declaration `.d.ts` files together with `.js` files created by `tsc` (compiler option `declaration: true`).
- Add missing exports to types/aliases that are transitively required to be public (this has been discovered by enabling `declaration: true`)
=> Extract shared settings to tsconfig.common.json

tslint.full.json
I enabled promise-function-async to catch the kind of errors
where a function returning a promise is not annotated with type
information and therefore the compiler cannot verify the correctness
of what the function is actually returning.
With noImplicitAny enabled, we have a better tool to detect such errors.
I also want to avoid the following downside of promise-function-async (see https://github.com/palantir/tslint/issues/2637):
it forces async functions even in places where an async function is
clearly a wrong thing to do, e.g.
```ts
const bar = () => Promise.resolve(1);
```
=> Remove promise-function-async

packages/authentication/test/acceptance/authentication/feature.md, packages/context/index.ts, packages/context/package.json, packages/context/src/binding.ts, packages/context/src/context.ts, packages/context/src/isPromise.ts, packages/context/src/resolver.ts, packages/context/test/acceptance/_feature.md, packages/context/test/acceptance/class-level-bindings.feature.md, packages/context/test/acceptance/class-level-bindings.ts, packages/context/test/acceptance/creating-and-resolving-bindings.feature.md, packages/context/test/acceptance/creating-and-resolving-bindings.ts, packages/context/test/acceptance/unlocking-bindings.feature.md, packages/context/test/acceptance/unlocking-bindings.ts, packages/context/test/unit/binding.ts, packages/context/test/unit/context.ts, packages/context/test/unit/isPromise.test.ts, packages/example-codehub/src/CodeHubApplication.ts, packages/example-codehub/test/support/util.ts, packages/loopback/lib/router/SwaggerRouter.ts, packages/loopback/lib/server.ts, packages/loopback/test/acceptance/routing/feature.md
This is required to allow injection of asynchronously-computed values into Controller constructors.
- Allow dynamic bindings to be created using an async function returning
a promise.
- Modify `ctx.get` to always return a promise, regardless of whether
the binding is sync or async.
- Modify dependency injection code to detect sync vs. async dependencies and optimise the code building the dependencies to prefer sync flow if allowed by dependencies.
- Add new API `ctx.getAsync` that returns the bound value synchronously and throws if the factory function was async.
- Add new API `ctx.getBinding` to look up the `Binding` object by a key
- Add new API `isPromise` that can be used by consumers of `ctx.getBinding().getValue()` to detect whether the value was resolved sync or async.
As we …
=> Add support for mixed sync/async bindings

packages/context/src/binding.ts, packages/context/src/context.ts, packages/context/src/resolver.ts, packages/context/test/acceptance/child-context.ts, packages/context/test/acceptance/class-level-bindings.ts, packages/context/test/unit/binding.ts, packages/loopback/index.ts, packages/loopback/lib/application.ts, packages/loopback/lib/server.ts, packages/loopback/test/acceptance/routing/routing.acceptance.ts, packages/loopback/test/support/client.ts
Create a new child context for each request handled by the app. Add the following two bindings to this new context:
- `http.request`
- `http.response`
This is a pre-requisite for #186 which I am implementing as part of the time allocated in https://github.com/strongloop-internal/scrum-asteroid/issues/117.
=> Add per-request child context

packages/core/src/Component.ts, packages/core/src/Sequence.ts, packages/core/src/application.ts, packages/core/src/index.ts, packages/core/test/acceptance/bootstrapping/application.acceptance.ts, packages/core/test/acceptance/bootstrapping/application.feature.md
* Application constructor allows injectable user-defined AppConfig
* AppConfig is used to automatically bind components and sequences into
the app context
* Added feature file and corresponding acceptance tests for Application
changes
=> Update Application to allow user-defined configs

package.json, packages/example-codehub/test/acceptance/health.test.ts, packages/example-codehub/test/acceptance/user.test.ts, packages/example-codehub/test/integration/smoke.ts, packages/example-codehub/test/support/util.ts, packages/example-codehub/test/unit/smoke.ts, test/mocha.opts, test/mocha.opts.root, tsconfig.json
Remove the following compiler options:
- baseUrl
- paths
In the past, these options allowed us to write `import from 'core'` instead of `import from '@loopback/core'`. The former works only inside our monorepo and breaks after we compile and publish our code to npmjs.org, therefore we shouldn't be using it anyways.
=> Remove unused tsconfig options

.gitignore, .vscode/settings.json, package.json
This is an attempt to try and get the ball rolling on - https://github.com/strongloop/loopback-next/issues/131 I have used nyc before in our repos, Its a good tool for getting coverage for typescript. It will also play well with coveralls from what I can see here https://github.com/nickmerwin/node-coveralls there is a section on nyc.
Here is a screenshot of the current test coverage. Am still not 100% sure how lerna works or am i grabbing the correct coverage metrics so please provide feedback
The command to use is 
```
npm run coverage
```
This will generate a folder called _test_results/coverage_ which I have ignored in the .gitignore file.
In our organization to ensure the code coverage does not go down we enforce a certain threshold which will …
=> Added nyc for test coverage

.travis.yml, package.json
- Modify `npm test` to run all tests with code coverage enabled via `nyc`
- Modify `npm run coverage` to report the coverage to coveralls.io
- Add a Travis hook `after_success` to run the npm script
reporting the coverage
Connect to #131
=> Report coverage data to coveralls.io

packages/core/package.json, packages/core/src/index.ts, packages/core/src/parser.ts, packages/core/src/promisify.ts, packages/core/src/router/SwaggerRouter.ts, packages/core/test/integration/router/SwaggerRouter.integration.ts, packages/core/test/unit/parser.test.ts
- New parser/unmarshaller function (yet to delete the same logic/functions from SwaggerRouter)
- This code assumes router is already created which has mounted controllers and created endpoints prior to calling parser() method. (We still need to create the router() function with just this logic.. In master branch code, everything is glued together in SwaggerRouter and Application.ts).
- See comments at the beginning of the method in the file.
- Parser method only unmarshalls the request and returns back the method arguments for the given endpoint.
@bajtos @raymondfeng  Feel free to provide initial feedback.
=> Implement parser/unmarshaller

packages/context/src/inject.ts, packages/context/src/resolver.ts, packages/context/test/acceptance/class-level-bindings.ts, packages/context/test/unit/inject.test.ts, packages/context/test/unit/resolver.test.ts
=> Add support for property dependency injection

.vscode/tasks.json, bin/compile-package.js, package.json, packages/authentication/package.json, packages/context/package.json, packages/core/package.json, packages/openapi-spec-builder/package.json, packages/openapi-spec/package.json, packages/testlab/package.json
Create "bin/compile-package" helper for running tsc compiler
from each package directory in a way that reports errors
with paths relative to loopback-next project root.
This makes it possible to feed compilation errors into VS Code
"Problems" window.
Rework all packages "build" scripts to use this new helper.
Add two new top-level npm scripts:
- npm run build
- npm run clean
Add two new VS Code tasks:
- "Compile TypeScript sources" with "isBuildCommand": true,
to integrate with the built-in "build" task (shift+command+b)
- "Clean all generated files" to remove generated files
=> Add build & clean tasks for VSCode

.vscode/settings.json
Hide the output of `tsc` from the file/project explorer in VS Code.
=> Ignore generated lib/lib6 in VS Code

packages/core/src/parser.ts, packages/core/src/router/SwaggerRouter.ts
Drop our custom implementation in favour of http-errors package.
=> Use HttpErrors in parser and SwaggerRouter

.vscode/tasks.json
Suppress lerna output which was duplicating compiler errors. The duplicates were prefixed with "lerna ERR! execute" prefix, which confused the built-in "$tsc" matcher and problems with non-existent paths were reported as a result.
This is a follow-up for #300.
=> Fix problem matching for the Build task

packages/core/src/index.ts, packages/core/src/invoke.ts, packages/core/src/writer.ts, packages/core/test/unit/writer.test.ts, packages/testlab/src/shot.ts
- This PR decomposes writer into it's own method. This method marshals/writes return result from operation invocation into HTTP response.
- invoker.ts calls writer(..) 
@bajtos @raymondfeng PTAL 
With this PR, we have fairly good decomposition of Swagger Router. We have now  Router(SwaggerRouter), Parser, invoke(invoker), writer separated out. However the current invocation path is still tightly coupled. HTTP Req -> http server --> Swagger Router --> Application.ts --> Swagger Router --> parser --> Swagger Router -> invoker --> End User Operation(MyController) --> writer --> send back HTTP response to HTTP server. As we can see in this case, the argument which are passed into parser, invoker, writer are still coupled with Router itself. For e.g parser() needs Endpoint to be passed in, …
=> Decompose writer

package.json, tsconfig.json
It is redundant to specify the included and excluded paths in the config
as well as on the commandline. Also trim glob patterns to remove
redundant trailing wildcards.
cc @bajtos @raymondfeng @ritch @superkhau @deepakrkris
=> lint: simplify tslint config and invocation

packages/core/src/application.ts, packages/core/src/http-handler.ts, packages/core/test/integration/http-handler.integration.ts, packages/core/test/unit/application/application.test.ts
Refactor the code and move logError implementation from a hard-coded HttpHandler method into a customizable Application-level method and binding.
Connect to #308
=> Move logError() to an app-level binding

.vscode/launch.json, tsconfig.common.json
- Enable source maps to allow debuggers to map transpiled .js files
back to original .ts files
- Disable timeout when running Mocha tests in the debugger. Otherwise
tests fail on timeout when the debugging session is longer than
the 2 seconds (which is almost always).
=> Improve debugging experience

package.json
When running on Node.js 8, most of the code in promisify is ignored because we use native `util.promisify`. Therefore I see little value in measuring code coverage of this source file and I am proposing to exclude it from code coverage.
=> Ignore coverage of platform-dependent promisify

package.json, packages/authentication/test/unit/authenticate.test.ts, packages/context/src/index.ts, packages/context/test/acceptance/child-context.ts, packages/context/test/acceptance/class-level-bindings.ts, packages/context/test/acceptance/creating-and-resolving-bindings.ts, packages/context/test/acceptance/finding-bindings.ts, packages/context/test/acceptance/locking-bindings.ts, packages/context/test/acceptance/tagged-bindings.ts, packages/context/test/acceptance/unlocking-bindings.ts, packages/context/test/unit/binding.ts, packages/context/test/unit/context.ts, packages/context/test/unit/inject.test.ts, packages/context/test/unit/isPromise.test.ts, packages/context/test/unit/resolver.test.ts, packages/core/test/acceptance/bootstrapping/application.acceptance.ts, packages/core/test/acceptance/bootstrapping/server.ts, packages/core/test/acceptance/routing/routing.acceptance.ts, packages/core/test/unit/application/application.controller.test.ts
~~Initially, I thought this may be the reason for wrong code coverage numbers we are observing. Unfortunately it was not, but I think it's still an change that should be made.~~
Fix tests imports to reference lib, not src. With that change in place, we can gather code-coverage data for transpiled .js files in lib/lib6 only. This fixes the problem where code coverage numbers were not including all passes.
Configure an exception for example-codehub which is not tranpiled nor published to npmjs.org.
=> Fix tests imports to reference lib, not src + fix code coverage

package.json
The new version 3.0.5 seems to contain a regression that causes
our builds to fail when running under `nyc`.
=> Fix ts-node version to 3.0.4

packages/core/src/index.ts, packages/core/test/acceptance/sequence/sequence.acceptance.ts
This is to help code coverage and also those types should be in index.ts as well since they are used in user defined sequence. @raymondfeng PTAL As talked before, I opened a new PR with same changes as previous PR https://github.com/strongloop/loopback-next/pull/347
=> Cleanup import in sequence.acceptance.ts

package.json
The version 3.0.6 has fixed the regression from 3.0.5, see https://github.com/TypeStrong/ts-node/issues/344
=> Track latest ts-node releases again

packages/context/package.json, packages/context/src/index.ts, packages/repository/src/legacy-juggler-bridge.ts
Use the version provided by `@loopback/context` in all places.
=> Unify isPromise implementation

packages/context/src/binding.ts, packages/context/src/index.ts, packages/context/src/resolver.ts, packages/context/test/unit/binding.ts, packages/context/test/unit/resolver.test.ts
A follow-up for #343:
Modify `getValue()` function to correctly support the case where both the provider instance and the provided value can be obtained synchronously.
Simplify related code by removing stuff no longer needed.
=> Support synchronous resolution of Provider binding

.vscode/tasks.json, package.json
Since "npm test" runs both TS Compiler and tslint now, the output can contain compilation and linting errors.
This commit is configuring problem matchers for the "run all tests" task to correctly pick up errors reported by tsc and tslint and list them in "problems" window.
Note: the tslint5 problem matcher is contributed by the VSCode extension vscode-tslint (maintained by Microsoft).
With this patch in place, we can use the single command "run tests" command (Cmd+Shift+T IIRC)  for a full build+test+lint run, with compiler/linter errors neatly listed in the Problems window.
=> Fix problem matchers for the test task in VS Code

package.json, packages/core/src/parser.ts
With `@types/node 7.0.31`, the header value is now string | string[]
@deepakrkris
=> Fix http header typing

packages/core/src/server.ts, packages/core/test/acceptance/routing/routing.acceptance.ts, packages/core/test/acceptance/sequence/sequence.acceptance.ts, packages/testlab/src/client.ts
As per the Node.js API docs (https://nodejs.org/api/http.html)
the `server.address` function should only be called *after*
the "listening" event is triggered.
=> server: call server.address after listening event

packages/context/src/binding.ts, packages/context/src/context.ts, packages/context/test/acceptance/locking-bindings.ts, packages/context/test/acceptance/tagged-bindings.feature.md, packages/context/test/acceptance/tagged-bindings.ts, packages/context/test/unit/binding.ts, packages/context/test/unit/context.ts
1. Allow separator for nested properties
2. Allow multiple tags for a binding
See https://github.com/strongloop/loopback-next/issues/258
With this change, we now support `ctx.get('x.y#a.b')` now.
=> Improve context bindings

packages/core/src/internal-types.ts, packages/core/src/parser.ts, packages/core/src/sequence.ts, packages/core/src/writer.ts
@raymondfeng @crandmck  @mpatsute  @ritch PTAL
Please review docs for below APIs. This PR covers APIs in issue #https://github.com/strongloop-internal/scrum-asteroid/issues/231 
APIs covered in this work item/PR
1. Sequence class
2. InvokeMethod in internal-types.ts 
3. parseOperationArgs () in parser.ts - Rest of the methods in this file are internal methods and hence doesn’t need API doc
4. writeResultToResponse() in writer.ts 
There are different work items opened for other APIs in loopback-next which are in different team-members board.
=> Add API doc for Sequence, writer, parser & InvokeMethod

.vscode/settings.json
Also remove tslint exception that's no longer needed.
=> Configure prettier in VSCode settings

packages/context/src/binding.ts, packages/context/src/index.ts, packages/context/test/unit/binding.ts, packages/context/test/unit/context.ts
The initial implementation only supports two scopes:
- BindingScope.TRANSIENT (default): Calculate the value each time
- BindingScope.SINGLETON: Calculate the value once globally and reuse it
- BindingScope.CONTEXT: Calculate the value once per context and reuse it
cc @bajtos @raymondfeng @ritch @superkhau 
See https://github.com/strongloop/loopback-next/issues/228
=> Add scope support for bindings

packages/core/src/application.ts, packages/core/src/component.ts, packages/core/test/acceptance/bootstrapping/application.acceptance.ts, packages/core/test/acceptance/bootstrapping/application.feature.md
A component can be registered with an application either at construction time via AppOptions, or by calling `app.component()` later.
This first version allows components to contribute controllers and arbitrary provider bindings.
=> Implement application components

.vscode/settings.json
Trailing-comma is already required by our tslint config, see https://github.com/strongloop/loopback-next/blob/4a90d66bc6ac08bb253e1b35eb809b42d0e3fe65/tslint.json#L37-L40
cc @bajtos @raymondfeng @ritch @superkhau @kjdelisle
=> Configure prettier to add trailing commas

packages/repository/examples/controllers/customer-controller-with-class-di.ts, packages/repository/examples/controllers/customer-controller-with-constructor-di.ts, packages/repository/examples/controllers/customer-controller-with-property-di.ts, packages/repository/src/decorators/repository.ts, packages/repository/test/unit/decorator/repository-with-value-provider.ts, packages/repository/test/unit/decorator/repository.ts
=> Implement @repository(model, dataSource) injection

packages/core/src/application.ts, packages/core/src/index.ts, packages/core/src/internal-types.ts, packages/core/src/router/reject.ts, packages/core/src/sequence.ts, packages/core/test/acceptance/sequence/sequence.acceptance.ts, packages/core/test/integration/http-handler.integration.ts, packages/core/test/unit/reject.test.ts, packages/core/test/unit/writer.test.ts, packages/testlab/package.json, packages/testlab/src/shot.ts, packages/testlab/src/testlab.ts
As I started working on `app.sequence((seq, res, res) => {...})`, I realised that we really need to refactor `sendResponse`/`sendError` into injectable `send`/`reject`.  That's what this pull request presents.
=> Make send/reject injectable

packages/authentication/test/acceptance/basic-auth.ts, packages/core/src/application.ts, packages/core/src/http-handler.ts, packages/core/src/index.ts, packages/core/src/sequence.ts, packages/core/test/acceptance/sequence/sequence.acceptance.ts
- Rename "run()" to "handle()"
- Introduce a new interface SequenceHandler describing the public
contract (API)
=> Clean up Sequence API

package.json
Disable the text summary of code coverage - it produces a long wall of text that hides the actual test results. Developers wishing to inspect code coverage can `open coverage/index.html` to find the numbers.
=> Remove text coverage summary from "npm test"

packages/authentication/test/acceptance/basic-auth.ts, packages/core/src/application.ts, packages/core/src/http-handler.ts, packages/core/src/index.ts, packages/core/src/internal-types.ts, packages/core/src/parser.ts, packages/core/src/router/routing-table.ts, packages/core/src/sequence.ts, packages/core/test/acceptance/routing/routing.acceptance.ts, packages/core/test/acceptance/sequence/sequence.acceptance.ts, packages/core/test/integration/http-handler.integration.ts, packages/core/test/unit/http-handler.ts, packages/core/test/unit/parser.test.ts, packages/core/test/unit/routing-table.test.ts, packages/openapi-spec-builder/src/openapi-spec-builder.ts, packages/openapi-spec/src/openapi-spec-v2.ts
Rework the internal implementation to support the new `app.route()` API as described in [wiki](https://github.com/strongloop/loopback-next/wiki/Routing#creating-routes)
```ts
// greet is a basic operation
function greet(name) {
return `hello ${name}`;
}
const spec = {
parameters: [{name: 'name', in: 'query', type: 'string'},
responses: {
'200': {
description: 'greeting text',
schema: {type: 'string'},
}
}
};
const route = new Route('get', '/', spec, greet);
app.route(route);
```
Notable changes:
- Renamed `RouteEntry` to `Route` and made it public
- Reworked `ResolvedRoute` to support both handler and controller+method
- Reworked `parseArgs` and `invoke` to accept a resolved route instead of controller+method
=> Refactor routing to support handlerFn-based routes

packages/authentication/test/acceptance/basic-auth.ts, packages/core/src/http-handler.ts, packages/core/src/index.ts, packages/core/src/internal-types.ts, packages/core/src/parser.ts, packages/core/src/router/routing-table.ts, packages/core/src/sequence.ts, packages/core/test/acceptance/sequence/sequence.acceptance.ts, packages/core/test/unit/http-handler.ts, packages/core/test/unit/parser.test.ts, packages/core/test/unit/routing-table.test.ts
Rework `findRoute` action to return an object containing two properties:
- the immutable `RouteEntry` registered at app start
- `pathParams` parsed from the request URL
Refactor `Route` class into three classes:
- Abstract `RouteEntry` providing the shared implementation
of route matching and defining the common API
- `Route` implementing invocation of handler-function-based routes
- `ControllerRoute` implementing invocation of controller-based routes
Closes #400
=> Refactor ResolvedRoute to {route, pathParams}

bin/compile-package.js, package.json, packages/authentication/package.json, packages/context/package.json, packages/core/package.json, packages/openapi-spec-builder/package.json, packages/openapi-spec/package.json, packages/repository/package.json, packages/testlab/package.json
Rework the build system to compile only for the current target (based on `node --version`) before running the tests.
This change speeds up `npm test` by 40% (approximately).
Before:
```
$ time npm test
[...]
real  0m29.338s
user  0m52.340s
sys  0m3.597s
```
After:
```
$ time npm test
[...]
real  0m17.657s
user  0m29.461s
sys  0m1.887s
```
=> Speed up "npm test" by compiling single target

packages/authentication/package.json, packages/context/package.json, packages/core/package.json, packages/openapi-spec-builder/package.json, packages/openapi-spec/package.json, packages/repository/package.json
cc @bajtos @raymondfeng @ritch @superkhau 
Bumped up versions, and published all packages. This is done for story connects to strongloop-internal/scrum-asteroid#233
```
@loopback/core@4.0.0-alpha.10
@loopback/context@4.0.0-alpha.10
@loopback/authentication@4.0.0-alpha.4
@loopback/openapi-spec@4.0.0-alpha.7
@loopback/openapi-spec-builder@4.0.0-alpha.5
@loopback/repository@4.0.0-alpha.4
```
The newly published versions now have the docs bundled inside them, which are viewable on `apidocs.strongloop.com`. This completes the whole cycle. To see the documentation from the published npm versions, follow these steps.
```
1. git clone https://github.com/strongloop-internal/apidocs.strongloop.com/
2. cd apidocs.strongloop.com
3. npm install
4. node app.js
5. Go to …
```
=> Bumped up versions, and published

packages/authentication/test/acceptance/basic-auth.ts, packages/core/src/http-handler.ts, packages/core/src/index.ts, packages/core/src/parser.ts, packages/core/src/router/routing-table.ts, packages/core/src/sequence.ts, packages/core/test/acceptance/sequence/sequence.acceptance.ts, packages/core/test/unit/parser.test.ts, packages/core/test/unit/routing-table.test.ts
Per our discussion in #417, simplify the usage of `findRoute` and related methods so that a single `route` entity can be passed around.
```ts
// inside Sequence.prototype.handle
const route = this.findRoute(req);
const args = await parseOperationArgs(req, route);
// etc.
```
Closes #426
cc @bajtos @raymondfeng @ritch @superkhau @kjdelisle
=> Rework ResolvedRoute to inherit from RouteEntry

packages/core/src/application.ts, packages/core/src/http-handler.ts, packages/core/src/index.ts, packages/core/src/router/routing-table.ts, packages/core/test/acceptance/routing/routing.acceptance.ts, packages/core/test/integration/http-handler.integration.ts, packages/core/test/unit/http-handler.ts, packages/openapi-spec-builder/src/openapi-spec-builder.ts
```ts
app.api({
baseURL: '/',
paths: {
'/greet': {
get: {
params: {name: 'string', source: 'query'}
'x-operation-name': 'greet',
'x-controller': 'MyController'
}
}
}
});
app.controller(MyController);
```
Refactor `registerRoute()` methods to accept arbitrary `RouteEntry` instance (a handler function or a controller method).
Closes #403
=> Allow controller API to be specified via app.api()

packages/core/src/application.ts, packages/core/src/http-handler.ts, packages/core/src/router/routing-table.ts, packages/core/test/acceptance/routing/routing.acceptance.ts, packages/core/test/acceptance/sequence/sequence.acceptance.ts, packages/core/test/integration/http-handler.integration.ts, packages/core/test/unit/http-handler.ts, packages/core/test/unit/router/controller-route.test.ts, packages/core/test/unit/router/reject.test.ts, packages/core/test/unit/router/routing-table.test.ts, packages/example-codehub/src/controllers/user-controller.api.ts
Example usage:
```ts
greet(name: string) {
return `hello ${name}`;
}
}
const spec = {parameters: {name: 'string', source: 'query'}};
app.route('get', '/greet', spec, MyController, 'greet');
```
I have also modified `app.route()` API to accept any instance implementing `RouteEntry` interface - a handler-function based `Route`, a `ControllerRoute`, but possibly also custom 3rd-party route type. The last line in the example above can be rewritten as follows:
```ts
app.route(new ControllerRoute('get', '/greet', spec, MyController, 'greet'));
```
In the second part of this patch, I simplified internal implementation by reworking `ControllerRoute` class to always expect a controller constructor, even for routes registered for controllers bound via `app.controller()` API. …
=> Add app.route() API for controller-based routes

bin/generate-apidocs.js
Fix the script running strong-docs to generate api-docs, so that it correctly forwards strong-doc's stdout and stderr.
cc @bajtos @raymondfeng @ritch @superkhau @mpatsute
=> apidocs: fix the script to forward stdout/stderr

packages/authentication/test/acceptance/basic-auth.ts, packages/core/src/application.ts, packages/core/src/http-handler.ts, packages/core/src/router/reject.ts, packages/core/src/sequence.ts, packages/core/test/acceptance/sequence/sequence.acceptance.ts, packages/core/test/integration/http-handler.integration.ts, packages/core/test/unit/application/application.test.ts, packages/core/test/unit/http-handler.ts
This fixes a left-over from an earlier work.
- `logError` -> `sequence.actions.logError`
- `findRoute` -> `sequence.actions.findRoute`
- `invokeMethod` -> `sequence.actions.invokeMethod`
The updated `DefaultSequence` constructor is nicely consistent now:
```ts
export class DefaultSequence implements SequenceHandler { 
constructor(
@inject('sequence.actions.findRoute') protected findRoute: FindRoute,
@inject('sequence.actions.invokeMethod') protected invoke: InvokeMethod,
@inject('sequence.actions.send') public send: Send,
@inject('sequence.actions.reject') public reject: Reject,
) {}
// ...
}
```
=> Rename sequence actions to start with "sequence.actions." prefix

.vscode/tasks.json
A follow-up for #360.
> @bajtos
> It makes me wonder, is anybody actually using these fine-grained tasks? Can we remove them? I personally always run the full compile+test+lint cycle.
> @superkhau 
> Me too, notice just running all them is easier (cmd+shift+t). I'm OK with removing the fine-grained ones to keep things simple/maintainable.
The following tasks are staying around:
=> vscode: remove unused tasks

packages/core/src/index.ts, packages/core/src/router/metadata.ts, packages/core/test/acceptance/routing/routing.acceptance.ts, packages/core/test/unit/router/metadata.test.ts
Allow Controller authors to describe REST API methods using per-method decorations via @get and @operation, as described on [wiki](https://github.com/strongloop/loopback-next/wiki/Controllers#routing-to-controllers).
```ts
@get('/greet', {parameters: {name: 'string', type: 'string', in: 'query'}})
greet(name) {
return `Hello ${name}.`;
}
}
```
I created this pull request as an outcome of my spike on #402, I am intentionally omitting `@post` etc. decorators - that will be part of the follow-up work (mostly in #404).
=> core: support @get and @operation decorators

packages/core/src/index.ts, packages/core/src/router/metadata.ts, packages/core/test/acceptance/routing/routing.acceptance.ts, packages/core/test/unit/router/metadata.test.ts, packages/core/test/unit/router/metadata/param.test.ts
- `@param(spec)`
- `@param.query.string(name)`
- `@param.query.number(name)`
- `@param.query.integer(name)`
- `@param.query.boolean(name)`
See [wiki](https://github.com/strongloop/loopback-next/wiki/Controllers#writing-controller-methods) for more details.
Connect to #404 
=> Add `@param` decorator + shortcuts

packages/core/src/router/metadata.ts, packages/core/test/unit/router/metadata.test.ts
- `@post()`
- `@put()`
- `@patch()`
- `@del()`
Note that `delete` is a reserved keyword that cannot be used
as a function name.
Connect to #404 
=> Add shortcut decorators for HTTP verbs

packages/core/src/router/metadata.ts, packages/core/test/integration/http-handler.integration.ts, packages/core/test/unit/parser.test.ts, packages/core/test/unit/router/metadata/param-body.test.ts, packages/core/test/unit/router/metadata/param-form-data.test.ts, packages/core/test/unit/router/metadata/param-header.test.ts, packages/core/test/unit/router/metadata/param-path.test.ts, packages/core/test/unit/router/metadata/param-query.test.ts, packages/core/test/unit/router/metadata/param.test.ts, packages/openapi-spec/src/openapi-spec-v2.ts
- `@param.header.string(name)`
- `@param.header.number(name)`
- `@param.header.integer(name)`
- `@param.header.boolean(name)`
- `@param.path.string(name)`
- `@param.path.number(name)`
- `@param.path.integer(name)`
- `@param.path.boolean(name)`
- `@param.formData.string(name)`
- `@param.formData.number(name)`
- `@param.formData.integer(name)`
- `@param.formData.boolean(name)`
- `@param.body(name, schema)`
Fix ParameterObject definition to restrict allowed `type` values and also to support `body` parameter definition with `schema` property. The change discovered invalid Swagger spec objects used in few tests, this commit fixes them along the way.
Connect to #404
We should probably wait until #459 is landed, so that tests using `body` and `formData` source can we reworked to use `POST` verb, …
=> Add more `@param.*` shortcuts

packages/core/src/router/metadata.ts, packages/core/test/unit/router/metadata/param.test.ts
Example usage:
```ts
@operation('get', '/', {responses})
@param(offsetSpec)
@param(pageSizeSpec)
list(offset?: number, pageSize?: number) {}
}
```
Connect to #404
=> Merge operation spec from @operation and @param

packages/core/package.json, packages/core/src/application.ts, packages/core/src/http-handler.ts, packages/core/src/router/metadata.ts, packages/core/src/router/routing-table.ts, packages/core/test/acceptance/routing/routing.acceptance.ts, packages/core/test/acceptance/sequence/sequence.acceptance.ts, packages/core/test/integration/application.integration.ts, packages/core/test/integration/http-handler.integration.ts, packages/core/test/unit/application/application.open-api-spec.test.ts, packages/core/test/unit/router/metadata.test.ts, packages/core/test/unit/router/metadata/param-body.test.ts, packages/core/test/unit/router/metadata/param-form-data.test.ts, packages/core/test/unit/router/metadata/param-header.test.ts, packages/core/test/unit/router/metadata/param-path.test.ts, packages/core/test/unit/router/metadata/param-query.test.ts, packages/core/test/unit/router/metadata/param.test.ts, packages/example-codehub/src/codehub-application.ts, packages/example-codehub/src/controllers/health-controller.api.ts, packages/example-codehub/src/controllers/user-controller.api.ts, packages/example-codehub/test/acceptance/smoke.test.ts, packages/openapi-spec-builder/src/openapi-spec-builder.ts, packages/openapi-spec/src/openapi-spec-v2.ts, packages/testlab/README.md, packages/testlab/package.json, packages/testlab/src/testlab.ts, packages/testlab/src/validate-api-spec.ts
The first commit implements a new method `app.getApiSpec()` for obtaining the OpenAPI spec containing paths (routes) contributed by all different means we support (`app.api()`, `app.route()`, `app.controller()`). It also exposes a new HTTP endpoint "GET /openapi.json" that returns this specification. This endpoint is excluded from the spec.
With this change in place, I tried what happens when I take OpenAPI spec from our CodeHub application and validate it in http://editor.swagger.io/. There was a bunch of validation errors reported, thus I decided to fix them.
I started with adding a new helper function `app.validateApiSpec()` that uses [swagger-parser](https://www.npmjs.com/package/swagger-parser) under the hood to validate the spec. In order to be able to do that, I had to beef up our …
=> Expose "GET /openapi.json", implement spec validation

packages/authentication/src/decorator.ts, packages/authentication/src/keys.ts, packages/context/src/binding.ts, packages/context/src/provider.ts
=> Add js docs for Authentication package

packages/authentication/README.md, packages/authentication/package.json, packages/authentication/src/auth-component.ts, packages/authentication/src/decorators/authenticate.ts, packages/authentication/src/index.ts, packages/authentication/src/keys.ts, packages/authentication/src/providers/auth-metadata.ts, packages/authentication/src/providers/authenticate.ts, packages/authentication/src/strategy-adapter.ts, packages/authentication/test/acceptance/basic-auth.ts, packages/authentication/test/unit/fixtures/mock-strategy.ts, packages/authentication/test/unit/provider.test.ts, packages/context/src/inject.ts, packages/context/test/acceptance/class-level-bindings.ts, packages/core/src/component.ts, packages/core/src/index.ts
As a preparatory work, implement a new `@inject.getter` decorator, which injects a getter function to obtain the bound value. This is useful when implementing Actions, where the action is instantiated for Sequence constructor, but some of action's dependencies become bound only after other actions have been executed by the sequence. (`autenticate` actions is a prime example.)
Next, make `@loopback/authentication` a proper component by adding exported `AuthenticationComponent` that registers providers for
`authenticate` action and current-route metadata.
Simplify usage of `authenticate` action by shifting the complexity
of deferring metadata resolution into the action itself (using the
new `@inject.getter` decorator), so that custom Sequence implementations
can inject this action the same …
=> authentication: make it a proper component + cleanup

packages/authentication/test/acceptance/basic-auth.ts, packages/core/src/application.ts, packages/core/src/index.ts, packages/core/src/internal-types.ts, packages/core/src/sequence.ts, packages/core/test/acceptance/sequence/sequence.acceptance.ts, packages/core/test/integration/http-handler.integration.ts
Rework DefaultSequence to allow injection of "parseParams" action.
While reviewing [Sequence wiki](https://github.com/strongloop/loopback-next/wiki/Sequence), I realised that `parseParams` was a hard-coded dependency that cannot be injected. This pull request fixes that problem :)
=> core: add binding "sequence.actions.parseParams"

.gitignore
Updating .gitignore to ignore api-docs created during bootstrap process
=> Add api-docs folder to .gitignore

packages/core/src/router/routing-table.ts, packages/core/test/unit/application/application.open-api-spec.test.ts, packages/core/test/unit/router/routing-table.test.ts
Set `x-controller-name` and `x-operation-name` for controller routes defined via `app.route()` and `app.controller()`. This way the OAI spec for controller-based routes always contains both extension fields, regardless of the way how the route was registered in the app.
Close #474
=> core: add controller/method metadata to OAI spec

packages/authentication/README.md
cc @bajtos @raymondfeng @ritch @superkhau 
This turned out to be a root cause of the bug in Hello-world client code because it copy&pasted the code piece from the README.
connect to https://github.com/strongloop/loopback-next/issues/490
=> Fix authentication key

packages/authentication/README.md, packages/authentication/src/auth-component.ts, packages/authentication/src/decorators/authenticate.ts, packages/authentication/src/keys.ts, packages/authentication/src/providers/auth-metadata.ts, packages/authentication/src/providers/authenticate.ts, packages/authentication/test/acceptance/basic-auth.ts, packages/authentication/test/unit/authenticate-action.test.ts, packages/authentication/test/unit/metadata-provider.test.ts, packages/core/src/application.ts, packages/core/src/http-handler.ts, packages/core/src/keys.ts, packages/core/src/router/providers/bind-element.ts, packages/core/src/router/providers/find-route.ts, packages/core/src/router/providers/get-from-context.ts, packages/core/src/router/providers/invoke-method.ts, packages/core/src/router/providers/reject.ts, packages/core/src/sequence.ts, packages/core/test/acceptance/bootstrapping/application.acceptance.ts, packages/core/test/acceptance/routing/routing.acceptance.ts, packages/core/test/acceptance/sequence/sequence.acceptance.ts, packages/core/test/integration/application.integration.ts, packages/core/test/integration/http-handler.integration.ts, packages/core/test/unit/application/application.test.ts, packages/example-codehub/src/codehub-application.ts, packages/example-codehub/test/support/util.ts
This pull request defines constants for all binding keys used in core. Because I found the old structure of BindingKeys constants sort of weird, so I took an attempt to clean it up a bit - both in `core` and `authentication`. I am looking for more suggestions on how to improve this!
Connect to #483
=> Define constants for all binding keys + cleanup

packages/authentication/README.md, packages/authentication/src/providers/authenticate.ts, packages/authentication/test/acceptance/basic-auth.ts, packages/authentication/test/unit/authenticate-action.test.ts
Improve authentication component to handle the use case where a controller method is not decorated with `@authenticate`, therefore allowing anonymous access.
The solution is not ideal, because when a method is not annotated with `@authenticate`, then we will never try to authenticate the current user, even if the request includes authorization header. I consider this patch as a stop gap needed to finish https://github.com/strongloop/loopback-next/wiki/Thinking-in-LoopBack. If you think we should find a better solution for longer term, then I'll open a GH issue - just let me know.
Connect to #393
=> authentication: support anonymous access

packages/core/src/router/routing-table.ts, packages/core/test/integration/http-handler.integration.ts
Throw an 404 error when an operation endpoint is mapped to a controller method that's not implemented by the controller class.
Before this change:
```
Unhandled error in GET /product/ink-pen:
500 TypeError: controller[this._methodName] is not a function
```
After this change:
```
Unhandled error in GET /product/ink-pen:
404 Error: Controller method not found: ProductController.getDetails
```
Connect to #393
=> core: handle invocation of an unknown method

package.json, packages/repository/examples/juggler-bridge/note-with-repo-class.ts, packages/repository/examples/juggler-bridge/note-with-repo-instance.ts, packages/repository/examples/models/order.ts, packages/repository/src/decorators/model.ts, packages/repository/src/decorators/repository.ts, packages/repository/src/index.ts, packages/repository/src/legacy-juggler-bridge.ts, packages/repository/src/loopback-datasource-juggler.ts, packages/repository/src/model.ts, packages/repository/test/acceptance/thinking-in-loopback/models/product.model.ts, packages/repository/test/acceptance/thinking-in-loopback/repositories/product.repository.ts, packages/repository/test/acceptance/thinking-in-loopback/thinking-in-loopback.acceptance.ts, packages/repository/test/unit/decorator/model-and-relation.ts, packages/repository/test/unit/decorator/repository-with-di.ts, packages/repository/test/unit/decorator/repository-with-value-provider.ts, packages/repository/test/unit/decorator/repository.ts, packages/repository/test/unit/model/model.ts, packages/repository/test/unit/repository/legacy-juggler-bridge.ts
**Fix `DefaultCrudRepository` methods to return expected instances**
Before, the type annotation of DefaultCrudRepository said that CRUD methods are returning Entity instances, but in fact these methods were returning PersistedModel instances.
Note that PersistedModel is inheriting from juggler's ModelBase class, while Entity is inheriting from our new Model base class, and these two inheritance chains never meet.
This commit fixes DefaultCrudRepository to convert internal PersistedModel instances into the correct Entity instances expected by the users of this class.
Under the hood, DefaultCrudRepository was changed to expect the Entity model constructor function in the constructor argument, and build the backing PersistedModel as an internal implementation detail. This is possible thanks …
=> feat(repository): simplify usage of juggler bridge

packages/repository/src/legacy-juggler-bridge.ts
Fix the following problem reported by `npm pack`:
Error: packages/repository/src/legacy-juggler-bridge.ts(100)
Type 'typeof ModelBase' is not assignable to
type 'typeof PersistedModel'.
Property 'create' is missing in type 'typeof ModelBase'.
I think the problem  was introduced by mine #539.
=> fix(repository): correct types in juggler bridge

.travis.yml, bin/lint-commits.sh, commitlint.config.js, package.json
This adds a commit message linter that enforces the conventional commit format that will be our new standard moving forward as it allows us to generate CHANGELOG’s using lerna automatically.
connect to #263
=> Adding conventional commit linting

packages/core/src/application.ts, packages/core/src/component.ts, packages/repository/package.json, packages/repository/src/index.ts, packages/repository/src/repository-mixin.ts, packages/repository/test/unit/repository-mixin/repository-mixin.test.ts
Adds a mixin to allow a user to bind a repository using app.repository(). Also automatically binds repositories passed into a constructor and binds any repositories exported by any components that are registered with the application. 
Connect to #425
=> feat(repository): Introduce Mixin to support repo binding

packages/core/src/application.ts, packages/core/test/integration/application.integration.ts
Add `/swagger-ui` which would redirect users to the online SwaggerUI instance with the app's OpenAPI spec loaded and CORS enabled so they could access their endpoints from it.
- closes #506 
=> Add CORS headers for swagger/openapi endpoints so that the spec can be rendered with petstore.swagger.io

bin/lint-commits.sh
Rebased PR's would often encounter a git range error because travis ENV
set COMMIT SHA to original (before rebase). So this updates it to the
PR SHA.
Example of a failed Travis Build where the $TRAVIS_COMMIT SHA can be seen to be outdated (compared against GitHub) but $TRAVIS_PULL_REQUEST_SHA is correct (again verified in GitHub). This was noticed as a result of the debug info seen in the Commit Linting check now. 
Failed PR: https://travis-ci.org/strongloop/loopback-next/jobs/277095188
Log incase Travis Log disappears:
```
0.93s$ /bin/bash ./bin/lint-commits.sh
TRAVIS_BRANCH => master
TRAVIS_COMMIT => 839f313f632406b140ee86be05f0ee4dac8255c4
TRAVIS_COMMIT_MSG => Merge a12bc147695746493c32af4b15deb14bd1488c70 into ae0bec96a06c98ab8219eb9a0733b3aae38dba0b
TRAVIS_COMMIT_RANGE => …
```
=> ci: fix commit linter rebase PR git range error

packages/repository/README.md
=> docs(repository): explain usage of RepositoryMixin

packages/context/src/binding.ts, packages/context/src/context.ts, packages/context/src/resolver.ts, packages/context/test/acceptance/class-level-bindings.ts, packages/context/test/unit/context.ts
Fix the implementation of `@inject` resolver to correctly support nested properties.
Simplify the implementation of nested properties to avoid edge cases that are difficult to support:
- All Context methods creating/returning full Binding instances require a key without property-path suffix.
- Only `get` and `getSync`, which are (eventually) returning the bound value only, allow property-path suffix.
- A new method `getValueOrPromise` is introduced, this is an internal method shared between `get`, `getSync` and `@inject` (`instantiateClass`). This method supports keys with property-path suffix too.
Connect to #567
See also #576 which discovered this problem, and #377 which implemented the initial support for nested properties.
=> fix(context): inject nested properties

packages/rest/src/keys.ts, packages/rest/src/rest-component.ts
Remove the workaround for retrieving "rest" config options and instead use the original hash-based property retrieval.
#567 
=> refactor(rest): Index rest config with hash

packages/core/src/component.ts, packages/core/test/unit/application.test.ts, packages/rest/src/rest-component.ts
BREAKING CHANGE: Components whose servers were originally in an array called "servers" must now provide key-value pairs in an object called "servers".
#567
=> refactor(core): Component servers are now key-value pairs

packages/rest/src/rest-component.ts
Moving it up to the definition rather than having it in the constructor means that overriding implementations can change which servers to instantiate as a default (or to opt out of doing so entirely!)
=> fix(rest): Move server instantiation to class definition

packages/authentication/package.json, packages/context/package.json, packages/core/package.json, packages/example-codehub/package.json, packages/openapi-spec-builder/package.json, packages/openapi-spec/package.json, packages/repository/package.json, packages/rest/package.json, packages/testlab/package.json
Add missing `engines` field to specify the minimum supported Node.js version, which is Node.js 6.x
=> build: add "engines" to all "package.json" files

.travis.yml, appveyor.yml
For pull requests sent from a feature branch living in the same
repository, both AppVeyor and Travis CI is running two CI jobs,
which is unnecessarily slowing down our feedback cycle:
- continuous-integration/appveyor/branch
- continuous-integration/appveyor/pr
and
- continuous-integration/travis-ci/pr
- continuous-integration/travis-ci/push
This commit changes AppVeyor config to skip CI for the branch
and run it for the pull request only.
In order to achieve the same on Travis, we are restricting the branches
built by CI to "master" only. (This means we will need to update Travis
config when forking a long-living "N.x" branch.)st only.
See also https://github.com/appveyor/ci/issues/882 and https://github.com/voxpupuli/modulesync_config/commit/bcccf0035903b35006d0f65af3ac708eaf20f8d6
=> build: skip CI of feature branches with an open PR

bin/select-dist.js
Fix "bin/select-dist.js" used to run Mocha tests to quote all arguments in order to preserve glob patterns like `test/**/*.js` and pass them as-is to Mocha, instead of letting the Unix shell incorrectly expand "**" as "*".
Before this change (but after 3698d76), we were running only tests that are exactly two-levels deep in the `test` directory tree, e.g. `test/acceptance/{name}.js`. With this change in place, we are running tests nested more deeply again, e.g. `test/unit/router/metadata/param-body.test.js`
Thank you @raymondfeng and @kjdelisle for spotting the problem!
=> build: fix select-dist to preserve args

package.json
Upgrade to mocha 4.0 (use --exit for backward compatibility for now)
Fix coverage inclusion from lib* to dist*
Upgrade commitlint related deps
=> build: Upgrade deps and fix coverage inclusion

.vscode/settings.json
Disable prettier-eslint integration in order to avoid the following
error:
ImportDeclaration should appear when the mode is ES6 and in the module context.
See the following two GitHub issues for more details:
- https://github.com/eslint/eslint/issues/4344
- https://github.com/eslint/typescript-eslint-parser/issues/117
This change should not have any negative side effects, since we are
not using eslint in this project.
@raymondfeng PTAL
=> chore: disable prettier-eslint integration in VSCode

README.md
connect to: https://github.com/strongloop/loopback-next/issues/625
=> docs:Update README for better DX

packages/rest/test/unit/router/reject.test.ts, packages/testlab/package.json, packages/testlab/src/testlab.ts
The sinon-should integration has some bad side effects, for example:
expect(() => throw new Error()).to.throw(...) is broken.
Also see https://github.com/strongloop/loopback-next/issues/641
=> fix(testlab): Remove sinon-should integration

packages/rest/src/http-handler.ts, packages/rest/src/writer.ts, packages/rest/test/unit/writer.test.ts
The response.write function requires a string or Buffer for the
final output. This change converts boolean and numeric values to
strings as well to prevent unhandled errors from being thrown
due to the output type.
connected to https://github.com/strongloop/loopback4-example-getting-started/pull/1
=> fix(rest): convert other primitive types to string

bin/generate-apidocs.js
This is a workaround for typedoc, which does not always have the same
version of TypeScript for our project. The script forces typdoc to use
project-level TypeScript dependency by renaming
`typedoc/node_modules/typescript` to `typedoc/node_modules/typescript.bak`.
=> build: Force typedoc to use the project-level TypeScript

.vscode/settings.json, package.json
=> chore: Fix vscode settings to exclude dist and dist6

.github/PULL_REQUEST_TEMPLATE.md, packages/build/bin/compile-package.js, packages/build/bin/utils.js, packages/build/test/integration/scripts.test.js
Fix two issues in the lb-tsc:
1. tsconfig requires relative path to be started with `./` or `../`
2. getConfigFile debug for default name
=> build: Fix build script for tsc

packages/repository/src/legacy-juggler-bridge.ts, packages/repository/test/unit/repository/legacy-juggler-bridge.ts
findById will now reject if there is no result returned from the database.
=> fix(repository): findById rejects on no result

packages/core/src/application.ts, packages/core/test/acceptance/application.acceptance.ts
An array of controllers can now be passed into the array to be bound
automatically.
=> feat(core): allow controllers to be bound via constructor

packages/cli/lib/project-generator.js, packages/cli/test/project.js
Replace `yo loopback4:` with `lb4 ` in the help text.
=> fix: Fix help text for cli

package.json, packages/rest/src/providers/log-error-provider.ts, packages/rest/src/providers/reject.ts, packages/rest/src/writer.ts, packages/rest/test/integration/http-handler.integration.ts, packages/rest/test/unit/writer.test.ts, test/mocha.opts
Error are now sent back as json object per HttpError structure
Error properties are controlled by `expose`
Only log http 5xx errors to console
=> feat(rest): Improve http error handling

packages/core/src/application.ts
Make sure `app.server()` and `app.servers()` to return binding(s) so that these apis are consistent with `app.controller` etc.
=> fix(core): Return binding(s) for app.server/servers

packages/context/src/index.ts, packages/context/src/inject.ts, packages/context/src/resolver.ts, packages/context/test/acceptance/_feature.md, packages/context/test/acceptance/class-level-bindings.feature.md, packages/context/test/acceptance/method-level-bindings.feature.md, packages/context/test/acceptance/method-level-bindings.ts, packages/context/test/unit/resolver.test.ts, packages/core/package.json
The PR adds the ability to declare method parameter dependency injections using `@inject`.
- Add `invokeMethod` to invoke a prototype method of a given class with dependency injection
- https://github.com/strongloop/loopback-next/blob/c4051416eb0d7dc1ac249557819885700519927d/packages/context/test/acceptance/method-level-bindings.feature.md
Connect to https://github.com/strongloop/loopback-next/issues/139
=> feat(context): Add method dependency injection

packages/rest/src/keys.ts, packages/rest/src/rest-server.ts, packages/rest/test/integration/rest-server.integration.ts, packages/rest/test/unit/rest-server/rest-server.test.ts
Introduce host and apiExplorerUrl rest config options
Use https://loopback.io/api-explorer as the hosted UI
See https://github.com/strongloop/loopback.io/pull/530
- connect to https://github.com/strongloop/loopback.io/pull/530
=> feat(rest): Make rest host and explorer configurable

packages/rest/package.json, packages/rest/src/router/metadata.ts, packages/rest/test/unit/router/metadata.test.ts
Make sure metadata inherited from base classes are cloned to avoid
pollution of base information
=> fix(rest): Improve rest metadata inheritance

packages/rest/src/router/routing-table.ts, packages/rest/test/unit/router/routing-table.test.ts
Avoid describing parameters if debug is not on
Check undefined parameters (not decorated with @param) in the array
=> fix(rest): Fix parameter description

packages/rest/src/rest-server.ts, packages/rest/test/unit/rest-server/rest-server.test.ts
Fix https://github.com/strongloop/loopback4-example-getting-started/issues/9
- connect to https://github.com/strongloop/loopback4-example-getting-started/issues/9
=> fix(rest): Listen on all interfaces if host is not configured

packages/cli/lib/artifact-generator.js, packages/cli/test/controller.js
- removed default name for the controller name prompt in favor of forcing user to give the controller a name
=> feat(cli): remove default option for controller

packages/rest/package.json
Move @types/http-errors from dev-dependency to dependency. Previously, project scaffolded by @loopback/cli would not compile when using @loopback/rest~11. On a side note, when the CLI is run on node 8.4 it installs rest@alpha.11, while node 8.7 installs rest@alpha.9. This may need to be looked into as well.
=> fix(rest): move @types/http-errors from dev-dep

packages/cli/generators/app/index.js, packages/cli/generators/controller/index.js, packages/cli/generators/extension/index.js, packages/cli/lib/artifact-generator.js, packages/cli/lib/base-generator.js, packages/cli/lib/project-generator.js, packages/cli/package.json, packages/cli/test/artifact.js
Throwing an error in yeoman is ugly. This PR allows a generator
to abort with a reason. The reason will be logged at the end.
=> feat: Add exit() to abort generation

packages/cli/generators/project/templates/package.json, packages/cli/generators/project/templates/package.plain.json
The caret (`^`) doesn't work for prerelease packages, so now the templates will use `>` for determining which prerelease is "newer"/"newest".
=> fix(cli): use prerelease versioning for templates

package.json, packages/rest/src/internal-types.ts, packages/rest/src/router/routing-table.ts
@types/node@8.0.56 introduces a breaking change for URL and our build
fails due to imcompatible types
=> fix(rest): Fix compilation error caused by @types/node

test/mocha.opts
With more than 400 hundred test cases, the output of the default Mocha reporter produces several screens of text, which is no longer useful.
This commit changes the test reporter to `dot`, which is the same reporter we are already using in LoopBack3 repositories.
=> test: use dot reporter

packages/rest/src/providers/bind-element.ts, packages/rest/src/providers/find-route.ts, packages/rest/src/providers/get-from-context.ts, packages/rest/src/providers/invoke-method.ts, packages/rest/src/providers/log-error-provider.ts, packages/rest/src/providers/reject.ts
Refactor sequence-action providers to use a named "action" method
to hold the actual action implementation, and change the anonymous
lambda (arrow) functions returned by "value" methods to delegate
to these new "action" methods.
This improves error stack traces in cases where the action fails.
Before this change, there would be no reference to the actual sequence
action that failed. After this change, the stack trace contains
an entry for "{Action}Provider.action" function.
This is a follow-up for my older comment https://github.com/strongloop/loopback4-example-log-extension/pull/3#discussion_r150567441:
> I was thinking about this pattern recently. When something wrong happens inside a sequence action implemented as an anonymous function, the stack trace will contain an empty function …
=> refactor(rest): use named functions for sequence actions

packages/repository/src/common-types.ts, packages/repository/src/connector.ts, packages/repository/src/legacy-juggler-bridge.ts, packages/repository/src/loopback-datasource-juggler.ts, packages/repository/src/query.ts, packages/repository/src/repository.ts, packages/repository/test/unit/query/query-builder.ts, packages/repository/test/unit/repository-mixin/repository-mixin.test.ts
The PR adds `execute()` and `builders` for our `Filter/Where` objects.
=> Add builders and execute for repository

package.json
The command invokes `lerna` to tag and publish next prereleases for all packages:
```
lerna publish --cd-version=prerelease --preid=alpha
```
=> chore: Add `npm run release` option

packages/rest/src/index.ts, packages/rest/src/rest-application.ts, packages/rest/test/acceptance/bootstrapping/rest.acceptance.ts, packages/rest/test/unit/rest-application/rest-application.test.ts
This implementation simplifies the use-case for anyone that wants
to create a single-server REST application without needing to
handle RestComponent.
connected to https://github.com/strongloop/loopback-next/pull/770
(see https://github.com/strongloop/loopback-next/pull/770#issuecomment-350200436) for details
=> feat(rest): Single-server RestApplication

packages/repository/src/decorators/model.ts, packages/repository/test/unit/decorator/model-and-relation.ts
The `@property` decorator no longer requires a parameter.
=> feat(repository): Make property parameter optional

packages/repository/src/decorators/model.ts, packages/repository/test/unit/decorator/model-and-relation.ts
Provide a nicer UX for the super-difficult-to-introspect array
properties, while limiting the amount of required information to
the class definition (while still allowing an optional props object)
=> feat(repository): Add array decorator

packages/metadata/src/decorator-factory.ts, packages/metadata/test/unit/decorator-factory.test.ts
Introduce `cloneInputSpec` to `DecoratorOptions` so that input
spec is cloned. It's set to `true` by default.
=> feat(metadata): Add a flag to keep args of decorators safe

package.json, packages/authentication/package.json, packages/context/package.json, packages/core/package.json, packages/metadata/package.json, packages/openapi-spec-builder/package.json, packages/openapi-spec/package.json, packages/repository/package.json, packages/rest/package.json, packages/testlab/package.json
- Replace Unix `rm -rf` command with `lb-clean` which is a node.js script that runs on all supported platforms.
- Remove unused dependencies in `loopback-next/package.json`.
=> chore: Use lb-clean script to clean the build

packages/metadata/README.md, packages/metadata/src/decorator-factory.ts, packages/metadata/test/unit/decorator-factory.test.ts
The PR fixes how method level parameter decorations are processed to make sure the order
of decorations match the number of parameters of the target method. It also uses a cache to 
track the parameter index.
=> fix(metadata): fix method-level parameter decorators

packages/rest/src/router/routing-table.ts, packages/rest/test/unit/rest-server/rest-server.open-api-spec.test.ts
Swagger UI uses tags to group REST operations. This PR sets the controller
name as the default tag if not provided by the operation spec.
=> feat(rest): set controller name as the default tag

packages/repository/src/decorators/model.ts, packages/repository/test/unit/decorator/model-and-relation.ts
Allows the name to be optional for `@model` so that you can provide the other options for a ModelDefinition without having to provide redundant data (you can still provide it to override this behaviour)
```ts
@model({
settings: { ... }
})
class Widget {
// will return metadata of { name: 'Widget', settings: { ... } }
}
```
=> refactor(repository): model decorator accepts options without name

packages/repository/src/decorators/metadata.ts, packages/repository/src/decorators/model.ts, packages/repository/src/index.ts, packages/repository/test/unit/decorator/metadata.ts
A helper function to roll the properties metadata into one object with the model's metadata.
connected to #786
=> feat(repository): helper function for getting Model metadata

package.json, packages/cli/test/project.js, packages/cli/test/test-utils.js
CLI Tests aren't run as part of top level `npm test`. Test count before change was 609. After this change it is 694.
=> test: run cli tests in top level npm test

packages/cli/bin/cli.js, packages/cli/generators/controller/index.js, packages/cli/lib/artifact-generator.js, packages/cli/lib/debug.js
Add scoped debugging to the CLI module, as well as some new debugging statements to the artifact-generator and the controller-generator.
Adding these statements to make my life easier when building the feature for the linked issue.
connected to https://github.com/strongloop/loopback-next/issues/727
=> feat(cli): add scoped debugging

packages/cli/generators/app/templates/src/controllers/ping.controller.ts, packages/cli/generators/project/templates/package.json, packages/cli/generators/project/templates/package.plain.json, packages/cli/test/app.js, packages/cli/test/project.js
Fix the cli template that missing `openapi-v2`
=> fix: add new openapi package

packages/openapi-spec-builder/src/openapi-spec-builder.ts
Added a function to allow tags to be specified when building an OpenAPI's operation spec.
With the newest commit that assigns default tag to the swagger spec, this PR would allow an easier time writing acceptance tests.
=> feat(openapi-spec-builder): add withTags function to spec-builder

packages/openapi-v2/package.json
Rename "unit" to "test" in package.json, to ensure `npm test` executed from the package directory actually runs any tests.
This is a follow-up for recently landed #804 
- (n/a) New tests added or existing tests modified to cover all changes
- (n/a) Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
=> build(openapi-v2): fix the test script

package.json, packages/repository/package.json
Before this PR, `npm run release` does not trigger clean/build/test. As a result, there is possibility that some packages are not fully built/tested before being published.
=> fix: ensure `npm run release` runs clean/build/test

packages/context/src/binding.ts, packages/context/test/unit/binding.ts
The current rest config key `RestBinding.CONFIG` in `packages/rest/keys.ts` is defined as `${CoreBindings.APPLICATION_CONFIG}#rest`.
It is safer to use an exported function from `context/binding` where both the concatenation and split are implemented.
The new key is `export const CONFIG = Binding.concatKeyAndPath (CoreBindings.APPLICATION_CONFIG, rest)`
=> feat(context): export function to concat the binding key and path

packages/core/src/component.ts, packages/repository/src/connector.ts, packages/repository/src/decorators/metadata.ts, packages/repository/src/legacy-juggler-bridge.ts, packages/repository/src/query.ts, packages/repository/src/types/model.ts, packages/repository/src/types/object.ts, packages/rest/src/parser.ts, packages/rest/src/providers/log-error-provider.ts, packages/rest/src/rest-application.ts, packages/rest/src/rest-server.ts
Importing from the root index leads to circular resolution and cause
undefined artifacts. Since the root index re-export such artifacts, the
compilation is good but it fails at runtime. For example:
`/src/index.js --> src/decorators/metadata.js --> /src/index.js`
=> fix: fix imports to use files owning the definitions

packages/build/bin/run-prettier.js, packages/build/config/tslint.common.json, packages/build/package.json
- fix build break by newer version of prettier (https://travis-ci.org/strongloop/loopback-next/jobs/327503885)
- upgrade tool dependencies
=> fix: fix build break and upgrade dependencies

packages/repository/src/legacy-juggler-bridge.ts, packages/repository/test/unit/repository/legacy-juggler-bridge.ts
Recreate PR from https://github.com/strongloop/loopback-next/pull/839
=> feat: add findOne function into legacy juggler bridge

packages/rest/index.ts, packages/rest/test/unit/backward-compatibility.test.ts
=> fix: export decorators for backward compatibility

packages/context/src/binding.ts, packages/context/test/unit/binding.ts, packages/context/test/unit/context.ts, packages/context/test/unit/resolver.test.ts
Promises are a construct primarily intended for flow control: In an algorithm with steps 1 and 2, we want to wait for the outcome of step 1 before starting step 2.
Promises are NOT a tool for storing values that may become available in the future, depending on the success or a failure of a background async task.
Values stored in bindings are typically accessed only later, in a different turn of the event loop or the Promise micro-queue. As a result, when a promise is stored via `.to()` and is rejected later, then more likely than not, there will be no error (catch) handler registered yet, and Node.js will print "Unhandled Rejection Warning".
It is no longer possible to pass a promise instance to `.to()` method of a Binding. Use `.toDynamicValue()` instead. Consider …
=> feat(context): forbid bind().to() a Promise instance

commitlint.config.js
The setting controls the total length of the footer, not a maximum
allowed line length :(
See https://github.com/strongloop/loopback-next/pull/854 and https://travis-ci.org/strongloop/loopback-next/jobs/328017516#L1155
- n/a `npm test` passes on your machine
- n/a New tests added or existing tests modified to cover all changes
- n/a Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- n/a Related API Documentation was updated
- n/a Affected artifact templates in `packages/cli` were updated
- n/a Affected example projects in `packages/example-*` were updated
=> build: disable commit linter's footer-max-length

.vscode/settings.json, packages/build/config/tslint.build.json, packages/build/config/tslint.common.json
- Fix tslint integration with VS Code
- Move the configuration of "no-unused-variables"
from tsling.common.json to tslint.build.json to avoid warnings printed
to VS Code console
- (n/a) New tests added or existing tests modified to cover all changes
- (n/a) Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- (n/a) Related API Documentation was updated
- (n/a) Affected artifact templates in `packages/cli` were updated
- (n/a) Affected example projects in `packages/example-*` were updated
=> Fix tslint-related configuration

packages/cli/.gitignore, packages/cli/bin/cli.js, packages/cli/generators/example/clone-example.js, packages/cli/generators/example/index.js, packages/cli/lib/promisify.js, packages/cli/package.json, packages/cli/test/clone-example.test.js, packages/cli/test/example.test.js, packages/cli/test/test-utils.js, packages/core/src/promisify.ts
Implement a new CLI command for cloning an example project from our monorepo.
```
Usage:
lb4 example [options] [<example-name>]
Arguments:
example-name  # Name of the example to clone  Type: String  Required: false
Available examples:
codehub: A GitHub-like application we used to use to model LB4 API.
```
The command:
- downloads the current master branch as a ZIP file from GitHub to a temp file,
- creates a local directory called `loopback4-example-${name}` and
- extracts all ZIP files from `packages/example-${name}` to this new directory.
See https://github.com/strongloop/loopback-next/issues/836
=> feat(cli): lb4 example [<example-name>]

packages/cli/README.md, packages/cli/generators/controller/index.js, packages/cli/generators/controller/templates/src/controllers/controller-rest-template.ts, packages/cli/lib/artifact-generator.js, packages/cli/lib/base-generator.js, packages/cli/lib/utils.js, packages/cli/package.json, packages/cli/test/controller.js, packages/cli/test/test-utils.js, packages/cli/test/utils.js, packages/core/package.json, packages/core/src/promisify.ts
CLI command for generating controllers now supports the creation of a CRUD controller template.
- You will now receive a prompt to select which kind of controller to generate
- If you select "Basic CRUD controller", it will scan for models and repositories, then prompt you to select an applicable model/repository
- If no models or repositories exist in the appropriate directories, you will receive an error.
Implements #727 (Part 1 of 2)
=> feat(cli): generate controller with CRUD methods

commitlint.config.js, package.json
Drop Angular config, which no longer supports "chore" type. Start using Conventional config, which was forked from the Angular config to preserve the "chore" type.
- (n/a) `npm test` passes on your machine
- (n/a) New tests added or existing tests modified to cover all changes
- (n/a) Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- (n/a) Related API Documentation was updated
- (n/a) Affected artifact templates in `packages/cli` were updated
- (n/a) Affected example projects in `packages/example-*` were updated
=> build: use conventional commitlint config

packages/context/docs.json, packages/context/package.json, packages/context/src/binding.ts, packages/context/src/context.ts, packages/context/src/index.ts, packages/context/src/inject.ts, packages/context/src/resolution-session.ts, packages/context/src/resolver.ts, packages/context/test/unit/binding.ts, packages/context/test/unit/resolver.test.ts, packages/metadata/src/decorator-factory.ts, packages/metadata/test/unit/decorator-factory.test.ts
Add ability to track dependency resolution and detect circular dependencies. This is a spin-off from https://github.com/strongloop/loopback-next/pull/671.
See #535
=> Track dependency resolution

packages/context/package.json, packages/context/src/inject.ts, packages/context/src/resolution-session.ts, packages/context/test/acceptance/class-level-bindings.ts, packages/metadata/package.json
Add `@inject.tag` decorator to allow injection of an array of bound values by a tag.
This DI can be used with the extension point/extension pattern so that the extension point can receive injection all extensions.
This is a spin-off from #671. The PR will be enhanced with ResolutionSession once https://github.com/strongloop/loopback-next/pull/852 is landed.
=> feat(context): add @inject.tag to allow injection by a tag

.gitignore, packages/authentication/.gitignore, packages/cli/.gitignore, packages/context/.gitignore, packages/core/.gitignore, packages/core/.travis.yml, packages/metadata/.gitignore, packages/openapi-spec-builder/.gitignore, packages/openapi-spec/.gitignore, packages/openapi-v2/.gitignore, packages/repository/.gitignore, packages/rest/.gitignore, packages/testlab/.gitignore
Follow up based on a review comment here:
https://github.com/strongloop/loopback-next/pull/858#discussion_r161526236
This removes package level .gitignore and .travis.yml files in favour
of top-level files.
- [n/a] New tests added or existing tests modified to cover all changes
- [n/a] Related API Documentation was updated
- [n/a] Affected artifact templates in `packages/cli` were updated
- [n/a] Affected example projects in `packages/example-*` were updated
=> refactor: use top-level .gitignore & .travis.yml

packages/cli/generators/example/index.js, packages/cli/test/example.test.js, packages/example-getting-started/.npmrc, packages/example-getting-started/LICENSE, packages/example-getting-started/README.md, packages/example-getting-started/config/datasources.json, packages/example-getting-started/data/db.json, packages/example-getting-started/index.d.ts, packages/example-getting-started/index.js, packages/example-getting-started/index.ts, packages/example-getting-started/package.json, packages/example-getting-started/src/application.ts, packages/example-getting-started/src/controllers/index.ts, packages/example-getting-started/src/controllers/todo.controller.ts, packages/example-getting-started/src/datasources/db.datasource.ts, packages/example-getting-started/src/index.ts, packages/example-getting-started/src/models/index.ts, packages/example-getting-started/src/models/todo.model.ts, packages/example-getting-started/src/repositories/index.ts, packages/example-getting-started/src/repositories/todo.repository.ts, packages/example-getting-started/test/acceptance/application.test.ts, packages/example-getting-started/test/helpers.ts, packages/example-getting-started/test/unit/controllers/todo.controller.test.ts, packages/example-getting-started/tsconfig.build.json
The loopback4-example-getting-started repository is now being moved into the monorepo
blocks #727 
implements a part of #836
=> feat(getting-started): migrate into monorepo

packages/example-getting-started/tsconfig.build.json
Without this, the build will break when the module is separately installed using `lb4 example`.
connected to #727
=> fix(example-getting-started): fix "extends" path to point to @loopback/build module

packages/rest/index.ts, packages/rest/src/index.ts, packages/rest/test/integration/rest-server.integration.ts
Before this change, decorators from openapi-v2 were exported at compile time only.
This patch moves the re-export from `index.ts` to `src/index.tx` to fix this problem.
See https://github.com/strongloop/loopback-next/pull/883 for a discussion about how to prevent this kind of problems to resurface in the future.
=> fix(rest): correctly re-export decorators at runtime

packages/rest/test/integration/rest-server.integration.ts
The master build is failing due to textual diffs in yaml documents produced.
=> fix(rest): fix yaml comparison to tolerate textual diffs

packages/openapi-v2/package.json
All our packages use `lb-clean` except for `openapi-v2`. This makes it consistent with other packages. `rm -rf` doesn't work on Windows without certain utilities installed while `lb-clean` will work on all OS platforms since it uses `rimraf`. 
- [n/a] New tests added or existing tests modified to cover all changes
- [n/a] Related API Documentation was updated
- [n/a] Affected artifact templates in `packages/cli` were updated
- [n/a] Affected example projects in `packages/example-*` were updated
=> refactor(openapi-v2): use lb-clean instead of rm -rf to be OS agnostic

packages/openapi-v2/src/controller-spec.ts, packages/rest/src/router/routing-table.ts, packages/rest/test/acceptance/routing/routing.acceptance.ts, packages/rest/test/unit/router/routing-table.test.ts
This PR allows controller methods to use dependency injection.
=> feat(rest): Enable method dependency injection for controllers

.vscode/launch.json
Fix the path to source files passed to Mocha when debugging tests
in VisualStudio Code.
This is a follow-up for 0b49badd which removed ts-node from our project.
=> build(vscode): fix debugger setup

CODEOWNERS, packages/cli/generators/example/index.js, packages/example-getting-started/package.json, packages/example-log-extension/.npmrc, packages/example-log-extension/.prettierignore, packages/example-log-extension/LICENSE, packages/example-log-extension/README.md, packages/example-log-extension/index.d.ts, packages/example-log-extension/index.js, packages/example-log-extension/index.ts, packages/example-log-extension/package.json, packages/example-log-extension/src/component.ts, packages/example-log-extension/src/decorators/log.decorator.ts, packages/example-log-extension/src/index.ts, packages/example-log-extension/src/keys.ts, packages/example-log-extension/src/mixins/log-level.mixin.ts, packages/example-log-extension/src/providers/log-action.provider.ts, packages/example-log-extension/src/providers/log-level.provider.ts, packages/example-log-extension/src/providers/timer.provider.ts, packages/example-log-extension/src/types.ts, packages/example-log-extension/test/acceptance/log.extension.acceptance.ts, packages/example-log-extension/test/unit/decorators/log.decorator.unit.ts, packages/example-log-extension/test/unit/mixins/log-level.mixin.unit.ts, packages/example-log-extension/test/unit/providers/log-action.provider.unit.ts, packages/example-log-extension/test/unit/providers/log-level.provider.unit.ts, packages/example-log-extension/test/unit/providers/timer.provider.unit.ts, packages/example-log-extension/tsconfig.json
The first commit 76558a6 brings in an exact copy of https://github.com/strongloop/loopback4-example-log-extension.
The second commit f4dd44e contains changes necessary to integrate the example with the rest of the monorepo.
See #836
=> Bring in loopback4-example-log-extension

packages/example-log-extension/package.json
Set `private` flag in package.json so that `lerna publish` won't push it to npm.
=> fix: mark example-log-extension private to avoid npm publish

.travis.yml, appveyor.yml, package.json, packages/repository-json-schema/package.json
current test script run pretest which cleans and rebuilds the project. This isn't needed on CI as
it's a clean build every time.
=> ci: skip re-build again in pretest

packages/build/bin/generate-apidocs.js, packages/build/test/integration/scripts.test.js
The generate-apidocs script has a workaround to remove local dependency
of TypeScript from typedoc module so that our version of TS will be used.
=> fix: remove typedoc/node_modules/.bin from local typescript dep

packages/example-rpc-server/package.json
Use the new "mocha.opts" instead of no-longer-available "mocha.ts.opts".
This is a follow-up for recently-landed #917, see also https://github.com/strongloop/loopback-next/issues/836
cc @kjdelisle @virkt25
=> fix(example-rpc-server): mocha opts, mark as private

.travis.yml, appveyor.yml, package.json, packages/authentication/package.json, packages/cli/generators/project/templates/package.json, packages/context/package.json, packages/core/package.json, packages/example-getting-started/package.json, packages/example-log-extension/package.json, packages/example-rpc-server/package.json, packages/metadata/package.json, packages/openapi-spec-builder/package.json, packages/openapi-spec/package.json, packages/openapi-v2/package.json, packages/repository-json-schema/package.json, packages/repository/package.json, packages/rest/package.json, packages/testlab/package.json
The current build has 'prepare' for each package to:
1. Run tsc for dist
2. Run tsc for dist6
3. Run apidocs generation
Neither 2 or 3 is required for most of our development tasks. Both steps
are pretty time-consuming.
Please note `prepare` is triggered with `npm install`, which is also part
of `erna bootstrap`.
This move will:
1. Speed up our scripts for most cases
2. Continue to ensure dist/dist6 builds and apidocs before publish
=> chore: move tasks from prepare to prepublishOnly

packages/build/bin/generate-apidocs.js, packages/build/package.json, packages/build/test/integration/scripts.test.js
This change makes sure typedoc runs with the same configuration as tsc
and tslint do.
=> fix(build): upgrade to strong-docs@1.7.1

packages/context/test/acceptance/method-level-bindings.feature.md, packages/context/test/acceptance/method-level-bindings.ts, packages/example-log-extension/package.json, packages/example-log-extension/src/providers/log-action.provider.ts, packages/example-log-extension/src/providers/log-level.provider.ts, packages/example-log-extension/test/acceptance/log.extension.acceptance.ts, packages/example-log-extension/test/unit/providers/log-action.provider.unit.ts, packages/rest/package.json, packages/rest/src/providers/log-error-provider.ts, packages/rest/test/integration/http-handler.integration.ts
See https://github.com/strongloop/loopback-next/issues/935
=> fix: remove console output from tests

.travis.yml
This PR looks to add osx to our travis build matrix. It gives us more platform coverage, but is also used as a way to fix build issue arising from #948.
=> ci: add osx to build matrix

packages/example-getting-started/package.json, packages/example-getting-started/src/application.ts
- `application.ts` now extends `RestApplication` instead of `Application`
- also added missing imports (`@loopback/openapi-spec` for `todo.model.ts`)
- connected to #846
=> fix(example-getting-started): use RestApplication

packages/cli/generators/project/templates/tslint.json, packages/context/src/binding.ts, packages/context/src/inject.ts, packages/context/src/resolution-session.ts, packages/context/test/unit/value-promise.test.ts, packages/example-getting-started/src/application.ts, packages/example-getting-started/src/datasources/db.datasource.ts, packages/example-hello-world/src/application.ts, packages/openapi-v2/src/controller-spec.ts, packages/repository-json-schema/src/build-schema.ts, packages/testlab/src/test-sandbox.ts, packages/testlab/test/integration/test-sandbox.integration.ts, tslint.json
This fixes a regression from https://github.com/strongloop/loopback-next/commit/15dd2dbd962882a63edb2227b2688dbdc961be80
=> fix(build): use `tslint.build.json` as the base

packages/example-getting-started/src/controllers/todo.controller.ts, packages/example-getting-started/test/acceptance/application.test.ts, packages/metadata/src/decorator-factory.ts, packages/metadata/test/unit/decorator-factory.test.ts
=> fix: use parameter level decorators for openapi params

packages/openapi-v2/test/unit/controller-spec/controller-decorators/param-decorators/param.test.ts, packages/repository-json-schema/README.md, packages/repository-json-schema/src/build-schema.ts, packages/repository-json-schema/test/integration/build-schema.test.ts, packages/repository-json-schema/test/unit/build-schema.test.ts
- previously, `$ref` key in JSON Schemas would be missing `/` between `#` and `definitions`. This PR fixes this
=> fix(repository-json-schema): fix $ref typo

packages/example-getting-started/README.md
connected to #729 
Porting over the same correction contained in https://github.com/strongloop/loopback.io/pull/601
=> docs(example-getting-started): use openapi-v2 decorators in readme

packages/context/package.json, packages/context/src/binding.ts, packages/context/src/context.ts, packages/context/src/index.ts, packages/context/src/inject.ts, packages/context/src/resolution-session.ts, packages/context/src/resolver.ts, packages/context/src/value-promise.ts, packages/context/test/acceptance/class-level-bindings.ts, packages/context/test/unit/context.ts, packages/context/test/unit/resolution-session.ts, packages/context/test/unit/resolver.test.ts, packages/context/test/unit/value-promise.test.ts
This is a cherry-pick of non-controversial changes from #882.
The PR adds a few improvements to our IoC container as I polish
#872.
- Use full resolution path to report circular deps
- Make binding level cache context aware to better handle various scopes
- Add name to context instances to better identify each of them
- Add @inject.context() to express dependency of the current context
- Add decorator to injection metadata so that we can tell which decorator function is used
- Add optional to injection metadata to control if a binding should fail due to missing key
- Add unit tests for ResolutionSession
=> Improve dependency injection/resolution

packages/example-getting-started/src/controllers/todo.controller.ts
Explicitly cast path parameter "id" from string to number because the REST transport does not implement parameter coercion yet. See https://github.com/strongloop/loopback-next/issues/750
This change removes the following warnings from `npm test` output:
WARNING: id property cannot be changed from 3 to 3 for model:Todo
in 'before save' operation hook
WARNING: id property cannot be changed from 3 to 3 for model:Todo
in 'loaded' operation hook
This pull request is an alternative to https://github.com/strongloop/loopback-next/pull/941.
=> fix(example-getting-started): remove juggler warning

packages/context/src/index.ts, packages/context/src/inject.ts, packages/context/src/resolution-session.ts, packages/context/test/unit/resolver.test.ts
This PR introduces `InjectionMetadata` interface to provide more type guidance for the metadata parameter of `@inject.*`.
=> feat(context): formalize injection metadata as an interface

packages/cli/generators/project/templates/tslint.build.json, packages/cli/generators/project/templates/tslint.json, tslint.build.json, tslint.json
This is a follow-up to https://github.com/strongloop/loopback-next/pull/964/.
Two config files are in place now:
- tslint.build.json for CLI build scripts
- tslint.json for vscode
=> chore: separate tslint config files for build and vscode

packages/authentication/README.md, packages/cli/generators/app/templates/src/application.ts, packages/cli/test/app.js, packages/example-hello-world/src/application.ts, packages/example-log-extension/README.md, packages/rest/README.md, packages/rest/package.json
- Move any REST-related setup from app.start() back to app constructor.
- Update the project template to use RestApplication too
- Update authentication README to use RestApplication
This is a follow-up for #955, a part of #846
=> refactor: simplify app setup via RestApplication (part II)

packages/example-getting-started/package.json, packages/example-getting-started/test/unit/controllers/todo.controller.test.ts
Rework example-getting-started to use sinon from @loopback/testlab
instead of importing it directly.
=> fix(example-getting-started): use sinon from testlab

packages/authentication/README.md, packages/authentication/test/acceptance/basic-auth.ts, packages/cli/generators/extension/templates/src/mixins/README.md, packages/cli/generators/extension/templates/src/providers/README.md, packages/core/README.md, packages/core/package.json, packages/core/src/application.ts, packages/core/test/acceptance/application.acceptance.ts, packages/core/test/acceptance/application.feature.md, packages/core/test/unit/application.test.ts, packages/example-getting-started/src/application.ts, packages/example-log-extension/README.md, packages/example-log-extension/test/acceptance/log.extension.acceptance.ts, packages/repository/README.md, packages/repository/src/repository-mixin.ts, packages/repository/test/unit/repository-mixin/repository-mixin.test.ts, packages/rest/README.md, packages/rest/src/rest-application.ts, packages/rest/src/rest-server.ts, packages/rest/test/acceptance/bootstrapping/rest.acceptance.ts, packages/rest/test/acceptance/routing/routing.acceptance.ts, packages/rest/test/acceptance/sequence/sequence.acceptance.ts, packages/rest/test/integration/rest-server.integration.ts, packages/rest/test/unit/rest-application/rest-application.test.ts, packages/rest/test/unit/rest-component.test.ts, packages/rest/test/unit/rest-server/rest-server.controller.test.ts, packages/rest/test/unit/rest-server/rest-server.open-api-spec.test.ts, packages/rest/test/unit/rest-server/rest-server.test.ts
- Tweaked `ApplicationConfig` so that it can no longer be used to set up `components`, `controllers`, or servers
- Components must now be registered through `app.component(MyComponent)`
- Controllers and servers as well through `.controller()` and `.server()`
- ~Added in functions~ Overloaded existing functions to take in multiple components/controllers/servers
- `component([My, List, Of, Components])`
- `server([My, List, Of, Servers])`
- `controller([My, List, Of, Controllers)`
- Also tweaked `RepositoryMixin` so that repositories can no longer be set up through the constructor
- overloaded `repository` to also be able to take in an array of `Repository`ies
- overloaded `component` to also be able to take in an array of `component`s
- First commit involves the code while the second …
=> Decouple application config from features (e.g. components)

packages/cli/generators/project/templates/.prettierignore, packages/cli/generators/project/templates/_.gitignore, packages/cli/generators/project/templates/tsconfig.json.ejs
Follow up from #996 and related to dropping Node 6 support. CLI template had references to `dist6` folders which are no longer generated.
=> chore(cli): update templates to remove Node 6 remnants

MONOREPO.md, README.md
Add a table to describe all packages and common tasks for this monorepo.
=> docs: add description of packages for the monorepo

packages/cli/test/clone-example.test.js
The check for equality on example packages after cloning prevents
update of the contents of those packages, since they are no longer
equivalent! As a result, we are disabling this test for now until
we can come up with something that suitably validates the
behaviour we expect, but in a way that doesn't prevent future
changes from passing tests.
blocks #1001
=> test(cli): disable GitHub cloning tests

packages/rest/src/rest-application.ts, packages/rest/src/rest-component.ts, packages/rest/src/rest-server.ts, packages/rest/test/acceptance/routing/routing.acceptance.ts, packages/rest/test/acceptance/sequence/sequence.acceptance.ts
Enhance `RestApplication` class to provide shortcuts for registering routes and configuring the master OpenAPI spec.
See #846 and #955.
- Affected example projects in `packages/example-*` were updated
=> feat(rest): app.route() and app.api()

CONTRIBUTING.md, docs/DEVELOPING.md, docs/VSCODE.md, docs/apidocs.html
Start a guide for contributors in a place that's [recognized by GitHub](https://help.github.com/articles/setting-guidelines-for-repository-contributors/) - add a short CONTRIBUTING.md file serving as a collection of links pointing to other documentation.
Start a guide for developers in DEVELOPING.md.
Describe VS Code setup in VSCODE.md, document steps needed to verify
integration with tsc and tslint.
Add docs/apidocs.html as an index file pointing to apidoc files of individual monorepo packages.
This work is loosely related to https://github.com/strongloop/loopback-next/issues/950 and #574. Even though it is not in MVP scope, I think it's very important for us internally, to avoid regressions like the one introduced by https://github.com/strongloop/loopback-next/pull/964
I am …
=> docs: add CONTRIBUTING, DEVELOPING and VSCODE

.gitignore, .vscode/settings.json, packages/cli/test/clone-example.test.js
Relax the assertions performed by the test to allow changes reorganizing files around.
Rework the test to async/await style, now that we no longer support Node.js 6.x
Change the sandbox directory from "test/sandbox" to ".sandbox" to prevent interference with code scanning "test" for test files to run.
This is a follow-up for #1003 which disabled this problematic test.
=> fix(cli) Add back the test for cloneExampleFromGitHub

MONOREPO.md
Add some guide on the things to remember when create a new package.
Any other stuff worth mentioning here?
=> doc: add new package

packages/example-getting-started/README.md, packages/example-getting-started/docs/1-prerequisites-and-setup.md, packages/example-getting-started/docs/2-scaffold-app.md, packages/example-getting-started/docs/3-add-legacy-juggler.md, packages/example-getting-started/docs/4-todo-model.md, packages/example-getting-started/docs/5-datasource.md, packages/example-getting-started/docs/6-repository.md, packages/example-getting-started/docs/7-controller.md, packages/example-getting-started/docs/8-putting-it-together.md
The README now links back to the pathways for the tutorial, either on our docs site or in this
package.
connected to #729
continuation of #1001
=> docs(example-getting-started): add links to tutorial paths

package.json, packages/authentication/package.json, packages/boot/package.json, packages/build/package.json, packages/cli/generators/project/templates/package.json.ejs, packages/cli/generators/project/templates/package.plain.json.ejs, packages/cli/package.json, packages/context/package.json, packages/core/package.json, packages/example-getting-started/package.json, packages/example-hello-world/package.json, packages/example-log-extension/package.json, packages/example-rpc-server/package.json, packages/metadata/package.json, packages/openapi-spec-builder/package.json, packages/openapi-spec/package.json, packages/openapi-v2/package.json, packages/repository-json-schema/package.json, packages/repository/package.json, packages/rest/package.json, packages/testlab/package.json
The current versioning `4.0.0-alpha-<x>` makes it difficult to release
breaking changes.
Fixes https://github.com/strongloop/loopback-next/issues/954
=> chore: switch to `0.x.y` for versioning before 4.0 GA

packages/cli/generators/app/templates/src/application.ts.ejs, packages/cli/generators/app/templates/src/sequence.ts.ejs, packages/cli/generators/app/templates/test/ping.controller.test.ts.ejs
Newly scaffolded LB4 apps fail to start:
```
src/application.ts(1,41): error TS2305: Module '"/private/tmp/t1/node_modules/@loopback/core/index"' has no exported member 'BootOptions'.
```
=> fix(cli): fix import for BootOptions (@loopback/boot)

packages/openapi-v3-types/package.json
Update the dev dependency's version after we adopt the new version convention.
=> fix(openapi-v3-types): change dev dependency

packages/cli/README.md
In packages\cli README:
- add the missing `lb4 example` usage 
- change `lb4 app`  to `lb4` command to be consistent with the official documentation.
- If `lb4 app` command is preferred, I can change [this doc](http://loopback.io/doc/en/lb4/Command-line-interface.html) instead. Just want to be consistent
Related to: https://github.com/strongloop/loopback-next/issues/988
=> docs(cli): add lb4 example command to README

packages/example-hello-world/README.md
In packages\example-hello-world README:
- Update the prereq to be Node 8 or higher
- fix typo for the directory name as `loopback4-example-hello-world`
Related to #988
=> docs(example-hello-world): fix typos in README

packages/context/src/resolver.ts, packages/context/test/acceptance/method-level-bindings.ts, packages/rest/test/acceptance/bootstrapping/rest.acceptance.ts
The following function has length of 0 as the param has a default value:
```
hello(@inject('user', {optional: true}) user: string = 'Mary')
```
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/length
Before this fix, the injected value for `user` is not used. The PR uses
decorations to help decide the real number of params.
=> fix(context): fix optional param injection for methods

packages/build/README.md
Fixes https://github.com/strongloop/loopback-next/issues/1027
for config instruction in packages/build README is different from generated LB app
Related to #988 
cc @raymondfeng
=> docs(build): update package.json config content

.vscode/settings.json, packages/cli/generators/app/templates/src/application.ts.ejs
This is a follow-up for #1022 which re-introduced a bad practice of customizing app behavior in `app.start`, something we are trying to get rid of (see e.g. #968 and #994).
=> fix(cli): move sequence customization to app constructor

packages/context/src/context.ts, packages/context/src/inject.ts, packages/context/src/resolution-session.ts, packages/context/src/resolver.ts, packages/context/test/unit/context.ts, packages/core/test/acceptance/application.acceptance.ts, packages/rest/src/rest-server.ts, packages/rest/test/unit/rest-server/rest-server.open-api-spec.test.ts
Sometimes we need to find bindings using multiple conditions, such as
multiple tags or the bound class. The filter function gives us the
maximum flexibility.
=> feat(context): allow context.find by a filter function

packages/testlab/README.md
Minor fixes in packages\testlab README:
- loopback-next -> LoopBack 4
- Contributing link is currently pointing to a wiki page which links to DEVELOPING.md.  Change it to reference DEVELOPING.md directly. 
Related to: #988
=> docs(testlab): fix README

packages/example-getting-started/config/datasources.json, packages/example-getting-started/src/application.ts, packages/example-getting-started/src/repositories/todo.repository.ts, packages/example-getting-started/test/acceptance/application.test.ts, packages/repository/package.json, packages/repository/src/repository-mixin.ts, packages/repository/test/unit/repository-mixin/repository-mixin.test.ts
The PR adds a new dataSource api to `RepositoryMixin` as described in https://github.com/strongloop/loopback-next/issues/743
=> feat(repository): add datasource method on repository mixin

CONTRIBUTING.md, MONOREPO.md, README.md, docs/DEVELOPING.md
-  integrate MONOREPO and DEVELOPING guides
- add "new package checklist"
- sort entries in MONOREPO.md
- add content from the wiki page [Contributing](https://github.com/strongloop/loopback-next/wiki/Contributing/96d17f2f328e060a7ca302d43f78be9db83ad4ae)
This is a follow-up for #977 and #1005 and requires https://github.com/strongloop/loopback-next/pull/1013 to be landed first.
=> Improve developer docs

packages/boot/README.md, packages/boot/docs.json, packages/boot/package.json, packages/boot/src/boot.component.ts, packages/boot/src/booters/controller.booter.ts, packages/boot/src/booters/index.ts, packages/boot/src/booters/repository.booter.ts, packages/boot/src/interfaces.ts, packages/boot/test/acceptance/controller.booter.acceptance.ts, packages/boot/test/fixtures/application.ts, packages/boot/test/fixtures/multiple.artifact.ts, packages/boot/test/integration/repository.booter.integration.ts, packages/boot/test/unit/booters/controller.booter.unit.ts, packages/boot/test/unit/booters/repository.booter.unit.ts, packages/boot/test/unit/bootstrapper.unit.ts, packages/example-getting-started/src/application.ts, packages/example-getting-started/src/controllers/todo.controller.ts, packages/example-getting-started/test/acceptance/application.test.ts, packages/repository/package.json, packages/repository/src/repository-mixin.ts
implements https://github.com/strongloop/loopback-next/issues/781
Repository Booter & update to example app.
- Added `repository` tag when binding a repository using `RepositoryMixin`
=> feat: add repository booter

packages/boot/src/bootstrapper.ts
Extracted from #1050 to keep that other pull request focused on a single change.
=> fix(boot): fix spelling typos

packages/build/bin/run-mocha.js, packages/build/src/fail-on-console-logs.js, packages/rest/test/acceptance/routing/routing.acceptance.ts, packages/rest/test/helpers.ts, packages/rest/test/integration/http-handler.integration.ts
This is a follow-up and a partial revert of #939.
The first commit adds a check to verify that no console logs are produced by our tests, beyond what Mocha prints. This is needed to ensure clean test output in the future.
The second commit reverts the default implementation of `LogError` sequence action to use `console.error` again (instead of `debug`) and fixes tests to suppress error messages for requests that fail with the expected error.
- Related API Documentation was updated
- Affected example projects in `packages/example-*` were updated
=>  fix(rest): log unexpected errors to console

packages/authentication/test/unit/authenticate-action.test.ts, packages/boot/src/bootstrapper.ts, packages/boot/test/unit/bootstrapper.unit.ts, packages/build/config/tslint.build.json, packages/context/src/binding.ts, packages/context/src/context.ts, packages/context/src/index.ts, packages/context/src/resolver.ts, packages/context/src/value-promise.ts, packages/context/test/acceptance/class-level-bindings.ts, packages/context/test/unit/binding.ts, packages/context/test/unit/context.ts, packages/context/test/unit/is-promise.test.ts, packages/example-rpc-server/src/servers/rpc-router.ts, packages/repository/src/decorators/repository.ts, packages/repository/src/legacy-juggler-bridge.ts, packages/repository/src/loopback-datasource-juggler.ts, packages/repository/test/unit/decorator/repository-with-di.ts, packages/repository/test/unit/decorator/repository-with-value-provider.ts, packages/repository/test/unit/decorator/repository.ts, packages/rest/src/http-handler.ts, packages/rest/src/rest-server.ts, packages/rest/test/acceptance/routing/routing.acceptance.ts, packages/rest/test/unit/rest-component.test.ts, packages/rest/test/unit/rest-server/rest-server.test.ts
Modify `ctx.get()` and friends to request callers to explicitly specify
what type they are expecting to receive from the context. This prevents
unintentional introduction of `any` type into our codebase.
Consider the following example:
```ts
const bootstrapper = ctx.get('core.Bootstrapper');
bootstrapper.run(options);
```
The variable `bootstrapper` has type `any`, which is super easy to miss
when reading/reviewing such code.
Once we introduce `any`, the compiler does not check anything - we can
invoke arbitrary methods with arbitrary parameters, the result of such
call is `any` again. As far as the compiler is concerned, the following
code is perfectly valid too:
```ts
const bootstrapper = ctx.get('core.Bootstrapper');
const applause = bootstrapper.danceSamba('hey', 'hou'); …
```
=> feat(context): add type as a generic parameter to `ctx.get()` and friends

packages/openapi-v3/.npmrc
Disables the package-lock file for this package. Noticed it getting created after bootstrapping the monorepo.
=> chore(openapi-v3): disable package-lock

packages/boot/src/booters/repository.booter.ts, packages/boot/test/unit/booters/repository.booter.unit.ts
console warning is excessive / clutters the logs for users. For someone not using the RepositoryMixin, they can enable debug to help identify the issue.
=> fix(boot): warn if attempts to call app.repository without RepositoryMixin

.gitignore, packages/build/index.js, packages/cli/generators/project/templates/package.json.ejs, packages/cli/generators/project/templates/package.plain.json.ejs, packages/cli/lib/project-generator.js, packages/cli/test/app-run.test.js, packages/cli/test/project.js
This PR adds a test to verify `lb app` generates an application that passes `npm test`.
1. The test generates a project at `loopback-next/packages/_sandbox`.
2. The test calls `lerna bootstrap` to set up the deps
3. The test calls `npm test`.
WARNING: The test takes sometime to run and it slows our local build. We need to figure out when to run the test (maybe as part of release).
Connects to https://github.com/strongloop/loopback-next/issues/932
=> test(cli): add a test to verify generated app is passing npm test

.github/ISSUE_TEMPLATE.md
A proposal for a new issues template that is simpler and allows users to ask questions / provide feedback via issues.
fixes #979 and #47
---
_It's hard to change this template by just discussing it so I hope this proposal provides ground for discussion based on something concrete. We can iterate over the content as needed till everyone agrees to a new revision (I think we all agree we need a new template)._
_P.S. Remember we can always try something out and re-iterate when / if needed_
=> chore: update issues template to be simpler

packages/build/package.json, packages/openapi-v3/src/parameter-decorator.ts
At the moment, `@param ...` is rendered as an email link. We add a leading
space to `@param` as a workaround.
=> chore: work around apidocs rendering issue for openapi-v3

packages/rest/package.json
Currently, a type from `cors` is being exported as a part of `RestConfig`:
```ts
export interface RestServerConfig {
host?: string;
port?: number;
cors?: cors.CorsOptions; // HERE
apiExplorerUrl?: string;
sequence?: Constructor<SequenceHandler>;
}
```
This means we need to move the typing for `cors` form dev-dependency to dependency so that users would have access to the type information.
- related to https://github.com/strongloop/loopback-next/issues/1102
=> fix(rest): move @types/cors to dependency

package.json, packages/build/bin/compile-package.js, packages/build/bin/generate-apidocs.js, packages/build/bin/run-clean.js, packages/build/bin/run-mocha.js, packages/build/bin/run-nyc.js, packages/build/bin/run-prettier.js, packages/build/bin/run-tslint.js, packages/build/bin/select-dist.js, packages/build/test/integration/scripts.test.js
The PR addresses two things:
1. Make cli scripts consistent to take `options` for controlling dryRun and spawn
2. Fix a warning from `npm test`
=> Tidy up build

packages/boot/test/acceptance/controller.booter.acceptance.ts, packages/boot/test/integration/controller.booter.integration.ts, packages/boot/test/integration/repository.booter.integration.ts, packages/boot/test/unit/booters/booter-utils.unit.ts, packages/boot/test/unit/booters/controller.booter.unit.ts, packages/boot/test/unit/booters/repository.booter.unit.ts, packages/cli/test/clone-example.test.js
I'm using this style for the repository booter #1030 and think it's cleaner and makes code easier to read and understand as the `resetSandbox` function was just one line. Didn't want to add this to the same PR since it's unrelated files so making a new PR to keep style consistent.
=> style: use lambda function to reset sandbox

docs/package.json, lerna.json
This PR adds `docs` as a package for `loopback-next` monorepo so that `lerna` can publish it as a npm module.
=> chore: add `docs` as a package for loopback-next

packages/core/src/application.ts
came across this while reviewing the code / readme. Making separate PRs for easier review. This usage was introduced in #1050
connected to #988
=> refactor(core): use generics for type casting

packages/cli/generators/project/templates/tsconfig.json.ejs
Previously, `tsconfig.json` would not compile `index.ts` at app-level of apps generated by `lb4`, but it was compiled anyway because `ping.controller.test.ts` imported from the file, meaning it wasn't excluded because it was a dependency.
This PR fixes this.
=> fix(cli): update tsconfig.json to include index.ts

packages/authentication/test/acceptance/basic-auth.ts, packages/boot/test/acceptance/controller.booter.acceptance.ts, packages/cli/generators/app/templates/test/ping.controller.test.ts.ejs, packages/cli/test/app-run.test.js, packages/example-getting-started/test/acceptance/application.test.ts, packages/example-log-extension/test/acceptance/log.extension.acceptance.ts, packages/rest/src/rest-application.ts, packages/rest/src/rest-server.ts, packages/rest/test/acceptance/routing/routing.acceptance.ts, packages/rest/test/acceptance/sequence/sequence.acceptance.ts, packages/rest/test/integration/rest-server.integration.ts
Each RestServer provides an HTTP handler function that can be used with core HTTP server or any compatible framework like Express.
This pull request exposes the handler function on the RestApplication class to simplify the usage.
See also: 
- #846 [Docs] Update documentation and examples to use RestApplication
- #955  fix(example-getting-started): use RestApplication 
- #968 refactor: simplify app setup via RestApplication (part II)
- #994 feat(rest): app.route() and app.api() 
- (n/a) Affected artifact templates in `packages/cli` were updated
=> feat(rest): expose app.requestHandler function

docs/site/Application.md, docs/site/Best-practices-with-Loopback-4.md, docs/site/Booting-an-Application.md, docs/site/Command-line-interface.md, docs/site/Context.md, docs/site/Decorators.md, docs/site/Defining-the-API-using-code-first-approach.md, docs/site/Defining-the-API-using-design-first-approach.md, docs/site/Defining-your-testing-strategy.md, docs/site/Examples-and-tutorials.md, docs/site/Extending-LoopBack-4.md, docs/site/Extension-generator.md, docs/site/FAQ.md, docs/site/Implementing-features.md, docs/site/Preparing-the-API-for-consumption.md, docs/site/Routes.md, docs/site/Sequence.md, docs/site/Server.md, docs/site/Testing-your-application.md, docs/site/sidebars/lb4_sidebar.yml, docs/site/tables/lb4-artifact-commands.html, docs/site/tables/lb4-project-commands.html
There are a couple of stray pages that haven't been migrated and updated over to the monorepo. The PR fixes this
- brings over commits made from Feb 23rd to Mar 15th, 2018.
- https://github.com/strongloop/loopback.io/pull/634
- https://github.com/strongloop/loopback.io/pull/636
- https://github.com/strongloop/loopback.io/pull/631
- https://github.com/strongloop/loopback.io/pull/637
- https://github.com/strongloop/loopback.io/pull/621
- https://github.com/strongloop/loopback.io/pull/640
- https://github.com/strongloop/loopback.io/pull/642
- https://github.com/strongloop/loopback.io/pull/638
- https://github.com/strongloop/loopback.io/pull/624
- https://github.com/strongloop/loopback.io/pull/635
- https://github.com/strongloop/loopback.io/pull/644
- …
=> Docs/finish migration from loopback.io

packages/testlab/should-as-function.d.ts
Fixed up some type definitions so that they reflect the actual parameters of some functions from `should-js`.
Alternatively, I think there should be a way for the type definition here to be synchronized to the one straight from `should-js`.
Uber-alternatively, we should switch to using `chai` since `should-js` is not very active compared to `chai`.
=> fix(testlab): fix throw() and rejectedWith() types

docs/site/Model.md
Minor fixes in the Key concepts > Model page: http://loopback.io/doc/en/lb4/Model.html
connected to: #988
=> docs: Fix typos and cleanup Model page

README.md
It's surprising and embarrassing that nobody has noticed that our travis build status is always failing due to a fixed link to https://img.shields.io/travis/rust-lang/rust.svg.
=> chore: fix the travis build status badge url

packages/rest/README.md
=> docs(rest): update readme

package.json, packages/build/bin/run-clean.js, packages/build/package.json
During development, we often switch between branches that have different
packages for the monorepo. This script cleans up the `dist` folder of
non-package directories under 'packages' so that `npm test` won't run
left-over tests from non-packages.
=> chore: add a script to prune dist folder from non packages

packages/cli/generators/app/templates/index.js.ejs, packages/cli/generators/app/templates/src/index.ts.ejs, packages/example-getting-started/index.js, packages/example-getting-started/src/index.ts, packages/example-hello-world/index.js, packages/example-hello-world/src/index.ts, packages/example-rpc-server/index.js, packages/example-rpc-server/src/index.ts
This is a fix for issue #925 which moves the the start error handler to the top-most caller instead of being handled by the main function.
fix #925
=> refactor(CLI Templates): move start error catch to application.main

packages/repository/README.md
- Updated the code to use current practices
- Got rid of in-depth explanation of each concepts, but they were good content that might be ok to move out of the readme and into one of the pages in `loopback.io`. But then again, they may have been covered already. @raymondfeng any thoughts?
- connected to https://github.com/strongloop/loopback-next/issues/988
=> fix(repository): fix broken code in readme

packages/context/src/binding.ts, packages/context/src/context.ts, packages/context/src/value-promise.ts, packages/context/test/unit/value-promise.test.ts
This PR adds optional typing for `Binding` and `getDeepProperty`.
Related to https://github.com/strongloop/loopback-next/pull/1169
=> feat(context): add optional typing for Binding

README.md, packages/authentication/README.md, packages/boot/README.md, packages/build/README.md, packages/cli/README.md, packages/context/README.md, packages/core/README.md, packages/example-getting-started/README.md, packages/example-hello-world/README.md, packages/example-log-extension/README.md, packages/example-rpc-server/README.md, packages/metadata/README.md, packages/openapi-spec-builder/README.md, packages/openapi-v3-types/README.md, packages/openapi-v3/README.md, packages/repository-json-schema/README.md, packages/repository/README.md, packages/testlab/README.md
connected to #988 
- Noticed different links for Contribution guidelines in different packages, so this fixes that. 
- Changes main README to use references for images in table
- quick typo fix 
- Add Last 4 section to packages missing that information (examples)
=> docs: update contribution guidelines link and minor fixes

docs/site/Repositories.md
Please review from the 2nd commit
I wasn't able to verify the code snippets for creating your own connector since there's too many functions to implement. I also don't know too much about working with databases to verify the code that I may have had to write.
I personally think that we need to have a working product that uses its own connector, and if others agree I can create a new issue for it. I know the microservices repo has one but if we were to use that, we'd need to pull it out of that repo.
=> docs: update Repositories.md to use openapi-v3

packages/cli/lib/project-generator.js, packages/cli/lib/utils.js, packages/cli/test/project.js, packages/cli/test/test-utils.js
Currently `lb4 app fooBar` fails by throwing an error with a stack trace. The PR makes the error exit the generator gracefully.
=> fix(cli): exit gracefully if the project name fails validation

packages/context/src/inject.ts, packages/context/test/unit/inject.test.ts, packages/metadata/src/decorator-factory.ts, packages/metadata/test/unit/decorator-factory.test.ts, packages/openapi-v3/src/controller-spec.ts, packages/repository/src/legacy-juggler-bridge.ts, packages/repository/src/loopback-datasource-juggler.ts, packages/repository/test/unit/decorator/repository.ts
See https://github.com/strongloop/loopback-next/issues/1182. The root
cause is that DataSource instances are cloned incorrectly.
Fixes #1182
=> fix(metadata): refine clone of decoration spec

docs/site/Using-components.md
connected to #988 
Same as this PR https://github.com/strongloop/loopback.io/pull/639 but since we moved docs before it landed, re-creating this.
=> docs: update using components page

packages/example-getting-started/docs/datasource.md
Quoting from #1185: 
```
Follow the Getting Starting Tutorial
datasources.json:
{
"name": "ds", <-- should be "db"
"connector": "memory"
}
```
The code was fixed by #966, now we're fixing the docs.
Fixes https://github.com/strongloop/loopback-next/issues/1185
=> docs(example-getting-started): fix typo for ds

docs/site/Dependency-injection.md
Small improvements of [Dependency Injection](http://loopback.io/doc/en/lb4/Dependency-injection.html).
See https://github.com/strongloop/loopback-next/issues/988
=> docs: polish Dependency Injection article

bin/build
Removing `bin/build` which is obsolete and unused.
=> Remove unused script

docs/site/Decorators.md
connect to https://github.com/strongloop/loopback-next/issues/753
- ~[ ] New tests added or existing tests modified to cover all changes~
- ~[ ] Affected artifact templates in `packages/cli` were updated~
- ~[ ] Affected example projects in `packages/example-*` were updated~
=> docs: openapi v3 decorators

packages/openapi-spec-builder/README.md
Update README in https://github.com/strongloop/loopback-next/tree/master/packages/openapi-spec-builder
related to #988
=> docs(openapi-spec-builder): update README code snippet to v3

bin/run-lerna.js, package.json, packages/build/bin/compile-package.js
This PR adds `run-lerna` script to allow `LERNA_ROOT_PATH` to be passed into `lerna` commands.
The run-lerna script adds the following logic:
- Set LERNA_ROOT_PATH env var
Fixes #1010
=> feat: run `tsc` relative to the root directory of loopback-next monorepo 

lerna.json, package.json
This is a follow-up to https://github.com/strongloop/loopback-next/pull/1189
See https://github.com/lerna/lerna/pull/1352
=> chore: disable prefixed output for lerna run

docs/site/Application-generator.md, docs/site/Application.md, docs/site/Best-practices-with-Loopback-4.md, docs/site/Controller-generator.md, docs/site/Creating-components.md, docs/site/Defining-the-API-using-code-first-approach.md, docs/site/Defining-the-API-using-design-first-approach.md, docs/site/Defining-your-testing-strategy.md, docs/site/Examples-and-tutorials.md, docs/site/Implementing-features.md, docs/site/Model.md, docs/site/Preparing-the-API-for-consumption.md, docs/site/Repositories.md, docs/site/Reserved-binding-keys.md, docs/site/Testing-the-API.md, docs/site/Testing-your-application.md, docs/site/index.md, docs/site/sidebars/lb4_sidebar.yml, docs/site/todo-tutorial-controller.md, docs/site/todo-tutorial-datasource.md, docs/site/todo-tutorial-juggler.md, docs/site/todo-tutorial-model.md, docs/site/todo-tutorial-putting-it-together.md, docs/site/todo-tutorial-repository.md, docs/site/todo-tutorial-scaffolding.md, packages/cli/package.json, packages/example-todo/README.md
- Fixes loopback.io LB4 sidebar for Todo Tutorial.
- Fixes formatting which was broken for includes after running markdown linter.
- Fixes numbering issue on todo-tutorial issue.
=> docs: fix links and liquid formatting

packages/authentication/package.json, packages/authentication/test/unit/authenticate-action.test.ts, packages/authentication/test/unit/fixtures/mock-strategy.ts, packages/authentication/test/unit/strategy-adapter.test.ts
`@types/passport` changes Strategy from to be a `class` instead of an `interface` which is breaking our build. 
See: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24682
This PR refactors the MockStrategy so it extends the `Strategy` class instead of `implements` the interface.
=> refactor(authentication): extend strategy instead of implement

docs/site/DEVELOPING.md
Add the `file naming convention` section in `DEVELOPING.md`. 
related to: #612
=> docs: add file naming convention

packages/example-todo/test/acceptance/application.test.ts, packages/repository/src/repository-mixin.ts, packages/repository/test/unit/repository-mixin/repository-mixin.test.ts
- needs to be rebased once https://github.com/strongloop/loopback-next/pull/1169 lands, or vice versa
Fixes #745
=> feat(repository): add getRepository function to mixin

docs/site/Controller-generator.md, docs/site/Controllers.md, docs/site/Decorators.md, docs/site/Repositories.md, docs/site/todo-tutorial-controller.md, examples/todo/src/controllers/todo.controller.ts, packages/cli/generators/controller/templates/src/controllers/controller-rest-template.ts.ejs, packages/cli/test/controller.js, packages/repository/README.md, packages/repository/src/decorators/repository.ts, packages/repository/test/unit/decorator/repository-with-di.ts
This PR splits `@repository` decorator into two overloaded methods for clarity in their two separate use cases: repository injection and repository generation based on a model and a datasource.
I had a question come up while I was working on the PR. Is advocating repository injection through `@repository(MyRepository.name)` the approach we want to take? I'd think that this is something that would go against the principles of Inversion of Control, which is what our Context system is based on.
I thought the point of the context system was to allow different `components` of an app to be swapped out in a single file. For example, if a user has a test repository and a production repository that he needs to swap out for deployment, our Context system should theoretically provide a single place …
=> fix(repository): clarify argument type for `@repository` 

packages/core/src/keys.ts, packages/rest/src/http-handler.ts, packages/rest/src/index.ts, packages/rest/src/rest.application.ts, packages/rest/src/rest.server.ts, packages/rest/src/router/routing-table.ts, packages/rest/test/acceptance/routing/routing.acceptance.ts, packages/rest/test/acceptance/sequence/sequence.acceptance.ts, packages/rest/test/integration/http-handler.integration.ts, packages/rest/test/unit/rest.server/rest.server.open-api-spec.unit.ts, packages/rest/test/unit/router/controller-factory.test.ts, packages/rest/test/unit/router/controller-route.unit.ts, packages/rest/test/unit/router/routing-table.unit.ts
The PR ensures the existing controller binding is used to resolve/invoke the controller method. It allows `scope` and configuration of a controller is honored. Please note `instantiateClass` always creates a new instance.
If a route is set up without binding the controller to a context (app), we now create a binding in the request context.
=> fix(rest): use context.get() to resolve current controller

packages/boot/test/acceptance/controller.booter.acceptance.ts, packages/boot/test/integration/controller.booter.integration.ts, packages/boot/test/integration/repository.booter.integration.ts, packages/boot/test/unit/booters/booter-utils.unit.ts, packages/testlab/src/test-sandbox.ts, packages/testlab/test/fixtures/test.ts, packages/testlab/test/integration/test-sandbox.integration.ts
When a `.ts` compled `.js` file is copied and required, a warning / error is logged to console because the accompanying `.js.map` file cannot be resolved. This PR updates the sourceMappingURL in the copied file to point to the original `.js.map` file as an absolute path so it can be resolved (only if accompanying `.js.map` file exists).
Based on a review comment here: https://github.com/strongloop/loopback-next/pull/858#discussion_r164777386
=> feat(testlab): update sourceMappingURL when copying a JS file

packages/authentication/src/keys.ts, packages/context/src/inject.ts, packages/context/test/unit/binding-key.unit.ts, packages/metadata/README.md, packages/metadata/docs.json, packages/metadata/src/decorator-factory.ts, packages/metadata/src/index.ts, packages/metadata/src/inspector.ts, packages/metadata/src/types.ts, packages/metadata/test/unit/inspector.unit.ts, packages/metadata/test/unit/metadata-accessor.test.ts, packages/openapi-v3/src/controller-spec.ts, packages/openapi-v3/src/keys.ts, packages/repository-json-schema/src/build-schema.ts, packages/repository/src/decorators/metadata.ts, packages/repository/src/decorators/model.decorator.ts, packages/repository/test/unit/decorator/metadata.unit.ts
This PR introduces a strong-typed MetadataKey for metadata access via reflection. It's inspired by #1169.
=> Introduce strongly-typed metadata key

.gitignore, lerna.json, packages/cli/test/acceptance/app-run.acceptance.js, sandbox/.gitignore, sandbox/README.md
This PR formalizes the idea to allow packages to be tested against our source code from git. It adds a `sandbox` folder to contain modules/applications that need to be bootstrapped by lerna.
=> chore: add a sandbox location to enable testing w/ source code

README.md, packages/rest/README.md
When we are ready to release Developer Preview 2, we need to update the status on the readme files.
Change the release name for:
- `README.md`
- `packages/rest/README.md`
connected to: https://github.com/strongloop/loopback-next/issues/1059
Will merge when we are ready.
=> chore: update release name

docs/site/todo-tutorial-controller.md, examples/todo/src/controllers/todo.controller.ts, packages/authentication/src/providers/authentication.provider.ts, packages/cli/generators/controller/index.js, packages/repository/src/repositories/legacy-juggler-bridge.ts, packages/rest/src/parser.ts, packages/testlab/test/integration/test-sandbox.integration.ts
I recommend `throw` over `return Promise.reject()` because:
1. It is shorter, which makes it easier to read.
2. It retains some parity between synchronous and asynchronous code. (It will continue to work as expected if those lines were extracted into a synchronous function.)
There are [some occasions](https://gist.github.com/joeytwiddle/21331531f50885345e063d59ec7f11f2) when you cannot use `throw` in place of returning a rejection, but if you are in the body of an async function then it is always safe.
If you have considered this style but rejected it, I would be interested to learn your reasoning, if it happens to be available online somewhere. Cheers!
=> docs: Throw error instead of returning rejected promise

packages/build/package.json
Upgrade to typescript 2.8.x and prettier 1.12.x.
=> chore(build): upgrade dependencies

.travis.yml, bin/verify-docs.sh, package.json
Simpler approach to https://github.com/strongloop/loopback-next/pull/1251
A simple script clone's loopback.io, bootstrap's it and attempts to build the site. If it fails, CI will fail. 
--- 
Not adding it as a regular test since the script is not Windows compatible.
---
~The 2 items from #1251 with regards to changes to loopback.io repo would still need to happen.~ (DONE)
fixes #1232
=> test: build loopback.io to validate docs package

packages/openapi-spec-builder/src/openapi-spec-builder.ts, packages/openapi-v3-types/src/openapi-v3-spec-types.ts, packages/openapi-v3-types/src/type-guards.ts, packages/openapi-v3/src/json-to-schema.ts
Move the definition of ExtensionValue from openapi-v3-types (where it is no longer used) to openapi-spec-build.
Fix openapi type guards to use a more correct `object` type instead of `ExtensionValue`, since the guards are not dealing with any extensions.
Fixa json-to-schema converter to use `any` instead of `ExtensionValue` when converting a JSON Schema object to an indexable object.
This is a follow-up for #1265.
- (n/a) New tests added or existing tests modified to cover all changes
- (n/a) API Documentation in code was updated
- (n/a) Documentation in [/docs/site](../tree/master/docs/site) was updated
- (n/a) Affected artifact templates in `packages/cli` were updated
- (n/a) Affected example projects in `examples/*` were updated
=> refactor: clean usage of OAI's ExtensionValue

packages/authentication/test/acceptance/basic-auth.acceptance.ts, packages/boot/src/booters/booter-utils.ts, packages/build/package.json, packages/repository/test/unit/type/type.unit.ts
- Replace new Buffer() with Buffer.from()
- Work around https://github.com/nodejs/node/issues/20278
- Upgrade to source-map-support@0.5.5
=> chore: make the code compatible with node 10.0.0

docs/site/sidebars/lb4_sidebar.yml
I found it weird that our sidebar is listing "Testing your application" at top level, while most of other testing-related content is nested under "Best practices".
This pull request moves "Testing your application" to "Best practices" section and also adds a link to "Testing your extensions" to best practices.
Please consider this change as a quick improvement of the current status. In the future, we will probably want to revamp the sidebar and these best practices guides. Such bigger change is out of scope of this pull request though!
=> doc: list Testing guides under Best Practices

packages/repository-json-schema/src/build-schema.ts
Minor: Improve the helpfulness of the error message, so the developer know which type is causing the problem.
When I use a type in my model which does not exist (e.g. 'date') I get an error but I don't get the line number or the model name to help me find and fix the problem.
```
Cannot start the application. Error: Unsupported type
at stringTypeToWrapper (.../node_modules/@loopback/repository-json-schema/dist/src/build-schema.js:50:19)
at metaToJsonProperty (.../node_modules/@loopback/repository-json-schema/dist/src/build-schema.js:76:16)
...
```
This PR will simply include the actual type in the error message, to give the developer a nudge in the right direction.
```
Cannot start the application. Error: Unsupported type: date
at stringTypeToWrapper …
```
=> feat(repository-json-schema): include type in err

appveyor.yml
Speed up our AppVeyor CI builds by disabling features that are not
needed:
- Linting is performed by Travis CI, no need to lint on Windows too
- Code coverage is collected by Travis jobs, AppVeyor was never
exporting code coverage to Coveralls.
This change speeds up AppVeyor runs by about 1 minute from ~4m27s to ~3m25s.
=> ci: disable code coverage and linting on Windows

examples/hello-world/package.json, examples/log-extension/package.json, examples/rpc-server/package.json, examples/todo/package.json
This is the first step of reworking `lb4 example` to download example packages from `npm` instead of `GitHub` - see #1120
=> chore: enable publishing of examples to npm

packages/openapi-v3/src/json-to-schema.ts, packages/openapi-v3/test/unit/json-to-schema.unit.ts, packages/repository-json-schema/package.json, packages/repository-json-schema/src/build-schema.ts, packages/repository-json-schema/src/index.ts, packages/repository-json-schema/test/integration/build-schema.integration.ts, packages/repository-json-schema/test/unit/build-schema.unit.ts
- ditches the heavy `typescript-json-schema` module in favor of light-weight and more accurate `JSONSchema6`
- fixes #1132 
- related to #1256
=> chore(repository-json-schema): replace JsonDefinition with JSONSchema6

packages/openapi-v3/src/json-to-schema.ts, packages/openapi-v3/test/unit/json-to-schema.unit.ts, packages/repository-json-schema/src/index.ts, packages/repository-json-schema/test/integration/build-schema.integration.ts
Our current convention is to treat abbreviations longer than 2
characters as regular words and capitalize only the first character.
We already use "Json" form across the codebase instead of "JSON".
This commit applies the same convention to the JSON Schema type
introduced by the recent commit e9e6b12c7f (see #1286).
=> refactor(repository-json-schema): rename JSONSchema to JsonSchema

packages/context/src/binding.ts, packages/context/src/context.ts, packages/context/src/index.ts, packages/context/test/acceptance/tagged-bindings.acceptance.ts, packages/context/test/acceptance/tagged-bindings.feature.md, packages/context/test/unit/binding.unit.ts, packages/context/test/unit/context.unit.ts, packages/core/test/unit/application.unit.ts, packages/rest/test/unit/rest.server/rest.server.open-api-spec.unit.ts
This PR enhances our binding tags to allow optional values. For example, we can associate a `controller` binding with tags such as:
- 'controller' (tag name only)
- {name: 'MyController'} (tag with name and value)
- {extensionPoint: 'controllers'}
=> [RFC] feat(context): allow tags to have an optional value

docs/site/DEVELOPING.md, packages/authentication/src/keys.ts, packages/boot/src/keys.ts, packages/openapi-v3/src/keys.ts, packages/repository-json-schema/src/build-schema.ts, packages/repository-json-schema/src/index.ts, packages/repository-json-schema/src/keys.ts, packages/rest/src/keys.ts
- No changes made to `Reserved-binding-keys.md` since apidocs do not render the docs on the keys at all.
- related to #956
=> chore: add apidocs for binding keys

packages/context/src/binding.ts, packages/context/src/index.ts, packages/context/src/resolver.ts, packages/context/src/value-promise.ts, packages/context/test/unit/value-promise.unit.ts
This PR is spin-off from https://github.com/strongloop/loopback-next/pull/983. It extracts a few utilities to help handle ValueOrPromise.
=> feat(context): add more utils to resolve valueOrPromises

docs/site/Repositories.md, packages/repository/src/repositories/legacy-juggler-bridge.ts, packages/repository/test/unit/repositories/legacy-juggler-bridge.unit.ts
Fix DefaultCrudRepository to re-use legacy juggler Models across all instances of the same Repository class.
Before this change, each call of DefaultCrudRepository constructor was redefining the backing persisted model.
This commit adds a caching mechanism to DefaultCrudRepository: when setting up a backing model, we check datasource's modelBuilder registry to find if the backing model was not already created by an older instance of the repository.
See #1032 and #995.
=> fix: multiple instances of the same repository class

docs/CONTRIBUTING.md
I noticed that sometimes newcomers don't realize that our VS Code setup requires few additional plugins. In this pull request, I am adding an explicit mention of VS Code right to our main CONTRIBUTING guide, to give our VSCODE guide more visibility.
=> docs: mention VSCode in the CONTRIBUTING guide

docs/site/Context.md, docs/site/Creating-components.md, docs/site/Implementing-features.md, packages/authentication/README.md, packages/cli/generators/extension/templates/src/providers/README.md
Update the documentation to reflect the recently landed changes in SequenceHandler API.
This is a part of #1292 and a follow-up for #1316
=> docs: replace (req, res) with RequestContext

packages/cli/generators/app/index.js, packages/cli/generators/extension/index.js, packages/cli/lib/project-generator.js, packages/cli/lib/utils.js, packages/cli/package.json
We need to do in-place rename so that the file can be managed by mem-fs
for. The gulp-rename@1.2.3 breaks us as the clone of file object causes
mem-fs-editor to rewrite a file that's already committed.
=> fix: replace gulp-rename with our own implementation

packages/openapi-v3/src/decorators/parameter.decorator.ts
Added a workaround for the `@param` apidocs.
Connects to #584
=> chore: add typedocs for `@param` decorator

packages/rest/src/rest.server.ts, packages/rest/test/integration/rest.server.integration.ts
Clean up the RestServer implementation by moving CORS out of `_handleHttpRequest()` and mounting it as a regular Express middleware instead.
This is a follow-up for #1326 as part of #1038.
=> refactor(rest): mount CORS as a regular middleware

docs/site/Controller-generator.md, docs/site/Defining-the-API-using-code-first-approach.md, docs/site/todo-tutorial-controller.md, docs/site/todo-tutorial-putting-it-together.md, examples/todo/src/controllers/todo.controller.ts, examples/todo/test/acceptance/application.acceptance.ts, packages/cli/generators/controller/index.js, packages/cli/generators/controller/templates/src/controllers/controller-rest-template.ts.ejs, packages/cli/lib/utils.js, packages/cli/package.json, packages/cli/test/integration/generators/controller.integration.js, packages/cli/test/unit/utils.unit.js
- closes #887
UX:
```shell
Select the HTTP path naming convention of this CRUD repository
- default ('/todo' and '/todos')
- custom
```
If `custom` is selected:
```shell
What is the singular base HTTP path of this CRUD repository? (`/todo`) 
```
```shell
What is the singular base HTTP path of this CRUD repository? /customer-order
What is the plural base HTTP path of this CRUD repository? (/customer-orders) 
```
=> feat(cli): add prompt for plural model name 

packages/repository-json-schema/package.json, packages/repository-json-schema/test/integration/build-schema.integration.ts, packages/repository-json-schema/test/unit/build-schema.unit.ts, packages/repository-json-schema/test/unit/json-schema.unit.ts
=> chore(repository-json-schema): add JSON schema type tests

examples/hello-world/package.json, examples/log-extension/package.json, examples/rpc-server/package.json, examples/todo/package.json
> running `lb4 example __whatever__` does not copy over tests
Fix ^
cc @shimks
=> fix: clone the test folder for examples

docs/site/Deploy-for-GDPR-readiness.md, docs/site/sidebars/lb4_sidebar.yml
Add `Deploy for GDPR readiness` information.
The info is similar to LB2 and LB3 ones, except updated the Data Cycle section to fit for LB4.
=> docs: add Deploy for GDPR readiness doc

.prettierignore
As I was working and ran `npm run prettier:fix`, it started formatting `sandbox/loopback.io`. I don't think we should be formatting stuff in sandbox folder as it's not checked into git.
=> chore: ignore all files in sandbox when linting

packages/repository/package.json, packages/repository/src/query.ts, packages/repository/src/repositories/constraint-utils.ts, packages/repository/src/repositories/index.ts, packages/repository/src/repositories/relation.factory.ts, packages/repository/src/repositories/relation.repository.ts, packages/repository/test/acceptance/has-many.relation.acceptance.ts, packages/repository/test/unit/query/query-builder.unit.ts
This PR aims to incrementally implement the `hasMany` model relations in LoopBack 4 from discussions and code in #1194. It has the following components:
- `constrainedRepositoryFactory` to create relational repository instances based on specified constraint and relation metadata
- `HasManyEntityCrudRepository` interface which specifies the shape of the public APIs exposed by the `HasMany` relation
- `DefaultHasManyEntityCrudRepository` class which implements those APIs by calling utility functions on a target repository instance to constrain its CRUD methods.
- `constrain*` utility functions which apply constraints on a data object, filter, or where object.
**TODOs**: 
Connect to #995 and #1372.
=> feat(repository): hasMany model relation

docs/site/Deploy-for-GDPR-readiness.md, docs/site/sidebars/lb4_sidebar.yml
Similar to https://github.com/strongloop/loopback.io/pull/699 but with LB4.
- Change the page title to LoopBack considerations for GDPR readiness
- remove the redundant title for the page
=> docs: update GDPR consideration page title

docs/site/todo-tutorial-controller.md, packages/cli/generators/app/templates/src/controllers/index.ts.ejs, packages/cli/generators/controller/index.js, packages/cli/lib/artifact-generator.js, packages/cli/lib/update-index.js, packages/cli/test/unit/update-index.unit.js
This is part of the work I did for the **Boot Spike**. `lb4 datasource` makes use of the index generation so decided to just deliver this as it's own feature. 
fix #1127
**UPDATE: MAY 31**
- The PR no longer re-generated index.ts -- If already present, it adds a line at the end. If it doesn't exist in the folder it creates it and adds the file to to it.
- Auto-generation can be skipped as documented in code
=> feat(cli): auto-generate index.ts for exports

.travis.yml
Based on https://github.com/strongloop/loopback-next/pull/1374#issuecomment-393059835
> @virkt25 IIRC, we will be reporting coverage data from all matrix entries (platforms) now. Would it make sense to limit coverage report to a single platform, let's say Node.js 10.x on Linux?
=> ci: report coverage only on Node 10

packages/rest/test/unit/parser.unit.ts, packages/testlab/README.md
Improve testlab's README to show how to use `stubServerRequest`, `stubHandlerContext` and `stubExpressContext` for mocking/stubbing HTTP request and response objects.
Close #760 
=> docs(testlab): describe Request/Response mocks

packages/repository/test/acceptance/has-many.relation.acceptance.ts
kept showing up as pending in mocha
**UPDATE**
- Changed the PR to mark the test with a `skip` - this way someone looking at the pending test has an easy way of identifying where the test is ... which was my biggest issue since I thought a test is being mysteriously skipped as I couldn't find anything with a `.skip`. 
Signed-off-by: Taranveer Virk <taranveer@virk.cc>
=> test(repository): mark pending test with a skip

package.json
fixes #585
Signed-off-by: Taranveer Virk <taranveer@virk.cc>
---
To test -- try `git commit -m "foo: fail"` OR `git commit -m "chore(not-a-package): should give error"`
Override for hook is to use `--no-verify` option **BUT** I do not recommend that since CI will fail on an invalid commit message.
=> feat: add local commit message linting

packages/http-server/.npmrc, packages/http-server/README.md, packages/http-server/index.d.ts, packages/http-server/index.js, packages/http-server/index.ts, packages/http-server/package.json, packages/http-server/src/http-server.ts, packages/http-server/src/index.ts, packages/http-server/test/integration/http-server.integration.ts, packages/http-server/tsconfig.build.json, packages/rest/src/keys.ts, packages/rest/src/rest.server.ts, packages/rest/test/integration/rest.server.integration.ts
Implements #1331.
Main changes:
1. Added a new package `@loopback/http-server`
2. Made changes to `@loopback/rest` to use `@loopback/http-server`.
=> Implement HTTP endpoint factory

packages/build/package.json
TypeScript 2.9 transpiles code with relative import to reference
external types and the path can be invalid if a depenednecy is
symbol-linked.
See https://github.com/strongloop/loopback-next/issues/1405
=> chore(build): pin typescript version to 2.8.x

examples/hello-world/package.json, examples/hello-world/src/application.ts, examples/hello-world/test/acceptance/application.acceptance.ts, examples/hello-world/tsconfig.build.json
Before this change, `npm test` under `examples/hello-world` fails as there is no test.
=> chore: add a test case to examples/hello-world

examples/todo/src/controllers/todo.controller.ts, packages/rest/src/coercion/coerce-parameter.ts, packages/rest/src/coercion/rest-http-error.ts, packages/rest/src/coercion/validator.ts, packages/rest/src/index.ts, packages/rest/src/parser.ts, packages/rest/test/acceptance/coercion/coercion.acceptance.ts, packages/rest/test/unit/coercion/invalid-spec.unit.test.ts, packages/rest/test/unit/coercion/paramStringToBoolean.unit.ts, packages/rest/test/unit/coercion/paramStringToBuffer.unit.ts, packages/rest/test/unit/coercion/paramStringToDate.unit.ts, packages/rest/test/unit/coercion/paramStringToInteger.unit.ts, packages/rest/test/unit/coercion/paramStringToNumber.unit.ts, packages/rest/test/unit/coercion/utils.ts
connect to #750 
This is the first PR for story #750 that
- Implements a coercion function called in `parseOperationArgs` that converts the http raw data into a JS type data according to its OpenAPI schema
- Implements helper functions to easily create tests for more edge cases
- Adds unit test + acceptance test
- More PRs for edge cases + validation rules are coming next.
=> feat: add type coercion

.travis.yml, packages/cli/test/acceptance/app-run.acceptance.js, packages/cli/test/integration/lib/project-generator.js
This partially reverts commit a36e2574e0296aedc531bd283e0702e149c40002,
as it is no longer needed on Travis CI - the new Node.js version 10.2.0 has
fixed the problem we were experiencing on Node.js 10.1.0.
=> revert on Travis: pin Node.js 10.x version to 10.0.0 

packages/repository/src/decorators/repository.decorator.ts, packages/repository/src/repositories/repository.ts, packages/repository/test/unit/mixins/repository.mixin.unit.ts
=> chore(repository): separate execute function from repository interface

docs/site/Calling-other-APIs-and-Web-Services.md, examples/todo/package.json, examples/todo/src/application.ts, examples/todo/src/controllers/todo.controller.ts, examples/todo/src/datasources/geocoder.datasource.json, examples/todo/src/datasources/geocoder.datasource.ts, examples/todo/src/models/todo.model.ts, examples/todo/src/services/geocoder.service.ts, examples/todo/src/services/index.ts, examples/todo/test/acceptance/application.acceptance.ts, examples/todo/test/helpers.ts, examples/todo/test/integration/services/geocoder.service.integration.ts, examples/todo/test/unit/controllers/todo.controller.unit.ts, packages/core/src/index.ts, packages/http-caching-proxy/package.json, packages/service-proxy/package.json
This pull request improves our Todo example to demonstrate how to use Services in practice. To do so, we leverage [US Census Geocoder](https://geocoding.geo.census.gov/geocoder/) ([API docs](https://geocoding.geo.census.gov/geocoder/Geocoding_Services_API.html))  to add location-based reminders to our Todo items. 
Based on the outcome of this work, I'll update our Services docs with best practices on testing, see
https://github.com/strongloop/loopback-next/issues/1311, and also update [Todo tutorial](http://loopback.io/doc/en/lb4/todo-tutorial.html) to match the new Todo example implementation. These documentation updates are out of scope of this pull request though!
- Affected artifact templates in `packages/cli` were …
=> Add GeoCoder Service to examples/todo

packages/repository/package.json, packages/repository/src/query.ts, packages/repository/src/repositories/constraint-utils.ts, packages/repository/src/repositories/relation.factory.ts, packages/repository/src/repositories/relation.repository.ts, packages/repository/test/acceptance/has-many.relation.acceptance.ts, packages/repository/test/integration/repositories/relation.factory.integration.ts, packages/repository/test/unit/query/query-builder.unit.ts, packages/repository/test/unit/repositories/constraint-utils.unit.ts, packages/repository/test/unit/repositories/relation.repository.unit.ts
Implements #1379. Add unit tests for the following files:
=> tests(repository): add missing unit tests

packages/cli/bin/download-connector-list.js, packages/cli/package.json
Signed-off-by: Taranveer Virk <taranveer@virk.cc>
Addressed feedback https://github.com/strongloop/loopback-next/pull/1385#pullrequestreview-128677113 regarding making the download function more robust using request module.
=> fix(cli): make download-connector-list more robust

docs/site/todo-tutorial-controller.md, packages/rest/package.json, packages/rest/src/coercion/coerce-parameter.ts, packages/rest/src/coercion/rest-http-error.ts, packages/rest/src/coercion/utils.ts, packages/rest/test/unit/coercion/paramStringToBoolean.unit.ts, packages/rest/test/unit/coercion/paramStringToBuffer.unit.ts, packages/rest/test/unit/coercion/paramStringToDate.unit.ts, packages/rest/test/unit/coercion/paramStringToInteger.unit.ts, packages/rest/test/unit/coercion/paramStringToNumber.unit.ts, packages/rest/test/unit/coercion/parseStringToDatetime.unit.ts
connect to #750 
coercion for **integer** and **boolean** is good for review
coercion for date-time is missing some invalid value check, but earlier feedback are welcomed.
(@bajtos you left some feedback for date and date-time, I applied under the original PR, see [comment](https://github.com/strongloop/loopback-next/pull/1370#discussion_r192674150), PTAL, thanks!)
=> feat: coercion for other types

docs/site/Calling-other-APIs-and-Web-Services.md, docs/site/Testing-your-application.md
Update[Testing-your-application](http://loopback.io/doc/en/lb4/Testing-your-application.html) and [Calling-other-APIs-and-web-services](http://loopback.io/doc/en/lb4/Calling-other-APIs-and-web-services.html) to describe how to test service proxies.
This task is a part of #1331, see also #1441 which is updating Todo tutorial with similar changes.
=> docs: describe how to tests services

docs/site/sidebars/lb4_sidebar.yml, docs/site/todo-tutorial-geocoding-service.md, docs/site/todo-tutorial-putting-it-together.md, examples/todo/README.md, examples/todo/src/application.ts, examples/todo/src/datasources/geocoder.datasource.ts, examples/todo/src/datasources/index.ts
Update Todo tutorial - describe how to add a Geocoder service.
See #1311 
-  New tests added or existing tests modified to cover all changes
=> docs: add geo-coding service to Todo tutorial

examples/todo/test/acceptance/application.acceptance.ts
`npm test` consistently fails for me due to the following timeout:
```
1) Application
creates a todo:
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/rfeng/Projects/loopback4/loopback-next/examples/todo/dist8/test/acceptance/application.acceptance.js)
```
Instrumentation shows the geocode lookup takes more than 3.5 seconds.
=> chore: increase timeout to allow slow geocode response

packages/cli/bin/cli.js, packages/cli/generators/openapi/README.md, packages/cli/generators/openapi/index.js, packages/cli/generators/openapi/schema-helper.js, packages/cli/generators/openapi/spec-helper.js, packages/cli/generators/openapi/spec-loader.js, packages/cli/generators/openapi/templates/src/controllers/controller-template.ts.ejs, packages/cli/generators/openapi/templates/src/models/model-template.ts.ejs, packages/cli/generators/openapi/templates/src/models/type-template.ts.ejs, packages/cli/generators/openapi/utils.js, packages/cli/generators/project/templates/package.json.ejs, packages/cli/generators/project/templates/package.plain.json.ejs, packages/cli/package.json, packages/cli/smoke-test/openapi/README.md, packages/cli/smoke-test/openapi/code-gen-utils.js, packages/cli/smoke-test/openapi/real-world-apis.smoke.js, packages/cli/test/fixtures/openapi/2.0/petstore-expanded-swagger.json, packages/cli/test/fixtures/openapi/3.0/customer.yaml, packages/cli/test/fixtures/openapi/3.0/petstore-expanded.yaml, packages/cli/test/fixtures/openapi/3.0/uspto.yaml, packages/cli/test/integration/cli/cli.integration.js, packages/cli/test/integration/generators/openapi-petstore.integration.js, packages/cli/test/integration/generators/openapi-uspto.integration.js, packages/cli/test/integration/generators/swagger-petstore.integration.js, packages/cli/test/unit/openapi/controller-spec.unit.js, packages/cli/test/unit/openapi/schema-helper.unit.js, packages/cli/test/unit/openapi/schema-model.unit.js
The PR adds `lb4 openapi` command to generate controllers from openapi specs (Swagger 2.0 and OpenAPI 3.0). 
- Supports swagger 2.0 and openapi 3.0
- Maps tagged operations to controllers
- Maps schemas to TypeScript classes/types
- Supports circular references
- Supports `enum`
- Supports `default`
- Supports `required`
Smoke test against https://api.apis.guru/v2/list.json.
=> feat(cli): add code gen from openapi spec

packages/http-server/src/http-server.ts, packages/http-server/test/integration/http-server.integration.ts
Reset `addressInfo` when the server is stopped. Currently it returns the old address.
=> fix(http-server): reset addressInfo when server is stopped

packages/cli/generators/openapi/spec-helper.js, packages/cli/generators/openapi/utils.js, packages/cli/test/fixtures/openapi/3.0/customer.yaml, packages/cli/test/unit/openapi/controller-spec.unit.js
OpenAPI spec allows `parameters` at path level which apply to all operations of the given path. This PR adds the support.
=> Allow openapi path level params

.travis.yml, packages/http-server/src/http-server.ts, packages/http-server/test/integration/http-server.integration.ts
Format IPv6 local address correctly in the `url` property.
Fixes https://github.com/strongloop/loopback-next/issues/1453.
=> fix(http-server): correctly format IPv6 host in url

examples/rpc-server/src/rpc.server.ts, packages/core/src/server.ts, packages/rest/src/rest.server.ts
In a follow-up for #1479, I'd like to propose a small clean-up.
- Annotate `server.listening` property as readonly
- Rework `restServer.listening` as a getter property delegating the actual work to underlying `httpServer.listening`
=> refactor: clean up server.listening() implementation

packages/repository/package.json, packages/repository/src/decorators/model.decorator.ts, packages/repository/src/decorators/relation.decorator.ts, packages/repository/src/model.ts, packages/repository/src/repositories/legacy-juggler-bridge.ts, packages/repository/src/repositories/relation.factory.ts, packages/repository/src/repositories/relation.repository.ts, packages/repository/test/acceptance/has-many-without-di.relation.acceptance.ts, packages/repository/test/acceptance/has-many.relation.acceptance.ts, packages/repository/test/integration/repositories/relation.factory.integration.ts, packages/repository/test/unit/decorator/model-and-relation.decorator.unit.ts, packages/repository/test/unit/decorator/relation.decorator.unit.ts, packages/repository/test/unit/repositories/relation.repository.unit.ts
- Implement `hasMany` decorator which takes the target model class and infers the relation metadata and return type as an array of the target model instances
- store relation metadata on model definition
- modify the function returned by `hasManyRepositoryFactory` function to only take in value of the PK/FK constraint instead of a key value pair for the PK (`{id: 5}` -> `5`}
- create a protected function in DefaultEntityCrudRepository which calls `hasManyRepositoryFactory` using the metadata stored by `hasMany` decorator on the source model definition and returns a constrained version of the target repository
Connect to #1372.
=> feat(repository): hasmany relation decorator inference

docs/site/Model.md, packages/repository/src/model.ts, packages/repository/src/repositories/constraint-utils.ts, packages/repository/src/repositories/legacy-juggler-bridge.ts, packages/repository/src/repositories/relation.factory.ts, packages/repository/src/repositories/repository.ts, packages/repository/test/acceptance/repository.acceptance.ts, packages/repository/test/integration/repositories/relation.factory.integration.ts, packages/repository/test/unit/model/model.unit.ts, packages/repository/test/unit/repositories/constraint-utils.unit.ts, packages/repository/test/unit/repositories/crud.repository.unit.ts, packages/repository/test/unit/repositories/legacy-juggler-bridge.unit.ts, packages/repository/test/unit/repositories/relation.repository.unit.ts
Modify the code building legacy PersistedModel definition to enable strict mode by default. This means only properties described in model definitions are allowed, requests adding extra properties are rejected with an error.
Fix `Model.toJSON()` to correctly handle strict/non-strict mode:
- in strict mode, only defined properties are returned
- in non-strict mode, all instance properties are returned
My reasoning for this change: in LB4, we are using TypeScript classes and decorators to define models. By default, TS classes forbid additional properties not specified in the type definition. IMO, our persistence implementation should mirror that behavior.
One can disable the strict mode via model setting at juggler level and an indexer property at TypeScript level. Do we want to describe …
=> fix(repository): make models strict by default

packages/repository/src/repositories/relation.factory.ts, packages/repository/src/repositories/relation.repository.ts
Rename generic arguments of various HasMany-related templates to use more descriptive names making it clear whether the type argument is related to source or target model (entity).
=> refactor(repository): make generic arguments more descriptive

docs/site/Controller-generator.md, packages/cli/generators/controller/index.js, packages/cli/lib/utils.js, packages/cli/test/unit/utils.unit.js
Divided into two commits:
- the first includes the link to the documentation on CLI to the error thrown when no models/repositories are detected AND switches promises to use es7's async/await
- the second is the actual docs
Closes #1085
=> docs(cli): add docs on how the CLI detects artifacts

docs/site/includes/CLI-std-options.md, packages/cli/generators/controller/index.js, packages/cli/generators/datasource/index.js, packages/cli/lib/artifact-generator.js, packages/cli/lib/base-generator.js, packages/cli/lib/project-generator.js, packages/cli/lib/utils.js, packages/cli/package.json, packages/cli/test/integration/lib/artifact-generator.js, packages/cli/test/integration/lib/base-config.json, packages/cli/test/integration/lib/base-generator.js, packages/cli/test/integration/lib/project-generator.js, packages/repository/package.json
The PR adds the following features:
- Allow options to be passed in via `--config` from a json file, stdin, or stringified value
- Allow `--yes` option so that optional questions will be skipped with default values
For example,
```sh
lb4 app my-app --yes
lb4 app --config config.json
lb4 app --config {"name":"my-app"}
cat config.json | lb4 app --config stdin
lb4 app --config stdin < config.json
lb4 app --config stdin << EOF
> {"name":"my-app"}
> EOF
```
=> Enable json config options and non-interactive mode

packages/cli/lib/utils.js, packages/cli/test/unit/utils.unit.js
Before, if you had `foo-bar.model.ts`, the CLI would show `Foo-Bar` as an option to choose for the Default CRUD controller generator. This fixes this
=> fix(cli): tweak getArtifactList to return pascalCased strings

packages/rest/src/rest.server.ts, packages/rest/test/integration/rest.server.integration.ts
Add `url` property to Rest server.
=> feat(rest): add url property

packages/repository/src/repositories/legacy-juggler-bridge.ts
Fix the type information and implementation of DefaultCrudRepository's method _createHasManyRepositoryFactoryFor to correctly distinguish between source and target model/ID types.
I discovered this problem why reviewing the blog post introducing HasMany relation.
=> fix(repository): fix return type of DefaultCrudRepository#_createHasManyRepositoryFactoryFor

docs/site/includes/CLI-std-options.md, packages/cli/generators/app/index.js, packages/cli/generators/datasource/index.js, packages/cli/lib/artifact-generator.js, packages/cli/lib/base-generator.js, packages/cli/lib/project-generator.js, packages/cli/test/acceptance/app-run.acceptance.js, packages/cli/test/integration/generators/app.integration.js, packages/cli/test/integration/lib/artifact-generator.js
The PR adds `--format` option to run `npm lint:fix` to format generated code.
=> Cli run lint fix

.vscode/launch.json
The generated dist folder is `dist<node_version>`. Fix the vscode config file to reflect it.
=> fix: path to test folder

.travis.yml, packages/http-server/test/integration/http-server.integration.ts, packages/rest/test/integration/rest.server.integration.ts
Builds on Travis (Linux) are failing as we use `sudo` in the `before_script` BUT we had `sudo: false` in `.travis.yml`. 
Not sure how it worked before but it looks like something changes with Travis causing the builds to now fail.
Since only one test requires IPv6 - this PR removes the `before_script` and skips the one test on Travis (and other tests failing are updated to explicitly use IPv4 address). 
Example of a failing build: https://travis-ci.org/strongloop/loopback-next/jobs/403098729
=> ci: skip IPv6 tests on Travis and remove sudo script

examples/todo/src/models/todo.model.ts, packages/cli/bin/cli.js, packages/cli/generators/controller/index.js, packages/cli/generators/model/index.js, packages/cli/generators/model/templates/model.ts.ejs, packages/cli/lib/artifact-generator.js, packages/cli/lib/utils.js, packages/cli/test/integration/cli/cli.integration.js, packages/cli/test/integration/generators/model.integration.js, packages/cli/test/integration/lib/artifact-generator.js
implements #1221 
- Associated documentation changes will be in a follow up PR once this lands.
Commit Summary:
- First commit fixes CLI so the base ArtifactGenerator supports updating multiple `index.ts` files
- Second commit implemented `lb4 model` command
- Third commit updates `example-todo` to match output from `lb4 model` command
=> feat(cli): `lb4 model` to scaffold model files

examples/todo/README.md
images in /pages folder aren't generated under `/doc` URL.
=> fix(example-todo): correct todo-overview image link

packages/cli/generators/controller/templates/src/controllers/controller-rest-template.ts.ejs
…st controller template parsing
now it works on models that specify string as their id data type such as mongodb
- [x ] `npm test` passes on your machine
=> fix(cli): use <idtype> on param.path

docs/site/Controller-generator.md, packages/cli/generators/controller/templates/src/controllers/controller-rest-template.ts.ejs, packages/cli/test/integration/generators/controller.integration.js
Current way the call is made with updateAll in the CRUD CLI template:
`return await this.<%= repositoryNameCamel %>.updateAll(where, obj);`
Signature of `updateAll`:
```ts
updateAll(
data: Partial<T>,
where?: Where,
options?: Options,
): Promise<number>
```
The where object and the body need to be switched around
fixes #1521
=> fix(cli): reorder where and body in CLI template for updateAll

packages/rest/src/rest-http-error.ts, packages/rest/src/validation/request-body.validator.ts, packages/rest/test/unit/request-body.validator.test.ts
connect to https://github.com/strongloop/loopback-next/pull/1489
Original [comment](https://github.com/strongloop/loopback-next/pull/1489#issuecomment-403525040) from @bajtos 
LB3 and AJV error details are in different flavours:
- LB3: organized by detail attribute like `codes`, `messages`, and details are stored per field. e.g.:
```js
// error.details
{
codes: {
field1: ['errCode1', 'errCode2'],
field2: ['errCode1', 'errCode3'],
},
messages: {
field1: ['errMsg1', 'errMsg2'],
field2: ['errMsg3', 'errMsg4'],
}
}
```
- AJV: organized per error, each error entry includes detail attributes like field('dataPath'), code('keyword'), message, etc...e.g.:
```js
// the corresponding ajv.errors of example above
[
{dataPath: 'field1', keyword: 'code1', message: 'msg1', params: {...additionalInfo1}} …
```
=> feat: localize error in details

.nycrc
Right now, we are including all test files (e.g. `packages/core/test/acceptance/application.acceptance.ts`) in the code coverage data. Because most (if not all) test files have 100% coverage by their nature, by including them in code coverage data we are artificially inflating the reported percentage number.
I am proposing to configure `nyc` to exclude all test files.
A downside I am aware of: when test file coverage is measured, we can detect changes that are skipping tests (e.g. via `it.skip` - but this can be caught by a linter too) and find test code that's no longer executed (e.g. test helpers).
=> build: remove test files from code coverage data

docs/site/Parsing-requests.md, docs/site/Sequence.md, docs/site/sidebars/lb4_sidebar.yml
Connect to https://github.com/strongloop/loopback-next/pull/1489
The story only contains validation doc, while I realized the doc for action `parsing request` is missing, so I added it and also the coercion doc.
=> docs: add parsing request

packages/repository/src/repositories/legacy-juggler-bridge.ts, packages/repository/test/unit/repositories/legacy-juggler-bridge.unit.ts
When using `updateAll` if no `where` and `options` objects are given as arguments, we get:
```shell
AssertionError [ERR_ASSERTION]: The where argument must be an object
```
Refer to AssertionError [ERR_ASSERTION]: The where argument must be an object
@raymondfeng Is there a reason why `where = where || {}` does not exist in the juggler's updateAll implementation?
=> fix(repository): default where object to an empty object

packages/cli/generators/controller/templates/src/controllers/controller-rest-template.ts.ejs, packages/cli/test/integration/generators/controller.integration.js
Fix commas on lines 38 and 39 of `packages/cli/generators/controller/templates/src/controllers/controller-rest-template.ts.ejs` to produce valid code that passes lint
Fixes #1551
=> fix: fix cli rest controller generator template

docs/site/sidebars/lb4_sidebar.yml
The sidebar formatting was off for `Parsing-requests.html`
=> fix(docs): fix Parsing-requests.html sidebar entry

packages/http-server/test/integration/http-server.integration.ts, packages/rest/test/integration/rest.server.integration.ts, packages/testlab/README.md, packages/testlab/src/http-server-config.ts, packages/testlab/src/index.ts, packages/testlab/src/request.ts, packages/testlab/src/skip-travis.ts
Move https/travis helper functions to testlab
=> refactor: move https/travis helper functions to testlab

examples/todo-list/README.md
In ToDo List tutorial set up https://loopback.io/doc/en/lb4/todo-list-tutorial.html#setup, the command to download the tutorial should be:
```
lb4 example todo-list
```
instead of 
```
lb4 example todo
```
=> docs: fix todo-list tutorial command

examples/rpc-server/src/application.ts, examples/rpc-server/src/index.ts, examples/todo-list/src/index.ts, examples/todo/src/index.ts, packages/cli/generators/app/templates/src/application.ts.ejs, packages/cli/generators/app/templates/src/index.ts.ejs, packages/cli/test/integration/generators/app.integration.js, packages/http-server/src/http-server.ts, packages/http-server/test/integration/http-server.integration.ts
**fix(http-server): use loopback instead of 0.0.0.0/[::] in URLs**
Host values `0.0.0.0` (IPv4) and `::` (IPv6), which mean "any host", are not supported by certain browsers and platforms, e.g. Windows and Safari on MacOS.
This commit fixes the `url` getter to convert these "any host" values into a loopback address (`127.0.0.1` for IPV4 or `::1` for IPv6).
**feat(cli): use `app.restServer.url` for console logs**
Rework and simplify the application project template:
- Remove console logs from `Application.prototype.start()`, let the caller print any logs if they wish to.
- Modify the `main` function to log the URL to the console, use `app.restServer.url` to obtain the URL where the app is listening on.
- Update example projects to follow this new style.
- API Documentation in code was …
=> Use `app.restServer.url` for console logs, improve the URL generated by http-server

docs/site/Application.md, docs/site/Context.md, docs/site/Creating-components.md, docs/site/Defining-the-API-using-code-first-approach.md, docs/site/Defining-the-API-using-design-first-approach.shelved.md, docs/site/Parsing-requests.md, docs/site/Preparing-the-API-for-consumption.shelved.md, docs/site/Reserved-binding-keys.md, docs/site/Testing-your-application.md
Fixes how this page is rendered on the docs: https://loopback.io/doc/en/lb4/Parsing-requests.html
Tested in Chrome. Verified all pages I changed to make sure none others broke (after making the usage consistent).
Before: 
After:
=> docs: fix info style

docs/site/Calling-other-APIs-and-Web-Services.md, examples/todo/src/services/geocoder.service.ts, examples/todo/test/integration/services/geocoder.service.integration.ts, packages/service-proxy/src/legacy-juggler-bridge.ts, packages/service-proxy/test/integration/service-proxy.integration.ts, packages/service-proxy/test/mock-service.connector.ts
When `getService` returns a service, it does not wait until the service has been completely set up. The PR now calls `datasource.connect()` before the service is returned.
- related to #1553
=> fix(service-proxy): await datasource until it connects to the service

docs/site/todo-tutorial-juggler.md
The content on `todo-tutorial-juggler.md` was outdated.
fixes #1566
=> fix: update todo juggler page

README.md
We have recently created an AppVeyor org to run our CI builds on Windows. This commit changes the badge URL in README to point to the new AppVeyor project.
cc @strongloop/sq-lb-apex
=> chore: update AppVeyor badge URL

docs/site/Controller-generator.md, examples/todo-list/src/controllers/todo-list.controller.ts, examples/todo-list/test/acceptance/todo-list.acceptance.ts, examples/todo-list/test/unit/controllers/todo-list.controller.unit.ts, packages/cli/generators/controller/templates/src/controllers/controller-rest-template.ts.ejs, packages/cli/test/integration/generators/controller.integration.js
The endpoint for deleting all model instances is dangerous - it makes it too easy to accidentally delete the entire table/collection. We have intentionally not exposed this endpoint by default in LoopBack 3.x.
This commits is removing deleteAll endpoint from the REST Controller template used by `lb4 controller` command.
=> fix(cli): remove deleteAll endpoint from REST Controller template

packages/build/package.json, packages/cli/package.json
Some of the code formatting depends on `prettier@^1.14.0`.
=> chore(build): make sure prettier@^1.14.0 is used

docs/site/Download-examples.md, docs/site/Preparing-the-API-for-consumption.shelved.md, examples/hello-world/README.md, examples/log-extension/README.md, examples/rpc-server/README.md, examples/todo-list/README.md, examples/todo/README.md, packages/cli/generators/example/index.js, packages/cli/lib/base-generator.js, packages/cli/lib/project-generator.js, packages/cli/test/integration/generators/example.integration.js
fixes #1555 
Output for `lb4 example todo` now:
```
? What example would you like to clone? todo
> sinon@4.5.0 postinstall /Users/taranveer/LoopBack/loopback4-example-todo/node_modules/sinon
> node scripts/support-sinon.js
Have some ❤️ for Sinon? You can support the project via Open Collective:
> https://opencollective.com/sinon/donate
npm notice created a lockfile as package-lock.json. You should commit this file.
added 752 packages from 1412 contributors and audited 4565 packages in 12.455s
found 0 vulnerabilities
The example was cloned to loopback4-example-todo.
```
=> fix(cli): install dependencies for cloned examples

examples/soap-calculator/README.md, examples/soap-calculator/test/acceptance/application.acceptance.ts
remove the call to givenDataSource since it is not needed as the datasource booter takes care of it
=> test(example-soap-calculator): remove givenDataSource from test

packages/cli/generators/app/index.js, packages/cli/generators/app/templates/src/application.ts.ejs, packages/cli/test/integration/generators/app.integration.js
add the switch --enableRepository to CLI to automatically add the juggler imports and include
RepositoryMixin in the extended class
Fixes #1594
I tried to follow the pattern in applicationName and loopbackBuild in the switch name and followed @raymondfeng suggested switch name (--enable-repository). Please review and let me know if it makes sense. This is a minor change but really useful when creating the application.
=> feat(cli): add repositorymixin and imports by a new switch

packages/cli/generators/model/index.js, packages/cli/generators/model/templates/model.ts.ejs
The CLI used to build the templates without the quotation marks around value for `arrayType`.
Also removes the ugly new lines generated through the template
The generated code before:
```ts
import {Entity, model, property} from '@loopback/repository';
@model()
export class Model extends Entity {
@property({
type: 'array',
arrayType: string,
})
prop?: string[];
@property({
type: 'number',
})
propNumberTwo?: number;
constructor(data?: Partial<Model>) {
super(data);
}
}
```
The generated code with this PR:
```ts
import {Entity, model, property} from '@loopback/repository';
@model()
export class Model extends Entity {
@property({
type: 'array',
arrayType: 'string',
})
prop?: string[];
@property({
type: 'number',
})
propNumberTwo?: number;
constructor(data?: Partial<Model>) {
super(data);
}
} …
```
=> fix(cli): change model template to properly render array types

packages/cli/generators/model/index.js, packages/cli/generators/model/templates/model.ts.ejs, packages/repository-json-schema/src/build-schema.ts, packages/repository-json-schema/test/integration/build-schema.integration.ts, packages/repository-json-schema/test/unit/build-schema.unit.ts, packages/repository/src/decorators/model.decorator.ts, packages/repository/src/model.ts, packages/repository/src/repositories/legacy-juggler-bridge.ts, packages/repository/test/unit/decorator/metadata.unit.ts, packages/repository/test/unit/decorator/model-and-relation.decorator.unit.ts, packages/repository/test/unit/decorator/relation.decorator.unit.ts, packages/repository/test/unit/repositories/legacy-juggler-bridge.unit.ts
The property definition for arrays used to be defined this way:
```ts
{type: 'string', array: true}
// or
{type: String, array: true}
```
This does not match with the property definition of an array as the legacy juggler would define it. The property definition created by the `@property.array(String)` decorator can now look like this:
```ts
{type: 'array', itemType: String}
// @repository-json-schema also supports
{type: 'array', itemType: 'string'}
```
Related to #1508
Fixes #1562
=> Juggler array

.gitignore, .prettierignore, .vscode/settings.json, benchmark/.npmrc, benchmark/LICENSE, benchmark/README.md, benchmark/index.js, benchmark/index.ts, benchmark/package.json, benchmark/src/autocannon.ts, benchmark/src/benchmark.ts, benchmark/src/client.ts, benchmark/src/index.ts, benchmark/src/scenarios/create-todo.scenario.ts, benchmark/src/scenarios/find-todos.scenario.ts, benchmark/src/scenarios/index.ts, benchmark/src/worker.ts, benchmark/test/benchmark.integration.ts, benchmark/test/mocha.opts, benchmark/tsconfig.build.json, examples/todo/src/index.ts, lerna.json
Add two simple benchmarks to measure how fast we can fetch data (`repository#find`) and create new records (`repository#create`).
See #534
**An important discussion point: Should we check that the benchmark keeps working as part of our test suite?**
Autocannon, the library I use for hammering the app with client requests, does not support runs shorter than one second. Together with the worker-process setup, the minimum benchmark run is about five seconds.
I feel adding five seconds to our already long-running test suite may be too much.
On the other hand, if we don't run these test frequently, then we may end up with benchmarking code that no longer works.
Thoughts?
- Affected …
=> feat: add two simple benchmarks

packages/context/src/inject.ts, packages/context/test/unit/inject.unit.ts
Fixes https://github.com/strongloop/loopback-next/issues/1565
=> fix(context): check constructor/method override for @inject

packages/build/config/tsconfig.common.json, packages/repository/examples/juggler-bridge/note-with-repo-class.ts, packages/repository/examples/juggler-bridge/note-with-repo-instance.ts, packages/repository/package.json, packages/repository/src/common-types.ts, packages/repository/src/model.ts, packages/repository/src/repositories/constraint-utils.ts, packages/repository/src/repositories/index.ts, packages/repository/src/repositories/kv.repository.bridge.ts, packages/repository/src/repositories/kv.repository.ts, packages/repository/src/repositories/legacy-juggler-bridge.ts, packages/repository/src/repositories/relation.factory.ts, packages/repository/src/repositories/relation.repository.ts, packages/repository/test/unit/repositories/kv.repository.bridge.unit.ts, packages/repository/test/unit/repositories/relation.repository.unit.ts, packages/service-proxy/package.json
Replacing https://github.com/strongloop/loopback-next/pull/1527, see also #1448
=> feat(repository): add KVRepository impl using legacy juggler

packages/cli/generators/project/templates/tsconfig.json.ejs
This fixes the build error for generated LB4 project without `loopbackBuild` selected:
```
> tsc --outDir dist --target es2017
node_modules/@loopback/repository/dist8/src/repositories/kv.repository.bridge.d.ts(29,55): error TS2304: Cannot find name 'AsyncIterable'.
node_modules/@loopback/repository/dist8/src/repositories/kv.repository.d.ts(72,56): error TS2304: Cannot find name 'AsyncIterable'.
```
=> fix(cli): add esnext.asynciterable to lib for typescript

packages/http-caching-proxy/package.json, packages/http-caching-proxy/test/integration/http-caching-proxy.integration.ts
Master build fails due to npm module `delay`. See https://github.com/sindresorhus/delay/blob/master/index.d.ts
=> Fix build error

examples/hello-world/package.json, examples/log-extension/package.json, examples/rpc-server/package.json, examples/soap-calculator/package.json, examples/todo-list/package.json, examples/todo/package.json, package.json, packages/cli/generators/app/templates/test/acceptance/ping.controller.acceptance.ts.ejs, packages/cli/generators/controller/templates/src/controllers/controller-rest-template.ts.ejs, packages/cli/generators/datasource/templates/datasource.ts.ejs, packages/cli/generators/project/templates/package.json.ejs, packages/cli/generators/project/templates/package.plain.json.ejs, packages/cli/test/integration/generators/datasource.integration.js
Came across the following annoyances when working on `@loopback/example-shopping`
- Move `ping.controller.acceptance.ts` from `/test` to `/test/acceptance`.
- For REST Controller Template change `obj` to the model name as it's more descriptive
- Remove unused import from datasource template
- Run `tslint:fix` before `prettire:fix` for `lint:fix` since I ran into an issue where tslint:fix breaks prettier formatting requiring you to run `prettier:fix` / `lint:fix` again.
- Reorder the dependencies so they are alphabetical otherwise `npm install` results in additional changes to the file diff ass it reorders the deps alphabetically.
=> fix(cli): tweaks to templates

docs/site/sidebars/lb4_sidebar.yml
See https://loopback.io/doc/en/lb4/Testing-your-extension.html
The entry appears twice in the sidebar ... making the sidebar look all weird with both entries highlighted. Should only appear once.
=> docs: remove testing-your-extension double entry in sidebar

bin/build-docs-site.sh, bin/config-lerna-scopes.js, bin/run-lerna.js, bin/travis.sh, bin/update-template-deps.js, commitlint.config.js, lerna.json, package.json, packages/build/.prettierrc, packages/build/package.json, packages/build/test/integration/scripts.integration.js, packages/cli/test/acceptance/app-run.acceptance.js
Upgrade to TypeScript 3.0.x and lerna 3.1.x
=> chore: upgrade to typescript 3.0.x and lerna 3.1.x

packages/openapi-v3/src/controller-spec.ts, packages/openapi-v3/test/integration/operation-spec.integration.ts, packages/openapi-v3/test/unit/decorators/param/param-path.decorator.unit.ts, packages/openapi-v3/test/unit/decorators/param/param.decorator.unit.ts, packages/rest/test/unit/parser.unit.ts
https://github.com/strongloop/loopback-next/issues/1531
It sets `required: true` for path parameters to be compliant with OpenAPI spec.
=> fix(openapi-v3): set required to true for path parameters

docs/site/Crafting-LoopBack-4.md
=> docs: explain express in crafting loopback 4

docs/site/Testing-your-application.md
=> Add testdb.datasource.ts example in Testing doc section 

bin/update-template-deps.js
Fix how to use lerna to collect packages.
=> Fix lerna packages

benchmark/src/benchmark.ts, benchmark/src/worker.ts, docs/site/Booting-an-Application.md, docs/site/todo-tutorial-putting-it-together.md, examples/soap-calculator/src/application.ts, examples/todo-list/src/application.ts, examples/todo/src/application.ts, packages/boot/test/fixtures/application.ts, packages/cli/generators/app/templates/src/application.ts.ejs, packages/repository/README.md, packages/repository/src/repositories/legacy-juggler-bridge.ts, packages/repository/test/unit/query/query-builder.unit.ts, packages/rest/src/keys.ts, tsconfig.json
With the new TypeScript version, it is no longer necessary to manually import types referenced by mixin classes.
This commit removes those extra imports from the CLI template and scaffolded "application.ts" files; and also sorts import using VS Code's feature "Organize imports".
I have discovered this opportunity while working on service-registration mixin (#1439).
=> fix: remove extra imports for mixin dependencies

docs/site/Model.md, packages/repository/src/repositories/legacy-juggler-bridge.ts, packages/repository/test/acceptance/repository.acceptance.ts
Send 404 for delete requests to non-existent resource by default. Addresses issues like #1472
=> feat: default 404 for delete request to non-existent resource

docs/site/soap-calculator-tutorial.md, examples/soap-calculator/README.md
add full path of image and adjust 2 links that were still not working from inside the first page. sorry this was not covered in the last PR (missed it).
- [ x] `npm test` passes on your machine
=> docs(example-soap-calculator): fix image link from README.md file

docs/site/Calling-other-APIs-and-Web-Services.md, docs/site/soap-calculator-tutorial-register-service.md, docs/site/todo-tutorial-geocoding-service.md, examples/soap-calculator/src/application.ts, examples/todo/src/application.ts, packages/boot/src/booters/datasource.booter.ts, packages/boot/src/booters/repository.booter.ts, packages/boot/test/unit/booters/datasource.booter.unit.ts, packages/boot/test/unit/booters/repository.booter.unit.ts, packages/cli/generators/app/index.js, packages/cli/generators/app/templates/src/application.ts.ejs, packages/cli/generators/project/templates/package.json.ejs, packages/cli/test/integration/generators/app.integration.js, packages/repository/src/mixins/repository.mixin.ts, packages/repository/test/acceptance/has-many.relation.acceptance.ts, packages/service-proxy/docs.json, packages/service-proxy/src/mixins/index.ts, packages/service-proxy/src/mixins/service.mixin.ts, packages/service-proxy/test/unit/mixin/service.mixin.unit.ts
Implement "ServiceMixin" for applications. This mixin enhances component
registration so that service providers exported by a component are
automatically registered for dependency injection; and adds a new sugar
API for registering service providers manually:
```ts
app.serviceProvider(MyServiceProvicer);
```
The method name "serviceProvider" was chosen deliberately to make it
clear that we are binding a Provider, not a class constructor. Compare
this to `app.repository(MyRepo)` that accepts a class construct. In the
future, we may add `app.service(MyService)` method if there is enough
user demand.
This pull request is the first step towards automated service registration via boot, see #1439.
=> feat(service-proxy): add service mixin

packages/build/config/tslint.build.json, packages/context/test/unit/value-promise.unit.ts, packages/rest/test/acceptance/coercion/coercion.acceptance.ts, packages/rest/test/acceptance/validation/validation.acceptance.ts, packages/rest/test/integration/rest.server.integration.ts, packages/rest/test/unit/rest.server/rest.server.unit.ts
A follow-up for https://github.com/strongloop/loopback-next/pull/1648.
> After I disabled no-unused-variable check, tslint started to complain about places incorrectly using promises. Some of the warnings were legitimate and I fixed the code. Other cases were not valid, I fixed them by modifying tslint config and adding comments to disable the problematic rule for few source code lines.
It makes me wonder why `tslint` is not reporting these promise-related problems when `no-unused-variable` is enabled, but I can't be bothered to investigate.
- Affected …
=> build: fix tslint issues related to promises

docs/site/Repositories.md
Add basic docs for `KeyValueRepository]` using https://github.com/strongloop/loopback4-example-shopping/pull/4 as an example.
=> docs: add basic docs for KeyValueRepository

packages/rest/package.json, packages/rest/src/keys.ts, packages/rest/src/providers/reject.provider.ts, packages/rest/src/writer.ts, packages/rest/test/integration/http-handler.integration.ts
This PR configures `writer.ts` to use `strong-error-handler` to transform the thrown error.
Please take a look at the modified test cases to see what the response body would now look like.
- fixes #1434 
- depends on https://github.com/strongloop/strong-error-handler/pull/77
=> fix(rest): pass a better detailed error message into the response body

docs/site/Getting-started.md, docs/site/soap-calculator-tutorial-scaffolding.md, docs/site/todo-tutorial-scaffolding.md, examples/log-extension/README.md, packages/cli/generators/app/index.js, packages/cli/generators/app/templates/src/application.ts.ejs, packages/cli/generators/project/templates/package.json.ejs, packages/cli/lib/project-generator.js
_This is a follow-up for #1652 and #1649._
- Rename `--enableRepository` to `--repositories`  (notice the plural form)
- Rename `--enableServices` to `--services`
This commit fixes the inconsistency where `--enableRepository` was using the singular form, while `--enableServices` was using the plural form.
It also improves the feature prompt so that the word "enable" is not
repeated twice.
Before:
? Select project build settings:
❯◉ Enable tslint
◉ Enable prettier
◉ Enable mocha
◉ Enable loopbackBuild
◉ Enable vscode
◉ Enable enableRepository
◉ Enable enableServices
After:
? Select features to enable in the project:
❯◉ Enable tslint
◉ Enable prettier
◉ Enable mocha
◉ Enable loopbackBuild
◉ Enable vscode
◉ Enable repositories
◉ Enable services
=> fix(cli): rename repository/service feature flags

docs/site/Application.md, docs/site/Defining-the-API-using-code-first-approach.md, docs/site/Repositories.md, packages/rest/src/rest.application.ts, packages/rest/src/rest.server.ts, packages/rest/test/integration/fixtures/index.html, packages/rest/test/integration/rest.server.integration.ts
This PR allows static assets to be served from a REST server by calling `static()`.
- ~~When a file cannot be read (e.g. because of permission problems), the error response is sent by the Sequence (as provided/customized by the app).~~
=> feat(rest): allow static assets to be served by a rest server

docs/site/Model.md, docs/site/Repositories.md, docs/site/todo-tutorial-controller.md, docs/site/todo-tutorial-datasource.md, docs/site/todo-tutorial-model.md, docs/site/todo-tutorial-repository.md
=> docs: add oneliners and links to tutorials per 1444

docs/site/Parsing-requests.md, packages/openapi-v3-types/package.json, packages/openapi-v3/src/decorators/parameter.decorator.ts, packages/openapi-v3/test/unit/decorators/param/param-query.decorator.unit.ts, packages/rest/package.json, packages/rest/src/coercion/coerce-parameter.ts, packages/rest/src/coercion/utils.ts, packages/rest/src/coercion/validator.ts, packages/rest/src/parser.ts, packages/rest/src/rest-http-error.ts, packages/rest/src/rest.server.ts, packages/rest/test/acceptance/coercion/coercion.acceptance.ts, packages/rest/test/unit/coercion/paramObject.unit.ts, packages/rest/test/unit/coercion/utils.ts, packages/rest/test/unit/parser.unit.ts
Introduce a new decorator `@param.query.object` allowing controller methods to describe a parameter as an object and optionally provide the schema for the accepted values.
Improve `parseParams` action to correctly parse and coerce object values coming from query strings, supporting the following two flavours:
- "deepObject" encoding as described by OpenAPI Spec v3:
GET /api/products?filter[where][name]=Pen&filter[limit]=10
- JSON-based encoding for compatibility with LoopBack 3.x:
GET /api/products?filter={"where":{"name":"Pen"},"limit":10}
See #100 
While working on these changes, I discovered and fixed a bug in openapiv3-ts, see https://github.com/metadevpro/openapi3-ts/pull/28.
- Affected example projects in `examples/*` were …
=> feat: coerce object arguments from query strings

docs/site/Glossary.md
Currently from the LB4 docs sidebar, when clicking on Reference > Glossary, it says "Page Not Found".
=> docs: Fix "Page Not Found" error when going to the Glossary page

docs/site/Server.md, packages/rest/README.md, packages/rest/src/rest.component.ts, packages/rest/src/rest.server.ts, packages/rest/test/integration/rest.server.integration.ts
The generated openapi spec has a dummy server url at the moment: `servers: [url: '/']`. The PR adds more options to rest server config.
See https://github.com/strongloop/loopback-next/blob/c78d636b9cccf66bc843ec49b203b0a6c319f78e/packages/rest/README.md#configuration
=> feat(rest): provide more options to customize api explorer and openapi spec

packages/rest/package.json, packages/rest/src/keys.ts
See https://github.com/Microsoft/TypeScript/issues/26985
Work around https://github.com/strongloop/loopback-next/issues/1688#issuecomment-419688949
=> fix(rest): use direct import to work around a TS bug

packages/cli/bin/cli-main.js, packages/cli/lib/cli.js, packages/cli/package.json, packages/cli/test/integration/cli/cli.integration.js, packages/dist-util/index.js, packages/dist-util/package.json
Check required Node.js versions and print out meaningful error message if fails.
=> chore: add node version check to fail gracefully

lerna.json, package.json, packages/build/bin/utils.js
For some reason, the `tsc` process exits before the `outDir` is created. This PR adds some logic to detect such cases and limit concurrency to 16 to prevent processes from being killed by travis.
See  https://docs.travis-ci.com/user/common-build-problems/#my-build-script-is-killed-without-any-error.
=> fix: limit concurrent processes to prevent them from being killed by travis

packages/cli/generators/datasource/index.js
It seems that the connector in mention doesn't have a settings property, thus the code was not enforcing a {} object but rather an undefined, which caused the generator to fail. I am assuming this connector doesn't need the settings property, if that's the case , this PR successfully fixes the error. If not, then I believe we need to add the settings property also.
fix #1697
=> fix(cli): enforce an empty object on connectors with no settings

docs/site/Deploying-to-IBM-Cloud.md, docs/site/sidebars/lb4_sidebar.yml
Document deployment to Cloud Foundry. Addresses https://github.com/strongloop/loopback-next/issues/1604.
=> docs: document deployment to Cloud Foundry

examples/todo-list/src/controllers/todo-list-todo.controller.ts, examples/todo-list/src/controllers/todo-list.controller.ts, examples/todo-list/src/controllers/todo.controller.ts, examples/todo/src/controllers/todo.controller.ts, packages/boot/test/fixtures/multiple.artifact.ts, packages/cli/generators/controller/templates/src/controllers/controller-rest-template.ts.ejs, packages/cli/test/integration/generators/controller.integration.js, packages/openapi-spec-builder/src/openapi-spec-builder.ts, packages/openapi-v3/src/controller-spec.ts, packages/openapi-v3/src/decorators/parameter.decorator.ts, packages/openapi-v3/src/decorators/request-body.decorator.ts, packages/openapi-v3/src/generate-schema.ts, packages/openapi-v3/test/integration/controller-spec.integration.ts, packages/openapi-v3/test/integration/operation-spec.integration.ts, packages/openapi-v3/test/unit/decorators/operation.decorator.unit.ts, packages/openapi-v3/test/unit/decorators/param/param.decorator.unit.ts, packages/openapi-v3/test/unit/generate-schema.unit.ts, packages/rest/test/unit/rest.server/rest.server.open-api-spec.unit.ts
connected to #1531 
---
This PR:
- Ensures we set a default `responses` property on a Controller methods OpenAPI Spec if one isn't given
- Extends the OpenAPI spec by introducing a `x-ts-type` property that can be used to specify the schema of a response object. Can also be used to specify the type of array items. 
```
content: {'x-ts-type': Todo} => content: {schema: {$ref: '#components/schemas/Todo'}}
content: {schema: {type: 'array', items: {x-ts-type: Todo}}} => content: {schema: {type: 'array', items: {$ref: '#components/schemas/Todo'}}}
```
- Refactors `generate-schema` to have a single function to resolve schema from a Function.
- Updates CLI Controller template to set a `responses` object based on the Model
- Updates `example-todo` / `example-todo-list` to set `responses` object …
=> feat(openapi-v3): responses decorator

docs/site/Booting-an-Application.md, docs/site/todo-tutorial-geocoding-service.md
Document the need for extend the application with ServiceMixin and fix two typos in service booter
doc
re #1701
=> docs: todo-tutorial extend app with ServiceMixin

examples/hello-world/src/application.ts, examples/rpc-server/src/application.ts, examples/rpc-server/src/index.ts, examples/soap-calculator/src/application.ts, examples/soap-calculator/src/index.ts, examples/todo-list/src/application.ts, examples/todo-list/src/index.ts, examples/todo/src/application.ts, examples/todo/src/index.ts, packages/boot/src/bootstrapper.ts, packages/cli/generators/app/templates/src/application.ts.ejs, packages/cli/generators/app/templates/src/index.ts.ejs, packages/core/src/application.ts, packages/rest/src/rest.application.ts, packages/rest/src/rest.server.ts
`options` is an optional argument. Causes us to introduce unnecessary checks to see if it exists in the deploy workflow. This PR proposes making the argument optional by setting a default value instead of marking it as optional.
=> refactor: set default for optional options argument

packages/cli/generators/project/templates/_.gitignore
Fix the project template to configure Git to ignore all dist files created by the TypeScript compiler, e.g. `dist8` for Node.js 8.x and `dist10` for Node.js 10.x
Before this change, only the directory `dist` was ignored.
I discovered this problem while testing #1659
=> fix(cli): git-ignore all "dist*" dirs in scaffolded projects

packages/rest/src/parser.ts, packages/rest/src/validation/request-body.validator.ts, packages/rest/test/unit/request-body.validator.test.ts
When the code fails to generate schema for a model class, the error thrown is lost and it's hard to figure out what went wrong.
This PR exposes such errors.
=> fix(rest): make sure validation system error is reported

docs/site/Error-handling.md, docs/site/sidebars/lb4_sidebar.yml, examples/todo-list/src/controllers/todo-list.controller.ts, examples/todo-list/test/acceptance/todo-list.acceptance.ts, examples/todo-list/test/acceptance/todo.acceptance.ts, examples/todo/test/acceptance/todo.acceptance.ts, packages/cli/generators/controller/templates/src/controllers/controller-rest-template.ts.ejs, packages/cli/test/unit/update-index.unit.js, packages/context/test/unit/value-promise.unit.ts, packages/repository/src/errors/entity-not-found.error.ts, packages/repository/src/errors/index.ts, packages/repository/src/index.ts, packages/repository/src/model.ts, packages/repository/src/repositories/legacy-juggler-bridge.ts, packages/repository/src/repositories/repository.ts, packages/repository/test/unit/decorator/model-and-relation.decorator.unit.ts, packages/repository/test/unit/errors/entity-not-found-error.test.ts, packages/repository/test/unit/model/model.unit.ts, packages/repository/test/unit/repositories/legacy-juggler-bridge.unit.ts, packages/rest/src/providers/reject.provider.ts, packages/rest/src/rest-http-error.ts, packages/rest/src/validation/request-body.validator.ts, packages/rest/test/unit/request-body.validator.test.ts, packages/rest/test/unit/router/reject.provider.unit.ts
_This is an alternative solution to #1617 that fixes #1469._
- test: fix incorrect usage of rejectedWith assertion. I discovered this problem while fixing tests added as part of this pull request.
- feat(repository): change Model.modelName to a computed property. This ensures `modelName` is always available and match model definition.
- feat(repository): implement EntityNotFoundError. This error builds a descriptive error message and sets `error.code` to `ENTITY_NOT_FOUND` string.
- refactor: rework "findById" to leverage EntityNotFoundError. As a result, "model not found" scenario can be detected by checking whether the error `code` is `ENTITY_NOT_FOUND`.
- fix(rest): return 404 when a model was not found. Here we modify the `reject` action to convert `ENTITY_NOT_FOUND` error code to …
=> fix: return 404 when a model was not found

docs/site/Controller-generator.md, docs/site/Model.md, docs/site/todo-tutorial-controller.md, examples/todo-list/src/controllers/todo-list.controller.ts, examples/todo-list/src/controllers/todo.controller.ts, examples/todo-list/test/acceptance/todo-list-todo.acceptance.ts, examples/todo-list/test/acceptance/todo-list.acceptance.ts, examples/todo-list/test/acceptance/todo.acceptance.ts, examples/todo-list/test/unit/controllers/todo-list.controller.unit.ts, examples/todo-list/test/unit/controllers/todo.controller.unit.ts, examples/todo/src/controllers/todo.controller.ts, examples/todo/test/acceptance/todo.acceptance.ts, examples/todo/test/unit/controllers/todo.controller.unit.ts, packages/cli/generators/controller/templates/src/controllers/controller-rest-template.ts.ejs, packages/cli/test/integration/generators/controller.integration.js, packages/repository/src/repositories/legacy-juggler-bridge.ts, packages/repository/src/repositories/repository.ts, packages/repository/test/acceptance/repository.acceptance.ts, packages/repository/test/unit/repositories/legacy-juggler-bridge.unit.ts, packages/rest/src/writer.ts, packages/rest/test/unit/writer.unit.ts
_This is a follow-up for #1658 related to #1469._
Rework Repository interface and implementations to throw EntityNotFound error from `updateById`, `replaceById` and `deleteById` when there is no entity with the provided id. 
Update related controller methods to return 204 No Content on success, because there is no boolean flag to indicate success anymore. Clients should check the response status code instead (204 vs 404).
Improve our REST layer to set the response status code to 204 when body is undefined.
This patch is reverting the implementation details of #1621 while keeping the observed REST API behavior.
See the discussion in #1658 and https://github.com/strongloop/loopback-next/pull/1658#issuecomment-421966796 in particular to better understand the reasoning for this change. Also …
=> feat(repository): rework *ById methods to throw if id not found

lerna.json, packages/cli/package.json
Remove dependency on `nsp` which is deprecated and will be shutdown soon.
=> Remove nsp

docs/site/soap-calculator-tutorial-add-datasource.md
without trailing slash response will be empty
=> fix(docs): fix incorrect soap url

docs/site/Implementing-features.shelved.md, docs/site/Testing-your-application.md, examples/hello-world/test/acceptance/application.acceptance.ts, examples/soap-calculator/test/acceptance/application.acceptance.ts, examples/todo-list/test/acceptance/todo-list-todo.acceptance.ts, examples/todo-list/test/acceptance/todo-list.acceptance.ts, examples/todo-list/test/acceptance/todo.acceptance.ts, examples/todo/test/acceptance/todo.acceptance.ts, packages/boot/test/acceptance/controller.booter.acceptance.ts, packages/cli/generators/app/templates/test/acceptance/ping.controller.acceptance.ts.ejs, packages/rest/test/acceptance/bootstrapping/rest.acceptance.ts, packages/rest/test/acceptance/coercion/coercion.acceptance.ts, packages/rest/test/acceptance/validation/validation.acceptance.ts, packages/testlab/README.md, packages/testlab/src/client.ts
While reviewing https://github.com/strongloop/loopback4-example-shopping/pull/12, I noticed the test code is depending on low-level types from `supertest` that are difficult to discover (in my experience). I decided to fix this and introduce a type alias, only to find that we already have `Client` alias defined! As I was replacing supertest type with `Client` alias,  I found few places calling `supertest` directly instead of using our `createClient*` helper APIs and decided to improve that too. Here is the outcome:
- Clean up all test code (including examples in the documentation) to use `Client` instead of `supertest.SuperTest<supertest.Test>`.
- Remove `createClientForRestServer` because it was not used anywhere and had the issue of leaking a listening server (not stopping the server …
=> feat(testlab): add createRestAppClient(), simplify usage in tests

packages/cli/generators/project/templates/package.json.ejs
Remove the following dependencie:
- `mocha`
- `@types/mocha`
- `source-map-support`
These dependencies are not needed because `mocha` is invoked via `lb-mocha` from `@loopback/build`.
As a nice side effect, when a new application is scaffolded via `lb4 app` into loopback-next's `sandbox` folder, then `lerna bootstrap` does not need to install any 3rd party dependencies for this new project, everything is resolved locally from loopback-next packages.
=> fix(cli): removed unused dependencies from project template

examples/hello-world/test/acceptance/application.acceptance.ts, examples/todo-list/test/acceptance/todo-list-todo.acceptance.ts, examples/todo-list/test/acceptance/todo-list.acceptance.ts, examples/todo-list/test/acceptance/todo.acceptance.ts, examples/todo/test/acceptance/todo.acceptance.ts, packages/boot/test/acceptance/controller.booter.acceptance.ts, packages/cli/generators/app/templates/test/acceptance/ping.controller.acceptance.ts.ejs, packages/http-server/test/integration/http-server.integration.ts, packages/rest/test/acceptance/coercion/coercion.acceptance.ts, packages/rest/test/acceptance/validation/validation.acceptance.ts, packages/testlab/src/http-server-config.ts
Modify the test helper `givenHttpServerConfig` to explicitly set the port to zero. With this change in place, applications can use this helper in acceptation tests without having to explicitly specify `{port: 0}` to override RestServer's default port 3000.
=> feat(testlab): set port to zero in givenHttpServerConfig

packages/cli/bin/cli-main.js, packages/cli/package.json
Add [update-notifier](https://github.com/yeoman/update-notifier) to remind users of newer CLI versions.
=> feat(cli): add update notifier to remind cli upgrade

packages/testlab/README.md, packages/testlab/src/index.ts, packages/testlab/src/to-json.ts, packages/testlab/test/unit/to-json.test.ts
Implement a helper function to convert an object (e.g. a Model instance) to a data object representing JSON version of the input object.
Specifically, properties set to a value that cannot be represented in
JSON (e.g. `undefined`) are removed from the result.
=> feat(testlab): add a new helper `toJSON`

packages/rest/src/coercion/coerce-parameter.ts, packages/rest/test/acceptance/coercion/coercion.acceptance.ts, packages/rest/test/unit/coercion/paramStringToString.unit.ts
Add a missing coercion step for string parameters and prevent the situation when a string value provided by the HTTP client and converted into an object or an array by query-string parser is passed as-is to the controller method, violating the endpoint contract and TypeScript declaration.
I discovered this problem while working on #1679. Without this change, endpoints like `TodoListController#count` are incorrectly accepting object values for their `where` parameter described as `type: string`. 
https://github.com/strongloop/loopback-next/blob/d65a17fab7ce44b7977e9c03388f5684558475f2/examples/todo-list/src/controllers/todo-list.controller.ts#L37-L39
- Affected artifact templates …
=> fix(rest): coerce string parameters (reject object values)

docs/site/Controller-generator.md, docs/site/todo-list-tutorial-controller.md, examples/todo-list/src/controllers/todo-list-todo.controller.ts, examples/todo-list/src/controllers/todo-list.controller.ts, examples/todo-list/src/controllers/todo.controller.ts, examples/todo-list/src/repositories/todo-list.repository.ts, examples/todo-list/test/acceptance/todo-list-todo.acceptance.ts, examples/todo-list/test/acceptance/todo-list.acceptance.ts, examples/todo-list/test/acceptance/todo.acceptance.ts, examples/todo/src/controllers/todo.controller.ts, examples/todo/test/acceptance/todo.acceptance.ts, examples/todo/test/unit/controllers/todo.controller.unit.ts, packages/cli/generators/controller/index.js, packages/cli/generators/controller/templates/src/controllers/controller-rest-template.ts.ejs, packages/cli/test/integration/generators/controller.integration.js, packages/openapi-v3/src/decorators/parameter.decorator.ts, packages/openapi-v3/src/filter-schema.ts, packages/openapi-v3/src/index.ts, packages/openapi-v3/test/unit/decorators/param/param-query.decorator.unit.ts, packages/repository-json-schema/src/filter-json-schema.ts, packages/repository-json-schema/src/index.ts, packages/repository-json-schema/test/unit/filter-json-schema.unit.ts, packages/repository/src/decorators/model.decorator.ts, packages/repository/src/decorators/relation.decorator.ts, packages/repository/src/model.ts, packages/repository/test/unit/decorator/relation.decorator.unit.ts, packages/rest/test/unit/coercion/paramObject.unit.ts, packages/rest/test/unit/parser.unit.ts
This pull request leverages the recently added `@param.query.object()` decorator (see #1667) to add support for querying a subset of models using a Filter object.
For example:
```
GET /todos?filter[where][isCompleted]=false
```
The OpenAPI spec contains a reasonably-minimal description of the Filter object.
**Done**
- infrastructure to describe `filter` and `where` parameters
- updated `todo` example 
- update `todo-list` example
- update CRUD Controller template in CLI
- doc updates
See also #100
=> REST API to find models using a filter 

packages/rest/src/writer.ts, packages/rest/test/unit/writer.unit.ts
=> feat(rest): allow controller methods to handle response writing

packages/cli/generators/app/templates/src/controllers/ping.controller.ts.ejs, packages/cli/generators/app/templates/test/acceptance/ping.controller.acceptance.ts.ejs, packages/cli/test/integration/generators/app.integration.js, packages/rest/src/index.ts
Fixes https://github.com/strongloop/loopback-next/issues/1754
=> feat(cli): add responses for PingController.ping()

docs/site/Service-generator.md, docs/site/sidebars/lb4_sidebar.yml, docs/site/tables/lb4-artifact-commands.html, packages/cli/generators/datasource/templates/datasource.ts.ejs, packages/cli/generators/repository/index.js, packages/cli/generators/service/index.js, packages/cli/generators/service/templates/service-template.ts.ejs, packages/cli/lib/cli.js, packages/cli/lib/utils.js, packages/cli/test/fixtures/repository/index.js, packages/cli/test/fixtures/repository/models/decoratordefined.model.txt, packages/cli/test/fixtures/repository/models/defaultmodel.model.txt, packages/cli/test/fixtures/repository/models/invalid-id.model.txt, packages/cli/test/fixtures/repository/models/multi-word.model.txt, packages/cli/test/fixtures/service/index.js, packages/cli/test/integration/cli/cli.integration.js, packages/cli/test/integration/generators/repository.integration.js, packages/cli/test/integration/generators/service.integration.js, packages/cli/test/test-utils.js, packages/cli/test/unit/utils.unit.js
This PR implements the basic generation of a service class, as discussed in https://github.com/strongloop/loopback-next/issues/1312#issuecomment-423224230.  
- **Generates** a **basic** _service class_
- Add **Integration test** 
- Add **Documentation**  for `lb4 service`
- **Move** the datasource file inspector to the utils library to be consumed by other artifacts such as lb4 repository, _this way we don't duplicate code_
- **Add* a function to return the connector type, which is basic for future inferring of remote methods, so the function returns soap or rest based on the DS name.
- **Share** `addGivenLB4Project` now with repository and service generators. This way we separate concerns and make the code reading and reviewing more efficient
- **Move** the fixtures to their respective …
=> feat(cli) add basic lb4 service 

packages/cli/generators/repository/index.js, packages/cli/generators/service/index.js, packages/cli/test/integration/generators/service.integration.js
It now runs utils.toClassName on datasource name to pass over the template generators correctly.  That function only converts the initial character of artifact name to uppercase.
closes #1771
=> fix(cli): fixes final datasource class name on repository and service

docs/site/todo-list-tutorial-controller.md, examples/todo-list/src/controllers/todo-list-todo.controller.ts, examples/todo-list/src/controllers/todo-list.controller.ts, examples/todo-list/test/acceptance/todo-list-todo.acceptance.ts, examples/todo-list/test/acceptance/todo-list.acceptance.ts, packages/cli/generators/controller/templates/src/controllers/controller-rest-template.ts.ejs, packages/cli/test/integration/generators/controller.integration.js, packages/repository/src/common-types.ts, packages/repository/src/connectors/crud.connector.ts, packages/repository/src/repositories/legacy-juggler-bridge.ts, packages/repository/src/repositories/relation.repository.ts, packages/repository/src/repositories/repository.ts, packages/repository/test/acceptance/has-many.relation.acceptance.ts, packages/repository/test/acceptance/repository.acceptance.ts, packages/repository/test/unit/repositories/crud.repository.unit.ts, packages/repository/test/unit/repositories/legacy-juggler-bridge.unit.ts, packages/repository/test/unit/repositories/relation.repository.unit.ts
fixes https://github.com/strongloop/loopback-next/issues/1471
- update repository to return a {count: number} instead of just a `number`
- update `@responses`, examples, cli, docs.
=> fix(repository): return an object for count and updateAll

packages/cli/generators/app/templates/public/index.html.ejs, packages/cli/generators/app/templates/src/controllers/home-page.controller.ts.ejs, packages/cli/generators/app/templates/test/acceptance/home-page.controller.acceptance.ts.ejs, packages/cli/generators/app/templates/test/acceptance/ping.controller.acceptance.ts.ejs, packages/cli/generators/app/templates/test/acceptance/test-helper.ts.ejs, packages/cli/lib/utils.js, packages/cli/test/integration/generators/app.integration.js
This PR adds code template for a default home page controller to be generated as part of `lb4 app`.
Fixes https://github.com/strongloop/loopback-next/issues/1745
=> feat(cli): add code template for default home page controller

packages/cli/package.json
This completes the excellent @virkt25  PR on @phenomnomnominal/tsquery , which was upgraded to tsquery@2.1.1 to include typescript 3.x as a peerDependency. Now it shouldn't display the npm warning about typescript 2.x
close #1769
=> chore(cli): upgrade tsquery that supports typescript 3.x

packages/cli/generators/app/templates/src/controllers/ping.controller.ts.ejs
This PR removes the invalid headers sent from ping controller related to OAS Graph.
@raymondfeng ,  I am not sure why we had to place headers in the response object the first time. I think they are needed for custom headers only.  we placed a basic header for content-type and additionalProperties set to true.
=> refactor(cli): update the response OAS for ping controller

packages/cli/generators/app/index.js, packages/cli/generators/controller/index.js, packages/cli/generators/datasource/index.js, packages/cli/generators/example/index.js, packages/cli/generators/model/index.js, packages/cli/generators/openapi/index.js, packages/cli/generators/repository/index.js, packages/cli/generators/service/index.js, packages/cli/lib/base-generator.js, packages/cli/test/integration/lib/artifact-generator.js
Sometimes a user try to run newer version of `lb4` against existing
applications. This feature will prompt users to confirm if some of
the project deps do not satisify the cli template.
It also checks exit status to avoid unnessary prompts.
=> feat(cli): check project deps against cli template

packages/build/package.json, packages/cli/package.json
I ran into an issue where I didn't have `typescript` installed and ran `lb4 repository`. 
```
___________________    | ~/todo-list @ biniams-mbp (badmike)
| => npm un -g typescript
removed 1 package in 0.111s
___________________    | ~/todo-list @ biniams-mbp (badmike)
| => lb4 repository
internal/modules/cjs/loader.js:583
throw err;
^
Error: Cannot find module 'typescript'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
at Function.Module._load (internal/modules/cjs/loader.js:507:25)
at Module.require (internal/modules/cjs/loader.js:637:17)
at require (internal/modules/cjs/helpers.js:20:18)
at Object.<anonymous> (/Users/badmike/n/lib/node_modules/@loopback/cli/node_modules/@phenomnomnominal/tsquery/dist/src/ast.js:4:20)
at Module._compile …
```
=> chore(cli): make typescript required dep

packages/cli/generators/repository/index.js, packages/cli/test/fixtures/repository/index.js, packages/cli/test/integration/generators/repository.integration.js
Now uses the functions created at utils to refer properly to the src/datasources file name. We fixed `lb4 services` but forgot about `lb4 repository` on this issue. Now I removed the function that was being duplicated in `lb4 repository` and use the one in utils which contains a fix for this problem.
close #1791
=> fix(cli): fixed ds names that were hyphened, uses utils functions

packages/boot/test/fixtures/application.ts, packages/boot/test/unit/booters/base-artifact.booter.unit.ts, packages/boot/test/unit/booters/booter-utils.unit.ts, packages/boot/test/unit/booters/controller.booter.unit.ts, packages/boot/test/unit/booters/datasource.booter.unit.ts, packages/boot/test/unit/booters/repository.booter.unit.ts, packages/boot/test/unit/booters/service.booter.unit.ts, packages/boot/test/unit/bootstrapper.unit.ts, packages/core/test/unit/application.unit.ts, packages/openapi-v3-types/test/unit/type-guards.unit.ts, packages/repository-json-schema/test/unit/filter-json-schema.unit.ts, packages/repository-json-schema/test/unit/json-schema.unit.ts, packages/repository/test/acceptance/repository.acceptance.ts, packages/repository/test/unit/decorator/metadata.unit.ts, packages/repository/test/unit/repositories/legacy-juggler-bridge.unit.ts, packages/rest/test/integration/rest.server.integration.ts, packages/rest/test/unit/parser.unit.ts
Simplify import paths ending with `../src` or `../index` by leaving out the last part which is not needed.
Run VSCode's "Organize Import" command in the modified files to keep import statements organized in a deterministic way.
=> refactor: simplify and organize imports

docs/site/Model-generator.md, packages/cli/generators/model/index.js, packages/cli/generators/model/templates/model.ts.ejs, packages/cli/test/integration/generators/model.integration.js
This PR adds the option to select a base model class to `lb4 model` **CLI** command.
**Done** 
- User can specify --base command line option with either Entity , Model or any valid model  custom class name. The command will validate if any custom class provided exists in `src/models`
- User is presented a list of options including Entity, Model and any valid model already created in `src/models` directory
- The **CLI** command will generate the file from the appropriate model template.
- Tests with invalid model name and valid model names were added
- Add documentation about the new option
- Thanks to @raymondfeng  suggestion the separator (base classes and custom one) was added in the model list.
**Excluded**
- `lb4 repository` update to filter models based on the baseModel  type 
- …
=> feat(cli): add lb4 model option to select base model class

examples/soap-calculator/public/index.html, examples/soap-calculator/src/controllers/home-page.controller.ts, examples/soap-calculator/src/index.ts, examples/soap-calculator/test/acceptance/home-page.controller.acceptance.ts, examples/soap-calculator/test/acceptance/test-helper.ts, examples/todo-list/public/index.html, examples/todo-list/src/controllers/home-page.controller.ts, examples/todo-list/src/index.ts, examples/todo-list/test/acceptance/home-page.controller.acceptance.ts, examples/todo-list/test/acceptance/test-helper.ts, examples/todo/public/index.html, examples/todo/src/controllers/home-page.controller.ts, examples/todo/test/acceptance/home-page.controller.acceptance.ts, examples/todo/test/acceptance/test-helper.ts
This PR close #1806 .  
**Added home page controller to:**
- todo
- todo-list
- soap-calculator
=> chore: add home page controller to examples

packages/cli/generators/app/templates/index.js.ejs, packages/cli/generators/extension/templates/index.js.ejs, packages/cli/generators/project/templates/package.json.ejs
This is a follow-up for https://github.com/strongloop/loopback-next/pull/1803 fixing few places using dist-util that I did not notice.
=> fix(cli): remove dist-util from project templates

packages/cli/bin/cli-main.js, packages/cli/package.json, packages/dist-util/README.md, sandbox/example/index.js
As a follow-up for  #1803 and #1809, this pull request is removing remaining usages of dist-util package and marking the package as deprecated. My intention is to remove dist-util from loopback-next *before* 4.0 GA.
=> feat: deprecate dist-util package

packages/repository/package.json, packages/service-proxy/package.json
Upgrade `@loopback/repository` and `@loopback/service-proxy` to use v4 of loopback-datasource-juggler.
This is a preparation of 4.0 GA release, see https://github.com/strongloop/loopback-next/issues/1744
=> chore: update juggler to 4.0

examples/soap-calculator/test/acceptance/home-page.controller.acceptance.ts
follow up on @bajtos  findings here https://github.com/strongloop/loopback-next/pull/1814#issuecomment-428141442
=> fix(example-soap-calculator): fix decreased coverage on accpetance test

README.md
connect to https://github.com/strongloop/loopback-next/issues/1744
PLEASE DO NOT MERGE IT UNTIL GA
=> docs: update GA status

README.md, docs/apidocs.html
Use `https` for apidocs assets
=> docs: use https for apidocs

packages/repository/src/errors/index.ts, packages/repository/src/errors/invalid-relation.error.ts, packages/repository/src/repositories/relation.factory.ts, packages/repository/test/unit/errors/invalid-relation-error.test.ts
Introduce a new error class InvalidRelationError to simplify the code dealing with validation of relation definitions.
As a nice bonus, errors reported for invalid relations come with `code` property set to `INVALID_RELATION_DEFINITION` now.
=> refactor(repository): introduce InvalidRelationError

packages/cli/generators/controller/index.js, packages/cli/generators/datasource/index.js, packages/cli/generators/model/index.js, packages/cli/generators/repository/index.js, packages/cli/generators/service/index.js, packages/cli/test/integration/generators/model.integration.js, packages/cli/test/integration/lib/base-generator.js
Add more checks to make sure CLI fails fast. For example, if `--config` has an invalid value/file, we should abort before further prompting.
=> fix(cli): add more exit checks to fail fast

packages/repository/src/query.ts
An improvement I found possible while looking at the code :)
=> perf(repository): prevent multiple array allocation

docs/site/index.md
In the [LB4 docs main page](https://loopback.io/doc/en/lb4/), remove the note about LB4 is still in early development and is not yet released.
=> docs: update LB4 status

packages/repository-json-schema/src/build-schema.ts, packages/repository-json-schema/test/unit/build-schema.unit.ts
Working on improving the JSON schema output in general, but just commiting a simple first fix to see how the contributor process is.
Fixing the missing "description" property on the property level (it's already supported on the model level)
=> Add property description to JSON schema

packages/rest/src/rest.application.ts, packages/rest/src/rest.server.ts, packages/rest/test/acceptance/routing/routing.acceptance.ts, packages/rest/test/integration/rest.server.integration.ts, packages/rest/test/unit/rest.server/rest.server.open-api-spec.unit.ts
Move the implementation of 4-arg version of "route` method from RestApplication to RestServer, simplify RestApplication's "route" to delegate the implementation to RestServer.
=> feat(rest): push route(verb, path, spec, fn) down to RestServer

docs/site/HasMany-relation.md
Just a typo in the import of hasMany
=> docs: fix hasMany typo

packages/rest/src/router/routing-table.ts, packages/rest/test/unit/rest.server/rest.server.open-api-spec.unit.ts
Add `x-visibility` extension property to OpenAPI spec.
Addresses https://github.com/strongloop/loopback-next/issues/1874.
=> feat: add 'x-visibility' extension property to OpenAPI spec

packages/repository/src/model.ts, packages/repository/src/query.ts, packages/repository/src/relations/belongs-to/belongs-to.decorator.ts, packages/repository/src/relations/has-many/has-many.decorator.ts, packages/repository/src/relations/has-many/has-many.repository.ts, packages/repository/src/repositories/kv.repository.ts, packages/repository/src/repositories/legacy-juggler-bridge.ts, packages/repository/src/repositories/repository.ts
This PR fix typos, missing parameters or bad names in the tsdoc of the repository package :smiley:
=> docs(repository): fix tsdoc

packages/boot/src/booters/booter-utils.ts
https://github.com/nodejs/node/issues/20278 was solved so Object.entries/values can now be used.
=>  style(boot): remove workaround warning comment 

docs/site/Deploying-to-IBM-Cloud.md
Add link to cloudant dashboard in example. I had to google how to access the dashboard so
having the link would be useful.
=> docs: add link to cloudant dashboard

packages/rest/package.json
Fixes #1917
Blank items above because there are no code changes in this PR
Ideally would like this to say, logically, "pull in whatever version of `serve-static` is used by `express`", but I'm not sure how to do that.
I've tried to verify this with my problem project where I found the issue, but I can't get `pnpm` to play nice with linked packages in the context of the rush monorepo.  That said, the imports I've added here are exactly the same ones I added to that parent project as a workaround, so I'm _reasonably_ confident this should work.
Note that only including `@types/express-serve-static-core` and not the base `express-serve-static-core` is quite intentional and a bit important -- see the issue report for why.
=> fix(rest): don't rely on transitive dependencies from express

examples/hello-world/index.js, examples/soap-calculator/index.js, examples/todo-list/index.js, examples/todo/index.js, packages/cli/generators/app/templates/index.js.ejs, packages/cli/test/integration/generators/app.integration.js
This PR only applies the options object in the application to benefit the app developer in two areas:
1. For new developers change the application port number with ease
2. Avoid the step to specify the server url + port number when used by OASGraph _(if not used, then I believe it won't hurt? )_
This pull request supersedes #1900.
=> refactor(cli): use options to specify port and OpenAPI server url

docs/site/Decorators.md, docs/site/Decorators_inject.md, docs/site/Decorators_openapi.md, docs/site/Decorators_route.md, docs/site/Deploying-to-IBM-Cloud.md, docs/site/Model.md, docs/site/sidebars/lb4_sidebar.yml, examples/soap-calculator/README.md
Related to https://github.com/strongloop/loopback-next/issues/1908
A quick pass on the LB4 docs.  
- mostly number formatting. It appears all `1.` in the docs
- Remove "work in progress" note at the top of the [Model docs page](https://loopback.io/doc/en/lb4/Model.html).
=> docs: fix number formatting

packages/cli/generators/datasource/index.js, packages/cli/generators/repository/index.js, packages/cli/lib/utils.js, packages/cli/test/fixtures/repository/index.js, packages/cli/test/integration/generators/datasource.integration.js, packages/cli/test/integration/generators/repository.integration.js
The problem was reported by Sam Ruby.
1. `lb4 datasource` to add a DS with `loopback-connector-sqlite3`
2. `lb4 repository` fails to list `loopback-connector-sqlite3` as it's NOT on the list of connectors we pull from `loopback-workspace`
=> fix(cli): allow other connectors to be used for repositories

packages/rest/src/http-handler.ts, packages/rest/src/rest.server.ts, packages/rest/src/router/router-base.ts, packages/rest/src/router/routing-table.ts, packages/rest/test/integration/rest.application.integration.ts, packages/rest/test/integration/rest.server.integration.ts
Optimize serving static files
See #1784 and #1785
=> fix: optimize serving static files

docs/site/Parsing-requests.md, packages/openapi-v3/src/decorators/request-body.decorator.ts, packages/rest/package.json, packages/rest/src/keys.ts, packages/rest/src/parser.ts, packages/rest/src/providers/parse-params.provider.ts, packages/rest/src/rest-http-error.ts, packages/rest/src/router/routing-table.ts, packages/rest/src/types.ts, packages/rest/src/validation/request-body.validator.ts, packages/rest/test/integration/http-handler.integration.ts, packages/rest/test/unit/parser.unit.ts, packages/rest/test/unit/request-body.validator.test.ts, packages/rest/test/unit/rest.server/rest.server.open-api-spec.unit.ts
See https://github.com/strongloop/loopback-next/issues/1797
=> feat(rest): add support for form request body

docs/site/Server.md
Add docs to configure `CORS` for rest servers.
=> docs: add configuration for CORS

packages/build/bin/run-mocha.js, packages/build/bin/utils.js, packages/build/config/mocha.opts, packages/build/mocha.opts, packages/build/test/integration/scripts.integration.js
After generating a new loopback 4 project with cli generator, a new `mocha.opts` file is created by default. When I run the `npm test` command, all options defined in the `mocha.opts` file should be loaded. This PR loads your default built-in mocha options only if the corresponding parameter `--use-default-options` is added to the `npm test` command.
If this logic is accepted, all affected packages should be modified accordingly. I look forward to knowing from you which of them should I update.
=> refactor(build): honors project mocha.opts file

docs/site/BelongsTo-relation.md, examples/todo-list/src/repositories/todo.repository.ts, packages/repository/src/decorators/model.decorator.ts, packages/repository/src/relations/belongs-to/belongs-to.decorator.ts, packages/repository/src/relations/has-many/has-many.decorator.ts, packages/repository/src/relations/relation.decorator.ts, packages/repository/test/fixtures/repositories/order.repository.ts, packages/repository/test/unit/decorator/relation.decorator.unit.ts
The current implementation uses property names as the key of
relations and it's not compatible with legacy juggler.
See https://github.com/strongloop/loopback-next/issues/1909
=> fix(repository): build relations based on their names

packages/rest/test/integration/http-handler.integration.ts
Based on a test failure reported for https://github.com/strongloop/loopback-next/pull/1955 by AppVeyor in https://ci.appveyor.com/project/strongloop/loopback-next/builds/19978953/job/nioktpbi7frhc0xx, it looks like Windows can emit `ECONNRESET` instead of `EPIPE`.
This commit is fixing our test implementation to treat `ECONNRESET` the same way as `EPIPE` and ignore it in the relevant tests.
=> test(rest): fix connection reset errors in tests

packages/cli/generators/controller/index.js, packages/cli/generators/datasource/index.js, packages/cli/generators/model/index.js, packages/cli/generators/openapi/index.js, packages/cli/generators/repository/index.js, packages/cli/generators/service/index.js, packages/cli/lib/artifact-generator.js, packages/cli/lib/base-generator.js, packages/cli/lib/project-generator.js
=> fix(cli): set glob options to support windows paths with special chars

benchmark/src/rest-routing/README.md, benchmark/src/rest-routing/routing-table.ts, packages/rest/src/router/route-sort.ts, packages/rest/src/router/routing-table.ts, packages/rest/src/router/trie.ts, packages/rest/test/unit/router/route-sort.unit.ts, packages/rest/test/unit/router/trie-router.unit.ts
1. Handle overlapping paths with different vars
For example:
- GET /users/{id}/products
- GET /users/{id}
- GET /users/{userId}/orders
The issue was discovered with https://github.com/strongloop/loopback4-example-shopping/pull/23
2. Improve route sorting to group by path and verb. 
For example:
```
{verb: 'get', path: '/orders/count'},
{verb: 'get', path: '/orders/{id}/exists'},
{verb: 'put', path: '/orders/{id}'},
{verb: 'patch', path: '/orders/{id}'},
{verb: 'get', path: '/orders/{id}'},
{verb: 'delete', path: '/orders/{id}'},
{verb: 'post', path: '/orders'},
{verb: 'patch', path: '/orders'},
{verb: 'get', path: '/orders'},
{verb: 'delete', path: '/orders'},
{verb: 'get', path: '/users/{userId}/orders'},
{verb: 'get', path: '/users/{id}/products'},
{verb: 'get', path: '/users/{id}'}, …
```
=> Fix trie routing

packages/rest/test/unit/router/route-sort.unit.ts
See https://bugs.chromium.org/p/v8/issues/detail?id=90
It replaces https://github.com/strongloop/loopback-next/pull/1985
=> fix(rest): make sure the sorting test pass for node 11

docs/site/Database-migrations.md, docs/site/sidebars/lb4_sidebar.yml
Connect to #1547.
Added documentation for `automigrate()` and `autoupdate()` and added link to sidebar.
=> Doc: Auto-Migration and Auto-Update Documentation

bin/update-template-deps.js, packages/build/bin/utils.js, packages/build/package.json, packages/context/test/unit/value-promise.unit.ts, packages/openapi-v3/src/controller-spec.ts
=> chore: update prettier to 1.15.1

packages/authentication/src/keys.ts, packages/authentication/src/providers/auth-metadata.provider.ts
Use decorators index when importing
=> refactor(authentication): simplify decorators import path

docs/site/BelongsTo-relation.md, docs/site/DataSources.md, docs/site/Defining-the-API-using-code-first-approach.md, docs/site/Getting-started.md, docs/site/HasMany-relation.md, docs/site/Model.md, docs/site/Repositories.md, docs/site/Using-components.md, docs/site/todo-list-tutorial-controller.md, docs/site/todo-list-tutorial-model.md, docs/site/todo-list-tutorial-repository.md, docs/site/todo-tutorial-geocoding-service.md, docs/site/todo-tutorial-putting-it-together.md, docs/site/todo-tutorial-repository.md, docs/site/todo-tutorial-scaffolding.md, examples/todo-list/README.md, examples/todo/README.md
Connect to #1908 and #1828. 
Minor fixes in the documentation for the TodoList example, including adding `lb4 repository` command, and other miscellaneous updates.
=> docs: update todolist doc

docs/site/Creating-components.md, packages/context/src/binding.ts, packages/context/src/context.ts, packages/context/test/unit/context.unit.ts, packages/core/src/component.ts, packages/core/test/unit/application.unit.ts
Reactivation of https://github.com/strongloop/loopback-next/pull/929
- Improve the component design to allow contribution of various bindings
- Introduce a `@component` decorator to mark a component class (inspired by https://docs.nestjs.com/modules)
A component class can be declared as follows:
```ts
@component({
controllers: [MyController],
bindings: [binding],
classes: {'my-class': MyClass},
providers: {'my-provider': MyProvider},
})
class MyComponent implements Component {
bindings = [];
constructor() {
// Dynamically add more bindings
this.bindings.push(...);
}
}
```
=> feat(core): improve component bindings

docs/site/exposing-graphql-apis.md
Now that oasgraph has separated into 2 modules: `oasgraph` and `oasgraph-cli`, we're updating our docs for https://loopback.io/doc/en/lb4/exposing-graphql-apis.html accordingly.
=> docs: update OASGraph instructions

.gitignore, bin/build-docs-site.sh, docs/bin/copy-readmes.js, docs/package.json
Add a script to copy per-package README files `docs/site/readmes`, run it as part of the release process.
This enhancement simplifies the process of including new READMEs in the documentation rendered at https://loopback.io, supersedes https://github.com/strongloop/loopback.io/pull/767 and makes loopback.io's script `update-v4-readmes.sh` pretty much obsolete.
To keep things simple, I am copying READMEs from almost all packages, even though those READMEs are not used yet. Skipped packages:
- `@loopback/docs`
- `@loopback/benchmark`
- everything starting with `@loopback/sandbox-`
See also https://github.com/strongloop/loopback-next/pull/2014 which will greatly benefit from this change. …
=> build(docs): include READMEs from all packages at publish time

examples/todo-list/index.js
Originated from https://github.com/strongloop/loopback-next/issues/2029#issuecomment-438806289
@dougal83 reported that the GraphQL tutorial won't work for todo-list example.  It is because the index.js in the `todo-list` example does not take in the config as parameter in https://github.com/strongloop/loopback-next/blob/master/examples/todo-list/index.js#L22
It should be the same as the index.js in the `todo` example: https://github.com/strongloop/loopback-next/blob/master/examples/todo-list/index.js#L22
=> fix: todo-list example index.js

docs/site/BelongsTo-relation.md, docs/site/HasMany-relation.md
This brings the documentation inline with the https://loopback.io/doc/en/lb4/BelongsTo-relation.html. 
When using `hasMany` and `belongsTo` together, it's important to use string based class names to break the cyclic dependency.
=> Docs: Break cyclic dependency for hasMany

packages/cli/lib/base-generator.js, packages/cli/test/integration/lib/artifact-generator.js
See https://github.com/strongloop/loopback-next/issues/2028
=> fix(cli): allow `*` for version range

examples/soap-calculator/package.json, examples/todo-list/package.json, examples/todo/package.json, packages/cli/package.json, packages/rest-explorer/package.json
Set `rest-explorer` version to `1.0.0` so that we can publish its 1st release.
=> chore(rest-explorer): set rest-explorer version to 1.0.0

docs/site/Deploying-to-IBM-Cloud.md
In the [IBM Cloud deployment guide](https://loopback.io/doc/en/lb4/Deploying-to-IBM-Cloud.html), the image links are broken.  
It is because the relative path that the image refers to will bring it to: https://loopback.io/doc/en/lb4/imgs/deploytocloud-mycloudant.png, where the actual image is found in https://loopback.io/pages/en/lb4/imgs/deploytocloud-mycloudant.png.
=> docs: fix image links in Cloud Deployment guide

packages/http-server/src/http-server.ts, packages/http-server/test/integration/http-server.integration.ts
To create a sockio server from the HttpServer, we need to access the
underlying http/https server.
See https://github.com/raymondfeng/loopback4-example-websocket/blob/master/src/websocket.server.ts
=> feat(http-server): exposes underlying http server before start

docs/site/Controllers.md, docs/site/Decorators_authenticate.md, docs/site/Decorators_inject.md, docs/site/Decorators_openapi.md, docs/site/Decorators_repository.md, docs/site/Defining-the-API-using-design-first-approach.shelved.md, docs/site/OpenAPI-generator.md, docs/site/Repositories.md, docs/site/Testing-Your-Extensions.md, docs/site/soap-calculator-tutorial-add-datasource.md, docs/site/soap-calculator-tutorial-add-service.md, docs/site/todo-list-tutorial-controller.md, docs/site/todo-list-tutorial-model.md, docs/site/todo-list-tutorial-repository.md, docs/site/todo-tutorial-datasource.md, docs/site/todo-tutorial-geocoding-service.md, examples/todo-list/src/controllers/todo-list-todo.controller.ts
Connect to https://github.com/strongloop/loopback-next/issues/1994. 
Changed file name captions to match the `{% include code-caption.html content="..." %}` format. Also, fixed small doc issue in the `TodoList` example and small fix to filter function for `TodoListTodoController`.
=> docs: fix file name captions

docs/site/How-tos.md, docs/site/sidebars/lb4_sidebar.yml
Rename "How tos" to "How-tos", I find "How tos" as difficult to read.
Add a new page `docs/site/How-tos.md` and use it to back "How-tos"
section. Before this change, both "How-tos" and "Key concepts" were
sharing the same section page, which was confusing.
=> fix(docs): create a new page for How-tos sidebar section

docs/site/DEVELOPING.md
There are a few similar tasks on "Contributing to LoopBack", e.g. https://github.com/strongloop/loopback-next/issues/1673.
This PR is to make `DEVELOPING.md` show up in the contribute side bar. 
https://loopback.io/doc/en/contrib/code-contrib.html
It has been ran locally.  (Thanks @b-admike and @nabdelgadir!)
=> docs: make DEVELOPING.md to be part of docs

docs/site/todo-tutorial-controller.md, docs/site/todo-tutorial-datasource.md, docs/site/todo-tutorial-model.md
When running the `todo` or `todo-list` example, if I choose to use a relational database as datasource instead of the in-memory database, I will need to create the table.  As a new user, it might not be trivial. 
In this PR, I've added a note to remind users to have the table created or follow the [database migration docs](https://loopback.io/doc/en/lb4/Database-migrations.html).
=> docs: add note to create table in todo example

packages/rest/src/router/openapi-path.ts, packages/rest/src/router/trie.ts, packages/rest/test/unit/router/openapi-path.unit.ts, packages/rest/test/unit/router/routing-table.unit.ts, packages/rest/test/unit/router/trie.unit.ts
See https://github.com/strongloop/loopback-next/issues/1866
=> fix(rest): allow `.` to be used in openapi path template

docs/site/Database-migrations.md, examples/todo/src/migrate.ts, packages/repository/src/datasource.ts, packages/repository/src/mixins/repository.mixin.ts, packages/repository/test/unit/mixins/repository.mixin.unit.ts
I find the current instructions for database migration as too involved for practical use, for example when running our example applications against a real database (SQL, MongoDB). I would like to propose a better user experience as a short-term solution to scratch this itch. Please see https://github.com/strongloop/loopback-next/issues/487 for the discussion about a more comprehensive solution for long term.
In this pull request, I am introducing new APIs to simplify database migrations:
- ~~A new interface `MigrateableRepository` describing repositores that know how to migrate their database schema.~~
- A new Application-level method `app.migrateSchema()` provided by `RepositoryMixin` and running schema migration provided by all registered ~~repositories~~ datasources under the hood. …
=> Easy-to-use database migrations at application level

docs/site/Model-generator.md, docs/site/OpenAPI-generator.md, packages/cli/generators/model/index.js
Connect to https://github.com/strongloop/loopback-next/issues/1842.
Added brief descriptions to `Model` and `Entity` in the model generator and in the model generator doc. Also, made the links in the `OpenAPI Generator` page hyperlinked.
How it looks:
=> fix: add model/entity descriptions

docs/site/Database-migrations.md, examples/todo-list/package.json, examples/todo-list/src/migrate.ts, examples/todo/package.json, packages/cli/generators/app/templates/src/migrate.ts.ejs, packages/cli/generators/project/templates/package.json.ejs, packages/cli/generators/project/templates/package.plain.json.ejs, packages/cli/test/integration/generators/app.integration.js
As a follow-up for https://github.com/strongloop/loopback-next/pull/2059:
- Add a template of `migrate.ts` to `lb4 app` generator. All new app project will be created with `src/migrate.ts` now.
- Further extend `lb4 app` generator to include the following npm/package script:
```
"migrate": "node ./dist/src/migrate"
```
- Apply these changes to `examples/todo` and `examples/todo-list`
- Update `Database migrations` documentation page accordingly.
=> feat: scaffold DB migration script for new app projects

benchmark/tsconfig.build.json, examples/hello-world/tsconfig.build.json, examples/log-extension/tsconfig.build.json, examples/rpc-server/tsconfig.json, examples/soap-calculator/tsconfig.build.json, examples/todo-list/tsconfig.build.json, examples/todo/tsconfig.build.json, package.json, packages/authentication/test/unit/strategy-adapter.unit.ts, packages/authentication/tsconfig.build.json, packages/boot/tsconfig.build.json, packages/build/README.md, packages/build/config/tsconfig.common.json, packages/build/package.json, packages/cli/generators/project/templates/tsconfig.json.ejs, packages/context/tsconfig.build.json, packages/core/tsconfig.build.json, packages/http-caching-proxy/tsconfig.build.json, packages/http-server/tsconfig.build.json, packages/metadata/tsconfig.build.json, packages/openapi-spec-builder/tsconfig.build.json, packages/openapi-v3-types/tsconfig.build.json, packages/openapi-v3/tsconfig.build.json, packages/repository-json-schema/tsconfig.build.json, packages/repository/src/query.ts, packages/repository/tsconfig.build.json, packages/rest-explorer/tsconfig.build.json, packages/rest/tsconfig.build.json, packages/service-proxy/tsconfig.build.json, packages/testlab/tsconfig.build.json
See https://blogs.msdn.microsoft.com/typescript/2018/11/29/announcing-typescript-3-2/
=> chore(build): upgrade to TypeScript 3.2.1

docs/site/DEVELOPING.md
VSCode Documentation link was broken, fixed that to point to correct URL
=> docs: fixed broken links to VSCODE documentation

docs/site/Server.md, packages/rest/src/keys.ts, packages/rest/src/rest.application.ts, packages/rest/src/rest.server.ts, packages/rest/test/integration/rest.application.integration.ts, packages/rest/test/integration/rest.server.integration.ts, packages/rest/test/unit/rest.server/rest.server.unit.ts
See https://github.com/strongloop/loopback-next/issues/918
Some deviation from #918:
- The `basePath` is only available as part of `RestServerConfig` because we set up express routes within the constructor.
- The `basePath` only applies to registered routes (including static assets)
- `servers` in openapi spec are adjusted accordingly
=> feat(rest): allow basePath for rest servers

docs/site/Binding.md, docs/site/Concepts.md, docs/site/Context.md, docs/site/sidebars/lb4_sidebar.yml, packages/context/src/binding.ts, packages/context/test/unit/binding.unit.ts
It allows a binding to be configured using a template function that can consistently set up bindings for certain scope/tags.
For example,
```ts
const serverTemplate = (binding: Binding) =>
binding.inScope(BindingScope.SINGLETON).tag('server');
const serverBinding = new Binding<RestServer>('servers.RestServer1');
serverBinding.apply(serverTemplate);
```
=> feat(context): add binding.apply(templateFn)

docs/site/OpenAPI-generator.md, packages/cli/generators/openapi/index.js, packages/cli/generators/openapi/schema-helper.js, packages/cli/generators/openapi/spec-helper.js, packages/cli/generators/openapi/spec-loader.js, packages/cli/generators/openapi/templates/src/models/model-template.ts.ejs, packages/cli/generators/openapi/templates/src/models/type-template.ts.ejs, packages/cli/test/integration/generators/openapi-uspto-with-anonymous.integration.js, packages/cli/test/unit/openapi/controller-spec.unit.js, packages/cli/test/unit/openapi/schema-model.unit.js
This PR adds `--promote-anonymous-schemas` option to map anonymous schemas in OpenAPI specs to LoopBack 4 models. Without the flag, we generate such schemas as TypeScript type literals.
=> feat(cli): allow annonymous schemas in openapi to be mapped to models

examples/todo-list/src/models/todo-list-image.model.ts, examples/todo-list/src/repositories/index.ts, examples/todo-list/src/repositories/todo-list-image.repository.ts, examples/todo-list/test/acceptance/todo-list-image.acceptance.ts, examples/todo-list/test/helpers.ts, packages/repository/src/relations/belongs-to/belongs-to.decorator.ts, packages/repository/src/relations/has-one/has-one-repository.factory.ts, packages/repository/src/relations/has-one/has-one.repository.ts, packages/repository/test/acceptance/has-one.relation.acceptance.ts, packages/repository/test/fixtures/models/address.model.ts, packages/repository/test/fixtures/repositories/address.repository.ts, packages/repository/test/unit/decorator/model-and-relation.decorator.unit.ts, packages/repository/test/unit/repositories/has-one-repository-factory.unit.ts
Remove attempt at guaranteeing the foreign key of a has one relation to be unique by using it
as the primary key of the target model. This allow users to set up their own unique contstraints. @RaphaelDrai FYI (what I mentioned in https://github.com/strongloop/loopback-next/pull/2005#issuecomment-445991523)
Motivation:
>@bajtos @raymondfeng and I had a discussion and since the memory connector and cloudant connector do not support unique indexes, we've decided to have the first release of hasOne provide "weak" relations i.e. ease of navigation and aggregation instead of enforcement of referential integrity and document it so users are aware of the limitations. 
TODO: docs for the `hasOne` relation (most likely in another PR, so we can do a release).
=> fix(repository): revert hasOne target FK as PK implementation

docs/site/Binding.md, packages/context/docs.json, packages/context/src/binding-decorator.ts, packages/context/src/binding-inspector.ts, packages/context/src/binding.ts, packages/context/src/context.ts, packages/context/src/index.ts, packages/context/src/keys.ts, packages/context/test/acceptance/bind-decorator.acceptance.ts, packages/context/test/acceptance/binding-decorator.feature.md, packages/context/test/unit/binding-decorator.test.ts, packages/context/test/unit/binding-inspector.test.ts, packages/core/src/application.ts, packages/repository/src/mixins/repository.mixin.ts, packages/service-proxy/src/mixins/service.mixin.ts
This PR is a reactivation of https://github.com/strongloop/loopback-next/pull/992.
=> feat(context): add `@bind` to decorate classes with binding attributes

packages/repository/test/acceptance/has-one.relation.acceptance.ts, packages/rest/src/rest.server.ts
The rule "no-unused-variable" is messing up with TypeScript compiler state and as a result, other rules don't detect certain violations.
In this commit, I am fixing few violations I discovered when I have temporarily disabled no-unused-variable rule.
=> chore: fix tslint violations

packages/build/bin/run-mocha.js, packages/build/bin/utils.js, packages/build/src/fail-on-console-logs.js
CI fails on Windows. See:
https://ci.appveyor.com/project/strongloop/loopback-next/builds/21019237
This PR adds a flag to suppress Node.js warnings per:
https://medium.com/@jasnell/introducing-process-warnings-in-node-v6-3096700537ee
=> chore: suppress node.js warnings to have clean logs

packages/tslint-config/package.json
Turn on the public config for module tslint-config
=> fix: make the tslint-config repo public

packages/build/bin/utils.js
Fix the algorithm looking up CLI paths to correctly detect CLIs present in the target package.
The old version was overloading the same variable `path` with two different values (a string path, a built-in `path` module), throwing an error as a result and thus always falling back to the version bundled inside `@loopback/build`.
I discovered the problem while working on #2156.
=> fix(build): fix path lookup in build helpers

examples/rpc-server/src/index.ts
`main` function is calling two times which trying to re-binding of port on `app.start()` call.
Fixes #2191
=> fix: remove multiple application start calls

docs/site/Testing-your-application.md
Proposed update on how to add a repository getter to a repository definition in case of relation.
As discussed in this issue #1922 
Removed checklist because no code was changed.
=> Add example add repository getter to testing docs

docs/site/includes/CLI-std-options.md
According to [CLI docs](https://loopback.io/doc/en/lb4/Application-generator.html), one of the ways to use `--config` is:
```
lb4 app --config {"name":"my-app"}
```
I've tried it on Mac and it didn't work.  It works for me with quotes added, i.e. 
```
lb4 app --config '{"name":"my-app"}'
```
=> fix(docs): fix example for using --config option

packages/authentication/src/providers/auth-metadata.provider.ts, packages/authentication/test/unit/providers/auth-metadata.provider.unit.ts
static endpoint like the homepage in the shopping example doesn't have a controller, thus the metadata injected for the auth action should be optional.
Related to https://github.com/strongloop/loopback4-example-shopping/pull/26
=> fix: optional auth metadata

docs/site/Preparing-the-API-for-consumption.shelved.md
Use Markdown image tags for LB4 docs.
The `{% include image.html file="lb4/10000000.png" alt="" %}` format is a legacy remnant from the time when LoopBack docs were hosted using Confluence. 
I considered the possibility of replacing all the instances of `{% include image.html }` tag with Markdown tags, but they are way too may in older docs. Replacing them may have unforeseen side-effects, so left them alone.
Good thing is, there were only three instances in the LB4 docs.
=> docs: use markdown image tags

docs/site/DEVELOPING.md, packages/cli/generators/example/index.js
Connect to https://github.com/strongloop/loopback-next/issues/2175.
Renamed the `tsconfig.build.ts` files in the examples to `tsconfig.ts` because, when using the examples from the `lb4 example` command, they weren't extending [`tsconfig.common.json`](https://github.com/strongloop/loopback-next/blob/master/packages/build/config/tsconfig.common.json) until after the rename. They also now match the [`rpc-server`](https://github.com/strongloop/loopback-next/blob/master/examples/rpc-server/tsconfig.json) example.
=> refactor: rename tsconfig.build files in examples

packages/cli/lib/base-generator.js, packages/cli/test/integration/generators/controller.integration.js, packages/cli/test/integration/generators/datasource.integration.js, packages/cli/test/integration/generators/model.integration.js, packages/cli/test/integration/lib/artifact-generator.js, packages/cli/test/test-utils.js
When the CLI performed an artifact generation, it would validate that the CLI's current working directory was a directory in which a Loopback application is installed. In order to do this, it looked at the package.json's "keywords" section and looked to see if the "loopback" keyword was present in that section. So that we do not have to force users to have the "loopback" keyword in their package.json, we can simply check the package.json dependencies to make sure that the `@loopback/core` package is installed. 
Fixes #2163
=> refactor: remove dependency of package.json keywords

packages/cli/test/acceptance/app-run.acceptance.js
See e.g. https://travis-ci.org/strongloop/loopback-next/builds/478157375
=> test(cli): increate test timeout to prevent CI build failures

docs/site/Decorators_repository.md
Connect to https://github.com/strongloop/loopback-next/issues/1910.
Add syntax and examples to `belongsTo`, `hasOne`, and `hasMany` decorator docs.
=> docs: add specific relation decorators

docs/site/BelongsTo-relation.md
PR for #2118  Update document for recursive `belongsTo` relationship.
Fixes #2118
=> docs: update document for recursive belongsTo relationship

docs/site/Model-generator.md, docs/site/Model.md, docs/site/todo-list-tutorial-model.md, docs/site/todo-tutorial-model.md, packages/cli/generators/model/index.js, packages/cli/generators/model/templates/model.ts.ejs, packages/cli/test/integration/generators/model.integration.js
Connect to https://github.com/strongloop/loopback-next/issues/1530.
Add a prompt to model generator that asks the user if they want to allow additional properties (disable the `strict` setting). And add `modelSettings` to `this.artifactInfo` in `ModelGenerator` that contains settings such as `strict`.
=> feat(cli): add strict prompt to model generator

packages/repository-json-schema/test/integration/build-schema.integration.ts, packages/repository/src/relations/has-many/has-many.decorator.ts, packages/repository/test/acceptance/has-many.relation.acceptance.ts, packages/repository/test/unit/decorator/relation.decorator.unit.ts
…y relation inconsistency
Fix for issue #1944 - Create related model in hasMany relation inconsistency
fix #1944
=> fix(repository): remove property.array() call from hasMany decorator

packages/cli/lib/project-generator.js
Connect to https://github.com/strongloop/loopback-next/issues/2251.
When checking for which settings to enable, the `settings` variable: https://github.com/strongloop/loopback-next/blob/master/packages/cli/lib/project-generator.js#L198 is either equal to `props.settings` which includes the long version of the names 
```
[ 'Enable tslint: \u001b[90madd a linter with pre-configured lint rules\u001b[39m',
'Enable prettier: \u001b[90madd new npm scripts to facilitate consistent code formatting\u001b[39m',
'Enable mocha: \u001b[90minstall mocha to assist with running tests\u001b[39m',
'Enable loopbackBuild: \u001b[90muse @loopback/build helpers (e.g. lb-tslint)\u001b[39m',
'Enable vscode: \u001b[90madd VSCode config files\u001b[39m',
'Enable repositories: \u001b[90minclude repository imports …
```
=> fix(cli): change enable setting check

packages/cli/generators/model/index.js, packages/cli/test/integration/generators/model.integration.js
When using `lb4 model --config` option, if the json file I passed in contains `base` attribute/class, it gives an error saying `Model was not found`.   In a previous version of `@loopback/cli`, it was working with the following json as stated in https://github.com/strongloop/loopback-next/issues/1517#issuecomment-433522659:
```
{
"name": "Customer",
"base": "Entity",
"properties": {
"id": {
"type": "number",
"id": true,
"required": false
},
"name": {
"type": "string",
"length": 200,
"id": false,
"required": true
}
}
}
```
It is caused by the check being incorrect in this line:  https://github.com/strongloop/loopback-next/blob/master/packages/cli/generators/model/index.js#L131
cc @b-admike 
Fixes https://github.com/strongloop/loopback-next/issues/2257
=> fix(cli): allow base class exist for model config option

packages/openapi-v3/test/unit/filter-schema.unit.ts, packages/repository-json-schema/src/filter-json-schema.ts
enumerate properties of the Entity in the schema of the fields filter
=> feat(repository-json-schema): enumerate fields

packages/build/package.json, packages/context/src/binding-decorator.ts
Upgrade prettier to 1.16.1 and reformat code to avoid CI failure.
=> chore(build): upgrade prettier to 1.16.1

packages/cli/README.md
Connect to https://github.com/strongloop/loopback-next/issues/2269.
Add `lb4 respository`. `lb4 service`, and `lb4 openapi` to CLI package's README.
=> docs: add more commands to cli readme

docs/site/FAQ.md, docs/site/LoopBack-3.x.md, docs/site/Preparing-the-API-for-consumption.shelved.md
When looking up some information, I found out some broken links and irrelevant information.  
In this PR, I'm proposing to remove links that no longer exist or relevant.
=> docs: remove broken links

docs/site/todo-tutorial-geocoding-service.md
This pull request supersedes https://github.com/strongloop/loopback-next/pull/1891, which seems to be abandoned.
=> fix(docs): update link in todo-tutorial-geocoding-service

docs/site/HasMany-relation.md, docs/site/hasOne-relation.md
Remove `.ts` from some imports due to:
=> fix(docs): remove .ts from imports

packages/repository/test/unit/repositories/relation.repository.unit.ts, packages/rest-explorer/test/acceptance/rest-explorer.acceptance.ts, packages/rest/test/unit/coercion/paramStringToNumber.unit.ts, packages/rest/test/unit/rest.component.unit.ts
See https://github.com/mochajs/mocha/pull/3550
=> chore: fix test cases to be compatible with mocha@6.x

packages/cli/generators/repository/templates/src/repositories/repository-crud-default-template.ts.ejs
VSCode complains about the unused `juggler` import in a `repository` generated from the CLI. `juggler` was used before as `juggler.DataSource` which was changed into `dataSourceClassName` (see [commit](https://github.com/strongloop/loopback-next/commit/26915e5762f9bad48010ee3506b671c8ebf43ac6#diff-0dddf087a0acac6ac658913bb40c3128L10) where it was changed).
=> fix: remove unused juggler import

packages/cli/generators/repository/index.js, packages/cli/generators/repository/templates/src/repositories/repository-crud-default-template.ts.ejs, packages/cli/generators/repository/templates/src/repositories/repository-kv-template.ts.ejs, packages/cli/test/fixtures/repository/index.js, packages/cli/test/fixtures/repository/repositories/defaultmodel.repository.base.ts, packages/cli/test/integration/generators/repository.integration.js
Allow the user to specify a custom Repository class to inherit from.
CLI supports custom repository name
* via an interactive prompt
* via CLI options
* via JSON config
Two tests modified to use the new parameter to pass
Modified tests:
* generates a kv repository from default model
* generates a kv repository from decorator defined model
=> feat(cli): use a custom repository base class

packages/rest/src/__tests__/unit/body-parser.unit.ts, packages/rest/src/__tests__/unit/parse-json.unit.ts, packages/rest/src/body-parsers/body-parser.json.ts, packages/rest/src/coercion/coerce-parameter.ts, packages/rest/src/index.ts, packages/rest/src/parse-json.ts
Fixes https://github.com/strongloop-internal/scrum-apex/issues/409
=> fix(rest): sanitize json for JSON.parse()

docs/site/Crafting-LoopBack-4.md
See https://github.com/strongloop/loopback-next/issues/2020
This PR is a quick fix in the `Crafting in LoopBack` page for the broken link. 
As suggested by @bajtos, we'll create a dedicated Component page as a longer term fix. 
See https://github.com/strongloop/loopback-next/issues/2020#issuecomment-461822363.
=> fix(docs): broken link in Crafting in LB

docs/site/Context.md, packages/context/package.json, packages/context/src/__tests__/unit/context-observer.unit.ts, packages/context/src/__tests__/unit/context.unit.ts, packages/context/src/context-observer.ts, packages/context/src/context.ts, packages/context/src/index.ts, packages/rest/package.json, packages/rest/src/request-context.ts
Spin-off from #2122 
- Add support for context to emit bind and unbind events
- Allow observers to register with the context chain and respond to come and go of bindings of interest
Followed-up PRs:
#2122 (depends on #2291)
- Introduce ContextView to dynamically resolve values of matching bindings
- Introduce @inject.view to support dependency injection of multiple bound values
- Extend @inject and @inject.getter to support multiple bound values
#2249
- Add an example package to illustrate how to implement extension point/extension pattern using LoopBack 4’s IoC and DI container
#2259
- Propose new APIs for Context to configure bindings
- Add @inject.config to simplify injection of configuration
=> feat(context): introduce context events and observers for bind/unbind

packages/rest/src/__tests__/unit/router/routing-table.unit.ts, packages/rest/src/router/trie.ts
Fixes #2188 
This is a spin-off from #2355.
=> fix(rest): only return matched trie nodes with values

greenkeeper.json
Add `@types/node` to `ignore` list so that Greenkeeper skips PRs such as #2377.
=> chore: ignore @types/node upgrade by greenkeeper

packages/rest/src/__tests__/integration/express.integration.ts, packages/rest/src/rest.server.ts
See https://github.com/strongloop/loopback-next/pull/2306#discussion_r252321716
=> feat: allow rest-server to be mounted on a path to express

.github/PULL_REQUEST_TEMPLATE.md
Add 'Agreed to CLA' checkbox to Checklist and ask user to click url
Related to #2280 
A pre-condition to a pull request being approved is that the contributor read and agree to the CLA (contributor license agreement).
There should be a checkbox for this in the `Checklist` section of the pull request template, and it should be the first.
=> chore: add 'Agreed to CLA' checkbox to Checklist

docs/site/BelongsTo-relation.md
I think the type of customerId should be number, not string. Is it a typo mistake or it must be string?
=>  docs: change type of customerId property from string to number

packages/cli/generators/app/templates/src/__tests__/acceptance/test-helper.ts.ejs, packages/cli/test/integration/generators/app.integration.js
Fixes https://github.com/strongloop/loopback-next/issues/1995
=> fix(cli): force test host to be HOST env var or ipv4 interface

docs/site/Server.md, packages/rest/src/__tests__/unit/rest.server/rest.server.unit.ts, packages/rest/src/rest.server.ts
=> feat(rest): introduce requestBodyParser options in RestServerOptions

examples/todo-list/tsconfig.build.json
When running `todo-list` example using `npm start`, it throws the following error:
```
module.js:550
throw err;
^
Error: Cannot find module './dist'
at Function.Module._resolveFilename (module.js:548:15)
at Function.Module._load (module.js:475:25)
at Module.require (module.js:597:17)
at require (internal/module.js:11:18)
```
It seems like the `rootDir` in the tsconfig.json should be set to `src` instead of `.`.  The other examples, e.g. `todo` example, had been changed and seems like only this example has left out.
=> fix(example-todo-list): change rootDir in compilerOptions

.github/PULL_REQUEST_TEMPLATE.md
checkbox for 'Agree to CLA' was causing confusion, so the checkbox has been turned into a link instead.
=> chore: change sign cla checkbox to link

docs/site/Application-generator.md, packages/cli/generators/app/index.js, packages/cli/generators/app/templates/.dockerignore, packages/cli/generators/app/templates/Dockerfile, packages/cli/generators/app/templates/index.js.ejs, packages/cli/generators/project/templates/package.json.ejs, packages/cli/generators/project/templates/package.plain.json.ejs, packages/cli/lib/project-generator.js, packages/cli/test/integration/generators/app.integration.js
This PR adds a `docker` option for `lb4 app` cli to generate:
- Dockerfile
- .dockerignore
- Add `docker:build` and `docker:run` scripts to `package.json`
=> feat(cli): add `--docker` option to generate docker files

docs/site/soap-calculator-tutorial-add-controller.md, docs/site/soap-calculator-tutorial-add-datasource.md, docs/site/soap-calculator-tutorial-add-service.md, docs/site/soap-calculator-tutorial-run-and-test.md, docs/site/soap-calculator-tutorial-web-service-overview.md, examples/soap-calculator/src/__tests__/acceptance/application.acceptance.ts, examples/soap-calculator/src/__tests__/integration/services/calculator.service.integration.ts, examples/soap-calculator/src/controllers/calculator.controller.ts, examples/soap-calculator/src/datasources/calculator.datasource.json, examples/soap-calculator/src/services/calculator.service.ts
Fixes #2444. 
The hosted server is a deployment of https://github.com/raymondfeng/calculator-webservice on my account@IBM Cloud using CF.
See https://calculator-webservice.mybluemix.net/calculator
=> fix(example-soap-calculator): switch to a new soap calculator webservice

packages/rest-explorer/package.json, packages/rest-explorer/src/__tests__/acceptance/rest-explorer.express.acceptance.ts, packages/rest-explorer/src/rest-explorer.controller.ts
This is a follow-up to https://github.com/strongloop/loopback-next/pull/2387. It makes sure REST explorer also honors the `baseUrl`.
=> fix(rest-explorer): allow explorer for a rest app to be mounted to express

docs/site/Server.md, packages/rest/src/__tests__/unit/rest.server/rest.server.unit.ts, packages/rest/src/rest.server.ts
Add a new rest configuration for `queryParser`
Fixes #2420
=> feat(rest): allow assigning express settings

README.md, docs/site/Application-generator.md, docs/site/Download-examples.md, docs/site/FAQ.md, docs/site/soap-calculator-tutorial-scaffolding.md, docs/site/submitting_a_pr.md, docs/site/todo-tutorial-putting-it-together.md, docs/site/todo-tutorial-scaffolding.md
Quick docs clean up (including updating `Examples-and-tutorials` link to reflect change).
=> chore(docs): clean up

packages/rest-explorer/src/rest-explorer.controller.ts
Simplify the code building redirect location to leverage [`req.originalUrl`](https://expressjs.com/en/4x/api.html#req.originalUrl provided by Express.
=> refactor(rest-explorer): use request.originalUrl when available

docs/site/Decorators_openapi.md
Fixes a broken link to model decorators
This document : https://loopback.io/doc/en/lb4/Decorators_openapi.html
has a link
which is broken.
It most likely needs to link to:
https://loopback.io/doc/en/lb4/Model.html#model-decorator
=> docs: fix a broken link to model decorators

examples/todo-list/src/__tests__/acceptance/todo-list-todo.acceptance.ts, packages/repository/src/__tests__/unit/mixins/repository.mixin.unit.ts, packages/repository/src/mixins/repository.mixin.ts
First phase fix for https://github.com/strongloop/loopback-next/issues/2495
This is a spin-off from #2499 to provide the first phase for #2495 by changing the binding scope of repositories to `TRANSIENT`.
=> fix(repository): change default binding scope to TRANSIENT for repos

docs/site/express-with-lb4-rest-tutorial.md, examples/express-composition/package.json, examples/express-composition/src/server.ts
Removed `prepublishOnly` script and starting the `note` app (it starts without the explicit call). And updated name from `express-composition` to `@loopback/example-express-composition`. 
=> fix(example-express-composition): remove prepublishOnly and lbApp.start() and fix example's name

docs/site/Routes.md, packages/rest/src/__tests__/acceptance/routing/routing.acceptance.ts, packages/rest/src/__tests__/integration/rest.application.integration.ts, packages/rest/src/__tests__/integration/rest.server.integration.ts, packages/rest/src/__tests__/unit/rest.server/rest.server.redirect.unit.ts, packages/rest/src/rest.application.ts, packages/rest/src/rest.server.ts, packages/rest/src/router/index.ts, packages/rest/src/router/redirect-route.ts
Implement a new class RedirectRoute to provide redirection from a given URL path to a new URL path.
Add RestServer and RestApplication methods for defining redirect routes:
```ts
redirect(fromPath: string, toPathOrUrl: string, statusCode?: number);
```
This pull request supersedes #2314, see also #2022
=> feat(rest): add support for redirect routes

benchmark/package.json, examples/express-composition/package.json, examples/rpc-server/package.json, packages/http-caching-proxy/package.json, packages/http-server/package.json
As of `p-event@3.0.0`, type definitions are shipped as part of the package itself.
This is a follow-up for #2521 that upgraded `p-event` to v3.
@raymondfeng feel free to land this PR yourself if it LGTY.
=> chore: remove dependency on `@types/p-event`

packages/rest/src/rest.server.ts, packages/rest/src/router/external-express-routes.ts, packages/rest/src/router/index.ts, packages/rest/src/router/routing-table.ts
Refactor the code handling static assets routes to make it open to extension and allow adding additional types of external routes later in the (near) future.
This commit is a pure refactoring. The only visible change is removal of `StaticAssetsRoute` from the public API.
See #2389 and the PoC in #2318.
=> refactor(rest): rework StaticAssetsRoute into ExternalExpressRoutes

packages/cli/generators/app/templates/src/__tests__/acceptance/test-helper.ts.ejs, packages/cli/test/integration/generators/app.integration.js, packages/http-server/src/__tests__/integration/http-server.integration.ts, packages/testlab/src/__tests__/unit/http-server-config.test.ts, packages/testlab/src/http-server-config.ts
#1995 modified the project template to use the following configuration for HTTP server host & port:
```ts
const config = givenHttpServerConfig();
// Set host to `HOST` env var or ipv4 loopback interface
// By default, docker container has ipv6 disabled.
config.host = config.host || process.env.HOST || '127.0.0.1';
// Set port to `PORT` env var or `0`
config.port = config.port || +(process.env.PORT || 0);
```
I find such approach problematic.
1. Acceptance tests are sort of self-contained. Both the server and the client are running in the same Node.js process and the server is running only for the duration of the test suite. There is no need to expose the server to public by honoring HOST/PORT environment variables.
2. By honoring HOST/PORT environment variables, we can actually break the …
=> Improve HTTP server config used by tests

packages/boot/src/__tests__/unit/mixins/boot.mixin.unit.ts, packages/boot/src/bootstrapper.ts, packages/boot/src/mixins/boot.mixin.ts
The PR introduces two minor enhancements to booter class bindings.
1. Honor `@bind` for booter classes
2. Bind booter classes using `SINGLETON` scope by default
=> fix(boot): improve booter bindings

packages/service-proxy/src/__tests__/acceptance/service.mixin.acceptance.ts, packages/service-proxy/src/__tests__/unit/mixin/service.mixin.unit.ts, packages/service-proxy/src/mixins/service.mixin.ts
=> fix(service-proxy): change default binding scope to TRANSIENT for service proxies

docs/site/express-with-lb4-rest-tutorial.md, examples/express-composition/src/server.ts
See https://github.com/strongloop/loopback-next/pull/2306#discussion_r262027071.
Updating the `express-composition` example to use the `host` and `port` from `ApplicationConfig`.
=> fix(example-express-composition): use rest options

docs/site/Examples.md, docs/site/Getting-started.md, docs/site/express-with-lb4-rest-tutorial.md, docs/site/soap-calculator-tutorial-scaffolding.md, docs/site/todo-tutorial-scaffolding.md, packages/cli/README.md
CLI options and their descriptions were updated in [this commit](https://github.com/strongloop/loopback-next/commit/4cd24424f6ec937a3308b8e3c542677e5e59618f), so this an update to the docs to match. I disabled the `docker` option on the examples because the examples don't have docker files. Also, fixed the levels of the `express-composition`'s docs. 
=> docs: update cli options and descriptions

packages/cli/generators/controller/index.js
When using the command `lb4 controller -h`, I noticed that in the arguments it said:
```
Arguments:
name  # Name for the undefined  Type: String  Required: false
```
This was because for the controller, it was setting up the generator before attaching the properties (e.g. [`this.artifactInfo.type`](https://github.com/strongloop/loopback-next/blob/master/packages/cli/lib/artifact-generator.js#L26)) causing them to be undefined. I changed it to call `_setupGenerator()` after attaching the properties (similar to what [`model`](https://github.com/strongloop/loopback-next/blob/master/packages/cli/generators/model/index.js#L90), [`datasource`](https://github.com/strongloop/loopback-next/blob/master/packages/cli/generators/datasource/index.js#L60), …
=> fix(cli): setup controller generator after adding properties

docs/site/express-with-lb4-rest-tutorial.md, docs/site/todo-list-tutorial-repository.md, docs/site/todo-tutorial-repository.md
Update examples to include repository base class prompt from https://github.com/strongloop/loopback-next/pull/2235.
=> docs: add repository base class

examples/express-composition/index.d.ts, examples/express-composition/package.json, examples/express-composition/src/__tests__/acceptance/note.acceptance.ts, examples/express-composition/src/application.ts, examples/express-composition/src/server.ts, examples/express-composition/tsconfig.build.json
Removed `files` from `package.json` of `express-composition` example so the correct files download when using `lb4 example express-composition`. Then changed the `express-composition` example based on how it's done in https://github.com/strongloop/loopback-next/pull/2316 so they're included when running `npm test` at the root of `loopback-next`.
=> update express-composition example's npm files and include the example in `npm test`

docs/site/Server.md, packages/rest/src/__tests__/unit/rest.server/rest.server.unit.ts, packages/rest/src/__tests__/unit/router/routing-table.unit.ts, packages/rest/src/__tests__/unit/router/trie-router.unit.ts, packages/rest/src/keys.ts, packages/rest/src/rest.server.ts, packages/rest/src/router/regexp-router.ts, packages/rest/src/router/rest-router.ts, packages/rest/src/router/router-base.ts, packages/rest/src/router/trie-router.ts
This PR replaces https://github.com/strongloop/loopback-next/pull/2355.
It introduces `strict` option for REST routers to deal with trailing slashes.
1. `strict` is true:
- request `/orders` matches route `/orders` but not `/orders/`
- request `/orders/` matches route `/orders/` but not `/orders`
2. `strict` is false (default)
- request `/orders` matches route `/orders` first and falls back to `/orders`
- request `/orders/` matches route `/orders/` first and falls back to `/orders`
=> feat(rest): add strict option for routers

docs/site/Context.md, packages/context/src/__tests__/unit/context-view.unit.ts, packages/context/src/context-view.ts
Extension points that use ContextView can then listen on events to update
its state/cache beyond the view accordingly.
=> feat(context): add events to ContextView

docs/site/Binding.md, packages/context/src/__tests__/acceptance/bind-decorator.acceptance.ts, packages/context/src/__tests__/unit/binding.unit.ts, packages/context/src/binding-inspector.ts, packages/context/src/binding.ts, packages/core/src/__tests__/unit/application.unit.ts, packages/core/src/application.ts, packages/repository/src/__tests__/unit/mixins/repository.mixin.unit.ts, packages/repository/src/mixins/repository.mixin.ts, packages/rest/src/__tests__/acceptance/bootstrapping/rest.acceptance.ts, packages/service-proxy/src/__tests__/unit/mixin/service.mixin.unit.ts
The PR improves binding attributes as follows:
- Refine visibility for binding attributes
- Introduce `defaultScope` to only override binding scope if not set
Use case:
If a class is decorated with `@bind({scope: BindingScope.SINGLETON})`, we should honor it and not override it with a default scope. For example:
```
@bind({scope: BindingScope.SINGLETON})
class MyController {}
app.controller(MyController); // My controller should be bound as SINGLETON
```
=> feat(context): honor binding scope from @bind

benchmark/package.json, examples/rpc-server/package.json, packages/authentication/package.json, packages/boot/package.json, packages/core/package.json, packages/http-caching-proxy/package.json, packages/metadata/package.json, packages/openapi-v3/package.json, packages/repository-json-schema/package.json, packages/rest/package.json, packages/service-proxy/package.json, packages/testlab/package.json
Update package.json for all packages to use a consistent glob pattern for tests.
=> chore: use a simpler pattern for npm test to run all tests

packages/repository/src/__tests__/acceptance/has-many.relation.acceptance.ts, packages/repository/src/__tests__/fixtures/models/customer.model.ts, packages/repository/src/__tests__/fixtures/repositories/customer.repository.ts, packages/repository/src/__tests__/fixtures/repositories/order.repository.ts
Resolves https://github.com/strongloop/loopback-next/issues/1571. 
Added tests to test the `Customer` model having many `Customers`.
=> test(repository): hasMany relation to same entity

.vscode/settings.json
With this change in place, VSCode will automatically organize imports on every save, thus keeping imports consistently ordered.
=> chore: automatically organize imports on save in VS Code

packages/repository/src/__tests__/unit/decorator/relation.decorator.unit.ts, packages/repository/src/relations/belongs-to/belongs-to.decorator.ts
allow optional property definition on belongsTo decorator as property decorator can not applied twice
Fixes #2345
Fixes #2256
=> feat(repository): allow optional property definition on belongsTo decorator

README.md, docs/site/Calling-other-APIs-and-Web-Services.md
Fixes https://github.com/strongloop/loopback-next/issues/1766
The [Calling other APIs docs page](https://loopback.io/doc/en/lb4/Calling-other-APIs-and-web-services.html) is updated because we no longer need to manually install `@loopback/service-proxy`.  Instead, we can use `lb4 service`. 
The code snippets and instructions are verified with my repo: https://github.com/dhmlau/loopback4-external-apis.  
-----
Since we no longer need to install `@loopback/service-proxy` manually and can use `lb4 service` instead, I'm updating this doc: https://loopback.io/doc/en/lb4/Calling-other-APIs-and-web-services.html. 
_I think_ my changes can be generalized to be used for calling REST APIs as well, just that the datasource generation will be different.  Will need some work on that. 
This is currently …
=> fix(docs): add steps to call SOAP services

packages/repository/src/__tests__/acceptance/has-one.relation.acceptance.ts, packages/repository/src/relations/has-one/has-one.repository.ts, packages/repository/src/relations/has-one/index.ts
implemented the missing crud operations delete, patch and put operations
in relation hasOne.
"fix #2233"
=> feat(repository): delete & patch operations for HasOne relation

packages/build/config/tsconfig.common.json, packages/cli/generators/project/templates/tsconfig.json.ejs
- Disable type checking of declaration files.
Declaration files are typically shipped by our dependencies, we cannot apply our compiler checks (e.g. noImplicitAny) on them.
- Remove "dom" from the list of global libraries.
Historically, we were including "dom" because it was required by `supertest`'s type declarations to pass the compilation. Now that we are not type-checking declaration files, we don't need "dom" library any more.
Please note that "dom" library is for HTML/Browser environment only, no Node.js code should be depending on DOM types, e.g. the global `Request` object provided by browsers. …
=> build: enable "skipLibCheck", remove "dom" library

packages/context/src/__tests__/unit/binding-inspector.unit.ts, packages/context/src/binding-inspector.ts, packages/context/src/keys.ts
This fixes an issue discovered for #2249. It now allows `namespace` tag to customize class bindings.
```ts
@bind({tags: {namespace: 'services'}})
class MyService () {
}
const binding = createBindingFromClass(MyService);
// binding.key is now `services.MyService`
``` 
=> feat(context): allow namespace tag for createBindingFromClass

packages/rest/src/__tests__/integration/rest.server.integration.ts, packages/rest/src/rest.server.ts, packages/testlab/src/client.ts
RestServer.url does not reflect `basePath`. The problem can be reproduced by adding basePath: '/api' to [examples/todo/index.js](https://github.com/strongloop/loopback-next/blob/master/examples/todo/index.js#L15) and run `npm build`:
The url is printed as http://127.0.0.1:3000, which returns 404. I think the url should include the basePath, i.e., 'http://127.0.0.1:3000/api'.
See https://github.com/strongloop/loopback-next/pull/2554#issuecomment-471089213
=> fix(rest): make sure basePath is included in RestServer.url

docs/site/Routes.md, docs/site/express-with-lb4-rest-tutorial.md, packages/rest/src/__tests__/integration/rest.application.integration.ts, packages/rest/src/__tests__/unit/router/assign-router-spec.unit.ts, packages/rest/src/__tests__/unit/router/rebase-openapi-spec.unit.ts, packages/rest/src/rest.application.ts, packages/rest/src/rest.server.ts, packages/rest/src/router/external-express-routes.ts, packages/rest/src/router/index.ts, packages/rest/src/router/router-spec.ts, packages/rest/src/router/routing-table.ts
Closes https://github.com/strongloop/loopback-next/issues/2389.
Add `mountExpressRouter` to `RestApplication` and `RestServer` and include in `Routes.md`.
=> feat(rest): add mountExpressRouter

bin/check-package-locks.js, package.json, sandbox/example/.npmrc, sandbox/example/package-lock.json
- Add a new script `bin/check-package-lock.js` to verify that local monorepo dependencies are excluded from package-lock files.
- Run this script as part of `npm run lint`.
- Fix `sandbox/example` package - add `.npmrc` to enable package-lock feature, remove a monorepo-local references from `sandbox/examples/package-lock.json`.
My intention is to prevent accidental addition of monorepo-local references to package locks, see https://github.com/strongloop/loopback-next/pull/2650#pullrequestreview-219976910
- Documentation in [/docs/site](../tree/master/docs/site) …
=> build: add script to check package-lock files

packages/context/src/__tests__/unit/binding.unit.ts, packages/context/src/binding.ts, packages/context/src/context.ts, packages/context/src/resolution-session.ts, packages/rest/src/__tests__/acceptance/routing/routing.acceptance.ts
Extracted from #2635:
Make sure binding cache is cleared if the binding is bound to a new value provider or scope
- The binding instance may cache values for contexts based on the scope
- If an existing binding changes its value provider or scope, the cache should be invalidated.
=> fix(context): clear binding cache upon scope/getValue changes

MAINTAINERS.md, docs/MAINTAINING.md
Add `MAINTAINING.md` for maintainers' guide. 
Some of the contents are coming from the email content when we're inviting maintainers, regarding the benefits, expectation and responsibilities.  
=> docs: add MAINTAINING.md for maintainers guide

.github/PULL_REQUEST_TEMPLATE.md
Add 'How to submit a pull request (PR) for LoopBack 4' link to the PR template
=> chore: add 'submit pr' link to pr template

packages/http-server/package-lock.json, packages/http-server/package.json, packages/http-server/src/__tests__/integration/http-server.integration.ts
See #2672.
This pull request is removing `request` from dev-dependencies of `@loopback/http-server`. The only test using that module is reworked to use `httpGetAsync` from Node.js core instead.
=> refactor(http-server): remove "request" module from tests

docs/site/Binding.md, packages/context/src/__tests__/unit/binding.unit.ts, packages/context/src/binding.ts
A few improvements for `@loopback/context` related to #2259 
- Add `binding.toAlias()`
Use case:
```ts
ctx.bind('parent.options').to({child: {disabled: true}});
ctx.bind('child.options').toAlias('parent.options#child');
const childOptions = ctx.getSync('child.options');
expect(childOptions).to.eql({disabled: true});
```
Related to #2657 
Depends on #2656 
=> feat(context): add `binding.toAlias()`

packages/repository/src/__tests__/unit/repositories/legacy-juggler-bridge.unit.ts, packages/repository/src/repositories/legacy-juggler-bridge.ts
Added execute implementation to the default repository class
Fixes #2165
=> feat(repository): add execute implementation

docs/site/Sequence.md
Resolves #2390:
> Describe request handling steps. Explain the order in which different middleware and route handlers are invoked in LB4, what extension points are provided.
=> docs: explain request handling phases and Express middleware

docs/site/Tutorials.md, docs/site/express-with-lb4-rest-tutorial.md, examples/express-composition/README.md, examples/soap-calculator/README.md, examples/todo-list/README.md, examples/todo/README.md, packages/cli/README.md
Add `greeter-extension` to docs that call `lb4 example`.
=> docs: add greeter-extension example to other example docs

packages/repository-json-schema/src/__tests__/integration/build-schema.integration.ts, packages/repository-json-schema/src/__tests__/unit/build-schema.unit.ts, packages/repository-json-schema/src/build-schema.ts, packages/repository/src/model.ts
We need to add additional attributes (AJV keywords) from PropertyDefinition so they will be written to openapi.json and we can use it as validation. Currently, only type, description, items (for arrays), and $ref are written (and a hard-coded format: 'date-time' for Date instances).
issue #2684
=> Refactor metaToJsonProperty to accept AJV keywords

packages/context/src/inject.ts, packages/context/src/resolution-session.ts
See the discussion in https://github.com/strongloop/loopback-next/pull/2704#discussion_r273005256
=> feat(context): always pass the session to ResolverFunction

packages/cli/generators/openapi/schema-helper.js, packages/cli/test/fixtures/openapi/3.0/customer.yaml, packages/cli/test/unit/openapi/schema-model.unit.js
Make sure item types referenced in `@property.array()` is imported in the generated model TypeScript source code.
=> fix(cli): make sure the item type is imported for an array in openapi spec

docs/site/Discovering-models.md, docs/site/Model.md, docs/site/sidebars/lb4_sidebar.yml, docs/site/tables/lb4-artifact-commands.html, packages/cli/README.md, packages/cli/generators/discover/index.js, packages/cli/generators/model/index.js, packages/cli/lib/artifact-generator.js, packages/cli/lib/cli.js, packages/cli/lib/model-discoverer.js, packages/cli/lib/update-index.js, packages/cli/package-lock.json, packages/cli/package.json, packages/cli/test/fixtures/discover/index.js, packages/cli/test/fixtures/discover/mem.datasource.js.txt, packages/cli/test/integration/cli/cli.integration.js, packages/cli/test/integration/generators/discover.integration.js, packages/cli/test/integration/generators/model.integration.js, packages/cli/test/integration/lib/file-check.js, packages/cli/test/test-utils.js
Adds the command `lb4 discover` command and its documentation.
The command has a `schemaDefs` option (the path to a file which contains a schema definition, or array of lb3 schema definitions) which overrides everything and simply creates the corresponding typescript file.  It's used for the integration test, and could also solve #2224
It's a piece of #2090
Implements #1921
=> Model Discovery

examples/greeter-extension/src/decorators.ts, packages/context/src/__tests__/unit/resolution-session.unit.ts, packages/context/src/__tests__/unit/resolver.unit.ts, packages/context/src/inject.ts, packages/context/src/resolver.ts
The `Injection` interface now has `metadata` as a required property. We always set `decorator` name internally.
=> feat(context): make Injection.metadata a required property

packages/cli/generators/openapi/schema-helper.js, packages/cli/generators/openapi/spec-helper.js, packages/cli/generators/openapi/utils.js, packages/cli/test/fixtures/openapi/3.0/customer.yaml, packages/cli/test/unit/openapi/controller-spec.unit.js, packages/cli/test/unit/openapi/openapi-utils.unit.js, packages/cli/test/unit/openapi/schema-model.unit.js
Fixing issues to generate code from OpenAPI specs from https://www.berlin-group.org/psd2-access-to-bank-accounts. Here is the [swagger doc](https://github.com/strongloop/loopback-next/files/3064625/berlin-group-swagger-2.yaml.txt).
=> fix(cli): improve openapi code generation for naming and typing

packages/context/src/__tests__/unit/resolver.unit.ts, packages/context/src/resolver.ts
Passes non-injected arguments from instantiateClass to resolveInjectedArguments for resolution.
Fixes #2727 
=> fix(context): instantiate class with non-injected arguments

docs/site/Decorators_inject.md, docs/site/Dependency-injection.md, packages/authentication/src/__tests__/unit/providers/authentication.provider.unit.ts, packages/context/src/__tests__/acceptance/class-level-bindings.acceptance.ts, packages/context/src/__tests__/unit/binding.unit.ts, packages/context/src/__tests__/unit/context.unit.ts, packages/context/src/binding.ts, packages/context/src/context.ts, packages/context/src/inject.ts
Extracted from https://github.com/strongloop/loopback-next/pull/2635
1. Allow `@inject.setter` to set other forms of value providers than constant
```ts
// Set the binding to a constant value, this is the current behavior
injectedSetter('my-value'); 
// or use the returned binding to configure it
const binding = injectedSetter();
binding.toClass(MyClass);
```
2. Allows `bindingCreation` option to control how the underlying binding is resolved/created.
=> feat(context): improve @inject.setter and add @inject.binding

examples/todo-list/src/__tests__/unit/controllers/todo-list.controller.unit.ts, examples/todo-list/src/__tests__/unit/controllers/todo.controller.unit.ts, examples/todo/src/__tests__/unit/controllers/todo.controller.unit.ts, packages/metadata/src/decorator-factory.ts, packages/metadata/src/reflect.ts
This pull requests contains first two commits from #2704. The changes are needed to pass TypeScript's `strictFunctionTypes` check.
=> Improve type safety of function calls

packages/authentication/README.md
broken link in the packages/authentication/README.md
=> doc: fix broken link in authentication

packages/cli/generators/openapi/schema-helper.js, packages/cli/generators/openapi/utils.js, packages/cli/test/integration/generators/openapi-petstore.integration.js, packages/cli/test/integration/generators/swagger-petstore.integration.js, packages/cli/test/unit/openapi/openapi-utils.unit.js, packages/cli/test/unit/openapi/schema-model.unit.js
Per our discussion at https://github.com/strongloop/loopback-next/pull/2722#discussion_r274373287, we need to maintain the property names as `@property` does not support name customization yet.
=> fix(cli): keep or escape property names for models

packages/context/src/binding-filter.ts, packages/context/src/context-view.ts, packages/context/src/context.ts
Fixes the `BindingFilter` generic typing as discovered by https://github.com/strongloop/loopback-next/pull/2704.
=> feat(context): fix generic typing for BindingFilter

packages/repository/src/__tests__/unit/repositories/constraint-utils.unit.ts, packages/repository/src/repositories/constraint-utils.ts
Consider a Product constraint like `{categoryId: 1}` and a request
to update (patch) Product with the following data:
{
name: 'updated',
categoryId: 1
}
Before this change, such request would be incorrectly rejected.
With this change in place, such requests are allowed.
Fixes #1719, resolves #2658 
/cc @foobarrrz 
=> fix: relax constrain check to allow input containing constrained values

packages/authentication/docs/authentication-strategy.md, packages/authentication/src/types.ts
Introduce an authentication strategy interface
Implements #2466 
=> feat: introduce an authentication strategy interface

docs/site/BelongsTo-relation.md, docs/site/HasMany-relation.md, docs/site/Relations.md, docs/site/hasOne-relation.md
Documented hasMany/belongsTo/hasOne limitations for NoSQL databases.
Addresses https://github.com/strongloop/loopback-next/issues/2340.
=> docs: document hasMany/belongsTo/hasOne limitations for NoSQL databases

benchmark/src/benchmark.ts, packages/build/config/tsconfig.common.json, packages/context/src/context-view.ts, packages/core/src/lifecycle.ts, packages/repository/src/__tests__/unit/type-resolver.unit.ts
Enable all "strict" checks with the exception of `strictPropertyInitialization` which would require significant changes.
The following additional checks are added:
- noImplicitThis
- alwaysStrict
- strictFunctionTypes
In the future, any checks added to TypeScript "strict" mode will be automatically enabled for LoopBack projects too.
See also [TypeScript Compiler Options](https://www.typescriptlang.org/docs/handbook/compiler-options.html) …
=> feat(build): add more TypeScript "strict" checks

docs/site/Loopback-component-authorization.md, docs/site/sidebars/lb4_sidebar.yml
Add documentation specifying guidelines on creating an authorisation component
Related #538
=> docs: add guideline doc for authorize component

packages/rest/src/__tests__/integration/rest.application.integration.ts
Added a test to verify that `mountExpressRouter` mounts the router on top of a `RestApplication`'s `basePath`.
=> test(rest): add express router on top of basePath test

examples/soap-calculator/src/__tests__/integration/services/calculator.service.integration.ts
We observe that timeouts happen for the soap calculator example integration test.
=> chore(example-soap-calculator): increase timeout for integration tests

packages/repository-json-schema/src/__tests__/integration/build-schema.integration.ts, packages/repository-json-schema/src/build-schema.ts
Fixes https://github.com/strongloop/loopback-next/issues/2628
The solution here is a little bit different than the proposal in the original issue:
- Ignore this item. ~The `definitions` contains both `Category` and `Product`.(This is not true) So that~
```
...
properties: {
category: {
$ref: '#/definitions/Category',
},
},
...
```
~refers to a valid definition entry.~
- The `visited` field is ~an array~ a set tracks the title of visited items instead of caching the schema. This is because `getJsonSchema` is called during each iteration of the property schema generation, not after the completed model schema(without definitions) get built. …
=> fix(repository-json-schema): resolve the circular reference

packages/cli/generators/openapi/index.js, packages/cli/generators/openapi/spec-helper.js, packages/cli/generators/openapi/templates/src/controllers/controller-template.ts.ejs, packages/cli/generators/openapi/templates/src/models/model-template.ts.ejs, packages/cli/generators/openapi/templates/src/models/type-template.ts.ejs, packages/cli/generators/openapi/utils.js, packages/cli/test/fixtures/openapi/3.0/customer.yaml, packages/cli/test/integration/generators/openapi-uspto-with-anonymous.integration.js, packages/cli/test/unit/openapi/controller-spec.unit.js, packages/cli/test/unit/openapi/openapi-utils.unit.js
1. Escape `/*` and `*/` inside `description` for generated code comments.
2. Use `_requestBody` to avoid tslint shadowed name complaints
=> fix(cli): escape char sequences for javascript comments

docs/site/Extension-point-and-extensions.md, docs/site/sidebars/lb4_sidebar.yml, examples/greeter-extension/README.md, examples/greeter-extension/index.js, examples/greeter-extension/package.json, examples/greeter-extension/src/__tests__/greeter-extension.acceptance.ts, examples/greeter-extension/src/application.ts, examples/greeter-extension/src/decorators.ts, examples/greeter-extension/src/greeting-service.ts, examples/greeter-extension/src/index.ts, examples/greeter-extension/src/keys.ts, examples/greeter-extension/src/types.ts, packages/core/src/__tests__/acceptance/extension-point.acceptance.ts, packages/core/src/extension-point.ts, packages/core/src/index.ts, packages/core/src/keys.ts
Add helper/decorator functions for extension point/extension pattern to `@loopback/core`.
=> feat(core): extension point/extension decorators and helper functions

packages/booter-lb3app/src/index.ts
Since the component is being used instead of the booter, export the component instead.
=> fix(booter-lb3app): export component instead of booter

benchmark/package-lock.json, benchmark/package.json, benchmark/src/benchmark.ts
`npm run build` fails on my local while passes on CI. Not sure is it my own problem, appreciate it if someone can test on their end.
```
> lb-tsc es2017 --outDir dist
npm WARN invalid config loglevel="notice"
benchmark/src/benchmark.ts(117,15): error TS2314: Generic type 'Emitter<EventName, EmittedType>' requires 2 type argument(s).
```
=> fix the emitter

packages/http-server/src/__tests__/integration/http-server.integration.ts, packages/http-server/src/http-server.ts
See https://github.com/strongloop/loopback-next/issues/2811
=> feat(http-server): add support for unix socket path

packages/booter-lb3app/src/__tests__/acceptance/booter-lb3app.acceptance.ts, packages/booter-lb3app/src/lb3app.booter.ts
LB3 models with `forceId: true` require request bodies for CREATE operations to exclude the primary key (id property), because the value is always generated by the database (e.g. as auto-incremented number, or as a UUID/GUID value).
This patch turns on a loopback-swagger feature flag to describe this constraint in the emitted Swagger spec. See the internal story https://github.com/strongloop-internal/scrum-asteroid/issues/283 and the following LB3 pull requests:
- strongloop/loopback-swagger#99
- strongloop/loopback-component-explorer#219
- strongloop/loopback-workspace#496
- strongloop/generator-loopback#319
- strongloop/loopback-cli#54
I tested the change using LB3 example application from https://github.com/strongloop/loopback-next/pull/2803.
The `create` endpoint for `User` model DOES …
=> feat(booter-lb3app): enable operation-scoped model schemas

packages/rest/src/__tests__/integration/rest.server.integration.ts, packages/rest/src/rest.server.ts
Send 302, instead of 308 for Swagger UI redirection.
Fixes https://github.com/strongloop/loopback-next/issues/2808
=> fix(rest): aggressive redirection to Swagger UI

packages/authentication/docs/authentication-system.md, packages/authentication/package-lock.json, packages/authentication/package.json, packages/authentication/src/__tests__/acceptance/basic-auth-extension.acceptance.ts, packages/authentication/src/__tests__/acceptance/basic-auth.acceptance.ts, packages/authentication/src/__tests__/acceptance/jwt-auth-extension.acceptance.ts, packages/authentication/src/__tests__/fixtures/helper.ts, packages/authentication/src/__tests__/fixtures/keys.ts, packages/authentication/src/__tests__/fixtures/sequences/authentication.sequence.ts, packages/authentication/src/__tests__/fixtures/services/basic-auth-user-service.ts, packages/authentication/src/__tests__/fixtures/services/jwt-service.ts, packages/authentication/src/__tests__/fixtures/strategies/basic-strategy.ts, packages/authentication/src/__tests__/fixtures/strategies/jwt-strategy.ts, packages/authentication/src/__tests__/fixtures/users/user.repository.ts, packages/authentication/src/__tests__/fixtures/users/user.ts, packages/authentication/src/__tests__/unit/providers/authentication.provider.unit.ts, packages/authentication/src/authentication.component.ts, packages/authentication/src/index.ts, packages/authentication/src/keys.ts, packages/authentication/src/providers/auth-action.provider.ts, packages/authentication/src/providers/auth-metadata.provider.ts, packages/authentication/src/providers/auth-strategy.provider.ts, packages/authentication/src/providers/index.ts, packages/authentication/src/services/token.service.ts, packages/authentication/src/services/user.service.ts, packages/authentication/src/types.ts
Resolve authentication strategies registered via extension point
Part of #2312
=> feat: resolve authentication strategy registered via extension point

docs/site/Components.md, docs/site/Concepts.md, docs/site/Using-components.md, docs/site/sidebars/lb4_sidebar.yml
Addresses https://github.com/strongloop/loopback-next/issues/2020.
=> docs: document Component

packages/boot/src/booters/base-artifact.booter.ts, packages/boot/src/interfaces.ts, packages/core/src/application.ts, packages/core/src/component.ts, packages/core/src/server.ts, packages/http-server/src/http-server.ts, packages/openapi-v3/src/decorators/request-body.decorator.ts, packages/openapi-v3/src/generate-schema.ts, packages/repository/src/type-resolver.ts, packages/rest/src/providers/parse-params.provider.ts, packages/rest/src/providers/send.provider.ts, packages/rest/src/rest.server.ts, packages/rest/src/router/external-express-routes.ts, packages/testlab/src/sinon.ts
Invalid block tags prevent api-documenter from generating apidocs.
Relates to #2834 
=> chore: fix invalid tsdoc tags in comments

packages/rest/src/__tests__/acceptance/routing/routing.acceptance.ts, packages/rest/src/__tests__/helpers.ts, packages/rest/src/__tests__/integration/http-handler.integration.ts, packages/testlab/README.md, packages/testlab/src/http-error-logger.ts, packages/testlab/src/index.ts
See https://github.com/strongloop/loopback-next/pull/2803#discussion_r280324582 for motivation.
Moving the `unexpectedHttpErrorLogger` from `@loopback/rest` to `@loopback/testlab` so it can be used for tests in other packages/examples.
=> refactor: move unexpectedHttpErrorLogger to testlab

packages/boot/src/booters/base-artifact.booter.ts, packages/boot/src/interfaces.ts
Follow-up fix for https://github.com/strongloop/loopback-next/pull/2836
=> chore(boot): fix tsdoc comments

packages/cli/generators/model/index.js, packages/cli/generators/model/templates/model.ts.ejs, packages/cli/package-lock.json, packages/cli/package.json, packages/cli/test/integration/generators/model.integration.js
Leverage stringify-object package to convert model settings object into well-formatted TypeScript source code.
An example of a simple settings object:
```ts
@model({settings: {strict: false}})
export class MyModel extends Entity {
// ...
}
```
A more complex example:
```ts
@model({
settings: {
annotations: [{destinationClass: 'class1', argument: 0}],
foreignKeys: {fk_destination: {name: 'fk_destination'}},
strict: false
}
})
export class MyModel extends Entity {
// ...
}
```
See #2604 /cc @yanamg7 …
=> feat(cli): improve scaffolding of complex model settings

packages/boot/src/booters/base-artifact.booter.ts
api-documenter has trouble handling `@link` and it complains about circular dependencies.
=> chore(boot): fix tsdoc comments so that apidocs can be generated

examples/log-extension/src/mixins/log.mixin.ts, packages/authentication/src/keys.ts, packages/authentication/src/services/user.service.ts, packages/boot/src/mixins/boot.mixin.ts, packages/context/src/binding-filter.ts, packages/context/src/binding-inspector.ts, packages/context/src/binding-key.ts, packages/context/src/binding.ts, packages/context/src/context.ts, packages/context/src/inject.ts, packages/core/src/application.ts, packages/core/src/component.ts, packages/core/src/extension-point.ts, packages/metadata/src/decorator-factory.ts, packages/openapi-v3/src/decorators/parameter.decorator.ts, packages/openapi-v3/src/decorators/request-body.decorator.ts, packages/repository/src/common-types.ts, packages/repository/src/decorators/repository.decorator.ts, packages/repository/src/mixins/repository.mixin.ts, packages/repository/src/model.ts, packages/repository/src/query.ts, packages/repository/src/repositories/legacy-juggler-bridge.ts, packages/repository/src/repositories/repository.ts, packages/rest/src/rest.application.ts, packages/rest/src/rest.server.ts, packages/rest/src/sequence.ts, packages/service-proxy/src/mixins/service.mixin.ts
Embedded typescript code in comments cannot be rendered correctly inside
markdown tables. Add @example to extract example code snippets.
=> chore: fix tsdoc comments for @example

packages/rest/src/__tests__/unit/router/assign-router-spec.unit.ts, packages/rest/src/router/router-spec.ts
When using `mountExpressRouter` to mount a LoopBack 3 application, the explorer complains when trying to do a `POST` request (for LB3 models), e.g.:
And this doesn't allow a `POST` (or similar) request to be made through the explorer:
By adding all of `component`'s properties, `components.requestBodies` will be added to the spec and this allows requests to be made through the explorer:
=> fix(rest): assign all component properties to target spec

packages/context/src/__tests__/unit/invocation-context.unit.ts, packages/context/src/interceptor.ts
Add more getters for `InvocationContext` as discovered during the development of `authorization` component using `Interceptor`.
See https://github.com/strongloop/loopback-next/pull/1205 
=> feat(context): add more getters for InvocationContext

packages/build/bin/compile-package.js
For example:
`src/__tests__/fixtures/my.conf` -> `dist/__tests__/fixtures/my.conf`
=> fix(build): honor tsconfig compilerOptions.rootDir to copy resources

packages/context/src/__tests__/unit/invocation-context.unit.ts, packages/context/src/interceptor.ts
Before this fix, `invocation context` is closed synchronously and interceptors may fail to resolve bindings in parent contexts.
=> fix(context): close invocation context only after async is done

packages/rest-explorer/src/__tests__/acceptance/rest-explorer.acceptance.ts, packages/rest-explorer/src/__tests__/acceptance/rest-explorer.express.acceptance.ts, packages/rest-explorer/src/rest-explorer.controller.ts
Endpoints serving OpenAPI spec ignore basePath setting, i.e. even if basePath is set to `/api`, the spec is served at `/openapi.json`.
This pull request is fixing the problem and supersedes #2554 and #2854.
The following four use cases are correctly supported now (when sending requests directly to the application):
1. No base path, everything is at `/`.
2. basePath is set via `app.basePath()`. Explorer is served at `/api/explorer`, OpenAPI spec is served at `/openapi.json`.
3. LB app mounted on Express at `/api`, no LB basePath is set. Explorer is served at `/api/explorer`, OpenAPI spec is served at `/api/openapi.json`.
4. LB app mounted on Express at `/api`, basePath is set to `v1`. Explorer is served at `/api/v1/explorer`, OpenAPI spec is served at `/api/openapi.json`.
Support for …
=> fix(rest-explorer): exclude basePath from /openapi URL

docs/site/Context.md, docs/site/Decorators_inject.md, packages/context/src/__tests__/acceptance/inject-multiple-values.acceptance.ts, packages/context/src/__tests__/unit/binding-sorter.unit.ts, packages/context/src/__tests__/unit/context-view.unit.ts, packages/context/src/binding-sorter.ts, packages/context/src/context-view.ts, packages/context/src/context.ts, packages/context/src/index.ts, packages/context/src/inject.ts, packages/context/src/interceptor.ts, packages/core/src/extension-point.ts, packages/core/src/lifecycle-registry.ts, packages/rest/src/body-parsers/body-parser.ts
This PR introduces BindingSorter to help sort bindings discovered from contexts. Some extension points need to control the order of bound extensions. Such APIs can be used to sort life cycle observers
and global interceptors after the PR is landed. 
It has two commits:
1. Add `BindingComparator` interface and a utility to sort by group tag.
2. Add support of `bindingComparator` for `ContextView` and `@inject.*`.
=> feat(context): add support to sort bindings for `@inject.*` and `ContextView`

packages/authentication/src/index.ts, packages/authentication/src/services/index.ts
Include user and token service interfaces
in ./service.index.ts and ./index.ts
While [refactoring the shopping cart application](https://github.com/strongloop/loopback4-example-shopping/pull/120) to use the latest [authentication package](https://github.com/strongloop/loopback-next/pull/2763), I noticed the newly added
user and token service interfaces in the services folder from the [feat: design auth system with user scenario PR](https://github.com/strongloop/loopback-next/pull/2576) weren't added to an index.ts in the 
services folder, and that the main index.ts doesn't include all exports from the ./services folder. 
Before the shopping application refactor PR lands, this PR (which updates to the @loopback/authenticate package) must land. …
=> refactor: include user and token service interfaces in index.ts

package-lock.json, package.json
Fix the vulnerabilities reported by `npm audit`
```
found 8 high severity vulnerabilities
run `npm audit fix` to fix them, or `npm audit` for details
jannyhous-mbp:loopback-next jannyhou$ npm audit fix
+ lerna@3.13.4
added 7 packages from 8 contributors, removed 8 packages, updated 20 packages and moved 1 package in 18.094s
fixed 8 of 8 vulnerabilities in 43076 scanned packages
jannyhous-mbp:loopback-next jannyhou$ npm audit fix
up to date in 3.403s
fixed 0 of 0 vulnerabilities in 42851 scanned packages
```
=> chore: fix vulnerability

packages/context/src/__tests__/acceptance/interceptor.acceptance.ts, packages/context/src/__tests__/unit/context.unit.ts, packages/context/src/context.ts, packages/rest/src/__tests__/integration/request-context.integration.ts, packages/rest/src/request-context.ts
Fixes https://github.com/strongloop/loopback-next/issues/2541
In some cases, the request context is still in use when the http response is finished. This PR changes `close` to only clear subscriptions and remove itself from the parent context so that the context is ready
for GC without destroying bindings.
=> feat(context): leave local bindings and parent unchanged in context.close()

docs/site/Testing-your-application.md, examples/todo/src/__tests__/unit/controllers/todo.controller.unit.ts
=> docs: add stub service section

docs/site/sidebars/lb4_sidebar.yml
Add the life cycle observer generator to the sidebar under CLI section https://loopback.io/doc/en/lb4/Command-line-interface.html
=> fix(docs): add life cycle observer cli to sidebar

packages/context/src/__tests__/acceptance/inject-multiple-values.acceptance.ts, packages/context/src/__tests__/unit/context-view.unit.ts, packages/context/src/context-view.ts, packages/context/src/context.ts, packages/context/src/inject.ts
Use `comparator` instead of `sorter` for parameter names to be consistent.
=> chore(context): use name comparator consistently

packages/openapi-v3/src/__tests__/integration/controller-spec.integration.ts, packages/openapi-v3/src/controller-spec.ts
Closes https://github.com/strongloop/loopback-next/issues/2629.
Controller methods can now reference model schema directly via OpenAPI spec and without using the `x-ts-type` extension
=> feat(openapi-v3): allow controller to reference models via openapispec

examples/lb3-application/lb3app/server/middleware.json
Fix configuration of Helmet middleware to remove the following warning:
hsts deprecated The "includeSubdomains" parameter is deprecated.
Use "includeSubDomains" (with a capital D) instead.
=> fix(example-lb3-application): remove deprecation warning

packages/repository/src/__tests__/unit/repositories/legacy-juggler-bridge.unit.ts, packages/repository/src/repositories/legacy-juggler-bridge.ts
Avoids an issue where it modifies the property definition in a way such that
it can't build a second juggler model from the same definition, e.g.  from
attaching the model to a second datasource.
Fixes #2912
:heavy_check_mark: 👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-next) 👈
=> fix(repository): always copy property definition during juggler model build (#2912)

packages/core/src/application.ts, packages/metadata/src/types.ts, packages/repository/src/type-resolver.ts, packages/service-proxy/src/legacy-juggler-bridge.ts, packages/testlab/src/sinon.ts
Use `@typeParam T - description` format.
=> chore: fix generic type param comments in tsdocs

packages/cli/generators/observer/templates/observer-template.ts.ejs, packages/cli/test/integration/generators/observer.integration.js
Fix typo/unused import in template for life cycle observers.
=> fix(cli): clean up template for life cycle observers

docs/site/Context.md, packages/context/src/__tests__/acceptance/binding-config.acceptance.ts, packages/context/src/__tests__/acceptance/binding-config.feature.md, packages/context/src/__tests__/acceptance/class-level-bindings.acceptance.ts, packages/context/src/__tests__/unit/context-config.unit.ts, packages/context/src/__tests__/unit/context-view.unit.ts, packages/context/src/__tests__/unit/context.unit.ts, packages/context/src/binding-config.ts, packages/context/src/binding-key.ts, packages/context/src/binding.ts, packages/context/src/context-view.ts, packages/context/src/context.ts, packages/context/src/index.ts, packages/context/src/inject-config.ts, packages/context/src/inject.ts, packages/context/src/keys.ts
Reactivation of #983 based on requirements illustrated by #2249.
1. Add context.configure() to configure bindings
2. Add context.getConfig/getConfigSync() to look up configuration for a binding
3. Add `@config`, `@config.getter`, and `@config.view` to receive injection of configuration
=> feat(context): add support for binding configuration and injection

packages/cli/test/acceptance/app-run.acceptance.js
Lerna v3.10.3 changed the way how `lerna bootstrap --scope` works, breaking our CLI tests when changes are made in dependencies of newly scaffolded projects. (As I discovered while working on https://github.com/strongloop/loopback-next/pull/2928).
This commit fixes the problem by adding `--force-local` option to restore previous behavior, see https://github.com/lerna/lerna/commit/71174e4709. Unfortunately, `--force-local` is broken now, we need to wait until https://github.com/lerna/lerna/pull/2104 is merged and released.
Also to make future troubleshooting easier, I am changing lerna log level used by the test from "silent" to "warn".
- API Documentation in code was …
=> test(cli): fix `lerna bootstrap` to link monorepo packages

packages/context/src/__tests__/acceptance/inject-multiple-values.acceptance.ts, packages/context/src/__tests__/integration/inject-view.integration.ts, packages/context/src/__tests__/integration/inject.integration.ts, packages/context/src/__tests__/unit/binding.unit.ts
Convert `describe` functions from async to sync.
I noticed this problem while experimenting with Jest, which does not support async describe blocks.
=> test: remove unnecessary async functions

docs/site/hasOne-relation.md
resolves https://github.com/strongloop/loopback-next/issues/2770
=> docs: update errors/typo in hasOne page

packages/context/src/__tests__/unit/binding.unit.ts, packages/context/src/__tests__/unit/invocation-context.unit.ts, packages/context/src/binding.ts, packages/context/src/interceptor.ts
1. InvocationContext.parent (public readonly)
2. Allow `optional` for binding without a value getter
=> Make invocation context parent public and fix optional binding resolution

packages/rest/src/router/external-express-routes.ts
Fixes the following build error on my local:
```
packages/rest/src/router/external-express-routes.ts(53,34): error TS2345: Argument of type 'Handler' is not assignable to parameter of type 'Application'.
Type 'Handler' is missing the following properties from type 'Application': init, defaultConfiguration, engine, set, and 61 more.
npm ERR! Darwin 17.7.0
npm ERR! argv "/Users/jannyhou/.nvm/versions/node/v10.15.3/bin/node" "/Users/jannyhou/node_modules/.bin/npm" "run" "build"
npm ERR! node v10.15.3
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! @loopback/benchmark@1.2.6 build: `lb-tsc es2017 --outDir dist`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @loopback/benchmark@1.2.6 build script 'lb-tsc es2017 --outDir dist'.
npm ERR! Make sure you have the latest version of …
```
=> fix: specify the type for handler

packages/rest/src/router/external-express-routes.ts
Revert https://github.com/strongloop/loopback-next/pull/2976
@jannyHou Please try the following:
```sh
cd loopback-next
npm run clean:lerna
rm -rf node_modules
npm i
npm run build
```
=> chore: revert https://github.com/strongloop/loopback-next/pull/2976

bin/build-docs-site.sh
Add `@loopback/docs` as a filter option when running `lerna bootstrap` for `loopback.io` in order to see changes in local docs package live after running `npm run build:site`.
=> fix: use symlinked docs package

packages/openapi-v3/src/__tests__/integration/controller-spec.integration.ts, packages/openapi-v3/src/controller-spec.ts, packages/openapi-v3/src/json-to-schema.ts, packages/repository-json-schema/src/__tests__/helpers/expect-valid-json-schema.ts, packages/repository-json-schema/src/__tests__/integration/build-schema.integration.ts, packages/repository-json-schema/src/__tests__/integration/schema-ref.integration.ts, packages/repository-json-schema/src/build-schema.ts, packages/rest/src/__tests__/acceptance/validation/validation.acceptance.ts
Introduce the following helpers:
- `getModelSchemaRef` returning OpenAPI spec
- `getJsonSchemaRef` returning JSON Schema
Example usage in controllers:
```ts
@get('/my', {
responses: {
'200': {
description: 'Array of MyModel model instances',
content: {
'application/json': {
schema: getModelSchemaRef(MyModel),
},
},
},
},
})
async find(): Promise<MyModel[]> {
// etc.
}
}
```
Resolve #2631.
See also #1352, #2652 and #2653. …
=> Helpers for building JSON/OpenAPI schema referencing shared definitions

packages/authentication/src/decorators/authenticate.decorator.ts
See discussion in https://github.com/strongloop/strongloop.com/pull/198#discussion_r287506418
Fix the type of `options` in the auth decorator. It should be `object` not `Object`. I didn't add a test case because when providing other types the code will have the red line warning in editor, before compiling.
=> fix(authentication): fix the options type in decorator

packages/cli/lib/base-generator.js, packages/cli/lib/cli.js, packages/cli/lib/model-discoverer.js, packages/context/src/context.ts, packages/core/src/application.ts, packages/metadata/src/reflect.ts, packages/repository/src/repositories/legacy-juggler-bridge.ts, packages/testlab/src/sinon.ts
=> chore: fix more @param comments in tsdocs

packages/cli/generators/discover/index.js, packages/cli/generators/model/index.js, packages/cli/lib/utils.js
modelSettings is stringified ahead of time to prevent `@settings([object object])`
Fixes #2915, see also #2953
=> fix: modelSettings is stringified properly #2915

packages/testlab/src/skip-travis.ts
Describe referenced Mocha types directly in testlab to avoid compile-time dependency on Mocha types, some of which are not compatible with Jest -- fix https://github.com/strongloop/loopback-next/issues/2452
Contents of `packages/testlab/dist/skip-travis.d.ts`:
**BEFORE**
```ts
/// <reference types="mocha" />
export declare type TestCallbackRetval = void | PromiseLike<any>;
/**
* Helper function for skipping tests on Travis env
* @param expectation
* @param callback
*/
export declare function itSkippedOnTravis(expectation: string, callback?: (this: Mocha.ITestCallbackContext, done: MochaDone) => TestCallbackRetval): void;
```
Notice `/// <reference types="mocha" />` which is the root cause of the problem reported in #2452
**AFTER**
```ts
export interface TestFn {
(this: TestContext): …
```
=> feat(testlab): rework itSkippedOnTravis to support Jest framework

examples/greeting-app/package-lock.json, examples/greeting-app/package.json, packages/build/package.json, packages/cli/package.json, packages/eslint-config/package.json
Please note that lerna promotes 1.0.0-1 to 1.0.0-2 instead of 1.0.0.
=> chore: use 1.0.0 instead of prereleases

docs/site/Sequence.md
=> docs: clean up WIP sections for sequence page

packages/cli/generators/project/templates/package.json.ejs, packages/cli/generators/project/templates/package.plain.json.ejs, packages/cli/test/integration/lib/project-generator.js
Some of eslint related dev dependencies are missing from generated project package.json files and it fails `npm test`.
The issue was not caught by our acceptance test as such deps happen to be available at `loopback-next` level and our generated app is in `loopback-next/sandbox`.
=> fix(cli): add eslint related dev dependencies to generated package.json

docs/site/Using-components.md
Removes unnecessary 'npm install @types/passport' command
after the 'npm install --save @loopback/authentication' command.
The authentication component no longer has a dependency
on the passport-based modules.
Related to : https://github.com/strongloop/loopback-next/issues/2940
=> docs: removes unnecessary 'npm install @types/passport' command

packages/cli/test/integration/lib/project-generator.js, packages/cli/test/unit/utils.unit.js, packages/context/src/__tests__/acceptance/class-level-bindings.acceptance.ts, packages/context/src/__tests__/unit/binding-sorter.unit.ts, packages/core/src/__tests__/unit/application.unit.ts, packages/eslint-config/eslintrc.js, packages/rest/src/__tests__/unit/rest.component.unit.ts
This pull request adds rules from eslint-config-loopback (see https://github.com/strongloop/eslint-config-loopback/blob/master/eslint.json) and fixes violations of these new rules (mostly mocha/no-identical-title).
This is a follow-up for #2492 which switched loopback-next from tslint to eslint.
=> chore: import eslint rules from eslint-config-loopback

bin/sync-dev-deps.js, examples/context/package-lock.json, examples/context/package.json, examples/express-composition/package-lock.json, examples/express-composition/package.json, examples/greeter-extension/package-lock.json, examples/greeter-extension/package.json, examples/greeting-app/package-lock.json, examples/greeting-app/package.json, examples/hello-world/package-lock.json, examples/hello-world/package.json, examples/lb3-application/package-lock.json, examples/lb3-application/package.json, examples/log-extension/package-lock.json, examples/log-extension/package.json, examples/rpc-server/package-lock.json, examples/rpc-server/package.json, examples/soap-calculator/package-lock.json, examples/soap-calculator/package.json, examples/todo-list/package-lock.json, examples/todo-list/package.json, examples/todo/package-lock.json, examples/todo/package.json, packages/build/package-lock.json, packages/build/package.json
Some of eslint related dev dependencies are missing from example projects.
=> chore: fix eslint related dev dependencies

packages/http-server/src/__tests__/integration/http-server.integration.ts, packages/rest/src/__tests__/integration/rest.server.integration.ts, packages/testlab/README.md, packages/testlab/src/skip-travis.ts
Introduce a generic helper `skipOnTravis` that supports arbitrary BDD verbs (`it`, `describe`, etc.) in a test-framework-agnostic way. Rework `itSkippedOnTravis` to leverage the new helper and deprecate it (in tsdocs only).
This is a follow-up for #3013.
=> feat(testlab): add generic helper `skipOnTravis`

docs/site/Interceptor-generator.md, docs/site/Interceptors.md, docs/site/sidebars/lb4_sidebar.yml, docs/site/tables/lb4-artifact-commands.html, examples/context/src/interceptor-proxy.ts, packages/boot/src/__tests__/fixtures/interceptor.artifact.ts, packages/boot/src/__tests__/fixtures/non-global-interceptor.artifact.ts, packages/boot/src/__tests__/integration/interceptor.booter.integration.ts, packages/boot/src/boot.component.ts, packages/boot/src/booters/index.ts, packages/boot/src/booters/interceptor.booter.ts, packages/cli/README.md, packages/cli/generators/interceptor/index.js, packages/cli/generators/interceptor/templates/interceptor-template.ts.ejs, packages/cli/lib/cli.js, packages/cli/lib/utils.js, packages/cli/test/fixtures/interceptor/index.js, packages/cli/test/integration/cli/cli.integration.js, packages/cli/test/integration/generators/interceptor.integration.js, packages/context/src/__tests__/acceptance/interceptor.acceptance.ts, packages/context/src/__tests__/unit/interceptor.unit.ts, packages/context/src/interceptor.ts, packages/context/src/keys.ts
1. Add `lb4 interceptor` command to generate interceptors.
2. Add `interceptor` booter to load interceptors from `src/interceptors`.
=> feat(cli): add `lb4 interceptor` to generate interceptors and a booter to load interceptors

.gitignore, packages/build/config/tsconfig.common.json, packages/cli/generators/project/templates/_.gitignore, packages/cli/generators/project/templates/tsconfig.json.ejs, packages/cli/test/integration/generators/app.integration.js
Enable incremental compilation to speed up our builds. Note: this improvement will apply to projects consuming LoopBack too, once they upgrade to the latest version of `@loopback/build`.
**BEFORE**
```
$ time npm run build
real  0m35.229s
user  3m51.223s
sys   0m14.384s
```
**AFTER**
The first build to populate tsbuildinfo file:
```
$ time npm run build
real  0m35.692s
user  3m55.728s
sys   0m13.828s
```
Subsequent builds (in my case, there were no code changes from the last build):
```
$ time npm run build
real  0m19.510s
user  2m3.894s
sys   0m9.581s
```
I am expecting the build times to improve even more when TypeScript 3.5 is released, see https://devblogs.microsoft.com/typescript/announcing-typescript-3-5-rc/ …
=> feat(build): enable incremental compilation

packages/tsdocs/src/__tests__/acceptance/tsdocs.acceptance.ts, packages/tsdocs/src/update-api-md-docs.ts
In https://loopback.io/doc/en/lb4/apidocs.context.binding.html, it references https://loopback.io/doc/en/lb4/context.binding.(constructor).md.
Please note api-extractor/api-documenter uses `.(constructor).md` for file names. Jekyll has trouble converting such files.
=> fix(tsdocs): escape constructor name to avoid Jekyll site generation issue

packages/repository-json-schema/src/__tests__/integration/build-schema.integration.ts, packages/repository-json-schema/src/__tests__/unit/build-schema.unit.ts, packages/repository-json-schema/src/build-schema.ts, packages/repository-json-schema/src/keys.ts, packages/repository/src/__tests__/integration/repositories/relation.factory.integration.ts, packages/repository/src/__tests__/unit/decorator/relation.decorator.unit.ts, packages/repository/src/__tests__/unit/repositories/belongs-to-repository-factory.unit.ts, packages/repository/src/__tests__/unit/repositories/has-many-repository-factory.unit.ts, packages/repository/src/__tests__/unit/repositories/has-one-repository-factory.unit.ts, packages/repository/src/decorators/metadata.ts, packages/repository/src/relations/belongs-to/belongs-to.decorator.ts, packages/repository/src/relations/has-many/has-many.decorator.ts, packages/repository/src/relations/has-one/has-one.decorator.ts, packages/repository/src/relations/relation.types.ts
Enhance `getJsonSchema` to describe navigational properties
fix #2630
=> feat(repository-json-schema): enhance getJsonSchema for navig props

examples/context/package.json, examples/greeter-extension/package.json, examples/greeting-app/package.json, examples/hello-world/package.json, examples/lb3-application/package.json, examples/log-extension/package.json, examples/soap-calculator/package.json, examples/todo-list/package.json, examples/todo/package.json, packages/authentication/package.json, packages/boot/package.json, packages/booter-lb3app/package.json, packages/cli/generators/project/templates/package.json.ejs, packages/context/package.json, packages/core/package.json, packages/http-caching-proxy/package.json, packages/http-server/package.json, packages/metadata/package.json, packages/openapi-spec-builder/package.json, packages/openapi-v3-types/package.json, packages/openapi-v3/package.json, packages/repository-json-schema/package.json, packages/repository/package.json, packages/rest-explorer/package.json, packages/rest/package.json, packages/service-proxy/package.json, packages/testlab/package.json, packages/tsdocs/package.json
During `npm run clean`, if `tsconfig.build.tsbuildinfo` is not removed but `dist` is removed, `tsc` won't regenerate JS code into `dist`.
The issue can be reproduced as follows:
```
cd loopback-next/packages/context
npm run clean
npm test
```
=>
```
Error: No test files found: "dist/__tests__/**/*.js"
npm ERR! Test failed.  See above for more details.
```
=> chore: remove tsconfig.build.tsbuildinfo with npm run clean

.renovaterc.json
Configure RenovateBot to group updates of the following packages into
a single pull request:
- `@microsoft/api-extractor`
- `@microsoft/api-documenter`
=> chore: configure RenovateBot to group api-extractor packages

packages/build/README.md
This is a follow-up for https://github.com/strongloop/loopback-next/pull/3063 which removed `lb-tslint` implementation. Let's update the docs too!
=> fix(build): remove `lb-tslint` from README

.travis.yml
As discussed on Slack:  We don't have any platform specific code, I think it's enough to pick a single Node.js version to test on MacOS. We test different Node.js versions on Linux. …
=> ci: remove Node.js 8 and 10 on MacOS on Travis

packages/cli/generators/discover/index.js
DiscoverModelNames used to return an array of {'table': 'foo', 'schema': 'bar'}, now the 'schema' key has been changed to 'owner'.  This broke a part of the discover feature, this one-liner fixes it.
Fixes #3074
Looking at the refactors across the board, it seems the term "schema" has been changed to "owner" in this context.  Should I do a follow-up PR which addresses this in the discover module?
=> discover uses owner instead of schema key

.travis.yml, bin/build-docs-site.sh, lerna.json, packages/cli/test/acceptance/app-run.acceptance.js
- set `forceLocal` to `true` by default (so that local versions of `@loopback/*` are used)
- use `--include-filtered-dependencies` (so that we only have to specify the root package to be linked)
=> chore: simplify lerna bootstrap

docs/site/Dependency-injection.md
Update dependency injection examples that mention authentication
Related to : https://github.com/strongloop/loopback-next/issues/2940
=> docs: update dependency injection examples

packages/testlab/README.md, packages/testlab/src/index.ts, packages/testlab/src/skip.ts
I discovered the need for a generic `skipIf` helper while working on https://github.com/strongloop/loopback-next/pull/3079
=> feat(testlab): add `skipIf` helper

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, .prettierignore
GitHub preserves newline characters in the rendered HTML output, see how the Checklist below is rendered now, before the changes in this PR are applied. We must not add extra newlines even if it means that the markdown files have lines longer than 80 characters.
This commit reverts changes in `.github` made by 72cb8aafad3 (https://github.com/strongloop/loopback-next/pull/3130
👉
[Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-next)
👈
- Code conforms with the
[style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- Affected artifact templates …
=> chore: fix formatting in PR & ISSUE templates

examples/lb3-application/README.md, packages/booter-lb3app/src/lb3app.booter.ts
Resolves https://github.com/strongloop/loopback-next/issues/3104.
=> fix: mention required loopback-boot version for mounting a lb3 app

packages/cli/generators/discover/index.js, packages/cli/test/fixtures/discover/mem.datasource.js.txt
resolves https://github.com/strongloop/loopback-next/issues/2952
=> fix(cli): discover prompt exits after generating

docs/site/decorators/Decorators_authenticate.md
Point to new Authentication component document
Related to https://github.com/strongloop/loopback-next/issues/2940 
Instead of pointing to @loopback/authentication/README.MD, point to 
new authentication component document.
=> docs: point to new authentication component doc link

packages/repository/src/repositories/legacy-juggler-bridge.ts
loopback-datasource-juggler is always using native Promises, no need to wrap the promises returned by juggler APIs into another Promise instance.
This is a follow-up for https://github.com/strongloop/loopback-datasource-juggler/pull/1749 and older https://github.com/strongloop/loopback-datasource-juggler/pull/1631.
I discovered this improvement opportunity while experimenting with optimizing dependencies of `@loopback/repository` (loosely related to https://github.com/strongloop/loopback-next/issues/3126).
- Documentation in [/docs/site](../tree/master/docs/site) …
=> refactor(repository): simplify `ensurePromise` helper

packages/metadata/src/decorator-factory.ts
The testing framework [Jest](https://jestjs.io) creates a new V8 VM for each test file and as a result, it's not possible to rely on `instanceof Function` checks to work - there may be multiple `Function` constructors present.
This commit reworks `instanceof Function` check to use `typeof` instead.
See also https://github.com/strongloop/loopback-next/issues/3159
👉 [Check out how …
=> fix(metadata): don't rely on `instanceof` checks

docs/site/Loopback-component-authentication.md
Change link from shopping cart example github link
to authentication tutorial link.
Related to : https://github.com/strongloop/loopback-next/issues/2940
Changing the github link at the bottom to the authentication tutorial link instead (the tutorial itself has the link to the github shopping cart example link, as well as the tutorial steps.)
=> docs: change link to authentication tutorial

.prettierignore
Sometimes when I run `npm t` after `git rebase`, I receive the following error:
```
> node packages/build/bin/run-prettier "**/*.ts" "**/*.js" "**/*.md" "-l"
packages/tsdocs/fixtures/monorepo/packages/pkg1/docs/apidocs/reports-temp/pkg1.api.md
packages/tsdocs/fixtures/monorepo/packages/pkg1/docs/apidocs/reports/pkg1.api.md
```
This pull request fixes the problem by adding `packages/tsdocs/fixtures/monorepo/**/docs` to `.prettierignore` list.
See also the similar `.gitignore` entries:
https://github.com/strongloop/loopback-next/blob/a18adf654f8a865c62ac21f08e3773f1ea419cef/.gitignore#L14-L15
- Code …
=> chore: configure prettier to ignore generated apidocs

docs/site/Loopback-component-authentication.md, docs/site/decorators/Decorators_authenticate.md, docs/site/tutorials/authentication/Authentication-Tutorial.md
Optional flag may need to be set to true when injecting
CURRENT_USER in a controller constructor if only
some controller methods are decorated with the
@authenticate decorator
Related to : https://github.com/strongloop/loopback-next/issues/2940
=> docs: injection of current user may require optional set to true

packages/repository/src/__tests__/unit/model/model.unit.ts, packages/repository/src/model.ts
Modify the code converting Model instances to JSON data to include navigational properties for the defined model relations.
See https://github.com/strongloop/loopback-next/pull/3171 and https://github.com/strongloop/loopback-next/issues/2633
=> feat(repository): include navigation properties in JSON

docs/site/exposing-graphql-apis.md, docs/site/tutorials/todo/todo-tutorial-datasource.md, examples/todo-list/data/db.json, examples/todo/data/db.json
See https://github.com/strongloop/loopback-next/pull/3171#discussion_r296126725.
Updated the sample instances to be less political, while keeping a similar theme. 
=> fix: update sample todo and todo-lists

packages/build/CHANGELOG.md
While describing Build 2.0 changes for our next Milestone blog post, I noticed that Breaking changes in our changelog are incorrectly formatted. This pull request fixes the formatting.
=> docs(build): fix formatting in CHANGELOG

packages/cli/generators/project/templates/package.json.ejs, packages/cli/generators/project/templates/package.plain.json.ejs, packages/cli/test/integration/generators/app.integration.js, packages/cli/test/integration/lib/project-generator.js
Fixes https://github.com/strongloop/loopback-next/issues/3197
=> fix(cli): make sure tsbuildinfo is removed by the clean script

docs/site/tutorials/todo-list/todo-list-tutorial-controller.md, docs/site/tutorials/todo-list/todo-list-tutorial-model.md, docs/site/tutorials/todo-list/todo-list-tutorial-repository.md, examples/todo-list/data/db.json, examples/todo-list/package.json, examples/todo-list/src/__tests__/acceptance/todo-list-image.acceptance.ts, examples/todo-list/src/__tests__/acceptance/todo-list.acceptance.ts, examples/todo-list/src/__tests__/acceptance/todo.acceptance.ts, examples/todo-list/src/__tests__/helpers.ts, examples/todo-list/src/__tests__/integration/todo-list-image.repository.integration.ts, examples/todo-list/src/__tests__/integration/todo-list.repository.integration.ts, examples/todo-list/src/__tests__/integration/todo.repository.integration.ts, examples/todo-list/src/controllers/todo-list-image.controller.ts, examples/todo-list/src/controllers/todo-list.controller.ts, examples/todo-list/src/controllers/todo.controller.ts, examples/todo-list/src/models/todo.model.ts, examples/todo-list/src/repositories/todo-list-image.repository.ts, examples/todo-list/src/repositories/todo-list.repository.ts, examples/todo-list/src/repositories/todo.repository.ts
See https://github.com/strongloop/loopback-next/issues/2633.
- Overwrote `find` and `findById` functions in `TodoRepository`, `TodoListRepository`, `TodoListImage` to include a hard-coded retrieval of related models.
- https://github.com/strongloop/loopback-next/issues/3195 is for improvement of this
- Updated response schemas for controller methods `find` and `findById` to leverage `getModelSchemaRef` and `includeRelations`
- Updated `TodoList` tutorial
Note: since `HasOneRepository<T>` doesn't have a `find` function, the `image` property wasn't included in the `TodoList` instances as part of this PR. …
=> feat(example-todo-list): add navigational properties to todo-list example

packages/cli/generators/model/templates/model.ts.ejs, packages/cli/test/integration/generators/model.integration.js
Disabling the no-any warning that happens when a model allows additional properties
=> fix(cli): remove no-any warning from model template

packages/cli/generators/project/templates/package.json.ejs, packages/cli/generators/project/templates/package.plain.json.ejs, packages/cli/test/integration/lib/project-generator.js
Implements https://github.com/strongloop/loopback-next/issues/3223
=> feat(cli): enable source map for npm start script

bin/run-lerna.js, bin/sync-dev-deps.js, bin/update-template-deps.js, examples/context/src/binding-types.ts, examples/context/src/configuration-injection.ts, examples/context/src/context-chain.ts, examples/context/src/context-observation.ts, examples/context/src/custom-configuration-resolver.ts, examples/context/src/custom-inject-decorator.ts, examples/context/src/custom-inject-resolve.ts, examples/context/src/dependency-injection.ts, examples/context/src/find-bindings.ts, examples/context/src/index.ts, examples/context/src/injection-without-binding.ts, examples/context/src/interceptor-proxy.ts, examples/context/src/parameterized-decoration.ts, examples/context/src/sync-async.ts, examples/context/src/value-promise.ts, examples/greeter-extension/index.js, packages/cli/bin/download-connector-list.js, packages/context/src/__tests__/unit/resolver.unit.ts, packages/context/src/__tests__/unit/value-promise.unit.ts, packages/eslint-config/eslintrc.js, packages/repository-json-schema/src/__tests__/unit/filter-json-schema.unit.ts, packages/rest/src/__tests__/acceptance/sequence/sequence.acceptance.ts, packages/tsdocs/bin/extract-apis.js, packages/tsdocs/bin/update-apidocs.js
See https://github.com/typescript-eslint/typescript-eslint/pull/495 that re-implemented the rule in typescript-eslint.
=> feat(eslint-config): enable "no-floating-promises" rule

packages/repository-json-schema/src/__tests__/unit/build-schema.unit.ts, packages/repository-json-schema/src/build-schema.ts
- Extract the code building schema title suffix (e.g. `WithRelations`) into a new function `getTitleSuffix`
- Rework the function `buildModelCacheKey` to leverage `getTitleSuffix` under the hood
This change simplifies the process of adding a new schema option, as there is only a single place to modify (`getTitleSuffix`) now.
See #3199
=> refactor(repository-json-schema): unify code building schema title and cache key

acceptance/repository-mongodb/src/__tests__/mongodb.datasource.ts, acceptance/repository-mysql/src/__tests__/mysql.datasource.ts
I noticed that the acceptance tests for MongoDB are skipping tests for free-form properties (strict mode turned off). This pull request is fixing the problem.
=> fix: run acceptance tests for free-form properties for MongoDB

docs/site/Sequence.md
In "Query string parameters" section's example, `id` should be obtained from `path` instead of `query`.
=> docs: update "Query string parameters" section

docs/site/Loopback-component-authentication.md
Show an example of how to pass default and overriding options
into a custom authentication strategy.
Related to: https://github.com/strongloop/loopback-next/issues/3190
=> docs: show how to process options for an authentication strategy

docs/site/tutorials/todo/todo-tutorial-putting-it-together.md
Now that partial updates are [supported](https://github.com/strongloop/loopback-next/pull/3199) for this example, this note is no longer relevant.
=> fix(docs): remove note about not supporting partial updates

packages/repository-json-schema/src/build-schema.ts, packages/repository-tests/src/helpers.repository-tests.ts
Fixes invalid block tags in tsdoc comments.
Maybe we should add a travis task to run apidocs generation to catch such errors.
=> chore: fix block tags for tsdoc comments

packages/rest/src/__tests__/unit/request-body.validator.test.ts, packages/rest/src/types.ts, packages/rest/src/validation/request-body.validator.ts
This PR improves the AJV validator caching by honoring `options` as different `options` leads to different validate functions.
Fixes https://github.com/strongloop/loopback-next/issues/3234
=> fix(rest): honor options for AJV validator caching

examples/express-composition/package.json
remove tsconfig.build.tsbuildinfo
- As part of https://github.com/strongloop/loopback-next/pull/3083
=> chore(example-express-composition): update npm run clean

packages/booter-lb3app/fixtures/lb3app/common/models/coffee-shop.json, packages/booter-lb3app/fixtures/lb3app/common/models/coffee.js, packages/booter-lb3app/fixtures/lb3app/common/models/coffee.json, packages/booter-lb3app/fixtures/lb3app/server/model-config.json, packages/booter-lb3app/src/__tests__/acceptance/booter-lb3app.acceptance.ts, packages/booter-lb3app/src/lb3app.booter.ts
Fixes https://github.com/strongloop/loopback-next/issues/3163.
Stringify the LB3 app's spec before converting it so it removes `default` values that are functions. These `default` values are included automatically as part of any `embedsMany` or `referencesMany` relation as part of the source model's target model property.
=> fix(booter-lb3app): stringify and parse lb3 spec before converting it

packages/testlab/src/__tests__/unit/to-json.test.ts, packages/testlab/src/to-json.ts
While working on https://github.com/strongloop/loopback-next/issues/2634, I discovered that `findOne` returns `T | null` and this type cannot be passed to `toJSON` helper, because there is no overload accepting such type.
This pull requests improves the type definitions to let the compiler understand toJSON's behavior for commonly used union types like `object | null` or `unknown[] | null`. …
=> feat(testlab): improve typings for `toJSON()` helper

packages/rest/src/__tests__/integration/request-context.integration.ts, packages/rest/src/__tests__/integration/rest.server.integration.ts, packages/rest/src/request-context.ts, packages/rest/src/rest.server.ts
- Fix `server.basePath()` method to update `basePath` in the config object too.
- This fixes the server url in openapi.json to include basePath again.
- Add more test to verify the changes and prevent future regressions
See https://github.com/strongloop/loopback-next/issues/914
=> fix(rest): correctly handle basePath set via basePath() API

packages/repository-tests/package.json
=> chore(repository-tests): fix the clean script to remove tsbuildinfo

.github/ISSUE_TEMPLATE/Bug_report.md
fix the spelling of "sandbox" the 'd' was missing
=> chore: fix a typo in GITHUB bug_report template

docs/site/decorators/Decorators_repository.md
the links were ending with '.md'... removing it fixes the problem
fixes #3317
=> docs: fix broken links in repository decorators page

docs/site/Controller-generator.md, docs/site/tutorials/todo-list/todo-list-tutorial-controller.md, examples/express-composition/src/controllers/note.controller.ts, examples/todo-list/src/controllers/todo-list-todo.controller.ts, examples/todo-list/src/controllers/todo-list.controller.ts, examples/todo-list/src/controllers/todo.controller.ts, examples/todo-list/src/models/todo-list.model.ts, examples/todo-list/src/models/todo.model.ts, examples/todo/src/controllers/todo.controller.ts, packages/cli/generators/controller/templates/src/controllers/controller-rest-template.ts.ejs, packages/cli/generators/relation/templates/controller-relation-template-has-many.ts.ejs, packages/cli/test/integration/generators/controller.integration.js, packages/cli/test/integration/generators/hasmany.relation.integration.js, packages/openapi-v3/src/controller-spec.ts, packages/repository-json-schema/src/__tests__/integration/build-schema.integration.ts, packages/repository-json-schema/src/__tests__/unit/build-schema.unit.ts, packages/repository-json-schema/src/build-schema.ts
See https://github.com/strongloop/loopback-next/issues/2653.
- Add `exclude` option to emit model schema excluding certain model properties.
- Update `POST` in example applications to exclude `id`.
- Update their docs for consistency.
- Update the CLI templates to also exclude `id` from `POST` request body.
=> Emit schema excluding certain model properties

examples/greeter-extension/README.md, packages/authentication/README.md
Fixes #3319 
Fixes the broken link on npmjs.com for authentication and example-greeter-extension.
=> docs: fix image links in READMEs when showing in npmjs.com

docs/ROADMAP.md
Tentative Q3 roadmap
- The idea is to create this PR to get reviews from the maintainers **and** the community.
- This roadmap is tentative that listed what we think it makes sense to work on, but we also need to consider the team velocity to make sure we have a realistic schedule.
- It is based on the discussion captured in this box note: https://ibm.ent.box.com/notes/435410471895 (limited access). 
@bajtos and I had a discussion whether the roadmap should eventually be in this md file or should be in a GitHub issue like we did before. 
=> docs: add Q3 roadmap

docs/site/sidebars/lb4_sidebar.yml
Modify sidebar as proposed in PR https://github.com/strongloop/loopback-next/pull/3164.
Current side:
New sidebar: 
=> docs: modify sidebar

packages/repository/src/__tests__/acceptance/belongs-to.relation.acceptance.ts, packages/repository/src/__tests__/fixtures/models/customer.model.ts, packages/repository/src/__tests__/fixtures/models/index.ts, packages/repository/src/__tests__/fixtures/models/order.model.ts, packages/repository/src/__tests__/fixtures/models/shipment.model.ts, packages/repository/src/__tests__/fixtures/repositories/index.ts, packages/repository/src/__tests__/fixtures/repositories/order.repository.ts, packages/repository/src/__tests__/fixtures/repositories/shipment.repository.ts, packages/repository/src/relations/belongs-to/belongs-to-accessor.ts, packages/repository/src/relations/has-many/has-many-repository.factory.ts, packages/repository/src/relations/has-one/has-one-repository.factory.ts
Closes https://github.com/strongloop/loopback-next/issues/2169.
* Added constraint to make sure the foreign key in `keyTo` actually exists in the target model
* Added tests to see if custom names (not the standard `{ModelName}Id` work e.g. with underscores or a completely different name) for the foreign key also work. 
=> Custom foreign key name

packages/cli/lib/project-generator.js, packages/cli/lib/utils.js, packages/cli/package-lock.json, packages/cli/package.json, packages/cli/test/integration/generators/app.integration.js
In the [issue 2092](https://github.com/strongloop/loopback-next/issues/2092), the **default project name** could be generated incorrectly if the cwd folder name has hyphens, fixed. The **input app name** has no such issue.
The user also suggested that `lb4` should allow the project to be generated in the CWD. However, that could be messy and confusing. The other issue is that `lb4` allows user to use any project path as they want. This could be problematic: 
```javascript
(CWD: User/lb4-app)
? Project name: pathFromRoot
? Project root directory:  ~/try/pathFromRoot
...
Application pathFromRoot was created in ~/try/pathFromRoot
lb4-app$ ls
~
lb4-app$ cd ~
[goes to the root folder]
```
The change here is to untildify the input path to make sure that it always uses absolute path.
resolves …
=> fix(cli): fix app default project name. untildify the project path

examples/todo-list/src/controllers/todo-list-todo.controller.ts, packages/repository-json-schema/package-lock.json, packages/repository-json-schema/package.json, packages/repository-json-schema/src/__tests__/integration/build-schema.integration.ts, packages/repository-json-schema/src/__tests__/unit/build-schema.unit.ts, packages/repository-json-schema/src/build-schema.ts
Add a new option `optional: []` so that `getJsonSchema` and related helpers can request a model schema that marks specified properties as optional
Connect to https://github.com/strongloop/loopback-next/issues/2653
=> feat(repository-json-schema): add an option to make properties optional

packages/repository-json-schema/src/__tests__/integration/build-schema.integration.ts, packages/repository-json-schema/src/build-schema.ts
See https://github.com/strongloop/loopback-next/pull/3309#pullrequestreview-262253508.
- Explain in API docs that the "partial" option is overridden by the "optional" option. 
- Test that `partial` is still overridden when it is set to false
=> Update API Docs and test to show that "optional" takes precedence over "partial"

packages/cli/generators/interceptor/index.js
Fixes #3374 
Changes proposed by @bajtos:
- Print the information about group names as a regular text (not a prompt).
- Possibly wrap the long line at 80 chars so that it's consistently rendered everywhere.
- The prompt should ask about the group name only, so that the question mark is printed at the beginning of the prompt line.
The output now is:
```
$ lb4 interceptor
? Interceptor name: interceptor1
? Is it a global interceptor? Yes
Global interceptors are sorted by the order of an array of group names bound to ContextBindings.GLOBAL_INTERCEPTOR_ORDERED_GROUPS. See https://loopback.io/doc/en/lb4/Interceptors.html#order-of-invocation-for-interceptors.
? Group name for the global interceptor: ('') 
create src/interceptors/interceptor1.interceptor.ts
update src/interceptors/index.ts …
```
=> fix(cli): rearrange interceptor cli prompts

packages/repository/src/__tests__/unit/model/model.unit.ts, packages/repository/src/model.ts
While working on a spike for "Resolve included models", I discovered a need to access the list of id properties via model class constructor (no model instance is available).
In this pull request, I am adding such API.
=> feat(repository): add static method Entity.getIdProperties()

docs/site/tutorials/todo-list/todo-list-tutorial-controller.md, docs/site/tutorials/todo/todo-tutorial-controller.md, packages/cli/generators/controller/index.js, packages/cli/generators/controller/templates/src/controllers/controller-rest-template.ts.ejs, packages/cli/generators/relation/has-many-relation.generator.js, packages/cli/generators/relation/index.js, packages/cli/generators/relation/templates/controller-relation-template-has-many.ts.ejs, packages/cli/test/integration/generators/controller.integration.js, packages/cli/test/integration/generators/hasmany.relation.integration.js
Closes https://github.com/strongloop/loopback-next/issues/3344.
=> fix(cli): add support for excluding custom pk from POST requests

docs/site/Model.md, packages/repository/src/__tests__/unit/model/model.unit.ts, packages/repository/src/model.ts
Implements #1914 
See also #3265 
=> Add Short-term solution for hiddenProperties in model

packages/repository/src/relations/belongs-to/belongs-to-accessor.ts, packages/repository/src/relations/belongs-to/belongs-to.helpers.ts, packages/repository/src/relations/has-many/has-many-repository.factory.ts, packages/repository/src/relations/has-many/has-many.helpers.ts, packages/repository/src/relations/has-one/has-one-repository.factory.ts, packages/repository/src/relations/has-one/has-one.helpers.ts
In https://github.com/strongloop/loopback-next/pull/3387 (spike for Inclusion of related models), I found a need to access resolved relation metadata from other files than just the repository factory. At the same time, I'd like to keep resolved metadata internal and don't export it from `@loopback/repository`, at least for now.
In this pull request, I am adding three new files (`belongs-to.helpers.ts`, `has-many.helpers.ts` and `has-one.helpers.ts`) and moving code related to resolution of relational metadata into these new files.
This pull request is a pure refactoring with no impact on our users.
- …
=> refactor: extract helpers resolving relation metadata into own files

acceptance/repository-mongodb/src/__tests__/mongodb.datasource.ts, acceptance/repository-mysql/src/__tests__/mysql.datasource.ts, packages/repository-tests/src/crud-test-suite.ts, packages/repository-tests/src/crud/create-retrieve.suite.ts, packages/repository-tests/src/crud/freeform-properties.suite.ts, packages/repository-tests/src/types.repository-tests.ts, tsconfig.json
In the future (see #3387), we are likely to add options that are specific to different Repository implementations, in addition to connector-specific options. Let's rename the interface to describe this enlarged scope.
The second commit adds "acceptance" packages like `acceptance/repository-mongodb` to `tsconfig.json` used by VSCode. Before this change, refactor-rename was not applied to packages in `acceptance` directory.
👉 [Check out how to …
=> Rename CrudConnectorFeatures to CrudFeatures

packages/repository-tests/README.md, packages/repository-tests/src/crud-test-suite.ts, packages/repository-tests/src/crud/create-retrieve.suite.ts, packages/repository-tests/src/crud/freeform-properties.suite.ts, packages/repository-tests/src/types.repository-tests.ts, packages/testlab/src/skip.ts
Clean up remaining places referencing "connectorFeatures" to use "features" instead. See https://github.com/strongloop/loopback-next/pull/3411 which renamed `CrudConnectorFeatures` to `CrudFeatures` and the spike #3387 which triggered the need for these renames.
=> refactor: clean up after CrudConnectorFeatures rename

packages/repository/src/__tests__/fixtures/models/order.model.ts, packages/repository/src/__tests__/fixtures/repositories/order.repository.ts
Because the code infering relation name from FK name supports camelCase only, it's important to explicitly provide the relation name when calling `@belongsTo` decorator.
This is a follow-up for #3326, fixing a problem discovered while working on #3387
=> test(repository): fix setup of relations with custom FK names

packages/context/src/__tests__/acceptance/interceptor.acceptance.ts, packages/context/src/__tests__/unit/invocation-context.unit.ts, packages/context/src/interceptor.ts, packages/context/src/invocation.ts
Use case: interceptors may add or change bindings to influence how the
method parameter injection is resolved.
The current implementation does not use the invocation context to resolve parameter injection. As a result, interceptors cannot rebind new values.
=> feat(context): use invocation context for method dependency injection

packages/cli/generators/project/templates/package.plain.json.ejs
Remove the eslint `-p` option in the project generator template for plain `package.json`, as `eslint` does not support this option.
Fixes: #3424
=> fix(cli): remove -p option from eslint

docs/site/Context.md, packages/context/src/__tests__/acceptance/binding-config.acceptance.ts, packages/context/src/__tests__/acceptance/class-level-bindings.acceptance.ts, packages/context/src/__tests__/unit/context-config.unit.ts, packages/context/src/binding-config.ts, packages/context/src/context.ts, packages/context/src/inject-config.ts
Sometimes we want to inject configuration from another binding instead of
the current one.
This PR allows the following config injections:
```ts
@config({targetBindingKey: 'parent', configPath: 'child1'})
@config.getter({targetBindingKey: 'parent', configPath: 'child2'})
@config({targetBindingKey: 'anotherBinding'})
```
=> feat(context): allow @config.* to specify the target binding key

packages/rest-explorer/README.md, packages/rest-explorer/src/__tests__/acceptance/rest-explorer.acceptance.ts, packages/rest-explorer/src/rest-explorer.component.ts, packages/rest-explorer/src/rest-explorer.keys.ts
Switch to `@config` and `ctx.configure` for rest-explorer options.
=> feat(rest-explorer): use configuration apis/decorators

acceptance/repository-mysql/src/__tests__/mysql.datasource.ts, packages/repository-tests/src/crud-test-suite.ts, packages/repository-tests/src/crud/create-retrieve.suite.ts, packages/repository-tests/src/crud/freeform-properties.suite.ts, packages/repository-tests/src/crud/replace-by-id.suite.ts, packages/repository-tests/src/helpers.repository-tests.ts, packages/repository-tests/src/types.repository-tests.ts
While working on the spike for Inclusion of related models (see #3387), I discovered that `replaceById` does not behave as expected when using MongoDB database and when implementing `fromEntity` repository method, extra care must be taken to not break MongoDB support.
In this pull request, I am adding new tests to verify that `replaceById` works correctly when called from JS/TS code (using a model instance as the data parameter) and via REST API (using a plain data object as the data parameter).
- The first commit fixes a wrong `import` statement. While it's not directly related to my changes, I feel it's not worth opening a new PR for that.
- The second commit introduces a new helper `deleteAllModelsInDefaultDataSource` that leverages the recently introduced juggler API (see …
=> feat(repository-tests): test `replaceById`, verify plain data handling + more

docs/site/Model.md, packages/repository/DEVELOPING.md
Resolves https://github.com/strongloop/loopback-next/issues/2133
Update inconsistent docs for `@model` and `@property` decorators part. 
By testing out the code in `loopback-datasource-juggler/lib/datasource.js`,  `loopback-datasource-juggler/lib/model-builder.js`, I made following changes: 
( I copied the available part of [the table](https://loopback.io/doc/en/lb3/Model-definition-JSON-file.html#top-level-properties) from lb3 site and made a bit change on the content. Because I think checking sites back and forth is kind of annoying.)
- indicates that lb4 now only supports `settings` entries in model decorator. And `top-level-properties` in lb3 now are passed in `settings`. 
- indicates that properties are defined via `@property` decorator.
- lists features like `options`, `acls` are …
=> docs: update model decorator

packages/tsdocs/src/__tests__/acceptance/tsdocs.acceptance.ts, packages/tsdocs/src/update-api-md-docs.ts
=> fix(tsdocs): use model.name as canonicalReference is removed

packages/openapi-v3/src/__tests__/unit/decorators/param/param-header.decorator.unit.ts, packages/openapi-v3/src/__tests__/unit/decorators/param/param-path.decorator.unit.ts, packages/openapi-v3/src/__tests__/unit/decorators/param/param-query.decorator.unit.ts, packages/openapi-v3/src/decorators/parameter.decorator.ts
See https://github.com/strongloop/loopback-next/issues/3457
=> feat(openapi-v3): allow optional spec for `@param.*` shortcut decorators

packages/cli/generators/repository/index.js, packages/cli/lib/artifact-generator.js
This commit adds a character defined in artifact-generator.js to be used when the output contains
multiple class names
The idea was to just add a comma as separator where the class names are merged, but at the end of the process, the class names variable is passed to a function in `artifact-generator.js`, `toClassName`, that transforms it to a PascalCaseName, removing any kind of invalid characters for a class name (whitespaces and commas included)
So the solution I've thought of is to apply that function for each class, instead of to every class at once
This is a work in progress and I'd appreciate if someone could help me with this, I won't be able to work on this anytime soon. And of course, any kind of feedback is appreciated!
fixes #3350 …
=> [WIP] fix: add class name separation to multiple class names output

docs/site/Booting-an-Application.md, docs/site/Service-generator.md, docs/site/tables/lb4-artifact-commands.html, packages/boot/src/__tests__/fixtures/bindable-classes.artifact.ts, packages/boot/src/__tests__/integration/service.booter.integration.ts, packages/boot/src/__tests__/unit/booters/service.booter.unit.ts, packages/boot/src/booters/interceptor.booter.ts, packages/boot/src/booters/service.booter.ts, packages/cli/generators/service/index.js, packages/cli/generators/service/templates/local-service-class-template.ts.ejs, packages/cli/generators/service/templates/local-service-provider-template.ts.ejs, packages/cli/generators/service/templates/remote-service-proxy-template.ts.ejs, packages/cli/test/integration/generators/local-service.integration.js, packages/cli/test/integration/generators/remote-service.integration.js, packages/core/src/__tests__/unit/application.unit.ts, packages/core/src/application.ts, packages/core/src/keys.ts, packages/service-proxy/src/mixins/service.mixin.ts
Replaces https://github.com/strongloop/loopback-next/pull/3262
This PR extends the `service` concept to be not only a service proxy but also a local service - classes decorated with `@bind`.
=> feat: add app.service() and extend service booter to load classes with `@bind`

packages/openapi-v3/src/controller-spec.ts, packages/repository-json-schema/src/build-schema.ts
Modify functions like `getModelSchemaRef` to link the prototype of the constructor function with the `T` argument of `JsonSchemaOptions`.
Before this change, the following code happily compiles:
schema: getModelSchemaRef(Note, {exclude: ['prop-doesnt-exist'])})
(The reason: compiler resolves `T` as `object`, therefore any properties are allowed in `exclude` list.)
With this change in place, the code above is rejected by the compiler, because the compiler understands that `T` is `Note` and therefore only `Note` properties are allowed in the `exclude` list.
Argument of type '{ exclude: "prop-doesnt-exist"[]; }' is not
assignable to parameter of type 'JsonSchemaOptions<Note>'.
Types of property 'exclude' are incompatible.
(...)
Type '"prop-doesnt-exist"' is not assignable to
type '"content" …
=> fix: enforce JsonSchemaOptions type when building model schema

.renovaterc.json
With this changes in place, Renovate should open a new PR when a Node.js major version enters LTS or reaches end-of-life.
Inspired by https://github.com/nodejs/package-maintenance/issues/206 …
=> build: configure Renovate to update Node.js versions in Travis config
