loopbackio/loopback-next

packages/boot/src/booters/application-metadata.booter.ts
packages/boot/src/booters/base-artifact.booter.ts
packages/boot/src/booters/controller.booter.ts
packages/boot/src/booters/datasource.booter.ts
packages/boot/src/booters/interceptor.booter.ts
packages/boot/src/booters/lifecyle-observer.booter.ts
packages/boot/src/booters/repository.booter.ts
packages/boot/src/booters/service.booter.ts
packages/boot/src/bootstrapper.ts
packages/boot/src/index.ts
packages/boot/src/keys.ts
packages/boot/src/mixins/boot.mixin.ts
packages/boot/src/types.ts

Switch to `@config` and `ctx.configure` for booter options.

feat(boot): use @config to inject options for booters

---

docs/site/sidebars/lb4_sidebar.yml

Add Connector docs to LB4 docs.
Required to fix https://github.com/strongloop/loopback-next/issues/2598.

feat: add Connector docs to LB4 docs

---

examples/context/.npmignore
examples/express-composition/.npmignore
examples/greeter-extension/.npmignore
examples/greeting-app/.npmignore
examples/hello-world/.npmignore
examples/lb3-application/.npmignore
examples/log-extension/.npmignore
examples/rpc-server/.npmignore
examples/soap-calculator/.npmignore
examples/todo-list/.npmignore
examples/todo/.npmignore

There is no `files` section in example package.json. This change prevents
*.tsbuildinfo files to be published into npm.

chore: exclude *.tsbuildinfo from published npm packages

---

acceptance/repository-mongodb/src/__tests__/mongodb.datasource.ts
acceptance/repository-mysql/src/__tests__/mysql-default-repository.acceptance.ts
acceptance/repository-mysql/src/__tests__/mysql.datasource.ts
docs/site/Transactions.md
docs/site/sidebars/lb4_sidebar.yml
packages/repository-tests/src/__tests__/acceptance/default-repository.memory.acceptance.ts
packages/repository-tests/src/crud-test-suite.ts
packages/repository-tests/src/crud/transactions.suite.ts
packages/repository-tests/src/types.repository-tests.ts
packages/repository/src/__tests__/unit/crud-connector.stub.ts
packages/repository/src/__tests__/unit/repositories/crud.repository.unit.ts
packages/repository/src/__tests__/unit/repositories/legacy-juggler-bridge.unit.ts
packages/repository/src/index.ts
packages/repository/src/repositories/legacy-juggler-bridge.ts
packages/repository/src/repositories/repository.ts
packages/repository/src/transaction.ts

feat(repository): add beginTransaction API

---

bin/build-docs-site.sh

This implementation will return an error message if the bundle command does not exist, therefore it does not execute the entire code until the command does not exist
This comes because it happened to me when I tried to do this https://github.com/strongloop/loopback-next/issues/3501#issuecomment-517951472
- …

Check if bundler is installed

---

packages/repository-tests/src/crud/create-retrieve.suite.ts
packages/repository/src/__tests__/unit/repositories/relation.helpers.unit.ts
packages/repository/src/relations/index.ts
packages/repository/src/relations/relation.helpers.ts

Implemented initial version of the new helper function `findByForeignKeys`. 
Resolves https://github.com/strongloop/loopback-next/issues/3443.

feat(repository): add findByForeignKeys function

---

examples/todo/src/__tests__/acceptance/todo.acceptance.ts
packages/repository-json-schema/src/build-schema.ts

Before this, the `exclude` option would act as the `optional` option and would not reject any properties passed into the request body.
One thing to note is that the `details` of the error message is not helpful when rejecting e.g.:
```json
{
"error": {
"statusCode": 422,
"name": "UnprocessableEntityError",
"message": "The request body is invalid. See error object `details` property for more info.",
"code": "VALIDATION_FAILED",
"details": [
{
"path": "",
"code": "not",
"message": "should NOT be valid",
"info": {}
}
]
}
}
```

fix(repository-json-schema): make exclude option reject properties

---

packages/repository/src/__tests__/unit/repositories/relation.helpers.unit.ts
packages/repository/src/relations/relation.helpers.ts

fix https://github.com/strongloop/loopback-next/pull/3473

fix: fixup findByForeignKey

---

packages/authorization/README.md
packages/authorization/package-lock.json
packages/authorization/package.json
packages/authorization/src/__tests__/acceptance/authorization-casbin.acceptance.ts
packages/authorization/src/__tests__/acceptance/authorization.acceptance.ts
packages/authorization/src/authorize-interceptor.ts
packages/authorization/src/types.ts

Some refactor for https://github.com/strongloop/loopback-next/pull/1205
It contains subsequent changes to make the e2e tests in PR https://github.com/strongloop/loopback4-example-shopping/pull/231 work.

Refactor authorization

---

packages/rest/package-lock.json
packages/rest/package.json
packages/rest/src/__tests__/acceptance/validation/validation.acceptance.ts
packages/rest/src/types.ts
packages/rest/src/validation/request-body.validator.ts

Implements https://github.com/strongloop/loopback-next/issues/3536

feat(rest): add support for ajv-keywords

---

packages/repository/src/__tests__/unit/repositories/relations-helpers/find-by-foreign-keys.helpers.unit.ts
packages/repository/src/__tests__/unit/repositories/relations-helpers/include-related-models.helpers.unit.ts
packages/repository/src/__tests__/unit/repositories/relations-helpers/relations-helpers-fixtures.ts
packages/repository/src/relations/relation.helpers.ts
packages/repository/src/relations/relation.types.ts
packages/repository/src/repositories/legacy-juggler-bridge.ts
packages/repository/src/repositories/repository.ts

resolves https://github.com/strongloop/loopback-next/issues/3445
When reviewing, select **`hide white space changes`** would make it easier to review :smile:
- Add InclusionResolver interface, includeRelatedModels and isInclusionAllowed helpers.
- Used stubbed resolvers for the unit tests.

feat(repository): add InclusionResolver type and includeRelatedModels

---

packages/cli/generators/relation/utils.generator.js
packages/cli/test/fixtures/relation/index.js
packages/cli/test/fixtures/relation/models/order-with-fk.model.ts
packages/cli/test/integration/generators/relation.integration.js

connect to https://github.com/strongloop/loopback-next/issues/3186
Fixes https://github.com/strongloop/loopback-next/issues/3186
- First create a hasMany relation: `Customer` hasMany `Orders`, there will be a property `customerId` created in the Order model class in `order.model.ts`, decorated by `@property`
- Second create a belongsTo relation: `Order` belongsTo `Customer`, the generator exits with error because `customerId` property already exist
In the second step, generator should only reject existing relational property NOT regular property, with this PR, the regular property decorator will be replaced with a relational one, e.g. `@property()` will be replaced with `@belongsTo()`.  …

fix(cli): belongsto property generation

---

docs/site/DEVELOPING.md
docs/site/sidebars/lb4_sidebar.yml
docs/site/submitting_a_pr.md

As @raymondfeng suggested, adding `Contribute to LoopBack 4` to the sidebar. 
Both the `Contribute to LoopBack 4` and `Submitting a pull request to LoopBack 4` are existing pages.  As much as I don't want to change the permalink for `DEVELOPING.md`, I find it's problematic to keep it this way.  
Here are the user experience:
- In LB4 docs, user clicks on either page, sidebar will remain the same, i.e. LB4 sidebar
- In "Contributing", loopback.io/doc > Contributing to LB > Contributing code > LB4, the sidebar will be switched to the LB4 one.  It is problematic to use the `contrib_sidebar`, because it will cause broken links in the subsequent links you click.
👉 [Check …

fix(docs): add contributing guide to LB4 docs

---

packages/rest-crud/index.d.ts
packages/rest-crud/index.js
packages/rest-crud/index.ts
packages/rest-crud/package-lock.json
packages/rest-crud/src/__tests__/acceptance/default-model-crud-rest.acceptance.ts
packages/rest-crud/src/crud-rest.controller.ts
packages/rest-crud/src/index.ts

A follow-up for #3582 fixing the package name in license headers (`crud-rest` -> `rest-crud`) and also syncing package version in `package-lock.json` file.

fix(rest-crud): fix pkg name in license headers

---

packages/context/src/__tests__/unit/binding-decorator.unit.ts
packages/context/src/binding-decorator.ts

```ts
@bind({scope: BindingScope.TRANSIENT})
@bind({tags: {name: 'my-controller'}})
export class MyController {
}
```

feat(context): allow @bind to be applied on the same class multiple times

---

packages/repository-tests/src/crud/create-retrieve.suite.ts
packages/repository-tests/src/crud/freeform-properties.suite.ts
packages/repository-tests/src/crud/replace-by-id.suite.ts
packages/repository-tests/src/crud/transactions.suite.ts

Unifies the usage of `MixedIdType` for all tests in `repository-tests`.
`MixedIdType` is introduced in https://github.com/strongloop/loopback-next/pull/3538

fix(repository-tests): unify the usage of MixedIdType for all tests

---

packages/authentication/src/decorators/authenticate.decorator.ts
packages/authorization/src/decorators/authorize.ts
packages/context/src/__tests__/acceptance/binding-config.acceptance.ts
packages/context/src/__tests__/unit/inject.unit.ts
packages/context/src/binding-decorator.ts
packages/context/src/inject.ts
packages/context/src/interceptor.ts
packages/metadata/README.md
packages/metadata/src/__tests__/unit/decorator-factory.unit.ts
packages/metadata/src/decorator-factory.ts
packages/openapi-v3/src/decorators/api.decorator.ts
packages/openapi-v3/src/decorators/operation.decorator.ts
packages/openapi-v3/src/decorators/parameter.decorator.ts
packages/openapi-v3/src/decorators/request-body.decorator.ts
packages/repository/src/decorators/model.decorator.ts
packages/repository/src/relations/relation.decorator.ts

Extracted and improved from https://github.com/strongloop/loopback-next/pull/3617

feat: allow custom decorator name for error messages

---

packages/core/src/__tests__/acceptance/application.acceptance.ts
packages/core/src/application.ts
packages/core/src/keys.ts
packages/rest/src/rest.application.ts

This change allows an application to inherit bindings from a parent. For example, we can create a parent application that mounts extension components, such as health, metrics, and tracing and use it as the base image for appsody loopback stack. See https://github.com/appsody/stacks/pull/95

feat(core): allow application to accept a parent context

---

docs/site/Loopback-component-authorization.md

fix typo `AuthorizatonBindings` -> `AuthorizationBindings`

fix(docs): typo in example

---

packages/rest-crud/src/__tests__/acceptance/default-model-crud-rest.acceptance.ts
packages/rest-crud/src/crud-rest.controller.ts

While working on #3617, I discovered that I forgot to implement `replaceById` in `@loopback/rest-crud`. This pull request is adding that operation.

feat(rest-crud): add "replaceById" endpoint

---

packages/context/src/__tests__/unit/inject.unit.ts
packages/context/src/inject.ts

See the discussion in https://github.com/strongloop/loopback-next/pull/3617

fix(context): allow `inject` to be explicitly invoked for class ctor args

---

packages/testlab/src/__tests__/integration/test-sandbox.integration.ts
packages/testlab/src/test-sandbox.ts

See https://github.com/strongloop/loopback-next/pull/3617

feat(testlab): add TestLab.writeJsonFile

---

packages/repository-json-schema/src/__tests__/unit/build-schema.unit.ts
packages/repository-json-schema/src/build-schema.ts

Fixes https://github.com/strongloop/loopback-next/issues/3671

fix(repository-json-schema): allow recursive model definitions

---

packages/cli/generators/model/index.js

connect to https://github.com/strongloop/loopback-next/pull/3538
We found in [refactor test PR](https://github.com/strongloop/loopback-next/pull/3538#discussion_r317624487) that id needs to be generated for any instances for the mysql tests, otherwise it complains with Error: `ER_NO_DEFAULT_FOR_FIELD: Field 'id' doesn't have a default value`.
It's not required for relations. But it might be problematic if models are migrated to databases such `MySQL`.

fix(cli): add 'generated: true' entry to id property when generating

---

packages/authentication/README.md

BREAKING CHANGE: PR #3590 rewrote type UserProfile, add the missing
breaking change tag here to amend the one in #3590

fix(authentication): add breaking change notice

---

packages/cli/generators/app/templates/.dockerignore
packages/cli/test/integration/generators/app.integration.js

Fixes https://github.com/strongloop/loopback-next/issues/3684

fix(cli): exclude *.tsbuildinfo from Docker image

---

packages/cli/README.md

While working on https://github.com/strongloop/loopback-next/issues/2480 and reviewing https://github.com/strongloop/loopback-next/pull/2245, it occurred to me that "Basic use" in README of `@loopback/cli` is no longer basic, it looks more like a reference manual. It also requires extra maintenance whenever a new CLI command or a new option/argument is added.
In this pull request, I am proposing a radical simplification:
- Describe the principles how to use our CLI tool
- Show users how they can learn more about the commands and their options
- Add a link to [CLI reference](https://loopback.io/doc/en/lb4/Command-line-interface.html) where they can learn more.
You can view the rendered version of the newly proposed README [here](https://github.com/strongloop/loopback-next/blob/refactor/cli- …

docs(cli): simplify "Basic use" in README

---

packages/booter-lb3app/src/__tests__/acceptance/booter-lb3app.acceptance.ts
packages/booter-lb3app/src/lb3app.booter.ts

While migration from lb3 to lb4 I had several issues with the converted openapi spec of my lb3app, e.g.:
- incomplete return types which results in unuseable angular model interfaces
- renaming of models in the spec to avoid name collisions between lb3 and lb4 implementations
We solved this by post processing the generated openapi spec before it gets published into lb4.
If you think this is the way to go, we can add some tests.

feat(booter-lb3app): process generated OpenApiSpec of lb3 app

---

packages/context/src/__tests__/unit/binding-inspector.unit.ts
packages/context/src/binding-inspector.ts

Extracted from https://github.com/strongloop/loopback-next/pull/3617

feat(context): add more logs to simplify troubleshooting

---

docs/site/Controller-generator.md
docs/site/tutorials/todo-list/todo-list-tutorial-controller.md
examples/express-composition/src/controllers/note.controller.ts
examples/todo-list/src/controllers/todo-list-todo.controller.ts
examples/todo-list/src/controllers/todo-list.controller.ts
examples/todo-list/src/controllers/todo.controller.ts
examples/todo/src/controllers/todo.controller.ts
packages/cli/generators/controller/templates/src/controllers/controller-rest-template.ts.ejs
packages/cli/generators/relation/templates/controller-relation-template-has-many.ts.ejs
packages/cli/test/integration/generators/controller.integration.js
packages/repository-json-schema/src/__tests__/integration/build-schema.integration.ts
packages/repository-json-schema/src/__tests__/unit/build-schema.unit.ts
packages/repository-json-schema/src/build-schema.ts
packages/rest-crud/src/crud-rest.controller.ts

While reviewing #3698, #3504 and #1466, it occurred to me that schema titles like `TodoExcluding[id]` or `ProductPartialExcluding[id,_rev]` are not very friendly to human consumers.
In this pull request, I am introducing a new JsonSchemaOption `title` that allows developer to specify a title that described the intent (data of a new Todo to be created - `NewTodo`) instead of the implementation details (Todo data excluding `id` property).
The second commit updates controller templates and `rest-crud` package to leverage this new schema option for POST requests.
/cc @ericzon @remkohdev
IMPORTANT: Although this change is very likely to fix the issues described in #3698, #3504 and #1466 _for newly created controllers_, it's not meant as a replacement for …

Custom schema title for POST requests

---

labs/authentication-passport/package.json

Update build to v2 in authentication-passport package.
When running `npm test` currently, the local test failed, so updating the `@loopback/build` as the first step. 

chore: update build to v2 in authentication-passport package

---

packages/cli/test/fixtures/relation/index.js
packages/cli/test/integration/generators/relation.belongs-to.integration.js
packages/cli/test/integration/generators/relation.has-many.integration.js
packages/cli/test/integration/generators/relation.integration.js

In this pull request I am significantly cleaning up integration tests for `lb4 relation` command. It's best to review the changes one commit at a time, I recommend to ignore white-space changes too.
List of commits/changes:
- refactor "fixtures/relation" to reduce code duplication
- rename files to follow the pattern `relation.{type}.integration.ts`
- move relation-type-specific tests from `relation.integration.ts` to relation-type-specific test files
- improve readability of tests by inlining (some of) `SANDBOX_FILES{n}`
- improve structure of `relation.has-many.integration.js` and `relation.belongs-to.integration.js` by fixing nesting of `describe` and `context` blocks and grouping parameterized groups into `describe` blocks with a descriptive titles generated from the parameter values …

Clean up tests for "lb4 relation" command

---

examples/greeting-app/src/caching-service.ts
packages/cli/generators/example/index.js
packages/eslint-config/eslintrc.js
packages/rest/src/__tests__/integration/rest.application.integration.ts

I suggest we add this useful new rule [`no-misused-promises`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-misused-promises.md) to core. It catches a common mistake of forgetting to await a `Promise<boolean>`:
```js
const isAllowed = checkIsAllowed(user);
if (isAllowed) {
await doSomethingPrivileged();
}
// Mistake: checkIsAllowed() returns a promise, but we forgot to await it!
//
// So the condition will always pass, because `isAllowed: Promise<boolean>`
// is an object so is always truthy.
//
// This is not currently caught by eslint, until the rule is enabled.
```
It also complains if you pass an `async` function when a synchronous function is expected.
With default settings, the rule found three files of concern in the …

feat(eslint-config): enable "no-misused-promises" rule

---

packages/repository/src/__tests__/integration/repositories/resolve-has-many-metadata.integration.ts
packages/repository/src/__tests__/integration/repositories/resolve-has-one-metadata.integration.ts
packages/repository/src/relations/has-many/has-many.helpers.ts
packages/repository/src/relations/has-one/has-one.helpers.ts

Resolves https://github.com/strongloop/loopback-next/issues/3441.

feat(repository): add keyFrom to resolved relation metadata

---

packages/cli/generators/relation/templates/controller-relation-template-has-many.ts.ejs
packages/cli/test/integration/generators/relation.has-many.integration.js

_This pull request is a follow-up for https://github.com/strongloop/loopback-next/pull/3716#discussion_r324178656._
While adding a missing test I found that we have a bug in the current implementation 🙈This pull requests adds the missing test and fixes the implementation too.

fix(cli): fix schema title for POST operation in relation controllers

---

packages/rest/src/__tests__/acceptance/validation/validation.acceptance.ts
packages/rest/src/types.ts
packages/rest/src/validation/request-body.validator.ts

I'm currently doing some localization works, it should be easy by just using [`ajv-i18n`](https://github.com/epoberezkin/ajv-i18n):
```typescript
const localize_zh = require('ajv-i18n/localize/zh');
// option `i18n` is required for this package to work
var ajv = Ajv({ allErrors: true });
var validate = ajv.compile(schema);
var valid = validate(data);
if (!valid) {
localize_zh(validate.errors);
console.log(ajv.errorsText(validate.errors, { separator: '\n' }));
}
```
But I could find a way to do that.
After some searching & reading, I found #2146, I really need this feature, so I'm submitting a minimal change.
Advice needed (we can discus in #2146 ), thank you!
> See also #2146 
👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopbac …

feat(rest): allow AJV error messages customization

---

docs/site/Loopback-component-authentication.md
docs/site/decorators/Decorators_authenticate.md
packages/authentication/src/__tests__/unit/decorators/authenticate.decorator.unit.ts
packages/authentication/src/__tests__/unit/providers/auth-metadata.provider.unit.ts
packages/authentication/src/authentication.component.ts
packages/authentication/src/decorators/authenticate.decorator.ts
packages/authentication/src/keys.ts
packages/authentication/src/providers/auth-metadata.provider.ts
packages/authentication/src/providers/auth-strategy.provider.ts
packages/authentication/src/types.ts
packages/authorization/README.md
packages/authorization/src/__tests__/unit/authorize-decorator.test.ts
packages/authorization/src/authorize-interceptor.ts
packages/authorization/src/decorators/authorize.ts
packages/authorization/src/types.ts

This PR improves `@authenticate` (implements https://github.com/strongloop/loopback-next/issues/2460)
1. Allow `@authenticate` to be applied at class level
2. Add `@authenticate.skip` to skip authentication
It also improves `@authorize`:
1. Add `@authorize.skip` to skip authorization

Improve auth decorators

---

.prettierignore
packages/cli/package-lock.json
packages/cli/package.json
packages/cli/snapshots/integration/generators/controller.integration.snapshots.js
packages/cli/snapshots/integration/generators/datasource.integration.snapshots.js
packages/cli/test/integration/generators/controller.integration.js
packages/cli/test/integration/generators/datasource.integration.js
packages/cli/test/snapshot-matcher.js
packages/cli/test/snapshots.js

While working on https://github.com/strongloop/loopback-next/pull/3754 and thinking about how to test https://github.com/strongloop/loopback-next/pull/3688, I realized the current approach, where we write a bunch of regular expressions to match parts of the generated code, is no longer serving us well:
- The regular expressions are difficult to read. It's not clear how exactly does the generated code looks like.
- It's easy to write these regexes in such way that they don't catch significant changes (e.g. regressions).
- It's difficult to update the assertions when we improve some small aspects of the generated code.
In this pull request, I am proposing to introduce snapshot-based testing, as explained in [Jest's guide](https://jestjs.io/docs/en/snapshot-testing).
- Implement basic …

test(cli): introduce snapshot-based testing

---

packages/rest/src/__tests__/unit/rest.server/rest.server.unit.ts
packages/rest/src/keys.ts
packages/rest/src/rest.server.ts

feat(rest-server): add support for unix socket path

---

docs/site/exposing-graphql-apis.md

Without this, failed with address (port 3000) already in use
Error signing CLA: 👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-next) 👈
Should add `--cors` as well?

[doc] Add `--port=3001` as documented

---

packages/repository/src/__tests__/unit/repositories/legacy-juggler-bridge.unit.ts
packages/repository/src/repositories/legacy-juggler-bridge.ts

Fixes https://github.com/strongloop/loopback-next/issues/3671#issuecomment-529376105

fix(repository): allow model classes with recursive type references

---

docs/site/BelongsTo-relation.md
packages/repository-tests/src/crud-test-suite.ts
packages/repository-tests/src/crud/relations/acceptance/belongs-to.inclusion-resolver.relation.acceptance.ts
packages/repository-tests/src/crud/relations/acceptance/belongs-to.relation.acceptance.ts
packages/repository-tests/src/crud/relations/acceptance/has-many.relation.acceptance.ts
packages/repository-tests/src/crud/relations/acceptance/has-one.relation.acceptance.ts
packages/repository-tests/src/crud/relations/helpers.ts
packages/repository-tests/src/types.repository-tests.ts
packages/repository/src/__tests__/unit/repositories/relations-helpers/flatten-targets-of-one-to-one-relation.helpers.unit.ts
packages/repository/src/__tests__/unit/repositories/relations-helpers/relations-helpers-fixtures.ts
packages/repository/src/relations/belongs-to/belongs-to-accessor.ts
packages/repository/src/relations/belongs-to/belongs-to.helpers.ts
packages/repository/src/relations/belongs-to/belongs-to.inclusion-resolver.ts
packages/repository/src/relations/belongs-to/index.ts
packages/repository/src/relations/relation.helpers.ts

resolves https://github.com/strongloop/loopback-next/issues/3448
This PR implements the inclusionResolver for `belongsTo` relation:
- Add a helper `flattenTargetsOfOneToOneRelation` and its unit tests for `belongsTo` and `hasOne` relation ( since they both use this helper to implement inclusion resolver)
- Add a new function `createBelongsToInclusionResolver` into the belongsTo factory `createBelongsToAccessorFor `
- Add tests for `createBelongsToInclusionResolver` in `repository-tests`.
- introduce a new test-suite flag `supportsInclusionResolvers`.
- Add docs to explain the idea of `belongsToInclusionResolver`, and the basic setup/usages.
**Suggested way to review:**  
-> start with the document file and `belongs-to-inclusion-resolver.acceptance.ts` to get the idea of the `inclusion …

feat(repository): implement inclusionResolver for belongsTo relation 

---

docs/site/HasMany-relation.md
packages/repository-tests/src/crud/relations/acceptance/belongs-to.relation.acceptance.ts
packages/repository-tests/src/crud/relations/acceptance/has-many-inclusion-resolver.relation.acceptance.ts
packages/repository-tests/src/crud/relations/fixtures/repositories/customer.repository.ts
packages/repository-tests/src/crud/relations/helpers.ts
packages/repository/src/__tests__/unit/repositories/relations-helpers/flatten-targets-of-one-to-many-relation-helpers.unit.ts
packages/repository/src/__tests__/unit/repositories/relations-helpers/relations-helpers-fixtures.ts
packages/repository/src/relations/has-many/has-many-repository.factory.ts
packages/repository/src/relations/has-many/has-many.helpers.ts
packages/repository/src/relations/has-many/has-many.inclusion-resolver.ts
packages/repository/src/relations/has-many/index.ts
packages/repository/src/relations/relation.helpers.ts

resolves https://github.com/strongloop/loopback-next/issues/3447
This PR implements the inclusionResolver for `hasMany` relation:
- Add a helper `flattenTargetsOfOneToManyRelation` and its unit tests for `hasMany` 
- Add a new function `createHasManyInclusionResolver` to hasMany factory.
- Add tests for `hasManyInclusionResolver` in `repository-tests`.
- introduce a new test-suite flag `supportsInclusionResolvers`.
- Add docs to explain the idea of `hasManyInclusionResolver`, and the basic setup/usages.
**Suggested way to review:**
-> start with the document file and `hasmany-inclusion-resolver.acceptance.ts` to get the idea of the inclusion resolver
->  review `has-many.inclusion-resolver.ts` to see the implementation details.
-> review the rest of files.
👉 [Read and sign the CLA …

feat(repository): implement inclusionResolver for hasMany relation

---

packages/cli/snapshots/integration/cli/cli.integration.snapshots.js
packages/cli/test/integration/cli/cli.integration.js

I discovered this opportunity while working on https://github.com/strongloop/loopback-next/pull/3688 where I am adding a new CLI command.

test(cli): use snapshots to match list of commands in help

---

packages/cli/generators/model/index.js
packages/cli/generators/model/property-definition.js
packages/cli/lib/artifact-generator.js
packages/cli/lib/base-generator.js
packages/cli/lib/update-index.js
packages/cli/lib/utils.js
packages/cli/test/integration/lib/artifact-generator.js
packages/cli/test/integration/lib/base-generator.js
packages/cli/test/integration/lib/check-loopback-project.suite.js

While working on https://github.com/strongloop/loopback-next/pull/3688 (`lb4 import-lb3-model`), I discovered many obstacles preventing me from reusing existing code in my new generator.
This pull request contains a series of commits to make various bits in our CLI code base easier to use in new ways.
It may be best to review the changes commit-by-commit.

Refactor CLI code for easier reuse

---

examples/express-composition/src/__tests__/acceptance/express.acceptance.ts
examples/express-composition/src/application.ts
packages/rest-explorer/README.md
packages/rest-explorer/src/__tests__/acceptance/rest-explorer.acceptance.ts
packages/rest-explorer/src/__tests__/acceptance/rest-explorer.express.acceptance.ts
packages/rest-explorer/src/rest-explorer.component.ts
packages/rest-explorer/src/rest-explorer.controller.ts
packages/rest-explorer/src/rest-explorer.types.ts
packages/rest/src/__tests__/integration/rest.server.integration.ts
packages/rest/src/keys.ts
packages/rest/src/rest.server.ts

This PR updates the `rest-explorer` to, by default, cause the main `RestServer` to expose an additional copy of the OpenAPI spec at path that is fixed relative to the explorer itself.  The explorer then gives the path to the spec as a relative one.
The goal of this is to make the explorer work reliably when behind a reverse proxy that does non-trivial URL transforms (such as placing the app under a path prefix).  Since such reverse proxy configurations are generally external to the app, it may be difficult for the app to reliably know the absolute path to itself.
Making it use a relative URL for the OpenAPI spec means that it doesn't need to care at all about path or hostname transformations a proxy might apply.
This behavior is enabled by default, but possible to disable in case some …

feat: rest explorer now hosts its own copy of oas by default

---

docs/site/BelongsTo-relation.md
docs/site/HasMany-relation.md
docs/site/Relations.md
docs/site/hasOne-relation.md
packages/repository-tests/src/crud/relations/acceptance/belongs-to.relation.acceptance.ts
packages/repository-tests/src/crud/relations/acceptance/has-one.inclusion-resolver.acceptance.ts
packages/repository-tests/src/crud/relations/helpers.ts
packages/repository/src/relations/has-one/has-one-repository.factory.ts
packages/repository/src/relations/has-one/has-one.helpers.ts
packages/repository/src/relations/has-one/has-one.inclusion-resolver.ts

resolves https://github.com/strongloop/loopback-next/issues/3449
This PR implements the inclusionResolver for hasOne relation:
- Add a new function createHasOneInclusionResolver to hasOne factory.
- Add tests for hasOneInclusionResolver in repository-tests.
- Add docs to explain the idea of hasOneInclusionResolver, and the basic setup/usages.

feat(repository): implement inclusion resolver for hasOne relation

---

docs/site/tutorials/todo-list/todo-list-tutorial-repository.md
examples/todo-list/src/__tests__/integration/todo-list-image.repository.integration.ts
examples/todo-list/src/__tests__/integration/todo-list.repository.integration.ts
examples/todo-list/src/__tests__/integration/todo.repository.integration.ts
examples/todo-list/src/repositories/todo-list-image.repository.ts
examples/todo-list/src/repositories/todo-list.repository.ts
examples/todo-list/src/repositories/todo.repository.ts

`hasMany`, `belongsTo`, and `hasOne` factories have an inclusion resolver property that we can leverage in this example
Resolves https://github.com/strongloop/loopback-next/issues/3450

feat(example-todo-list): use real relation resolvers

---

packages/cli/test/snapshot-matcher.js

Two commits:
1. print help on updating snapshots when some snapshots were not matched
2. write snapshot files in parallel

Improve snapshot matcher

---

packages/authorization/src/__tests__/unit/util.test.ts
packages/authorization/src/authorize-interceptor.ts
packages/authorization/src/util.ts

Fixes #3766 and #3707 
Since PR https://github.com/strongloop/loopback-next/pull/3796 is created earlier I would like to respect @derdeka 's contribution, feel free to take code from this PR to save your time on adding tests/code refactor.
My only concern for #3796 is explained in [comment](https://github.com/strongloop/loopback-next/pull/3796#discussion_r328143044), after fixing it we can land it, then see if my PR still needed(improve #3796 or close it).

fix: user profile to principal

---

packages/testlab/src/__tests__/integration/test-sandbox.integration.ts
packages/testlab/src/test-sandbox.ts

Add `writeTextFile` method to `TestSandbox`.
Addresses https://github.com/strongloop/loopback-next/issues/3731.

feat: implement TestSandbox.writeTextFile

---

docs/site/Migrating-from-LoopBack-3.md
examples/lb3-application/src/migrate.ts
packages/booter-lb3app/fixtures/app-with-model.js
packages/booter-lb3app/src/__tests__/acceptance/booter-lb3app.acceptance.ts
packages/booter-lb3app/src/lb3app.booter.ts

Migrates LB4 models mounted on LB4 an app.
Fixes https://github.com/strongloop/loopback-next/issues/2825.

fix: migrate LB3 models mounted on LB4 app

---

packages/cli/lib/cli.js
packages/cli/snapshots/integration/cli/cli.integration.snapshots.js
packages/cli/test/integration/cli/cli.integration.js

I noticed the extra space while reviewing and editing snapshot files. At the moment, I cannot edit snapshot files manually because my editor is configured to remove trailing spaces, and thus breaks the snapshot on save.

fix(cli): remove extra SPACE at EOL in help output

---

packages/repository-json-schema/src/__tests__/integration/build-schema.integration.ts
packages/repository-json-schema/src/__tests__/unit/build-schema.unit.ts
packages/repository-json-schema/src/build-schema.ts

This PR is related with my comment in https://github.com/strongloop/loopback-next/issues/1466 about problems found during the process of deploy an API in Azure.
With this PR is possible to deploy an API as "App Service" and connect it with the API Manager as OpenAPI.
I added the optional key 'itExtendsCompatibility' (boolean) in JsonSchemaOptions to tackle these cases. By default uses the current behaviour.
Added some tests, applied prettier & linter of the project.
P.S: by the way, trying to sign your CLA gives a 504 Error in Cloudfront.

fix(repository-json-schema): update to pass openapi validation in azure

---

docs/site/tutorials/todo/todo-tutorial-controller.md
docs/site/tutorials/todo/todo-tutorial-datasource.md
docs/site/tutorials/todo/todo-tutorial-geocoding-service.md
docs/site/tutorials/todo/todo-tutorial-putting-it-together.md

Fixes: https://github.com/strongloop/loopback.io/issues/889

docs: update outdated links in todo tutorial

---

docs/site/BelongsTo-relation.md
docs/site/HasMany-relation.md
docs/site/hasOne-relation.md

Fixes wrong function name in relations docs: `registerInclusion` -> `registerInclusionResolver`

docs: fix wrong function name in relation docs

---

packages/rest-crud/README.md
packages/rest-crud/src/__tests__/unit/crud-rest-controller.unit.ts
packages/rest-crud/src/crud-rest.controller.ts

defineCrudRestController generates controller based on the Model's name.
Addresses https://github.com/strongloop/loopback-next/issues/3732.

feat: generate controller based on Model name

---

.github/ISSUE_TEMPLATE/Security_vulnerability.md

Update to use `reachsl@us.ibm.com` in the issue template. 
I've also searched for any instance of `callback@ibm.com` and no match. 

fix: update email in issue template

---

packages/authentication/src/__tests__/unit/types/register-authentication-strategy.unit.ts
packages/authentication/src/types.ts

Use case:
```ts
const binding = registerAuthenticationStrategy(app, MyAuthStrategy);
app.configure(binding.key).to(myAuthConfig);
```

feat(authentication): return binding for registerAuthenticationStrategy

---

examples/express-composition/index.js
examples/express-composition/src/__tests__/acceptance/express.acceptance.ts
examples/express-composition/src/observers/hello.observer.ts
examples/express-composition/src/observers/index.ts
examples/express-composition/src/server.ts
packages/rest/src/__tests__/integration/rest.server.integration.ts
packages/rest/src/rest.server.ts

Fixes https://github.com/strongloop/loopback-next/issues/3878

feat: allow LB4 app with lifecycle observers to be mounted to Express

---

docs/site/Server.md
docs/site/express-with-lb4-rest-tutorial.md

Document the feature introduced by #3879 

docs: document listenOnStart for REST servers

---

docs/site/Model.md

Changes Model.md to reflect a known issue with property reflection when dealing with type aliases and extracted types. See #3863. No code changes.

docs: changes Model.md to reflect known issue

---

docs/site/Usage-scenarios.md

Currently the [Usage scenario page](https://loopback.io/doc/en/lb4/Usage-scenarios.html) is empty. This PR adds some content in the page which serves as an index besides the sidebar. 

fix(docs): add content to usage-scenario page

---

docs/site/Relation-generator.md
packages/cli/generators/relation/base-relation.generator.js
packages/cli/generators/relation/belongs-to-relation.generator.js
packages/cli/generators/relation/has-many-relation.generator.js
packages/cli/generators/relation/index.js
packages/cli/snapshots/integration/generators/relation.belongs-to.integration.snapshots.js
packages/cli/snapshots/integration/generators/relation.has-many.integration.snapshots.js
packages/cli/test/integration/generators/relation.belongs-to.integration.js
packages/cli/test/integration/generators/relation.has-many.integration.js

Implements https://github.com/strongloop/loopback-next/issues/3451
(updated the cli relation tests with snapshots in https://github.com/strongloop/loopback-next/pull/3875)

feat(cli): add inclusion resolver to `lb4 relation`

---

docs/site/BelongsTo-relation.md

Fixes https://github.com/strongloop/loopback-next/issues/2639

docs: update belongsTo docs with decorator syntax

---

packages/repository-json-schema/src/__tests__/integration/build-schema.integration.ts

Modify the tests for JsonSchemaOption "exclude" to verify that"not" + "anyOf" is used to forbid excluded properties in data.
See the following discussion for background context: https://github.com/strongloop/loopback-next/pull/3895#discussion_r332545593
The PR that introduced the tests I am modifying: https://github.com/strongloop/loopback-next/pull/3297

test(repository-json-schema): verify "not.anyOf" in model schema

---

lerna.json

It happens very frequently for me with `npm run update-packages`, which is also part of our release process.
Sample error:
```
lerna ERR! npm install exited 254 in '@loopback/service-proxy'
lerna ERR! npm install stderr:
npm ERR! code ENOENT
npm ERR! syscall lchown
npm ERR! path /Users/rfeng/.npm/_locks/staging-1f9c9b6dc2a3f888.lock
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, lchown '/Users/rfeng/.npm/_locks/staging-1f9c9b6dc2a3f888.lock'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

chore: reduce concurrency to avoid bootstrap issues due to npm locks

---

packages/openapi-v3/src/__tests__/integration/controller-spec.integration.ts
packages/openapi-v3/src/__tests__/integration/operation-spec.integration.ts
packages/openapi-v3/src/__tests__/unit/filter-schema.unit.ts
packages/openapi-v3/src/__tests__/unit/json-to-schema.unit.ts
packages/openapi-v3/src/json-to-schema.ts
packages/repository-json-schema/src/__tests__/integration/build-schema.integration.ts
packages/repository-json-schema/src/__tests__/integration/schema-ref.integration.ts
packages/repository-json-schema/src/build-schema.ts
packages/repository-json-schema/src/filter-json-schema.ts
packages/rest-crud/src/__tests__/acceptance/default-model-crud-rest.acceptance.ts
packages/rest/src/__tests__/acceptance/validation/validation.acceptance.ts
packages/rest/src/__tests__/unit/rest.server/rest.server.open-api-spec.unit.ts
packages/rest/src/validation/request-body.validator.ts

In a recent discussion about using [openapi-to-graphql](https://loopback.io/openapi-to-graphql.html) with LoopBack apps, we found that the schema created by LoopBack 4 is difficult to interpret. Schema for creating new model instances (e.g. `NewTodo`) is excluding the PK property (e.g. `id`) using `not` and `anyOf` operators, see #3297.
IMO, we should not need to use such construct, it should be enough to omit the excluded property from the schema.
While investigating such fix, I found out that JSON Schema allows arbitrary additional properties by default (`additionalProperties: true`). At the same time, LoopBack 4 models are strict by default and don't allow arbitrary properties.
The first commit removes this inconsistency by modifying `repository-json-schema` to correctly set …

Simplify model schema with excluded properties

---

docs/site/Understanding-the-differences.md

The first commit switches the text from a giant Markdown table to raw HTML table that's easier to edit and review. No text changes were made here.
The second commit improves the content to reflect features delivered since the page was
created and adds more entries for LB3 features and components.
This PR is a part of https://github.com/strongloop/loopback-next/issues/3718
- Affected example projects in …

docs: update "Understanding differences between LB3 and LB4"

---

packages/openapi-v3/src/__tests__/unit/filter-schema.unit.ts
packages/openapi-v3/src/__tests__/unit/json-to-schema.unit.ts
packages/openapi-v3/src/json-to-schema.ts
packages/repository-json-schema/src/filter-json-schema.ts

Follow up to #2379
Copy first example from examples in JsonSchema to SchemaObject to be used in api explorer. This is a kind of workaround until the api explorer uses one of the listed examples or the default object.

feat(openapi-v3): copy first example from examples to schema

---

packages/cli/generators/model/index.js

* Questions have been ordered in favor of the id
* The question of "If the property is required" has been deleted after saying that the id property is generated

refactor(cli): change order of questions when creating models

---

docs/site/Migrating-from-LoopBack-3-redirect.md
docs/site/migration/auth/built-in.md
docs/site/migration/auth/oauth2.md
docs/site/migration/auth/overview.md
docs/site/migration/auth/passport.md
docs/site/migration/boot-scripts.md
docs/site/migration/cli.md
docs/site/migration/clients.md
docs/site/migration/datasources.md
docs/site/migration/express-middleware.md
docs/site/migration/extensions.md
docs/site/migration/models/core.md
docs/site/migration/models/methods.md
docs/site/migration/models/mixins.md
docs/site/migration/models/operation-hooks.md
docs/site/migration/models/overview.md
docs/site/migration/models/relations.md
docs/site/migration/models/remoting-hooks.md
docs/site/migration/mounting-lb3app.md
docs/site/migration/not-planned.md
docs/site/migration/overview.md
docs/site/sidebars/lb4_sidebar.yml

A skeleton of our migration guide, laying down the overall structure and creating placeholder pages that will be filled in later in follow-up pull requests.
Important: I am not aiming at covering all aspects of LB3 application development. This pull request is meant as the first step to allow incremental improvements in the (near) future.
<details>
<summary>Screenshot of the (final) sidebar</summary>
</details>
- …

docs: add a skeleton of migration guide

---

packages/booter-lb3app/src/__tests__/acceptance/booter-lb3app.acceptance.ts

Connect to https://github.com/strongloop/loopback-next/issues/3859.
Verify that an error is thrown if we can't find the lb3 application.

test(booter-lb3app): throw error if lb3 app is not found

---

bin/build-docs-site.sh
docs/site/migration/models/core.md

See https://github.com/strongloop/loopback-next/issues/3718

docs: describe how to migrate model definition & built-in APIs

---

examples/todo/src/__tests__/acceptance/todo.acceptance.ts
examples/todo/src/__tests__/helpers.ts
examples/todo/src/__tests__/integration/services/geocoder.service.integration.ts
examples/todo/src/datasources/geocoder.datasource.json
packages/http-caching-proxy/src/__tests__/integration/http-caching-proxy.integration.ts
packages/http-caching-proxy/src/http-caching-proxy.ts

The examples/todo depends on https://geocoding.geo.census.gov/geocoder/, which can be down once a while.
The PR improves http-caching-proxy with two new options:
1. timeout - timeout connecting to the target endpoint
2. logError - a flag to control if errors should be logged to console
It also makes the todo tests conditional on the availability of the geocoding service.

Improve http-caching-proxy and geocoder test

---

docs/site/tutorials/todo/todo-tutorial-geocoding-service.md

Fixing the code with the correct one (createTodo w/ geocode).
Fixes #3977

fix(docs): todoTutorial

---

packages/openapi-v3/src/__tests__/unit/json-to-schema.unit.ts
packages/openapi-v3/src/json-to-schema.ts
packages/repository-json-schema/src/__tests__/unit/build-schema.unit.ts
packages/repository-json-schema/src/build-schema.ts

Fixes https://github.com/strongloop/loopback-next/issues/3706

fix: allow json schema with circular refs to be converted to OpenAPI schema

---

acceptance/repository-mongodb/package-lock.json
acceptance/repository-mysql/package-lock.json
benchmark/package-lock.json
bin/rebuild-package-locks.js
examples/context/package-lock.json
examples/express-composition/package-lock.json
examples/greeter-extension/package-lock.json
examples/greeting-app/package-lock.json
examples/hello-world/package-lock.json
examples/lb3-application/package-lock.json
examples/log-extension/package-lock.json
examples/rpc-server/package-lock.json
examples/soap-calculator/package-lock.json
examples/todo-list/package-lock.json
examples/todo/package-lock.json
package-lock.json
package.json
packages/authentication/package-lock.json
packages/boot/package-lock.json
packages/booter-lb3app/package-lock.json
packages/build/package-lock.json
packages/cli/package-lock.json
packages/http-caching-proxy/package-lock.json
packages/repository/package-lock.json
packages/rest/package-lock.json
packages/service-proxy/package-lock.json
packages/testlab/package-lock.json
sandbox/example/package-lock.json

The PR introduces a Node.js script to rebuild package-lock.json files as follows:
1. Remove all `package-lock.json` and `node_modules` for all package, including the root
2. Run `npm install` to regenerate `package-lock.json` files
These steps seems to be most reliable to rebuild package-lock.json files for a lerna monorepo.

feat: rebuild package locks using a Node.js script

---

docs/site/tutorials/core/1-introduction.md
docs/site/tutorials/core/2-architecture.md
docs/site/tutorials/core/index.md

There are duplicate titles appear in the core-tutorial by removing the title in the main content because there's already title in the front matter. 

fix(docs): remove duplicate title in core-tutorial

---

examples/todo/src/__tests__/acceptance/todo.acceptance.ts
examples/todo/src/__tests__/integration/services/geocoder.service.integration.ts

I find the solution introduced by https://github.com/strongloop/loopback-next/pull/3979 very problematic. When the geocoder service is not available, we skip the test body and yet mark the test as passed. This creates a false sense of security, leading us to believe that the geocoding functionality is covered by tests and working, despite the fact that eventually we may get to the point when the test is always skipped.
In this pull request, I am improving the code to report the tests as skipped when the Geocoder service is not available.
This is not perfect, because we won't have any automated notification to let us know when the geocoder service becomes permanently broken, but at least we have a chance to notice the problem. …

test(example-todo): mark geocoding tests as skipped when the service is down

---

packages/rest-crud/README.md
packages/rest-crud/src/__tests__/acceptance/default-model-crud-rest.acceptance.ts
packages/rest-crud/src/__tests__/unit/define-crud-repository-class.unit.ts
packages/rest-crud/src/index.ts
packages/rest-crud/src/repository-builder.ts

Add `defineCrudRepositoryClass` - a helper to create named repository classes.
Addresses https://github.com/strongloop/loopback-next/issues/3733.

feat: add defineCrudRepositoryClass

---

package.json

We have `sort: "true"` in [lerna.json](https://github.com/strongloop/loopback-next/blob/master/lerna.json#L29) to maximize concurrency for `lerna run`. But for build, it should be run by the order of dependencies.

chore: ensure packages are built in order of dependencies

---

extensions/authentication-passport/README.md

Fixes https://github.com/strongloop/loopback-next/issues/4035
I shouldn't have added the "BREAKING CHANGE" keyword in https://github.com/strongloop/loopback-next/pull/3761/commits 's first commit, it bumps the version from 0.1.x to 1.x, while my intention was to release 0.2.x, that's why the experimental warning causes confusion.
I searched through our issues and I don't think or remember we have any further plan for the passport adapter module, and since it's already released for several months, I tend to remove the experimental warning. 
We can discuss better plan in this PR if people have different opinions. …

docs: remove ambiguous warning

---

packages/repository/src/query.ts

Fix a problem discovered by the upcoming TypeScript compiler version 3.7, see the discussion in https://github.com/strongloop/loopback-next/pull/3858 for more details.
Here is gist of the problem:
Before my change, when querying an `Author` model and including let's say `BlogPost` models written by the author, the `include` part of the filter was expecting `scope` property with `Filter<Author>` instead of `Filter<BlogPost>`. The latter is difficult to express, because Filter is recursive and when a `BlogPost` has many comments, then `Filter<BlogPost>` needs to accept `Filter<Comment>` in its nested `include[].scope`.
In this pull request, I am changing `include[].scope` property to accept `Filter` for any model. This new style is consistent with `include[].relation` property which is …

fix(repository): improve typings for model inclusion

---

packages/repository/src/relations/has-many/has-many.inclusion-resolver.ts
packages/repository/src/relations/has-one/has-one.inclusion-resolver.ts
packages/repository/src/relations/relation.types.ts

One more compilation errors to be fixed before upgrading to `typescript@3.7.2`.

fix(repository): fix compilation errors with TypeScript 3.7.2

---

docs/site/tutorials/todo/todo-tutorial-geocoding-service.md

After following all steps of the tutorial user ends up with `create` method name, not with the `createTodo` one.
There are no references of `createTodo` name on previous pages/steps.
So it looks confusing.

Fixes inconsistent naming.

---

packages/cli/lib/utils.js

Adds better output when failing to parse a datasource file for any reason, by including the filename of the datasource in question.
Fixes #3965

[WIP] Fix 3965

---

bin/checkout-pr.sh

Sometimes a LoopBack maintainer needs to help improve/fix a pull request.
This script allows us to set up the PR code base as follows:
1. Read the url and branch for base and head for the PR
2. Clone the forked repository and branch
3. Set up upstream to strongloop/loopback-next
4. Fetch changes from upstream branch
5. Rebase the PR branch to the upstream branch

chore: add a bash script to help check out code for a given PR

---

packages/cli/generators/discover/index.js

Before this change, `lb4 discover` prints out:
```
Discover RegionsModelTs was created in src/models/
```
With this PR:
```
DiscoveredModels Regions was created in src/models/ 
```

fix(cli): improve message for model discovery code generation

---

docs/site/submitting_a_pr.md

In the document `Submitting a pull request to LoopBack 4`, the link for `Commit Message Format` became invalid.
This PR fixes it.

docs: fix 'commit message format' link

---

packages/rest/src/__tests__/unit/router/controller-route.unit.ts
packages/rest/src/__tests__/unit/router/handler-route.unit.ts
packages/rest/src/keys.ts
packages/rest/src/router/controller-route.ts
packages/rest/src/router/handler-route.ts

Controller methods sometime want to access the corresponding OpenAPI operation spec.

feat(rest): bind operation spec to the request context

---

.eslintignore
.gitignore
.prettierignore
docs/bin/build-jekyll-preview-config.js
docs/bin/build-preview-site.sh
docs/site/DEVELOPING.md
package.json

Add a script `docs/bin/build-preview-site.sh` that creates a subset of loopback.io site with just enough content to support fast previews of LB4 documentation. Add monorepo-level npm scripts to simplify usage of the new build script.
Fixes #1310
Usage:
1. Run the script to create a new Jekyll site in `docs/_preview` dir:
$ npm run docs:prepare
2. Follow the instructions printed by the script to start Jekyll:
$ npm run docs:start
3. View the documentation.
4. Make changes to documentation files in `docs/site`.
5. Restart Jekyll (stop the running process and go to step 2).
The good parts:
- Initial build of LB4-only docs takes about 6 seconds. 🏇 (Compare to ~4 minutes for the entire docs site! 😱)
- Incremental rebuild after changing a single file takes less than a second. 🏎
Downsides:
- …

build(docs): add a script for fast previews of LB4 doc changes

---

packages/repository/src/__tests__/integration/repositories/resolve-belongs-to-metadata.integration.ts
packages/repository/src/__tests__/integration/repositories/resolve-has-many-metadata.integration.ts
packages/repository/src/__tests__/integration/repositories/resolve-has-one-metadata.integration.ts

Resolves https://github.com/strongloop/loopback-next/issues/3440.
Split into two commits: 
[1)](https://github.com/strongloop/loopback-next/pull/4046/commits/369d82850e6f3d040835de2e6e08e6d0d86fc957) Added tests to verify the correct relation type is used in `resolve{Relation}Metadata`.
[2)](https://github.com/strongloop/loopback-next/pull/4046/commits/00c95b1536251a3fcc173daf5ec5d73794bce480) Improved setup for `resolve{Relation}Metadata` tests based on https://github.com/strongloop/loopback-next/pull/4046#discussion_r343664021.

test(repository): verify relation type in `resolve{Relation}Metadata`

---

docs/site/sidebars/lb4_sidebar.yml

Add the sidebar for the core-tutorial
Here is what it looks like:

fix(docs): add sidebar for core-tutorial

---

docs/site/Dependency-injection.md
docs/site/Loopback-component-authentication.md
docs/site/decorators/Decorators_authenticate.md
docs/site/tutorials/authentication/Authentication-Tutorial.md
extensions/authentication-passport/README.md
extensions/authentication-passport/src/__tests__/acceptance/authentication-with-passport-strategy-adapter.acceptance.ts
packages/authentication/docs/controller-functions.md
packages/authentication/src/keys.ts

There are still a few places where we need to
replace AuthenticationBindings.CURRENT_USER from `authentication` package with SecurityBindings.USER from `security` package in documentation, mocha tests, and the passport adapter code/docs.
In `authentication` package,
const AuthenticationBindings.CURRENT_USER = SecurityBindings.USER
is being kept for backward compatibility but we should use
SecurityBindings.USER everywhere else.
Shopping Cart application no longer has any usage of AuthenticationBindings.CURRENT_USER; so that's good. Nothing to do there.

chore: replace CURRENT_USER with SecurityBindings.USER

---

packages/security/src/types.ts

`UserProfile` used to be exported by `authentication` module, but now it is exported by `security` module.
There is a comment that implies the `authentication` module still has the `UserProfile` interface.
This PR will change the comment to make it clear that `UserProfile` was previously exported by `authentication` module, but it now is exported from `security`.

chore: update a comment about UserProfile interface

---

packages/cli/generators/discover/index.js
packages/cli/generators/import-lb3-models/index.js
packages/cli/generators/openapi/index.js
packages/cli/generators/repository/index.js

When asking the user to select 1 or more items, e.g. models to import, require at least one item to be selected.
This prevents users from accidentally pressing ENTER instead of SPACE to select an item from the list, in which case the prompt is resolved with an empty list and thus the CLI command ends prematurely. …

feat(cli): improve UX of multi-item selection

---

docs/site/decorators/Decorators_inject.md
packages/context/src/__tests__/acceptance/class-level-bindings.acceptance.ts
packages/context/src/inject.ts

This minor improvement allows a class or provider to receive its own binding information.

feat(context): allow current binding to be injected with `@inject.binding`

---

docs/site/migration/models/overview.md
docs/site/migration/models/relations.md

Describe how to migrate model relations from LB3 to LB4.
Fix #3948

Migration guide for model relations

---

docs/site/Controller-generator.md
docs/site/Sequence.md
packages/cli/generators/controller/templates/src/controllers/controller-rest-template.ts.ejs
packages/cli/snapshots/integration/generators/controller.integration.snapshots.js

As LB4 supports inclusion, I think it's fair to allow users to traverse related models with `findById()` endpoint with CLI generated controllers.
Also, the [todoList example](https://github.com/strongloop/loopback-next/blob/master/examples/todo-list/src/controllers/todo-list.controller.ts#L129) enables such filters. I think they should be consistent as we have a note in [the site](https://loopback.io/doc/en/lb4/todo-list-tutorial.html):
```
This page was generated from the loopback-next/examples/todo-list/README.md
``` 

feat(cli): update controller template to enable filter for findById endpoint

---

packages/cli/generators/openapi/schema-helper.js
packages/cli/test/unit/openapi/schema-helper.unit.js

fix(cli): updated OAS 'date' type mapping to JS 'string'

---

packages/cli/generators/discover/import-discovered-model.js
packages/cli/generators/discover/index.js
packages/cli/generators/import-lb3-models/migrate-model.js
packages/cli/generators/model/index.js
packages/cli/generators/model/property-definition.js
packages/cli/snapshots/integration/generators/discover.integration.snapshots.js
packages/cli/snapshots/integration/generators/model.integration.snapshots.js
packages/cli/test/integration/generators/discover.integration.js
packages/cli/test/integration/generators/model.integration.js
packages/cli/test/unit/discover/import-discovered-model.test.js

This pull request fixes model discovery to correctly handle built-in types and convert e.g. `type: String` to `type: 'string'`, see https://github.com/strongloop/loopback-next/issues/3806.
I split the change into several smaller commits:
1. Add snapshots to CLI tests to give us better understanding of what code we are actually scaffolding. This is also needed to have a test that demonstrates the problem!
2. Refactor the current implementation to make the fix easier: extract helper function converting discovered model to template data, extract `findBuiltintType` helper.
These first steps are not changing observable behavior. With the preparations done, we can make the fixes now.
3. Emit correct property definitions for built-in types from `lb4 discover`.
4. Disconnect the datasource after …

fix(cli): emit correct property definitions for built-in types in discovered models

---

benchmark/package.json
examples/rpc-server/package.json

Without this change, `npm run clean` leaves `examples/rpc-server` in a state that `dist` is not re-populated with `npm run build` as there is a stale `tsbuildinfo` file.

chore: make sure *.tsbuildinfo is removed with `npm run clean` to force a clean build

---

packages/cli/lib/model-discoverer.js
packages/cli/lib/utils.js
packages/cli/test/unit/discover/import-discovered-model.test.js

Rework the code handling object-like property metadata (typically connector-specific conciguration) to use `stringifyObject` instead of `JSON.parse`. Resolve #3806.
Before this change, a model property discovered from a database could
look as follows:
```ts
@property({
type: String,
postgresql: {"columnName":"title","dataType":"text"},
})
title: String;
```
With this commit in place, the property definition is generated
in TypeScript style:
```ts
@property({
type: String,
postgresql: {columnName: 'title', dataType: 'text'},
})
title: String;
```
Please note that in a typical case, connector metadata won't fit into a single line. Ideally, we would like to split the object into multiple lines. Unfortunately, that requires more complex changes in the way how we are generating property …

Use stringifyObject instead of JSON.stringify for connector metadata

---

examples/rpc-server/package.json

chore(example-rpc-server): fix a typo in the npm scripts

---

packages/context/src/__tests__/unit/binding.unit.ts
packages/context/src/__tests__/unit/context.unit.ts
packages/context/src/binding.ts
packages/context/src/context.ts

I was trying to expose json metadata for the context hierarchy to REST as follows and realized that there are deficiencies in ctx.toJSON():
```ts
export class PingController {
@get('/metadata')
metadata(
@inject(CoreBindings.APPLICATION_INSTANCE) application: Context,
@inject(RestBindings.SERVER) server: Context,
@inject(RestBindings.Http.CONTEXT) request: Context,
): object {
return {
application,
server,
request,
};
}
}
```
ctx.inspect() can be now used to print out the context hierarchy in JSON.
This is useful for troubeshooting and rendering in UI.
With this PR, I can simplify the implementation:
```ts
@get('/metadata')
metadata(
@inject(RestBindings.Http.CONTEXT) request: Context,
): object {
return request.inspect();
}
``` …

feat(context): improve context/binding with inspect/toJSON for metadata dumping

---

packages/cli/lib/utils.js
packages/cli/test/integration/generators/controller.integration.js
packages/cli/test/integration/generators/model.integration.js

When creating a new artifact (e.g. Model or Repository) while the target directory does not exist yet (e.g. `src/models` or `src/repositories`), we used to abort CLI with a ENOENT error.
This commit is fixing our CLI to treat the missing directory as if it was empty and continue the operation if possible.

fix(cli): handle missing target artifact dir

---

.travis.yml
packages/eslint-config/eslintrc.js

Require users to await a promise before returning the result inside a `try` block. Otherwise the errors won't be caught by the catch block.
Require users to NOT await a promise when the result is immediately returned outside of a `try` block. This is a (micro)performance optimization to avoid unnecessary allocation of an extra Promise instance.
Rule docs: https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/return-await.md
~~At the moment (2019-11-28), eslint reports false positives, they should be fixed by https://github.com/typescript-eslint/typescript-eslint/pull/1270. This pull request cannot be landed until that patch is released & our package-lock files are updated with the new version of the eslint plugin.~~ 
The eslint fix was …

feat(eslint-config): enable return-await

---

packages/repository/src/common-types.ts

Add title property to Count schema definition under common types in order to enable better model
generation by third party tools such as https://github.com/OpenAPITools/openapi-generator
Without a title property the generator would simply name the count response as InlineObject<n>.  By adding the title property, the tooling can produce a model named after the object title.

feat(repository): add title property to Count schema definition

---

docs/site/Interceptors.md
packages/context/src/__tests__/acceptance/interception-proxy.acceptance.ts
packages/context/src/__tests__/acceptance/interceptor.acceptance.ts
packages/context/src/__tests__/unit/interceptor.unit.ts
packages/context/src/__tests__/unit/resolution-session.unit.ts
packages/context/src/binding.ts
packages/context/src/interception-proxy.ts
packages/context/src/interceptor.ts
packages/context/src/invocation.ts
packages/context/src/keys.ts
packages/context/src/resolution-session.ts
packages/rest/src/__tests__/acceptance/caching-interceptor/caching-interceptor.ts
packages/rest/src/__tests__/unit/router/controller-route.unit.ts
packages/rest/src/__tests__/unit/router/handler-route.unit.ts
packages/rest/src/router/base-route.ts
packages/rest/src/router/controller-route.ts
packages/rest/src/router/handler-route.ts

Interceptors can be invoked in the following cases:
1. A route to a controller method
2. A controller to a repository/service with injected proxy
3. A repository/service method invoked explicitly with `invokeMethod/invokeMethodWithInterceptors`
Some interceptors want to check invocationContext.source to decide if its logic should be applied. For example, an http access logger only cares about invocations from the rest layer to the first controller.
This is also useful for metrics, tracing and logging.
This PR sets `source` as follows:
- the ResolutionSession in `ProxySource` for injected proxies. 
- the Rest Route in `RouteSource` for REST
👉 [Check out how to submit …

feat(context): make it possible to set source information for interceptions

---

examples/hello-world/README.md

The link to `src/application.ts` mentioned in
https://www.npmjs.com/package/@loopback/example-hello-world
was giving a 404.
Update the underlying link to be : https://github.com/strongloop/loopback-next/blob/master/examples/hello-world/src/application.ts   

docs: fix link to src/application.ts in @loopback/example-hello-world

---

.travis.yml

With Node.js version 12 already in LTS mode, it's time to upgrade our Travis jobs to use the latest & greatest & fastest! version of Node.
Also note that the version 8 is going end of life soon, it's time to upgrade to a newer one.

chore: upgrade Node to 12.x for Travis jobs

---

packages/repository-tests/src/crud/relations/acceptance/has-many-inclusion-resolver.relation.acceptance.ts
packages/repository-tests/src/crud/relations/acceptance/has-many.relation.acceptance.ts
packages/repository-tests/src/crud/relations/acceptance/has-one.relation.acceptance.ts
packages/repository-tests/src/crud/relations/helpers.ts
packages/repository-tests/src/crud/replace-by-id.suite.ts
packages/repository/src/__tests__/unit/repositories/legacy-juggler-bridge.unit.ts
packages/repository/src/repositories/legacy-juggler-bridge.ts

implements https://github.com/strongloop/loopback-next/issues/3439.
Add two new protected methods:
`DefaultCrudRepository.ensurePersistable` and `DefaultCrudRepository.entityToData`.
This new function checks `create*(), update*(), save(), delete*(), and replaceById()` methods. Throws when the target data ( the one we are going to create, update) contains navigational properties: 
```
target data: {id: 1, name: 'cusotmer', orders: [{id: 1...}]}
```
- in the `ensurePersistable`, the `//FIXME` from @bajtos says mongoDB would break `replaceById` with ObjectID issue if we apply `ensurePersistable` to `replaceIdBy`. 
By debugging, I think it's caused by replacing the **id project** (`ObjectID` type) to a **string type id**. ~So in my proposal, I remove the id property from the target data for …

feat(repository): rejects create/update operations for navigational  properties

---

docs/site/Authentication-passport.md
docs/site/Metrics.md
docs/site/Using-extensions.md
docs/site/sidebars/lb4_sidebar.yml

feat(docs): expose docs for extension modules

---

packages/repository/src/__tests__/unit/common-types.unit.ts
packages/repository/src/__tests__/unit/model/define-model-class.unit.ts
packages/repository/src/common-types.ts
packages/repository/src/define-model-class.ts
packages/repository/src/index.ts

_See #4235 for background context._
Implement a new helper function that allows LB4 users to create
model classes dynamically at runtime. This is similar functionality
as offered by LB3, but with the benefit of compile-time type checks.
Example use:
```ts
const definition = new ModelDefinition('Product')
.addProperty('id', {type: 'number', id: true})
.addProperty('name', {
type: 'string',
});
const Product = defineModelClass<
typeof Entity,
{id: number; name: string}
>(
Entity,
definition,
);
```
While testing this code, I found a bug in `DeepPartial<T>` that I have experienced before. This time I could not ignore it because one of my tests would fail, so I am finally fixing it (see the first commit). Consider the following code:
```ts
function create<T extends object>(data?: …
```

repository: Add `defineModelClass` helper and fix `DeepPartial<AnyObject>`

---

docs/site/BelongsTo-relation.md
docs/site/HasMany-relation.md
docs/site/hasOne-relation.md
packages/repository-tests/src/crud/relations/acceptance/belongs-to.inclusion-resolver.relation.acceptance.ts
packages/repository-tests/src/crud/relations/acceptance/has-many-inclusion-resolver.relation.acceptance.ts
packages/repository-tests/src/crud/relations/acceptance/has-one.inclusion-resolver.acceptance.ts
packages/repository-tests/src/crud/relations/acceptance/multi-relations-inclusion-resolver.relation.acceptance.ts
packages/repository/src/__tests__/unit/repositories/relations-helpers/find-by-foreign-keys.unit.ts
packages/repository/src/relations/relation.helpers.ts

Implements https://github.com/strongloop/loopback-next/issues/3453
This will allow using custom scope in inclusion. Example:
```
Order: [{id: 1, customerId: 1, name: "to be excluded"}, {id: 2, customerId: 1, name: "to be included"}]
result = await customerRepo.find({
include: [
{
relation: 'orders',
scope: {where: {id: 2}, include: [{relation: 'customer'}]},
},
],
});
```
the result should be:
```
[{ id: 1, 
name: 'IBM', 
orders:[
{id: 2, 
customerId: 1, 
name: "to be included",
customer: {id: 1, name: 'IBM'}
}
]
}]
```

feat(repository): enable inclusion with custom scope

---

examples/express-composition/src/controllers/ping.controller.ts
packages/cli/generators/app/templates/src/controllers/ping.controller.ts.ejs

Add title property to ping response schema definition in order to enable better model
generation by third party tools such as https://github.com/OpenAPITools/openapi-generator .
Without a title property the generator would simply name the ping response as `InlineResponse200`. By adding the title property, the tooling can produce a model named after the object title.
Similar to #4240

feat: add title property to ping response schema definition

---

docs/site/HasMany-relation.md
docs/site/hasOne-relation.md

Use orders property instead of products property to make the example code snippet correct

docs: fix example code snippet

---

extensions/metrics/README.md

Jekyll does not interpret markup like `:warning:` and as a result, the Metrics page was showing the following heading:
In this patch, I am replacing `:warning:` with the actual emoji glyph, i.e. `⚠️`. This fixes the rendered page, see the screenshot from `npm run docs:start`:
/cc @raymondfeng 

fix(docs): replace emoji markup with an emoji glyph

---

docs/site/Loopback-component-authorization.md

The anchor links in the [authorization page](https://loopback.io/doc/en/lb4/Loopback-component-authorization.html) are not working. The links are working as markdown file but not after they get generated with Jekyll. 

fix(docs): fix anchor link in authorization page

---

README.md

Add @derdeka, @dougal83 and @achrinza to the list of maintainers.
It looks like GitHub is not able to down-scale the auto-generated avatars :(
@derdeka @dougal83 Would you mind updating your profile to set your own avatar? It does not have to be your real picture, any image will do.
I will understand if you don't want to, in which case I am proposing to leave out the auto-generated avatars from the table in the README.
@dhmlau I would like to wait for  @derdeka, @dougal83 and @achrinza to approve this pull request before it's landed. To avoid waiting until I get back from my vacation, can you please take care of this pull request for me?
- New tests added or existing …

chore: add new maintainers to README 🚀

---

docs/ROADMAP.md

Based on our initial discussion in https://ibm.ent.box.com/notes/556759029402, I'm creating this PR to capture the 2020 Q1 roadmap.

feat(docs): add 2020Q1 roadmap

---

packages/repository/src/relations/relation.types.ts

Adds interface for the new relation type "hasManyThrough" to support many-to-many model relations.
This PR is a continuation of #2359 and implements the first change described in https://github.com/strongloop/loopback-next/pull/2359#issuecomment-559719080.

feat(repository): add interface for hasManyThrough

---

docs/site/Loopback-component-authentication.md

The example snippet fails to work correctly without the following proposed added line.
```
import {AuthenticationComponent} from '@loopback/authentication';
```
- [Y] `npm test` passes on your machine
- [N ] New tests added or existing tests modified to cover all changes
- [N] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [N] API Documentation in code was updated
- [Y] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [N] Affected artifact templates in `packages/cli` were updated
- [N] Affected example projects in `examples/*` were updated …

fix(docs): add import authentication component

---

packages/core/src/__tests__/unit/lifecycle-registry.unit.ts

The timeout based assumption is not always reliable in CI.

chore(core): fix the assertion for parallel run of observers within the same group

---

docs/site/Database-migrations.md

part of https://github.com/strongloop/loopback-connector-postgresql/pull/404

docs: add link to connectors page as reference for auto-migrate

---

.vscode/settings.json

`eslint.autoFixOnSave` has been deprecated and replaced by `source.fixAll.eslint` (see https://github.com/microsoft/vscode-eslint/blob/master/README.md#release-notes - 2.0.4)

chore: update eslint fix on save settings

---

docs/site/Extending-OpenAPI-specification.md
docs/site/sidebars/lb4_sidebar.yml
packages/openapi-v3/package-lock.json
packages/openapi-v3/package.json
packages/openapi-v3/src/__tests__/unit/enhancers/fixtures/application.ts
packages/openapi-v3/src/__tests__/unit/enhancers/fixtures/info.spec.extension.ts
packages/openapi-v3/src/__tests__/unit/enhancers/fixtures/security.spec.extension.ts
packages/openapi-v3/src/__tests__/unit/enhancers/spec-enhancer.extensions.unit.ts
packages/openapi-v3/src/controller-spec.ts
packages/openapi-v3/src/decorators/api.decorator.ts
packages/openapi-v3/src/decorators/operation.decorator.ts
packages/openapi-v3/src/decorators/parameter.decorator.ts
packages/openapi-v3/src/decorators/request-body.decorator.ts
packages/openapi-v3/src/enhancers/index.ts
packages/openapi-v3/src/enhancers/keys.ts
packages/openapi-v3/src/enhancers/spec-enhancer.service.ts
packages/openapi-v3/src/enhancers/types.ts
packages/openapi-v3/src/index.ts
packages/openapi-v3/src/keys.ts

connect to https://github.com/strongloop/loopback-next/issues/3854
- Created a service as extension point for OpenAPI spec enhancers under folder `src/enhancers`.
- the extension point is created in file `spec-enhancer.service.ts`
- `types.ts` describes the extension interface
- `keys.ts` gives the extensionpoint a key
- Added two extensions in test fixtures, they are also the demo example for extension contributors
- add info spec
- add security spec
- Added unit test for service utility functions like `findEnhancerByName`, `applyEnhancerByName`, `generateSpec`
- Feedback addressed: 
- renamed the extension point to be enhancer instead of contributor(the name is still open for discussion, opinions are welcomed.)
- based on discussion in …

feat: openapi spec contributor extension point

---

packages/repository-tests/src/crud/relations/acceptance/belongs-to.relation.acceptance.ts
packages/repository/src/relations/belongs-to/belongs-to-accessor.ts

fixes https://github.com/strongloop/loopback-next/issues/4147
Relates to https://github.com/strongloop/loopback-next/issues/2333
For instances:
```
Customer {
id: 1,
name: 'exists'
}
Order {
id: 1,
name: 'has fk',
customerId: 1
}
Order {
id: 2,
name: 'customer doesn't exist',
customerId: 999
}
Order {
id: 3,
name: 'no fk',
}
```
The result of await `orderRepo.customer(order.id = 3);` returns the first customer in the database even it doesn't have the foreign [key](url)
**After reading through #2333, this is only a workaround.**
~Should check the foreign key value of the source instance.
Since different databases use different empty value, we check both `undefined` and `null`.~
I think this issue can be closed as duplicate.. 
- when user uses lb4, the memory connector is mostly for …

fix(repository): belongsTo accessor should return undefined if foreign key is not included

---

docs/site/BelongsTo-relation.md
docs/site/HasMany-relation.md
docs/site/hasOne-relation.md
packages/repository-tests/src/crud/relations/acceptance/belongs-to.inclusion-resolver.relation.acceptance.ts
packages/repository-tests/src/crud/relations/acceptance/belongs-to.relation.acceptance.ts
packages/repository-tests/src/crud/relations/acceptance/has-many-inclusion-resolver.relation.acceptance.ts
packages/repository-tests/src/crud/relations/acceptance/has-many.relation.acceptance.ts
packages/repository-tests/src/crud/relations/acceptance/multi-relations-inclusion-resolver.relation.acceptance.ts
packages/repository-tests/src/crud/relations/fixtures/models/order.model.ts
packages/repository-tests/src/crud/relations/fixtures/models/shipment.model.ts
packages/repository-tests/src/crud/relations/fixtures/repositories/shipment.repository.ts
packages/repository-tests/src/crud/relations/helpers.ts
packages/repository/src/relations/has-many/has-many.helpers.ts
packages/repository/src/relations/has-one/has-one.helpers.ts
packages/repository/src/relations/relation.types.ts

LB4 relation `hasMany` and `hasOne` use the mode id property as the source key. However, there are cases use would like to define a non-id property as their source key in these two relations ( in the other words, join tables on non-id attribute). 
- `Customer` has many `Order`s. 
- `Customer` has many `Review`s.
Traditionally, `Order` takes the id property `Customer.customerId` as it's foreign key.
**This feature would allow `Review` to have the non-id property `Customer.articleId` as its foreign key.**
Users could travers order and also reviews with different attributes.
Similar to the `belongTo` relation, this PR enables the custom source key, which is `keyFrom` in lb4 relation metadata. The feature should also work with inclusion. …

feat(repository): allow custom keyFrom for hasMany and hasOne

---

docs/site/migration/datasources.md

Add steps to migrate LB3 datasources to LB4. Closes https://github.com/strongloop/loopback-next/issues/3946.

docs: migrate datasources from lb3 to lb4

---

docs/site/migration/datasources.md

fix(docs): fix formatting for datasource migrations

---

docs/site/migration/boot-scripts.md

connect to https://github.com/strongloop/loopback-next/issues/3957
This PR contains the migration guide for LB3 boot script, and two observers migrated from 2 typical LB3 scripts as demo. After the doc gets approved, I will delete the code part.
An outline of the covered topics:

docs: boot script migration

---

extensions/health/README.md

See also #4289 
Adds a notice to inform users of the mandatory function calling order of `this.component()` and `this.configure()` to prevent a 404 HTTP error.

docs(extension-health): add function call-order note

---

packages/repository-tests/src/crud/relations/acceptance/has-many.relation.acceptance.ts
packages/repository/src/__tests__/unit/repositories/legacy-juggler-bridge.unit.ts
packages/repository/src/repositories/legacy-juggler-bridge.ts

related https://github.com/strongloop/loopback-next/issues/4392,  [stackoverflow](https://stackoverflow.com/questions/59468329/unhandled-error-in-post-order-products-500-error-navigational-properties-are)
The `belongsTo` generator generates the default relation name by taking the `@belongsTo` decorated name then removing `Id` from it. **Idealy**, the default fk name is expected to be `customerId`, and the ideal relation name will be `customer` ([code]( https://github.com/strongloop/loopback-next/blob/master/packages/repository/src/relations/belongs-to/belongs-to.decorator.ts#L45)).
However, lots of users would come up with their own customized name, `customer_id` for example.  And the default relation name generated by the belongsTo will be `customer_id` according to the code. This is …

fix(repository): make the navigational property err msg more clear

---

docs/site/BelongsTo-relation.md
docs/site/HasMany-relation.md
docs/site/hasOne-relation.md

Related https://github.com/strongloop/loopback-next/issues/4392,  [stackoverflow](https://stackoverflow.com/questions/59468329/unhandled-error-in-post-order-products-500-error-navigational-properties-are)
The `belongsTo` generator generates the default relation name by taking the `@belongsTo` decorated name then removing `Id` from it. **Idealy**, the default fk name is expected to be `customerId`, and the ideal relation name will be `customer` ([code]( https://github.com/strongloop/loopback-next/blob/master/packages/repository/src/relations/belongs-to/belongs-to.decorator.ts#L45)).
However, lots of users would come up with their own customized name, `customer_id` for example.  And the default relation name generated by the belongsTo will be `customer_id` according to the code. This is …

docs: update belongsTo relation metadata

---

docs/site/Server.md
packages/rest-explorer/README.md

Add instructions to completely disable API explorer for both remote and self-hosted.
See also #4138

docs: add instruction to remove api explorer

---

packages/openapi-v3/src/__tests__/unit/json-to-schema.unit.ts
packages/openapi-v3/src/json-to-schema.ts

feat(openapi-v3): add support for `anyOf` and `oneOf` on the `jsonToSchemaObject` utility

---

packages/repository/src/relations/has-many/has-many-through.repository.ts

The hasManyThrough repository interface defines the actions that can be performed on a many-to-many model relation.
This PR is a continuation of https://github.com/strongloop/loopback-next/pull/2359 and implements a step from https://github.com/strongloop/loopback-next/pull/2359#issuecomment-559719080.
Relates to: https://github.com/strongloop/loopback-next/pull/4247

feat(repository): add interface for hasManyThrough repository

---

examples/todo-list/.eslintrc.js
examples/todo/.eslintrc.js

Fixes https://github.com/strongloop/loopback-next/issues/4205

lint: ignore js file

---

.vscode/settings.json
packages/cli/generators/project/templates/.vscode/settings.json

Latest version of vscode prompts us to update deprecated settings.

chore: update vscode settings for eslint

---

docs/site/Interceptor-generator.md
packages/cli/generators/interceptor/templates/interceptor-template.ts.ejs
packages/cli/snapshots/integration/generators/interceptor.integration.snapshots.js
packages/cli/test/integration/generators/interceptor.integration.js

While working on #3950, I discovered that non-global interceptors are difficult to use via `@intercept` when they are implemented as provider classes. In this pull request, I am improving the CLI templates to add a static property `BINDING_KEY` when generating a new non-global interceptor.
At the moment, we have to use a magic string to reference an interceptor:
```ts
@inject('interceptors.FooBarInterceptor')
```
With my change in place, we can use the new static variable instead:
```ts
@inject(FooBarInterceptor.BINDING_KEY)
```
The pull request has two commits:
1. The first commit reworks interceptor tests to use snapshot-based assertions, no changes in the actual functionality as made.
2. The second commit modifies the template per the feature description above.
👉 [Read and sign the CLA …

feat(cli): add static BINDING_KEY prop to non-global interceptors 

---

examples/todo/src/datasources/geocoder.datasource.config.json
packages/cli/generators/service/index.js
packages/cli/test/fixtures/service/index.js
packages/cli/test/integration/generators/remote-service.integration.js

When generating a service using `lb4 service`, the generator would look for a `name` property in the config file of the datasource and if it didn't include it, it would still generate the service with errors.
For example:
```ts
import {getService} from '@loopback/service-proxy';
import {inject, Provider} from '@loopback/core';
import {Error: bad inputDataSource} from '../datasources'; // notice this import statement
export interface Geocoder {
// this is where you define the Node.js methods that will be
// mapped to REST/SOAP/gRPC operations as stated in the datasource
// json file.
}
export class GeocoderProvider implements Provider<Geocoder> {
constructor(
//  must match the name property in the datasource json file
// **SEE THE FOLLOWING TWO LINES**
@inject('datasources.')
protected …
```

fix(cli): reject datasources with no name property for service generator

---

docs/site/BelongsTo-relation.md
docs/site/HasMany-relation.md
docs/site/Relation-generator.md
packages/cli/generators/relation/base-relation.generator.js
packages/cli/generators/relation/belongs-to-relation.generator.js
packages/cli/generators/relation/has-many-relation.generator.js
packages/cli/generators/relation/index.js
packages/cli/generators/relation/templates/controller-relation-template-has-many.ts.ejs
packages/cli/lib/utils.js
packages/cli/snapshots/integration/generators/relation.belongs-to.integration.snapshots.js
packages/cli/snapshots/integration/generators/relation.has-many.integration.snapshots.js
packages/cli/test/fixtures/relation/index.js
packages/cli/test/fixtures/relation/models/no-key.model.ts
packages/cli/test/fixtures/relation/models/no-repo.model.ts
packages/cli/test/fixtures/relation/repositories/no-key.repository.ts
packages/cli/test/fixtures/relation/repositories/order.repository.ts
packages/cli/test/integration/generators/relation.belongs-to.integration.js
packages/cli/test/integration/generators/relation.has-many.integration.js

Fixes https://github.com/strongloop/loopback-next/issues/3287 and https://github.com/strongloop/loopback-next/issues/4209
1st commit: code changes
2nd commit: tests
- **hasMany**
? SourceModel: `Customer`
? DestModel: `Order`,
? Foreign key to define on the target model: `customerId`
? Source property name for the relation getter: `orders
? Allow Order queries to include data from related Customer instances? Yes
==> issues:
- if generation gets aborted, part of code still gets generated in Model and Repository 
- the default value doesn't match with the code in `/repository/relation`
- **belongTo**
? SourceModel: `Order`
? DestModel: `Customer`,
? Source property name for the relation getter: `customerId`
? Allow ..inclusion? Yes
==> issues:
- if generation gets aborted, part of code …

fix(cli): discard changes if lb4 `relation` fails. Allow customized relation name for belongsTo

---

MAINTAINERS.md

This PR is to update [`MAINTAINERS.md`](https://github.com/strongloop/loopback-next/blob/0ca8cd1840300643958c264b4d79f1bdc3f5a77a/MAINTAINERS.md) to include the new maintainers as per-[`README.md`](https://github.com/strongloop/loopback-next/blob/0ca8cd1840300643958c264b4d79f1bdc3f5a77a/README.md).

chore: update community maintainers on MAINTAINERS.md

---

docs/site/migration/models/remoting-hooks.md

Resolve https://github.com/strongloop/loopback-next/issues/3950:
> Write content for `docs/site/migration/models/remoting-hooks.md`, explain how to migrate LB3 remoting hooks to LB4 interceptors.
>
> Explain how to map properties provided by LB3 remoting context to LB4 concepts
and how to access that data via Dependency Injection.
👉 [Check out how to submit …

feat(docs): migration guide for remoting hooks

---

docs/site/Server.md

The `@loopback/rest` package now defaults `rest.url` to `https://explorer.loopback.io`. This PR is to update the docs to reflect these changes.

docs: update default external explorer URL

---

docs/site/Understanding-the-differences.md

docs: remove @loopback/passport-authentication experimental warning

---

docs/site/Understanding-the-differences.md
docs/site/index.md

Currently, LoopBack 4 does not provide full parity of the features from LoopBack 3. This PR is intended to add a warning for existing users of LoopBack 3 on the docs page (see: https://github.com/strongloop/loopback-next/issues/1920#issuecomment-563309178).
While there is a [pinned issue](https://github.com/strongloop/loopback-next/issues/1920) to keep track of this, it may be hidden to the average user. Hence, this PR intends to put forward the pinned issue in more clearly.
This is to prevent users from taking extra time to work around the lack of feature parity that may not have been known to them due to lack of warning in the docs. …

docs: add lb3 parity warnings

---

docs/site/Model.md

connects to https://github.com/strongloop/loopback-next/issues/4042. Related to https://github.com/strongloop/loopback-datasource-juggler/pull/1817

docs: specify strict:false is only supported by NoSQL DBs

---

docs/site/Binding.md
docs/site/Context.md
packages/context/src/__tests__/unit/binding.unit.ts
packages/context/src/__tests__/unit/context-observer.unit.ts
packages/context/src/__tests__/unit/context.unit.ts
packages/context/src/binding.ts
packages/context/src/context-observer.ts
packages/context/src/context.ts

Spin-off from #4377 
1. Add `ContextEventListener` interface
2. Tidy up parent context event handling
3. Set `maxListeners` to `Infinity` by default

feat(context): improve context listener and events

---

packages/cli/generators/openapi/index.js
packages/cli/generators/openapi/templates/src/models/model-template.ts.ejs
packages/cli/snapshots/integration/generators/openapi-petstore.integration.snapshots.js
packages/cli/snapshots/integration/generators/openapi-uspto-with-anonymous.integration.snapshots.js
packages/cli/snapshots/integration/generators/openapi-uspto.integration.snapshots.js
packages/cli/test/integration/generators/openapi-petstore.integration.js
packages/cli/test/integration/generators/openapi-uspto-with-anonymous.integration.js
packages/cli/test/integration/generators/openapi-uspto.integration.js

fixes: https://github.com/strongloop/loopback-next/issues/4135
- The first commit refactors openapi cli tests with snapshot
- The second commit fixes the generator so that the index files get updated correctly. Also adds relation interface to the openAPI model template so that when it generates repositories from these models, it won't complain that `xxxRelations` doesn't exist.

fix(cli): openAPI generator should update index files. Add relation interfaces to model template.

---

packages/openapi-v3/src/__tests__/unit/filter-schema.unit.ts
packages/repository-json-schema/src/__tests__/unit/filter-json-schema.unit.ts
packages/repository-json-schema/src/filter-json-schema.ts

Adding titles to json filter schemas as groundwork toward openapi spec ref consolidation based on title property. See #4290

Add title to filter schemas

---

packages/repository-tests/src/crud/freeform-properties.suite.ts

connects to https://github.com/strongloop/loopback-next/issues/4042
The test is for the change in https://github.com/strongloop/loopback-datasource-juggler/pull/1817

test(repository-tests): add a test for SQL DBs strict mode warning

---

docs/site/BelongsTo-relation.md
docs/site/HasMany-relation.md
docs/site/Relations.md
docs/site/hasOne-relation.md

See also: #4435, #4299, #4354
This PR adds documentation on the common limitations of `inclusionResolver()` and its related issues/PRs.
This is to reduce the difficulty of finding information on these kinds of limitations; of which some may assume are standard features of LoopBack 4.

improvement(docs): add limitations of inclusionResolver

---

packages/tsdocs/src/__tests__/acceptance/tsdocs.acceptance.ts
packages/tsdocs/src/helper.ts
packages/tsdocs/src/update-api-md-docs.ts

See https://github.com/strongloop/loopback-next/issues/4467
This is the 1st step to fix #4467. The generated md files now have `editurl` metadata.
The next step is to fix https://github.com/strongloop/loopback.io/blob/gh-pages/_layouts/page.html#L15 to allow `editurl` to customize the default calculation.

feat(tsdocs): fix package url and add editurl to page metadata

---

examples/context/src/context-observation.ts
packages/context/src/__tests__/acceptance/interceptor.acceptance.ts
packages/context/src/__tests__/unit/binding-filter.unit.ts
packages/context/src/__tests__/unit/context-observer.unit.ts
packages/context/src/__tests__/unit/context-tag-indexer.unit.ts
packages/context/src/__tests__/unit/context-view.unit.ts
packages/context/src/__tests__/unit/context.unit.ts
packages/context/src/binding-filter.ts
packages/context/src/context-event.ts
packages/context/src/context-observer.ts
packages/context/src/context-subscription.ts
packages/context/src/context-tag-indexer.ts
packages/context/src/context-view.ts
packages/context/src/context.ts
packages/context/src/index.ts
packages/context/src/interceptor.ts
packages/context/src/invocation.ts
packages/context/src/value-promise.ts
packages/rest/src/__tests__/integration/request-context.integration.ts

Fixes #4356 and #4363 
Matching all bindings by a filter function can be expensive. This PR improves performance for one of the primary usage - find bindings by tags.
Main changes in this PR:
1. Make `Binding` to be `EventEmitter` - emitting events when binding scope/tags/value are changed
2. Set up listeners in `Context` to react to binding events to maintain an index of bindings by tag
3. Optimize `Context.findByTag` to leverage binding index if possible
4. Change interceptor to find matching global interceptors by tag

feat: improve context.find/findByTag() and interceptor perf

---

packages/openapi-spec-builder/src/__tests__/unit/openapi-spec-builder.unit.ts
packages/openapi-spec-builder/src/openapi-spec-builder.ts

extend builder to include components schema
See also #4365

feat(openapi-spec-builder): add components schema

---

packages/openapi-v3/src/__tests__/unit/x-ts-type.unit.ts
packages/openapi-v3/src/controller-spec.ts

Partially implements: #4300 
See: #4406
This has been split from #4406 as a more manageable, smaller PR.
This PR adds support for using `x-ts-type` schema bodies the value of `anyOf`, `allOf`, `oneOf`, and `not` schema object keys, as described by the [OpenAPI Schema Object specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#schema-object).  In this example `ResponseObject`:
```ts
{
description: 'Path Response Description',
content: {
'application/json': {
schema: {
anyOf: [
{ 'x-ts-type': CouldBeThisModel },
{ 'x-ts-type': OrThisModel } 
],
not: { 'x-ts-type': ButNotThisModel }
}
}
}
}
```

feat/complex-x-ts-types - Adds supports for using x-ts-type in `anyOf`, `allOf`, `oneOf`, and `not` keywords

---

packages/cli/generators/relation/has-many-relation.generator.js
packages/cli/snapshots/integration/generators/relation.has-many.integration.snapshots.js
packages/cli/test/integration/generators/relation.has-many.integration.js

Fix relation controller. Currently it's using the **default relation name** in the template. It's supposed to use the relation name defined by CLI. 
A test is modified to verify the new change.
Also delete a redundant test in this PR.
BelongsTo controller has the correct setup : https://github.com/strongloop/loopback-next/blob/master/packages/cli/generators/relation/belongs-to-relation.generator.js#L49

fix(cli): fix hasMany relation controller artifacts

---

packages/repository-json-schema/src/__tests__/unit/filter-json-schema.unit.ts
packages/repository-json-schema/src/filter-json-schema.ts

add title property to IncludeFilter items
See also #4355

feat(repository-json-schema): add filter title

---

docs/site/migration/models/methods.md

Content for `docs/site/migration/models/methods.md`
Explains how to migrate model methods defined by the user.
- Methods related to persistence go to model-specific Repository class
- Remote methods (public API) go to Controller class
connect to: https://github.com/strongloop/loopback-next/issues/3949

docs: migrate custom model methods

---

packages/cli/package-lock.json
packages/http-caching-proxy/package-lock.json
packages/repository-tests/src/crud/transactions.suite.ts
packages/repository/src/transaction.ts

Implements https://github.com/strongloop/loopback-next/issues/3471
Previous PRs see:
https://github.com/strongloop/loopback-connector/pull/164
https://github.com/strongloop/loopback-connector/pull/165

feat: leverage isactive for transaction

---

packages/authorization/src/__tests__/acceptance/authorization.acceptance.ts
packages/authorization/src/authorize-interceptor.ts

Fixes https://github.com/strongloop/loopback-next/issues/4351

fix(authorization): make sure an authorizer is only invoked once per request

---

docs/site/Transactions.md

Implements https://github.com/strongloop/loopback-next/issues/3471
The doc PR.

docs: is active method in transaction

---

docs/site/decorators/Decorators_openapi.md
packages/openapi-v3/src/__tests__/unit/decorators/tags.decorator.unit.ts
packages/openapi-v3/src/controller-spec.ts
packages/openapi-v3/src/decorators/index.ts
packages/openapi-v3/src/decorators/tags.decorator.ts
packages/openapi-v3/src/keys.ts
packages/openapi-v3/src/types.ts

Partially implements: #4300 
See: #4406
This has been split from #4406 as a more manageable, smaller PR.
This PR adds `@oas.tags` to Controller classes and methods, and adds an array of tag strings in accordance with the [OpenAPI Operation Object specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#operation-object).
As the spec defines `tags` as an _optional property_, this feature will only add `tags: string[]` when tags are set, and never an empty array of tags.
Using the `@oas.tags` decorator will set the tags on a path, and will be appended to any `@tags` set on a class.
This decorator is added to the `oas` namespace export in order to prevent naming conflicts with other popular decorators.  The existing decorators in `@loopback/openapi-v3` have …

feat: adds @tags convenience decorator

---

docs/site/HasOne-relation.md
docs/site/Relation-generator.md
docs/site/Relations.md
packages/cli/generators/relation/has-one-relation.generator.js
packages/cli/generators/relation/index.js
packages/cli/generators/relation/templates/controller-relation-template-has-one.ts.ejs
packages/cli/generators/relation/utils.generator.js
packages/cli/snapshots/integration/generators/relation.has-one.integration.snapshots.js
packages/cli/test/fixtures/relation/controllers/address-customer.controller.ts
packages/cli/test/fixtures/relation/index.js
packages/cli/test/fixtures/relation/models/address-class-type.model.ts
packages/cli/test/fixtures/relation/models/address-class.model.ts
packages/cli/test/fixtures/relation/models/address-with-fk.model.ts
packages/cli/test/fixtures/relation/models/address.model.ts
packages/cli/test/fixtures/relation/models/customer6.model.ts
packages/cli/test/fixtures/relation/repositories/address-class-type.repository.ts
packages/cli/test/fixtures/relation/repositories/address-class.repository.ts
packages/cli/test/fixtures/relation/repositories/address.repository.ts
packages/cli/test/integration/generators/relation.has-one.integration.js

feat(cli): add hasOne relation type to `lb4 relation`

---

examples/context/package.json
examples/express-composition/package.json
examples/greeter-extension/package.json
examples/greeting-app/package.json
examples/hello-world/package.json
examples/lb3-application/package.json
examples/log-extension/package.json
examples/metrics-prometheus/package.json
examples/rpc-server/package.json
examples/soap-calculator/package.json
examples/todo-list/package.json
examples/todo/package.json

Fixes https://github.com/strongloop/loopback-next/issues/4545
Please note that `lb4 example` rename `tsconfig.build.json` to
`tsconfig.json`. As a result, the build cache file is `tsconfig.tsbuildinfo`.

fix: update clean script for examples to be compatible with `lb4 example`

---

docs/site/decorators/Decorators_openapi.md
packages/openapi-v3/src/__tests__/unit/decorators/deprecated.decorator.unit.ts
packages/openapi-v3/src/controller-spec.ts
packages/openapi-v3/src/decorators/deprecated.decorator.ts
packages/openapi-v3/src/decorators/index.ts
packages/openapi-v3/src/keys.ts

Partially implements: #4300 
See: #4406
This has been split from #4406 as a more manageable, smaller PR.
This PR adds `@deprecated` to Controller classes and methods, and marks all paths as `deprecated: true` in accordance with the [OpenAPI Operation Object specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#operation-object).
As the spec defines `deprecated` as an _optional property_, this feature will only add `deprecated: true` and never `deprecated: false`.
This PR does _not_ add support for marking parameters as `deprecated`
```ts
@deprecated()
@get('/greet')
public async function greet() {
return 'Hello, World!'
}
@get('/greet-v2')
@deprecated(false)
public async function greetV2() {
return 'Hello, World!'
}
}
class …
```

feat: adds @deprecated convenience decorator

---

packages/context/src/__tests__/unit/context.unit.ts
packages/context/src/context.ts

context.inspect() or other debug statements will have more meaningful
context names to understand if the context is an Application, RestServer,
or RequestContext.
For example, the context name for `TestContext` will be prefixed with `TestContext-`:
`TestContext-f859c8c1-4444-11ea-b8e7-f93bb3eeab9e`

feat(context): improve context name with the subclass name as prefix

---

packages/context/src/__tests__/unit/binding.unit.ts
packages/context/src/__tests__/unit/context.unit.ts
packages/context/src/binding-filter.ts
packages/context/src/binding.ts
packages/context/src/context.ts
packages/context/src/index.ts
packages/context/src/inject.ts
packages/context/src/json-types.ts
packages/context/src/resolution-session.ts
packages/core/src/application.ts

The PR improves context/binding inspection APIs with more options and information:
At binding level, there is one flag:
- includeInjections: control if injections should be inspected
At context level, there are two flags:
- includeInjections: control if binding injections should be inspected
- includeParent: control if parent context should be inspected

feat: improve context/binding inspection

---

package-lock.json
package.json

The npm script `npm run coverage` invokes `open coverage/index.html`, which is invalid on both Linux and Windows.  This pr adds `open-cli` as a dependency, which is a cross-platform `open`, and uses it instead.

fix: replace `open` with `open-cli`

---

docs/site/decorators/Decorators_openapi.md

This PR updates the documentation to reflect that `x-ts-type` can be used under the schema keywords `allOf`, `anyOf`, `oneOf`, and `not` - functionality which landed in #4479

docs: update documentation to reflect any/all/oneOf

---

examples/todo-list/src/__tests__/acceptance/todo-list.acceptance.ts
examples/todo/src/__tests__/acceptance/todo.acceptance.ts
packages/openapi-v3/src/__tests__/unit/decorators/param/param-query.decorator.unit.ts
packages/openapi-v3/src/decorators/parameter.decorator.ts
packages/rest/src/__tests__/unit/coercion/paramObject.unit.ts
packages/rest/src/__tests__/unit/parser.unit.ts
packages/rest/src/coercion/coerce-parameter.ts
packages/rest/src/coercion/validator.ts

issue: https://github.com/strongloop/loopback-next/issues/2208
BREAKING CHANGE
Based on spike https://github.com/strongloop/loopback-next/pull/4141

fix: suport complex objects for query params in api explorer

---

packages/context/src/__tests__/unit/binding-filter.unit.ts
packages/context/src/binding-filter.ts

Fixes https://github.com/strongloop/loopback-next/issues/4570
Please note that `bindingSelector instanceof BindingKey` is not always
reliable as the `@loopback/context` module might be loaded from multiple
locations if `npm install` does not dedupe or there are mixed versions in
the tree.

fix(context): relax checking on instances of BindingKey class

---

docs/site/Loopback-component-authorization.md

Fixes: https://github.com/strongloop/loopback-next/issues/4576
Copy from ^
I verified with an app in PR https://github.com/strongloop/loopback-next/pull/4571
```ts
const auth_options: AuthorizationOptions = {
defaultDecision: AuthorizationDecision.ALLOW,
precedence: AuthorizationDecision.ALLOW,
}
this.configure(AuthorizationBindings.COMPONENT).to(auth_options);
```
works.
The debug log:
```
loopback:authorization:interceptor Authorization options { defaultDecision: 'Allow', precedence: 'Allow' } +272ms
```
And according to the code in
https://github.com/strongloop/loopback-next/blob/6eea5e428b145cafb84a998bd53979da8c8fba07/packages/authorization/src/authorize-interceptor.ts#L38
Your solution is the correct fix. Submitting a PR to update the doc
👉 [Read and sign the CLA (Contributor …

docs: update auth options

---

CODEOWNERS

While looking up owners of CLI, I noticed that the catch-all CLI entry is after more specific entries for individual generators. Because CODEOWNERS algorithm is picking up the last matching pattern, this setup was effectively invalidating generator-specific configuration.
In this commit, I am fixing the issue by moving the catch-all CLI entry to the top.
See also https://github.com/strongloop/loopback-next/pull/4559

chore: fix CLI records in CODEOWNERS

---

docs/site/Discovering-models.md
packages/cli/generators/discover/index.js
packages/cli/snapshots/integration/generators/discover.integration.snapshots.js
packages/cli/test/fixtures/discover/mem.datasource.js.txt
packages/cli/test/integration/generators/discover.integration.js

connects to #3343 
Add 2 prompts:
- asking naming convention for db column names: **UPDATED**
```
? Select a convention to convert db column names(EXAMPLE_COLUMN) to model property names:
❯ Camel case (exampleColumn) (Recommend) 
No conversion (EXAMPLE_COLUMN) 
```
If the user pick `keep the same as db`, prompt:
```
? You might need to specify these customized names in relation 
definition. Would you like to continue?
❯ Yes 
No (back to the previous step) 
```

feat(cli): allow different naming convention for discover

---

MAINTAINERS.md

chore: add frbuceta and agnes to maintainers list

---

packages/rest/src/__tests__/integration/rest.server.integration.ts
packages/rest/src/__tests__/unit/router/controller-route.unit.ts
packages/rest/src/__tests__/unit/router/routing-table.unit.ts
packages/rest/src/rest.server.ts
packages/rest/src/router/controller-route.ts
packages/rest/src/router/routing-table.ts

This PR makes it consistent for all routes to be bound under `routes.*` namespace. Before the change, controller routes are not bound to the context.

feat(rest): bind controller routes to the context

---

docs/site/decorators/Decorators_openapi.md
packages/openapi-v3/package-lock.json
packages/openapi-v3/package.json
packages/openapi-v3/src/__tests__/unit/decorators/response.decorator.unit.ts
packages/openapi-v3/src/build-responses-from-metadata.ts
packages/openapi-v3/src/controller-spec.ts
packages/openapi-v3/src/decorators/index.ts
packages/openapi-v3/src/decorators/response.decorator.ts
packages/openapi-v3/src/keys.ts
packages/openapi-v3/src/types.ts

Partially implements: #4300
See: #4406
This PR adds the `@oas.response(code: number, ...modelOrSpec: ModelOrSpec[])` decorator.  
The decorator only affects the OpenAPI specification object that is created, and anything that uses it to verify and validate responses.  **This decorator has no impact on the actual response code**.  It also doesn't add any typings or lint configuration that could force response compliance at compile/lint time (if that's even possible).
```ts
@model()
class SuccessModel extends Model {
constructor(err: Partial<SuccessModel>) {
super(err);
}
@property({default: 'Hi there!'})
message: string;
}
class FooNotFound extends Model {
@property()
message: string;
}
class BarNotFound extends Model {
@property()
message: string;
}
class BazNotFound extends Model { …
```

feat: adds @oas.response decorator

---

packages/cli/lib/base-generator.js

Before this change, the following command did not work:
$ lb4 --yes --config '{}' < /dev/null
Generation is aborted: SyntaxError: Unexpected end of JSON input
In this change, I am tweaking the condition detecting when we need to read config from stdin to use data from CLI arg `--config` when it's available and don't try to read from stdin.
See also https://github.com/strongloop/loopback-next/issues/4425
- …

fix(cli): ignore stdin when config is provided via CLI args

---

benchmark/package-lock.json
benchmark/package.json
benchmark/src/__tests__/benchmark.integration.ts
benchmark/src/client.ts
packages/cli/package-lock.json
packages/cli/package.json

Replacing `request` with `axios`

chore(benchmark): replace request with axios

---

docs/site/Model.md
docs/site/Parsing-requests.md
packages/rest/package-lock.json
packages/rest/package.json
packages/rest/src/__tests__/acceptance/validation/validation.acceptance.ts
packages/rest/src/__tests__/unit/request-body.validator.test.ts
packages/rest/src/types.ts
packages/rest/src/validation/request-body.validator.ts

feat(rest): add support for ajv-errors

---

packages/rest/src/__tests__/integration/rest.server.integration.ts
packages/rest/src/rest.server.ts

Fixes https://github.com/strongloop/loopback-next/issues/4530

fix(rest): improves error handling for express middleware

---

docs/site/Parsing-requests.md

https://github.com/strongloop/loopback-next/issues/2208
Opened to fix https://github.com/strongloop/loopback-next/pull/4347#issuecomment-581730071

docs: update docs for issue 2208 switching to url-encoded style params

---

docs/site/decorators/Decorators_openapi.md

issue: https://github.com/strongloop/loopback-next/issues/2208

docs: update decorator documentation for url-encoded query params

---

CODEOWNERS

I noticed that after recent changes in our CODEOWNERS file (#4559, #4587), GitHub stopped assigning code owners for pull request reviews. I run few experiments in a dummy repo and found that the trailing slash after the directory name seems to be the cause.
In this pull request, I am removing trailing `/` characters from all CODEOWNERS entries, with the hope to restore the order and allow GitHub to understand our configuration.

chore: fix CODEOWNERS syntax

---

docs/site/tutorials/authentication/Authentication-Tutorial.md
packages/cli/generators/app/templates/src/application.ts.ejs
packages/rest-explorer/README.md
packages/rest-explorer/src/__tests__/acceptance/rest-explorer.express.acceptance.ts
packages/rest-explorer/src/rest-explorer.controller.ts
packages/rest-explorer/src/rest-explorer.keys.ts

chore: use configure/@config for RestExplorer component

---

docs/site/Components.md

Change 'aded' to 'added'
Signed-off-by: Dominique Emond <dremond@ca.ibm.com>

docs: fix typo in Component doc

---

docs/site/tutorials/todo-list/todo-list-tutorial-controller.md

File paths contain the 'models' directory. Replaced by 'controllers'.

docs: correct controller base path

---

.vscode/launch.json
packages/cli/test/integration/generators/model.integration.js
packages/cli/test/snapshot-matcher.js

While investigating failing `npm test` on Windows (see #4425), I have identified few more issues to fix:
- fix VSCode launch task for Mocha to work on Windows 
- increase timeout in a test running longer on Windows (this may fix the timing-related issues described in https://github.com/strongloop/loopback-next/issues/4425#issuecomment-584100049)
- fix source-code check to allow `\r\n` line ending on Windows
- normalize EOL values when comparing snapshots
- Affected example projects in `examples/*` …

Fix Windows-related issues in CLI tests

---

CODEOWNERS

More fixes in the CODEOWNERS file, hopefully the last ones needed to make code owners work again.
This is a follow-up for #4641, #4559 and #4587.

chore: more fixes of CODEOWNERS syntax

---

docs/site/index.md

See #4466
Fix a minor typo that prevents Jekyll from parsing and converting the
link into a navigatable URL.

chore(docs): fix feature parity link

---

packages/cli/test/integration/generators/app.integration.js

Fixes error on windows tests.  Removes instances of sandbox folder
erroniously placed in packages folder.
See #4425

fix(cli): correct root directory in test

---

docs/site/tutorials/todo/todo-tutorial-geocoding-service.md
examples/todo/src/__tests__/acceptance/todo.acceptance.ts
examples/todo/src/controllers/todo.controller.ts

Throw an error if the geocoder service cannot find the address.
Related PR https://github.com/strongloop/loopback-next/pull/3512

fix(example-todo): throw if geocode address is not found

---

CODEOWNERS

While reviewing a recent pull request (#4662), I noticed that it was assigned to all team members because one of the tutorial doc pages was updated as part of the changes. I find that suboptimal because then it's not clear who is primarily responsible for reviewing the changes.
In this pull request, I am adding new CODEOWNERS entries for each sub-directory in `/docs/site/tutorials/`

chore: add codeowners for tutorials

---

packages/cli/test/integration/generators/app.integration.js
packages/http-caching-proxy/src/__tests__/integration/http-caching-proxy.integration.ts
packages/http-server/src/__tests__/integration/http-server.integration.ts

Give windows extra time to complete tests
Fixes #4425
fix: cleanup tilde-path-app post test …
ensure test app is remove afterward
Fixes #4652

fix: extend test timeout for windows

---

packages/repository-tests/src/crud/create-retrieve.suite.ts
packages/repository-tests/src/crud/nested-model-properties.suite.ts
packages/repository-tests/src/crud/relations/acceptance/belongs-to.relation.acceptance.ts
packages/repository-tests/src/crud/relations/acceptance/has-many.relation.acceptance.ts
packages/repository-tests/src/crud/relations/acceptance/multi-relations-inclusion-resolver.relation.acceptance.ts
packages/repository-tests/src/crud/relations/fixtures/models/address.model.ts
packages/repository-tests/src/crud/relations/fixtures/models/customer.model.ts
packages/repository-tests/src/crud/relations/fixtures/models/order.model.ts
packages/repository-tests/src/crud/relations/fixtures/models/shipment.model.ts
packages/repository-tests/src/crud/replace-by-id.suite.ts
packages/repository/src/__tests__/unit/decorator/model-and-relation.decorator.unit.ts
packages/repository/src/model.ts

Preserve custom type of auto-generated id property

---

.vscode/settings.json
packages/cli/generators/project/templates/.vscode/settings.json

useful rule for when Prettier not enabled.
Implements #4584

feat: .vscode add no spaces in braces + single quotes typescript rules

---

packages/http-caching-proxy/README.md
packages/http-caching-proxy/package-lock.json
packages/http-caching-proxy/package.json
packages/http-caching-proxy/src/__tests__/integration/http-caching-proxy.integration.ts
packages/http-caching-proxy/src/http-caching-proxy.ts

This is part 2 to fix https://github.com/strongloop/loopback-next/issues/2672

feat(http-caching-proxy): replace request package with axios

---

docs/site/Calling-other-APIs-and-Web-Services.md
docs/site/tutorials/todo/todo-tutorial-geocoding-service.md

Now that we have the connector reference under /doc/lb4, it's time to update the URL reference in the following 2 pages:
- Calling other APIs and web services
- todo tutorial

fix(docs): update connector reference to lb4 link

---

packages/eslint-config/eslintrc.js

fixes #4675
BREAKING CHANGE: eslint rule `@typescript-eslint/no-non-null-asserted-optional-chain` is set to `error` which may break existing lint tests.

feat(eslint-config): disallow non-null assertions after optional chain

---

packages/boot/package.json
packages/boot/src/__tests__/acceptance/crud-rest.api-builder.acceptance.ts
packages/boot/src/__tests__/fixtures/no-entity.model.ts
packages/boot/src/__tests__/fixtures/product.repository.ts
packages/rest-crud/README.md
packages/rest-crud/package-lock.json
packages/rest-crud/package.json
packages/rest-crud/src/crud-rest.api-builder.ts
packages/rest-crud/src/crud-rest.component.ts
packages/rest-crud/src/index.ts

Closes https://github.com/strongloop/loopback-next/issues/3737
`CrudRestApiBuilder` is a model API builder that builds the default repository and controller class for a given Entity class.

feat(rest-crud): add CrudRestApiBuilder

---

docs/site/Testing-your-application.md
packages/build/README.md

add docs for setting up code coverage using 'lb-nyc'
closes #3227
closes #3301

chore(build): add docs for code coverage

---

packages/testlab/src/skip.ts

The helper `itSkippedOnTravis` is no longer available, please change your tests to use `skipOnTravis` instead.
```diff
- itSkippedOnTravis('supports IPv6', () => {
+ skipOnTravis(it, 'supports IPv6', () => {
```

feat(testlab): remove legacy API `itSkippedOnTravis`

---

packages/repository/src/query.ts
packages/repository/src/relations/has-many/has-many.inclusion-resolver.ts
packages/repository/src/relations/has-one/has-one.inclusion-resolver.ts
packages/repository/src/relations/relation.helpers.ts
packages/repository/src/relations/relation.types.ts
packages/repository/src/repositories/legacy-juggler-bridge.ts

Ideally, `Inclusion` interface should use type information from the source model to restrict the allowed values in the filter for a target model. That is unfortunately rather difficult to achieve,
because an `Entity` does not provide type information about related models. We could use `{ModelName}WithRelations` interface for first-level inclusion, but that won't handle second-level (and deeper) inclusions. To keep things simple, `Inclusion` allows any filters and thus does not require any generic parameter.
The type `Inclusion` is no longer generic. Please update your code and remove any generic arguments provided for the type.
```diff
- Inclusion<MyModel>
+ Inclusion
``` …

feat(repository): remove generic parameters from `Inclusion` type

---

packages/context/src/__tests__/unit/binding-filter.unit.ts
packages/context/src/binding-filter.ts

This allows us to find all bindings that match multiple tag name/value
pairs but we don't care about the value for certain tags. For example,
we can now find controller bindings by name as follows:
```ts
const bindings = ctx.findByTag({
controller: ANY_TAG_VALUE,
name: 'my-name',
});
```

feat(context): allow tags to be matched by a given name with any value

---

tsconfig.json

This speeds up `npm run eslint` from about `4m10s` down to `2m50s`.
More importantly, it enables proper caching behavior, so that subsequent runs of `npm run eslint` are super quick, even after `npm run build` modified `dist` files.
```
$ npm run build
(...)
$ time npm run eslint
> loopback-next@0.1.0 eslint /Users/bajtos/src/loopback/next
> node packages/build/bin/run-eslint --report-unused-disable-directives --cache .
real	0m1.626s
user	0m1.143s
sys	0m0.393s
```
(That's less than 2 seconds for subsequent eslint runs leveraging the cached data!)
See the discussion in https://github.com/strongloop/loopback-next/pull/4382 for more context.
- New tests added or …

Remove dist files from top-level tsconfig to speed up eslint checks 🏎🚀

---

packages/repository-json-schema/src/__tests__/integration/build-schema.integration.ts
packages/repository-json-schema/src/build-schema.ts
packages/repository-json-schema/src/keys.ts

The following constants are no longer available:
- `MODEL_TYPE_KEYS.ModelOnly`
- `MODEL_TYPE_KEYS.ModelWithRelations`
Please use the helper `buildModelCacheKey` to obtain the cache key for a given set of schema options.
```diff
- MODEL_TYPE_KEYS.ModelOnly
+ buildModelCacheKey()
- MODEL_TYPE_KEYS.ModelWithRelations
+ buildModelCacheKey({includeRelations: true})
```

feat(repository-json-schema): remove deprecated `MODEL_TYPE_KEYS`

---

tsconfig.json

https://github.com/strongloop/loopback-next/pull/4707#issuecomment-590255940
See also #4707

chore: update node_modules exclude in root tsconfig

---

packages/cli/generators/project/templates/tsconfig.json.ejs

https://github.com/strongloop/loopback-next/pull/4707#issuecomment-590255940
See also #4707

fix(cli): update tsconfig template excludes

---

packages/repository/src/__tests__/integration/repositories/relation.factory.integration.ts
packages/repository/src/__tests__/unit/errors/invalid-relation-error.test.ts
packages/repository/src/relations/relation.types.ts

Modify `RelationDefinitionBase` to require all relation definitions to provide value of `targetsMany` field.
If you are building a custom relation type with its own definition interface, make sure the interface includes `targetsMany` property. Typically, the type of this property is hard-coded as `true` or `false`, depending on the relation type.
```ts
interface HasManyDefinition extends RelationDefinitionBase {
type: RelationType.hasMany;
targetsMany: true;
// etc.
}
export interface BelongsToDefinition extends RelationDefinitionBase {
type: RelationType.belongsTo;
targetsMany: false;
// etc.
}
```
When creating an instance of a relation definition, make sure to include a value for `targetsMany` property.
```ts
new ModelDefinition('Order')
.addRelation({
name: …
```

feat(repository): make `targetsMany` property required

---

README.md

Now that we're planning to post more development updates to Twitter, I'm thinking that it might be a good idea to add a twitter badge in readme.  The [nodejs.dev repo](https://github.com/nodejs/nodejs.dev#nodejsdev) and other popular repos have it too. 
Here is the preview from VSCode:

chore: add twitter badge to readme

---

packages/authorization/README.md

…ns and put comma
It is a minor fix on documentation.

fix(docs): corrected AuthorizationOptions example line endings

---

docs/site/Importing-LB3-models.md
packages/cli/test/unit/import-lb3-model/migrate-model.test.js

satisfies: https://github.com/strongloop/loopback-next/issues/3810

feat: lb3 migration tests for models customized with db metadata

---

docs/site/Controller-generator.md
docs/site/Sequence.md
docs/site/decorators/Decorators_openapi.md
examples/express-composition/src/controllers/note.controller.ts
examples/todo-list/src/controllers/todo-list-todo.controller.ts
examples/todo-list/src/controllers/todo-list.controller.ts
examples/todo-list/src/controllers/todo.controller.ts
examples/todo/src/controllers/todo.controller.ts
packages/cli/generators/controller/templates/src/controllers/controller-rest-template.ts.ejs
packages/cli/snapshots/integration/generators/controller.integration.snapshots.js
packages/openapi-v3/src/__tests__/unit/decorators/query.decorator.unit.ts
packages/openapi-v3/src/__tests__/unit/filter-schema.unit.ts
packages/openapi-v3/src/decorators/parameter.decorator.ts
packages/openapi-v3/src/filter-schema.ts
packages/repository-json-schema/src/__tests__/unit/filter-json-schema.unit.ts
packages/repository-json-schema/src/filter-json-schema.ts
packages/repository/src/__tests__/unit/model/model.unit.ts
packages/repository/src/__tests__/unit/repositories/legacy-juggler-bridge.unit.ts
packages/repository/src/model.ts
packages/repository/src/query.ts
packages/repository/src/repositories/legacy-juggler-bridge.ts
packages/repository/src/repositories/repository.ts
packages/rest-crud/src/crud-rest.controller.ts

Fixes #1721, #3336, and #1749 
- #1721: add type and schema for filter excluding where for `findById`
- #3336: add a test for findById with `filter.fields`
- #1749: add sugar decorators for `filter` and `where`

feat: simplify filter and where usage for constraint, schema, and OpenAPI mapping

---

packages/rest/src/__tests__/unit/request-body.validator.test.ts
packages/rest/src/parser.ts
packages/rest/src/validation/request-body.validator.ts

Add support for async validations. The need arises from allowing custom formats & keywords for ajv, which can also be async in nature.

add async validation support

---

docs/site/migration/models/operation-hooks.md
packages/repository/src/__tests__/acceptance/operation-hooks.acceptance.ts
packages/repository/src/repositories/legacy-juggler-bridge.ts

Added support for operation hooks. Addresses https://github.com/strongloop/loopback-next/issues/3952.
Signed-off-by: Hage Yaapa <hage.yaapa@in.ibm.com>

feat: support operation hooks

---

examples/lb3-application/src/__tests__/acceptance/lb3app.acceptance.ts
packages/booter-lb3app/src/__tests__/acceptance/booter-lb3app.acceptance.ts
packages/rest-crud/src/__tests__/acceptance/default-model-crud-rest.acceptance.ts
packages/rest/src/__tests__/integration/rest.application.integration.ts
packages/rest/src/__tests__/unit/rest.server/fixtures/info.spec.extension.ts
packages/rest/src/__tests__/unit/rest.server/rest.server.open-api-spec.unit.ts
packages/rest/src/rest.server.ts

Add OpenAPI enhancer service in @loopback/rest
Implements #4365

feat(rest): add OAS Enhancer service

---

packages/cli/package.json

The recently created `intl` folder didn't get copied to the packaged module. Add `intl` to package.json.
I've verified on my laptop that adding the `intl/en/messages.json` will make CLI work again.

fix(cli): include intl in package.json

---

packages/build/README.md
packages/build/src/fail-on-console-logs.js
packages/testlab/README.md

As a follow-up to the conversation we had on Slack, I am proposing to add some documentation for `ATTENTION - INVALID USAGE OF CONSOLE LOGS DETECTED` and make this docs easier to discover by modifying `lb-mocha` to print a URL for that content.
See also https://github.com/strongloop/loopback-next/pull/1058 which introduced log detection to `lb-mocha`.
👉 [Check out how to submit …

Add more details about rejecting console logs in tests 

---

packages/repository-tests/src/crud/relations/acceptance/belongs-to.inclusion-resolver.relation.acceptance.ts
packages/repository/src/relations/belongs-to/belongs-to.inclusion-resolver.ts

fixes https://github.com/strongloop/loopback-next/issues/4372
fix querying related entities with null keys and add tests to repository-test

fix: filter null keys when including belongs-to relations in queries 

---

packages/rest/src/__tests__/unit/ajv.service.unit.ts
packages/rest/src/validation/ajv.service.ts
packages/rest/src/validation/request-body.validator.ts

Inspired by #4801 
- Extract AJV to a separate service provider (use as a factory function for now without DI)
- Allow to ignore `binary` format by default

refactor(rest): extract AJV to a separate service provider

---

.travis.yml

The default npm for node v12.16.1 (npm v6.13.4) fails with `cb() never called`
Upgrading to `npm@6.14.2` fixed `lerna bootstrap`.

chore: fix verify-docs build failure with travis

---

CODEOWNERS

Removing `/packages/booter-rest` since it doesn't exist

fix: remove booter-rest package from CODEOWNERS

---

.vscode/launch.json
bin/mocha-current-file.js

Partially implements: #4300
See: #4406
This has been split from #4406 as a more manageable, smaller PR.
This update adds a developer convenience Launch task to allow debugging a single unit test file in Visual Studio Code.  
- **`bin/mocha-current-file.js`** - this is a utility script that attempts to determine the dist output of the given test file, and passes it off to mocha in-process.
- **VSCode: Debug Current Test File** launch configuration.  This launch configuration allows you to debug the current unit test file currently focused.  It uses the above helper to determine the correct name and path of the compiled JavaScript file to run.
- The launch for "Run Mocha Tests" so that it also runs on Windows.

feat: adds utility launch for debugging a single test file

---

docs/site/Binding.md
docs/site/Extension-point-and-extensions.md
packages/context/src/__tests__/unit/binding-filter.unit.ts
packages/context/src/binding-filter.ts
packages/core/src/__tests__/acceptance/extension-point.acceptance.ts
packages/core/src/extension-point.ts

The PR is to address the need by https://github.com/strongloop/loopback-next/pull/4693#discussion_r389321928.
1. Introduce `TagValueMatcher` function type for more flexible tag value matching used by `filterByTag`
2. Use an array inclusion based TagValueMatcher to discover extensions tagged for multiple extension points.

feat(core): allow an extension to be used by multiple extension points

---

.github/ISSUE_TEMPLATE/Migration_docs.md
docs/site/migration/auth/built-in.md
docs/site/migration/auth/example.md
docs/site/migration/auth/oauth2.md
docs/site/migration/auth/overview.md
docs/site/migration/auth/passport.md
docs/site/migration/boot-scripts.md
docs/site/migration/cli.md
docs/site/migration/clients.md
docs/site/migration/datasources.md
docs/site/migration/express-middleware.md
docs/site/migration/extensions.md
docs/site/migration/models/core.md
docs/site/migration/models/methods.md
docs/site/migration/models/mixins.md
docs/site/migration/models/operation-hooks.md
docs/site/migration/models/overview.md
docs/site/migration/models/relations.md
docs/site/migration/models/remoting-hooks.md
docs/site/migration/mounting-lb3app.md
docs/site/migration/not-planned.md
docs/site/migration/overview.md

1. Add a new issue template for reporting missing documentation related to migration from LoopBack 3 to LoopBack 4.
2. Update all doc pages in our migration guide, add a "tip" alert asking users to open a new issue if they are missing instructions for their particular use case.

chore: add Migration Docs issue template + docs alerts

---

docs/bin/build-preview-site.sh

Rework the script setting up docs preview to create hard-links instead of symbolic links, because Jekyll no longer supports symbolic links pointing outside of the site directory.
The new solution is based on `pax` tool, which is a part of POSIX, included in MacOS but often not included in GNU/Linux distributions by default. Developers working on loopback-next in Linux may need to install the tool via the package manager provided by their distro. Learn more here: https://en.wikipedia.org/wiki/Pax_(Unix)
- Code conforms with the [style …

chore: fix setup of docs preview site

---

packages/authentication/src/services/token.service.ts

When implementing token systems other then `jwt` there is a need to **revoke a token**. I also discovered that there is a need to access the `UserProfile` of the current user to validate tokens in some token systems.
Example usecases:
- `RefreshToken`, e.g https://github.com/strongloop/loopback4-example-shopping/pull/537
- Reimplementing `lb3` `AccessToken` in `lb4`
Related to #4573.
With this PR I'm suggesting to change the `TokenService` interface.
~~This is a BREAKING CHANGE.~~
WDYT?

feat(authentication): extend TokenService for revokeable tokens

---

docs/site/Model.md

clean up old content and make it less relate to lb3
some content are copied from lb3 and rewrite it with lb4-way
closes https://github.com/strongloop/loopback.io/issues/907
While doing ^907, I realized that we link to LB3 docs a lot. Considering there are several differences between them and not all users are familiar with LB3, I think it's time to separate them. ( And ofc it is also annoying to jump back and forth between LB3 and LB4 docs)
So I edited  the `Model Decorator` and `Property Decorator` sections that:
- copy content form LB3 if we linked it to LB3 before.
- Remove the unsupported part and rewrite it with Ts-way to LB4.
- Edit them as a whole to make it more consistent
I tested them briefly before I removing some features/entries. If you happen to know that they are still …

docs: update Models.md

---

packages/authentication/src/__tests__/acceptance/basic-auth-extension.acceptance.ts
packages/authentication/src/__tests__/acceptance/jwt-auth-extension.acceptance.ts
packages/authentication/src/__tests__/fixtures/strategies/basic-strategy.ts
packages/authentication/src/__tests__/fixtures/strategies/jwt-strategy.ts
packages/authentication/src/__tests__/unit/types/register-authentication-strategy.unit.ts
packages/authentication/src/types.ts
packages/openapi-v3/src/__tests__/unit/merge-security-scheme.unit.ts
packages/openapi-v3/src/enhancers/spec-enhancer.service.ts

Extend AuthenticationStrategy to implement OASEnhancer.
Example usage:
App > jwt-strategy.ts:
```ts
// ...
@bind(asAuthStrategy, asSpecEnhancer)
export class JWTAuthenticationStrategy
implements AuthenticationStrategy, OASEnhancer {
// ...
modifySpec(spec: OpenApiSpec): OpenApiSpec {
return mergeSecuritySchemeToSpec(spec, this.name, {
type: 'http',
scheme: 'bearer',
bearerFormat: 'JWT',
});
}
}
```
App > application.ts:
```ts
// ...
// authentication
this.add(createBindingFromClass(JWTAuthenticationStrategy));
```
See also #4554
Impl. #3669

feat(Authentication) enable authentication strategies to contribute OASEnhancer

---

docs/site/migration/auth/example.md
examples/access-control-migration/src/models/project.model.ts
examples/access-control-migration/src/models/team.model.ts
examples/access-control-migration/src/models/user.model.ts
examples/access-control-migration/src/repositories/project.repository.ts
examples/access-control-migration/src/repositories/user.repository.ts

connect to https://github.com/strongloop/loopback-next/issues/4521, prepare for User model migration
address comment https://github.com/strongloop/loopback-next/pull/4706#discussion_r383625928

refactor: migrate models from cli

---

docs/site/Extending-OpenAPI-specification.md
packages/authentication/src/__tests__/unit/types/register-authentication-strategy.unit.ts
packages/openapi-v3/src/__tests__/unit/enhancers/fixtures/application.ts
packages/openapi-v3/src/enhancers/keys.ts
packages/openapi-v3/src/enhancers/spec-enhancer.service.ts
packages/openapi-v3/src/enhancers/types.ts
packages/rest/src/rest.server.ts

Refactor const into bindings 
will wait for https://github.com/strongloop/loopback-next/pull/4693 and rebase
Export `OAS_ENHANCER_SERVICE` and  `OAS_ENHANCER_EXTENSION_POINT_NAME` from namespace `OASEnhancerBindings`

refactor: move const into bindings

---

.gitignore
docs/bin/build-preview-site.sh
docs/bin/copy-changelogs.js
docs/package.json
docs/site/sidebars/lb4_sidebar.yml

This PR adds an internal script to generate Jekyll friendly pages for CHANGELOG files. The sidebar has a new section `CHANGELOG` as the index page for all changelogs.
The script is run at `prepack` phase. It adds:
- docs/site/CHANGELOG.md (as index page with links to all modules)
- docs/site/changelogs/*

feat(docs): generate Jekyll friendly pages for CHANGELOG files

---

acceptance/extension-logging-fluentd/package-lock.json
acceptance/repository-cloudant/package-lock.json
acceptance/repository-mongodb/package-lock.json
benchmark/package-lock.json
examples/access-control-migration/package-lock.json
examples/context/package-lock.json
examples/express-composition/package-lock.json
examples/file-upload-download/package-lock.json
examples/greeter-extension/package-lock.json
examples/greeting-app/package-lock.json
examples/hello-world/package-lock.json
examples/lb3-application/package-lock.json
examples/log-extension/package-lock.json
examples/metrics-prometheus/package-lock.json
examples/rest-crud/package-lock.json
examples/rpc-server/package-lock.json
examples/soap-calculator/package-lock.json
examples/todo-list/package-lock.json
examples/todo/package-lock.json
package-lock.json
packages/authentication/package-lock.json
packages/boot/package-lock.json
packages/booter-lb3app/package-lock.json
packages/build/package-lock.json
packages/cli/package-lock.json
packages/cli/package.json
packages/rest/package-lock.json
packages/testlab/package-lock.json

- Fixes https://github.com/strongloop/loopback-next/network/alert/package-lock.json/minimist/open
- Pin yeoman-test at ~2.2.0 to avoid windows hang with inquirer 7.1.x
See more information at:
- #4871
- SBoudrias/Inquirer.js#904

chore: update package-lock.json

---

docs/site/File-upload-download.md
docs/site/Usage-scenarios.md
docs/site/decorators/Decorators_openapi.md
docs/site/sidebars/lb4_sidebar.yml
examples/file-upload-download/src/controllers/file-download.controller.ts
examples/file-upload-download/src/controllers/file-upload.controller.ts
packages/openapi-v3/src/__tests__/unit/decorators/request-body/request-body-shortcut.decorator.unit.ts
packages/openapi-v3/src/__tests__/unit/decorators/response.decorator.unit.ts
packages/openapi-v3/src/decorators/request-body.decorator.ts
packages/openapi-v3/src/decorators/response.decorator.ts

This PR introduces two sugar openapi decorators to further simplify configuration of file upload/download.
- `@requestBody.file` - configure the request body for file upload
- `@oas.response.file` - configure the response for file download
The file upload/download example is now simplified with these decorators.
A new page is added under `Usage Scenarios` to cover file upload/download.
Fixes https://github.com/strongloop/loopback-next/issues/1873

feat: Introduce @requestBody.file and @oas.response.file decorators

---

docs/site/Database-migrations.md
docs/site/Discovering-models.md

connects to https://github.com/strongloop/loopback-next/issues/4744
Add content to Migration and Discover pages to indicates that it is possible to map column names and property names and how to do it.

docs: enhance property and column names mapping for connectors

---

docs/site/migration/not-planned.md

feat(docs): describe LB3 features not planned in LB4

---

docs/site/Context.md
packages/context/src/__tests__/unit/context-view.unit.ts
packages/context/src/context-view.ts

This allows applications to listen on an injected context view to react
on bind/unbind events in addition to refresh for more fine-grained update.

feat(context): emit bind/unbind events on ContextView

---

docs/site/Rest-Crud-generator.md
docs/site/sidebars/lb4_sidebar.yml
docs/site/tables/lb4-artifact-commands.html
packages/cli/generators/rest-crud/crud-rest-component.js
packages/cli/generators/rest-crud/index.js
packages/cli/generators/rest-crud/templates/src/model-endpoints/model.rest-config-template.ts.ejs
packages/cli/lib/cli.js
packages/cli/lib/utils.js
packages/cli/snapshots/integration/cli/cli.integration.snapshots.js
packages/cli/test/fixtures/rest-crud/application.ts
packages/cli/test/fixtures/rest-crud/index.js
packages/cli/test/fixtures/rest-crud/models/decorator-defined.model.txt
packages/cli/test/fixtures/rest-crud/models/default-model.model.txt
packages/cli/test/fixtures/rest-crud/models/multi-word.model.txt
packages/cli/test/integration/generators/rest-crud.integration.js

The PR adds `lb4 rest-crud` command to generate `src/model-endpoints/<model>.rest-config.ts`.
It prompts for selection of a datasource and one or more models, similar as `lb4 repository`.
TODO: 
- ~add tests~ (done)
- ~add docs~ (done)
- ~implement the logic to update `application.ts` to register `CrudRestComponent`.~ (done)
Implements https://github.com/strongloop/loopback-next/issues/2739

feat(cli): add `lb4 rest-crud` command to generate model endpoints from model/datasource

---

packages/boot/src/__tests__/acceptance/application-metadata.booter.acceptance.ts
packages/boot/src/booters/application-metadata.booter.ts

projectRoot is set to `dirname` of `application.js` (dist). We need to
resolve `package.json` in its parent folder.

fix(boot): fix resolution of package.json for application metadata

---

packages/rest/src/__tests__/acceptance/validation/validation.acceptance.ts
packages/rest/src/validation/request-body.validator.ts

The `$async: true` is not set on `components/schemas/<schema-name>/{}`.
Fixes https://github.com/strongloop/loopback-next/issues/4939

fix(rest): allow async custom keyword by setting {$async: true} to referenced schemas

---

docs/site/Extension-point-and-extensions.md
packages/core/src/__tests__/acceptance/extension-point.acceptance.ts
packages/core/src/extension-point.ts

This allows a getter, a view, or a list of extensions to be injected.

feat(core): add more flavors of @extensions decorator

---

packages/rest/src/__tests__/unit/rest.server/fixtures/info.spec.extension.ts
packages/rest/src/__tests__/unit/rest.server/rest.server.open-api-spec.unit.ts
packages/rest/src/index.ts
packages/rest/src/rest.component.ts
packages/rest/src/spec-enhancers/info.spec-enhancer.ts

See https://github.com/strongloop/loopback4-example-shopping/pull/611

feat(rest): add info spec enhancer to build `info` for OpenAPI spec from application metadata

---

docs/site/Validation-ORM-layer.md
docs/site/Validation-REST-layer.md
docs/site/Validation-controller-layer.md
docs/site/Validation.md
docs/site/sidebars/lb4_sidebar.yml

Add more documentation on how to add validation to a LoopBack application. 
Propose to add the validation docs under "Usage scenarios"

feat(docs): add validation docs

---

docs/site/Creating-CRUD-REST-apis.md
docs/site/Extending-Model-API-builder.md
docs/site/Using-components.md
docs/site/sidebars/lb4_sidebar.yml

Closes https://github.com/strongloop/loopback-next/issues/2740.
Documentation for application developers to use `@loopback/rest-crud` and extension developers to use `@loopback/model-api-builder`.

docs: add model to rest api docs

---

extensions/authentication-passport/package-lock.json
extensions/authentication-passport/package.json
extensions/authentication-passport/src/__tests__/acceptance/authentication-with-passport-strategy-oauth2-adapter.acceptance.ts
extensions/authentication-passport/src/__tests__/acceptance/fixtures/mock-oauth2-social-app.ts
extensions/authentication-passport/src/__tests__/acceptance/fixtures/simple-rest-app.ts
extensions/authentication-passport/src/__tests__/acceptance/fixtures/user-repository.ts
extensions/authentication-passport/src/strategy-adapter.ts
packages/authentication/src/__tests__/unit/fixtures/mock-strategy.ts
packages/authentication/src/__tests__/unit/providers/authentication.provider.unit.ts
packages/authentication/src/keys.ts
packages/authentication/src/providers/auth-action.provider.ts
packages/authentication/src/types.ts
packages/rest/src/router/redirect-route.ts

fixes: https://github.com/strongloop/loopback-next/issues/4902
**highlights of changes** :
* `packages/rest/src/writer.ts` - modified to handle redirections, controller can choose to redirect an api call
* `extensions/authentication-passport/src/strategy-adapter.ts ` - adapter is modified to handle redirection calls in passport strategy
* `extensions/authentication-passport/src/__tests__/acceptance/fixtures/oauth2-provider.ts`
- Mock oauth2 provider to mock the whole authorization flow
* `extensions/authentication-passport/src/_tests__/acceptance/authentication-with-passport-strategy-oauth2-adapter.acceptance.ts`
- test cases for the whole  authorization flow
👉 …

fix: passport strategy adapter must support oauth2 flows

---

examples/todo/src/__tests__/acceptance/todo.acceptance.ts
examples/todo/src/models/todo.model.ts
packages/repository-json-schema/src/__tests__/integration/build-schema.integration.ts
packages/repository-json-schema/src/__tests__/unit/build-schema.unit.ts
packages/repository-json-schema/src/build-schema.ts
packages/rest/src/__tests__/unit/ajv.service.unit.ts

Implements https://github.com/strongloop/loopback-next/issues/4255, which supports the `any` as the type for arbitrary model property.
*This is the first PR created to support `any` type. We need another PR to append the `any` type's openapi schema in `components.schemas`*
Define the property in model as:
```ts
import {AnyType} from '@loopback/repository';
@property({
// `@loopback/repository-json-schema` recognizes it
type: 'any'
})
// specify `AnyType` for it
arbitraryProp: AnyType
```
Generated json schema would be
```ts
arbitraryProp: {
$ref: '#/definitions/AnyType'
}
```
Generated openapi spec would be
```ts
"components": {
"schemas": {
"Todo": {
"title": "Todo",
"properties": {
"id": {
"type": "number"
},
// ...other properties
// The schema will be generated as a reference
// TODO: …
```

feat: support any type

---

packages/repository/src/repositories/kv.repository.bridge.ts

KeyValue repository does not require Entities, it can be used with any model. This was an intentional decision when implementing LB3 key-value APIs, to allow the key value to be provided outside of the data stored, thus enabling use cases like storing arbitrary data (including binary blobs) via the key-value API.
I have extracted this pull request from https://github.com/strongloop/loopback-next/pull/4949 to get it landed faster.
- …

fix: remove restriction to Entities from DefaultKeyValueRepository

---

packages/context/src/context-subscription.ts
packages/repository/src/repositories/kv.repository.bridge.ts

Async iterators are a first-class feature in Node.js 10.x and newer, the polyfill is no longer needed.

feat: remove Node.js 8.x polyfill for Symbol.asyncIterator

---

docs/site/express-with-lb4-rest-tutorial.md
examples/express-composition/.eslintrc.js
examples/express-composition/src/__tests__/acceptance/test-helper.ts
examples/express-composition/src/server.ts

Avoid hard-coded port 3000 for testing.

fix(example-express-composition): use an assinged port number for testing

---

docs/site/Validation-REST-layer.md
examples/validation-app/package-lock.json
examples/validation-app/package.json
examples/validation-app/src/__tests__/acceptance/validate.acceptance.ts
examples/validation-app/src/application.ts
examples/validation-app/src/interceptors/validate-phone-num.interceptor.ts
examples/validation-app/src/sequence.ts

Add code for customizing error to `validation-app` example.
Will add docs after https://github.com/strongloop/loopback-next/pull/4874 lands.

feat(example-validation-app): customize error

---

packages/http-server/src/__tests__/integration/http-server.integration.ts

fix(http-server): ensure rejection handler is registered before the error event is emitted

---

packages/context/src/__tests__/unit/context-observer.unit.ts
packages/context/src/context-subscription.ts

The unhandled error is reported when context-observer.unit.ts is run by itself. The root cause is that ContextSubscriptionManager always emits errors to the context chain without checking if there is an error listener on itself.

fix(context): fix context subscription manager to not emit errors to its context if there is an error listener is in place

---

examples/file-transfer/src/__tests__/acceptance/file-download.acceptance.ts
examples/file-transfer/src/__tests__/acceptance/test-helper.ts
examples/file-transfer/src/application.ts
examples/file-transfer/src/controllers/file-download.controller.ts
examples/file-transfer/src/keys.ts
packages/boot/src/__tests__/acceptance/application-metadata.booter.acceptance.ts
packages/testlab/README.md
packages/testlab/src/__tests__/integration/test-sandbox.integration.ts
packages/testlab/src/__tests__/unit/test-sandbox.unit.ts
packages/testlab/src/test-sandbox.ts

Step 3 of #5011 
Depends on #5014 (included here as the 1st commit so that CI can pass).

feat: improve test sandbox

---

package.json

Use `--check` instead of `--list` when linting source code formatting.
The option `--list` produces very terse output which makes it difficult
to understand what's the problem and how to fix it:
```
> loopback-next@0.1.0 prettier:cli /Users/bajtos/src/loopback/next
> node packages/build/bin/run-prettier "**/*.ts" "**/*.js" "**/*.md" "-l"
packages/core/src/application.ts
```
The option `--check` is more verbose:
```
> loopback-next@0.1.0 prettier:cli /Users/bajtos/src/loopback/next
> node packages/build/bin/run-prettier "**/*.ts" "**/*.js" "**/*.md" "--check"
Checking formatting...
packages/core/src/application.ts
Code style issues found in the above file(s). Forgot to run Prettier?
``` …

build: improve errors printed by Prettier

---

packages/rest/src/__tests__/unit/rest.server/rest.server.open-api-spec.unit.ts
packages/rest/src/spec-enhancers/info.spec-enhancer.ts

I wanted to include a config field in the package.json file. Something like:
```
"config": {
"loopback": {
"name": "LoopBack API",
"contact": {
"name": "Support",
"email": "support@localhost"
}
},
"commitizen": {
"path": "./node_modules/cz-conventional-changelog"
}
}
```
OR
```
"config": {
"loopback": "./loopbackrc", (IN JSON FORMAT)
"commitizen": {
"path": "./node_modules/cz-conventional-changelog"
}
}
```
The example:
```
info: {
title: this.pkg.config.loopback.name || this.pkg.name,
description: this.pkg.description,
version: this.pkg.version,
contact: this.pkg.config.loopback.contact || contact,
}
```
- Documentation in …

[REST] Use the description field in Openapi

---

extensions/authentication-passport/src/index.ts
extensions/health/src/index.ts
extensions/logging/src/decorators/index.ts
extensions/logging/src/index.ts
extensions/metrics/src/index.ts
packages/authentication/src/index.ts
packages/authorization/src/index.ts
packages/boot/src/index.ts
packages/booter-lb3app/src/index.ts
packages/context/src/index.ts
packages/core/src/index.ts
packages/http-caching-proxy/src/index.ts
packages/http-server/src/index.ts
packages/metadata/src/index.ts
packages/model-api-builder/src/index.ts
packages/openapi-spec-builder/src/index.ts
packages/openapi-v3/src/index.ts
packages/repository-json-schema/src/index.ts
packages/repository-tests/src/index.ts
packages/repository/src/index.ts
packages/rest-crud/src/index.ts
packages/rest-explorer/src/index.ts
packages/rest/src/index.ts
packages/security/src/index.ts
packages/service-proxy/src/index.ts
packages/testlab/src/index.ts
packages/tsdocs/src/helper.ts
packages/tsdocs/src/index.ts

Loosely related: #4697
This PR is part of a bigger incremental doc improvement.
As a starting point, the package documentation were, for the most part, copy-&-pasted from the respective `README` files.
**Why this (and future tsdoc) PRs?**
1. Improve documentation
* Improving the tsdocs would free up the main docs from having to state the fundamental purposes of each components.
*  The main docs can be updated to be more "guided" for new lb4 users.
* The main docs can instead point readers to the tsdocs as reference.
2. Improve reference docs
* For those who need a quick reference point, the tsdocs can be useful.
**Why this PR?**
This PR fixes the emptiness this page:
* ^ This page is usually the first page seen by users looking for a reference doc
* Through this PR, the users will have a …

Add tsdoc package documentation

---

packages/cli/generators/app/templates/public/index.html.ejs

Just add a little CSS to adapt the main page to the dark mode of the operating systems
[Standard USAGE](https://caniuse.com/#feat=mdn-css_at-rules_media_prefers-color-scheme)
https://drive.google.com/file/d/1ZqnQ90HevZOHPG_8Qa7Y0b3_NltPbLPu/view?usp=sharing

[CLI] implement dark mode in the app template

---

packages/context/package.json
packages/context/src/__tests__/unit/context.unit.ts
packages/context/src/context.ts
packages/core/src/__tests__/unit/application.unit.ts
packages/core/src/application.ts

Key changes:
- only register shutdown listeners when the app starts
- it does not make sense to register shutdown listener before the app starts
- starts to use system resources in the constructor is not a good idea
- unregister process listeners upon explicit stop
- fix the test case to clean up process listeners
- improve debugging with context name prefix
Replace #5015 

feat(core): improve application signal handler registration

---

packages/repository-json-schema/src/__tests__/unit/build-schema.unit.ts
packages/repository-json-schema/src/build-schema.ts

Fix https://github.com/strongloop/loopback-next/issues/5088
When building the relation schema, the `title` field should be omitted.
See details in comment https://github.com/strongloop/loopback-next/issues/5088#issuecomment-613069334

fix: relation schemas should not inherit `title` from the source model's schema

---

docs/site/Fields-filter.md
docs/site/Include-filter.md
docs/site/Limit-filter.md
docs/site/Order-filter.md
docs/site/Querying-data.md
docs/site/Skip-filter.md
docs/site/Where-filter.md
docs/site/Working-with-data.md
docs/site/sidebars/lb4_sidebar.yml

Closes https://github.com/strongloop/loopback-next/issues/2527

docs: adding working with data pages

---

packages/cli/generators/copyright/index.js
packages/cli/test/fixtures/copyright/single-package/index.js
packages/cli/test/integration/generators/copyright.integration.js

fix(cli): exclude `**/node_modules/**/*` from copyright header searching

---

docs/site/OpenAPI-generator.md
packages/cli/generators/copyright/license.js
packages/cli/generators/openapi/index.js
packages/cli/generators/openapi/spec-helper.js
packages/cli/generators/openapi/templates/src/controllers/controller-template.ts.ejs
packages/cli/generators/openapi/templates/src/datasources/datasource.config.json.ejs
packages/cli/generators/openapi/templates/src/datasources/datasource.ts.ejs
packages/cli/generators/openapi/templates/src/models/model-template.ts.ejs
packages/cli/generators/openapi/templates/src/services/service-proxy-template.ts.ejs
packages/cli/generators/openapi/utils.js
packages/cli/lib/base-generator.js
packages/cli/lib/update-index.js
packages/cli/lib/utils.js
packages/cli/snapshots/integration/generators/openapi-client.integration.snapshots.js
packages/cli/snapshots/integration/generators/openapi-petstore.integration.snapshots.js
packages/cli/snapshots/integration/generators/openapi-uspto-with-anonymous.integration.snapshots.js
packages/cli/snapshots/integration/generators/openapi-uspto.integration.snapshots.js
packages/cli/test/fixtures/openapi/3.0/customer.yaml
packages/cli/test/fixtures/openapi/3.0/index.js
packages/cli/test/fixtures/openapi/3.0/petstore-expanded.yaml
packages/cli/test/fixtures/openapi/3.0/src/datasources/index.ts
packages/cli/test/fixtures/openapi/3.0/src/datasources/pet-store.datasource.config.json
packages/cli/test/fixtures/openapi/3.0/src/datasources/pet-store.datasource.ts
packages/cli/test/integration/generators/openapi-client.integration.js
packages/cli/test/integration/generators/openapi-petstore.integration.js
packages/cli/test/integration/generators/openapi-uspto-with-anonymous.integration.js
packages/cli/test/integration/generators/openapi-uspto.integration.js
packages/cli/test/snapshots.js
packages/cli/test/unit/openapi/controller-spec.unit.js

This PR extends `lb4 openapi` with client-side service proxy code generation. The primary use case is to generate strongly-typed service proxies for REST apis that have Swagger 2.0 or OpenAPI 3.0 spec.
Usage:
`lb4 openapi --client`
It will prompt the user to give a datasource name and generate:
- models (models and types)
- services (for strongly-typed service providers per each tag)
- datasources (for openapi connector, can be supplied by `--datasource`)
The `--client` can be used with `--server`. By default, `client` is `false` and `server` is true. 
See docs at https://github.com/strongloop/loopback-next/blob/cli-openapi-client/docs/site/OpenAPI-generator.md
Depends on https://github.com/strongloop/loopback-connector-openapi/pull/10 …

feat(cli): add client side service proxy generation for `lb4 openapi` command

---

extensions/apiconnect/src/__tests__/acceptance/apiconnect.acceptance.ts
packages/cli/generators/app/index.js
packages/cli/generators/app/templates/src/application.ts.ejs
packages/cli/generators/project/templates/package.json.ejs
packages/cli/generators/project/templates/package.plain.json.ejs
packages/cli/lib/project-generator.js
packages/cli/test/integration/generators/app.integration.js

Add `--apiconnect` option to generate a project that enables `ApiConnect` component.

feat(cli): add `--apiconnect` option to enable ApiConnectComponent

---

bin/create-package.js
docs/site/DEVELOPING.md

We often need to add new packages to `loopback-next`. Copy/paste is error prone. This script scaffolds a new project under `packages` or `extensions` depending on the current directory. Then it uses `lerna bootstrap` to set up dependencies.
Depends on https://github.com/strongloop/loopback-next/pull/4994

feat: add a script to scaffold and bootstrap a new package

---

packages/cli/intl/en/messages.json
packages/cli/lib/project-generator.js

Fixes https://github.com/strongloop/loopback-next/issues/5121
After adding the translation as a test, it shows:

fix: globalize app generator strings

---

docs/site/Model.md
packages/repository-json-schema/src/__tests__/unit/build-schema.unit.ts
packages/repository-json-schema/src/build-schema.ts
packages/repository-json-schema/src/filter-json-schema.ts
packages/repository-json-schema/src/index.ts
packages/repository-json-schema/src/keys.ts
packages/repository/package-lock.json
packages/repository/package.json
packages/repository/src/index.ts
packages/repository/src/model.ts

With `lb4 openapi` command, I would like to populate `jsonSchema` for models/properties so that generated controllers/models will have schemas from the spec.

feat: allow `jsonSchema` for model definitions

---

packages/build/config/tsconfig.common.json

A small improvement. I am not sure if this is strictly required, considering that we are already using some of the ES2020 features (e.g. `??` and `?.`), but I think it won't hurt.
Please note this is changing what language features TypeScript accepts in our `.ts` files, it does not change what code is produced by the compiler - see #5205 for changing that aspect.
- Affected artifact templates in …

feat(build): enable all ES2020 features in TypeScript `lib` config

---

packages/build/config/tsconfig.common.json

Now that we no longer support Node.js 8.x (see #4619), we can configure TypeScript compiler to emit code leveraging newer language constructs available in Node.js 10.x.
See also 9424b40 which added support for ES2018/Node.js 10.x target back in the days where we were producing custom `dist` versions for each target Node.js version supported.
- …

feat(build): change the default compilation target to ES2018 (Node.js 10.x)

---

packages/cli/generators/example/index.js
packages/cli/test/integration/generators/example.integration.js

In strongloop/loopback-next#5155, we reworked our typescript setup to leverage composite mode and project references. This breaks our example applications when they are checked out standalone, typically via `lb4 example`.
```sh
$ lb4 example todo
(...)
$ cd loopback4-example-todo
$ npm t
(...)
> lb-tsc
error TS6053: File '/private/packages/http-caching-proxy/tsconfig.json' not found.
error TS6053: File '/private/packages/testlab/tsconfig.json' not found.
(...)
Found 10 errors.
```
This patch fixes the problem by introducing a new step to `lb4 example` command where we remove `references` and `compilerOptions.composite` field from `tsconfig.json` file.
Implements https://github.com/strongloop/loopback-next/issues/2609. …

fix(cli): remove project references from examples

---

docs/site/sidebars/lb4_sidebar.yml

From Slack conversation, @bajtos pointed out that the remote connector is not supported in LB4. 
The other part of the change is in PR https://github.com/strongloop/loopback.io/pull/971. 

fix(docs): remove remote connector

---

bin/create-package.js
bin/update-ts-project-refs.js
docs/site/DEVELOPING.md

See https://github.com/strongloop/loopback-next/pull/4984#pullrequestreview-399140529

feat: update bin/create-package.js to be compatible with TypeScript project references

---

packages/cli/generators/app/templates/src/application.ts.ejs
packages/cli/snapshots/integration/generators/app.integration.snapshots.js
packages/cli/test/integration/generators/app.integration.js

`lb4 app --apiconnect` is broken as the generated `src/application.ts` is missing `);`.

fix(cli) fix `lb4 app --apiconnect` to generate the correct code 

---

packages/cli/generators/openapi/templates/src/services/service-proxy-template.ts.ejs
packages/cli/snapshots/integration/generators/openapi-client.integration.snapshots.js

feat(cli): uses `HttpErrors` for openapi service proxies

---

packages/cli/package.json

Test if inquirer@7.1.x works with windows.

chore(cli): remove inquirer@7.0.x

---

docs/spikes/2020-04-how-to-migrate-lb3-components.md
docs/spikes/README.md

This is the first part of documentation for the spike #4099 How to migrate LB3 components.
I reviewed our official components and (most popular) community extensions, and compiled a list of techniques they use. The idea is to use this list of techniques to identify what content we need to write for LB3 extension maintainers to enable them to upgrade to LB4.
My intention is to commit this document so that it can serve as a kind of a [Lightweight Architecture Decision Record](https://www.thoughtworks.com/radar/techniques/lightweight-architecture-decision-records). I created a new directory `docs/spikes` to hold spike-related docs.
@raymondfeng @jannyHou @emonddr (FA owners of Infrastructure for extensions): Please review the document. I am specifically looking for feedback on the list of …

docs: overview of LB3 components and techniques they use

---

packages/context/src/__tests__/unit/binding-key.unit.ts
packages/context/src/binding-key.ts

Some bindings are created as extensions to a given extension point. These
bindings use tags and their keys do not matter for discovery.

feat(context): add `BindingKey.generate()` to generate unique binding keys

---

docs/site/migration/LB3-vs-LB4-booting.md
docs/site/sidebars/lb4_sidebar.yml

Differences in LB3 and LB4 booting. Addresses https://github.com/strongloop/loopback-next/issues/4838.

docs: booting in LB3 vs LB4

---

extensions/cron/package-lock.json
extensions/cron/package.json
extensions/cron/src/__tests__/acceptance/cron.acceptance.ts

Timeout-based tests are not reliable. Switch to explicit events for coordination. 

test(cron): use events to synchronize timing for assertions

---

bin/build-docs-site.sh
bin/check-package-locks.js
bin/config-lerna-scopes.js
bin/create-package.js
bin/rebuild-package-locks.js
docs/site/DEVELOPING.md

Tidy up internal build scripts:
1. Use `--include-dependencies` for `lerna bootstrap --scope <scope> --include-dependencies` as `--include-filtered-dependencies` is deprecated.
2. Check local packages instead of hard-coded `@loopback/*` to make sure `package-lock.json` does not have entries for local packages.
3. Report errors if provided scopes does not match any packages for `rebuild-package-locks.js`
4. Allow printing out of valid commit scopes 

feat: improve internal build scripts

---

packages/openapi-v3/src/__tests__/unit/decorators/query.decorator.unit.ts
packages/openapi-v3/src/__tests__/unit/filter-schema.unit.ts
packages/openapi-v3/src/filter-schema.ts
packages/openapi-v3/src/json-to-schema.ts
packages/repository-json-schema/src/__tests__/integration/build-schema.integration.ts
packages/repository-json-schema/src/__tests__/unit/build-schema.unit.ts
packages/repository-json-schema/src/build-schema.ts
packages/repository-json-schema/src/index.ts
packages/repository/src/common-types.ts

The `x-typescript-type` can help client code generation tool such as `lb4 openapi --client` to use the built-in TypeScript types.

feat: populate x-typescript-type for openapi schema

---

packages/repository-json-schema/src/__tests__/unit/build-schema.unit.ts
packages/repository-json-schema/src/build-schema.ts

link to https://github.com/strongloop/loopback-next/issues/5088#issuecomment-617696920
https://github.com/strongloop/loopback-next/pull/5108 fixed the relation property's schema title, this PR also fixes it for the regular property.
Relation property:
```ts
@hasMany(() => Child)
children: Child[];
```
Regular property:
```ts
@property.array(Child)
children: Child[];
```

fix(repository-json-schema): avoid title inheritance

---

packages/build/src/fail-on-console-logs.js

Improve `lb-mocha` to complain about invalid usage of console logs when some of the tests failed. It's a common practice to add temporary console logs while troubleshooting.

feat(build): don't reject console logs when tests failed

---

docs/site/OpenAPI-generator.md
examples/multi-tenancy/src/datasources/db.datasource.ts
examples/multi-tenancy/src/datasources/db1.datasource.ts
examples/multi-tenancy/src/datasources/db2.datasource.ts
examples/validation-app/src/datasources/ds.datasource.ts
packages/cli/generators/datasource/templates/datasource.ts.ejs
packages/cli/snapshots/integration/generators/datasource.integration.snapshots.js
packages/cli/snapshots/integration/generators/openapi-client.integration.snapshots.js
packages/cli/test/fixtures/openapi/3.0/src/datasources/pet-store.datasource.ts

Use the `stop()` method provided by `juggler.DataSource` instead.
See also #5220
~~CI builds are failing now and that's expected, because this PR requires a newer version of juggler, I'll rebase it on top of a newer master once the relevant RenovateBot's pull request is landed.~~
@raymondfeng @agnes512 let's continue our discussion from https://github.com/strongloop/loopback-next/pull/5261 in this pull request please. …

feat: remove hand-written datasource `stop()` method

---

docs/site/migration/auth/oauth2.md

After discussing with @raymondfeng and @deepakrkris we decided to update the documentations as this stage and postpone the migration guide. Thanks for the thoughtful suggestions!
Will close https://github.com/strongloop/loopback-next/issues/5184 after landing.

docs: oauth2 provider migration

---

packages/rest-explorer/README.md
packages/rest-explorer/src/__tests__/acceptance/rest-explorer.acceptance.ts
packages/rest-explorer/src/__tests__/fixtures/theme-newspaper.css
packages/rest-explorer/src/rest-explorer.controller.ts
packages/rest-explorer/src/rest-explorer.types.ts
packages/rest-explorer/templates/index.html.ejs

This is a demo PR for https://github.com/strongloop/loopback-next/issues/2023 - customizing visual style of REST API Explorer
It introduces a config property in `@loopback/rest-explorer`:
- swaggerThemeFile: provide the custom path of swagger ui theme file to override the default one
The themes fixtures are added for demo purpose:
- `todoApp/src/public/theme-newspaper.css`
- `todoApp/src/application.ts`
- ~`rest-explorer/src/css`: for demo purpose, and also in case we want to include them as popular theme options, suggested in https://github.com/strongloop/loopback-next/issues/2023#issuecomment-601090982.~
The swagger ui assets are kept inside module `node_modules/swagger-ui-dist`, and mounted to endpoint `/explorer` by
https://github.com/strongloop/loopback-next/blob/3674a99396cf80a64c295 …

customize theme

---

packages/booter-lb3app/src/__tests__/acceptance/booter-lb3app.acceptance.ts
packages/booter-lb3app/src/lb3app.booter.ts

Rename the key from `datasources.lb3-{ds}` to `lb3-datasources.{ds}`
See https://github.com/strongloop/loopback-next/pull/3779#discussion_r327659012 for previous discussion.
Proposal to rename the binding key for datasources in order to match the proposed naming for lb3 models (see https://github.com/strongloop/loopback-next/pull/5251#discussion_r416616108).

fix(booter-lb3app): rename ds binding key

---

docs/site/Booting-an-Application.md
packages/boot/src/__tests__/acceptance/component-application.booter.acceptance.ts
packages/boot/src/booters/component-application.booter.ts
packages/boot/src/booters/index.ts

Use case:
- Create a LoopBack application
- Add controllers, services, datasources
- Now use this application as a component with the main applicaiton
- The main application needs to have artifacts from the component application

feat(boot): add helpers to create a booter for component applications

---

packages/core/src/__tests__/unit/application-lifecycle.unit.ts
packages/core/src/__tests__/unit/application.unit.ts
packages/core/src/application.ts
packages/core/src/service.ts
packages/repository/src/__tests__/unit/mixins/repository.mixin.unit.ts
packages/repository/src/mixins/repository.mixin.ts
packages/service-proxy/src/__tests__/unit/mixin/service.mixin.unit.ts
packages/service-proxy/src/mixins/service.mixin.ts

The new style allows extra options such as `namespace` to be customized.
One use case is that a sub application might boot artifacts into its own
namespace.

feat(core): allow options for artifact registration on an application

---

.travis.yml
appveyor.yml
packages/cli/generators/app/index.js
packages/cli/generators/datasource/index.js
packages/cli/generators/extension/index.js
packages/cli/generators/model/index.js
packages/cli/generators/openapi/index.js
packages/cli/generators/rest-crud/index.js
packages/cli/generators/service/index.js
packages/cli/lib/base-generator.js
packages/cli/lib/project-generator.js
packages/cli/lib/version-helper.js
packages/cli/test/integration/generators/app.integration.js
packages/cli/test/integration/generators/copyright-monorepo.integration.js
packages/cli/test/integration/generators/copyright.integration.js
packages/cli/test/integration/lib/project-generator.js

One of the commits ignores the prompt when checking required in a model.
The other adds the functionality of using different package managers.

Add yarn support for generated projects

---

packages/http-caching-proxy/README.md

Explain when the proxy is not the right tool for the job and offer two popular tools that can record and replay HTTP interactions: Polly.JS and nock.
(This is based on a conversation I had with a LB user looking for guidance.) …

docs(http-caching-proxy): mention alternative libraries

---

CODEOWNERS

While reviewing https://github.com/strongloop/loopback-next/pull/5324, I noticed no code owner was picked for review. Closer inspection of the CODEOWNERS file shown that the entry for `/bin` did not contain any names. 
In this change, I am
- adding missing owners for `/bin` entry
- removing duplicate mention of Raymond in the comment

chore: fix CODEOWNERS for build tooling

---

docs/site/Binding.md
docs/site/Interceptors.md
packages/boot/src/booters/interceptor.booter.ts
packages/context/src/__tests__/unit/binding-inspector.unit.ts
packages/context/src/__tests__/unit/binding-key.unit.ts
packages/context/src/__tests__/unit/context.unit.ts
packages/context/src/__tests__/unit/interceptor-chain.unit.ts
packages/context/src/__tests__/unit/interceptor.unit.ts
packages/context/src/binding-inspector.ts
packages/context/src/binding-key.ts
packages/context/src/context.ts
packages/context/src/interceptor-chain.ts
packages/context/src/interceptor.ts
packages/context/src/keys.ts
packages/context/src/value-promise.ts
packages/core/src/__tests__/unit/application.unit.ts
packages/core/src/application.ts

The PR makes it easier to compose and register interceptors. This is a spin-off from #5118 

feat: improve interceptors with composition and registration

---

CODEOWNERS

At the moment, whenever a pull request touches a doc file, all team members are assigned as code owners for review. This is not very practical, because almost every pull request adding a new feature with docs included is assigned to everybody.
In this proposal, I am changing CODEOWNERS configuration for `/docs` tree to have NO code owners at all. 
- When some doc pages are changed as part of a pull request changing the implementation, then GitHub will assign the reviewers based on who is owning the code being modified 👌 
- There will be no code owners assigned for pull requests changing the documentation only 🤷  We can improve this situation in the future, e.g. by re-organizing doc pages to align the file structure with functional areas. …

chore: remove codeowners of `/docs`

---

packages/context/src/binding-decorator.ts
packages/context/src/binding-inspector.ts
packages/context/src/interceptor.ts

This change makes it possible to test if a unknown value is provider class
without casting to Constructor first.

feat(context): relax parameter type for isProviderClass()

---

docs/site/Binding.md
packages/context/src/__tests__/unit/context.unit.ts
packages/context/src/binding.ts

This makes it possible to reload singleton/context scoped bindings when its
configuration or dependencies are changed. For example, a logging provider
can be refreshed to pick up a new logging level. The same functionality can
be achieved with transient scope but with much more overheads.

feat(context): allows bindings with singleton/context scopes to be refreshed

---

packages/context/src/__tests__/unit/interceptor-chain.unit.ts
packages/context/src/interceptor-chain.ts

fix(context): allow binding keys to be used with composeInterceptors()

---

docs/site/Running-debugging-apps.md
docs/site/Setting-debug-strings.md
docs/site/sidebars/lb4_sidebar.yml

Implements https://github.com/strongloop/loopback-next/issues/4845
Include **Most of** the bug strings

docs: add running and debugging pages

---

packages/cli/lib/project-generator.js
packages/cli/lib/utils.js
packages/cli/test/acceptance/app-run.acceptance.js
packages/cli/test/integration/lib/project-generator.js

`npm run test` fails for `packages/cli` if `yarn` is not installed. This PR tests if `yarn` is available before run yarn related tests.

fix(cli): make yarn related tests conditional on the yarn availablity

---

packages/context/src/__tests__/unit/interceptor.unit.ts
packages/context/src/interceptor-chain.ts
packages/core/src/__tests__/unit/application.unit.ts

The `NonVoid` return type prohibits an interceptor function from having
void return type. This is important that an interceptor should either
return the value from downstream interceptors or a value from its own.
For example, the code will fail to compile.
```ts
const myInterceptor: Interceptor = async (ctx, next) {
// preprocessing
// ...
// subtle bug that the returned value from `next` is not returned
// back to the upstream interceptors
next();
// postprocessing
// ...
// We must have `return ...` here
}
```
Related to #5339 

feat(context): force interceptor functions to return a value

---

packages/repository/src/__tests__/acceptance/repository.acceptance.ts
packages/repository/src/__tests__/fixtures/models/product.model.ts
packages/repository/src/__tests__/unit/model/model.unit.ts
packages/repository/src/model.ts

Implements https://github.com/strongloop/loopback-next/issues/3607
Discussion see https://github.com/strongloop/loopback-next/issues/3607#issuecomment-624050020
The new conversion rules are:
> toObject() preserves type of Date, ObjectID and other non-model values. Of course, if a model instance has a property set to a value of another Model, that property must be recursively converted via toObject to a plain object.

feat(repository): to object preserves prototype

---

docs/site/OpenAPI-generator.md

Fix the format issue in https://loopback.io/doc/en/lb4/OpenAPI-generator.html:

fix(docs): fix format in OpenAPI generator

---

packages/context/src/binding-filter.ts
packages/core/src/__tests__/acceptance/extension-point.acceptance.ts
packages/core/src/extension-point.ts

We can now use `extensionFilter` to match one or more extension points for aggregation if needed.

feat(core): allow extensionFilter to take a list of extension point names

---

packages/express/src/middleware-interceptor.ts
packages/express/src/middleware.ts

1. Consistently use `DEFAULT_MIDDLEWARE_GROUP`
2. Change return type to `BindingTemplate` for `asMiddleware`.

fix: minor fixes to middleware group and binding template

---

packages/express/src/__tests__/acceptance/invoke-middleware.acceptance.ts
packages/express/src/middleware.ts
packages/express/src/providers/invoke-middleware.provider.ts
packages/express/src/types.ts

`options.next` allows invokeMiddleware to be cascaded with another middleware
chain.

feat(express): allow invokeMiddleware to take a `next` option

---

packages/booter-lb3app/src/__tests__/acceptance/booter-lb3app.acceptance.ts
packages/booter-lb3app/src/lb3app.booter.ts

Implements https://github.com/strongloop/loopback-next/issues/5299
Bind LB3 models to booter.
All credit goes to @nabdelgadir 🙇‍♀️ her spike PR has very detailed code.

feat(booter-lb3app): bind lb3 models

---

packages/repository/src/__tests__/unit/model/model.unit.ts
packages/repository/src/model.ts
packages/repository/src/repositories/legacy-juggler-bridge.ts

Extract the code for rejecting navigational properites into a standalone helper function that can be used from other repository implementations too.
I have extracted this pull request from #5222

feat(repository): extract helper `rejectNavigationalPropertiesInData`

---

packages/openapi-v3/src/decorators/api.decorator.ts
packages/rest/src/__tests__/acceptance/routing/routing.acceptance.ts

The usage of `@api({basePath: '/customers'}) is now allowed without `paths`.

feat(openapi-v3): relax `@api` to make `paths` optional with `{}` as the default

---

packages/cli/package.json

Fix issue with Yarn plug'n'play. `yeoman-environment` is required by [`lib/cli.js`](https://github.com/strongloop/loopback-next/blob/b13b3386a06332b71b33a64f5bc2ab9b4544cc8a/packages/cli/lib/cli.js#L12) but not declared in `dependencies` field in [`package.json`](https://github.com/strongloop/loopback-next/blob/b13b3386a06332b71b33a64f5bc2ab9b4544cc8a/packages/cli/package.json#L84).
> Error: @loopback/cli tried to access yeoman-environment, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

fix(cli): add previously undeclared dependency

---

packages/cli/lib/version-helper.js

Some users run into inconsistent `node_modules` after `lb4 update`. This PR removes `node_modules` to force a clean install.

feat(cli): remove `node_modules` before run `npm install` for `lb4 update`

---

.vscode/tasks.json
packages/build/bin/compile-package.js

TypeScript compiler enables `pretty` mode when using the build mode (project references). Unfortunately, pretty mode is not supported by VSCode's problem matcher and therefore VSCode is not able to parse the errors to populate the Problems window.
This change addes `--pretty false` arguments to `tsc` when invoked from VSCode task "Build project".
In order to make this work, I had to also fix `lb-tsc` to correctly recognize and pass boolean arguments with a value. Before this change, `lb-tsc -b --pretty false` would discard `--pretty false` arguments.

build: fix VSCode problem matcher for the build task 

---

benchmark/src/__tests__/benchmark.integration.ts
benchmark/src/__tests__/mocha.opts

The CI build on Windows fails once a while due to benchmark timeout

chore(benchmark): increase timeout for benchmark tests

---

packages/boot/src/__tests__/fixtures/multiple-models.model.ts
packages/boot/src/__tests__/integration/model.booter.integration.ts
packages/boot/src/boot.component.ts
packages/boot/src/booters/datasource.booter.ts
packages/boot/src/booters/index.ts
packages/boot/src/booters/model.booter.ts
packages/boot/src/booters/service.booter.ts

feat(cli): bind model classes during boot

---

docs/site/sidebars/lb4_sidebar.yml

Fixes https://github.com/strongloop/loopback-next/issues/5409
Since LB3 email connector does not work in LoopBack 4 (see discussion https://github.com/strongloop/loopback-next/issues/1979), we're removing the email connector from the LB4 sidebar.  
#1979 has the workaround and potential documentation around how to send emails in LB4. 
Once this PR lands and the change is published, I'll submit another PR in loopback.io to clean up the md files. 

fix: remove email connector from sidebar

---

docs/site/Creating-components.md
docs/site/Mixin.md
docs/site/Testing-Your-Extensions.md
docs/site/migration/models/mixins.md
examples/log-extension/README.md
examples/log-extension/src/mixins/log.mixin.ts
packages/boot/src/mixins/boot.mixin.ts
packages/core/src/index.ts
packages/core/src/mixin-target.ts
packages/express/src/middleware-registry.ts
packages/express/src/mixins/middleware.mixin.ts
packages/repository/src/__tests__/fixtures/mixins/category-property-mixin.ts
packages/repository/src/__tests__/fixtures/mixins/find-by-title-repo-mixin.ts
packages/repository/src/mixins/repository.mixin.ts
packages/rest/src/__tests__/fixtures/mixins/find-by-title-controller-mixin.ts

Introduce a new type helper `MixinTarget` allowing mixin functions to accept a type that describes public members of the target class only. This is working around the current TypeScript limitations:
- https://github.com/microsoft/TypeScript/issues/17293
- https://github.com/microsoft/TypeScript/issues/17744
- https://github.com/microsoft/TypeScript/issues/36060
Rework all existing mixins and the related documentation to use `MixinTarget<RealClass>` instead of `Constructor<any>`.
Fix any errors discovered by the compiler after enabling type checks.
See also https://github.com/microsoft/TypeScript/issues/38496
~~This PR depends on https://github.com/strongloop/loopback-datasource-juggler/pull/1839, the build will keep failing until a new version of juggler is released & loopback-next …

refactor: enable type checks inside mixin classes

---

docs/site/Creating-components.md
docs/site/extending/rest-api.md
docs/site/extending/services.md
docs/site/migration/components/overview.md
docs/site/migration/components/rest-api.md
docs/site/sidebars/lb4_sidebar.yml
docs/spikes/2020-04-how-to-migrate-lb3-components.md

_This is a part of documentation for the spike #4099 How to migrate LB3 components._
In this pull request, I am covering migration of REST API endpoints.
- Create a new page for component authors to explain how to contribute REST API endpoints
- Create a new page for component authors to explain how to contribute local service classes or providers
- Create a migration guide explaining how to migrate REST API endpoints from LoopBack 3 components to LoopBack 4 style.
This is a part of a spike, so I should not be changing the real docs, but then I figured out that since I have already wrote the content, it will give more value to our users to put the content up, even if it's not finished yet. My intention is to land this pull request even if the content is not in the shape we would …

docs: create REST API endpoints in components + LB3 migration

---

docs/site/migration/components/models.md
docs/site/migration/components/overview.md
docs/site/sidebars/lb4_sidebar.yml
docs/spikes/2020-04-how-to-migrate-lb3-components.md

Link to follow-up issues for the following areas:
- Services: https://github.com/strongloop/loopback-next/issues/5424
- API transports: https://github.com/strongloop/loopback-next/issues/5425
- Instrospection: https://github.com/strongloop/loopback-next/issues/5426
Propose to not write any migration guide for auth/auth extensions yet.
Add a placeholder page for migration of Models, finalize LB4 sidebar and the component-migration overview page.
This pull request resolves most of the remaining tasks in https://github.com/strongloop/loopback-next/issues/4099 with the exception of "Migrate Models, Entities and Repositories", for which I'll open a new pull request (I have some content to include in the migration docs).
@raymondfeng @jannyHou @emonddr: please review
👉 [Read and sign the CLA …

docs: update "LB4 Component Migration" spike proposal

---

packages/repository/src/__tests__/unit/repositories/relations-helpers/resolve-has-many-through-metadata.unit.ts
packages/repository/src/relations/has-many/has-many-through.helpers.ts
packages/repository/src/relations/has-many/has-many.helpers.ts
packages/repository/src/relations/relation.types.ts

Extract hasManyThrough relation definition and its helpers from #4438 
Adding unit tests for `hasManyThrough.help`
Changes: 
- Move the through member to `HasManyDefinition` and get rid of `hasManyThroughDefinition`.

feat(repository): adding hasManyThrough (through model) to hasMany and its helpers

---

benchmark/package-lock.json
benchmark/package.json
benchmark/src/context-binding/README.md
benchmark/src/context-binding/context-binding.ts
benchmark/tsconfig.json
docs/site/Binding.md
packages/context/src/__tests__/unit/binding.unit.ts
packages/context/src/binding.ts
packages/context/src/inject.ts
packages/context/src/resolution-session.ts

A provider class can use dependency injection to receive resolution-related
metadata such as `context` and `binding`. But the overhead to wrap a factory
function is not desired for some use cases. This PR introduces a lightweight
alternative using `toDynamicValue` as follows:
1. Add a parameter to the factory function to receive resolution context
2. Support a specialized class with a static `value` method that allows
parameter injection.
Some benchmark tests are added to `benchmark` to measure performances for
various flavors of the dynamic value resolution for bindings.
See https://github.com/strongloop/loopback-next/tree/pass-ctx-to-dynamic-value/benchmark/src/context-binding for examples.
This change is backward compatible. Existing factory functions continue to work.
👉 [Read and sign …

feat(context): provide resolution context metadata for factory functions with toDynamicValue()

---

examples/lb3-application/README.md
examples/lb3-application/lb3app/common/models/coffee-shop.js
examples/lb3-application/lb3app/test/acceptance.js
examples/lb3-application/lb3app/test/authentication.js
examples/lb3-application/lb3app/test/integration.js
examples/lb3-application/package-lock.json
examples/lb3-application/package.json
examples/lb3-application/src/__tests__/acceptance/lb3app.acceptance.ts
examples/lb3-application/src/server.ts
packages/booter-lb3app/README.md

Implements https://github.com/strongloop/loopback-next/issues/5298 and https://github.com/strongloop/loopback-next/issues/5300
Based on the spike in https://github.com/strongloop/loopback-next/issues/5004

Run LB3 tests from LB4 when LB3 is mounted on the LB4 app

---

examples/lb3-application/README.md

Recent changes in the inner content made the snippets in README.md to not run by default.

docs(example-lb3-application): update README.md to match recent changes

---

docs/bin/build-preview-site.sh

I noticed that recent changes in our website broke the fast preview (`npm run docs:preview`) - the top navigation bar was no longer displayed in the preview.
This change is fixing the problem by adding `navbar-template.html` to the list of static assets copied from `loopback.io` to the preview site. …

fix(docs): copy navbar-template to fast preview site

---

docs/site/Express-middleware.md
packages/express/src/__tests__/acceptance/middleware-registeration.acceptance.ts
packages/express/src/__tests__/acceptance/test-helpers.ts
packages/express/src/types.ts

To simulate expressApp.get(...), post(...), we can create an Express router.
add handlers, and register the router as an Express middleware to LoopBack.

test(express): add a test to illstruate how to use express router

---

packages/repository/src/__tests__/unit/model/model.unit.ts
packages/repository/src/model.ts

Fixes https://github.com/strongloop/loopback-next/issues/1914#issuecomment-628900038
Reported by @joel-izaguirre

Hidden properties when strict is false

---

packages/repository-json-schema/src/__tests__/unit/filter-json-schema.unit.ts
packages/repository-json-schema/src/filter-json-schema.ts

Allow user to define `Filter` object without "include" property.

honor excluded "include" property

---

docs/bin/copy-changelogs.js

Fixes https://github.com/strongloop/loopback-next/issues/5474
Depends on https://github.com/strongloop/loopback.io/pull/985

fix(docs): set `toc_level` to customize toc layout for changelogs

---

packages/context/src/__tests__/unit/inject.unit.ts
packages/context/src/inject.ts

`inspectTargetType` fails to handle the following case correctly:
```ts
class HelloProviderWithMI {
static value(
@inject('count')
count: number,
) {
return 'hello';
}
count(
@inject('count')
count: number,
) {
return count;
}
}
```
The PR makes sure the parameter design type is checked if the injection is for a parameter.

fix(context): inspectTargetType needs to check parameters if index is a number

---

docs/site/Extending-OpenAPI-specification.md
docs/site/Server.md

When working on https://github.com/strongloop/loopback-next/pull/5493, I think it's better to add a section for retrieving the openapi spec in code from the app. Therefore created this PR. It also explains the usage of adding spec enhancer.

docs: usage of openapi spec enhancer

---

docs/site/migration/components/models.md
docs/spikes/2020-04-how-to-migrate-lb3-components.md
packages/repository/src/__tests__/unit/mixins/repository.mixin.unit.ts
packages/repository/src/mixins/repository.mixin.ts

In the first commit, I am adding a new optional property `models` to `Component` interface, to allow extension developers to declaratively contribute model classes to be bound in the target context. (I am aware that https://github.com/strongloop/loopback-next/pull/5432 added `createModelClassBinding`, I just realized it's different from the existing approach we are using for components contributing repositories.)
In the second commit, I am _starting_ the migration guide for LB3 components contributing models. Because we haven't figured out yet what should be our recommended solution for LB4 components wishing to contribute Entites and Repositories, I opened a follow-up issue https://github.com/strongloop/loopback-next/issues/5476 to figure it out.
This is the last part of _Spike: How to …

Allow components to contribute models + migration guide for LB3 components

---

packages/cli/generators/openapi/schema-helper.js
packages/cli/test/unit/openapi/schema-helper.unit.js

Mapping array types as follows:
- `(string | number)[]` (instead of `string | number[]`)
- `({x: string} & {y: boolean})[]` (instead of `{x: string} & {y: boolean}[]` )

fix(cli): group union/intersection types for array

---

docs/site/tutorials/connectors/Postgresql-tutorial.md

Closes https://github.com/strongloop/loopback-next/issues/4877

docs: adding postgres connector tutorial for lb4

---

appveyor.yml

When running Appveyor, there is error:
```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
1: 00F6D5CE node::MakeCallback+3982
2: 0139AD32 v8::internal::Heap::MaxHeapGrowingFactor+8194
3: 01391F21 v8::internal::ScavengeJob::operator=+14993
4: 0139966E v8::internal::Heap::MaxHeapGrowingFactor+2366
npm ERR! code ELIFECYCLE
npm ERR! errno 134
```
@raymondfeng suggested to configure the heap.

fix: set NODE_OPTIONS in appveyor.yml

---

packages/cli/generators/update/index.js
packages/cli/lib/base-generator.js
packages/cli/lib/version-helper.js
packages/cli/package-lock.json
packages/cli/package.json

If `lb4 update` changes dependencies of an application, the user will be prompted to check out 
https://loopback.io/doc/en/lb4/changelog.index.html. It will remind our users to pay attention to breaking changes.

feat(cli): add a prompt for `lb4 update` to open changelog

---

docs/site/migration/boot-scripts.md

In async start function on line 260, TodoRepo variable is used but during variable injection in constructor, the variable name used is todoRepo so changed the start function variable name to todoRepo from TodoRepo

fix(docs): fix variable name in boot script docs

---

docs/site/tutorials/todo-list/todo-list-tutorial-controller.md

There's a tiny error that I noticed as I went through these incredibly written docs :)

chore: remove extra }) in docs

---

packages/boot/src/__tests__/unit/boot.custom-binding.component.unit.ts
packages/boot/src/__tests__/unit/mixins/boot.mixin.unit.ts
packages/boot/src/mixins/boot.mixin.ts
packages/boot/src/types.ts

There is a small misbehavior in `boot.mixin.ts`, where upon invoking `this.component(ComponentClass)`, `mountComponentBooters` will assume `"components.${class.name}"` to be the binding key, even if another key was specified.
This presents itself in Applications where components marked with `@bind()` using a custom name, and attempting to use them:
```ts
export const COMPONENT_KEY = BindingKey.create<MyComponent>('org.my.namespace.MyComponent');
@bind({
tags: {[ContextTags.KEY]: COMPONENT_KEY},
scope: BindingScope.SINGLETON,
})
export class MyComponent implements Component, LifeCycleObserver {
}
```
```ts
import { MyComponent } from '@myScope/my-library';
export class MyApplication extends BootMixin(ServiceMixin(RestApplication)) {
constructor() {
this.component(MyComponent);
// Error: …
```

Fix: bootmixin should use super.component() to get binding key

---

docs/site/Model.md
packages/repository-json-schema/src/__tests__/integration/build-schema.integration.ts
packages/repository-json-schema/src/__tests__/unit/build-schema.unit.ts
packages/repository-json-schema/src/build-schema.ts

Fixes https://github.com/strongloop/loopback-next/issues/4754
To define a nested array property with `@property.array()`, you must provide a json schema to describe the sub array item:
```ts
@model()
class TestModel {
// alternatively use @property.array('array')
@property.array(Array, {
jsonSchema: {
type: 'array',
items: {type: 'string'},
},
})
nestedArr: Array<Array<string>>;
}
```
A few issues this PR addresses:
- We didn't allow nested array property before due to 
https://github.com/strongloop/loopback-next/blob/ef155eeddf11895bac8ddc491cb87c1e5b7398d0/packages/repository-json-schema/src/build-schema.ts#L260
which is not correct. I tested with todo app, when decorate the nested array property well, creating & retrieving an instance works properly.
- It's not possible to infer the …

fix: array decorator

---

examples/access-control-migration/package.json
examples/access-control-migration/src/migrate.ts
examples/access-control-migration/src/openapi-spec.ts
examples/greeting-app/package.json
examples/greeting-app/src/openapi-spec.ts
examples/lb3-application/package.json
examples/lb3-application/src/openapi-spec.ts
examples/multi-tenancy/package.json
examples/multi-tenancy/src/openapi-spec.ts
examples/rest-crud/package.json
examples/rest-crud/src/openapi-spec.ts
examples/todo-jwt/package.json
examples/todo-jwt/src/openapi-spec.ts
examples/todo-list/package.json
examples/todo-list/src/openapi-spec.ts
examples/todo/package.json
examples/todo/src/openapi-spec.ts
examples/validation-app/package.json
examples/validation-app/src/openapi-spec.ts
packages/cli/generators/app/templates/src/openapi-spec.ts.ejs
packages/cli/generators/project/templates/package.json.ejs
packages/cli/generators/project/templates/package.plain.json.ejs
packages/cli/package.json
packages/cli/snapshots/integration/generators/app.integration.snapshots.js
packages/cli/test/integration/generators/app.integration.js
packages/rest/src/__tests__/integration/export-openapi-spec.integration.ts
packages/rest/src/rest.application.ts
packages/rest/src/rest.server.ts

Alternative option to https://github.com/strongloop/loopback-next/pull/5508

feat: generate src/openapi-spec.ts to export openapi spec into a file

---

packages/repository/src/__tests__/unit/model/define-model-class.unit.ts
packages/repository/src/define-model-class.ts

Before this change, the following code would create an instance with the type of the base model class, ignoring custom model properties:
```ts
const Product = defineModelClass<typeof Model, {name: string}>(
Model,
definition,
);
const p = new Product();
// p has type Model now
```
This patch fixes the problem by changing the order in which constructor functions are defined in `DynamicModelCtor`, so that the compiler always picks the constructor returning `Base & Props`.
I discovered this problem while reviewing #5591.
- Affected artifact templates in …

fix(repository): fix DynamicModelCtor type to correctly preserve Props

---

docs/site/Dynamic-models-repositories-controllers.md
docs/site/sidebars/lb4_sidebar.yml

Addresses https://github.com/strongloop/loopback-next/issues/4296.
How to dynamically add models, repositories, and controllers during
runtime.

docs: dynamic models, repositories, and controllers

---

bin/update-ts-project-refs.js

Normalize 'update-ts-project-refs.ts' paths to be POSIX-compliant (use forward slash '/')  irregardless of host platform.
This resolves an issue with Windows-based development environments that would cause all `tsconfig.json` project reference paths to be updated to use Windows path syntax.
**@loopback/tsdocs `tsconfig.json`:**
```diff
{
"$schema": "http://json.schemastore.org/tsconfig",
"extends": "@loopback/build/config/tsconfig.common.json",
"compilerOptions": {
"outDir": "dist",
"rootDir": "src",
"composite": true
},
"include": [
"src"
],
"references": [
{
-      "path": "..\\testlab\\tsconfig.json"
+      "path": "../testlab/tsconfig.json"
}
]
}
``` …

fix: normalize project ref update path

---

examples/access-control-migration/src/__tests__/acceptance/project.acceptance.ts
packages/authorization/src/__tests__/acceptance/authorization.acceptance.ts
packages/authorization/src/__tests__/acceptance/authorization.options.acceptance.ts
packages/authorization/src/authorize-interceptor.ts
packages/authorization/src/types.ts

Fixes #5411 according to the [suggested solution](https://github.com/strongloop/loopback-next/issues/5411#issuecomment-628065626)

set default HTTP status code for authorization error to 403

---

docs/site/Copyright-generator.md
packages/cli/generators/copyright/header.js
packages/cli/generators/copyright/index.js
packages/cli/generators/copyright/license.js
packages/cli/test/integration/generators/copyright.integration.js

Add `custom` license to generate custom copyright/license headers, such as:
```
=============================================================================
Licensed Materials - Property of <%= owner %>
(C) Copyright <%= owner %> <%= years %>
US Government Users Restricted Rights - Use, duplication or disclosure
restricted by GSA ADP Schedule Contract with <%= owner %>.
=============================================================================
```

feat(cli): allow custom copyright/license lines

---

packages/context/src/__tests__/unit/try-catch-finally.unit.ts
packages/context/src/__tests__/unit/value-promise.unit.ts
packages/context/src/value-promise.ts

Add a helper function to apply `try-catch-finally` to value or promise.
Extracted from https://github.com/strongloop/loopback-next/pull/5586.

feat(context): add `tryCatchFinally` helper function for value or promise

---

packages/repository/src/__tests__/unit/repositories/constraint-utils.unit.ts
packages/repository/src/__tests__/unit/repositories/relations-helpers/resolve-has-many-through-metadata.unit.ts
packages/repository/src/relations/has-many/has-many-through.helpers.ts
packages/repository/src/repositories/constraint-utils.ts

Add two more helpers for HasManyThrough relation

feat(repository): add more helpers for HasManyThrough

---

docs/site/decorators/Decorators_openapi.md
docs/site/tutorials/connectors/Mongodb-tutorial.md
docs/site/tutorials/connectors/Postgresql-tutorial.md

Closes https://github.com/strongloop/loopback-next/issues/4879

docs: adding MongoDB connector tutorial

---

packages/repository/src/__tests__/unit/repositories/has-many-through-repository-factory.unit.ts
packages/repository/src/relations/has-many/has-many-through-repository.factory.ts
packages/repository/src/relations/has-many/has-many-through.repository.ts
packages/repository/src/relations/has-many/index.ts

Add repository factory for hasManyThrough

feat(repository): add repo factory and tests for hasManyThrough

---

docs/site/Controllers.md
docs/site/DataSources.md
docs/site/Model.md
docs/site/Repositories.md

Describe how to create datasources, models, repositories, and
controllers at runtime. Part of addressing https://github.com/strongloop/loopback-next/issues/4296.
First half addressed by https://github.com/strongloop/loopback-next/pull/5591.

docs: dynamic datasource, model, repository, and controller

---

docs/site/Authentication-overview.md
extensions/authentication-passport/README.md

Sub PR for https://github.com/strongloop/loopback-next/pull/5598
- Add the passport page with new layout

docs: refactor passport doc

---

packages/express/src/__tests__/acceptance/invoke-middleware.acceptance.ts
packages/express/src/providers/invoke-middleware.provider.ts

Before this change, if we have an injected `invokeMidddleware` from the `InvokeMiddlewareProvider`, the `next` option is not honored.

fix(express): ensure options are honored for `invokeMiddleware` resolved from the provider

---

docs/ROADMAP.md

I created a new epic https://github.com/strongloop/loopback-next/issues/5669 to keep track of internal tooling improvements we would like to investigate & implement in 2020Q3.
In this PR, I am updating our ROADMAP.md file with a link to the epic.

docs: add a link to epic tracking tooling improvements

---

docs/site/DEVELOPING.md

Based on the discussion in #5550, I am updating the documentation for developers with the definition of "building-blocks", a list of packages considered as building blocks, and finally instructions on how to treat these packages in our docs, CLI templates and examples.
After this PR is approved, I'll created follow-up stories to ensure proper use of the following packages:
- packages/context - already done in #5625
- packages/openapi-v3
The following foundation-level packages are already not depended on directly:
- packages/express
- packages/http-server
- packages/metadata
- packages/repository-json-schema
- New tests added or existing tests modified to cover all …

docs: add a new section on content organization

---

docs/site/Express-middleware.md
docs/site/Middleware.md
examples/passport-login/package.json
examples/passport-login/tsconfig.json

- Update code snippets to import from `@loopback/rest` instead of `@loopback/express`.
- Remove `@loopback/express` from dependencies of `examples/passport-login`, it was not used at all.
This is a follow-up for #5659, see also #5550

Hide `@loopback/express` from framework-level documentation

---

docs/site/Extending-LoopBack-4.md
docs/site/Repositories.md
docs/site/Sequence.md
docs/site/Update-generator.md
docs/site/tutorials/core/3-context-in-action.md
examples/greeter-extension/README.md
extensions/authentication-passport/README.md
extensions/cron/README.md
extensions/logging/README.md
packages/authorization/README.md
packages/eslint-config/eslintrc.js

Update few more places to use `@loopback/core` only, or to explain that `@loopback/core` is re-exporting all `@loopback/context` APIs and is the preferred package to import from.
See #5625 which started the work but missed few places needing updates.
This PR is a follow-up for #5659, see also #5550.

refactor: use `@loopback/core` instead of `@loopback/context`

---

docs/site/Creating-decorators.md
docs/site/tutorials/core/10-advanced-recipes.md
docs/site/tutorials/core/2-architecture.md
examples/log-extension/README.md
examples/log-extension/src/keys.ts
extensions/authentication-passport/package.json
extensions/authentication-passport/tsconfig.json
packages/authentication/package.json
packages/authentication/tsconfig.json

- Remove unused dependency `@loopback/metadata` from `extensions/authentication-passport` and ` packages/authentication`
- Remove references to `@loopback/metadata`, rework code and docs to import from `@loopback/core` instead.
This is a follow-up for #5659, see also #5550.

Hide `@loopback/metadata` from framework-level documentation

---

packages/context/src/__tests__/unit/binding.unit.ts
packages/context/src/__tests__/unit/context-view.unit.ts
packages/context/src/binding.ts
packages/context/src/context-view.ts
packages/context/src/context.ts

Declare `on` and `once` overload methods to describe event parameters in a strongly typed way:
```ts
context.on('bind' | 'unbind', ContextEventListener)
context.once('bind' | 'unbind', ContextEventListener)
binding.on('changed', BindingEventListener)
binding.once('changed', BindingEventListener)
view.on('refresh', listener);
view.once('refresh', listener);
// and so on
```
The change preserves the generic variant provided by `EventEmitter` too and thus is fully backwards compatible.
- Affected artifact templates in `packages/cli` …

feat(context): add strongly typed `on` and `once` methods

---

packages/boot/src/__tests__/acceptance/application-metadata.booter.acceptance.ts
packages/boot/src/__tests__/acceptance/component-application.booter.acceptance.ts
packages/boot/src/__tests__/acceptance/controller.booter.acceptance.ts
packages/boot/src/__tests__/acceptance/crud-rest.api-builder.acceptance.ts
packages/boot/src/__tests__/acceptance/model-api.booter.acceptance.ts
packages/boot/src/__tests__/fixtures/application.ts
packages/boot/src/__tests__/integration/controller.booter.integration.ts
packages/boot/src/__tests__/integration/datasource.booter.integration.ts
packages/boot/src/__tests__/integration/interceptor.booter.integration.ts
packages/boot/src/__tests__/integration/lifecycle-observer.booter.integration.ts

Extracted from #5011. It cleans up the tests to avoid conflicting sandbox paths for parallel testing.

fix(boot): make sure sandbox directories are removed after tests

---

packages/context/src/__tests__/acceptance/class-level-bindings.acceptance.ts
packages/context/src/__tests__/acceptance/method-level-bindings.acceptance.ts
packages/context/src/__tests__/unit/resolution-session.unit.ts
packages/context/src/__tests__/unit/resolver.unit.ts
packages/context/src/binding.ts
packages/context/src/context.ts
packages/context/src/inject.ts
packages/context/src/resolution-session.ts
packages/context/src/resolver.ts
packages/metadata/src/decorator-factory.ts

Current issue: when a binding key is not bound, a long stack trace is printed and it's not easy to find out where the failure happens. This PR introduces `ResolutionError` to capture more contextual information.
TBD:
I was planning to extend the `message` with such information, but it breaks a lot of existing test assertions, for example:
```
AssertionError: expected [Promise] to be rejected with a message matching 'bar: error', but got 'bar: error (@TestClass.prototype.bar => cb8e48c2-8d0e-4d28-bd93-0738840afdd9#bar)'
```
Should we bite the bullet to fix old assertions?

feat(context): improve binding resolution error reporting with more contextual info

---

docs/site/Components.md
packages/core/src/__tests__/unit/application.unit.ts
packages/core/src/application.ts
packages/core/src/component.ts

Add services to component artifacts and automatically bind services to application when mounting the component.
Currently, to add a service from a component to an application the following needs to be done
```ts
export class MyComponent implements Component {
constructor(@inject(CoreBindings.APPLICATION_INSTANCE) app: Application) {
app.service(MyService);
}
}
```
After this change adding services would be possible without a workaround and similar to adding controllers, repositories, models, life cycle observers, etc.
```ts
export class MyComponent implements Component {
services = [MyService];
}
``` …

feat(core): add services to component artifacts

---

docs/site/Mixin.md

Fixes the issue mentioned in comment https://github.com/strongloop/loopback-next/pull/5718#issuecomment-643329485

fix(docs): fix missing % in mixin.md

---

packages/context/src/__tests__/unit/resolver.unit.ts
packages/context/src/binding.ts

Fixes https://github.com/strongloop/loopback-next/issues/5730
Before this PR, we alway resolve a promise before caching the bound value for CONTEXT/SINGLETON scopes. As a result, there might be racing condition where the same binding is being injected concurrently.

fix(context): cache binding value or promise as-is to avoid racing condition

---

docs/site/Dynamic-models-repositories-controllers.md
docs/site/migration/auth/authentication.md
docs/site/sidebars/lb4_sidebar.yml
docs/site/tutorials/authentication/Authentication-Tutorial.md
extensions/authentication-passport/README.md
packages/authentication/README.md

Fix broken links
Also, the authentication extension under the "Using Components" section does not exist, so I added there too. 

fix(docs): fix broken links

---

packages/repository/src/__tests__/integration/repositories/relation.factory.integration.ts
packages/repository/src/relations/has-many/has-many-through.repository.ts

continuation of #4438 and #2359 
Add implementation and tests for CRUD operations. 
Methods `link` and `unlink` need more discussions.

feat(repository): CRUD implementation and tests for hasManyThrough Repository

---

docs/site/Context.md
packages/core/src/__tests__/unit/application.unit.ts
packages/core/src/application.ts

@frbuceta pointed an error in https://loopback.io/doc/en/lb4/Context.html#configuration-by-convention.
This PR allows `CoreBindings.APPLICATION_INSTANCE` to have corresponding `config`. It also keeps backward compatibility for `CoreBindings.APPLICATION_CONFIG`.

feat(core): enable application config with configure/getConfig/@config

---

docs/site/sidebars/lb4_sidebar.yml

To further align our sidebar with the four-quadrant documentation system (see #5549 and #5718), I am proposing to rename "Usage Scenarios" to "How-to guides". 
This pull request is extracted from https://github.com/strongloop/loopback-next/pull/5768.

docs: rename "Usage Scenarios" to "How-to guides"

---

packages/cli/snapshots/integration/snapshot-matcher/suite-first-run.integration.snapshots.js
packages/cli/snapshots/integration/snapshot-matcher/suite-second-run.integration.snapshots.js
packages/cli/test/integration/snapshot-matcher/common.suite.js
packages/cli/test/integration/snapshot-matcher/suite-first-run.integration.js
packages/cli/test/integration/snapshot-matcher/suite-second-run.integration.js
packages/cli/test/snapshot-matcher.js

- add debug logs to snapshot-matcher to make it easier to troubleshoot snapshot-matcher related problems,
especially when running the tests in parallel.
- add a test suite with a shared test suite to verify snapshot-matcher's support for this advanced test organization. This scenario is tricky to get right when running tests in parallel.
Extracted from #5724
👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) …

cli: add a test suite for snapshot-matcher + improve debug logs

---

docs/site/reference/error-codes.md
docs/site/sidebars/lb4_sidebar.yml

This is a follow-up to #5718, see also #5549.

docs: move "Error handling" to "Error codes" in "Reference guides"

---

docs/site/reference/reserved-binding-keys.md
docs/site/sidebars/lb4_sidebar.yml

Also remove "Overview" heading from the page. I feel the heading is redundant when there are no other headings. Before this change, the page was rendered with a single-item Table of Contents at the top, which looked weird to me. After this change, the pages is rendered as a single block with the page title as the only heading.
This is a follow-up to #5718, see also #5549. …

docs: move "Reserved binding keys" to "Reference guides"

---

docs/site/Server.md
docs/site/guides/deployment/enabling-https.md
docs/site/guides/rest/customize-openapi.md
docs/site/sidebars/lb4_sidebar.yml

As part of our move towards four-quadrant documentation system (see #5549 and #5718), we (@hacksparrow and me) took a look at restructuring [Server](https://github.com/strongloop/loopback-next/blob/d653cfc4c96c78282e408b5f7054eee04a67841c/docs/site/Server.md) page and extracted two new how-to guides:
- Enabling HTTPS (under Deployment)
- Customizing how OpenAPI spec is served (under a new section REST APIs)
The goal of this work is to explore how to best (re)structure the existing content, so that we can create better user-stories. 
- Affected artifact templates …

docs: extract how-to guides from "Server" page

---

packages/boot/src/__tests__/acceptance/application-metadata.booter.acceptance.ts
packages/boot/src/__tests__/acceptance/component-application.booter.acceptance.ts
packages/boot/src/__tests__/acceptance/controller.booter.acceptance.ts
packages/boot/src/__tests__/acceptance/crud-rest.api-builder.acceptance.ts
packages/boot/src/__tests__/acceptance/model-api.booter.acceptance.ts
packages/testlab/src/__tests__/integration/test-sandbox.integration.ts
packages/testlab/src/test-sandbox.ts

Extracted from https://github.com/strongloop/loopback-next/pull/5744 for ease of review.

fix: ensure unique sandbox directories for boot tests

---

README.md

I hope I listed everybody who used to be a maintainer at some point in the past 🤞 

docs: add "alumni" section to README

---

docs/site/Creating-components.md

`Using-components.md` doesn't exist.
I changed the link to `components.md` instead, which is where I assume the link was supposed to take me.
(I'm unable to sign the license agreement currently. I will keep retrying, otherwise feel free for someone else to just make this change)

docs: Incorrect link to using components from creating components

---

packages/repository/src/__tests__/integration/repositories/relation.factory.integration.ts
packages/repository/src/__tests__/unit/repositories/relations-helpers/resolve-has-many-through-metadata.unit.ts
packages/repository/src/relations/has-many/has-many-through-repository.factory.ts
packages/repository/src/relations/has-many/has-many-through.helpers.ts
packages/repository/src/relations/has-many/has-many-through.repository.ts

Implemented `link` and `unlink` methods.
_(continuation of #4438, #5674 and #2359)_

feat(repository): add link and unlink methods for hasManyThrough repository

---

packages/rest/src/index.ts

Some of the public APIs use strong-error-handler types. This PR makes it
easy to override/customize RejectProvider.

feat(rest): expose types from strong-error-handler

---

packages/repository-tests/src/crud/relations/acceptance/has-many-through.relation.acceptance.ts
packages/repository-tests/src/crud/relations/fixtures/models/cart-item.model.ts
packages/repository-tests/src/crud/relations/fixtures/models/customer-cart-item-link.model.ts
packages/repository-tests/src/crud/relations/fixtures/models/customer.model.ts
packages/repository-tests/src/crud/relations/fixtures/models/index.ts
packages/repository-tests/src/crud/relations/fixtures/repositories/cart-item.repository.ts
packages/repository-tests/src/crud/relations/fixtures/repositories/customer-cart-item-link.repository.ts
packages/repository-tests/src/crud/relations/fixtures/repositories/customer.repository.ts
packages/repository-tests/src/crud/relations/fixtures/repositories/index.ts
packages/repository-tests/src/crud/relations/fixtures/repositories/order.repository.ts
packages/repository-tests/src/crud/relations/helpers.ts
packages/repository/src/relations/has-many/has-many-through.helpers.ts

test(repository-tests): adding acceptance tests for hasManyThrough relation

---

fixtures/mock-oauth2-provider/package.json

See the error mentioned in https://github.com/strongloop/loopback-next/issues/5573#issuecomment-649046288
npm still has 0.1.0 for `@loopback/mock-oauth2-provider`

fix(mock-oauth2-provider): reset publish status

---

packages/rest/src/__tests__/acceptance/coercion/coercion.acceptance.ts
packages/rest/src/coercion/coerce-parameter.ts
packages/rest/src/parser.ts
packages/rest/src/types.ts
packages/rest/src/validation/request-body.validator.ts

Connect to #4992 
Filter with non-string properties like `?filter[fields][name]=false` are not coerced, so `false` turns to be `'false'`. This PR applies coercion for parameter query.

feat: coerce query object with schema

---

.mocharc.js
docs/site/DEVELOPING.md
package.json
packages/cli/test/integration/cli/cli.integration.js

- move Mocha flags from CLI args to config file 
- enable parallel execution of Mocha tests  by adding `parallel: true` to monorepo's root mocha config
- update DEVELOPING.md to mention parallel execution and to show how to run tests in series
This pull request supersedes #5011. I am intentionally keeping this change small and enabling parallel test execution only when the tests are executed for the entire monorepo. We can discuss further improvements after this pull request is landed. (E.g. which packages should run tests in parallel when running `npm t` from their package directory. At the moment, users can opt into parallel execution via `npm t -- -p`).
👉 [Check …

test: enable parallel execution of Mocha tests

---

docs/site/Fields-filter.md

Update docs after fixing #4992 

docs: remove fields filter warning

---

packages/openapi-v3/src/__tests__/integration/controller-spec.integration.ts
packages/openapi-v3/src/__tests__/integration/operation-spec.integration.ts
packages/repository-json-schema/src/__tests__/integration/build-schema.integration.ts
packages/repository-json-schema/src/__tests__/integration/schema-ref.integration.ts
packages/repository-json-schema/src/__tests__/unit/build-schema.unit.ts
packages/repository-json-schema/src/build-schema.ts
packages/rest/src/__tests__/acceptance/validation/validation.acceptance.ts
packages/rest/src/__tests__/unit/rest.server/rest.server.open-api-spec.unit.ts

#3804
Added type 'object' to generated model schema to allow `ajv` validation to work correctly.
Fixes #3804 

fix(repository-json-schema): added type 'object' to model json schema

---

docs/site/sidebars/lb4_sidebar.yml

The link https://loopback.io/doc/en/lb4/Authentication-Tutorial.html doesn't exist, it should be https://loopback.io/doc/en/lb4/Authentication-tutorial.html. There are 2 occurrences in the sidebar, we probably fixed one of them last time. 

fix: broken link in sidebar

---

examples/rest-crud/src/__tests__/acceptance/todo.acceptance.ts
examples/todo-list/src/__tests__/acceptance/todo-list-image.acceptance.ts
examples/todo-list/src/__tests__/acceptance/todo-list-todo.acceptance.ts
examples/todo-list/src/__tests__/acceptance/todo.acceptance.ts
examples/todo/src/__tests__/acceptance/todo.acceptance.ts
packages/repository/src/__tests__/unit/model/model.unit.ts
packages/rest/src/__tests__/acceptance/routing/routing.acceptance.ts

TypeScript 4.x reports errors for `delete x.y` if `y` is not optional

fix: ensure delete only applies to optional properties

---

docs/site/exposing-graphql-apis.md

---
I hit an error while running through the sample commands. I believe that `openapi-to-graphql` should be `openapi-to-graphql-cli`.
```bash
$ npx openapi-to-graphql --port=3001 http://localhost:3000/openapi.json
command not found: openapi-to-graphql
```

fix(docs): fix typo in guide command

---

packages/boot/src/__tests__/acceptance/component-application.booter.acceptance.ts
packages/boot/src/booters/component-application.booter.ts

Before this PR, the following calls will override each other as they have the same binding key:
```
createComponentApplicationBooterBinding(subApp1);
createComponentApplicationBooterBinding(subApp2);
```
The fix uses application name to build the binding key to avoid conflicts.

fix(boot): generate unique binding keys for component application booters

---

packages/repository/src/__tests__/integration/repositories/relation.factory.integration.ts
packages/repository/src/__tests__/unit/model/model.unit.ts
packages/repository/src/__tests__/unit/repositories/belongs-to-repository-factory.unit.ts
packages/repository/src/__tests__/unit/repositories/relations-helpers/resolve-belongs-to-metadata.unit.ts
packages/repository/src/model.ts
packages/repository/src/relations/belongs-to/belongs-to.helpers.ts
packages/repository/src/relations/relation.types.ts

* create helpers for belongsTo, hasOne, and hasMany relations
* infer the keyFrom value for belongsTo relation
Fixes https://github.com/strongloop/loopback-next/issues/5384

feat(repository): add helpers to create relations

---

.lintstagedrc
docs/site/DEVELOPING.md
package-lock.json
package.json

Adds precommit hook to lint staged files. Also fixes prettier EOL handling on Windows.
Running linting on the whole project manually takes a while. It is much more convenient to lint only modified files automatically every time.
Or is there a good reason not to do so?
**EDIT:** Just saw #5462. This one is slightly different though.

chore: lint staged files before commit

---

packages/cli/generators/repository/index.js
packages/cli/intl/en/messages.json

fixes #5656 
Only `custom repository` was not being translated.

fix: globalize strings for repository generator

---

packages/cli/generators/project/templates/package.json.ejs
packages/cli/generators/project/templates/package.plain.json.ejs
packages/cli/test/integration/lib/project-generator.js

See #5692. This pull request changes the project template only, I'll be updating documentation files later (but still as part of #5692).
It is safe to remove `@loopback/openapi-v3` from the template, because we are not importing from that package in any other CLI templates. 

feat(cli): remove openapi-v3 from project template dependencies

---

packages/cli/test/integration/cli/cli.integration.js

Instead of supressing the linter check, use a jsdoc-style comment to provide type information about `this` value.
See https://github.com/strongloop/loopback-next/pull/5831

test: improve fix for eslint no-invalid-this

---

docs/site/Command-line-interface.md
docs/site/Extending-OpenAPI-specification.md
docs/site/Update-generator.md
docs/site/decorators/Decorators_openapi.md

Rework references to `@loopback/openapi-v3` to refer to `@loopback/rest` instead.
See #5692

docs: remove references to openapi-v3

---

extensions/apiconnect/package.json
extensions/apiconnect/src/apiconnect.spec-enhancer.ts
extensions/apiconnect/tsconfig.json

Use `@loopback/rest` to access openapi-related types and helpers.
This pull request is a part of #5692.
~~BREAKING CHANGE: `@loopback/core` and `@loopback/rest` were moved to peer dependencies, to ensure the extension uses application's version of these modules. If this change breaks your application (which is unlikely), then simply add both `@loopback/core` and `@loopback/rest` to your project dependencies.~~
~~_I am observing timeouts when running the tests locally (even on master), I think they are not related to my changes and will rely on CI builds to confirm._~~
- API Documentation in code was …

feat: remove openapi-v3 from apiconnect dependencies

---

packages/repository-tests/src/crud/relations/acceptance/has-many-through.relation.acceptance.ts
packages/repository-tests/src/crud/relations/acceptance/has-many.relation.acceptance.ts
packages/repository/src/__tests__/integration/repositories/relation.factory.integration.ts
packages/repository/src/__tests__/unit/repositories/relations-helpers/resolve-has-many-through-metadata.unit.ts
packages/repository/src/relations/has-many/has-many-through-repository.factory.ts
packages/repository/src/relations/has-many/has-many-through.helpers.ts
packages/repository/src/relations/has-many/has-many-through.repository.ts

fix(repository): hasManyThrough can delete correct target n through based on filter

---

docs/site/Community-extensions.md
docs/site/sidebars/lb4_sidebar.yml

Fixes #5702
Add a community extensions page with some of the extensions we know about. The intention of this page is to have community adding their own extensions there. 
Preview of the change: 

feat(docs): add community extensions page

---

docs/README.md
docs/site/index.md

feat(docs): explain how is the content organized

---

packages/context/src/__tests__/unit/context.unit.ts
packages/context/src/context.ts

Fixes https://github.com/strongloop/loopback-next/issues/5943

fix(context): destroy debug instances to avoid memory leak

---

docs/site/Loopback-component-authorization.md
packages/authorization/README.md

Corrects some typos I have encountered while following the documentation.
👉 [I have read and signed the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-next) 👈
👉 [I have checked out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

docs(authorization): correct typos

---

docs/site/Include-filter.md
packages/repository-json-schema/src/__tests__/unit/filter-json-schema.unit.ts
packages/repository-json-schema/src/filter-json-schema.ts
packages/rest/src/__tests__/acceptance/coercion/coercion.acceptance.ts

Fixes https://github.com/strongloop/loopback-next/issues/5872
Nested inclusion filter like 
```ts
{
include: [{
relation: 'todos',
scope: {
// after enabling coercion against spec schema in PR 
// https://github.com/strongloop/loopback-next/pull/5808
// it breaks cuz scope schema doesn't have property include.
include: [{
relation: 'someOtherRelation',
}]
}
}]
}
```
Fails. Because the `scope` schema is generated from `EmptyModel`, which doesn't have a relation:
https://github.com/strongloop/loopback-next/blob/683e162de982acde34b45101383a5d69cf1c0df1/packages/repository-json-schema/src/filter-json-schema.ts#L38
and thus does not have `include` generated in its `properties`:
https://github.com/strongloop/loopback-next/blob/683e162de982acde34b45101383a5d69cf1c0df1/packages/repository-json-sch …

fix: nested scope filter

---

packages/build/src/fail-on-console-logs.js
packages/tsdocs/src/__tests__/acceptance/tsdocs.acceptance.ts

I noticed that `npm test` is no longer failing when unwanted console logs are printed. This problem was introduced by parallel test execution, the test suite fails when executed in serial. The first commit reworks `fail-on-console-logs.js` helper to leverage Mocha Global/Root hooks to get the desired behavior for parallel execution too.
The second commit fixes `@loopback/tsdocs` test suite to suppress console logs reported by `@microsoft/api-extractor`. I wish there was a config option to silence these logs! Unfortunately and AFAICT, api-extractor does not allow configurable handling of "Console category" messages:
https://github.com/microsoft/rushstack/blob/bdd3ee54b3a05772347baf12b0817660b07aa265/apps/api-extractor/src/collector/MessageRouter.ts#L531 As a workaround, I implemented a …

Rework fail-on-console-logs to support parallel test execution + remove extraneous logs from api-extractor

---

extensions/pooling/README.md
extensions/pooling/src/__tests__/acceptance/pooling.acceptance.ts
extensions/pooling/src/pooling.ts

Sometimes the resource needs to the request context during acquire, for
example, to access security credentials.

feat(pooling): allow optional request context to be passed to acquire

---

packages/rest-explorer/package-lock.json
packages/rest-explorer/package.json

Related to https://github.com/swagger-api/swagger-ui/issues/6249
When clicked on the /ping controller, there is only loading icon. 
This fix is suggested by @raymondfeng to revert to use 3.30.0.

fix: pin swagger-ui-dist to v3.30.0

---

docs/site/Model.md
docs/site/Parsing-requests.md
examples/validation-app/README.md
examples/validation-app/src/__tests__/acceptance/validate.acceptance.ts
examples/validation-app/src/models/coffee-shop.model.ts
examples/validation-app/src/sequence.ts
packages/rest/src/__tests__/acceptance/validation/validation.acceptance.ts
packages/rest/src/__tests__/fixtures/models/book.model.ts
packages/rest/src/coercion/coerce-parameter.ts
packages/rest/src/parser.ts
packages/rest/src/providers/parse-params.provider.ts
packages/rest/src/types.ts
packages/rest/src/validation/ajv-factory.provider.ts
packages/rest/src/validation/request-body.validator.ts

The current documentation is missing a crucial piece of information on how to enable custom validation and error messages, added the details.

fix: enable custom AJV validation errors

---

extensions/authentication-jwt/src/__tests__/fixtures/controllers/user.controller.ts

This pull request is to provide the signup method in the authentication-jwt So it would be easier for developers.
https://github.com/strongloop/loopback-next/blob/master/extensions/authentication-jwt/src/__tests__/fixtures/controllers/user.controller.ts

feat(authentication-jwt) Add signup / create user

---

docs/site/Relation-generator.md

connects to https://github.com/strongloop/loopback-next/issues/5836

docs: add hasManyThrough to relation cli page

---

packages/cli/.yo-rc.json
packages/cli/generators/relation/base-relation.generator.js
packages/cli/generators/relation/has-many-through-relation.generator.js
packages/cli/generators/relation/index.js
packages/cli/generators/relation/templates/controller-relation-template-has-many-through.ts.ejs
packages/cli/generators/relation/utils.generator.js
packages/cli/lib/utils.js
packages/cli/snapshots/integration/cli/cli.integration.snapshots.js
packages/cli/snapshots/integration/generators/relation.has-many-through.integration.snapshots.js
packages/cli/test/fixtures/relation/controllers/doctor-patient.controller.ts
packages/cli/test/fixtures/relation/index.js
packages/cli/test/fixtures/relation/models/appointment.model.ts
packages/cli/test/fixtures/relation/models/doctor.model.ts
packages/cli/test/fixtures/relation/models/patient.model.ts
packages/cli/test/fixtures/relation/repositories/appointment.repository.ts
packages/cli/test/fixtures/relation/repositories/doctor.repository.ts
packages/cli/test/fixtures/relation/repositories/patient.repository.ts
packages/cli/test/integration/generators/relation.has-many-through.integration.js
packages/cli/test/unit/utils.unit.js

relates to https://github.com/strongloop/loopback-next/issues/5836
The following could be specified through the cli:
- source, target, and through model. (allow self-through)
- sourceId, targetId on the through model
- relation name
Besides primary key checking, property existence checking, the cli also does:
- the through model won't be the same as source/target model ( they are excluded from the through model list)
- checks if the input sourceId and targetId are the same (cli would not pass)

feat(cli): add hasManyThrough to relation options

---

packages/rest/src/__tests__/integration/rest.server.integration.ts
packages/rest/src/rest.server.ts

The components provided by `server.api()` are not registered as api definition as how controller does. This PR fixes it.

fix(rest): register component for apispec

---

docs/site/Database-migrations.md
docs/site/Model.md

closes https://github.com/strongloop/loopback-next/issues/2197
Recommend to run `npm run docs:prepare` and `npm run docs:start` to review the updated docs

docs: update Model.md

---

packages/cli/generators/project/templates/.eslintignore
packages/eslint-config/eslintrc.js
packages/repository-json-schema/src/__tests__/unit/filter-json-schema.unit.ts
packages/repository/src/mixins/repository.mixin.ts
packages/testlab/src/test-sandbox.ts
tsconfig.build.json

While playing with eslint (https://github.com/strongloop/loopback-next/pull/5590, typescript-eslint/typescript-eslint#1192 and typescript-eslint/typescript-eslint#2094), I realized we don't have to migrate our eslint setup to project references in order to get rid of `createDefaultProgram` & its performance penalty.
In this pull request, I am proposing an alternative improvement and fixing few problems discovered by eslint along the way.
1. Add missing `await` statement to `testlab` code checking if a `.map` file exists when copying `.js` files to sandbox. The problem was discovered by the linter.
2. Update the `tsconfig` file used by `eslint` to include all files we are checking.
3. Remove `createDefaultProgram` flag from the shared/default eslint config (this is a breaking change). …

eslint-config: disable `createDefaultProgram`

---

SECURITY.md
docs/site/sidebars/lb4_sidebar.yml

connects to https://github.com/strongloop/loopback-next/issues/5267

docs: add couchdb2 connector to database connector ref

---

packages/rest/src/__tests__/integration/rest.server.integration.ts
packages/rest/src/__tests__/unit/rest.server/rest.server.open-api-spec.unit.ts
packages/rest/src/rest.server.ts

`RestServer.api()` registers an open api spec with handlers/controller methods. `RestServer.getApiSpec()` populates paths from routes. When a route is added/removed from the server, it triggers recreation of `httpHandler`, which tries to set up routes from `API_SPEC` (which used to be mutated by `RestServer.getApiSpec()`). As a result, some routes does not have `x-operation` or `x-controller-name` and an error is thrown.

fix(rest): skip operations from api spec that matches explicit routes

---

packages/repository/src/__tests__/unit/repositories/legacy-juggler-bridge.unit.ts
packages/repository/src/repositories/legacy-juggler-bridge.ts

This is a follow-up for strongloop/loopback-datasource-juggler#1855 and a part of #3342

feat(repository): add support for non-SQL variants of `Repository.execute()`

---

packages/rest/src/rest.server.ts

connect to https://github.com/strongloop/loopback-next/issues/5756
Display the code block in a readable way:
**Before:**
**After:**
I tried a lot to show them as code, but none of them works. So as a workaround, I reformatted the doc to fix the table display and make it readable.
See explanation in the next comment.

fix(rest): code block in interface apidoc

---

packages/authentication/README.md
packages/authentication/docs/authentication-action.md
packages/rest/README.md

For some reason, we lost the `BREAKING CHANGE` in commit logs to indicate that `@loopback/rest` and `@loopback/authentication` contains breaking changes. This PR marks such changes so that these two packages will be released as new major versions.

feat: mark breaking changes for @loopback/rest and @loopback/authentication

---

packages/context/src/__tests__/unit/binding.unit.ts
packages/context/src/binding.ts
packages/context/src/invocation.ts

This allows parameter injection of current binding using @inject.binding
and configuration of the current binding using @config. For example,
```ts
class GreetingProvider {
static async value(
@inject('user') user: string,
@inject.binding currentBinding: Binding,
@config() cfg: GreetingConfig,
) {
// ...
}
}
```

feat(context): propagate resolution session to dynamic value factory

---

docs/site/Appsody-LoopBack.md
docs/site/Behind-the-scene.md
docs/site/Crafting-LoopBack-4.md
docs/site/Repositories.md
docs/site/Testing-your-application.md
docs/site/migration/auth/authentication.md
docs/site/migration/auth/example.md
docs/site/tutorials/todo-list/todo-list-tutorial-has-one-relation.md
docs/site/tutorials/todo-list/todo-list-tutorial-repository.md
docs/site/tutorials/todo/todo-tutorial-repository.md
packages/cli/generators/repository/index.js
packages/repository/DEVELOPING.md
packages/repository/README.md
packages/repository/src/index.ts

Fixes https://github.com/strongloop/loopback-next/issues/5558
I also renamed it in the CLI.

fix(docs): rename legacy juggler to juggler

---

packages/cli/lib/connectors.json

* Fix IBM i Db2 connector not working with CLI
* Remove schema option (doesn't apply)
* Clean up and simplify settings
Signed-off-by: Mark Irish <mirish@ibm.com>
Fixes #6068 

fix: IBM i Db2 connector

---

packages/express/src/middleware.ts
packages/express/src/types.ts
packages/rest/src/__tests__/acceptance/middleware/middleware-sequence.acceptance.ts
packages/rest/src/__tests__/integration/rest.server.integration.ts
packages/rest/src/rest.application.ts
packages/rest/src/rest.component.ts
packages/rest/src/rest.server.ts
packages/rest/src/sequence.ts

- Optimize middleware based sequence and its middleware providers to be singletons
- MiddlewareSequence is now a singleton and it caches a list of middleware
- Built-in middleware providers are now singletons
- Add the ability to validate sorted middleware groups
- Help our developers troubleshoot misconfigured middleware group orders

feat(rest): optimize and tidy up middleware based sequence

---

packages/repository/src/__tests__/unit/model/define-model-class.unit.ts
packages/repository/src/decorators/metadata.ts
packages/repository/src/define-model-class.ts
packages/rest/src/__tests__/integration/repository.integration.ts

Schema was not generated for Model classes generated by `defineModelClass()`, since it did not contain model definition details. This PR fixes it.
Addresses https://github.com/strongloop/loopback-next/issues/6001.

fix(repository): apply `@model` to generated model class

---

acceptance/repository-mongodb/package.json
acceptance/repository-mongodb/src/__tests__/mongodb-repository-execute.acceptance.ts
acceptance/repository-mongodb/tsconfig.json
acceptance/repository-mysql/package.json
acceptance/repository-mysql/src/__tests__/mysql-repository-execute.acceptance.ts
acceptance/repository-mysql/tsconfig.json
acceptance/repository-postgresql/package.json
acceptance/repository-postgresql/setup.sh
acceptance/repository-postgresql/src/__tests__/postgresql-repository-execute.acceptance.ts
acceptance/repository-postgresql/tsconfig.json
packages/repository-tests/src/crud-test-suite.ts
packages/repository-tests/src/crud/transactions.suite.ts

See #3342
~~WAITING FOR strongloop/loopback-datasource-juggler#1857~~

test: add acceptance-level tests for `repository.execute()`

---

docs/bin/build-preview-site.sh
docs/site/Cassandra-connector.md
docs/site/Cloudant-connector.md
docs/site/DB2-connector.md
docs/site/DB2-for-i-connector.md
docs/site/DB2-for-z-OS-connector.md
docs/site/Example-kv-connector.md
docs/site/Executing-database-commands.md
docs/site/Installing-the-Oracle-connector.md
docs/site/JSON-RPC-connector.md
docs/site/MQLight-connector.md
docs/site/Memory-connector.md
docs/site/MongoDB-connector.md
docs/site/MySQL-connector.md
docs/site/OpenAPI-connector.md
docs/site/Oracle-connector.md
docs/site/PostgreSQL-connector.md
docs/site/REST-connector.md
docs/site/Redis-connector.md
docs/site/SOAP-connector.md
docs/site/SQL-Server-connector.md
docs/site/SQLite3.md
docs/site/Working-with-data.md
docs/site/kv-redis-connector.md
docs/site/sidebars/lb4_sidebar.yml

The first commit adds connector README layout files from loopback.io, the second commit updates docs preview build script to include connector READMEs in the preview site too. These changes together makes it easier to preview connector-related changes via `npm run docs:start`.
The last commit adds a new page `Executing database commands`, see #3342.
I am intentionally not including connector-specific examples, my plan is to add them to individual connector README files.
- Affected example projects in …

Add documentation for executing native database commands

---

docs/site/Component.md
docs/site/Controller.md
docs/site/DataSource.md
docs/site/Interceptors.md
docs/site/Repository.md
docs/site/Route.md
docs/site/Service.md
docs/site/index.md
docs/site/sidebars/lb4_sidebar.yml

connect to https://github.com/strongloop/loopback-next/issues/5776
I renamed the concept items to use the singular terms.
fold subsections:
unfold subsections, part 1:
unfold subsections, part 2:

docs: restructure the concepts page

---

docs/site/Controller.md
docs/site/decorators/Decorators_openapi.md

connect to https://github.com/strongloop/loopback-next/issues/5970
Add guide for specifying `operationId` in the spec

docs: add operationId in spec

---

docs/site/Configuring-datasource.md
docs/site/DataSource.md
docs/site/sidebars/lb4_sidebar.yml
docs/site/tutorials/connectors/Connecting-to-back-end.md

Closes #5961 
Currently, our connector reference sits under "Reference Guides". It's hard to find a specific connector page as the path might be `Reference Guides/Connector reference/Database Connector/MySQL connector/Tutorial`.
Here is a proposal of how to reorganize them into the four quadrants 
keep the current connector reference as is.
add a section or a subpage under "Behind the scene/Datasource" that talk about:
- what is connectors
- what role it plays in req/res cycle, and what relation it has between model and other artifacts (briefly)
- connector types (add links ):
- SQL (transaction), NoSQL (freeform properties)
- Services connectors (service proxy) and others
- (optional) In-memory connector
- (optional) Community connector
add a page "Configuring DataSource"(or a better …

[Spike][Docs] reorganize connector reference into reference, how-to guides, and tutorials

---

packages/rest/src/__tests__/acceptance/coercion/coercion.acceptance.ts
packages/rest/src/coercion/coerce-parameter.ts
packages/rest/src/rest-http-error.ts
packages/rest/src/types.ts
packages/rest/src/validation/request-body.validator.ts

Rework the validation code to use exiting `RestHttpErrors.invalidData` error instead of a custom `BadRequest` error. This way the error object includes the parameter name in the error message & properties and has a machine-readable `code` property.
See also #5808 which introduced parameter coercion.
Surprisingly, all existing tests are passing with my change in place, so I didn't make any changes in the test suite. Please let me know if you think I should write a new test 🤷🏻 
👉 …

feat(rest): improve validation errors for invalid parameter value

---

docs/site/Context-explorer.md
docs/site/Integrating-with-api-connect.md
docs/site/Logging.md
docs/site/Pooling.md
docs/site/sidebars/lb4_sidebar.yml

Add extensions based on discussion in https://github.com/strongloop/loopback-next/pull/6081#discussion_r468262484
newly added extension:
part 1
part2

docs: add extensions

---

packages/authentication/src/__tests__/unit/decorators/authenticate.decorator.unit.ts
packages/authentication/src/__tests__/unit/fixtures/mock-metadata.ts
packages/authentication/src/__tests__/unit/fixtures/mock-strategy.ts
packages/authentication/src/__tests__/unit/providers/auth-metadata.provider.unit.ts
packages/authentication/src/__tests__/unit/providers/auth-strategy.provider.unit.ts
packages/authentication/src/__tests__/unit/providers/authentication.provider.unit.ts
packages/authentication/src/__tests__/unit/types/authentication-metadata-for-strategy.unit.ts
packages/authentication/src/decorators/authenticate.decorator.ts
packages/authentication/src/keys.ts
packages/authentication/src/providers/auth-action.provider.ts
packages/authentication/src/providers/auth-metadata.provider.ts
packages/authentication/src/providers/auth-strategy.provider.ts
packages/authentication/src/types.ts

Resolves #5310 
This change allows to specify multiple strategies, e.g. `@authenticate(['basicAuth', 'localAuth'])`
**Edit:** authenticate decorator signature was updated to `@authenticate('basicAuth', 'localAuth')`
The logic on how the strategies are executed is similiar to how [passportjs](http://www.passportjs.org/) does it.
- The authentication strategies will be executed in the provided order.
- If at least one authentication strategy succeeds, the request will be further processed without throwing an error.
- Once a strategy succeeds or redirects, all subsequent strategies will not be evaluated.
- if all strategies fail, a error will be thrown with the error message of the first provided strategy
- it is not feasible to use multiple strategies that redirect (e.g. oauth login …

feat(authentication): add support for multiple strategies on same method

---

packages/boot/src/__tests__/unit/bootstrapper.unit.ts
packages/boot/src/__tests__/unit/mixins/boot.mixin.unit.ts
packages/boot/src/mixins/boot.mixin.ts

Warns if app is started without booting. Ref: https://github.com/strongloop/loopback-next/issues/6136.

feat: warn if app is started without booting

---

docs/site/Authentication-component-decorator.md
docs/site/decorators/Decorators_authenticate.md

Update auth decorator docs to include multiple strategies. 
This adds docs for PR https://github.com/strongloop/loopback-next/pull/5735

docs: auth decorator with multiple strategies

---

bin/check-package-metadata.js
bin/update-monorepo-file.js

see: https://github.com/strongloop/loopback-next/pull/6155#issuecomment-678593502

fix: monorepo, package metadata scripts' filepath on Windows

---

docs/site/Testing-your-application.md

Fixes https://github.com/strongloop/loopback-next/issues/6178
Application must be booted before changing datasource to test datasource, otherwise it'll be overridden by the real datasource.

fix(docs): change to test db after booting app

---

extensions/authentication-jwt/README.md
extensions/authentication-jwt/src/__tests__/acceptance/jwt.component.test.ts
extensions/authentication-jwt/src/__tests__/fixtures/application.ts
extensions/authentication-jwt/src/__tests__/fixtures/controllers/user.controller.ts
extensions/authentication-jwt/src/__tests__/unit/jwt.service.ts
extensions/authentication-jwt/src/index.ts
extensions/authentication-jwt/src/jwt-authentication-component.ts
extensions/authentication-jwt/src/keys.ts
extensions/authentication-jwt/src/models/index.ts
extensions/authentication-jwt/src/models/refresh-token.model.ts
extensions/authentication-jwt/src/repositories/index.ts
extensions/authentication-jwt/src/repositories/refresh-token.repository.ts
extensions/authentication-jwt/src/services/index.ts
extensions/authentication-jwt/src/services/refreshtoken.service.ts
extensions/authentication-jwt/src/services/user.service.ts
extensions/authentication-jwt/src/types.ts

feature refresh token implemented through  i̶n̶t̶e̶r̶c̶e̶p̶t̶o̶r̶s̶ service
Implements #5187
See also #5046

5187 jwt refresh token Feature

---

docs/site/Interceptor-generator.md
docs/site/LB3-vs-LB4-request-response-cycle.md
docs/site/REST-action-sequence.md
docs/site/REST-middleware-sequence.md
docs/site/migration/models/remoting-hooks.md

Fix the broken links caused by "Interceptors" --> "Interceptor"
Vefified other broken links in https://github.com/strongloop/loopback-next/pull/6085 are already fixed

docs: fix broken link for interceptors

---

packages/rest/src/__tests__/integration/http-handler.integration.ts
packages/rest/src/__tests__/unit/router/controller-route.unit.ts
packages/rest/src/__tests__/unit/router/handler-route.unit.ts
packages/rest/src/__tests__/unit/router/routing-table.unit.ts
packages/rest/src/providers/invoke-method.provider.ts
packages/rest/src/router/base-route.ts
packages/rest/src/router/controller-route.ts
packages/rest/src/router/handler-route.ts
packages/rest/src/router/redirect-route.ts

Improve `RouteEntry.describe()` to be `<verb> <path> => <target handler/controller method>`

feat(rest): improve route description to include verb and path

---

docs/site/Component.md
docs/site/Creating-components.md
docs/site/Extending-LoopBack-4.md
packages/cli/generators/extension/index.js
packages/cli/generators/extension/templates/src/component.ts.ejs
packages/cli/generators/extension/templates/src/index.ts.ejs
packages/cli/generators/extension/templates/src/keys.ts.ejs
packages/cli/generators/extension/templates/src/types.ts.ejs
packages/cli/generators/project/templates/README.md.ejs
packages/core/src/component.ts

Addresses https://github.com/strongloop/loopback-next/issues/5336.

chore: clean up extension generator

---

.vscode/tasks.json

Add a task to build the entire monorepo in a watch mode, where the compiler keeps running in background and recompiles affected files when a change is detected.

build: add "build & watch" task for VSCode

---

docs/site/Creating-components.md
packages/cli/generators/project/templates/package.json.ejs
packages/cli/generators/project/templates/package.plain.json.ejs

> As discussed several times in the past (most recently in [#5927 (comment)](https://github.com/strongloop/loopback-next/pull/5927#discussion_r453727653)), extensions should use framework modules from the target application via `peerDependencies`. 
This PR is a spin-off from #5959 which is becoming too difficult to get landed because of merge conflicts. It brings two commits from the original PR:
- Document the best practice in "Creating components"
- Update CLI template
Please read #5959  for the original discussion around this proposal. We have reached consensus to follow this new direction, so I hope we can get this PR landed quickly. …

Put framework modules to peerDependencies in new extensions

---

docs/site/Life-cycle.md
packages/context/src/value-promise.ts
packages/core/src/__tests__/unit/application-lifecycle.unit.ts
packages/core/src/application.ts

In some cases,  it's desirable to register a single function to be called at start or stop time. For example, when writing integration-level tests, we can use `app.onStop()` to register a cleanup routine to be invoked whenever the application is shut down.
This pull request adds `app.onStart()` and `app.onStop()` methods that can be used to register life-cycle observers as plain functions.

feat: add `app.onStart()` and `app.onStop()` helpers

---

extensions/apiconnect/package.json
extensions/authentication-jwt/package.json
extensions/authentication-passport/package.json
extensions/context-explorer/package.json
extensions/cron/package.json
extensions/health/package.json
extensions/logging/package.json
extensions/metrics/package.json
extensions/pooling/package.json
extensions/typeorm/package.json

> As discussed several times in the past (most recently in [#5927 (comment)](https://github.com/strongloop/loopback-next/pull/5927#discussion_r453727653)), extensions should use framework modules from the target application via `peerDependencies`. 
This PR is a spin-off from #5959 which is becoming too difficult to get landed because of merge conflicts. In this patch, I have updated dependencies in all `extension/*` packages.
Please read #5959  for the original discussion around this proposal. We have reached consensus to follow this new direction, so I hope we can get this PR landed quickly.
Extensions no longer install framework packages as their own dependencies, they use the framework packages provided by the target application instead.
If you are getting `npm …

feat: move framework packages to `peerDependencies`

---

extensions/graphql/package-lock.json
extensions/graphql/package.json
extensions/graphql/src/decorators/index.ts

feat(graphql): use peer dependencies for core and boot

---

docs/site/Accessing-http-request-response.md
docs/site/sidebars/lb4_sidebar.yml
packages/rest/src/__tests__/acceptance/routing/routing.acceptance.ts

feat(docs): add docs to access http request/response objects

---

packages/metadata/src/decorator-factory.ts

This change corrects the rendering of
https://loopback.io/doc/en/lb4/apidocs.metadata.decoratorfactory.html

chore(metadata): fix tsdocs for DecoratorFactory.getTargetName

---

packages/rest/src/__tests__/unit/coercion/paramStringToInteger.unit.ts
packages/rest/src/__tests__/unit/coercion/paramStringToString.unit.ts
packages/rest/src/coercion/coerce-parameter.ts
packages/rest/src/validation/openapi-formats.ts
packages/rest/src/validation/request-body.validator.ts

Fixes https://github.com/strongloop/loopback-next/issues/6247

fix(rest): make sure OpenAPI parameters with simple types are validated by AJV

---

packages/eslint-config/eslintrc.js

Fixes conflicting eslint rules.
`@typescript-eslint/return-await` inserts `await` and then `no-return-await` complains about it.
According to the docs `@typescript-eslint/return-await` supersedes  `no-return-await`.
In my case the conflict happened in the following code
```js
try {
...
} catch {
return await this.findById(id); // <-- both plugins conflict on this line
}
```
See: https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/return-await.md#how-to-use

chore: fix conflicting eslint rules

---

docs/CODE_OF_CONDUCT.md
docs/CONTRIBUTING.md

This PR consists of 1 commit:
- Adopt Contributor Covenant v2
This is to steer the project to be more in-line with the expectations from the FOSS community, thereby increasing ease of adoption and contribution.
Electron, AMP, nvm, Node-RED are examples of Node.js projects that adopt the Contributor Covenant.
- Affected example projects in `examples/*` were …

[RFC] adopt contributor covenant v2

---

docs/site/Booting-an-Application.md
packages/boot/src/__tests__/fixtures/bindable-classes.artifact.ts
packages/boot/src/__tests__/fixtures/service-dynamic-value-provider.artifact.ts
packages/boot/src/__tests__/integration/service.booter.integration.ts
packages/boot/src/booters/service.booter.ts
packages/context/src/binding-inspector.ts
packages/context/src/inject.ts
packages/core/src/application.ts
packages/core/src/service.ts

This PR allows the following classes to be booted from `src/services`.
```ts
import {bind, BindingScope, inject, Provider} from '@loopback/core';
// Dynamic factory provider class
export class DynamicDateProvider {
static value() {
return new Date();
}
}
// With `@inject`
export class ServiceWithConstructorInject {
constructor(@inject('currentUser') private user: string) {}
}
export class ServiceWithPropertyInject {
@inject('currentUser') private user: string;
}
export class ServiceWithMethodInject {
greet(@inject('currentUser') user: string) {
return `Hello, ${user}`;
}
}
```

feat: allow dynamic value provider classes and classes with @inject to be booted

---

packages/repository/src/model.ts

The properties have been added to the types for the configuration of the model and thus have autocompletion in the most modern IDE's

Add types to the model configuration for autocompletion

---

.travis.yml

The CI build with Node 10.x on Travis reports the following issue:
```
$ npm run build
> loopback-next@0.1.0 build /home/travis/build/strongloop/loopback-next
> node packages/build/bin/compile-package -b
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed -
JavaScript heap out of memory
...
The command "npm run build" exited with 0.
```

chore: set NODE_OPTIONS=–max_old_space_size=2048

---

packages/openapi-v3/src/enhancers/spec-enhancer.service.ts
packages/openapi-v3/src/types.ts
packages/rest/src/__tests__/unit/rest.server/rest.server.open-api-spec.unit.ts
packages/rest/src/spec-enhancers/info.spec-enhancer.ts

Fixes #6310 #6215 
The built-in info spec enhancer will only override the `info` section of the OpenAPI spec if the `spec.info` has the default values: 
```ts
{
title: 'LoopBack Application',
version: '1.0.0',
}
```

fix(rest): do not blindly override openapi spec info from package.json

---

examples/graphql/src/__tests__/acceptance/graphql-tests.ts
examples/graphql/src/__tests__/acceptance/graphql.acceptance.ts
examples/graphql/src/application.ts
examples/graphql/src/graphql-resolvers/recipe-resolver.ts
examples/graphql/src/index.ts
extensions/graphql/README.md
extensions/graphql/src/__tests__/unit/graphql.component.unit.ts
extensions/graphql/src/__tests__/unit/graphql.server.unit.ts
extensions/graphql/src/decorators/index.ts
extensions/graphql/src/graphql.component.ts
extensions/graphql/src/graphql.server.ts
extensions/graphql/src/keys.ts
extensions/graphql/src/types.ts

feat: improve graphql configuration and subscriptions

---

docs/site/reference/error-codes.md
packages/context/src/inject.ts
packages/core/src/service.ts
packages/metadata/src/__tests__/unit/inspector.unit.ts
packages/metadata/src/inspector.ts
packages/metadata/src/types.ts
packages/openapi-v3/src/controller-spec.ts
packages/repository-json-schema/src/__tests__/integration/build-schema.integration.ts
packages/repository/src/decorators/model.decorator.ts
packages/repository/src/relations/belongs-to/belongs-to.decorator.ts

- `@loopback/metadata`: Improve the typings for `getDesignTypeForProperty` and `getDesignTypeForMethod` to account for the fact that no metadata may be available when the project is written in pure JavaScript or not enabling TypeScript compiler option `emitDecoratorMetadata`.
- Other packages: Improve the code to handle the case where design-time type metadata is not available.
This work was triggered by a user reporting crash with unhelpful error message when their project did not have `emitDecoratorMetadata` enabled. 
Example error message:
```
Cannot start the application. TypeError: paramTypes is not iterable
at resolveControllerSpec (loopback-next/packages/openapi-v3/dist/controller-spec.js:204:25)
at Object.getControllerSpec …
```

Handle missing design-time type metadata

---

docs/site/reference/error-codes.md

Rework the table into a list of h2 sections. The new format makes it easy to share URLs pointing to individual error codes.
This is a follow-up for #6293.

docs: reorganize error-codes page

---

packages/context/src/interceptor-chain.ts

Fixes tsdoc rendering issue by moving the code block into `@remarks`:

chore(context): fix GenericInterceptor tsdoc generation

---

docs/site/DEVELOPING.md

Add instructions for requiring connectors inside monorepo's example apps.
Thanks for @bajtos 's orginal comments, summarize and add it in the doc.
> In a typical app inside our monorepo, the code loading connectors is executed from loopback-next/packages/repository/node_modules/loopback-datasource-juggler/lib/datasource.js. The connector is installed e.g. in examples/todo/node_modules/loopback-connector-mongodb. (This is caused by the way how lerna installs internal monorepo dependencies.) The solution is to change datasource configuration and replace the connector name ('mongodb') to the connector module (require('loopback-connector-mongodb')). The datasource config file is inside the example project, therefore it looks for the connector in the …

docs: requiring connectors

---

docs/site/BelongsTo-relation.md
docs/site/HasMany-relation.md
docs/site/HasManyThrough-relation.md
docs/site/HasOne-relation.md
docs/site/Relations.md

This _pull request_ adds a short explainer on weak relations to remove ambiguity on how LoopBack 4 handles relations and the caveats with referential integrity.

chore(docs): add weak relations explainer

---

docs/site/HasManyThrough-relation.md
docs/site/Relation-generator.md
packages/cli/generators/relation/has-many-through-relation.generator.js
packages/cli/generators/relation/index.js
packages/cli/snapshots/integration/generators/relation.has-many-through.integration.snapshots.js
packages/cli/test/integration/generators/relation.has-many-through.integration.js
packages/repository-tests/src/crud/relations/acceptance/has-many-through-inclusion-resolver.acceptance.ts
packages/repository-tests/src/crud/relations/fixtures/models/index.ts
packages/repository-tests/src/crud/relations/helpers.ts
packages/repository/src/__tests__/unit/repositories/relations-helpers/flatten-targets-of-one-to-many-relation-helpers.unit.ts
packages/repository/src/relations/has-many/has-many-through-repository.factory.ts
packages/repository/src/relations/has-many/has-many-through.inclusion.resolver.ts
packages/repository/src/relations/relation.helpers.ts

Resolves https://github.com/strongloop/loopback-next/issues/5946.
Similar to the other LoopBack relations, this PR aims to allow the hasManyThrough relation to also support querying related instances by enabling the resolver at the repository level.

feat(repository): implement hasManyThrough resolver

---

packages/http-server/src/__tests__/integration/http-server.integration.ts
packages/http-server/src/http-server.ts

Added options to configure properties that are directly set on `http.Server` and `Server`.
Signed-off-by: Yaapa Hage <hage.yaapa@in.ibm.com>

feat(http-server): configure http.Server and Server properties

---

examples/passport-login/src/authentication-strategy-providers/google.ts

Fixes a problem reported in https://github.com/strongloop/loopback-next/issues/6217

fix(example-passport-login): import options from google oauth2

---

extensions/context-explorer/package.json
extensions/context-explorer/src/__tests__/integration/context-graph.integration.ts
extensions/context-explorer/src/context-graph.ts

Without this fix, the `public` directory is not part of published npm package. And http://[::1]:3000/context-explorer/ reports 404 not found error.

fix(context-explorer): include `public` directory in the npm package

---

packages/cli/generators/project/templates/.mocharc.json
packages/cli/snapshots/integration/generators/app.integration.snapshots.js
packages/cli/test/integration/generators/app.integration.js

Add exit option to mocharc.json template in generator cli.
Ref #2403 
Signed-off-by: Simon Mezzomo <simlt@users.noreply.github.com>

feat(cli): add exit option to mocharc template in generator

---

packages/cli/lib/project-generator.js
packages/cli/test/integration/generators/app.integration.js

Address https://github.com/strongloop/loopback-next/issues/6224.
We should simply lowercase the app name and use it as the dir name, `toFileName()` is best applicable to  "real" files only.

feat(cli): leave numbers in dirname alone

---

.renovaterc.json

This PR configures Renovate Bot to automatically merge PRs if:
1. CI is green
2. It updates to a new patch/minor version or only for devDependencies
See https://docs.renovatebot.com/configuration-options/#automerge

chore: enable renovate automerge for patch/minor versions or devDependencies

---

docs/site/decorators/Decorators_openapi.md
docs/site/extending/rest-api.md
packages/openapi-v3/src/__tests__/unit/decorators/visibility.decorator.unit.ts
packages/openapi-v3/src/controller-spec.ts
packages/openapi-v3/src/decorators/index.ts
packages/openapi-v3/src/decorators/visibility.decorator.ts
packages/openapi-v3/src/keys.ts
packages/openapi-v3/src/types.ts

feat(openapi-v3): add OAS3 visibility decorator

---

docs/site/Binding.md
examples/binding-resolution/src/application.ts
examples/binding-resolution/src/controllers/ping.controller.ts
examples/binding-resolution/src/interceptors/spy.interceptor.ts
examples/binding-resolution/src/keys.ts
examples/binding-resolution/src/middleware/spy.middleware.ts
examples/binding-resolution/src/services/counter.service.ts
examples/binding-resolution/src/services/index.ts
examples/binding-resolution/src/services/logger.service.ts
examples/binding-resolution/src/util.ts
extensions/graphql/src/graphql.container.ts
extensions/graphql/src/graphql.server.ts
packages/context/src/__tests__/unit/binding.unit.ts
packages/context/src/__tests__/unit/context.unit.ts
packages/context/src/binding.ts
packages/context/src/context.ts
packages/context/src/resolver.ts
packages/core/src/application.ts
packages/express/src/express.server.ts
packages/express/src/types.ts
packages/rest/src/rest.server.ts

Implements https://github.com/strongloop/loopback-next/issues/6325
Consider the following context hierarchy: invocationCtx -> requestCtx -> serverCtx -> appCtx, we use `Transient` scope for controllers/services so that each request will get a new instance. But if a controller/service is resolved within the `invocationCtx` (interceptors), a new instance will be created again. Ideally, we should get the same instance at the subtree of the `requestCtx`. Even worse, resolving a binding twice in the same `reqCtx` will get two different instances too.
Neither `Singleton` or `Context` can satisfy this requirement. Typically, controllers/servers are discovered and loaded into the application context. Those from components such as `RestComponent` also contribute bindings to the `appCtx` instead of …

feat(context): introduce new binding scopes

---

docs/site/Building-frontend-angular-application.md
docs/site/sidebars/lb4_sidebar.yml

Add instructions in how to build an Angular application from OpenAPIs coming from LoopBack application. 
Related to https://github.com/strongloop/loopback-next/issues/4849
Local preview:
It's based on my blog:
https://medium.com/@MobileDiana/building-a-frontend-application-with-loopback4-and-angular-e15c6fb48971

feat(docs): add docs for Angular

---

docs/site/Copyright-generator.md
packages/cli/generators/copyright/header.js
packages/cli/generators/copyright/index.js
packages/cli/test/fixtures/copyright/single-package/index.js
packages/cli/test/integration/generators/copyright.integration.js

This allows a `license-header.template` file from the project root directory
to be read as the custom licenese header lines.
It also fixes the header matching regex to avoid duplicate headers.

feat(cli): improve lb4 copyright to accept custom license-header.template

---

docs/site/FAQ.md

This PR is part of a larger initiative to incrementally improve the documentation.

feat(docs): update FAQ

---

extensions/health/README.md

This PR adds a few notes about readiness/liveness probes. I also updated the code example of custom live/ready checks since the database dependency health check was used in the liveness probe which is usually not recommended because not routing traffic to the container is sufficient in this case until the database is healthy again, whereas restarting the container would be unnecessary.

docs(health): add few notes about readiness/liveness probes

---

docs/site/Model.md
examples/passport-login/src/models/user-credentials.model.ts
packages/repository/src/__tests__/unit/decorator/model-and-relation.decorator.unit.ts
packages/repository/src/decorators/model.decorator.ts
packages/repository/src/model.ts

Implements: #6385 
Related to: #1914

feat: add hidden properties

---

packages/rest/src/__tests__/acceptance/coercion/coercion.acceptance.ts
packages/rest/src/coercion/coerce-parameter.ts

PR fixes an issue where by passing only a single query parameter throws an error with code `INVALID_PARAMETER_VALUE` and message `should be array`
Fixes: #6514

fix: allow array query parameter for a single value

---

packages/rest/src/__tests__/integration/rest.server.integration.ts
packages/rest/src/providers/log-error.provider.ts

Change the message from "unhandled error" to "request failed".
The original message was often creating confusion for our users. It seemed like the error was not handled at all, when in fact it was caught by the configured error handler and converted into a proper HTTP error response.
See the discussion in https://github.com/strongloop/strong-error-handler/issues/54 and also https://github.com/strongloop/strong-error-handler/pull/91.

Reword the message printed by REST LogError action

---

docs/site/sidebars/lb4_sidebar.yml

After https://github.com/strongloop/loopback.io/pull/1079 merged. The sidebar will be:
"Extending LoopBack 4" and "Building Applications" are expanded:
Extension point and extensions is moved to concepts

docs: refactor extension sidebar

---

packages/openapi-v3/src/enhancers/spec-enhancer.service.ts

Before this change, `mergeOpenAPISpec` was using auto-inferred return type which was unfortunately `any`.
In this change, I am leveraging generics to get the following behavior:
- If both parameters are partial specs, then the result is a partial  spec too.
- If at least one of the parameters is a full spec, then the result  is a full spec too.
/cc @fennixx

feat(openapi-v3): make `mergeOpenAPISpec` retval strongly typed

---

docs/site/migration/auth/authentication.md

Signed-off-by: Hector Leiva <hector@hectorleiva.com>
There were some links in the migration documentation from Loopback 3 to Loopback 4 that were pointing to files that had moved. This PR is intended to point to the files where they currently reside now to avoid 404's for future users.

docs: updating links for jwt-authentication documentation

---

docs/site/Validation-REST-layer.md

There is a typo in the word "sequence", it was written as "sequnce" at line 183.

Fixes typo in "sequence"

---

docs/site/Setting-debug-strings.md

fix(docs): fix debug string typo

---

docs/site/DEVELOPING.md

Add more detailed steps for previewing the API docs.

docs: add api docs preview guide

---

docs/site/REST-action-sequence.md
docs/site/REST-middleware-sequence.md
docs/site/Using-strong-error-handler.md

Fix 'Handling Errors' link in a few places
in the documentation.
Related to: https://github.com/strongloop/loopback-next/issues/6627 

docs: fix 'handling errors' link in the docs

---

examples/todo-jwt/src/controllers/user.controller.ts

The OpenAPI spec created by the `todo-jwt` example is not valid because of the response object in the `/whoAmI` endpoint in `user.controller.ts`. 

fix(example-todo-jwt): fix response in whoAmI endpoint

---

packages/cli/bin/cli-main.js

Currently `lb4` exits if the Node.js version does not satisfy the range.
This PR relaxes it to be a warning so that developers can still use it
with new releases such as 15.x.

fix(cli): print a warning for Node.js versions that are not supported

---

extensions/health/src/__tests__/acceptance/health.acceptance.ts
extensions/health/src/controllers/health.controller.ts

Fixes https://github.com/strongloop/loopback-next/issues/6647

fix(health): fix http status code for health endpoints

---

packages/repository/src/__tests__/unit/model/model.unit.ts
packages/repository/src/model.ts

this.definition.idName is not a function

---

docs/site/Extending-OpenAPI-specification.md
packages/openapi-v3/src/enhancers/spec-enhancer.service.ts
packages/openapi-v3/src/enhancers/types.ts

Change `modifySpec` to be an async function to allow async spec updates.

feat: make modifySpec async

---

extensions/metrics/README.md
extensions/metrics/src/__tests__/acceptance/metrics.acceptance.ts
extensions/metrics/src/controllers/metrics.controller.ts
extensions/metrics/src/metrics.component.ts
extensions/metrics/src/types.ts

Adds the option to enable the openapi spec which allows to show the metrics endpoint in the API explorer. By default it will be disabled.

feat(metrics): add option to enable/disable openapi spec

---

extensions/health/README.md
extensions/health/src/__tests__/acceptance/health.acceptance.ts
extensions/health/src/controllers/health.controller.ts
extensions/health/src/health.component.ts
extensions/health/src/types.ts

Adds the option to enable the openapi spec which allows to show the endpoints in the API explorer.  By default it will be disabled.

feat(health): add option to enable/disable openapi spec

---

extensions/metrics/src/__tests__/acceptance/metrics-push.acceptance.ts
extensions/metrics/src/__tests__/acceptance/metrics.acceptance.ts
extensions/metrics/src/metrics.component.ts
extensions/metrics/src/types.ts

This PR resolves three issues of the component:
1. The component adds `MetricsPushObserver` even if it is not configured
2. Providing custom config was overwriting whole default config instead of merging

fix(metrics): only add required artifacts to application

---

docs/site/Troubleshooting.md
packages/cli/generators/project/templates/.vscode/launch.json

connect to https://github.com/strongloop/loopback-next/issues/6463
Added "debug mocha test", "debug mocha test in current file", "debug app" in this PR.
For debugging current test, the mocha-current-file is needed. I am thinking, should we move it to `@loopback/build` to avoid duplicate?

feat(cli): add vscode launch tasks in app

---

packages/express/src/providers/invoke-middleware.provider.ts
packages/rest/src/__tests__/acceptance/middleware/middleware-sequence.acceptance.ts
packages/rest/src/__tests__/integration/http-handler.integration.ts
packages/rest/src/__tests__/unit/rest.component.unit.ts
packages/rest/src/__tests__/unit/router/reject.provider.unit.ts
packages/rest/src/providers/find-route.provider.ts
packages/rest/src/providers/invoke-method.provider.ts
packages/rest/src/providers/log-error.provider.ts
packages/rest/src/providers/parse-params.provider.ts
packages/rest/src/providers/reject.provider.ts
packages/rest/src/providers/send.provider.ts
packages/rest/src/rest.component.ts

Optimize actions using static providers.

refactor(rest): use dynamic value provider for actions

---

docs/site/deployment/Deploying-with-pm2-and-nginx.md

Fix an example that mistakenly lists the Node application's port instead of
Nginx's when demonstrating the use of a reverse proxy. Given the original port,
the user would make requests directly to the LoopBack application and not
through the proxy as intended by the example.
Thanks!

fix(docs): fix incorrect port in deployment example

---

packages/metadata/src/__tests__/unit/inspector.unit.ts
packages/metadata/src/inspector.ts

Fixes #6522
after some checks i notice:
```ts
class MyModel {
@propertyDecorator() // with decorator
prop: string;
}
const meta = MetadataInspector.getDesignTypeForProperty(
MyModel.prototype,
'prop',
);
meta // String
---
class MyModel {
@propertyDecorator()
prop: string;
}
const meta = MetadataInspector.getDesignTypeForProperty(
MyModel, // without prototype
'prop',
);
meta // always undefined
---
class MyModel { 
prop: string; // without decorator
}
const meta = MetadataInspector.getDesignTypeForProperty(
MyModel.prototype,
'prop',
);
meta // always undefined
```
so https://github.com/strongloop/loopback-next/blob/master/packages/metadata/src/__tests__/unit/inspector.unit.ts#L680-L687 is a useless tests (because always is gonna be undefined)
and …

fix: getDesignTypeForProperty

---

docs/site/Binding.md
packages/context/src/__tests__/unit/binding.unit.ts
packages/context/src/binding-inspector.ts
packages/context/src/binding.ts

Some developers forget to use `createBindingFromClass` and use `toClass`
or `toProvider` directly. In such cases, the metadata from `@injectable`
are not honored. This shortcut method makes it easy to bind all types of
injectable classes.
```ts
@injectable({scope: BindingScope.SINGLETON, tags: {x: 1}})
class MyInjectableService {
constructor(@inject('msg') private _msg: string) {}
getMessage(): string {
return 'hello ' + this._msg;
}
}
const serviceBinding = ctx
.bind('myService')
.toInjectable(MyInjectableService);
```
Please note that `ctx.bind('myService').toClass(MyInjectableService)` does NOT honor `@injectable`.

feat(context): add binding.toInjectable shortcut

---

examples/todo/src/__tests__/acceptance/test-helper.ts
examples/todo/src/__tests__/acceptance/todo.acceptance.ts
packages/rest/src/__tests__/unit/parse-json.unit.ts
packages/rest/src/body-parsers/body-parser.json.ts
packages/rest/src/coercion/coerce-parameter.ts
packages/rest/src/parse-json.ts
packages/rest/src/parser.ts
packages/rest/src/types.ts

- reject __proto__ and constructor by default
- allow json parse options to provide additional prohibitedKeys

feat(rest): further sanitize json parsing by rejecting prohibited keys

---

docs/site/Creating-artifacts-runtime.md
docs/site/Creating-datasource-runtime.md
docs/site/Creating-model-runtime.md
docs/site/Creating-repository-runtime.md
docs/site/DataSource.md
docs/site/Model.md
docs/site/Repository.md
docs/site/sidebars/lb4_sidebar.yml

Related to https://github.com/strongloop/loopback-next/issues/5783.
There are docs for creating LoopBack artifacts at runtime, so I created a separate how-to sidebar item. 
There are some clean up that's probably needed for the Repository and DataSource page, but i'd keep this PR smaller and for refactoring. 

fix(docs): refactor docs to create artifacts at runtime

---

.github/stale.yml

As we discussed in yesterday's Maintainers Call, I am proposing few changes in our Stale Bot configuration.
The first commit refactors `stale.yaml` to introduce three sections:
- shared config common to both issues and pull requests
- config for issues (kept as is)
- config for pull requests (marking as stale after 60 days, closing after 14 days)
The second commit reduces the time in which an issue is marked as stale from 360 down to 180 days, to match the text in the mark comment ("six months").
@strongloop/loopback-maintainers PTAL.
- Documentation in …

Shorten time before marking issues/PRs as stale

---

docs/site/tutorials/todo-list/todo-list-tutorial-controller.md
docs/site/tutorials/todo-list/todo-list-tutorial-has-one-relation.md
examples/todo-list/src/__tests__/acceptance/home-page.acceptance.ts
examples/todo-list/src/__tests__/acceptance/test-helper.ts
examples/todo-list/src/__tests__/acceptance/todo-list-image.acceptance.ts
examples/todo-list/src/__tests__/acceptance/todo-list.acceptance.ts
examples/todo-list/src/__tests__/acceptance/todo.acceptance.ts
examples/todo-list/src/__tests__/unit/controllers/todo.controller.unit.ts
examples/todo-list/src/application.ts
examples/todo-list/src/controllers/index.ts
examples/todo-list/src/controllers/todo-list-image.controller.ts
examples/todo-list/src/controllers/todo-list-todo-list-image.controller.ts
examples/todo-list/src/controllers/todo-list-todo.controller.ts
examples/todo-list/src/controllers/todo-list.controller.ts
examples/todo-list/src/controllers/todo.controller.ts
examples/todo-list/src/datasources/db.datasource.ts
examples/todo-list/src/datasources/index.ts
examples/todo-list/src/index.ts
examples/todo-list/src/models/index.ts
examples/todo-list/src/models/todo-list-image.model.ts
examples/todo-list/src/models/todo-list.model.ts
examples/todo-list/src/models/todo.model.ts
examples/todo-list/src/repositories/index.ts
examples/todo-list/src/repositories/todo-list-image.repository.ts
examples/todo-list/src/repositories/todo-list.repository.ts
examples/todo-list/src/repositories/todo.repository.ts
examples/todo-list/src/sequence.ts

Update the artifacts of this example
to the latest style generated by the
LoopBack CLI.
Update the documentation to add the
step of adding TodoListImage controller.

update artifacts of the todo-list example to the latest style generated by the LoopBack CLI

---

packages/repository/src/__tests__/unit/repositories/relations-helpers/include-related-models.unit.ts
packages/repository/src/relations/relation.helpers.ts

Fixes https://github.com/strongloop/loopback-next/issues/6741
The code should return 400 instead of 500

fix(repository): invalid inclusion relation name should return error code 400

---

examples/file-transfer/README.md

fix file paths in README.md file in file-transfer example
Signed-off-by: Omar Almalol <omar.alma3lol@gmail.com>

docs: fix incorrect files paths

---

docs/site/Binding.md

supersede https://github.com/strongloop/loopback-next/pull/6783
It seems like note.html doesn't quite work when it's indented. So remove the indentation in the Binding page:
cc @mrfarhadir 

fix(docs): fix formatting in note

---

packages/rest/src/__tests__/integration/rest.server.integration.ts

Github code scan reports the following issue:
Incomplete regular expression for hostnames
Matching a URL or hostname against a regular expression that contains an
unescaped dot as part of the hostname might match more hostnames than
expected.
See https://github.com/strongloop/loopback-next/security/code-scanning/6?query=ref%3Arefs%2Fheads%2Fmaster

fix(rest): fix incomplete hostname in regexp

---

packages/rest/CHANGELOG.md

adding the message change to BREAKING CHANGES, as it might potentially break existing alerting rules based on this message pattern

chore(rest): add message change to BREAKING CHANGES

---

docs/site/tutorials/todo-list/todo-list-tutorial-controller.md

Now that https://github.com/strongloop/loopback-next/issues/2208 is fixed, we can remove the note about the filter not working in API explorer.

fix(docs): remove note about explorer filter not working

---

docs/site/Authorization-component-decision-matrix.md
docs/site/Authorization-component-interceptor.md
docs/site/Authorization-component.md
docs/site/Authorization-overview.md

I noticed that there were a few links in the [Authorization Component](https://loopback.io/doc/en/lb4/Loopback-component-authorization.html) documentation section that were linking to an anchor tag in the same document; but those links were now broken since those sections were moved to separate pages.
Example is: https://loopback.io/doc/en/lb4/Loopback-component-authorization.html | contains a link to the decision matrix (https://loopback.io/doc/en/lb4/Loopback-component-authorization.html#authorization-by-decision-matrix) which doesn't go anywhere since the decision matrix has been updated to exist [here](https://loopback.io/doc/en/lb4/Authorization-component-decision-matrix.html) instead.
Several other links (including links to the decision matrix) were updated as well due to the same …

Update links surrounding the authorization component documentation

---

.travis.yml

Add a new build step to Travis CI configuration to detect `npm@7` and downgrade it to `npm@6` to avoid CI builds getting stuck in `npm install` phase.

build: use `npm@6` when testing Node.js v15

---

docs/site/LoopBack-types.md

Signed-off-by: kursattokpinar <kursattokpinar@gmail.com>
GeoPoint implementation is not completed yet. It'd be better if we add a note to Loopback Types page.
See [Cannot start the application. Error: Unsupported type: geopoint](https://github.com/strongloop/loopback-next/issues/1981)"

docs: add note about current GeoPoint type support

---

docs/site/Interceptor.md

Share a workaround to intercept all requests
re #6099
Signed-off-by: quentin <31855566+QPierre1@users.noreply.github.com>

docs: tip to intercept all queries

---

docs/site/Validation-REST-layer.md

fix(docs): add info on action-based sequences

---

examples/lb3-application/README.md

chore: fix docs formatting

---

docs/site/REST-middleware-sequence.md

fix(docs): add injectable decorator in custom extended sequence

---

.github/workflows/continous-integration.yaml

Improve GitHub Actions configuration to run CI only on pushes to master or pull requests to master.
Specifically, the new configuration does not run CI for pushes to feature branches, to avoid duplicate runs for the same commit: one run for the pull request, another for the feature branch the pull request is from.
See https://github.community/t/how-to-trigger-an-action-on-push-or-pull-request-but-not-both/16662
Note that our Travis CI configuration used to have the same setup.
This is a follow-up for https://github.com/strongloop/loopback-next/pull/5110
- …

ci: run GitHub Actions only for `master` and pull requests

---

extensions/context-explorer/src/__tests__/acceptance/context-explorer.acceptance.ts
extensions/context-explorer/src/__tests__/integration/visualizer.integration.ts

Skip tests that use viz.js to render graph on z/OS, which complain about
```
Runtime error: expected the system to be little-endian!
```
as z/OS is not in little-endian.

test: skip tests that use viz.js on z/OS

---

extensions/metrics/README.md
extensions/metrics/src/__tests__/acceptance/metrics-push.acceptance.ts
extensions/metrics/src/__tests__/acceptance/mock-pushgateway.ts
extensions/metrics/src/observers/metrics.push.observer.ts
extensions/metrics/src/types.ts

Add new options for pushed metrics: job name, grouping key and put/post semantics
Signed-off-by: Lukito Truong <lukito@users.noreply.github.com>

feat(metrics): add new Pushgateway options

---

extensions/authentication-jwt/README.md

Replaced RefreshTokenBindings (incorrect/non-existing namespace) with the correct RefreshTokenServiceBindings

chore: use correct refresh token binding namespace

---

extensions/metrics/README.md
extensions/metrics/src/__tests__/acceptance/metrics.acceptance.ts
extensions/metrics/src/__tests__/acceptance/mock.controller.ts
extensions/metrics/src/interceptors/metrics.interceptor.ts
extensions/metrics/src/metrics.component.ts
extensions/metrics/src/types.ts

This PR adds labels to all method invocation metrics to allow better filtering with PromQL and also improves visualization in Grafana. It is now possible to display the invocations based on method and path e.g. `GET /users` instead of only having the option to use an internal method name (`targetName`) which is still kept for backward compatibility. It is also now possible to create dashboards for error metrics since the status code of the response is now tracked. 
Another feature added by this PR is a new option to configure default labels, this could also be done in the prometheus scrape configuration but this might not always be the best solution, e.g. for setting the app version as a static label. 
- create dashboard and publish to [Grafana …

Additional method invocation labels and option to set default labels

---

extensions/metrics/src/__tests__/acceptance/metrics.acceptance.ts
extensions/metrics/src/interceptors/metrics.interceptor.ts

Fix error thrown by metrics interceptor if invocation source is an
interception proxy and only add targetName label.
Signed-off-by: nflaig <nflaig@protonmail.com>

fix(metrics): fix error thrown by interceptor if invoked by proxy

---

extensions/health/src/controllers/health.controller.ts

Update variable names of openapi definitions to follow naming convention (CONSTANT_CASE)
Signed-off-by: nflaig <nflaig@protonmail.com>

style(health): update variable names of openapi definitions

---

extensions/metrics/src/controllers/metrics.controller.ts
extensions/metrics/src/types.ts

Update variable names of openapi definitions to follow naming convention (CONSTANT_CASE)
Signed-off-by: nflaig <nflaig@protonmail.com>

style(metrics): update variable names of openapi definitions

---

docs/site/REST-middleware-sequence.md
packages/context/src/__tests__/unit/binding-decorator.unit.ts
packages/context/src/binding-inspector.ts

Fixes https://github.com/strongloop/loopback-next/issues/6918
Replaces #6961 and reverts https://github.com/strongloop/loopback-next/pull/6953

fix(context): make sure subclass is used for create binding from class

---

packages/repository/src/connectors/connector.ts

We would like to create new _repostories_ based off _CrudRepositoryImpl_, and would like to introduce the idea of native strong relations and query joins. This is the 1st pull request, which introduces well-defined values for the Connector.interfaces property.
Future pull requests will...
1. Introduce an optional `strong: boolean | 'try'` configuration for _@relation_ decorators, and new "guard code" for `CrudRepositoryImpl` to check and enforce this contract. `DefaultCrudRepository` should immediately reject any relations with `strong: true`.
2. Introduce relation repositories for `CrudRepositoryImpl` that can enforce the "strong relation" contract.
3. Introduce weak relation inclusion resolvers
---
Very Loosely Related: #7019, #4299
Signed-off-by: Rifa Achrinza …

feat: add connector interface enums

---

packages/context/src/__tests__/acceptance/interception-proxy.acceptance.ts
packages/context/src/binding.ts

The provider or dynamic value binding can also return an object that can
be proxied with interceptors.

feat(context): allow asProxyWithInterceptors to be used for non-class bindings

---

extensions/authentication-passport/src/__tests__/unit/passport-strategy-adapter.unit.ts
extensions/authentication-passport/src/strategy-adapter.ts

The `authenticate` method of a `passport` strategy supports options to configure the authentication attempt. This PR adds support for these optional `authenticate` options. Some passport strategies currently require an options object, even if empty, due to missing defaults (e.g. [`passport-saml`](https://github.com/node-saml/passport-saml/blob/master/src/passport-saml/strategy.ts#L42)). While that can be addressed separately for each strategy, the changes in this PR allow the consumer to handle that case for all similarly affected strategies.

fix: support options in passport auth strategies

---

docs/site/Inside-Loopback-Application.md

Signed-off-by: ddsultan <2477698+ddsultan@users.noreply.github.com>

docs(site): fix link path to 'JWT Service'

---

packages/rest-explorer/README.md
packages/rest-explorer/package-lock.json
packages/rest-explorer/src/__tests__/acceptance/rest-explorer.acceptance.ts
packages/rest-explorer/src/__tests__/fixtures/index.html.ejs
packages/rest-explorer/src/rest-explorer.controller.ts
packages/rest-explorer/src/rest-explorer.types.ts

customizing the explorer index.html.ejs gives full control
over the swagger-ui  options, appearance and functionality
Signed-off-by: kyle-apex <kyle.hoskins@apexbpm.com>

feat: add explorer indexTemplatePath customization

---

packages/authorization/src/__tests__/unit/authorize-decorator.test.ts
packages/authorization/src/decorators/authorize.ts

The current implementation does not populete all attributes of the spec
from `@authorize` decorated for the subclass.

fix(authorization): allow `@authorize.skip` and other metadata for subclasses

---

extensions/graphql/src/graphql.container.ts
packages/express/src/types.ts

Signed-off-by: Matthew Schnee <i.am@matthew.engineer>
The middleware chain is bound in context by using the Symbol `import { MIDDLEWARE_CONTEXT } from '@loopback/rest`;
However, `@loopback/graphql` was creating a different `MIDDLEWARE_CONTEXT`, and `LoopBackCountainer` was using a default context instead, because `Symbol.for('name') !== Symbol('name')`.  This could be caused due to order of imports.
Given a system that already has a lot of services expecting `@inject(SecurityBindings.CURRENT_USER)`, and a desire to use inject these services and providers into a `GraphQLResolver`, we need to verify and bind the CurrentUser ourselves:
```ts
// in Application.ts
this.bind(GraphQLBindings.GRAPHQL_CONTEXT_RESOLVER).to(async (graphQLCtx) => {
// we need to get the request Context from the given …
```

fix: use Symbol.for() for MIDDLEWARE_CONTEXT 

---

docs/site/tutorials/todo-list/todo-list-tutorial-relations.md

fix interface name in tutorial from TodoRelations to TodoListRelations
Signed-off-by: gkraska <gkraska@poczta.onet.pl>

fix(examples): typo in interface name

---

docs/site/Context.md

Signed-off-by: ddsultan <2477698+ddsultan@users.noreply.github.com>
Fix URL link to 'Promise micro-task queue' in Concepts/Context to improve developer (reading) experience

docs(context): fix URL link to 'Promise micro-task queue'

---

packages/cli/generators/project/templates/package.json.ejs
packages/cli/generators/project/templates/package.plain.json.ejs

Generating a lb4 extension does not include the `rebuild` script in the package.json file but it is called by the `pretest` script
`"pretest": "npm run rebuild"`

fix(cli): add rebuild script to package.json of extensions

---

docs/bin/build-jekyll-preview-config.js

Reported by @mrmodise. 
When running `npm run docs:prepare`, there's an error:
```
Reading Jekyll config from _loopback.io/_config.yml
...../loopback-next/docs/node_modules/js-yaml/index.js:10
throw new Error('Function yaml.' + from + ' is removed in js-yaml 4. ' +
^
Error: Function yaml.safeLoad is removed in js-yaml 4. Use yaml.load instead, which is now safe by default.
```
Switching to use `yaml.load` in the `bin/build-jekyll-preview-config.js` as suggested by the error seems to fix the problem.

docs: fix breaking change from js-yaml

---

packages/cli/test/integration/generators/copyright.integration.js

Rework the assertions in `lb4 copyright` tests to verify the entire content of the `LICENSE` file generated, not just isolated substrings.
There is no change in CLI functionality, I am only updating the test to better describe the current behavior.
See also https://github.com/strongloop/loopback-next/pull/7107

test(cli): use a more strict check license text

---

.github/workflows/continuous-integration.yaml

I have seen that the command for the `commit-lint` job compares it from the `master` branch therefore it makes no sense to compare `master` with `master`

[CI] do only commit-lint job for PR

---

packages/cli/test/acceptance/app-run.acceptance.js

The tests for npm are being ignored in a no ci environment and yet for yarn no. This fixes this situation.
https://github.com/strongloop/loopback-next/blob/6f074ce3d08a2e8ee54ca201668a123c757a96ff/packages/cli/test/acceptance/app-run.acceptance.js#L31

test(cli): ignore yarn tests in a non-ci environment

---

packages/openapi-v3/src/__tests__/integration/controller-spec.integration.ts
packages/openapi-v3/src/controller-spec.ts
packages/openapi-v3/src/decorators/parameter.decorator.ts
packages/openapi-v3/src/decorators/request-body.decorator.ts
packages/rest/src/parser.ts

See https://github.com/strongloop/loopback-next/discussions/7224. The
relative index should be used instead of the absolute index to insert
body to parameter list.

fix(rest): fix the request body index handling

---

packages/cli/test/integration/generators/copyright-git.integration.js
packages/cli/test/integration/generators/copyright-monorepo.integration.js

The MacOS worker is often timing out, let's increase the value to avoid such test failures.
Example PRs that failed with a timeout: 
- #7284 (see https://github.com/strongloop/loopback-next/pull/7284/checks?check_run_id=2149908320)

test(cli): increase timeout to avoid GitHub Actions failures

---

docs/site/Using-openapi-to-graphql.md

Signed-off-by: Javier Zapata <javierzapata82@gmail.com>
The mutation name provided by the guide was wrong. I updated it.

fix(docs): fix mutation name in openapi-to-graphql how-to guide

---

docs/MAINTAINING.md

As part of our effort to make LoopBack an _open_ open source project, we would like to open up the process of nominating new maintainers. 🎉 
In the past, it was up to the core team at IBM to watch for non-trivial contributions and nominate their authors. Let's open this process to all maintainers, both from IBM and the community.
@strongloop/loopback-maintainers Please review the propsal in the markdown file I am editing and let me know if you agree/disagree with the proposed process, where to add more details or which parts to clarify.
**UPDATE 2021-03-26:** I moved the description of the nomination process to https://github.com/strongloop/loopback-governance/pull/8.
- Affected …

docs: how to nominate a new maintainer

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
MAINTAINING.md

Certain files such as `CONTRIBUTING.md` are expected at the root directory of the repository. Due to how the documentation's architecture is set-up, these files are hidden away under `docs/`, which may make it difficult to discover.
This pull request aims to reduce the discovery friction by creating a symbolic link of the original files into the root directory. This has the benefits of keeping future git history on those files consistent, and keeping the same maintenance overhead for changes to those files (as they're symlinks).
- API Documentation in code was …

chore: symlink common docs files to root

---

docs/site/Authentication-component-options.md
packages/authentication/src/__tests__/unit/providers/authentication.provider.unit.ts
packages/authentication/src/providers/auth-action.provider.ts
packages/authentication/src/types.ts

BREAKING CHANGE: The current code allows a strategy to throw an error but
it only fails the authentication process if other ones either skip or fail.
This behavior does not allow a strategy to abort the process. With this PR,
a strategy can decide how to proceed as follows:
1. Return normal user profile or redirect to finish the authentication
2. Return undefined/null to continue with next one
3. Throw an error to abort the process

feat: allow one strategy to fail the authentication process

---

.vscode/settings.json

This pull request is broken down into 2 commits:
1. Enable ESLint vscode extension as a formatter
Previously, the ESLint vscode extension was using its own `onSave` hook to engage formatting. This led to a clash with vscode's built-in TypeScript formatter, which led to issues ranging minor formatting inconsistencies during save to a completely broken TypeScript file.
This commit switches ESLint away from the custom `onSave` hook to vscode's built-in "default formatter" system for JavaScript/TypeScirpt files.
2. Enforce a consistent EOL character sequence
Windows-based installations of vscode may inadvertently use `\r\n` when creating a new file. This commit enforces a consistent behavior across vscode installations. 
- Code …

monorepo: fix eslint vscode formatter; enforce consistent eol vscode

---

packages/cli/generators/openapi/spec-helper.js
packages/cli/test/unit/openapi/spec-helper.unit.js

fixes #3417
In the long-term, we should be providing a better experience by allowing the users to manually set the method name on the spot.
This is an interim solution to resolve a long-standing issue.

fix: cli openapi generator op name inference

---

docs/site/migration/auth/migration-auth-access-control-example.md

Signed-off-by: Hector Leiva <hector@hectorleiva.com>
Updating some of the links within the `docs/site/migration/auth/migration-auth-access-control-example.md` to point to the new location of the files.

docs: update broken links in auth-access-control-example

---

packages/boot/README.md

Signed-off-by: Fengyuhe heyufeng8080@gmail.com
Updating ServiceBooter options(dirs and extensions) default value.

docs: correct ServiceBooter Options in README

---

packages/context/src/__tests__/acceptance/interception-proxy.acceptance.ts
packages/context/src/binding.ts

A binding can be resolved with asProxyWithInterceptors. Before this fix,
if a singleton binding is first resolved with asProxyWithInterceptors = true,
sesquential resolutions will always get the proxy even with asProxyWithInterceptors
= false. This PR fixes the issue by caching the non-proxy value.

fix(context): ensure non-proxy value is cached for bindings

---

packages/cli/generators/project/templates/package.plain.json.ejs

Generating a project (`lb4 app`) without enabling the `loopbackBuild` feature produces an invalid `package.json` with the following errors:
- duplicated `main` field (should be `types` for the second one) - introduced by #5440 ([diff](https://github.com/strongloop/loopback-next/commit/c3f048428f85eb1adcddc63b111db3286486339b#diff-4c3a2bc38d294c673194936e9f09b56f39a09b8db26eaa3313a57c1283088105R10))
- incorrect `types` path (should be `dist/index.d.ts`) - introduced by #5440 ([diff](https://github.com/strongloop/loopback-next/commit/c3f048428f85eb1adcddc63b111db3286486339b#diff-4c3a2bc38d294c673194936e9f09b56f39a09b8db26eaa3313a57c1283088105R10))
- `services` feature not handled (missing dependency) - missing in #1649
- `repositories` flag not handled (always enabled) - missing in #1649
- …

fix(cli): invalid package.plain.json.ejs template

---

docs/site/Database-migrations.md
packages/repository/src/__tests__/unit/mixins/repository.mixin.unit.ts
packages/repository/src/mixins/repository.mixin.ts

Signed-off-by: Mario Estrada <marioestradarosa@yahoo.com>
Developers have been asking a way to make a **DataSource** _readonly_ when migrating the database schema on certain environments. For a non-breaking change the property ```disableMigration``` is introduced that can be specified in the **DataSource** _configuration_, which behaves in the way it does currently if not specified or if set to false, so only when set to true it will skip that datasource when running the migrate script or when auto-migrate.
It can work together with the ```process.env.NODE_ENV``` in order to seamlessly achieve the readonly mode (not migrate flag).  The reason why I did not followed the pattern of models: property in the ```migrateSchemaoptions``` is because it is really easier to work along with the …

feat: adds support for disableMigration on repository mixin

---

docs/site/Inside-Loopback-Application.md

I noticed that the UserController has been moved/renamed to UserManagementController in the shopping application but the docs is outdated. This commit fixes the broken links and name references to the UserManagementController.

Fixes broken links and naming for UserController

---

.github/workflows/continuous-integration.yml
packages/cli/test/acceptance/app-run.acceptance.js

follow the [PR#7520](https://github.com/strongloop/loopback-next/pull/7520) I just want to make sure the lifecycle of the npm run synchronous, to make sure `npm run pretest`
run before `npm test`. I also add the script clean to ci, to reduce unknown bug.
Signed-off-by: Dat Pham <dat.pham@popsww.com>

ci: clean up before build and fix the tests for npm v7

---

packages/context/src/__tests__/acceptance/interception-proxy.acceptance.ts
packages/context/src/interception-proxy.ts

Ensures the following method to keep its parameter types:
`greet(name: string): string` => greet(name: string): ValueOrPromise<string>`

feat: improve TypeScript typing for AsyncProxy

---

packages/context/src/resolution-session.ts

The main point of this PR is changes in `packages/context/src/resolution-session.ts`.
The original code contains some complexity: 
1. Internal method `enterBinding` violates "the single concern" principle: it ensures that ResolutionSession exists or created, and also it is concerned with tracking resolution status. 
2. The code failed to express the intent that entering and leaving binding must happen just before action started and right after it is done. 
3. The same thing happens with `injection`-related methods
So I managed to get rid of private method, and without changing public interface managed to rewrite runWith- methods in sane way. Now runWithBinding looks this way:
```typescript
class  ResolutionSession {
// .....skipped....
static runWithBinding(
action: ResolutionAction, …
```

Some refactoring of ResolutionSession that makes module implementation very semantic and concise

---

packages/repository/src/mixins/repository.mixin.ts

This PR places back the imports needed inside repository mixin, which by mistake were removed in the allow migration false commit: https://github.com/strongloop/loopback-next/commit/65719e96f9289d956bf69001d4f1b6ca3cd27cb3
Signed-off-by: Mario Estrada <marioestradarosa@yahoo.com>

fix: imports core and context in repository mixin

---

packages/rest-explorer/README.md
packages/rest-explorer/src/__tests__/acceptance/rest-explorer.acceptance.ts
packages/rest-explorer/src/rest-explorer.controller.ts
packages/rest-explorer/src/rest-explorer.types.ts
packages/rest-explorer/templates/index.html.ejs

Signed-off-by: mrmodise <modisemorebodi@gmail.com>
In this change, I propose enabling customizing the RestExplorer title via RestExplorer configuration

refactor(rest-explorer): use indexTitle when available

---

packages/cli/lib/connectors.json

Signed-off-by: Mario Estrada <marioestradarosa@yahoo.com>
Current the `lb4 datasource` -> `grpc` is forcing the installation of `loopback-connector-grpc` version ^1.3.x, however the latest version is ^2.0.0 . Also it is not asking for two important properties `host` and `port` number in the cli wizard. 
I have created the [gRPC client example](https://github.com/marioestradarosa/loopback-grpc-client-example) with the version ^2.0.0 which I had to update manually and is working fine. 

feat(cli): updates loopback-connector-grpc

---

docs/site/DEVELOPING.md

Signed-off-by: Thanakrit Lee <thanakrit.lee.2014@gmail.com>
Fix minor typo in documentation.

docs: fix doc typo

---

.mocharc.js

The macOS tests are timing out every 5-10 runs. Increasing the timeout to monitor for improvements.

test: increase timeout

---

packages/openapi-v3/src/__tests__/unit/decorators/response.decorator.unit.ts
packages/openapi-v3/src/build-responses-from-metadata.ts

If a class is decorated with `@model` but not extending `Model`, it is not
honored by `@response` currently.

fix(openapi-v3): allow classes decorated with `@model` as response model

---

packages/repository-json-schema/src/__tests__/unit/build-schema.unit.ts
packages/repository-json-schema/src/build-schema.ts

If we have a Sub model that extends from Base, and we call
getJsonSchemaRef(Base) before getJsonSchemaRef(Sub), the base schema
is returned as we have base json schema cached at the base class.
This PR makes sure each class has its own cache for json schema.

fix: make sure json schema ref is built correctly for the subclass

---

packages/context/src/__tests__/unit/context-view.unit.ts
packages/context/src/context-view.ts
packages/context/src/context.ts
packages/context/src/inject.ts
packages/core/src/__tests__/acceptance/extension-point.acceptance.ts
packages/core/src/extension-point.ts
packages/rest/src/__tests__/unit/rest.server/rest.server.unit.ts

This PR allows resolution options to be set on ContextView and related injectors. The main use case is to allow extension point
to receive a list of proxies for extensions.

feat: allow context view to return proxies

---

extensions/socketio/src/index.ts

Allow user to use types without install socket.io dependency on own project.
Signed-off-by: Matteo Padovano <mrbatista@users.noreply.github.com>

chore: export socketio types

---

packages/security/src/__tests__/unit/principal.unit.ts

Found a minor typo in the tests while browsing the source code.

test: fix `principal` typo

---

packages/core/src/__tests__/unit/application-lifecycle.unit.ts
packages/core/src/application.ts

Some applications create resources during `init()` and `stop()` does not
clean up such resources at the moment.

fix: allow application.stop() to release release resources from init()

---

.github/workflows/continuous-integration.yml
examples/webpack/src/__tests__/integration/bundle-node.integration.ts

see: https://github.com/loopbackio/cicd/issues/4

ci: default to Node.js v16

---

packages/repository-json-schema/src/__tests__/unit/build-schema.unit.ts
packages/repository-json-schema/src/build-schema.ts

Signed-off-by: Simon Stone <Simon.Stone@docusign.com>
Fixes #8121 
This change stops `modelToJsonSchema` cascading the `exclude` list when building a JSON schema for the specified model. The exclude list is now treated the same as other properties such as `partial`, `includeRelations` and `title`.
Note that the exclude list is typed as a key of the model passed into `modelToJsonSchema`, so it makes sense that the exclude list is only for excluding properties of that model.

fix: do not cascade exclude list when building json schema

---

docs/site/tutorials/todo/todo-tutorial-model.md

It's line is not displayed when the property is required

Remove code sample line

---

packages/rest/src/__tests__/acceptance/validation/validation.acceptance.ts
packages/rest/src/validation/request-body.validator.ts

Signed-off-by: Jakub Mifek <jakub.mifek@lutherx.com>
Fix for request body validation. In previous versions of loopback (we have skipped some), it was possible to define optional request body (which is acceptable by openapi). However, after update on the latest version, we experienced an issue with incoming request validation.
The body can be defined as optional and the parser correctly parses the body as undefined, however, the body is then passed to AJV for validation purposes together with schema of the expected object. Since undefined is not an object, the validator returns an error. This is, because, the required property for request bodies is not included in the schema of the body - but in the schema of the operation.
This single line of code checks whether the body is required and …

fix: validation error on empty optional request body

---

docs/site/Setting-debug-strings.md

Add missing documentation on how to add debug in your own code.
Related to discussion: https://github.com/loopbackio/loopback-next/discussions/8315
Also fixed documentation, missing space in sentence

docs: Add documentation on how to add debug in your own code #8315

---

README.md
SECURITY.md
docs/CODE_OF_CONDUCT.md

We got the 2 email aliases from OpenJS Foundation for reporting, instead of using an IBM email address. 🎉 
Updating the corresponding docs in this repo to reflect this change.

docs: update email addresses for reporting

---

packages/cli/generators/model/index.js
packages/cli/test/integration/generators/model.integration.js

You can now provide properties in the model config file in this format.
```sh
{
"name": "product",
"base": "Entity",
"properties": {
"id": {
"type": "string",
"id": true,
"generated": true,
"required": true
},
"name": {
"type": "string",
"required": true,
"default": "xyz"
}
}
}
```
Fixes #7404 

feat(cli): model generator can now pick properties from config file

---

packages/cli/generators/controller/index.js
packages/cli/generators/datasource/index.js
packages/cli/generators/discover/index.js
packages/cli/generators/example/index.js
packages/cli/generators/extension/index.js
packages/cli/generators/openapi/index.js
packages/cli/generators/repository/index.js
packages/cli/lib/artifact-generator.js

The arguments that are provided in commands like —datasource=postgres and in the config file are treated as the same. Both of them end in the options object of the generator class. Whenever we want to ask a prompt, we check if, for that argument, there is already a value present in the options object. If there is, we assign that value to the respective property in the artifact info object and skip that prompt.
However, for some of the arguments in multiple generators, this check for a value in the options object was missing. I have added all the missing checks and tested them. They now work with both command-line arguments and config files.
Include references to all related GitHub issues and other pull requests, for example:
Fixes #8072 
Fixes #7404 
Fixes #7362 
Fixes #7361 
Fixed #8089

Fixes in CLI using -c config feature. 

---

docs/site/Polymorphic-relations.md

The title and permalink in the document head was mistakenly set as HasManyThrough relation. Just a minor fix.

docs: Fix polymorphic relations documentation

---

package-lock.json
package.json
packages/eslint-config/package-lock.json
packages/eslint-config/package.json

This reverts commit c7557d0a1439d097c3af58f7b41a57628f7967d7.
Reason: https://github.com/lo1tuma/eslint-plugin-mocha/issues/322
If the lint is run with Node v17 or greater, it fails

revert: update dependency eslint-plugin-mocha to ^10.0.4

---

packages/openapi-v3/src/__tests__/unit/decorators/response.decorator.unit.ts
packages/openapi-v3/src/controller-spec.ts

fix: security spec is removed when using @response decorator

---

extensions/typeorm/package-lock.json
extensions/typeorm/package.json
extensions/typeorm/src/__tests__/fixtures/controllers/book.controller.ts

It will be released shortly. The methods used for the connection are obsolete but they offer support until version 0.4, so it will be marked as a breaking change to change them later

feat!: update dependency typeorm to ^0.3.x

---

docs/site/Discovering-models.md
packages/cli/.yo-rc.json
packages/cli/generators/discover/index.js
packages/cli/snapshots/integration/cli/cli.integration.snapshots.js
packages/cli/snapshots/integration/generators/discover.integration.snapshots.js
packages/cli/test/integration/generators/discover.integration.js

Added a new parameter in the discover command `optionalId'. It defaults to false and if set to true, it does not mark `id` of generated models as required.
Fixes #8572

feat(cli): add option to mark id field as not required in discover command

---

docs/site/Discovering-models.md
packages/cli/.yo-rc.json
packages/cli/generators/discover/index.js
packages/cli/generators/model/templates/model.ts.ejs
packages/cli/snapshots/integration/cli/cli.integration.snapshots.js

Added a new option in `discover` CLI command `relations`. If true, relations are discovered from the datasource and added to models. Relations are discovered by settings `associations` property in `modelMaker.discoverSingleModel ` options to true. Then we map the discovered relations onto the `properties` object and also created arrays for relation and destination model imports. Because discover generator uses model generator's `model.ts.ejs` template file. we have updated this template file to include relation imports and property relations.

feat(cli): add option to create relations in cli discover command

---

.github/workflows/continuous-integration.yml
.prettierignore
appveyor.yml
package.json

Tests cannot be seen when they fail due to Fake-TTY

use FakeTTY only for CLI tests

---

docs/site/Repository-generator.md

fix in docs in repository generator from "specifyng" to "specifying"

fix(docs): documentation fix of for repository generator

---

docs/site/LB3-vs-LB4-request-response-cycle.md
docs/site/Testing-your-application.md
docs/site/decorators/Decorators_openapi.md
packages/repository/src/repositories/legacy-juggler-bridge.ts

fix in docs for typo from "overriden" to "overridden"

fix(docs): documentation fix of for overridden text

---

docs/site/Include-filter.md
packages/filter/src/query.ts
packages/repository/src/relations/relation.helpers.ts

fix in docs for typo from "compatability" to "compatibility" in "Include Filter" "Query" and "Relation.helpers" files

fix(docs): documentation typo fix in filters query and relation

---

docs/site/Repository-generator.md

fix in docs for typo from "infered" to "inferred"

fix(docs): documentation fix for infered text in repository generator

---

docs/site/Dynamic-models-repositories-controllers.md

fix in docs of dynamic models for typo from "folowed" to "followed"

fix(docs): fix in docs of dynamic models for typo

---

docs/site/DEVELOPING.md

fix in docs of crafting loopback for typo from incompatibilites to incompatibilities

fix(docs): fix in docs of crafting loopback for typo

---

docs/site/Polymorphic-relation.md

fix in docs for typo from "creater" to "creator"

fix(docs): documentation fix for creater text in polymorphic relation

---

docs/site/LB3-vs-LB4-request-response-cycle.md
docs/site/Repository-generator.md
docs/site/Request-response-cycle.md
packages/rest-crud/README.md

fix in docs for typo from "respositories" to "repositories"

fix(docs): fix in docs of dynamic models for typo respositories

---

docs/site/Crafting-LoopBack-4.md

fix in docs of crafting loopback for typo "extensibile" to "extensible"

fix(docs): fix in docs of crafting loopback for extensible typo

---

docs/site/Request-response-cycle.md

documentation typo fix in from "implemenation" to "implementation"

fix(docs): documentation fix in req response cycle

---

docs/site/decorators/Decorators_openapi.md
docs/site/tutorials/core/11-summary.md

documentation typo fix in from "extention" to "extension"

fix(docs): documentation typo fix from extention to extension

---

docs/site/Serving-static-files.md

documentation typo fix in from "drectories" to "directories"

fix(docs): documentation fix in service static files

---

docs/site/migration/auth/passport.md

documentation typo fix from "authorizaton" to "authorization"

fix(docs): passport documentation fix for typo

---

docs/site/tutorials/core/3-context-in-action.md

documentation typo update for recevies to receives

fix(docs): documentation typo update for recevies

---

docs/site/tutorials/core/3-context-in-action.md

fix document typo from moreved to removed

fix(docs): fix document typo from moreved to removed

---

docs/site/deployment/Deploy-for-GDPR-readiness.md

documentation typo fix in from "stablized" to "stabilized"

fix(docs): documentation fix in deployment docs

---

packages/build/README.md

update build documentation for spelling mistake explicity to explicitly

fix(docs): update build documentation for spelling mistake

---

packages/repository-json-schema/src/__tests__/unit/filter-json-schema.unit.ts
packages/repository-json-schema/src/filter-json-schema.ts

This PR will restrict the relations in openapi spec by using enum.

feat(cli): enumerate relations in openapispec relation object

---

packages/cli/lib/version-helper.js

fix #9144
Signed-off-by: Yesha  Mavani <yesha.mavani@sourcefuse.com>
Please provide a high-level description of the changes made by your pull request.
The lb4 update command does not update the peer dependencies 
while showing the list of which all packages it will update, it lists the peer dependencies but while updating it misses those
There was a minor issue due to which it wasn't updating it as it was trying to change the devDependencies again instead of peerDependencies. 
Include references to all related GitHub issues and other pull requests, for example:
Fixes #9144 

fix(cli): made changes so update comamnd updates the peerDependencies as well

---

docs/site/BelongsTo-relation.md

The way the default foreign key for a belongsTo relation is being generated [here](https://github.com/loopbackio/loopback-next/blob/6c73ca1037659315f17184c0325f64efe9398e98/packages/cli/generators/relation/index.js#L542) is different than mentioned in the docs. I have changed the docs according to the code.

docs: update standard for foreign key name in belongs to relation

---

docs/site/Discovering-models.md
packages/cli/.yo-rc.json
packages/cli/generators/discover/index.js
packages/cli/snapshots/integration/cli/cli.integration.snapshots.js
packages/cli/test/integration/generators/discover.integration.js

This PR adds an option to lb4 discover command. --models is an option to pass models that lb4 discover should create without prompt.
The actual PR is [here](https://github.com/loopbackio/loopback-next/pull/8612). This PR is a copy of the same PR. The reason to create another PR is to move things forward and allow merging the changes to the master. The original PR has been active for a while from the PR creator.
Actual credit for the changes goes to the original PR creator.

feat(cli): specify models with --models in lb4 discover

---

packages/cli/generators/model/property-definition.js
packages/cli/test/unit/discover/import-discovered-model.test.js

Currently, discovering models that have a field with BLOB type fails the build with an error. 
```
npm run build
> binaryissue@0.0.1 build
> lb-tsc
src/models/amounts.model.ts:69:11 - error TS2304: Cannot find name 'Binary'.
69   image?: Binary;
~~~~~~
src/models/amounts.model.ts:69:11 - error TS4031: Public property 'image' of exported class has or is using private name 'Binary'.
69   image?: Binary;
~~~~~~
Found 2 errors in the same file, starting at: src/models/amounts.model.ts:69
```
This happens due to the fact that lb4 doesn't handle Binary type. This PR intends to fix this issue and provides support for the BLOB type.
There was [PR](https://github.com/loopbackio/loopback-next/pull/6476) a while ago which was closed without merge. This PR continues that PR and has added a test for …

feat(cli): binary support for blob type

---

packages/cli/generators/relation/templates/controller-relation-template-belongs-to.ts.ejs
packages/cli/snapshots/integration/generators/relation.belongs-to.integration.snapshots.js

In case of a belongsTo relation, the openAPI docs show `array` in the responses for the route: 
`/sourceModel/:{targetId}/targetModel`. (e.g: /orders/1/customer. 
The target instance will always be a single record in case of belongsTo relation. Hence the type should be object. This PR changes the type in the response (in openAPI docs) from `array` to `object`.
There is one thing though, the actual response of the API is actually an object - not an array.

fix(cli): response type from array to object in belongsTo

---

packages/cli/generators/relation/base-relation.generator.js
packages/cli/generators/relation/belongs-to-relation.generator.js
packages/cli/generators/relation/templates/controller-relation-template-belongs-to.ts.ejs
packages/cli/generators/relation/utils.generator.js
packages/cli/snapshots/integration/generators/relation.belongs-to.integration.snapshots.js
packages/cli/test/fixtures/relation/controllers/employee.controller.ts
packages/cli/test/fixtures/relation/index.js
packages/cli/test/fixtures/relation/models/employee.model.ts
packages/cli/test/fixtures/relation/repositories/employee.repository.ts
packages/cli/test/integration/generators/relation.belongs-to.integration.js

This PR will allow belongsTo relations with the same table.
Currently creating relations with the same table results in buggy code.

fix(cli): allow belongsTo relation with same table

---

packages/cli/generators/repository/templates/src/repositories/repository-kv-template.ts.ejs
packages/cli/test/integration/generators/repository.integration.js

If we create a repository for a kv-based datasource, the repository class is supposed to extend DefaultKeyValueRepository but currently, if we run `lb4 repository` and select kv-based DS  & the model, the resulting code is buggy. 
This PR would allow the creation of correct code for kv based repository.

fix(cli): extend from DefaultKeyValueRepository in case of kv datasource

---

extensions/sequelize/README.md
extensions/sequelize/src/__tests__/unit/sequelize.datasource.unit.ts
extensions/sequelize/src/sequelize/connector-mapping.ts
extensions/sequelize/src/sequelize/sequelize.datasource.base.ts

For mysql, postgresql and oracle dialects.

feat(sequelize): add connection pooling support

---

packages/cli/.yo-rc.json
packages/cli/generators/relation/index.js
packages/cli/intl/en/messages.json
packages/cli/snapshots/integration/cli/cli.integration.snapshots.js

Current --help response for relation has a bit confusing description for foreignKeyName. I've updated the text to be clearer.

fix(cli): update --help for relation

---

packages/cli/generators/relation/index.js
packages/cli/snapshots/integration/generators/relation.has-many-through.integration.snapshots.js
packages/cli/test/integration/generators/relation.has-many-through.integration.js

`lb4 relation` with --config fails to recognize `sourceKeyOnThrough` & `targetKeyOnThrough`. This PR fixes that.

fix: add missing keys from config passed to lb4 relation

---

packages/cli/generators/relation/templates/controller-relation-template-has-many-through.ts.ejs
packages/cli/snapshots/integration/generators/relation.has-many-through.integration.snapshots.js
packages/cli/test/fixtures/relation/controllers/user-user.controller.ts
packages/cli/test/fixtures/relation/index.js
packages/cli/test/fixtures/relation/models/friend.model.ts
packages/cli/test/fixtures/relation/models/user.model.ts
packages/cli/test/fixtures/relation/repositories/friend.repository.ts
packages/cli/test/fixtures/relation/repositories/user.repository.ts
packages/cli/test/integration/generators/relation.has-many-through.integration.js

Running `lb4 relation` for hasManyThrough relation having same source & target models results in buggy controller code. (duplicate import of models due to source & target being identical). This PR fixes that.

fix: remove repeated import from controller for same table relation for hasManyThrough

---

packages/cli/.yo-rc.json
packages/cli/generators/repository/index.js
packages/cli/snapshots/integration/cli/cli.integration.snapshots.js
packages/cli/test/integration/generators/repository.integration.js

Currently, the lb4 repository fails to set repositoryBaseClass based on provided option in the configs. This PR will enable the lb4 repository to update the repositoryBaseClass with the value provided in the configs.

fix: enable the lb4 repository accept repositoryBaseClass option

---

packages/cli/generators/relation/index.js
packages/cli/snapshots/integration/generators/relation.belongs-to.integration.snapshots.js
packages/cli/test/integration/generators/relation.belongs-to.integration.js

lb4 relation with --config fails to recognize `registerInclusionResolver` and asks even if it is provided in the --config. This PR fixes that.

enable lb4 relation recognize registerInclusionResolver passed in --config

---

.github/workflows/continuous-integration.yml

⚠️ The CLI tests will be removed. Once they have been tested, they will be reinstated.

ci improvements

---

docs/site/Component.md

Added Sequelize extension in component.md and fixed a broken link.

docs: add `@loopback/sequelize` in official components

---

extensions/sequelize/src/__tests__/fixtures/models/test.model.ts
extensions/sequelize/src/__tests__/integration/repository.integration.ts
extensions/sequelize/src/sequelize/sequelize.repository.base.ts

Now picking up table name from the name parameter in `@model` decorator if specified. Or fallback to lowercase when using postgres dialect to match loopback connector's behaviour.
Fixes [loopback4-sequelize#34](https://github.com/sourcefuse/loopback4-sequelize/issues/34)

fix(sequelize): get table name dynamically

---

extensions/sequelize/src/__tests__/integration/repository.integration.ts
extensions/sequelize/src/sequelize/sequelize.repository.base.ts

Adds check if the include filter contains invalid value (the one that is not present in the inclusion resolver of that repository).
Fixes #9635

fix(sequelize): handle invalid inclusion filter

---

extensions/sequelize/src/__tests__/integration/repository.integration.ts
extensions/sequelize/src/sequelize/sequelize.repository.base.ts

Removes remapping of thrown errors by Sequelize models.
Fixes #9626

fix(sequelize): preserve error context

---

extensions/sequelize/src/__tests__/fixtures/models/developer.model.ts
extensions/sequelize/src/__tests__/fixtures/models/programming-language.model.ts
extensions/sequelize/src/__tests__/fixtures/models/user.model.ts
extensions/sequelize/src/__tests__/integration/repository.integration.ts
extensions/sequelize/src/sequelize/sequelize.repository.base.ts

Previously, the package used a custom `excludeHiddenProps` function to exclude hidden fields. But that prevented users from accessing those fields on backend too. With this change, we now defer to the LoopBack Model's built-in toJSON method, which already handles the exclusion of hidden properties when serializing data for response.
See: https://github.com/sourcefuse/loopback4-sequelize/issues/37

fix(sequelize): defer to `toJSON` for hidden property exclusion

---

packages/cli/generators/discover/index.js
packages/cli/snapshots/integration/generators/discover.integration.snapshots.js
packages/cli/test/fixtures/discover/mem.datasource.js.txt
packages/cli/test/integration/generators/discover.integration.js

Running `lb4 discover` with the `relations` flag generates buggy code for the hasManyThrough relation.
```
src/models/appointment.model.ts:1:45 - error TS2300: Duplicate identifier 'belongsTo'.
1 import {Entity, model, property, belongsTo, belongsTo} from '@loopback/repository';
```
This is happening due to duplicate imports [here](https://github.com/loopbackio/loopback-next/blob/master/packages/cli/generators/discover/index.js#L386). This PR fixes that by adding a check.

fix: check for existing relationImports

---

extensions/sequelize/src/__tests__/fixtures/controllers/index.ts
extensions/sequelize/src/__tests__/fixtures/controllers/task.controller.ts
extensions/sequelize/src/__tests__/fixtures/models/index.ts
extensions/sequelize/src/__tests__/fixtures/models/task.model.ts
extensions/sequelize/src/__tests__/fixtures/repositories/index.ts
extensions/sequelize/src/__tests__/fixtures/repositories/task.repository.ts
extensions/sequelize/src/__tests__/integration/repository.integration.ts
extensions/sequelize/src/sequelize/sequelize.repository.base.ts

`@loopback/sequelize`: Added support for `defaultFn` property with overridable registry of aliases.
The default registry includes existing ones that juggler provides such as uuid, now, shortid etc.
Fixes #9597

feat(sequelize): add `defaultFn` support

---

package-lock.json
packages/cli/package.json

fix: pin ts-query to 5.x as 6.x breaks cli tests on macos

---

README.md

LB3 support ended quite some time ago,
so this note is no longer needed / just leads
to more reading

fix(docs): update README on LB3 support

---

docs/site/migration/mounting-lb3app.md

There either needs to be no fil extension, or a .html file extension .md doesn't work
When rendered .md would take you to:
https://loopback.io/doc/en/lb4/Getting-started.md

fix(docs): Fix migration link to Getting-started page

---

docs/site/Getting-started.md

Displaying the standard input with round brackets might lead inexperienced developers to enter and
create a directory with round brackets. For clarity and consistency, the round brackets have been
removed from directory input.

docs: clarify in delete round brackets for input

---

packages/openapi-v3/src/decorators/request-body.decorator.ts

Fixes #9791
Fixes the `requestBody.array` example.

docs: fix requestBody.array JsDoc example

---

packages/context/src/binding-inspector.ts
packages/core/src/__tests__/unit/application.unit.ts

The current code mutates base class during calculation of the subclass binding metadata template. This causes issues for 
the following examples:
```ts
@injectable({scope: BindingScope.SINGLETON})
class BaseService {}
class SubService extends BaseService {}
const templates = getBindingMetadata(BaseService)?.templates;
app.service(BaseService, {
defaultScope: BindingScope.SINGLETON,
});
app.service(SubService, {
defaultScope: BindingScope.SINGLETON,
});
```
`app.service(SubService...` changes the metadata of `BaseService` due to in-place push of new items to the templates array.

fix: fix binding templates for base classes

---

extensions/sequelize/src/__tests__/fixtures/models/todo.model.ts
extensions/sequelize/src/__tests__/integration/repository.integration.ts
extensions/sequelize/src/sequelize/sequelize.repository.base.ts

NOTE: This is an updated PR on top of https://github.com/loopbackio/loopback-next/pull/9926 which was originally authored by @KalleV . 
Belongsto relation definition was not picking the right key for id. It was reproducible if there are multiple entries in the foreign table. 
Used keyFrom to handle the issue. 
Fixes #9591 
See also https://github.com/loopbackio/loopback-next/pull/9926
Co-author: @KalleV

fix(sequelize): use keyFrom as foreign key for belongsto relation definition

---

packages/repository-json-schema/src/__tests__/integration/build-schema.integration.ts
packages/repository-json-schema/src/__tests__/unit/build-schema.unit.ts
packages/repository-json-schema/src/build-schema.ts

fix: map type buffer & binary to string in open api specs

---

extensions/sequelize/package.json

Exclude test sandbox temp directory from the NPM publish.
Fixes: #10173
Tested fix with`npm pack`:

fix(sequelize): exclude test environment from NPM publish

---

packages/repository-json-schema/src/__tests__/integration/build-schema.integration.ts
packages/repository-json-schema/src/build-schema.ts

Provide foreign key in openapi specification in case of a relation. 

feat: show foreign key in openapi specs

---

extensions/sequelize/src/__tests__/fixtures/controllers/index.ts
extensions/sequelize/src/__tests__/fixtures/controllers/scoped-task.controller.ts
extensions/sequelize/src/__tests__/fixtures/models/index.ts
extensions/sequelize/src/__tests__/fixtures/models/scoped-task.model.ts
extensions/sequelize/src/__tests__/fixtures/repositories/index.ts
extensions/sequelize/src/__tests__/fixtures/repositories/scoped-task.repository.ts
extensions/sequelize/src/__tests__/integration/repository.integration.ts
extensions/sequelize/src/sequelize/sequelize.repository.base.ts

Add support for [Model settings scope](https://loopback.io/doc/en/lb4/Model.html#scope) when using the Sequelize ORM instead of Juggler.
Fixes #10169

fix(sequelize): support "defaultScope" via Model settings

---

packages/cli/lib/base-generator.js

Running `lb4 discover` with `--config` option causes it to get stuck. The lb4 discover works fine with other options like  `--dataSource` & `--schema` but it gets stuck when we run it with `--config`. The discoverer successfully generates the models but doesn't terminate. 
This PR fixes that

fix: add process.exit for generators

---

packages/cli/generators/discover/index.js
packages/cli/test/unit/discover/import-discovered-model.test.js

`lb4 discover` doesn't handle enum properly. This PR implements [this](https://loopback.io/doc/en/lb4/Model.html#enum-property) workaround for the enum in `lb4 discover`.
Related GitHub issues & PRs:
PR https://github.com/loopbackio/loopback-connector-mysql/pull/525

fix: handle enum

---

packages/repository/src/relations/belongs-to/belongs-to.repository.ts
packages/repository/src/relations/has-many/has-many-through.repository.ts
packages/repository/src/relations/has-one/has-one.inclusion-resolver.ts
packages/repository/src/relations/has-one/has-one.repository.ts

The `options` object will often have a `transaction`, which contains database connection resources that must not be cloned.
Fixes #10194
Introduced by #8026
Signed-off-by: Matthew Gabeler-Lee <mgabeler-lee@6river.com>

fix(repository): use a shallow clone for applying polymorphism to options

---

extensions/sequelize/src/sequelize/sequelize.repository.base.ts
extensions/sequelize/src/types.ts

Partial fix for: #10193
This resolves Typescript errors such as the following when trying to use the new property with a repository call using "find", "findOne", "findById":
```ts
Type '{ relation: string; scope: { where: { id: number; }; }; required: true; }'
is not assignable to type 'InclusionFilter'.
Object literal may only specify known properties, and 'required'
does not exist in type 'Inclusion'.
53           required: true
```
Reference:
https://loopback.io/pages/en/lb4/readmes/loopback-next/extensions/sequelize/

fix(sequelize): extend Inclusion interface with "required" property

---

extensions/sequelize/src/__tests__/integration/repository.integration.ts
extensions/sequelize/src/sequelize/sequelize.repository.base.ts

Ignore the "order" field if it is an empty string for backward-compatible behavior with the Loopback Juggler ORM.
Fixes #10275

fix(sequelize): resolves SQL error when order filter is an empty string

---

extensions/sequelize/src/__tests__/integration/repository.integration.ts
extensions/sequelize/src/sequelize/sequelize.repository.base.ts
extensions/sequelize/src/sequelize/utils.ts

Cast entity columns with type "boolean" from strings to boolean values in the Loopback 4 Where Filter to Sequelize operation translation layer.
This addresses a backward compatibility issue with the Juggler ORM for `Where` filter values passed in from REST API calls.
Fixes #10149

fix(sequelize): add type coercion for booleans in the Where filter

---

extensions/sequelize/package.json
extensions/sequelize/src/__tests__/fixtures/observers/index.ts
extensions/sequelize/src/__tests__/fixtures/observers/test.observer.ts
extensions/sequelize/src/__tests__/integration/repository.integration.ts
extensions/sequelize/src/sequelize/sequelize.datasource.base.ts
package-lock.json

This resolves initialization errors in Loopback 4 observers attempting to use repositories extending the Sequelize CRUD repository on start up.
Adds dev dependency for "oracledb" to address this test error:
```
parses pool options for oracle:
Error: Please install oracledb package manually
at OracleConnectionManager._loadDialectModule (node_modules/sequelize/src/dialects/abstract/connection-manager.js:81:15)
at new OracleConnectionManager (node_modules/sequelize/src/dialects/oracle/connection-manager.js:28:21)
at new OracleDialect (node_modules/sequelize/src/dialects/oracle/index.js:17:30)
at new Sequelize (node_modules/sequelize/src/sequelize.js:368:20)
at new SequelizeDataSource (extensions/sequelize/src/sequelize/sequelize.datasource.base.ts:9:34)
at Context.<anonymous> …
```

fix(sequelize): init Sequelize instance in constructor

---

extensions/sequelize/src/__tests__/fixtures/controllers/index.ts
extensions/sequelize/src/__tests__/fixtures/controllers/roles.controller.ts
extensions/sequelize/src/__tests__/fixtures/models/index.ts
extensions/sequelize/src/__tests__/fixtures/models/roles.model.ts
extensions/sequelize/src/__tests__/fixtures/repositories/index.ts
extensions/sequelize/src/__tests__/fixtures/repositories/roles.repository.ts
extensions/sequelize/src/__tests__/integration/repository.integration.ts
extensions/sequelize/src/sequelize/operator-translation.ts
extensions/sequelize/src/sequelize/sequelize.repository.base.ts
packages/filter/src/query.ts

postgres supports extended operators but missing in sequelize
fix #10272
**Please provide a high-level description of the changes made by your pull request.**
postgres supports extended operators but missing in sequelize
added the supported operators 
also the array field was by default given integer[] type even if it was string[].
added to condition to check before giving a default value.
Include references to all related GitHub issues and other pull requests, for example:
Fixes #10272
Example app to test - https://github.com/yeshamavani/sequelize

fix(sequelize): add support for extended operators in sequelize

---

extensions/sequelize/src/__tests__/integration/repository.integration.ts
extensions/sequelize/src/sequelize/sequelize.datasource.base.ts

modified regex to match select query with parenthesis
fix #10312

fix(sequelize): modified regex to match select query with parenthesis

---

.gitignore
extensions/sequelize/src/__tests__/integration/repository.integration.ts
extensions/sequelize/src/sequelize/sequelize.repository.base.ts

"MySQL 'updateById' triggers 'entity not found' due to 0 affected rows."
An 'entity not found' error is triggered during the execution of 'updateById' on a MySQL connector. This behavior is attributed to MySQL's practice of reporting 0 affected rows when no changes are made, as outlined in the MySQL C API documentation (https://dev.mysql.com/doc/c-api/8.3/en/mysql-affected-rows.html).
Fixes: [#9618](https://github.com/loopbackio/loopback-next/issues/9618)

For for MySQL connector on UpdateById when an existing entity update lead to Entity Not Found errors

---

packages/cli/generators/relation/templates/controller-relation-template-has-one.ts.ejs
packages/cli/test/integration/generators/relation.has-one.integration.js

Generating a hasOne relation with lb4 relations with the same table generates buggy code as it add imports for both source & target models are same. This PR fixes that.

fix: enable lb4 relation generate relation with same table

---

extensions/sequelize/src/__tests__/fixtures/models/user.model.ts
extensions/sequelize/src/__tests__/integration/repository.integration.ts
extensions/sequelize/src/sequelize/sequelize.datasource.base.ts
extensions/sequelize/src/sequelize/sequelize.repository.base.ts

By parsing the values to JSON objects, provide backward compatibility for JSON and Array entity properties when using dialects like MySQL, MariaDB, or SQLite.
Fixes: #9629
Fixes: #9598

fix(sequelize): parse JSON columns to objects for mysql dialect

---

packages/build/bin/compile-package.js

On Windows resources aren't copied to the dist directory.
This is because `glob` changed the behavior of file resolving on version 9 and now uses `\` instead of `/`. 
This commit joins the paths to be cross-platform compatible.

fix(build): correctly join file paths on windows when copying resources

---

docs/site/Model.md

The [docs for Property Decorator](https://loopback.io/doc/en/lb4/Model.html#property-decorator) mentions that the index is a boolean type. But it can have an object like `index: {unique: true}`  to apply a particular index. This PR fixes the document and adds the required details.

docs: mention another possible type of index attribute (object)

---

packages/repository/src/__tests__/unit/repositories/relations-helpers/resolve-has-many-through-metadata.unit.ts
packages/repository/src/relations/has-many/has-many-through.inclusion-resolver.ts

This pull request addresses an issue where MongoDB ID was causing problems in hasManyThrough relations. The solution implemented attempts conversion to a string type using the toString() function for both related and entity IDs. If the [toString()](https://www.mongodb.com/docs/manual/reference/method/ObjectId.toString/) function does not exist, the ID is used as it is. This ensures consistency in ID types, allowing the [intersection](https://github.com/loopbackio/loopback-next/blob/4407b5a040a9cde22c434d798a3450f0d122664b/packages/repository/src/relations/has-many/has-many-through.inclusion-resolver.ts#L270) function to work correctly.
Fixes #10259 

fix: correct MongoDB ID conversion in hasManyThrough relations

---

docs/site/Repository-generator.md

Fix incorrect directory name for base repository classes
fix #10611

docs(docs): fix incorrect directory name for base repository classes

---

packages/cli/test/integration/generators/discover.integration.js

fix: update variable names to standard

---

packages/cli/generators/app/templates/src/index.ts.ejs

If process.env.HOST is undefined or null the default HOST would be '127.0.0.1'

feat: add a condition on process.env.HOST

---

docs/site/Discovering-models.md
packages/cli/.yo-rc.json
packages/cli/generators/discover/index.js
packages/cli/snapshots/integration/cli/cli.integration.snapshots.js
packages/cli/snapshots/integration/generators/discover.integration.snapshots.js
packages/cli/test/integration/generators/discover.integration.js

The `lb4 discoverer` names the argument to pass datasource as "dataSource". This PR makes the argument consistent with the `lb4 datasource` without breaking existing cli command 'lb4 dataSource'.

change dataSource to datasource

---

packages/repository-json-schema/src/__tests__/unit/build-schema.unit.ts
packages/repository-json-schema/src/build-schema.ts

Openapi specs provide an option `readOnly` to show if a field is supposed to be generated and not provided in request data. This PR adds `readOnly: true` to a model property in openapi specs that is `generated: true`.

fix: show readonly in openapi spec of model property if it is generated

---

packages/cli/generators/datasource/index.js
packages/cli/generators/openapi/index.js
packages/cli/generators/rest-crud/index.js
packages/cli/generators/service/index.js

Some of the generators install dependencies like rest-crud (installs @loopback/rest-curd), service (installs @loopback/service) or openapi generator (installs loopback-connector-openapi). 
Before installing those dependencies, they see if the dependency is installed by looking at `packageJson.dependencies` (`packageJson` from yeoman-generator) - which always results in false as `packageJson` has no [property named](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/yeoman-generator/index.d.ts#L378) `dependencies`. 
Yeoman-generator's `packageJson` has no direct way to access dependencies from package.json file.
Hence the dependency is always installed even if it already exists.
This PR fixes that by properly accessing the dependencies with …

fix: fix accessing dependencies from yeoman's packageJson

---

packages/cli/generators/relation/has-one-relation.generator.js

The PR I created to fix hasOne relation with the same table [here](https://github.com/loopbackio/loopback-next/pull/10214) wasn't complete. Sorry about that.
This PR adds the remaining changes.

fix: fix hasOne relation with the same table

---

packages/cli/generators/datasource/index.js
packages/cli/snapshots/integration/generators/datasource.integration.snapshots.js
packages/cli/test/integration/generators/datasource.integration.js

While generating a datasource based on the REST connector, the generator works fine with prompts. But it fails to work with --config option.
The connector fails to parse the incoming option that has object type (`options` and `operations` option) as the `config` has already been parsed at [`base-generator.js`](https://github.com/loopbackio/loopback-next/blob/master/packages/cli/lib/base-generator.js#L187).
The following works:
```
lb4 datasource 
? Datasource name: rest
? Select the connector for rest:  REST services (supported by StrongLoop)
? Base URL for the REST service: /sample
? Default options for the request: {"headers":{"Accept":"application/json","Content-Type":"application/json"}}
? An array of operation templates: []
? Use default CRUD mapping: No
```
But passing the same …

fix: add condition to check type of property before parsing from json

---

extensions/socketio/src/socketio.server.ts

Currently the `npm run lint` failed with the following error which blocks the release of loopback-next modules
```
../loopback-next/extensions/socketio/src/socketio.server.ts
239:7  error  Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the `void` operator
```
This PR fixes the lint error.

fix: fix lint error

---

bin/create-package.js

Updates internal monorepo package creator to use `npm install` instead of `lerna bootstrap`.
This fix prevents the following error:
```
node ./bin/create-package.js packages/model
...
ERR! bootstrap The "bootstrap" command was removed by default in v7, and is no longer maintained.
ERR! bootstrap Learn more about this change at https://lerna.js.org/docs/legacy-package-management
Command aborts (code 1 signal null): npx "lerna" "bootstrap" "--scope" "@loopback/model".
Error: Process 1192 exits with code 1 signal null
at ChildProcess.<anonymous> (/home/user/Documents/git-repos/loopbackio/loopback-next/bin/create-package.js:61:11)
at ChildProcess.emit (node:events:519:28)
at ChildProcess._handle.onexit (node:internal/child_process:294:12)
```
- New tests added or existing tests modified to …

fix(monorepo): creating packages post-Lerna@7

---

extensions/sequelize/src/__tests__/fixtures/controllers/user-todo-list.controller.ts
extensions/sequelize/src/__tests__/fixtures/models/patient.model.ts
extensions/sequelize/src/__tests__/fixtures/models/todo-list.model.ts
extensions/sequelize/src/__tests__/fixtures/models/user.model.ts
extensions/sequelize/src/__tests__/fixtures/repositories/todo-list.repository.ts
extensions/sequelize/src/__tests__/integration/repository.integration.ts
extensions/sequelize/src/sequelize/sequelize.repository.base.ts

Resolves bug with hidden property configuration when using the Sequelize ORM and querying nested relations.
Fixes: https://github.com/loopbackio/loopback-next/issues/10495

fix(sequelize): ensure nested relations follow hidden property configuration from Loopback entities

---

examples/access-control-migration/package.json
examples/todo-jwt/package.json
extensions/authentication-jwt/package.json

According to [the documentation](https://www.npmjs.com/package/%40types/bcryptjs), `@types/bcryptjs` is no longer needed. 
Also, there's CI failure in https://github.com/loopbackio/loopback-next/pull/10909 that's related to `bcryptjs`. I'm trying to see if removing this will fix the issue. 

fix: remove @types/bcryptjs

---

packages/cli/lib/cli.js

When trying to publish the release for the LB4 modules, I got the following error: 
```
/somepath/loopback-next/packages/cli/lib/cli.js:208
for (const arg of gen._arguments) {
^
TypeError: gen._arguments is not iterable
at main (/somepath/loopback-next/packages/cli/lib/cli.js:208:29)
at Object.<anonymous> (/somepath/loopback-next/packages/cli/bin/cli-main.js:66:1)
at Module._compile (node:internal/modules/cjs/loader:1469:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
at Module.load (node:internal/modules/cjs/loader:1288:32)
at Module._load (node:internal/modules/cjs/loader:1104:12)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:173:12)
at node:internal/main/run_main_module:28:49
``` …

fix: fix release issue in cli.js

---

package-lock.json
packages/cli/package.json

Reverting changes in PR https://github.com/loopbackio/loopback-next/pull/10895. 
When running `npm run release`, it complained about: 
```
const link = require('terminal-link');
^
Error [ERR_REQUIRE_ESM]: require() of ES Module
```
After I reverted `terminal-link` version to 2.x, I was able to run the following command (which is part of the release command):
npm exec -c "cross-env LANG=en bin/cli-main.js --meta" -w @loopback/cli

fix: revert terminal-link version

---

examples/graphql/package.json
examples/graphql/src/__tests__/acceptance/graphql-context.acceptance.ts
examples/graphql/src/__tests__/acceptance/graphql-subscription.acceptance.ts
examples/graphql/src/application.ts
extensions/graphql/package.json
extensions/graphql/src/__tests__/integration/export-graphql-spec.integration.ts
extensions/graphql/src/__tests__/unit/graphql.server.unit.ts
extensions/graphql/src/booters/resolver.booter.ts
extensions/graphql/src/graphql.container.ts
extensions/graphql/src/graphql.server.ts
extensions/graphql/src/index.ts
extensions/graphql/src/keys.ts
extensions/graphql/src/types.ts
package-lock.json

Currently, the GraphQL extension leverages Apollo Server 3 that is officially deprecated, with end-of-life scheduled for 22 October 2024. This PR migrates the extension to Apollo Server version 4.
Additionally, it introduces support for GraphQL subscriptions using `graphql-ws` library.

feat(graphql): migrate to apollo server 4

---

README.md

The current LB4 EOL date aligned with Node.js 20 EOL date, according to the [Node.js release schedule](https://github.com/nodejs/Release). This PR updates LB4 EOL to align with Node.js 24 date. 
I also removed the FB link on README because that page is no longer being maintained.

chore: update LB4 EOL date

---

packages/security/package.json

A follow up PR from PR #11018 . When updating the `peerDependencies`, I didn't realize the one in `@loopback/security` was not saved. I checked all the peerDependencies in the package.json files, it should be the last one 🤞 . 

fix: fix the last peerDependencies

---

packages/cli/generators/controller/index.js
packages/cli/test/integration/generators/controller.integration.js

fix #10494
Fix controller failure when --controllerType=BASIC is explicitly specified

fix: fix CLI execution with explicit --controllerType=BASIC option

---

SECURITY.md

👋 Hi everyone! We’re @UlisesGascon and @RafaelGSS, working with the OpenJS Foundation as part of [the Alpha-Omega initiative](https://openjsf.org/blog/openjs-security-checkpoint-2025-so-far). Our focus is supporting OpenJS projects in strengthening their security posture. We can help with things like:
- Reviewing or creating security documentation (e.g., SECURITY.md, incident response plans...)
- Supporting vulnerability handling and escalation (reporting, triage, CVEs, disputes)
- Reviewing repo configurations and GitHub security settings
- Sharing best practices (e.g., OSSF Scorecard)
- Answering general questions on licenses, compliance, or incident response
:sparkles: We’re here as a resource for the LoopBack team and happy to collaborate on whatever is most useful for you. Looking …

docs: add security escalation policy
